### ISSUE TITLE
"Uncaught Error: [HMR] Hot Module Replacement is disabled." appearing when adding special entry point

### ISSUE THREAD

**Issue by jdan** [webpack/webpack#1151] opened 2015-06-09 21:12 UTC
I'm using webpack for [tota11y](http://khan.github.io/tota11y) and absolutely loving it, but I keep running into a problem with HMR and my config.

Following the instructions at http://webpack.github.io/docs/webpack-dev-server.html#hot-mode, I've added `webpack/hot/dev-server` as an entry point. Running

```
webpack-dev-server --hot
```

Everything works as expected, but the problem comes when I build with `webpack -p`. In doing so, I get the following error when running my bundle in a browser:

```
Uncaught Error: [HMR] Hot Module Replacement is disabled.
```

Grepping through my bundle I can see that error message, but why is this hot reloading code in my bundle?

I've since removed that bit from the entry field in my config, and hot reloading seems to work fine. So I remain a bit confused: do I not actually need `webpack/hot/dev-server` in my config? Are the docs outdated?

I checked around for this error but couldn't find anything, so perhaps my problem runs deeper than that.

**Comment by sokra** [comment] 2015-06-15 08:04
The docs are wrong... :cry:

Just use `webpack-dev-server --hot --inline` and don't anything special about webpack-dev-server or HMR to your webpack.config.js.

**Comment by artemist** [comment] 2015-06-22 18:32
I'm getting this error as well.

**Comment by sloria** [comment] 2015-07-14 00:28
I am seeing this error as well. Passing `--hot --inline` to the command line fixes it.

**Comment by jdan** [comment] 2015-07-19 15:25
Thank you @sokra, that worked. Sorry for not updating here!

I'm going to keep this open until a maintainer closes it, hopefully the docs will be updated soon. I would do it myself but I don't know enough about HMR.

**Comment by chrisdrackett** [comment] 2015-08-11 19:48
I'm getting the same, I had:

``` javascript
  devServer: {
    hot: true,
    inline: true
  }
```

in my `webpage.config.js` and was getting errors when running `webpack-dev-server`. However, running `webpack-dev-server --hot --inline` makes everything work as expected.

**Comment by lubosz** [comment] 2015-09-05 11:50
I have following in the config:
```
  devServer: {
    contentBase: "./src/www",
    noInfo: true,
    hot: true,
    inline: true
  }
```

The browser shows following log:
```
bundle.js:117 Uncaught Error: [HMR] Hot Module Replacement is disabled.
webpack-dev-server.js:1 [WDS] Hot Module Replacement enabled.
```

Running `webpack-dev-server` with `--hot --inline` does also not help.

**Comment by patgod85** [comment] 2015-09-09 07:01
I have the same issue as @lubosz

**Comment by sokra** [comment] 2015-09-09 07:10
`Hot Module Replacement is disabled.` means the `HotModuleReplacementPlugin` is not used.

`--hot` adds it. (because the CLI have access to your webpack configuration)

`hot: true` doesn't add it. (because the API doesn't have access to your webpack configuration)

**Comment by mailaneel** [comment] 2015-12-08 06:49
You have to push ```new webpack.HotModuleReplacementPlugin()``` this into your plugins config, webpack-dev-server when used with nodejs api do not add it automatically
```
var config = require('webpack.config');
config.plugins.push(new webpack.HotModuleReplacementPlugin())
```

**Comment by davesnx** [comment] 2015-12-16 10:34
I change from devServer stuff on the webpack config into --hot --inline in the CLI command and works perfectly. Also, using a express and handling the webpack config works too...

**Comment by vinhtq** [comment] 2016-01-21 03:59
@mailaneel Thanks! Your solution works!

**Comment by ace-han** [comment] 2016-02-18 01:42
@mailaneel Thanks!+1

**Comment by Amberish** [comment] 2016-02-23 18:06
<pre>var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
var path = require('path');

module.exports = {
  context: path.join(__dirname, "/"),
  devtool: debug ? "inline-sourcemap" : null,
  entry: ["webpack/hot/dev-server", "./src/start.jsx"],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy'],
        }
      }
    ]
  },
  output: {
    path: __dirname + "/build/js/",
    filename: "script.js",
    publicPath: "/build/js/"
  },
  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};</pre>

Here is my webpack config. I have following folder structure:
<pre>
-app
  -build
    -js
       -script.js
  -src
    -start.js
</pre>
I am compiling start.js in 'src' folder to 'script.js' in 'build/js' folder.

Running it with webpack is compiling exactly as I intended, however running webpack-dev server as:

<pre>webpack-dev-server --content-base ./build --hot --inline</pre>

is not doing as intended. However, in terminal it is showing compilation.

**Comment by samarpanda** [comment] 2016-04-08 03:07
I bumped in similar issue. Wondering why the build file is expecting HMR. This is what i see in console while using the build file
```txt
main.js:3 Uncaught Error: [HMR] Hot Module Replacement is disabled.
```

My config file
```js
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const distDir = 'dist';

function dirPath(dest){
  return path.resolve(__dirname, dest);
};

function webPath(dest){
  return dirPath('./' + dest);
};

const config = {
  entry: [
    webPath('scss/style.scss'),
    webPath('main.js')
  ],
  output: {
    path: process.env.NODE_ENV === 'production' ? dirPath(distDir) : dirPath('build'),
    filename: 'js/[name].js'
  },
  module: {
    loaders: [{
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract('style', 'css!sass')
    },
    {
      test: /\.css$/,
      loader: "style!css"
    },
    {
      test: /\.(png|jpg|jpeg|gif|woff)$/,
      loader: 'url-loader?limit=1000'
    },
    {
      test: /\.js?$/,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        compact: true,
        presets: ['es2015']
      }
    }]
  },
  plugins: [
    new ExtractTextPlugin('css/style.css'),
    new HtmlWebpackPlugin({
      template: webPath('index.html'),
      inject: 'body'
    })
  ],
  devServer: {
    quite: false,
    noInfo: false,
    stats: {
      assets: false,
      colors: true,
      version: false,
      timings: false,
      chunks: false,
      chunkModules: false
    }
  }
};

if(process.env.NODE_DEV === 'production'){
  config.plugins.push(
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        warnings: false
      },
      minimize: true
    })
  );
} else {
  config.entry.push(
    'webpack/hot/dev-server',
    'webpack-dev-server/client?http://localhost:8080'
  );
}

module.exports = config;
```

My `package.json` scripts
```js
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --devtool eval --progress --colors --hot --inline --content-base build",
    "deploy": "NODE_ENV=production webpack -p"
  },
```

**Comment by samarpanda** [comment] 2016-04-09 01:07
Sorry to post my silly mistake here. It was a typo error in webpack.config file. This `process.env.NODE_DEV` should be `process.env.NODE_ENV`. I was completely blind couldn't see this error until i added some debug logs.

**Comment by monochrome-yeh** [comment] 2016-06-04 19:41
@mailaneel Thanks 😄

**Comment by hkongm** [comment] 2016-06-07 08:43
just add the plugin into the webpack config file like this:
```
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
// other plugins
  ]
```

and thanks @mailaneel

**Comment by Skura23** [comment] 2016-09-10 04:50
perfectly solved my problem

**Comment by SpaceK33z** [comment] 2016-10-09 17:40
Closing this issue since this has become a dumping place of random issues with HMR.

HMR is still very difficult to setup. We are working on improved documentation around this. After that, we'll also start working to make it more easy to use.

**Closed by SpaceK33z** 2016-10-09 17:40 UTC
Labels: question

**Comment by IFmiss** [comment] 2017-01-04 08:33
I tried some methods but didn't work ，zzz

**Comment by holms** [comment] 2017-01-08 23:59
> Hot Module Replacement is disabled. means the HotModuleReplacementPlugin is not used.
> 
> --hot adds it. (because the CLI have access to your webpack configuration)
> 
> hot: true doesn't add it. (because the API doesn't have access to your webpack configuration)

How can one knowing how unix way works, do in this in CLI..? Don't follow ROR community anti-patterns, read UNIX recommendations. Both - config and CLI way should work equally. Sometimes it's ok to put additional params to configuration, but definitely not vice versa!!!!!!

**Comment by rubencodes** [comment] 2017-02-07 00:51
So, I had the `new webpack.HotModuleReplacementPlugin()` line in my plugins array, but I found it wasn't working unless I passed the `--hot --inline` options in the CLI. I moved the HMR Plugin to be the first in the plugins array, and now it works without the CLI options! So for anyone that sees this, try that if it's not working for you.

**Comment by johnelliott** [comment] 2017-04-02 03:47
I was getting the error until I _removed_ the `hot: true` from my config. Unfortunately now I'm looking for a good way to  disable the effect of adding the `new webpack.HotModuleReplacementPlugin()` to the loaders array. I may just extract the array and build it before exporting the webpack config module.

**Comment by sarink** [comment] 2017-11-13 03:28
See this [note](https://webpack.js.org/configuration/dev-server/#devserver-hot)

To fix: add `new webpack.HotModuleReplacementPlugin()` to your `plugins` array, _OR_ pass the `--hot` command line option

**Comment by slavafomin** [comment] 2019-01-12 17:14
The year is 2019, still when trying to set up dev-server and HMR following the documentation, I've stumbled upon this issue.

The explanation and actual behavior (when `hot` and `inline` options work only through the CLI, but not through the config) is extremely weird and counter-intuitive for people not familiar with how things work internally.

Could we remedy the situation somehow?

We should at least update the documentation to explain this more clearly. It's really bad when new user have to read through the issues in order to configure a pretty basic set up.

**Comment by mmmeff** [comment] 2019-01-15 02:05
@slavafomin I just encountered this for the first time as well. I wonder if this could be a regression?

**Comment by gingerwilliams** [comment] 2019-02-09 17:29
devServer: {
        + contentBase: path.join(__dirname, "dist"),
        compress: true,
        port: 8000,
        - hot: true,
        + watchContentBase: true,
        + writeToDisk: true,
        progress: true,
        open: true,
        historyApiFallback: true
    },

**Comment by gingerwilliams** [comment] 2019-02-09 17:29
`devServer: {
        + contentBase: path.join(__dirname, "dist"),
        compress: true,
        port: 8000,
        - hot: true,
        + watchContentBase: true,
        + writeToDisk: true,
        progress: true,
        open: true,
        historyApiFallback: true
    },`

**Comment by gingerwilliams** [comment] 2019-02-09 17:31
```devServer: {
        + contentBase: path.join(__dirname, "dist"),
        compress: true,
        port: 8000,
        - hot: true,
        + watchContentBase: true,
        + writeToDisk: true,
        progress: true,
        open: true,
        historyApiFallback: true
    },```

**Comment by evilebottnawi** [comment] 2019-02-09 18:14
@slavafomin already solved https://github.com/webpack/webpack-dev-server/blob/102941f0cd0fff69acf1753674b9da4952cb009f/lib/utils/addEntries.js#L53, just not published

**Comment by tianhuil** [comment] 2019-02-17 08:50
In response to https://github.com/webpack/webpack/issues/1151#issuecomment-343800515 and https://github.com/webpack/webpack/issues/1151#issuecomment-453764353, I actually need to do both:

1. add `new webpack.HotModuleReplacementPlugin()` to my `plugins` array in my webpack config
2. pass the `--hot` command line option when launching `webpack-dev-server`.

Also, I find it strange that I *cannot* use `devServer: {hot: true}` or `devServer: { hotOnly: true}` in `webpack.config.js` (it refuses to the load the webpage in the first place).  This seems to contradict [the documentaiton](https://webpack.js.org/configuration/dev-server/#devserverhot) which appears to say that that `devServer: {hot: true}` and `--hot` are the same.

**Comment by Laragh** [comment] 2019-02-17 23:28
> The docs are wrong... 😢
> 
> Just use `webpack-dev-server --hot --inline` and don't anything special about webpack-dev-server or HMR to your webpack.config.js.

Thanks so much for this - hours wasted here trying to figure out why live reload wasn't working...
