### ISSUE TITLE
ES6 Modules from a node_modules/ directly not importing default export correctly

### ISSUE THREAD

**Issue by ssylvia** [webpack/webpack#3403] opened 2016-12-01 14:22 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I have the following ES6 module:
```js
export const namedExport1 = 'foo';
export const namedExport2 = 'bar';

const Test = function Test() {

  const factory = {
    foo: 'bar',
  };

  factory.sayHello = function sayHello(name) {
    alert(`Hello ${name}`);
  };

  return factory;
};

export default Test;
```

If I import it as `import myModule from 'path/Test'` and it is located in the node_modules directory, it gets imported as:
```js
{
  default: Test()
  namedExport1: 'foo'
  namedExport2: 'bar'
}
```
However, if I load the module from any other directory, it gets imported as the default method:
```js
function Test() {

  var factory = {
    foo: 'bar'
  };

  factory.sayHello = function sayHello(name) {
    alert('Hello ' + name);
  };

  return factory;
}
```

**What is the expected behavior?**
Should always import the default export.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Webpack: 2.1.0-beta.27
Node: v7

**Comment by jaydenseric** [comment] 2016-12-06 03:55
[react-router-relay](https://github.com/relay-tools/react-router-relay) import is broken. I am using Webpack 2.1.0-beta.27, Node 7.2.0.

You should simply being able to:

```js
import useRelay from 'react-router-relay'
console.log(useRelay)
```

Instead you need to do this:

```js
import useRelay from 'react-router-relay'
console.log(useRelay.default)
```

**Comment by Kovensky** [comment] 2016-12-06 04:30
`react-router-relay`'s npm package does appear to have a correct `"module": "es/index.js"` definition as well. It, oddly, exports as `default` an object with functions instead of just exporting the functions, but that's how it is defined in the source code.

The commonjs version, though, does use `babel-plugin-add-module-exports`, just to make things more confusing :/

**Comment by Kovensky** [comment] 2016-12-06 05:17
Hm, I have not been able to reproduce it with current `master`. The imported default is bundled and resolved correctly.

I also thought this could be an interaction with `externals`, such as generated by https://github.com/liady/webpack-node-externals; but that would just load the commonjs build instead.

**Comment by sokra** [comment] 2016-12-07 09:12
duplicate of #3168

**Closed by sokra** 2016-12-07 09:12 UTC
Labels: bug, P1: Urgent
