### ISSUE TITLE
Global functions get called in wrong context in webpack 3

### ISSUE THREAD

**Issue by daniel-franz** [webpack/webpack#5111] opened 2017-06-20 13:36 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Global methods get called in context of the `__WEBPACK_IMPORTED_MODULE_0`-object in webpack 3.

**If the current behavior is a bug, please provide the steps to reproduce.**

timeout.js
```js
export default setTimeout;
```

index.js
```js
import timeout from './timeout';

timeout(() => console.log('test'));
```

`node_modules/.bin/webpack index.js out.js`

Open in a browser
```
out.js:75 Uncaught TypeError: Illegal invocation
    at Object.__webpack_exports__.a (out.js:75)
    at __webpack_require__ (out.js:20)
    at Object.defineProperty.value (out.js:63)
    at out.js:66
```

**What is the expected behavior?**

global function gets called in global context.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3.0.0
tested on IE 11 on Windows, Chrome 59 on Macos

**Comment by sokra** [comment] 2017-06-20 13:46
Read this https://medium.com/webpack/webpack-freelancing-log-book-week-5-7-4764be3266f5 chapter "Other changes required".

You can set `module.strictThisContextOnImports = true` allow it. But better use

``` js
export default (fn, timeout) => setTimeout(fn, timeout);
```

**Comment by daniel-franz** [comment] 2017-06-20 18:41
Ah, I was not aware of that, thank you.

A polyfill in https://github.com/rt2zz/redux-persist caused the problem in our build, I was just trying to give a minimal example in this issue.

So adapting the check for static imports to circumvent these kind of issues would not be possible?

**Comment by STRML** [comment] 2017-06-20 21:44
This also happens in combination with `babel-plugin-transform-runtime`, in particular with core-js's `Array.from` shim, which has [this line](https://github.com/zloirock/core-js/blob/8cf8d1e0cba3601fc533f8b27a3966d0d6100daf/modules/es6.array.from.js#L15). Webpack turns its context into the function `function() { return default; }` which causes the function to fail with:

```
Uncaught TypeError: Cannot assign to read only property 'length' of function 'function from() { [native code] }'
    at Function.from (native)
```

`module.strictThisContextOnImports` fixes the issue.

**Comment by alexsasharegan** [comment] 2017-06-27 17:08
Can someone elaborate on how to use the fix `module.strictThisContextOnImports = true`?

**Comment by STRML** [comment] 2017-06-27 17:10
Literally add the property `strictThisContextOnImports` to your `module` key, like so:

```js
module.exports = {
  entry:...,
  output: ...,
  module: {
    rules: ...,
    strictThisContextOnImports: true,
  }
}
```

But be aware of #5135.

**Comment by alexsasharegan** [comment] 2017-06-27 17:11
Thank you! So this fix is incompatible with the `Array.from` polyfill?

**Comment by STRML** [comment] 2017-06-27 17:12
Correct, and possibly with other functions, but hopefully not for much longer.

**Comment by alexsasharegan** [comment] 2017-06-27 17:15
Gotcha. Sounds like a patch release should solve this soon. I'm possibly having a different issue, but I'm trying to scour the `ModuleConcatenationPlugin` issues and try things before opening an issue (and because I have no idea how to create a bug reproduction of something I don't understand yet).

**Closed** 2017-07-11 18:36 UTC
