### ISSUE TITLE
DataUrl can't be generated automatically, because there is no mimetype for

### ISSUE THREAD

**Issue by StreetStrider** [webpack/webpack#14176] opened 2021-09-08 14:51 UTC
# Bug report

**What is the current behavior?**
I activate persistent cache and see this error:
```
DataUrl can't be generated automatically, because there is no mimetype for "" in mimetype database. Either pass a mimetype via "generator.mimetype" or use type: "asset/resource" to create a resource file instead of a DataUrl
```
I've tracked the input and it is already a Data URL base64, like `data:image/gif;base64,R0lGODlhCgAKAJECAAAAAP///////wAA…`.

**If the current behavior is a bug, please provide the steps to reproduce.**
There's no such error without persistent cache, so I belive this to be a bug. I have this on private codebase, but I think the reproduction would be to use data urls in webpack-handled files. One of our flawed assets come from `import 'react-image-crop/dist/ReactCrop.css';` which in turn uses data url in `url()`.

**What is the expected behavior?**
No error in console.

For bugged asset [this line](https://github.com/webpack/webpack/blob/200ce66945ef18621199c582575982b37d89ac8d/lib/asset/AssetGenerator.js#L151) got empty string without persistent cache and `{ encoding: undefined, mimetype: undefined }` with persistent cache.

**Other relevant information:**
webpack version:  5.52
Node.js version: 14.17
Operating System: GNU/Linux
Additional tools:

**Comment by alexander-akait** [comment] 2021-09-08 14:53
Please provide full DATA URI, because I think it is broken

**Comment by StreetStrider** [comment] 2021-09-08 14:56
We have a bunch of them in the output. On of the shortest:
```
data:image/gif;base64,R0lGODlhCgAKAJECAAAAAP///////wAAACH/C05FVFNDQVBFMi4wAwEAAAAh/wtYTVAgRGF0YVhNUDw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6OEI5RDc5MTFDNkE2MTFFM0JCMDZEODI2QTI4MzJBOTIiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6OEI5RDc5MTBDNkE2MTFFM0JCMDZEODI2QTI4MzJBOTIiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuZGlkOjAyODAxMTc0MDcyMDY4MTE4MDgzQzNDMjA5MzREQ0ZDIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjAyODAxMTc0MDcyMDY4MTE4MDgzQzNDMjA5MzREQ0ZDIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+Af/+/fz7+vn49/b19PPy8fDv7u3s6+rp6Ofm5eTj4uHg397d3Nva2djX1tXU09LR0M/OzczLysnIx8bFxMPCwcC/vr28u7q5uLe2tbSzsrGwr66trKuqqainpqWko6KhoJ+enZybmpmYl5aVlJOSkZCPjo2Mi4qJiIeGhYSDgoGAf359fHt6eXh3dnV0c3JxcG9ubWxramloZ2ZlZGNiYWBfXl1cW1pZWFdWVVRTUlFQT05NTEtKSUhHRkVEQ0JBQD8+PTw7Ojk4NzY1NDMyMTAvLi0sKyopKCcmJSQjIiEgHx4dHBsaGRgXFhUUExIREA8ODQwLCgkIBwYFBAMCAQAAIfkEBQoAAgAsAAAAAAoACgAAAhWEERkn7W3ei7KlagMWF/dKgYeyGAUAIfkEBQoAAgAsAAAAAAoACgAAAg+UYwLJ7RnQm7QmsCyVKhUAIfkEBQoAAgAsAAAAAAoACgAAAhCUYgLJHdiinNSAVfOEKoUCACH5BAUKAAIALAAAAAAKAAoAAAIRVISAdusPo3RAzYtjaMIaUQAAIfkEBQoAAgAsAAAAAAoACgAAAg+MDiem7Q8bSLFaG5il6xQAIfkEBQoAAgAsAAAAAAoACgAAAg+UYRLJ7QnQm7SmsCyVKhUAIfkEBQoAAgAsAAAAAAoACgAAAhCUYBLJDdiinNSEVfOEKoECACH5BAUKAAIALAAAAAAKAAoAAAIRFISBdusPo3RBzYsjaMIaUQAAOw==
```

**Comment by alexander-akait** [comment] 2021-09-08 15:01
Here regexp https://github.com/webpack/webpack/blob/main/lib/schemes/DataUriPlugin.js#L14, but based on test, works fine...

**Comment by StreetStrider** [comment] 2021-09-09 15:51
I tried to reproduce this on a simple repo but with no luck. In our private repo I have at least three different mime cases that causes errors: data:image/svg+xml, data:image/gif;base64, data:font/ttf;base64. We got css-loader and mini-css-extract-plugin. I will try to narrow this down.

**Comment by alexander-akait** [comment] 2021-09-09 15:56
Yes, I can't reproduce too, do you have `file-loader`/`url-loader`/`svg-loader` or something same?

**Comment by StreetStrider** [comment] 2021-09-09 16:01
We have them in the legacy part of the codebase which does not causes this errors. In affected codebase `asset` is used.

**Comment by alexander-akait** [comment] 2021-09-09 16:02
I think somebody modify URL so I got this problem, I can't reproduce this problem even with broken data URI

**Comment by pataar** [comment] 2021-09-15 07:18
@StreetStrider I stumbled upon the same issue. After clearing the cache the error(s) went away.

**Comment by alexander-akait** [comment] 2021-09-15 12:53
@StreetStrider try to remove cache, maybe you have corrupted cache, anyway I can't reproduce, closing, feel free to feedback

**Closed by alexander-akait** 2021-09-15 12:53 UTC
Labels: bug, webpack-5

**Comment by StreetStrider** [comment] 2021-09-15 12:54
@pataar it went away because it occurs only on cache. When I first run my build there's no error, on the second run I got multiple deserialization issues.

**Comment by alexander-akait** [comment] 2021-09-15 12:57
@StreetStrider it means some of your plugins break webpack cache

**Comment by StreetStrider** [comment] 2021-09-27 17:55
@alexander-akait what is the best way to debug a sequence of loaders working? I think to tap into webpack's node_modules code but don't know where to start. Can you point out the place where should I start to look?

**Comment by alexander-akait** [comment] 2021-09-30 14:37
@StreetStrider Can you provide cache options an list of plugins?

**Comment by StreetStrider** [comment] 2021-09-30 17:24
@alexander-akait,
```js
{
  type: 'filesystem',
  name: 'desktop',
  profile: true
}
```
```js
[
  ForkTsCheckerWebpackPlugin { options: { typescript: [Object] } },
  FilterWarningsPlugin { exclude: [ /export .* was not found in/ ] },
  HtmlWebpackPlugin {
    userOptions: {
      title: '---',
      hash: true,
      templateParameters: [Object],
      template: 'app/index.ejs',
      inject: false
    },
    version: 5
  },
  MiniCssExtractPlugin {
    _sortedModulesCache: WeakMap { <items unknown> },
    options: {
      filename: '[name].[contenthash:8].bundle.css',
      ignoreOrder: true,
      experimentalUseImportModule: false,
      runtime: true,
      chunkFilename: '[name].[contenthash:8].bundle.css'
    },
    runtimeOptions: { insert: undefined, linkType: 'text/css', attributes: undefined }
  },
  WebpackManifestPlugin {
    options: {
      basePath: '',
      fileName: 'manifest.json',
      filter: null,
      generate: undefined,
      map: null,
      publicPath: null,
      removeKeyHash: /([a-f0-9]{32}\.?)/gi,
      seed: undefined,
      serialize: [Function: serialize],
      sort: null,
      transformExtensions: /^(gz|map)$/i,
      useEntryKeys: false,
      writeToFileEmit: false
    }
  },
  { name: 'ClientVersionPlugin', apply: [Function: apply] }
]
```

**Comment by alexander-akait** [comment] 2021-09-30 17:29
hm , what is `ClientVersionPlugin`? Anyway can you try to disable each plugin and check, if you provide reproducible example I will help more faster

**Comment by StreetStrider** [comment] 2021-09-30 17:33
> you try to disable each plugin and check

Okay, will do that. I've already did this with loaders but with no luck.

ClientVersionPlugin uses `compiler.hooks.afterEmit` to create file as side effect. It does not interact with the code, only read compilation object.

**Comment by alexander-akait** [comment] 2021-10-01 09:42
@StreetStrider Do you have `cache-loader` or maybe you run build in parallels, do you have multiple compiler mode?

**Comment by StreetStrider** [comment] 2021-10-01 15:12
@alexander-akait we do not use cache-loader.

We do run build in parallel in different processes (one webpack instance per process). We have monorepo in which webpack cache lands in different locations for different packages (like `package/name/node_modules/.cache/webpack` so no collision), beside that we set up cache `name` different for different packages.

We have standard dev / prod modes, right now I'm having issues with dev build, because we aim to benefit from filesystem cache in in dev environment.

**Comment by alexander-akait** [comment] 2021-10-01 15:16
Sounds like you override caches caches, can you check name and locations for each compiler? Maybe you merge something and override name, for example using `webpack-merge`

**Comment by StreetStrider** [comment] 2021-10-01 15:44
We use merge, but when you asked me to share config I gave you the resulting config.

I've tried to investigate what is created:
```
drwxr-xr-x 3 strider strider 4096 окт  1 18:34 ./packages/admin/node_modules/.cache/webpack/
drwxr-xr-x 3 strider strider 4096 окт  1 18:34 ./packages/auth/node_modules/.cache/webpack/
drwxr-xr-x 3 strider strider 4096 окт  1 18:38 ./packages/desktop/node_modules/.cache/webpack/
drwxr-xr-x 3 strider strider 4096 окт  1 18:34 ./packages/help-widget-app/node_modules/.cache/webpack/
```
```
┗ tree ./packages/*/node_modules/.cache/webpack
Permissions Size User    Date Modified Name
drwxr-xr-x     - strider 10-01 18:34   ./packages/admin/node_modules/.cache/webpack/
drwxr-xr-x     - strider 10-01 18:35   └── admin/
.rw-r--r--  323M strider 10-01 18:35      ├── 0.pack
.rw-r--r--    74 strider 10-01 18:34      ├── 1.pack
.rw-r--r--  4,6M strider 10-01 18:35      ├── 2.pack
.rw-r--r--  5,1M strider 10-01 18:35      ├── index.pack
.rw-r--r--  5,1M strider 10-01 18:34      └── index.pack.old
drwxr-xr-x     - strider 10-01 18:34   ./packages/auth/node_modules/.cache/webpack/
drwxr-xr-x     - strider 10-01 18:35   └── auth/
.rw-r--r--  250M strider 10-01 18:35      ├── 0.pack
.rw-r--r--  128k strider 10-01 18:35      ├── 1.pack
.rw-r--r--  4,1M strider 10-01 18:35      ├── index.pack
.rw-r--r--  4,1M strider 10-01 18:34      └── index.pack.old
drwxr-xr-x     - strider 10-01 18:38   ./packages/desktop/node_modules/.cache/webpack/
drwxr-xr-x     - strider 10-01 18:38   └── desktop/
.rw-r--r--   85M strider 10-01 18:38      ├── 0.pack
.rw-r--r--   72M strider 10-01 18:38      ├── 1.pack
.rw-r--r--   44M strider 10-01 18:38      ├── 2.pack
.rw-r--r--  1,7G strider 10-01 18:38      ├── 3.pack
.rw-r--r--    74 strider 10-01 18:38      ├── 4.pack
.rw-r--r--   19M strider 10-01 18:38      └── index.pack
drwxr-xr-x     - strider 10-01 18:34   ./packages/help-widget-app/node_modules/.cache/webpack/
drwxr-xr-x     - strider 10-01 18:35   └── help-widget-app/
.rw-r--r--  240M strider 10-01 18:35      ├── 0.pack
.rw-r--r--  117k strider 10-01 18:35      ├── 1.pack
.rw-r--r--  3,7M strider 10-01 18:35      ├── index.pack
.rw-r--r--  3,7M strider 10-01 18:34      └── index.pack.old
```
This is clean build and timestamps are fresh.

**Comment by alexander-akait** [comment] 2021-10-01 16:18
Can you provide `resolve` options?

**Comment by StreetStrider** [comment] 2021-10-01 17:41
```js
{
  extensions: [ '.js', '.jsx', '.ts', '.tsx' ],
  fallback: {
    path: ' ... /node_modules/path-browserify/index.js' // some abs path
  }
}
```

**Comment by alexander-akait** [comment] 2021-10-01 18:26
Don't have ideas :disappointed: If repo is private maybe you can invite me to avoid publishing it (I can sign NDA if needed)

**Comment by StreetStrider** [comment] 2021-10-01 20:56
Can you give me an advice how to debug loader sequence? I can monkey-patch the code, I think I need to modify Tapable, but don't have the complete picture. That way I can see how specific datauri is transformed and pinpoint when it was broken.

**Comment by alexander-akait** [comment] 2021-10-02 13:12
@StreetStrider I have three ideas here:
1. We have a bug with replacing hashes, so it works fine on initial run and then broken, to check this let's change `data:image/gif;base64,R0lGODlhCgAKAJECAAAAAP///////` on something another, for example https://png-pixel.com/
2. Something broken in CSS loader, ideally it should work, let's debug it here https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L460
3. Corrupted cache, can you show output for `module` here https://github.com/webpack/webpack/blob/200ce66945ef18621199c582575982b37d89ac8d/lib/asset/AssetGenerator.js#L111

**Comment by alexander-akait** [comment] 2021-10-14 17:49
Thanks, I will look at this tomorrow

**Comment by yuzhanglong** [comment] 2021-10-17 03:58
I had the same problem and it was solved:
Follow the code below to modify your  configuration

```typescript
const config = {
optimization:{
   runtimeChunk: 'single',
}
```
and it works! 
Also, you can still use 'filesystem' cache options.
