### ISSUE TITLE
Error when we use Third party mscgenjs modules: "define cannot be used indirect" with webpack v3.6.0 working fine with v1.12.15

### ISSUE THREAD

**Issue by pgawali-broadsoft** [webpack/webpack#6180] opened 2017-12-22 13:06 UTC
Bug:
Third party modules like mscgenjs are not compatible with webpack v3.6.0  .Getting error Uncaught Error: define cannot be used indirect .
{
  "name": "mscgenjs",
  "version": "1.9.0",
  "description": "Implementation of MscGen in JavaScript",
  "main": "index.js",
  "dependencies": {
    "amdefine": "1.0.1",
    "requirejs": "2.3.2"
  },

Working fine older"version": "1.12.15".

Environment:
Nodejs :6.10.2
Webpack : 3.6.0
OS : Ubuntu

**Comment by EugeneHlushko** [comment] 2017-12-22 15:52
A piece of your code could help. are you doing it like this?
```
define(['./node_modules/mscgenjs/index'], function(mscgenjs){
    // your code here
});
```

**Comment by sokra** [comment] 2017-12-22 15:57
Duplicate of #5316

**Closed by sokra** 2017-12-22 15:57 UTC
