### ISSUE TITLE
The key of the entry must be the same as the file name of value

### ISSUE THREAD

**Issue by jundge** [webpack/webpack#10657] opened 2020-04-03 07:39 UTC
# Bug report

**What is the current behavior?**
<img width="678" alt="1" src="https://user-images.githubusercontent.com/24717511/78335715-b8a1bf00-75c0-11ea-94e2-8180cea6c01a.png">
![2](https://user-images.githubusercontent.com/24717511/78335770-d3743380-75c0-11ea-8211-9d5ca73af37a.png)

Note:The key and value file names in the document do not need to be the same

**If the current behavior is a bug, please provide the steps to reproduce.**
 Please look at photo

**What is the expected behavior?**

**Other relevant information:**
webpack version:  v4.42.1
Node.js version: v12.14.0
Operating System: Mac 10.14.6
Additional tools: VSCode

**Comment by Mistyyyy** [comment] 2020-04-03 08:48
duplicate of #10498

**Comment by evilebottnawi** [comment] 2020-04-03 10:53
Should be fixed in webpack@5

**Closed by evilebottnawi** 2020-04-03 10:53 UTC
