### ISSUE TITLE
path.parse method does not get included when bundling for target:web

### ISSUE THREAD

**Issue by diervo** [webpack/webpack#3494] opened 2016-12-15 18:10 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
For `target:web` If a module is using `import { parse } from 'path';`, It will fail on the client since it won't be sent/mocked.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just add the import described below and have the option for `node: {fs: 'empty'}` in your webpack config.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm not sure if there is a reason not to support this, but if so, there should be an error message indicating what's happening and why.

**Please mention other relevant information such as the browser version, Node.js version, 
Latests MacOs, node and webpack

**Comment by TheLarkInn** [comment] 2016-12-15 19:16
Could you please provide what version of webpack you discovered this, in addition to a very small reproducible example that we can test against?

**Comment by Kovensky** [comment] 2016-12-16 01:33
`import { parse } from 'path';` **should not work** (except by accident) regardless of whether you're using the real or shimmed `path`. Use `import path from 'path'; const { parse } = path;`. The import specifier is not object destructuring.

**Comment by Kovensky** [comment] 2016-12-16 01:36
As for the `parse` function, it looks like it's missing from `path-browserify`, and [has been for a very long time](https://github.com/substack/path-browserify/issues/2).

`path-browserify` might need to be forked?

**Comment by diervo** [comment] 2016-12-16 08:17
@TheLarkInn Here is a trivial repro case:
https://gist.github.com/diervo/fd1fb576e40bf2b6330e04b978323ced
So if there is a library shimming `path` that webpack uses, for whatever reason it just does not contain that method, most of other methods seem to be there.

I think it will be great if webpack tells could warn me that " `parse` method on `path` is not supported " at build time, rather than have to figure out by debugging the code. Actually it will be great for any other case as well.

To your point @Kovensky, there is some confusion here:`import { parse } from 'path'` should work [since is part of the semantics of es6 modules](https://tc39.github.io/ecma262/#table-40) which allows among other things tree shaking.

**Comment by Kovensky** [comment] 2016-12-16 12:01
@diervo that is the case when what you are importing is an ES6 module. `path`, however, is a commonjs module, and how importing commonjs modules should work is not actually yet defined. The only thing that is sure is that the commonjs module will be available as a `default` export.

**Comment by sokra** [comment] 2016-12-16 13:33
closing because it's a path-browserify issue

**Closed by sokra** 2016-12-16 13:33 UTC
Labels: X0: need more information

**Comment by diervo** [comment] 2016-12-16 18:13
Just as a side note , I think it will be very useful to give a warning (I think it should be doable since you are spidering dependencies) when using methods that are known to not be there. I will try to send a PR sometime in the future if you find it useful.

**Comment by G-Rath** [comment] 2018-07-26 21:44
Just a heads up: `path-browserify` has been updated, with path.parse being added in v1.

It's marked as a breaking change, and so it's possible that this has only shifted the issue from bing with `path-browserify` to another package higher up in the chain, but felt I should mention it here just to keep this issue up-to-date :)

**Comment by jshado1** [comment] 2019-03-23 14:37
@sokra webpack/node-libs-browser needs to be updated to consume path-browserify@^1 webpack/node-libs-browser#79

**Comment by ayshvab** [comment] 2019-09-03 10:45
Problem not solved?
`Uncaught TypeError: path__WEBPACK_IMPORTED_MODULE_5___default.a.parse is not a function`

**Comment by abrcdf1023** [comment] 2019-12-25 02:52
Hi @sokra,
Can you please update path-browserify to the v1.0.0. It's include parse function and we can solve this issue.

**Comment by okdistribute** [comment] 2020-04-24 05:33
Just ran into this issue too, has this been fixed?

**Comment by mi6th** [comment] 2020-11-23 09:05
> Just ran into this issue too, has this been fixed?

No, it still doesn't work

**Comment by niksy** [comment] 2021-11-13 17:41
If anyone is still facing this problem, you can try [updated version](https://github.com/niksy/node-stdlib-browser) of this package which includes newer version of `path-browserify`.
