### ISSUE TITLE
loaderContext.loadModule does not load modules recursively

### ISSUE THREAD

**Issue by MortenHoustonLudvigsen** [webpack/webpack#4959] opened 2017-05-29 12:34 UTC
**Do you want to request a *feature* or report a *bug*?**

I would like to request a feature, that enables `loaderContext.loadModule` to optionally load modules recursively.

**What is the current behavior?**

When loading a module using `loaderContext.loadModule`, modules are not loaded recursively.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

While implementing [ts-css-loader](https://github.com/MortenHoustonLudvigsen/ts-css-loader), I had trouble loading css modules using `loaderContext.loadModule` for modules loaded by `css-loader`. The error I got was:
```
Error: Cannot find module "../../../../node_modules/css-loader/lib/css-base.js"
```

I turns out that I could solve the problem by writing my own version of `loaderContext.loadModule`, copied from `webpack/lib/dependencies/LoaderPlugin.js`, that loads modules recursively.

I did this by changing the `recursive` parameter from `false` to `true` in the call to `compilation.addModuleDependencies`.

`loaderContext.loadModule`:
```javascript
...
compilation.addModuleDependencies(module, [
	[dep]
], true, "lm", false, (err) => {
...
```

My version of `loadModule`:
```javascript
...
compilation.addModuleDependencies(module, [
	[dep]
], true, "lm", true, (err) => {
...
```

This has solved the problem for now, but it would be much better to use the "official" version of `loadModule`.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment] 2017-06-03 04:14
This wouldn't be too bad of a PR.

**Comment by KTruong888** [comment] 2017-06-10 18:19
Is someone else working on this? I'd like to give it a go.

**Comment by bassdeveloper** [comment] 2017-06-21 01:07
Can I contribute?

**Comment by leoasis** [comment] 2017-11-13 12:46
Is this still something that can be contributed? I'm having a similar issue with a loader I'm trying to write and the suggestion to make `loadModule` load dependencies recursively fixed my problem. If this is the right way to go, I'm willing to send a PR to add that option to `loadModule`.

For more context, I have a question in SO: https://stackoverflow.com/questions/47229666/how-to-write-a-loader-that-depends-on-some-value-in-another-module-but-still-out/47264529#47264529 and a repo that reproduces the problem: https://github.com/leoasis/webpack-loader-issue

**Comment by buoyantair** [comment] 2018-02-18 12:54
Hi @TheLarkInn Can I take this issue? :D I'm sort of familiar with webpack repo but not as much, I'll be rushing back and forth here for help :sweat_smile: Bare with me!

**Comment by buoyantair** [comment] 2018-02-18 13:15
So I have to just turn a knob on? ;-;

**Comment by TheLarkInn** [comment] 2018-02-24 04:40
Looks like it!

**Comment by bastimeyer** [comment] 2018-04-16 04:50
I've just run into this issue and would really appreciate if this could be fixed any time soon, as the mentioned workaround seems to be working fine.

The loader I'm trying to write needs to load modules and get the list of their export names. When those modules get resolved regularly afterwards, all of their dependencies won't get resolved in the final build. The build is not failing, but all references of the imported dependencies of these modules get turned into an IIFE, like this:
```js
!(function webpackMissingModule() { var e = new Error("Cannot find module \"...\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())
```
which can also produce syntax errors in some cases, eg. with a leading `new`...

**Closed** 2018-04-17 07:24 UTC
Labels: D1: Easy (Contrib. Difficulty), D2: Medium (Contrib. Difficulty), P4: Nice To Have, enhancement
