### ISSUE TITLE
Error in webpack-sources

### ISSUE THREAD

**Issue by stepancar** [webpack/webpack#5326] opened 2017-07-20 07:25 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
TypeError: item.source is not a function
```
TypeError: item.source is not a function
    at /Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:23:50
    at Array.map (native)
    at ConcatSource.source (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:22:24)
    at /Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:23:50
    at Array.map (native)
    at ConcatSource.source (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:22:24)
    at /Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:23:50
    at Array.map (native)
    at ConcatSource.source (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:22:24)
    at CachedSource.source (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:28:44)
    at Compiler.writeOut (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/lib/Compiler.js:346:27)
    at require.forEach (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/lib/Compiler.js:336:21)
    at /Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/node_modules/async/dist/async.js:3145:5)
    at Compiler.emitFiles (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack/lib/Compiler.js:325:21)
    at Immediate.<anonymous> (/Users/u_021ly/Desktop/projects/arui-feather/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4
```
This is Travis build https://travis-ci.org/alfa-laboratory/arui-feather/jobs/255237762#L718
**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/alfa-laboratory/arui-feather.git
git checkout feat/add-md-lint
npm i
npm run gemini-ci
```

**What is the expected behavior?**
Runs without errors.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
npm -v 5.3.0
node -v 6.10.1
webpack 3.3.0

**Comment by stepancar** [comment] 2017-07-21 07:41
Works good with webpack 2.7.0

**Comment by TheLarkInn** [comment] 2017-07-31 12:09
Could you check webpack 3.4.1. and also provide a reproducible repository for us to test against?

**Comment by stepancar** [comment] 2017-07-31 12:52
@TheLarkInn , yes , I'll do it today

**Comment by Donmclean** [comment] 2017-07-31 23:04
@TheLarkInn @stepancar Thanks a lot for looking at this. Having the same issue also. It seems that the follow line isn't handling the case of `item` being: 
```javascript
ConcatSource {
  children: [ 'module.exports =\n', ConcatSource { children: [Array] } ]
}
``` 
https://github.com/webpack/webpack-sources/blob/master/lib/ConcatSource.js#L23

specifically in the case of `ExtractTextPlugin`: extract-text-webpack-plugin/dist/loader.js:99:87

**Comment by stepancar** [comment] 2017-08-01 20:43
@TheLarkInn 
I updated to 3.4.1 and still see error.
Could you please give a look at 
```
git clone https://github.com/alfa-laboratory/arui-feather.git
git checkout chore/branch-for-reproduce-webpack-error
npm i
npm run gemini-ci
```
created pull request https://github.com/alfa-laboratory/arui-feather/pull/194
you can see travis error 
https://travis-ci.org/alfa-laboratory/arui-feather/jobs/259937469#L736

**Comment by Smolations** [comment] 2017-09-05 19:37
Can I get some clarification on _why_ plugins run through the `ConcatSource` lib in the first place? I am troubleshooting a custom plugin I am writing, and it seems that plugin code that includes some `require` statements is causing me similar issues. Does webpack do some sort of concat operation on the config file itself? Is there any way to disable that for certain included libs?

**Comment by unfalse** [comment] 2017-09-25 14:37
Hello, I have just the same error. The important detail is that when I run webpack from command line it builds the bundle without errors. When I run script with npm which executes webpack-dev-server with config it gives me error about item.source.
Sadly I cannot provide you with repo because my project is not open source.
I even made a lengthy debug session of webpack and discovered that bad 'source' is adding at webpack\lib\Template.js:145
`source.add(module.source);`
where `module.source` is function which leads to the error in the end.
Hope it'll help to inspect the bug.

**Comment by cbrwizard** [comment] 2017-10-09 16:08
Also having this issue. I believe I've got this after updating npm deps.

**Comment by benjycui** [comment] 2017-10-13 06:02
I found the bug and fixed it locally.

After `git bisect` search, I found that 2bd2d2844cf656d7a653464e226d753394894e04 introduced the bug. However, the commit just updated syntax and API, so I doubt that these APIs behave differently in different runtime(Which I had met before in [bisheng](https://github.com/benjycui/bisheng)).

I tried to update the usage of API https://github.com/webpack/webpack/pull/5821/commits/1af69d6fa1fb1f06a47ceeb808174df059e031fc, and then every thing works fine.

@cbrwizard @unfalse @Smolations @stepancar @Donmclean you can try my patch locally, I think that will solve your issue.

And the PR https://github.com/webpack/webpack/pull/5821

**Comment by nowells** [comment] 2017-10-20 19:16
So I stumbled into this issue a while ago, and discovered it was not webpack's fault at all, but instead a dependency's dependency that was loading a poorly written poly/ponyfill library that instead of adding JS functions/features that were missing (like adding `Array.from` if not defined) they instead ALWAYS replaced `Array.from` with a bad implementation. For example, my issue was pulling in `q-io` which pulled in the `collections` npm package that poorly clobbers JS builtins in a really bad way.

**Comment by 1more** [comment] 2018-01-18 11:37
(FYI)
Thanks to @benjycui @nowells .
Below steps are how I fix my `item.source is not a function` error.

1. try to change webpack code like this [line](https://github.com/webpack/webpack/commit/1af69d6fa1fb1f06a47ceeb808174df059e031fc#diff-1064caa9219b7da75fbad061b1a25ec5R163) (only the 163 line of `Chunk.js` file)
2. test webpack doesn't print `item.source ~~` error message.
   1. if it works, some of your dependency may overrides `Array.from`
      1. turn back the code which you fixed in step 1
      2. find keyword `Array.from =` under your `'node_modules'` directories
      3. remove found modules one-by-one from your project, build, run. then you can find which module is wrong.
         1. replace it. (in my case, it was `excel-export` and I replace it with `excel-export-es6`)

**Comment by ooflorent** [comment] 2018-03-08 20:00
Thanks @nowells and @1more for your investigation on this issue! I'm closing it since it is not webpack's fault.

**Closed by ooflorent** 2018-03-08 20:00 UTC
Labels: S4: Broken, S5: Regression, X1: Inspection required, bug
