### ISSUE TITLE
create-react-app: source generated by webpack source and chrome source doesn't mactch up

### ISSUE THREAD

**Issue by bugzpodder** [webpack/webpack#8910] opened 2019-03-13 20:28 UTC
# Bug report

**What is the current behavior?**

Background: 
create-react-app was using cheap-module-source-map and it didn't work well with browser breakpoints: https://github.com/facebook/create-react-app/issues/6074

it switched from cheap-module-source-map to eval-source-map for 2.1.4 release: https://github.com/facebook/create-react-app/pull/5060

This broke the error overlay line number because the source code generated from webpack doesn't match that of Chrome's: https://github.com/facebook/create-react-app/issues/6433

**What is the expected behavior?**
Ideally eval-source-map should be used in create-react-app but this is a blocking issue.  
We should be able to matching source code in both chrome and webpack source.
Currently webpack source code is generated using this middleware for webpack-dev-server:
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/evalSourceMapMiddleware.js

**If the current behavior is a bug, please provide the steps to reproduce.**

Repo of mismatched source code: create-react-app --scripts-version 2.1.4 myapp

The only change I made:
```
$ git diff
diff --git a/src/App.js b/src/App.js
index 7e261ca..e2cb9ac 100755
--- a/src/App.js
+++ b/src/App.js
@@ -4,6 +4,7 @@ import './App.css';
 
 class App extends Component {
   render() {
+    console.log(null.length);
     return (
       <div className="App">
         <header className="App-header">
```

Run yarn start or npm start to start the app.

React-error-overlay:
```
TypeError: Cannot read property 'length' of null
App.render
src/App.js:10:8
   7 | console.log(null.length);
   8 | return (
   9 |   <div className="App">
> 10 |     <header className="App-header">
     |    ^  11 |       <img src={logo} className="App-logo" alt="logo" />
  12 |       <p>
  13 |         Edit <code>src/App.js</code> and save to reload.
```

Clicking on view compiled in the UI (from react-error-overlay):
``` 
TypeError: Cannot read property 'length' of null
App.render
webpack-internal:///./src/App.js:37:24
  34 |   className: "App-header",
  35 |   __source: {
  36 |     fileName: _jsxFileName,
> 37 |     lineNumber: 10
     |                  ^  38 |   },
  39 |   __self: this
  40 | }, React.createElement("img", {
```
Actual source code from chrome, notice that line 37 is the correct line, where as react-error-overlay shows a different source.
<img width="603" alt="screen shot 2019-02-16 at 1 25 37 am" src="https://user-images.githubusercontent.com/14841421/52897474-d2e4c780-3189-11e9-9086-d47f69215c92.png">

If you visit
http://localhost:3000/__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F.%2Fsrc%2FApp.js you'll see this is the source code generated from webpack, which is different from the source code in chrome.

This gist contains the difference in source code between that of react-error-overlay and webpack:
https://gist.github.com/bugzpodder/20e8bc711450d6c0b516785fecab876f

**Other relevant information:**
webpack version:   4.28.3
Node.js version:  10.15
Operating System:  MacOSX
Additional tools: create-react-app 2.1.4

**Comment by montogeek** [comment] 2019-03-14 08:16
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment] 2019-03-14 09:21
No need template here, problem from CRA after my request

**Comment by bugzpodder** [comment] 2019-03-14 09:23
@montogeek I will edit my original post to include any missing information from the template.  I am happy to clarify and make a better repo if needed, let me know.  Thanks evilebottnawi!

**Comment by evilebottnawi** [comment] 2019-03-14 11:45
@bugzpodder Can you provide minimum reproducible test steps?

**Comment by bugzpodder** [comment] 2019-03-14 21:55
Repo: https://github.com/bugzpodder/webpack-dev-server/tree/master/examples/api/middleware
1) run yarn to install a few packages
2) start the demo `node server.js`
3) navigate to localhost:8080
4) compare source from console (step 2) and in chrome source.

Chrome source of index.js
```
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "../../../node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react-dom */ "../../../node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_1__);




var target = document.querySelector('#target');
react_dom__WEBPACK_IMPORTED_MODULE_1___default.a.render(react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "Test"), target);
console.log(null.x);
```

Source from webpack middleware:
```
'use strict';

import React from "react";
import ReactDOM from "react-dom";
var target = document.querySelector('#target');
ReactDOM.render(React.createElement("div", null, "Test"), target);
console.log(null.x);

```

**Comment by sokra** [comment] 2019-03-15 11:03
![image](https://user-images.githubusercontent.com/1365881/54427169-00397c80-471a-11e9-80ee-9a29922bf628.png)

I tried your repo. They are not identical, but not the way you described.

Note that `originalSource()` do refer to the source webpack sees, which is the post-babel source code. Read the file from SourceMap `sourceContents` if you want to get the input file (or from disk in many cases).

**Comment by bugzpodder** [comment] 2019-03-15 21:47
Hi @sokra, thanks for taking time to look into it.

I'd like to clarify a few things: 
There seems to be three types of sources:

Original source:
This is what you posted above (app.js?9a78).  As you indicated, this is readily available.

post-babel source:
This is whats available via webpack-dev-server middleware (and what I can load)
In the demo it is whats posted in the console.
In the first example, it is the first snippet in https://gist.github.com/bugzpodder/20e8bc711450d6c0b516785fecab876f

chrome source:
This as far as I can tell is what chrome sees and executes.  I am a n00b to source maps, so I may get the following wrong but I think this is what happens:
- chrome executes this source
- it encounters an error
- it produces a line number on this source code
- this gets mapped to original source.

So, react-error-overlay was getting out the post-babel source, which is *different* from chrome source.

This is the second snippet in https://gist.github.com/bugzpodder/20e8bc711450d6c0b516785fecab876f
Here are examples of the chrome source from my middleware demo:

<img width="567" alt="Screen Shot 2019-03-15 at 2 26 57 PM" src="https://user-images.githubusercontent.com/14841421/54463604-e5becd80-4730-11e9-80d1-a3cbe82d8a0f.png">
<img width="566" alt="Screen Shot 2019-03-15 at 2 27 04 PM" src="https://user-images.githubusercontent.com/14841421/54463605-e5becd80-4730-11e9-891c-2ce8abdea4b3.png">

**Comment by bugzpodder** [comment] 2019-03-15 22:03
You are right the second repo demo is not working correctly, I changed it in the last minute.  It is currently outputting the original source code.  I will update it and edit this post to reflect this after I finished.

**Comment by ch3nl00ng** [comment] 2019-03-20 08:21
Is there a fix rolling out?

**Comment by montogeek** [comment] 2019-03-20 09:46
Can you try using latest CRA? they reverted changes to source maps.

**Comment by evilebottnawi** [comment] 2019-03-20 10:12
Latest version switch to other type of source map, but issue still exists

**Comment by dannycochran** [comment] 2019-04-09 14:21
@montogeek I believe this is still an issue. This is causing breakpoints to not work in any user using CRA, which is a pretty big blocker.

**Comment by justingrant** [comment] 2019-07-03 17:42
@bugzpodder @dannycochran @montogeek @evilebottnawi - is this issue the same as https://github.com/facebook/create-react-app/issues/6044 and https://github.com/facebook/create-react-app/issues/6296? 

If yes, then you may want to try (and upvote) the config changes in https://github.com/facebook/create-react-app/pull/7022 which fixes those issues.  (Full disclosure: I filed that PR.)

**Comment by bugzpodder** [comment] 2019-07-03 18:10
@justingrant your fix seem to be dealing with sourcemaps for files in node_modules, this is for the app's sourcemaps.  In any cases, I've already put your PR in 3.1 milestone for review.

**Closed** 2019-09-05 23:48 UTC

**Comment by evilebottnawi** [comment] 2019-09-23 09:38
@florian-bd if you still have issue, please open new issue with reproducible test repo, thanks!
