### ISSUE TITLE
Vendor chunk hash varies when app chunk changes

### ISSUE THREAD

**Issue by antonholmquist** [webpack/webpack#1150] opened 2015-06-09 08:01 UTC
My goal is to separate the app code and the vendor code in two different chunks. This works, but my issue is that the vendor chunk changes slightly based on the content of the app chunk. If I for instance require a new file in the app chunk there are some ID's and stuff in the vendor chunk that changes and I need to check that big file into source control every time.

I would very much prefer if the vendor chunk would be consistent between builds, even if the app code changes. I'm using the OccurenceOrderPlugin but it doesn't seem to help achieving this.

Is there anything I am doing wrong, or is this currently how Webpack works by design?

My config file:

````
webpack({
  entry: {
    vendor: ["react", "react-router", "lodash", "jquery", "bluebird"],
    app: "app.js",
  },
  output: {
    path: paths.jsPublicDev,
    filename: "app.bundle.js",
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(true),
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      filename: "vendor.bundle.js",
      minChunks: Infinity, 
      }),
    ],
   }
})
````

Apart from this, Webpack works very well for me. Thank you!

**Comment by zpratt** [comment] 2015-07-12 08:04
:+1:

**Comment by Zagitta** [comment] 2015-08-01 00:08
Have you managed to find a solution to this? I have the same problem with basically the same config and haven't been able to find much information regarding it.

**Comment by hh9527** [comment] 2015-08-07 09:05
This bug make the `common vendor` pattern useless.

**Comment by bebraw** [comment] 2015-11-14 19:04
Duplicate of #1315. Closing.

**Closed by bebraw** 2015-11-14 19:04 UTC
