### ISSUE TITLE
Maximum call stack size exceeded when webpack making a huge project bundle

### ISSUE THREAD

**Issue by mslmsl111** [webpack/webpack#7641] opened 2018-07-03 08:29 UTC
# Bug report

I upgrade my project from webpack 3 to 4 , this project is very huge, after run 30-40s give me this error, but in a small project it is fine. 

**What is the current behavior?**
```
Unhandled rejection RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at AsyncSeriesHookCodeFactory.create (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12)
    at AsyncSeriesHook.compile (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/AsyncSeriesHook.js:29:18)
    at AsyncSeriesHook._createCall (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:24:15)
    at AsyncSeriesHook.lazyCompileHook (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:34:22)
    at Compiler.emitAssets (/Users/mobike/Desktop/app-vue/node_modules/webpack/lib/Compiler.js:311:19)
    at onCompiled (/Users/mobike/Desktop/app-vue/node_modules/webpack/lib/Compiler.js:178:9)
    at hooks.afterCompile.callAsync.err (/Users/mobike/Desktop/app-vue/node_modules/webpack/lib/Compiler.js:500:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/mobike/Desktop/app-vue/node_modules/webpack/lib/Compiler.js:497:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/mobike/Desktop/app-vue/node_modules/webpack/lib/Compilation.js:995:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/mobike/Desktop/app-vue/node_modules/tapable/lib/Hook.js:35:21)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
this is my package.json, This project made by vue, I tried delete 3/4 pages of this project, then webpack work well.......
"dependencies": {
    "axios": "^0.16.2",
    "babel-runtime": "^6.26.0",
    "better-scroll": "^0.1.15",
    "lodash": "^4.17.4",
    "lodash.sortby": "^4.7.0",
    "moment": "^2.18.1",
    "node.extend": "^2.0.0",
    "qs": "^6.5.0",
    "request": "^2.83.0",
    "throttle-debounce": "^1.0.1",
    "tiny-cookie": "^2.1.1",
    "vue": "^2.5.2",
    "vue-i18n": "^7.3.2",
    "vue-infinite-scroll": "^2.0.1",
    "vue-multiselect": "^2.1.0",
    "vue-router": "^2.6.0",
    "vuex": "^2.5.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.0.1",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.5.2",
    "cos-nodejs-sdk-v5": "1.2.5",
    "css-loader": "^0.28.11",
    "cssnano": "^3.10.0",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "exec-cmds": "^1.0.1",
    "express": "^4.14.1",
    "file-loader": "^1.1.11",
    "fix-orientation": "0.0.2",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "glob": "^7.1.2",
    "happypack": "^5.0.0",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.17.3",
    "inline-manifest-webpack-plugin": "^4.0.0",
    "ip": "^1.1.5",
    "less": "^3.0.4",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.4.1",
    "ndir": "^0.1.5",
    "opn": "^5.1.0",
    "optimize-css-assets-webpack-plugin": "^4.0.3",
    "ora": "^1.2.0",
    "px2rem-loader": "^0.1.9",
    "rimraf": "^2.6.2",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "vue-lazyload": "^1.2.3",
    "vue-loader": "^15.2.4",
    "vue-multiselect": "^2.0.6",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.3.3",
    "vuex": "^2.5.0",
    "webpack": "^4.12.2",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.0"
  },

**What is the expected behavior?**
package everything as I expect

**Other relevant information:**
webpack version:  4.12.2
Node.js version: 8.11.1
Operating System: mac os
Additional tools:

**Comment by montogeek** [comment] 2018-07-03 08:40
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by mslmsl111** [comment] 2018-07-03 10:52
i found this is a html-webpack-html bug, when i have 300+ new HtmlWebpackPlugin() for multiple pages

**Comment by ooflorent** [comment] 2018-07-03 15:16
I'm closing the issue since it is related to `html-webpack-html`.

**Closed by ooflorent** 2018-07-03 15:16 UTC

**Comment by taimoortahir7** [comment] 2019-04-17 13:12
any updates on this issue ? 
waiting for response
