### ISSUE TITLE
Runtime `TypeError` when a `.js` ES module imports a `.mjs` ES module

### ISSUE THREAD

**Issue by isiahmeadows** [webpack/webpack#8491] opened 2018-12-12 17:09 UTC
**Edit:** Include some context around `mithril.mjs` itself.

# Bug report

**What is the current behavior?**
When you build and run the bundle in [this repo](https://github.com/ArthurClemens/polythene-mithril-setup/tree/next), it generates an error with the message `Uncaught ReferenceError: require is not defined at Module.../node_modules/mithril/mithril.mjs`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Instructions exist in the repo.

**What is the expected behavior?**
Either Webpack accepting it or spitting out an intentional, informative error with tips on how to fix it. Or in other words, not generating junk output that results in a runtime error.

**Other relevant information:**
webpack version: 4.27.1
Node.js version: Multiple
Operating System: Multiple
Additional tools: Mithril

The `mithril.mjs` file linked here is [this file](https://unpkg.com/mithril@2.0.0-rc.3/mithril.mjs), with no external dependencies, no instances of `require`, or anything else. It purely exports a default and about a dozen named exports.

-----

For context, I'm filing this on behalf of multiple users who ran into issues upgrading to our release candidate due to us adding a `.mjs` module variant and them running into this bug.

Our `package.json` has these two fields:

```json
"main": "mithril.js",
"module": "mithril.mjs",
```

People have found this workaround to avoid the error:

```js
// Add this to your `rules` array
{
	test: /\.mjs$/,
	type: "javascript/auto",
},
```

We have our own tracking issue for this, too: https://github.com/MithrilJS/mithril.js/issues/2336

**Comment by isiahmeadows** [comment] 2018-12-12 17:11
Sorry for the awful timing so close to Christmas.

**Comment by sokra** [comment] 2018-12-13 08:18
`require` is not available in `.mjs` files. They only support ESM.

**Comment by isiahmeadows** [comment] 2018-12-13 08:20
@sokra I'm aware. I'm filing a bug because Webpack seems to be erroneously adding one. Note that [`mithril.mjs` itself](https://unpkg.com/mithril@2.0.0-rc.3/mithril.mjs) contains no instance of `require`. I verified this before filing the bug.

**Comment by sokra** [comment] 2018-12-14 13:21
The problem is similar to https://github.com/webpack/webpack/issues/7032

`lib/node/NodeSourcePlugin.js` injects `global` and `setImmediate` into mithril via require. This is fixed in webpack 5, but injection doesn't work in webpack 4 for mjs files.

Send a PR and remove these lines + a test case:
https://github.com/webpack/webpack/blob/d5e26f728adb63a1fca080ef728fd627952a921d/lib/node/NodeSourcePlugin.js#L119-L121

**Comment by isiahmeadows** [comment] 2018-12-17 06:34
@sokra I pushed a patch that just removes those three lines in #8511, but I'm not sure where the tests go. We can talk more on it there.

**Comment by sokra** [comment] 2018-12-17 18:34
`.mjs` is an experimental technology. Don't use it yet. <- that's the current node.js recommendation.

Publishing ESM as `.js` and the `module` field should work pretty well for frontend stuff, but won't work in node.js natively.

So my recommendation publish ESM and CJS on npm. ESM as .js files in a separate folder and point to it via module field. Make sure to export the same API from CJS and ESM. Best write in ESM and transpire to CJS with Babel.

**Comment by ooflorent** [comment] 2018-12-18 07:59
This is fixed on `next` branch.

**Comment by sokra** [comment] 2018-12-18 08:04
see also #8511

**Closed** 2018-12-19 08:19 UTC
Labels: Send a PR
