### ISSUE TITLE
Treeshaking doesn't remove unused exports?

### ISSUE THREAD

**Issue by GordonSmith** [webpack/webpack#4206] opened 2017-02-05 09:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Un-referenced code is included in bundle (no tree shaking).

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal example:  https://github.com/GordonSmith/tmp

**What is the expected behavior?**
unitTest function to be excluded from the bundle

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by ishan28mkip** [comment] 2017-02-05 13:06
Have you turned off modules trans compilation when using babel? 
`"presets" : [
		['es2015' , { 'modules' : false} ]
]`

Are you building a production build using -p flag or using Uglify JS plugin? Tree Shaking only works when it is run along with Uglify JS to remove dead code.

**Comment by GordonSmith** [comment] 2017-02-05 13:53
I am not using babel - plain es5 JS + import/export syntax

**Comment by timse** [comment] 2017-02-06 01:38
see #2899

**Comment by gbakernet** [comment] 2017-02-06 03:19
Have you checked if it is still in the bundle after minification?

**Comment by GordonSmith** [comment] 2017-02-06 06:17
@timse #2899 is related, but not a duplicate - in my case the erroneously included item is a function not a class.
@gbakernet Yes and it is.

**Comment by timse** [comment] 2017-02-06 06:59
Its a duplicate. The issue is the IIFE that could have side effects and therefore cant be removed

**Comment by bebraw** [comment] 2017-02-06 07:01
Closing as duplicate.

**Closed by bebraw** 2017-02-06 07:01 UTC
