### ISSUE TITLE
Add option to enable/disable followSymlinks of watchpack

### ISSUE THREAD

**Issue by immortal-tofu** [webpack/webpack#6845] opened 2018-03-23 10:03 UTC
**Context:**
You have project A in babel 6 and project B transpiled via babel 7. You run a webpack watch in package B directory to create bundle while you code.
If you `npm link` package B in package A,  and run webpack in package A, it will throw an error because he doesn't find dependencies.
A webpack's issue is open here: https://github.com/webpack/webpack/issues/1866

**Solution**
In webpack, it's possible to disable symlinks via `symlinks: false`. It works and babel (of package A) won't try to transpile package B. Sadly, if you do this, webpack won't react to change.
It's possible to change this behavior with `followSymlinks` in watchpack/chokidar. A PR has been added there to add this option: https://github.com/webpack/watchpack/pull/72

Now, we need the last part: add an exposed option in webpack configuration to enable/disable this watchpack new option. As stated by @TheLarkInn, it could be planned for webpack v5.

**Comment by SEAPUNK** [comment] 2018-05-07 23:08
Why is this planned for webpack 5? Can't this land in webpack 4 as a feature request? I don't see how any of this would be a breaking change, this is primarily a non-breaking feature (or even a bugfix).

**Comment by evilebottnawi** [comment] 2018-05-10 12:03
@SEAPUNK because it is breaking changes in `webpack/watchpack` and can't breaking some build for some developers.

**Comment by bcowell** [comment] 2018-05-25 15:20
Would also like to see this included in webpack 4 as it is a bug.

**Comment by Globegitter** [comment] 2018-08-11 12:07
Agree with the sentiment here, this is either a backwards compatible feature or a bug-fix so there should be no issue shipping it with with v4 and it seems quite a few people would benefit from it.

**Comment by ItamarShDev** [comment] 2018-10-13 17:07
@birdy-  will be happy to get an instructions or a link to where should i start fixing it

(new to submitting PR's to such a library)

thanks

**Comment by birdy-** [comment] 2018-10-14 15:15
Well, since MR on watchpack didn't land yet, we can't do a lot... Comments and upvote MR linked in inital post :(

**Comment by achrefhafedh** [comment] 2019-03-06 11:04
AND FINALLY in Webpack 5

**Comment by Neira1991** [comment] 2019-03-06 11:06
greatttt!!!!

**Comment by wittibs** [comment] 2019-04-25 01:50
@birdy @evilebottnawi - I saw this issue was marked as "D0 first commit" so I decided to pursue it :P 

In researching this issue, I think I understand the problem, but I am unable to reproduce the issue with webpack not picking up on changes in symlinked module. I created a [sample repo](https://github.com/wittibs/webpack-issue-6845) to demonstrate how I am unable to reproduce this issue. Is this still an issue? Or has it been fixed?

Thanks!

**Comment by neonick** [comment] 2019-09-26 20:45
@immortal-tofu it looks like something you can close

**Comment by immortal-tofu** [comment] 2019-09-26 21:37
I close issue for now. I think it's ok now.

**Comment by immortal-tofu** [comment] 2019-09-26 21:56
For information, watchpack finally add the option for followSymlinks.
https://github.com/webpack/watchpack/pull/114
Now we need this option exposed in webpack.
Maybe webpack solved the issue with something else. I didn't try again.

**Comment by immortal-tofu** [comment] 2019-09-26 22:08
@wittibs Basically the issue is simple:
- Create a project A with a babel 6 and some plugin in .babelrc
- Create a project B with babel 7 and some plugin in .babelrc. This project is transpiled `"main": "dist/index.js"`
- Link project B in project A.
- Start webpack with babel-loader in project A.
Project A's Webpack will try to transpile project B with babel 6 and even use their .babelrc file. Since you have 2 versions of babel, you have issue like "this module doesn't exist" because it exists in Project B but not in Project A...
A mess.

First solution:
So far, you can disable symlink with `symlink` option. It works, but you loose watch. If your linked module changes, Project A's webpack won't rebuild. But at least, it won't try to transpile or read your linked module's babelrc.

Second solution:
You want the first solution BUT with the watch ability. Tadam, now you can since watchpack exposed `followSymlinks` option. Sadly Webpack doesn't allow you (yet) to use this param on watchOptions.


This is my summary. Maybe the problem described doesn't exist anymore, I switched to babel 7 everywhere so I encounter far less issue.

I keep close this issue, but tell me if it occurs again. Since watchpack added the option, if the problem still occurs, it can be solved by webpack team.

**Comment by EmpireJones** [comment] 2019-11-04 21:21
I believe this issue still exists regarding files in symlinked folders not being watched when symlink is set to false. It looks like followSymlinks was never exposed, so this should be re-opened, correct?

**Comment by evilebottnawi** [comment] 2019-11-05 10:42
@EmpireJones fixed in webpack@5

**Comment by slint** [comment] 2020-01-15 16:08
@immortal-tofu, @evilebottnawi, @achrefhafedh in what PR/commit was this solved in `webpack@5`? I can see that https://github.com/webpack/webpack/pull/9399 bumped `watchpack`'s version, but there is no way to e.g. pass the `followSymlinks: true` option, e.g. [via `watchOptions`](https://github.com/webpack/webpack/blob/0c7e135cc59d718f9e381a1d8ecce6c0f4c50a8e/schemas/WebpackOptions.json#L2262-L2301). 

IMHO issue should be re-opened until there is a way to also be able to pass options to Watchpack.

**Comment by barisusakli** [comment] 2020-02-22 18:17
Is this really fixed in v5?

**Comment by immortal-tofu** [comment] 2020-02-25 11:40
I don't know if it's fixed in v5. I opened this issue 2 years ago and so far, I didn't see an answer "Problem solved see commit 35D43F53" ;)

**Comment by evilebottnawi** [comment] 2020-02-25 11:49
Solved for webpack@5, you can the option here https://github.com/webpack/watchpack#api

**Comment by slint** [comment] 2020-02-25 13:05
> Solved for webpack@5, you can the option here https://github.com/webpack/watchpack#api

That's on Watchpack (i.e. it now allows passing the flag). But what would an appropriate `weback.config.js` look like though to use the flag? I imagined something like this:

```javascript
module.exports = {
  //...
  watchOptions: {
    followSymlinks: true
  }
};
```

Or to allow full flexibility on what is passed to the `Watchpack` constructor:

```javascript
module.exports = {
  watchOptions: {
  //...
    watchpackConfig: {  // this probably overrides Webpack's default config options 
      followSymlinks: true,
      // ...
    }
  }
};
```

But none of these are reflected in the [WebpackOptions schema](https://github.com/webpack/webpack/blob/443eb907a1dc120e0e6d3e93e96d9eee167a0431/schemas/WebpackOptions.json#L2674-L2714) currently.

**Comment by evilebottnawi** [comment] 2020-02-25 13:09
Oh, yes, we need update schema, WIP

**Comment by barisusakli** [comment] 2020-02-25 15:07
Thanks, I just modified the source and changed `followSysmlinks` to `true` for now.

**Comment by aviramaz** [comment] 2020-05-17 08:17
It'll be solved as part of webpack v5?
Someone has any recommendation how to implement nicely for webpack v4?

**Comment by slint** [comment] 2020-05-17 21:04
Not a particularly "nice" way, but since Webpack v5 is not yet released, a solution is to use the [`patch-package` library](https://www.npmjs.com/package/patch-package) to patch watchpack. Here's the patch diff, which also sets the `depth` parameter to 1 (needed for MacOS):

```diff
 
diff --git a/node_modules/watchpack/lib/DirectoryWatcher.js b/node_modules/watchpack/lib/DirectoryWatcher.js
index 940f616..210a1b7 100644
--- a/node_modules/watchpack/lib/DirectoryWatcher.js
+++ b/node_modules/watchpack/lib/DirectoryWatcher.js
@@ -53,8 +53,8 @@ function DirectoryWatcher(directoryPath, options) {
 	this.watcher = chokidar.watch(directoryPath, {
 		ignoreInitial: true,
 		persistent: true,
-		followSymlinks: false,
-		depth: 0,
+		followSymlinks: true,
+		depth: 1,
 		atomic: false,
 		alwaysStat: true,
 		ignorePermissionErrors: true,
```

**Comment by WeijieZhu0204** [comment] 2020-10-16 14:12
@slint It works !

**Comment by evilebottnawi** [comment] 2020-10-16 14:16
Implemented `followSymlinks` https://github.com/webpack/watchpack

**Comment by evilebottnawi** [comment] 2020-10-16 14:19
Need to send a PR to `watcherOptions` https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L3596

**Closed** 2020-10-23 07:03 UTC
Labels: D0: My First Commit (Contrib. Difficulty), P3: Important, S2: Inconvenient, Send a PR, webpack-5

**Comment by nitinkatyal1314** [comment] 2021-07-23 07:56
Is this working with webpack 5? I have enabled `followSymlinks`  but no luck.

**Comment by alexander-akait** [comment] 2021-07-23 11:48
`devServer` doesn't have this option

**Comment by nitinkatyal1314** [comment] 2021-07-27 11:53
> `devServer` doesn't have this option

Are you sure about this? I am a little confused based on docs which actually point to `watchOptions` inside `devServer` conf. Also, when I put `{ followSymlinks: true }` in webpack conf, nothing happens but adding it to devServer actually makes my app to recompile (though it does not hot reloads).
