### ISSUE TITLE
it has something problem of  'output.filename'  at webpack4.x

### ISSUE THREAD

**Issue by humorHan** [webpack/webpack#7642] opened 2018-07-03 09:29 UTC
I'm trying my luck here. 
```
entry: {
    home: '/......../home.js'
},
output: {
    publicPath: '/dist/',
    filename: "js/[name]-[hash].js",
    chunkFilename: "js/[name]-chunk-[chunkhash].js"
},
```

Expect:
```
js/home-70aa09e8630fee6b4bb2.js
```

Actually：
```
js/home-chunk-70aa09e8630fee6b4bb2.js
```

 
webpack version:   4.14.0
Node.js version:  9.6.1
Operating System: mac os

**Comment by sokra** [comment] 2018-07-03 09:31
Duplicate of #6604

**Closed by sokra** 2018-07-03 09:31 UTC

**Comment by humorHan** [comment] 2018-07-03 10:02
@sokra  
I don’t find the answer to my question in [#6604](https://github.com/webpack/webpack/issues/6604)
I'm looking forward to fix this bug
