### ISSUE TITLE
An error in UglifyJSPlugin when using html-loader

### ISSUE THREAD

**Issue by acwong00** [webpack/webpack#992] opened 2015-04-20 06:48 UTC
I use webpack and UglifyJSPlugin to build my backbone application. When building this application an error arises.

```
ERROR in ./~/html-loader!./templates/messageTemplate.html
Module build failed:
 @ ./js/message-view.js 1:22-72
```

I have two undersore's templates:

``` html
<!-- first template -->
<label><%- prompt %></label>
```

``` html
<!-- second template -->
<div <%= color ? ('style="color:' + color + '"') : '' %>>
    <%= link ? ('<a href="' + link + '">') : '' %>
        <%= message %>
    <%= link ? ('</a>') : '' %>
</div>
```

Only the second template have an error.

I would like to know whether I need to write a configuration in UglifyJSPlugin to fix the problem.

Thank you!

**Comment by sokra** [comment] 2015-04-20 13:54
Looks like a problem in the html-loader. Propably the html-minimizer used doesn't cope with templates.

**Comment by bebraw** [comment] 2015-11-15 10:05
@acwong00 Can you see the problem still?

**Comment by bjfletcher** [comment] 2016-01-21 17:06
@bebraw @acwong00 I'm getting this error. I'm not using underscore templates - just plain HTML files.

**Comment by bebraw** [comment] 2016-01-21 17:19
@bjfletcher Can you set up a minimal example that illustrates the issue? Easier to debug.

**Comment by bjfletcher** [comment] 2016-01-21 17:46
@bebraw Bad HTML syntax. E.g., `<div class="foobar></div>` with a missing closing double quote.

**Comment by bjfletcher** [comment] 2016-01-21 17:47
A couple observations regarding that:

1. without the uglify plugin, it didn't complain;
2. with the uglify plugin, the error is very unclear/vague

**Comment by bebraw** [comment] 2016-01-21 17:50
@bjfletcher You could try bumping the version of html-minifier at [html-loader](https://github.com/webpack/html-loader) to 1.1.1. Assuming it's an upstream issue, that might fix it. If it doesn't fix it, even that's useful to know. Maybe we can prepare some test case to push upstream.

**Comment by bjfletcher** [comment] 2016-01-21 18:31
@bebraw Here, `html-loader` uses version 0.7.2 of `html-minifier`. That's quite old, isn't it?

BTW, just checked, this is the exact HTML that caused the issue:

`<div mdl-card mdl-shadow--2dp">`

**Comment by bebraw** [comment] 2016-01-21 18:57
@bjfletcher Yeah, that's really old. Fork html-loader and give a newer version of the dependency a go. :+1:

**Comment by bjfletcher** [comment] 2016-01-21 19:16
Just upgraded to 0.4 of `html-loader` which caused me to have 1.1.1 of `html-minifier`. Still got the same error:

```
ERROR in ../~/html-loader!../component/riot/src/main/Checkout/Checkout.html
Module build failed:
```

That's vague.  I know that the issue is poor HTML syntax but still... it'd be nice to see a clearer error message.

**Comment by andreialecu** [comment] 2016-01-28 15:42
I think I'm seeing the same problem, but more serious since it cannot be worked around.

Angular2 requires tags like `<a (click)="...">` which seem to trigger the same error when using `UglifyJsPlugin`.

**Comment by andreialecu** [comment] 2016-01-28 15:45
Related: https://github.com/kangax/html-minifier/issues/422

**Comment by bentedder** [comment] 2016-03-25 20:30
I had similar issues. Poorly formatted html was all I had!

**Comment by pavankumarkatakam** [comment] 2016-04-07 08:24
Hi @bentedder , I has also same issue but all is of simple `<` character, My code is fully normal html with some lines as shown below after remove the `<` which is before `16` its working fine.
 `<td translate> < 16</td>`

**Comment by pavankumarkatakam** [comment] 2016-04-07 08:46
And the problem is causing by uglify js, if i remove the uglify js in plugins its working fine.

**Comment by andreialecu** [comment] 2016-04-07 10:48
Try `&lt;` instead of `<` (which is invalid inside html blocks)

**Comment by bebraw** [comment] 2017-02-12 12:34
Can anyone confirm this against webpack 2?

**Comment by Aghassi** [comment] 2017-06-03 21:03
@bebraw I can (assuming the issue still stems). When running `webpack -p` to minimize templates as well as JS, I get a very obscure "module failed error: Parser Error" and it just outputs whatever it was trying to build. The way I got around this issue, for now, is setting `minimize` to `false` under:

```
plugins: [
        new webpack.LoaderOptionsPlugin({
            test: /\.html$/,
            options: {
                htmlLoader: {
                    ignoreCustomFragments: [/\{\{.*?}}/],
                    minimize: false
                },
            }
       })
   ]
```

It isn't ideal, but it does allow me to import HTML fragments in legacy Dojo code that we are trying to work on converting to ES6 and eventually migrating to React.

**Comment by evilebottnawi** [comment] 2018-03-21 09:28
Done in https://github.com/webpack/webpack/pull/5940. Should be fixed. Feel free to feedback if problem still exists. Thanks!

**Closed by evilebottnawi** 2018-03-21 09:28 UTC
Labels: P4: Nice To Have, S2: Inconvenient, S4: Broken, bug, webpack-2
