### ISSUE TITLE
webpack 4 dynamic import got exception in "(window.webpackJsonP = window.webpackJsonP || []).push" which "push" is not a function 

### ISSUE THREAD

**Issue by zslucky** [webpack/webpack#6985] opened 2018-04-08 08:55 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It blocked lazy module load. due to error "push" is not a function. It's not always occur. some times I can see `webpackJsonp` is an array in chrome console. and some times I can see `webpackJsonp` is a function in chrome console.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure what's the root cause. everything is correct when I using `webpack 3+`, after upgrade to `webpack 4`, this issue occurred.

**What is the expected behavior?**
Should load lazy module correctly.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a features

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

`OS: MacOS 10.13.3 `
`node: 8.9.4`
`webpack: 4.4.1`
`browser: chrome 65`

**Comment by Legends** [comment] 2018-04-08 17:49
Create a little repo, which reproduces your error and we will take a look. Thanks.

**Comment by zslucky** [comment] 2018-04-08 22:15
@Legends I'm not sure I can reproduce this issue in a new project, but I will add it here a little later

**Comment by sokra** [comment] 2018-04-09 07:54
Sounds like a caching problem in your browser. webpackJsonp was a function in webpack 3. It's now an array. Maybe you load old files?

**Comment by ezhikov** [comment] 2018-04-11 13:59
Have same issue, but i have multiple scripts on page built with different versions of webpack. Could it be the issue?

**Comment by Legends** [comment] 2018-04-11 14:08
@ezhikov 

> webpackJsonp was a function in webpack 3

If you have the same issue, then yes..

**Comment by sokra** [comment] 2018-04-12 12:55
> Have same issue, but i have multiple scripts on page built with different versions of webpack. Could it be the issue?

You should choose a unique jsonp function anyway with `output.jsonpFunction`.

**Comment by zslucky** [comment] 2018-04-12 14:09
Hi @sokra , I have a library build by `webpack 2+`, and now used in my `webpack 4+` project as a dynamic component. 

When I startup my project and go to a page which doesn't use this component, I can still found that `webpackJsonp` sometimes is function, and sometimes is array. 

So is that means no matter when I use the dynamic component, I must use  `output.jsonpFunction` to avoid this issue?

If so I will tried it.

**Comment by sokra** [comment] 2018-04-15 08:16
Not sure.

Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by zslucky** [comment] 2018-04-15 11:26
@sokra  thanks so much, I need some days to follow your ideas as other things blocked me, I will give a feedback here as soon as possible.

**Comment by pwang2** [comment] 2018-04-18 22:27
Thanks @sokra , rename output.jsonpFunction to a different string fixes the error here.  But this only works I own the code.  I could see cases user have no choice when introducing libraries from other vendors. Reminds me `Array.prototype.includes vs MooTools`

I am vigilant seeing this as webpack4 seems **breaks the existing web** by re-patching window object here.  I think it is worth an analysis here. In any case, the master's work is awesome. 

><h1>With great power comes great responsibility</h1>

**Comment by glebmachine** [comment] 2018-05-06 10:54
I found that, i'm unable to use webpack2/3 bundled scripts together with webpack 4 project, because they replace window["webpackJsonp"] array with function and brokes things down.

That's so frustrating me now. I can't control third party webpack version...

**Comment by glebmachine** [comment] 2018-05-06 13:07
@sokra Is it possible to move from `webpackJsonp` to `MODERN_WEBPACK_webpackJsonp` or something like this (to keeps backward compatibility?)

**Comment by glebmachine** [comment] 2018-05-06 13:14
I'm found `output.jsonpFunction`

**Comment by ggriffithsIDBS** [comment] 2018-07-18 20:39
Came across a scenario where re-using the same name and modifying type is an issue:
- We have an app, built with Webpack 3.
- We have run time "plugins" that are built with Webpack 4 and export themselves to AMD, so we can consume in the App with some JS at run time.

Found that cannot use dynamic imports in the plugins bundled with Webpack 4 because they share the same window.webpackJsonp, which used to be a function and is now an array :(

**Comment by mrj0** [comment] 2018-08-28 03:18
We ran across this today after intermittent user reports on Evite.com of pages not loading. After inspection looks like third party code loaded something with webpack3, but that's not yet proven. It was intermittent for us and I didn't get my hands on a device that could reproduce it. 

Basically, anybody running 3rd party code should use `output.jsonpFunction` to avoid conflicts. Thanks for this bug, I would not have found that configuration option on my own - `jsonpFunction` would not have caught my eye, since I was not looking for anything to do with jsonp or a function.

I would agree the default should be changed so more people don't run into this.

**Comment by benqy** [comment] 2018-10-12 03:00
same problem if  i use splitChunks and multi version webpack

**Comment by yordis** [comment] 2019-02-15 19:41
### The issue

Our issue, having Webpack 3 and 4 outputs on the same page. Since Webpack 4 uses an array instead of a function.

### Solution

Change `output.jsonpFunction` value to something else than `webpackJsonP`.

**Comment by prakulgupta** [comment] 2019-06-13 15:12
@yordis  your solution works. 
I just added below content inside webpack.config.json file of angular 5 application which uses webpack 3. 
  output: {
        jsonpFunction:"webpackJsonpFunction3"
    }

My use case was - I had an angular 7 web component bundle which looks for webpack 4 and it was being consumed in application which uses webpack 3.

**Comment by manuhornung** [comment] 2019-09-10 17:53
This issue broke one of two apps which shared a page for us, even though we set an `output.library`. Setting an explicit `otuput.jsonpFunction` helped, but I'm not sure if that should be the case.

**Should the library name also automatically be appended to the `output.jsonpFunction` if the `output.library` is an *array*?**

This isn't done because the `library` is checked for being a `string` in 
https://github.com/webpack/webpack/blob/9741565588c64f82d942ec1096f0296ffd9443f4/lib/WebpackOptionsDefaulter.js#L120-L124
https://github.com/webpack/webpack/blob/9741565588c64f82d942ec1096f0296ffd9443f4/lib/Template.js#L68

It was not obvious to me that I have to manually set an `output.jsonpFunction` when using an *array-type* `output.library`. It's not mentioned as an exception on https://webpack.js.org/configuration/output/#outputjsonpfunction either.

For reference: this is the relevant config part in broken form: 
```
	output: {
        path: paths.clientOutputDirectory,
        filename: 'fragment.js',
        library: ['fragments', name],
        libraryTarget: 'umd',
        globalObject: "(typeof self != 'undefined' ? self : this)",
    },
```
and fixed:
```
	output: {
        path: paths.clientOutputDirectory,
        filename: 'fragment.js',
        library: ['fragments', name],
        libraryTarget: 'umd',
        globalObject: "(typeof self != 'undefined' ? self : this)",
        jsonpFunction: `webpackJsonp_${name}`,
    },
```

**Comment by evilebottnawi** [comment] 2019-09-10 18:10
@manuhornung thanks for issue, can you create minimum reproducible test repo? Looks like a bug

**Comment by malykhinvi** [comment] 2019-10-02 07:40
Guys, here is an example of this failure: https://twitter.com/stripestatus/status/1179172007218274304
> Some additional details here: sites utilizing Webpack on the front-end likely encountered errors as Stripe.js overwrote the global webpackJsonp object.

**Comment by alexander-akait** [comment] 2021-01-18 11:32
bump

**Comment by alexander-akait** [comment] 2021-01-29 14:23
Fixed in webpack@5 for libraries and standalone apps, we added `uniqueName` https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L550, feel free to feedback

**Closed by alexander-akait** 2021-01-29 14:23 UTC
Labels: Send a PR
