### ISSUE TITLE
Remove support for AMD by default in Webpack 2

### ISSUE THREAD

**Issue by andreypopp** [webpack/webpack#3017] opened 2016-09-19 18:28 UTC
**I'm submitting a feature request**

**Webpack version:**
2.x

**Current behavior:**
Webpack produces code which throws an error when it encounters `define` identifier in source code.

**Expected/desired behavior:**
Webpack doesn't treat `define` identifier in any custom way and make no assumptions about it unless it is configured with `AMDModulePlugin` (or something like that).

**What is the motivation / use case for changing the behavior?**
AMD isn't used widely anymore, most of the code is distributed through npm and is in the format of CommonJS modules. Therefore it does make sense to make AMD support opt-in rather than having it enabled by default.

**Comment by sokra** [comment] 2016-09-19 20:50
I think it's too early to remove AMD. Easy migration from requirejs codebase to webpack is (in my opinion) one mayor reason for people switching.

But I would love to hear more opinions on this topic...

**Comment by andreypopp** [comment] 2016-09-19 21:55
> Easy migration from requirejs codebase to webpack is (in my opinion) one mayor reason for people switching.

My intuition speaks against it but it would be interesting to see the numbers of AMD usage.

Anyway, we can provide a separate section in docs on how to migrate to AMD (just add a plugin, right?)—AMD is a legacy and supporting it by default don't make much sense, I think.

**Comment by aluanhaddad** [comment] 2017-01-08 07:24
> AMD isn't used widely anymore, most of the code is distributed through npm and is in the format of CommonJS modules. Therefore it does make sense to make AMD support opt-in rather than having it enabled by default.

I look forward to the day when both AMD and CommonJS are considered legacy formats, especially for browser based work.

That said, when I have to work on a Webpack project (my preference is for loaders, not blunders, no offense intended) I find that the AMD support makes me feel a bit more at home.

**Comment by dcworldwide** [comment] 2017-01-08 10:45
Using AMD on a large enterprise project with esri js api (who do not support commonjs).

**Comment by Vanuan** [comment] 2017-03-11 07:54
See also discussion in #4465

**Comment by Vanuan** [comment] 2017-03-11 08:02
@dcworldwide the issue is about removing it by default, no removing ability to optionally load it. It's users who decide which modules should they use. If people want to load ancient packages it should be opt-in, not opt-out.

**Comment by aluanhaddad** [comment] 2017-03-11 13:49
@Vanuan indeed but ESRI's leaflet integration is missing a lot of functionality as compared to its ArcGIS APIs for JavaScript.

That said, I don't think anyone likes working with the ArcGIS APIs for JavaScript because of the way that ESRI distributes them. This has much more to do with their build process, their code obfuscation process, and the overall complexity of those APIs (excessive emphasis on class-based programming).

None of this has anything to do with AMD.

**Comment by dcworldwide** [comment] 2017-03-11 14:54
Let's not waste time or confuse this conversation by talking about the specifics of mapping libraries.

**Comment by Vanuan** [comment] 2017-03-11 17:46
Is there at least a way to opt-out? [imports-loader](https://github.com/webpack-contrib/imports-loader) doesn't seem to work with webpack2.

**Comment by jdalton** [comment] 2017-03-11 20:40
I'm with @andreypopp and @Vanuan. Opting-in to AMD would be a better fit. I've seen several folks [complain about](https://github.com/lodash/lodash/issues/3052) the side effects of [Webpack's AMD transforms](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829) on Lodash issues too.

**Comment by sokra** [comment] 2017-03-12 16:05
You can opt-out.

``` js
module: {
  rules: [
    { parser: { amd: false } }
  ]
}
```

Feel free to include a `include` property to limit the scope.

**Comment by jdalton** [comment] 2017-03-12 16:26
> You can opt-out.

I'm glad there's a way to disable it but this issue is about changing it to opt-in by default.

**Comment by jdalton** [comment] 2017-03-12 16:38
Would an opt-in by default change be something that's doable for v3?

**Comment by imolorhe** [comment] 2017-03-27 14:52
I think the opt-out configuration provided by @sokra should be in the docs, somewhere.

**Comment by FranzSkuffka** [comment] 2017-05-30 16:19
I have a bad time trying to figured out where exactly I should put this. I currently have the follong `rules` config in my webpack config:
```
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loaders: ['babel-loader']
        },
        {
          test: /\.css$/,
          loaders: [ 'style-loader', 'css-loader' ]
        },
        {
          test: /\.vue$/,
          loader: 'vue-loader'
        }
      ]
```
I tried splitting up into rules and loaders, adding `parsers` object as a separate array entry and as a prop inside the `js` rule. All to no avail. HALP!

**Comment by Vanuan** [comment] 2017-05-30 16:37
This should work:

      rules: [
        {
          parser: {
            amd: false,
          }
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loaders: ['babel-loader']
        },
        {
          test: /\.css$/,
          loaders: [ 'style-loader', 'css-loader' ]
        },
        {
          test: /\.vue$/,
          loader: 'vue-loader'
        }
      ]

**Comment by cheshireoctopus** [comment] 2017-08-22 19:58
Having trouble understanding `parser: { amd: false }`, does this approach yield the same result if you used `noParse` https://webpack.js.org/configuration/module/#module-noparse?

**Comment by Vanuan** [comment] 2017-08-24 14:22
No

**Comment by dennisli92** [comment] 2018-02-08 00:33
Apologies if this is the wrong thread, but are there other situations where in webpack might modify the global context? I wasted quite a lot of time trying to figure out why my webpack bundle was modifying the global context, until I went through my libraries one by one and stumbled on this thread (via https://github.com/lodash/lodash/issues/3052)

Perhaps a warning at least during builds that amd parsing is enabled would be very helpful!

(I'm writing a chrome extension which injects code into sites, and it turned out the amd loaded version of lodash was breaking sites that use `window._`).

**Comment by rafde** [comment] 2018-06-21 17:14
I hope this doesn't happen. I work in a code base that has a lot of modules that load through AMD. If AMD support is removed, I can no longer upgrade webpack. 
Moving to `import` has been a slow process because of the large amount of modules we have in the code base that still use AMD and making those updates hasn't been a product priority. Tis the nature of working in an enterprise product.
webpack has monopolized bundling because it does an awesome job supporting all formats.
Please don't remove support for AMD.
![Sad Kitten](https://scontent-lax3-1.cdninstagram.com/vp/dc99fe01297d33c62beeae2a3d119658/5BAFFC17/t51.2885-15/e35/11421828_784607148303137_288351032_n.jpg)

**Comment by Vanuan** [comment] 2018-06-21 17:49
@rafde This issue is not about removing support for AMD. It's about changing the defaults. You could still use legacy AMD using this option:

```
module: {
  rules: [
    { parser: { amd: false } }
  ]
}
```

**Comment by rafde** [comment] 2018-06-21 17:58
I read the title more than anything else. Default opt-out of amd makes more sense. Not sure why have it in the rules. Could just be
```js
module: {
  parser: {
    amd: true,
  }
}
```

**Comment by Vanuan** [comment] 2018-06-21 18:05
Yeah, "remove by default" is kind of confusing title. "Make it opt-in" or "change defaults" is better one.

**Comment by FranzSkuffka** [comment] 2018-06-21 18:19
@rafde - converting `require` to `import` should be as simple as doing find-and-replace operations.

**Comment by rafde** [comment] 2018-06-21 18:41
Your suggestion is for small projects. There is a lot of regression involved in the project is work in. I’ve looked into it enough to know it’s going to raise too many problems for the QA team test against. Small and progressive  changes are easier to handle.

**Comment by mgol** [comment] 2019-01-23 22:30
Webpack 2 is long in the past and version 5 is coming. Is this a good time to revisit the defaults for that version?

**Comment by evilebottnawi** [comment] 2020-09-02 13:36
Let's close in favor https://webpack.js.org/configuration/other-options/#amd, you can use `amd: false` to disable AMD support  or like this https://github.com/webpack/webpack/issues/3017#issuecomment-285954512. Some developers still use AMD packages today :disappointed:

**Closed by evilebottnawi** 2020-09-02 13:36 UTC
Labels: P3: Important, RFC/Proposal, S2: Inconvenient, X3: discussion required, enhancement

**Comment by Vanuan** [comment] 2020-09-02 23:51
No. Those people who use AMD should opt in. They should feel pain, not people who use the latest and greatest features.

**Comment by evilebottnawi** [comment] 2020-09-03 10:58
@Vanuan nobody should should feel pain, nobody forbids you to use the latest and greatest features

**Comment by Vanuan** [comment] 2020-09-03 12:48
@evilebottnawi I felt pain because of the need to opt out of "amd"

**Comment by evilebottnawi** [comment] 2020-09-03 13:00
@Vanuan What is package broken, can you provide more context?

**Comment by Vanuan** [comment] 2020-09-03 14:06
@evilebottnawi Wasn't it already mentioned multiple times? https://github.com/webpack/webpack/issues/4465

**Comment by evilebottnawi** [comment] 2020-09-03 14:39
@Vanuan because only `lodash` had this problem, also I can't reproduce it again, can you provide reproducible test repo or examples?
