### ISSUE TITLE
Federated Modules: harmony import a package Miss `["default"]` if the package shared

### ISSUE THREAD

**Issue by dexbol** [webpack/webpack#17132] opened 2023-05-04 08:21 UTC
# Bug report

**What is the current behavior?**
I installed a package named `redux-register` , and I just import it and print it, like this:
```javascript
import Register from 'reudx-register'

alert(typeof Register); // function
```

Register is a function and Look at `src_index_js.js` that webpack created:

```javascript
var redux_register__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! redux-register */ "./node_modules/redux-register/lib/index.js");
alert(typeof redux_register__WEBPACK_IMPORTED_MODULE_0__["default"]);
```
Because of redux-register was a esm package, therefore webpack add `["default"]` automatically.

But, If i shared the package like this:

```javascript
new webpack.container.ModuleFederationPlugin({
    runtime: 'test',
    shared: {
        'redux-register': {
            singleton: true,
        },
    },
}),
```
`Register` will be a `object Module`. because `["default"]` was missing:

```javascript
var redux_register__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! redux-register */ "webpack/sharing/consume/default/redux-register/redux-register");
alert(typeof redux_register__WEBPACK_IMPORTED_MODULE_0__ );
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Reproducing repository: https://github.com/dexbol/module-federation-test .
npm install && npm run start

**What is the expected behavior?**
Whether or not using Module Federation shared package, the `Register` should be a function. 

**Other relevant information:**
webpack version:  v5.82.0
Node.js version: v20.0.0
Operating System: MacOS
Additional tools: -

**Comment by alexander-akait** [comment] 2023-05-05 21:19
Duplicate of https://github.com/webpack/webpack/issues/16125, PR welcome

**Closed by alexander-akait** 2023-05-05 21:19 UTC
