### ISSUE TITLE
Paper.js with webpack

### ISSUE THREAD

**Issue by HriBB** [webpack/webpack#1133] opened 2015-06-01 12:16 UTC
I don't know if this is the right place, but I'm out of options, so ...

I'm trying to load Paper.js with webpack. I already added json-loader to webpack.config.js, but it still does not work.

```bash
bojan@linux:~/www/react/MyApp$ gulp
[13:15:54] Using gulpfile ~/www/react/MyApp/gulpfile.js
[13:15:54] Starting 'build:watch'...
[13:15:54] Starting 'clean'...
[13:15:54] Finished 'clean' after 15 ms
[13:15:54] Starting 'build'...
[13:15:54] Starting 'vendor'...
[13:15:54] Starting 'assets'...
[13:15:54] Starting 'bundle'...
[13:15:54] Finished 'vendor' after 132 ms
    Asset    Size  Chunks             Chunk Names
server.js  570 kB       0  [emitted]  main
[13:16:02] Finished 'bundle' after 7.92 s
[13:16:05] 'assets' all files 30.95 kB
[13:16:05] Finished 'assets' after 11 s
[13:16:05] Finished 'build' after 11 s
[13:16:05] Finished 'build:watch' after 11 s
[13:16:05] Starting 'serve'...
paper { settings: { applyMatrix: true, handleSize: 4, hitTolerance: 0 },
  project: null,
  projects: [],
  tools: [],
  palettes: [],
  _id: 0 }
[13:16:13] Finished 'serve' after 8.28 s
[13:16:13] Starting 'sync'...
 Asset     Size  Chunks             Chunk Names
app.js  10.8 MB       0  [emitted]  main

WARNING in ./~/paper/dist/paper-node.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/paper/dist/paper-node.js
Critical dependencies:
12263:19-26 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/paper/dist/paper-node.js 12263:19-26

WARNING in ./~/paper/~/jsdom/~/acorn-globals/~/acorn/dist/walk.js
Critical dependencies:
1:503-510 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/paper/~/jsdom/~/acorn-globals/~/acorn/dist/walk.js 1:503-510

WARNING in ./~/paper/~/jsdom/~/acorn-globals/~/acorn/dist/acorn.js
Critical dependencies:
1:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/paper/~/jsdom/~/acorn-globals/~/acorn/dist/acorn.js 1:478-485

WARNING in ./~/paper/~/request/~/hawk/~/hoek/lib/index.js
Critical dependencies:
403:34-60 the request of a dependency is an expression
 @ ./~/paper/~/request/~/hawk/~/hoek/lib/index.js 403:34-60

ERROR in ./~/paper/~/canvas/lib/bindings.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in /home/bojan/www/react/MyApp/node_modules/paper/node_modules/canvas/lib
 @ ./~/paper/~/canvas/lib/bindings.js 2:17-51
[RSK] Proxying: http://localhost:5000
[RSK] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.104:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.104:3001
 --------------------------------------
[13:16:14] Finished 'sync' after 674 ms
[13:16:14] Starting 'default'...
[13:16:14] Finished 'default' after 10 μs
[RSK] File changed: build/app.js
```

Any ideas on how to fix this error?

**Comment by HriBB** [comment] 2015-06-01 13:42
OK so I was missing a node-loader. After I add it it builds with warning but now I get an error in the browser

```
Uncaught Error: Cannot open /home/bojan/www/react/MyApp/node_modules/paper/node_modules/canvas/build/Release/canvas.node: TypeError: process.dlopen is not a function
```

**Comment by cloppy** [comment] 2015-06-02 13:15
The `node-loader` only works in a node environment. To use node and it's third party modules, you can use https://github.com/nwjs/nw.js/ for example. It's based on chromium and includes the node runtime.

Nonetheless, the `node-loader` is currently broken.

**Comment by grabbou** [comment] 2015-06-04 16:08
Duplicate of #1053

**Comment by sokra** [comment] 2015-06-15 08:11
Try to use https://github.com/paperjs/paper.js/blob/master/dist/paper-full.js instead of `https://github.com/paperjs/paper.js/blob/master/dist/paper-node.js when using it in a browser environment.

You can do this in your config with `resolve.alias`

or the package author can do this in the package.json with the [browser field](https://gist.github.com/defunctzombie/4339901). (recommended)

**Comment by HriBB** [comment] 2015-06-16 00:45
Hey guys thanks for the info. I will try this tomorrow. Will let you know once I experiment a little bit. Question is, how to do isomorphic canvas with paperjs? Is this even possible?

**Closed** 2015-06-16 00:45 UTC
