### ISSUE TITLE
Populate sourceRoot for benefit of source-maps consumed by Node.js

### ISSUE THREAD

**Issue by bcoe** [webpack/webpack#11882] opened 2020-10-30 14:03 UTC
## Feature request

👋 I'm a developer who's been working on [adding source map support](https://nodejs.medium.com/source-maps-in-node-js-482872b56116) to Node.js stack traces.

I've noticed that webpack's source maps use special pseudo paths, which look something like this:

**webpack:///./index.js**

When these source maps are loaded in Node.js, it's difficult to know what path `./index.js` should be resolved relative to. The specification indictes:

> the sources are resolved relative to the SourceMap (like resolving script src in a html document).

Which to me would suggest `dist/index.js`, vs., the sources's actual location `dist/../index.js`.

**What is the expected behavior?**

It would be nice to be able to read a variable like `sourceRoot`, to determine the root path of the JavaScript file prior to transpilation.

**What is motivation or use case for adding/changing the behavior?**

Folks use webpack to create bundles of Node.js applications that are run outside of the browser, it would be nice for these people to have accurate stack traces.

**How should this be implemented in your opinion?**

When specifying `--target node`, it would be useful if source paths either did not use the `webpack://` pseudo path, or if the `sourceRoot` variable was populated (_populating `sourceRoot` would potentially break other implementations reading the sourceMap_).

**Are you willing to work on this yourself?**

yes

Refs: https://github.com/nodejs/node/issues/35325

**Comment by evilebottnawi** [comment] 2020-10-30 14:06
It was answered a lot of time... Do you try using search?

**Comment by evilebottnawi** [comment] 2020-10-30 14:07
Duplicate of https://github.com/webpack/webpack/issues/9601

**Closed by evilebottnawi** 2020-10-30 14:07 UTC
