### ISSUE TITLE
Re-exported JSON imports are undefined

### ISSUE THREAD

**Issue by afhole** [webpack/webpack#6700] opened 2018-03-07 18:10 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a module that imports some JSON objects and re-exports them as named exports, e.g.:

```
import someJson1 from './some-json-1';
import someJson2 from './some-json-2';

export {
  someJson1,
  someJson2
};
```

Then when I import these exports in another module they are undefined, e.g.:
```
import { someJson1, someJson2 } from 'jsonModule';
```
`someJson1` and `someJson2` are now undefined.

However, the two imports are valid within the jsonModule, and if I copy them to local variables and then export those then it does work, e.g.:

```
import someJson1_ from './some-json-1';
import someJson2_ from './some-json-2';

const someJson1 = someJson1_;
const someJson2 = someJson2_;

export {
  someJson1,
  someJson2
};
```

Now when I import these exports in an other module (as above) they are no longer undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**
See current behaviour above

**What is the expected behavior?**
I expect imported JSON should be able to be re-exported without it being undefined, and without having to copy the imports before re-exporting them.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack@^4.1.0
macOS 10.13.3 (17D102)
node v9.7.1

**Comment by michael-ciniawsky** [comment] 2018-03-07 18:43
You need to reassign a `ImportDeclaration`  since they are (live) bindings (in theory)

```js
export { a } from './some.json'
export { b } from './other.json' 
```

should work

**Comment by afhole** [comment] 2018-03-07 18:58
@michael-ciniawsky Thanks for your reply. Using your example above I get:

`"export 'a' was not found in './some.json'`
as there is no property `a` in some.json.
I would like to import the whole json file as `a`. If I use instead `export { default as a } from './some.json';` then `a` is still undefined when I try to import it.

Is it not possible to import a JSON file as a single object? It used to work with Webpack <4.

Thanks in advance

**Comment by michael-ciniawsky** [comment] 2018-03-07 19:28
**a.json**
```js
{
   "nameA": "A"
}
```

**b.json**
```js
{
   "nameB": "B"
}
```

**export.js**
```
export * from './a.json'
export * from './b.json'
```

**import.js**
```js
import { nameA, nameB } from './x.js'

console.log(nameA, nameB)
// => 'A', 'B'
```

Otherwise you need to reassign it 

```js
import a from './a.json'
import b from './b.json'

const c = Object.assign({}, a, b)

export default c
```
```js
import c from 'c.js'

console.log(c)
// => { a: '', b: '' } {Object}
```

ES Modules (especially `export`) syntax is very weird... :P

**Comment by afhole** [comment] 2018-03-07 19:49
Thanks again for your reply, weird indeed! I think I see how it works now. I'm just confused how it used to work, perhaps babel was allowing the incorrect imports? I still don't quite follow how an import would work locally within a module but then just be undefined when exported, with no error.

**Comment by afhole** [comment] 2018-03-07 20:06
This is very strange, I tried importing a JS file alongside my JSON imports, and now all the JSON imports have started working:

```
import someJson1 from './some-json-1';
import someJson2 from './some-json-2';
import foo from './testExport.js';

export {
  foo
  someJson1,
  someJson2
};
```

Now I can import e.g. someJson1 in another file and it is not undefined!
Furthermore, if I `import * as foo from 'jsonModule';` then it includes an additional export named `default`.

**Comment by michael-ciniawsky** [comment] 2018-03-07 20:07
`JSON` got it's own `module.type` in `webpack >= v4.0.0`, before `v4.0.0` one needed a loader to add JSON support to `webpack`, which always 'constructed' a JS Module which then was parsed by `webpack` as JS and things like `import { a, b, c } from 'json-loader!./file.json' worked like destructing an `{Object}` 

```js
export default loader (json) {
  return 'module.exports = '  + JSON.stringify(json)
}
``` 

This is no longer the case now and the `JSONParser` uses ES2015 Module Semantics to enable static analysis capabilities (e.g 'tree-shaking')  etc etc. The `json-loader` always imported the whole JSON file

**Comment by michael-ciniawsky** [comment] 2018-03-07 20:08
hmm... no idea about that. I'm reopening just in case :)

**Comment by afhole** [comment] 2018-03-07 20:08
Further to my previous comment, it is the import of the .js file that makes the JSON exports work, the .js import does not have to be exported

**Comment by sokra** [comment] 2018-03-07 21:02
This could be a bug when reexporting JSON.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by afhole** [comment] 2018-03-07 21:38
Thanks - I will put together a repro example and let you know

**Comment by afhole** [comment] 2018-03-08 15:48
So far my attempt to reproduce the issue has been unsuccessful. In fact it works exactly how I expected it to, e.g.

```
import jsonDataA from '../data/jsonDataA.json';
import jsonDataB from '../data/jsonDataB.json';

export {
	jsonDataA,
	jsonDataB
};
```
The JSON data is then available to import:
```
import { jsonDataA, jsonDataB } from './json.js';

console.log('Importing JSON data:');

console.log({
	jsonDataA,
	jsonDataB
});
```

Is this the correct behaviour? It is contrary to the description in the comments above.
I will keep trying to work out what's different between my production repo and the example, I wonder if babel is interfering somehow.

**Comment by sokra** [comment] 2018-03-08 16:07
Looks correct to me.

**Comment by afhole** [comment] 2018-03-08 16:08
OK that is good then, I thought that was the intended behaviour but @michael-ciniawsky suggested otherwise. I will continue trying to replicate.

**Comment by afhole** [comment] 2018-03-08 16:41
OK I have a working repro: https://github.com/afhole/webpack-6700

The issue seems to occur when using babel-loader to load the .js files - I have have excluded the json.js file from babel-loader to match my production repo (the JSON module I am using is used as an NPM dependency)

**Comment by michael-ciniawsky** [comment] 2018-03-08 17:03
```js
|- a.json
|- b.json
|- json.js
|– entry.js
```

**a.json**
```
{
  "a": "A"
}
```

**b. json**
```
{
   "b": "B"
}
```

**json.js**
```js
import a from './a.json'
import b from './b.json'

export { a, b }
```

**entry.js**
```js
import { a, b } from './json.js'

console.log({ a, b })
```

![json](https://user-images.githubusercontent.com/5419992/37163884-340369e0-22f9-11e8-9dc6-9c4ad49855d7.png)

https://github.com/afhole/webpack-6700/blob/master/src/json.js#L4

![webpack-6700](https://user-images.githubusercontent.com/5419992/37164494-c038d9bc-22fa-11e8-9c0a-ca5bc528b40d.png)

https://github.com/afhole/webpack-6700/blob/master/src/json.js#L4 works because you reassign the `ImportSpecifier`

**Comment by afhole** [comment] 2018-03-08 17:05
But if I stop using babel-loader then it all just works as I initially expected

**Comment by michael-ciniawsky** [comment] 2018-03-08 17:14
I didn't use any loader for the bare reproduction... Also `module.rules[i].test` checks for `/\.js/` in your  example, so the `.json` imports won't processed by `babel-loader`. The issue must be somewhere else

**Comment by afhole** [comment] 2018-03-08 17:19
I mean if I stop using babel-loader then I don't see the behaviour you saw in your repro, all of the exports come through with nothing undefined. Can you share your repro?

**Comment by afhole** [comment] 2018-03-08 17:24
Here is the repro with babel-loader disabled, and all the JSON exports come through ok. Is this a bug with webpack?
https://github.com/afhole/webpack-6700/tree/no-babel-loader

**Comment by michael-ciniawsky** [comment] 2018-03-08 17:30
**webpack.config.js**
```
module.exports = {
   context: path.resolve(__dirname, 'src'),
   entry: {
      index: './entry.js'
   },
}
```

+ files from https://github.com/webpack/webpack/issues/6700#issuecomment-371552743. That's it :)

```
// => { a: undefined, b: undefined }
```

**Comment by afhole** [comment] 2018-03-08 17:37
Thanks. How are you building/running it? Just trying to test it here

**Comment by afhole** [comment] 2018-03-08 17:39
@sokra do you agree with @michael-ciniawsky that what I am trying to do is not supposed to work?

**Comment by afhole** [comment] 2018-03-08 17:48
@michael-ciniawsky I built your repro with webpack and ran it in node and got the following output:
```
└> node dist/index.js
{ a: { a: 'A' }, b: { b: 'B' } }
```

**Comment by afhole** [comment] 2018-03-08 17:52
I get the same in Chrome if I add the bundle in a script tag
![screen shot 2018-03-08 at 17 52 18](https://user-images.githubusercontent.com/1911055/37167330-8228e000-22f9-11e8-877d-5f923e02cb35.png)

**Comment by michael-ciniawsky** [comment] 2018-03-08 18:05
Could you try with `'mode: 'development'` ? With  `mode: 'production'` it indeed 'works'  and I can reproduce it for both `node` and the `browser`

**Comment by afhole** [comment] 2018-03-08 18:08
Ah yes I now see the same behaviour in development mode. I wonder why it is different in production mode?

**Comment by michael-ciniawsky** [comment] 2018-03-08 18:18
¯\_(ツ)_/¯ `mode: 'production'` applies the `ModuleConcatenationPlugin` which scope hoists and concatenates modules, maybe this is the correct behavior there then or it's a bug, but there seems to be other/additional plugins applied for `production` aswell since `node bundle.js` with `mode: development` and `target: 'web'` (default) also won't execute normally...

**Comment by sokra** [comment] 2018-03-08 22:21
I can confirm that this is a bug

**Comment by afhole** [comment] 2018-03-09 13:00
Is the bug related to the fact that what I was attempting works in production mode, or that it doesn't work in development mode?

**Comment by nveenjain** [comment] 2018-03-11 13:22
Is this issue open for PR? I'm willing to work on it.

**Comment by sokra** [comment] 2018-03-13 08:49
@nveenjain yep.

ModuleConcatenationPlugin seem to only handle two of the 3 possible values of `module.buildMeta.exportsType`.

**Closed** 2018-03-20 12:05 UTC
