### ISSUE TITLE
Hot Module Replacement has problem working with dropbox

### ISSUE THREAD

**Issue by wangzhen10** [webpack/webpack#3206] opened 2016-10-29 07:17 UTC
I'm submitting a bug report

Webpack version:
1.13.3

Please tell us about your environment:
Windows 7

Current behavior:
Hot Module Replacement does not work when my project is in my dropbox named "dropbox(person)". But after I change the name to "dropbox" without"()". It does work.

I spend 2 days to figure out this problem.  I just want to share this to others. So they do not need to waste time on this.

**Comment by SpaceK33z** [comment] 2016-10-31 11:24
Dupe of #2258.

**Closed by SpaceK33z** 2016-10-31 11:24 UTC
Labels: bug, P4: Nice To Have, S4: Broken, X4: work required
