### ISSUE TITLE
FS error when i start the output of webpack

### ISSUE THREAD

**Issue by NicholasFalcone** [webpack/webpack#12776] opened 2021-02-24 17:23 UTC
# Bug report

Hi,
I got the following error when I try to run my "build" API server after the inclusion of mjml
```
fs.js:177
  return (stats[1/* mode */] & S_IFMT) === fileType;
               ^
TypeError: Cannot read property '1' of undefined
```

My current configuration:

**Webpack.js**
```
const path = require('path');
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: "api.server.js"
  },
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  module: {
    rules: [      
      // JavaScript      
      {        
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          'babel-loader'
        ],
      },
    ],
  },	
};
```

**.babelrc**
```
{
    "presets": ["@babel/preset-env"],
    "plugins": ["@babel/plugin-proposal-class-properties"]
}
```
Can some help me figure out the solution?
I have found nothing online
Thank you

**What is the current behavior?**
Webpack complete the building behaviour, but when I try to start the output this following error come
```
fs.js:177
  return (stats[1/* mode */] & S_IFMT) === fileType;
               ^
TypeError: Cannot read property '1' of undefined
``` 

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Everything working fine...

**Other relevant information:**
webpack version:   
Node.js version: v12.18.2
Operating System: Ubuntu 20.10
Additional tools: mjml, handleberse

**Comment by alexander-akait** [comment] 2021-02-24 17:34
> If the current behaviour is a bug, please provide the steps to reproduce.
> webpack version:

Do not ignore this

Sorry won't fix

**Closed by alexander-akait** 2021-02-24 17:34 UTC

**Comment by NicholasFalcone** [comment] 2021-02-24 17:43
> > If the current behaviour is a bug, please provide the steps to reproduce.
> > webpack version:
> 
> Do not ignore this
> 
> Sorry won't fix, `fs.js:177` from `fs`, so you have a bug in code (I think)
> 
> If you real want to good answer, please provide more information to help you

Sorry, I miss that bullet.
This behaviour appears when I include mjml on my project, if i remove the reference to this package everything work fine.

I found this guy with a relative issue [https://github.com/yarnpkg/berry/issues/1678](ref)

**Comment by alexander-akait** [comment] 2021-02-24 17:45
Maybe you can provide minimum reproducible test repo?

**Comment by NicholasFalcone** [comment] 2021-02-24 18:01
Sure
[https://github.com/NicholasFalcone/webpack_issues__12776](repo)

**Comment by NicholasFalcone** [comment] 2021-02-24 18:05
my bad, try now

**Comment by alexander-akait** [comment] 2021-02-24 18:17
Why do you try to bundle `uglify-js`?

**Comment by NicholasFalcone** [comment] 2021-02-24 18:27
On that project for no reason, it was an error when copying and pasting to create the sample repository. But I think it must not be the reason for the mistake.

**Comment by alexander-akait** [comment] 2021-02-24 18:31
`uglify-js` is the problem here, here problem https://github.com/mishoo/UglifyJS/blob/master/tools/node.js#L3 is not safe to use, you can keep name of modules and it will fix the problem...

**Comment by NicholasFalcone** [comment] 2021-02-24 18:49
I try to remove ```uglify-js``` from the test repo, but I keep getting the error.
 Some idea? Have you been able to make it work?

**Comment by alexander-akait** [comment] 2021-02-25 11:29
@NicholasFalcone Can you update repo, I can't reproduce it without `uglify-js`
