### ISSUE TITLE
Webpack should show environment clearly when running

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4886] opened 2017-05-17 16:54 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Webpack shows `--env` in the CLI call but it's not clear enough.

**What is the expected behavior?**

It would be clearer to show env in the build output like this:

```bash
...
Version: webpack 2.5.1
Environment: production
Time: 4632ms
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current behavior is a bit unclear.

**Comment by welll** [comment] 2017-05-20 20:51
@jbottigliero are you already doing that, right?

**Comment by jbottigliero** [comment] 2017-05-21 16:16
@welll  – I've got a PR open (#4903) that requires a few changes but should be knocked out soon.

**Comment by nikshepsvn** [comment] 2017-09-23 05:49
is this still open by any chance?

**Comment by jbottigliero** [comment] 2017-09-25 19:09
@nikshepsvn (cc. @welll)  – the PR #4903 had my latest revisions. IIRC, I ran into some issues once I began to implement more verbose tests and wound up closing the PR until I could devote some time to it.

It's been awhile since I've actually taken a look at the code in that branch/PR. But, let me pull it down and try to give a more specific (helpful) update based on the changes.

**Comment by nikshepsvn** [comment] 2017-09-25 22:39
@jbottigliero sounds good, thank you! would love to continue on what you were working on if you don't mind :)

**Comment by jbottigliero** [comment] 2017-09-26 04:33
I've updated the base branch of #4903 to `webpack-2` as this is what the original change-set was developed against. However, the changes in _that_ PR are a bit problematic. The update to `bin/webpack.js` was setting the `outputOptions.env` using the `--env` arguments directly. That means the `lib/Stats.js` component would output the `Environment ...` in the case a of the following configuration: `stats: { env: false }` with a truth-y `--env` argument.  I don't think this is expected, or intended behavior – this seems like where I left off.

I've cleaned up the implementation in a new branch. Here is _that_ diff: https://github.com/webpack/webpack/compare/webpack-2...jbottigliero:issue-4886-2.4.1

Now, although the issue is tagged as `webpack-2`, I've taken a look at the latest master (currently `3.6.0`) and it looks like a similar solution would be viable (looks like the `argv.env` handling was just abstracted a bit, so it's not quite a clean-merge). ...but, I'm not exactly sure how the webpack team would like me to propose those changes (assuming this is desired for 3+). Get this updated version (presumably as a new PR) merged and cherry-pick it on to the latest as another PR? Create an entirely new branch and set of commits?

**Comment by jbottigliero** [comment] 2017-10-02 15:28
@sokra – you had left a few comments on my previous PR... [based on my comment above](https://github.com/webpack/webpack/issues/4886#issuecomment-332083700), how would you like me to proceed?

**Comment by Kacppian** [comment] 2017-11-27 05:53
Is this still open?

**Comment by jbottigliero** [comment] 2017-11-27 15:43
This was added in `3.8.0/1`, I assume the ticket can be closed at this point.

**Comment by buoyantair** [comment] 2018-02-09 05:55
@TheLarkInn can you please close this? :D Looks like it's been added looong before. ^-^

**Comment by TheLarkInn** [comment] 2018-02-09 17:50
Yes thanks a bunch!!¡!

**Closed by TheLarkInn** 2018-02-09 17:50 UTC
Labels: D0: My First Commit (Contrib. Difficulty), S1: Confusing, X5: work required (PR / Help Wanted), enhancement, webpack-2
