### ISSUE TITLE
Source maps are failing to parse using devtool: source-map

### ISSUE THREAD

**Issue by wsm95** [webpack/webpack#8506] opened 2018-12-14 20:48 UTC
# Bug report

**What is the current behavior?**

If we build using the option `devtool: source-map`, the source maps that are being produced are failing to parse on Chrome and Firefox and debugging is not available. If we switch to `devtool: eval-source-map` the source-maps are being parsed into Chrome and Firefox and we are able to debug in Chrome. `devtool: source-map` was working up until yesterday.

**What is the expected behavior?**

The sourcemaps produced with `devtool: source-map` should not be failing to parse inside Chrome and Firefox.

**Other relevant information:**
webpack version:  4.27.1
Node.js version: 11.4.0
Operating System: Windows 10
Additional tools: Chrome Version 71.0.3578.98

**Comment by sokra** [comment] 2018-12-15 13:37
> `devtool: source-map` was working up until yesterday.

What was the change since yesterday?

**Comment by wsm95** [comment] 2018-12-17 13:55
We did not knowingly change anything before `dev: souce-map` broken for us. After it started to break we updated from 4.16 to 4.27, but the source map issue persisted.

**Comment by sokra** [comment] 2018-12-17 18:41
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by mlavina** [comment] 2018-12-19 16:00
@sokra this looks like an issue with Chrome 70+ as several people in my company are seeing this issue. I am starting to investigate and will come back if I find out more

**Comment by mlavina** [comment] 2018-12-20 17:34
Some findings

First, i was able confirm `eval-source-map` do work so the issue must be something with the way of external source maps.

Second, I used https://github.com/wbkd/webpack-starter as a reproducer and I was unable. I tried the following:
1) Regular source map and just loading up the static file. The source maps worked
2) Regular source map and webpack dev server. The source map still worked. 
3) Regular source map and using express to serve up static files. The source map worked.

I couldn't find any difference in source map structure and url stuff. 

Thirdly, I outputted some `stats` and see the `js.map` listed as an asset so webpack know s it's there

Fourthly, the only thing i can think of that is different is my team explicitly runs babel on `node_modules` to allow better tree shaking by using something like `lodash-es` instead of just `lodash`. That being the sources for those files all look good

Fifth I tried modifying the `devtoolModuleFilenameTemplate` and added the following:
```typescript
devtoolModuleFilenameTemplate: info =>'file://' + path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
```

Sixth If I open my index.html directly by doing some like `file://location/to/index.html` in my dist folder I can see sources maps. Though this may because chrome loads source maps differently for built files and local static files

**Comment by sokra** [comment] 2018-12-20 19:33
Could you check if the broken .js output file contains multiple `sourceMappingURL` comments?

**Comment by mlavina** [comment] 2018-12-20 19:55
There are two output files main.js and vendor.js. Both don't have source maps working.
The main.js has only one sourceMappingUrl comment 
`//# sourceMappingURL=main.fd00a63eeaf103a1aa5d.bundle.js.map`

The vendor file is weird as there are sourceMappingUrl inside the actual bundle for some reason. It seems some library we are pulling in is bundling in sourceMapUrl and isn't being read, which is weird because we are using `source-map-loader`

![image](https://user-images.githubusercontent.com/5084505/50307688-1d3a1880-0467-11e9-9048-3c44114c797e.png)

However, at the bottom of the file there is only one actual comment
![image](https://user-images.githubusercontent.com/5084505/50307746-380c8d00-0467-11e9-93c7-7a14072acc2d.png)

**Comment by mlavina** [comment] 2018-12-21 00:22
@sokra a bit more information.
So, apparently you can manually add source map files to chrome devTools https://lh3.googleusercontent.com/-0zK7TNWK36c/U8e5gm1u3aI/AAAAAAAAL6k/8R_-QL7-6X0/w530-h413-n-rw/add-source-map.gif

When I did that and tried `localhost:8000/fvendor.ccd90541124771c58223.bundle.js.map` nothing happened.

HOWEVER, if i did add source map and used
`file:///C:/Users/mlavina/VSCodeProjects/my-project/packages/app/dist/client/vendor.ccd90541124771c58223.bundle.js.map`

then the source map worked

**Comment by mlavina** [comment] 2019-01-04 20:15
Got updates and I at least know what's going on kinda.

For our requests we add authentication headers to each request so the backend knows it's a valid request. Our express app validates these headers and returns a 401 if they are unauthorized. Something happened in a recent chrome update and for whatever reason the requests for source maps, specifically, are not being appended with headers.

This is weird because we have a chrome extension that auto adds the necessary headers and you can see
request for main.bundle.js has headers
request for vendor.bundle.js has headers
request for main.bundle.js.map NO headers
request for vendor.bundle.js.map NO headers
but then
request for favicon.ico has headers

every request that show up in the network tab has headers.
It's almost as the way chrome gets source map whatever that HTTP request is to get the sourcemap doesn't include request headers

**Comment by mlavina** [comment] 2019-01-04 21:34
Okay so, I know the issue, but I don't know what recent change to Chrome caused this, but for some reason the context in which chrome requests source map files through dev tools cannot be intercepted by chrome extensions anymore.

For example, I tried the first search result on google and `ModHeader` is a chrome extension that adds request headers.

Open any simple webapp and add dummy request header to ModHeader. Then open up Fiddler or something like it to record network traffic.

Not when you open up the index.html on a page it will have the test request showing ModHeader works.

However, if you follow the above steps to `Add source map...` and try to do something like `./main.bundle.js.map` you will see in the request inside Fiddler the header will not be there.

**Comment by mlavina** [comment] 2019-01-07 18:45
@sokra I have filed an issue with chromium https://bugs.chromium.org/p/chromium/issues/detail?id=919575

I don't know if we need to keep this open or not. But I'll cross post updates. 

@wsm95 Sorry for hijacking your issue but I wonder if this is a similar issue you are having

**Comment by wsm95** [comment] 2019-01-07 19:05
@mlavina No problem! When this issue first cropped up we also submitted a bug with chrome, and was merged into this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=900923#c15

**Comment by sokra** [comment] 2019-01-10 14:01
Closing this issue, as it's not a webpack issue.

**Closed by sokra** 2019-01-10 14:01 UTC
