### ISSUE TITLE
Cant install version webpack 1.13.3

### ISSUE THREAD

**Issue by GeoffCraig** [webpack/webpack#3201] opened 2016-10-27 18:45 UTC
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
any

**Current behavior:**
Cannot install with a package.json that has a ^ symbol as it tries to install 1.13.3 and that version appears to not be available.

**Expected/desired behavior:**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
  set your package.json to 1.13.3 and try to npm install

**Comment by SpaceK33z** [comment] 2016-11-03 22:20
Do you still have to issue? It seems to have been published fine, so I don't think this is a webpack issue.

**Comment by SpaceK33z** [comment] 2016-11-09 16:36
Closing since I can't reproduce this and if it would be reproducible, it's a npm issue.

**Closed by SpaceK33z** 2016-11-09 16:36 UTC
Labels: bug, P0: Critical, S4: Broken, X0: need more information
