### ISSUE TITLE
TS2307: Cannot find module 'date-fns'. 

### ISSUE THREAD

**Issue by Elemino** [webpack/webpack#8907] opened 2019-03-13 02:52 UTC
Hello,

I am using the following template https://github.com/bradymholt/aspnet-core-react-template and added date-fns to it. Currently, I am getting the following error. Can you help me understand if it's either a typescript or a webpack issue? Maybe perhaps suggest a troubleshooting strategy? Thank you!  

**What is the current behavior?**

The app starts with a typescript inspector error. 

fail: Microsoft.AspNetCore.NodeServices[0]
      ✖ ｢wdm｣: Hash: 6cb37cd5883be074ecd7
      Version: webpack 4.29.6
      Time: 13121ms
      Built at: 03/07/2019 10:23:11 PM
           Asset       Size  Chunks             Chunk Names
      index.html  449 bytes          [emitted]  
         main.js    8.9 MiB    main  [emitted]  main
      Entrypoint main = main.js
      [0] multi react-hot-loader/patch webpack-hot-middleware/client?reload=true&path=__webpack_hmr&dynamicPublicPath=true ../client-react/boot.tsx 52 bytes {main} [built]
      [../client-react/boot.tsx] 545 bytes {main} [built]
      [../client-react/components/Routes.tsx] 2.25 KiB {main} [built]
      [../client-react/polyfills/array-find.ts] 1.51 KiB {main} [built]
      [../client-react/polyfills/object-assign.ts] 881 bytes {main} [built]
      [../client-react/styles/global.css] 1.06 KiB {main} [built]
      [../node_modules/bootstrap/dist/css/bootstrap.css] 1.03 KiB {main} [built]
      [../node_modules/querystring-es3/index.js] 127 bytes {main} [built]
      [../node_modules/react-dom/index.js] 1.33 KiB {main} [built]
      [../node_modules/react-hot-loader/dist/react-hot-loader.development.js] 81.6 KiB {main} [built]
      [../node_modules/react-hot-loader/patch.js] 228 bytes {main} [built]
      [../node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
      [../node_modules/react/index.js] 190 bytes {main} [built]
      [../node_modules/strip-ansi/index.js] 161 bytes {main} [built]
      [../node_modules/webpack-hot-middleware/client.js?reload=true&path=__webpack_hmr&dynamicPublicPath=true] 7.59 KiB {main} [built]
          + 855 hidden modules
      
      ERROR in /home/user/Desktop/Projects/CodeChallenge7-repo3/client-react/components/Contacts.tsx
      ../client-react/components/Contacts.tsx
      [tsl] ERROR in /home/user/Desktop/Projects/CodeChallenge7-repo3/client-react/components/Contacts.tsx(5,80)
            TS2307: Cannot find module 'date-fns'.
      Child html-webpack-plugin for "index.html":
               Asset     Size  Chunks  Chunk Names
          index.html  557 KiB       0  
          Entrypoint undefined = index.html
          [../node_modules/html-webpack-plugin/lib/loader.js!../client-react/index.ejs] 928 bytes {0} [built]
          [../node_modules/lodash/lodash.js] 527 KiB {0} [built]
          [../node_modules/webpack/buildin/global.js] 472 bytes {0} [built]
          [../node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
fail: Microsoft.AspNetCore.NodeServices[0]
      ✖ ｢wdm｣: Hash: 6cb37cd5883be074ecd7
      Version: webpack 4.29.6
      Time: 13121ms
      Built at: 03/07/2019 10:23:11 PM
           Asset       Size  Chunks             Chunk Names
      index.html  449 bytes          [emitted]  
         main.js    8.9 MiB    main  [emitted]  main
      Entrypoint main = main.js
      [0] multi react-hot-loader/patch webpack-hot-middleware/client?reload=true&path=__webpack_hmr&dynamicPublicPath=true ../client-react/boot.tsx 52 bytes {main} [built]
      [../client-react/boot.tsx] 545 bytes {main} [built]
      [../client-react/components/Routes.tsx] 2.25 KiB {main} [built]
      [../client-react/polyfills/array-find.ts] 1.51 KiB {main} [built]
      [../client-react/polyfills/object-assign.ts] 881 bytes {main} [built]
      [../client-react/styles/global.css] 1.06 KiB {main} [built]
      [../node_modules/bootstrap/dist/css/bootstrap.css] 1.03 KiB {main} [built]
      [../node_modules/querystring-es3/index.js] 127 bytes {main} [built]
      [../node_modules/react-dom/index.js] 1.33 KiB {main} [built]
      [../node_modules/react-hot-loader/dist/react-hot-loader.development.js] 81.6 KiB {main} [built]
      [../node_modules/react-hot-loader/patch.js] 228 bytes {main} [built]
      [../node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
      [../node_modules/react/index.js] 190 bytes {main} [built]
      [../node_modules/strip-ansi/index.js] 161 bytes {main} [built]
      [../node_modules/webpack-hot-middleware/client.js?reload=true&path=__webpack_hmr&dynamicPublicPath=true] 7.59 KiB {main} [built]
          + 855 hidden modules
      
      ERROR in /home/user/Desktop/Projects/CodeChallenge7-repo3/client-react/components/Contacts.tsx
      ../client-react/components/Contacts.tsx
      [tsl] ERROR in /home/user/Desktop/Projects/CodeChallenge7-repo3/client-react/components/Contacts.tsx(5,80)
            TS2307: Cannot find module 'date-fns'.
      Child html-webpack-plugin for "index.html":
               Asset     Size  Chunks  Chunk Names
          index.html  557 KiB       0  
          Entrypoint undefined = index.html
          [../node_modules/html-webpack-plugin/lib/loader.js!../client-react/index.ejs] 928 bytes {0} [built]
          [../node_modules/lodash/lodash.js] 527 KiB {0} [built]
          [../node_modules/webpack/buildin/global.js] 472 bytes {0} [built]

**If the current behavior is a bug, please provide the steps to reproduce.**

Might be. But this happens quite often with other modules when using typescript. 
Reproduce: Install the latest version of template and date-fns. 

**What is the expected behavior?**

yarn start should run app without webpack/typescript errors.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack 4.29.0, Node v10.14.1, Ubuntu 16.04 LTS. Is there anything else that I can provide?

**Comment by montogeek** [comment] 2019-03-13 07:57
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Elemino** [comment] 2019-03-13 08:11
Apologies for that. I cannot reopen this issue, but I believe you can. I am not sure what else I can provide. Any suggestions? Is there anything in the error I provided that may hint what the problem may be to an experienced engineer right off the bat? Thanks!

**Comment by evilebottnawi** [comment] 2019-03-13 11:54
@Elemino can you create minimum reproducible test repo?

**Comment by sokra** [comment] 2019-03-15 11:43
> Can you help me understand if it's either a typescript or a webpack issue?

It's a typescript issue.

**Closed by sokra** 2019-03-15 11:43 UTC

**Comment by Elemino** [comment] 2019-03-15 19:20
Thanks! It's a versioning conflict I presume where if you update date-fns webpack doesn't pick it up. I'll update after I solve this issue thanks.

**Comment by Elemino** [comment] 2019-10-21 09:38
I just wanted to give an update. In order to solve the isseu you need to:

set "module": "commonjs" unless you are using a separate tool to convert the ES6 modules to CommonJS in the tsconfig.json file.
