### ISSUE TITLE
Webpack 5 worker import fails with "chunks: 'all'" + [contenthash] in output filename

### ISSUE THREAD

**Issue by wh1t3cAt1k** [webpack/webpack#13801] opened 2021-07-15 15:58 UTC
# Bug report

**What is the current behavior?**

Worker import started producing a script loading error as soon as I added `[contenthash]` into the output filename.

I see a strange 404 error in the console for a **non-existent** chunk script with a strange path (note the `.undefined.js` postfix):

`https://localhost/addin/src_functions_parallelism_caching_passport-worker_ts-_36b50.undefined.js`

Where does this `.undefined.js` part come from? Does it give anyone any idea?

The actual filename of the chunk that **does exist** after compilation is `src_functions_parallelism_caching_passport-worker_ts-_36b50.8ba2df42b53ad688d69d.js` - instead of `undefined` there's a proper content hash. 

Relevant bits of configuration:

```typescript
    output: {
        path: path.resolve(__dirname, 'wwwroot'),
        publicPath,
        filename: '[name].[contenthash].js',
    },
    optimization: {
        moduleIds: 'deterministic',
        splitChunks: {
              chunks: 'all',
        },
        runtimeChunk: false,
    },
```

The worker import code in the transpiled code I see:

```typescript
return new Worker(
    new URL(/* worker import */ __webpack_require__.p +  
    __webpack_require__.u(
        "src_functions_parallelism_caching_passport-worker_ts-_36b50"), __webpack_require__.b), {
            ...
```

Not sure if it's OK or relevant to the problem, pasting here just in case.

**What is the expected behavior?**

The expected behaviour is that worker import is able to resolve the correct script name (with the contenthash appended).

**Other relevant information:**
webpack version: 5.44.0  
Node.js version: 14 LTS
Operating System: Mac OS 
Additional tools:

**Comment by wh1t3cAt1k** [comment] 2021-07-15 15:59
Apologies: I might have confused the string ID with the filename. Let me debug this further before reporting.

**Comment by wh1t3cAt1k** [comment] 2021-07-15 16:08
Added additional content into the issue, please take a look.

**Comment by alexander-akait** [comment] 2021-07-15 16:08
Please use `publicPath: auto`

**Comment by alexander-akait** [comment] 2021-07-15 16:08
You have invalid URL

**Comment by wh1t3cAt1k** [comment] 2021-07-15 16:12
@alexander-akait are you sure it's a question of public path? 

To reiterate, the worker import **was** working properly before I added `[contenthash]` into `output.filename`.

(In my case `publicPath` is a variable I define in advance in the configuration, its value seemed irrelevant since it was working without the `[contenthash]`, so I didn't paste it)

**Comment by alexander-akait** [comment] 2021-07-15 16:14
Please provide reproducible test repo, otherwise we can't help here, maybe other plugin break contenthash

**Comment by wh1t3cAt1k** [comment] 2021-07-15 16:30
Some more context before I jump into test repo:

I tried replacing `filename: '[name].[contenthash].js',` with `filename: '[name].[chunkhash].js'`.

The worker still tries to import a non-existed script, but instead of `undefined`, it references a chunkhash that is not present in the filename.

I.e. the browser tries to load `chunk-id.5deff33769142387d785.js` , but in the filesystem, the only file present is `chunk-id.d8777908f84bf2d38dc5`.

Different hash for some reason.

The "non-existent" hash is also referenced in chunk filename in the compiled code (hence the attempt to load the script from that path).

@alexander-akait 
 
Is there a way that `[chunkhash]` may change throughout the compilation, so that the file is created with one hash, but compiled code expects a different one?

**Comment by wh1t3cAt1k** [comment] 2021-07-15 16:32
During build time, I see a warning that might be relevant:

```
[webpack] (node:3343) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
```

**Comment by alexander-akait** [comment] 2021-07-15 16:45
It means you have plugin which break contenthash

**Comment by alexander-akait** [comment] 2021-07-15 16:46
I don't know why it is hard to use the issue template and provide example how we can reproduce, this will not only make your life easier, but also reduce the time spent trying to guess, and will also save your nerves

**Comment by wh1t3cAt1k** [comment] 2021-07-15 16:51
I used the issue template as is; re reproducible repo, agree it's not hard, just time consuming to strip down the NDA-protected codebase down to a reproducible example.

Thus, I am trying to figure out the potential root cause as is first, failing that I'll work on getting the example into the room.

For the record, I managed to get rid of the above warning by updating all my plugins, the issue was not gone.

I am beginning to suspect this:

```typescript
[webpack] WARNING in [entry]
[webpack] Circular dependency between chunks with runtime (src_functions_parallelism_caching_passport-worker_ts-_36b50, src_functions_parallelism_caching_passport-worker_ts-_36b51, src_functions_parallelism_calculation_function-worker_ts, taskpane)
```

This error is caused by the fact that, depending on the browser, I am using either a `SharedWorker`, or a `Worker`, but I import the same script path.

Apparently Webpack 5 cannot merge them into one chunk so I end up with two chunk bundles with identical content:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/5159662/125826566-3b68bffe-1fb0-4feb-864c-10916ae93933.png">

By the looks of things, maybe the `chunkhash` part in the filename gets overridden due to the above warning.

My working day is over, if I don't sort this problem out I am going to work on a repro.

**Comment by alexander-akait** [comment] 2021-07-15 16:52
unfortunately there can be many problems here, I cannot help without repo :disappointed:

**Comment by AprilArcus** [comment] 2021-08-12 03:31
I'm having the same issue, @wh1t3cAt1k. May I ask if you are using https://www.npmjs.com/package/webpack-subresource-integrity ?

**Comment by AprilArcus** [comment] 2021-08-12 05:50
Minimal repro: https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro

**Comment by alexander-akait** [comment] 2021-08-12 17:14
Reproducible example https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro

**Comment by roninjin10** [comment] 2021-08-12 17:21
Here is my investigation into this issue that lead to helping produce the minimal example:

If [using contenthash](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/webpack.config.js#L15) with a [WebWorker](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/index.js#L1) and any plugin is calling [Maintemplate.prototype.hook.localVars](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/minimalplugin.js#L22) such as the [webpack-subresource-integrity plugin](https://github.com/waysact/webpack-subresource-integrity/blob/main/webpack-subresource-integrity/index.ts#L168), the runtime starts requesting for undefined when it tries to load the web worker chunk both observed in the console and from [adding logging in webpacks source](https://github.com/webpack/webpack/blob/main/lib/runtime/GetChunkFilenameRuntimeModule.js#L240) .  

Since this is happening as a sideeffect of calling .tap, I think the issue lies downstream of https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/RuntimePlugin.js#L365 but I'm not sure.

**Comment by kinsei0916** [comment] 2021-08-20 02:30
Here is another reproduction: https://github.com/kinsei0916/webpack-worker-contenthash-repro
I'm not using any additional plugins other than html-webpack-plugin. This issue occurs when I bump webpack-dev-server from 3.11.2 to 4.0.0.

**Comment by alexander-akait** [comment] 2021-08-20 11:18
Marked as critical, we will fix it in near future

**Comment by alexander-akait** [comment] 2021-09-02 09:53
Fix https://github.com/webpack/webpack/pull/14112

**Comment by alexander-akait** [comment] 2021-09-02 13:28
Please try https://github.com/webpack/webpack/releases/tag/v5.51.2

**Comment by remcohaszing** [comment] 2021-09-02 13:45
It’s working now (remcohaszing/monaco-yaml#100) :tada:

**Comment by alexander-akait** [comment] 2021-09-02 13:52
Let's close, feel free to feedback if you faced with bugs again

**Closed by alexander-akait** 2021-09-02 13:52 UTC
Labels: webpack-5, critical-bug

**Comment by wh1t3cAt1k** [comment] 2021-09-06 11:02
I confirm that the issue has disappeared for me as well after the upgrade. I am grateful to the guys above who were able to provide the minimal repro as I never got around to doing it.
