### ISSUE TITLE
5.25.0 has broken my builds

### ISSUE THREAD

**Issue by roddypratt** [webpack/webpack#12880] opened 2021-03-12 13:41 UTC
# Bug report

I have a Laravel app which uses blade.php for browser-side content, with some small <script> sections using JQuery.
JQuery is part of the vendor.js chunk created by Webpack, via Laravel Mix

When build with 5.24.4, everything works as expected

**What is the current behavior?**

However, with 5.25, the bundles are created  but when a page loads and attempts to use JQuery I get  the dreaded..

`ReferenceError: $ is not defined` error in the browser console.

The only difference in the created bundles appears to be the new chunk loading code in manifest.js, and the 
`__webpack_require__ `section at the tail of each created file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Probably difficult to provide this as it's a large project - I will try and get a minimal example.

**What is the expected behavior?**
"$" should be defined.

**Other relevant information:**
webpack version:  5.25.0
Node.js version:  this is a client-side issue.
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment] 2021-03-12 13:48
Sorry, won't fix, without example we can't help you

**Comment by roddypratt** [comment] 2021-03-12 13:57
> Sorry, won't fix, without example we can't help you

Understood. Will try and make a minimal example.

**Comment by mtwalsh** [comment] 2021-03-12 16:03
Same issue here, I'm using Laravel Mix but no jQuery in the mix here, downgrading to `5.24.4` from `5.25.0` resolved the issue.

**What is the current behaviour?**

JS is not being executed client-side, I can't even get a `console.log()` output. No errors in the console either.

**What is the expected behaviour?**

JS should be executed client-side.

**Other relevant information:**

webpack version: 5.25.0
Node.js version: 14.15.4
Operating System: Windows 10
Additional tools: Laravel Mix

**Comment by alexander-akait** [comment] 2021-03-12 16:05
I thing bug on `Laravel Mix` side, as you can see not reports from other developers

**Comment by alexander-akait** [comment] 2021-03-12 16:05
Bug without example I can't help

**Comment by roddypratt** [comment] 2021-03-12 16:06
Inevitably, my minimal example doesn't have the problem.  :( However it looks in the 'broken' version, all the js chunks are loaded but Webpack never "runs" them.

**Comment by alexander-akait** [comment] 2021-03-12 16:07
What is output of `dist` and generated `index.html`?

**Comment by roddypratt** [comment] 2021-03-12 16:16
> What is output of `dist` and generated `index.html`?

My HTML is unchanged (Webpack isn't generating that).

Relevant section snipped is 
```
    <script src="/js/manifest.js?id=c7e3addb28db6d509f49"></script>
    <script src="/js/vendor.js?id=d425ac29b17e87266a7d"></script>
    <script src="/js/app.js?id=ce0df1181fd5328cf69f"></script>

    <script>console.log($)</script> -- crashes here
```
`dist` contains all the expected files.  Generated JS files seem identical apart from the last few lines. I can post an example of those if that helps?

In manifest.js there's this code, which I think is the actual module "runner".  It seems that `__webpack_require__.o()` is always returning false for these modules so they never get run...?
```
	if (__webpack_require__.o(installedChunks, chunkId) && installedChunks[chunkId]) {
		installedChunks[chunkId][0]();
```

**Comment by alexander-akait** [comment] 2021-03-12 16:25
Not all modules write yourself to `window`, so using `$` is not a safe using here, do you have `window.jQuery`

**Comment by roddypratt** [comment] 2021-03-12 19:25
> Not all modules write yourself to `window`, so using `$` is not safe here, do you have `window.jQuery`?

 I'd get the same problem. My `app.ts`  starts with

```
import * as $ from "jquery"

window["$"] = $
```
... But that code is never executed because Webpack never 'runs' the modules it loads.  Breakpoints on that line are never hit in 5.25, but they are in previous 5.x builds.

**Comment by sokra** [comment] 2021-03-12 22:05
This is very likely a bug in webpack. We did some refactoring to the startup logic.

You said only a few lines changed. Maybe you can post the diff?

**Comment by roddypratt** [comment] 2021-03-12 22:15
> This is very likely a bug in webpack. We did some refactoring to the startup logic.
> 
> You said only a few lines changed. Maybe you can post the diff?
I'm about to publish a small repo which demonstrates the issue. It's triggered by including a .scss file via mix. webpack thinks the load is not 'fulfilled' because it never 'sees' the scss file being loaded...

**Comment by sokra** [comment] 2021-03-12 22:20
Ah that's possible if you have a chunk with only css and no JS, due to splitChunks.

**Comment by roddypratt** [comment] 2021-03-12 22:21
Here's the repo. 
https://github.com/roddypratt/webpack252bug

**Comment by thecrypticace** [comment] 2021-03-12 22:52
Hi! I'm one of the people who works on Mix. I'd be happy to help where I can with this!

> Ah that's possible if you have a chunk with only css and no JS, due to splitChunks.

Yep this happens because we split CSS using `splitChunks` with a filename test + type: css/mini-extract + enforce: all

**Comment by alexander-akait** [comment] 2021-03-13 18:07
Yep, looks the regression, optimization options:
```js
{
  optimization: {
   // Comment `runtimeChunk` solve the problem
   runtimeChunk: { name: '/manifest'}
   cacheGroups: {
    default: false,
    defaultVendors: false,
    'styles-mycss': {
      name: 'mycss',
      chunks: 'all',
      enforce: true,
      type: 'css/mini-extract',
      test: [Function]
    },
    vendor0: {
      name: '/vendor',
      chunks: 'all',
      enforce: true,
      priority: -10,
      test: /(?<!node_modules)[\\/]node_modules[\\/]()/i
    }
  }
}
```

Entry:
```
entry: {
    '/app': [
      '/path/to/project/src/app.ts',
      '/path/to/project/src/mycss.scss'
    ]
  },
```

i.e. using `mini-css-extract-plugin` + CSS `entry` + `optimization.runtimeChunk` broken

**Closed** 2021-03-14 19:32 UTC
Labels: question, webpack-5

**Comment by roddypratt** [comment] 2021-03-14 21:12
Thanks - Can confirm 5.25.1 fixes both my original project and the repo previously provided to reproduce the issue.!
