### ISSUE TITLE
Generated Duplicate License Comment In Bundle

### ISSUE THREAD

**Issue by taroee** [webpack/webpack#8055] opened 2018-09-19 11:43 UTC
In webpack 4, I notice duplicate license comments in the bundle. I think it will be nice to show only once instead of multiple times. And also this makes the bundle size bigger.

Picture below is jQuery.
![duplicate](https://user-images.githubusercontent.com/2662413/45751055-61850500-bc3b-11e8-8741-f7906c78a161.PNG)

Picture below is CKEditor 5 Custom Build.
![multiple license](https://user-images.githubusercontent.com/2662413/45750854-86c54380-bc3a-11e8-96cd-8d1dbb80a595.PNG)

**Comment by evilebottnawi** [comment] 2018-09-19 12:09
Bug in `uglify-es`, can't be fixed, please switch to https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by kzc** [comment] 2018-09-19 15:56
> Bug in uglify-es, can't be fixed

That's incorrect. The uglify/terser API provides full control over which comments are emitted.

```
$ cat dedupe_comments.js 
var minify = require("uglify-es").minify;
var code = "/*A*/ /*A*/ foo(); /*B*/ /*A*/ /*B*/ bar(); /*C*/ /*A*/ /*C*/ baz(); /*D*/ /*B*/";
var m = Object(null);
var result = minify(code, {
    output: {
        comments: function(ignore, token) {
            var comment = token.value;
            if (comment == null || m[comment]) return false;
            m[comment] = 1;
            return true;
        }
    }
});
console.log("original:\n" + code);
console.log("\nminified:\n" + result.code);
```
```
$ node dedupe_comments.js 
original:
/*A*/ /*A*/ foo(); /*B*/ /*A*/ /*B*/ bar(); /*C*/ /*A*/ /*C*/ baz(); /*D*/ /*B*/

minified:
/*A*/foo(),/*B*/bar(),/*C*/baz();/*D*/
```

This is just an example. An actual comment deduper may want to ignore leading and trailing whitespace.

> please switch to https://github.com/webpack-contrib/terser-webpack-plugin

By all means, but be aware that the comment handling code in `terser` is the same as `uglify-es`.

**Comment by evilebottnawi** [comment] 2018-09-19 16:07
@taroee can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment] 2018-12-14 12:56
Should be fixed in `terser` and `uglify` plugin, PR already exists and will be merged in near future, thanks

**Closed by evilebottnawi** 2018-12-14 12:56 UTC
Labels: X2: answer required

**Comment by lucianosantana** [comment] 2019-08-23 10:50
@evilebottnawi would you mind referencing the PRs so we could follow up ? Thank you
