### ISSUE TITLE
Compilation progress is always displayed to stderr

### ISSUE THREAD

**Issue by segrey** [webpack/webpack#3520] opened 2016-12-19 13:45 UTC
According to [documentation](https://webpack.github.io/docs/cli.html#progress)  and [code](https://github.com/webpack/webpack/blob/v2.2.0-rc.1/lib/ProgressPlugin.js#L175), compilation progress is written to stderr. The problem is that the progress doesn't look great in IntelliJ IDEs that highlight stderr output as red by default.
Are there any reasons to not display the progress to stdout? If yes, what do you think about making it configurable via some environment variable maybe? Thanks!

**Comment by sokra** [comment] 2016-12-19 16:12
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by sokra** 2016-12-19 16:12 UTC

**Comment by segrey** [comment] 2016-12-19 17:05
@sokra Have updated the issue description. BTW, it was unclear to me that the issue template shouldn't be deleted. Maybe it's worth to add a comment inside the template indicating that such issues will be closed.

**Comment by segrey** [comment] 2016-12-19 20:06
>Please either update the issue with the template and reopen
Seems I can't reopen it. @sokra Could you please reopen it if it's OK?

**Comment by bmayen** [comment] 2016-12-23 12:11
I can confirm this same behavior

**Comment by sokra** [comment] 2016-12-23 12:41
POSIX defines:
* standard output = for writing conventional output
* standard error = for writing diagnostic output

progress is a diagnostic output so it belongs to standard errors.

**Comment by segrey** [comment] 2016-12-23 14:03
Sure, it can be a diagnostic output. On the other hand, it could be considered as conventional output as well, as there is no error to diagnose. It's mostly up to a program to define what diagnostic output is.
E.g. npm use stderr for progress too.
Found [this related answer](http://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout/331808#331808) on this topic. According to it, a better solution would be to check `isatty()` before printing progress.

**Comment by sokra** [comment] 2016-12-23 14:07
> or when explicitly enabled by a command-line option

It's explicit by `--progress`. So just don't enable it when you don't want the output.

btw. you can write your own plugin to write the output in some other style or to another stream by using the ProgressPlugin

**Comment by segrey** [comment] 2016-12-26 12:05
Thanks, I see. Unfortunately, IDE cannot remove `--progress`, as it's usually [hardcoded](https://github.com/preboot/angular-webpack/blob/master/package.json#L7) in package.json. Also, IDE cannot modify webpack config to add its own plugin.
Not sure there are good ways of resolving this issue on IDE side only.

**Comment by flakey-bit** [comment] 2017-10-26 13:33
This will also cause issues for people running with --progress in VSTS.

**Comment by AlexLnz** [comment] 2017-11-15 14:49
@sokra 
I don't share the opinion that progress output is diagnostic.

From my point of view "diagnostic" is related to bug finding or error analysis. Hence it makes sense to output it on stderr. A progress display however is on informational level and should be rendered to stdout.

Printing non-error-ouput on stderr makes trouble:
In WebStorm for example you get the progress output rendered to stderr all in red color. So everything looks like an error. 
This is quite disturbing for the user. One cannot tell status messages from "real" errors because they all appear in red.

**Comment by ambirdsall** [comment] 2018-06-10 06:19
> I don't share the opinion that progress output is diagnostic.

Nor do I. Also, directing ordinary progress output and error reporting to the same place makes some _extremely_ useful command-line workflows impossible. For example, redirecting non-error build output to `/dev/null` while running a test suite in watch mode and only seeing build errors and test output is impossible.

**Comment by dstj** [comment] 2019-09-18 19:06
This makes little sense to use `stderr`. A plain .NET Core `dotnet new angular` app upgraded to Angular 8 (which uses Webpack) and setting `progress: true` in the `angular.json` causes pages and pages of output like this on the app startup:

![image](https://user-images.githubusercontent.com/467692/65177624-0e4bbb00-da25-11e9-80df-bbd44ee5a9a7.png)

This makes `progress: true` quite useless as I'll be ignoring its ouput...

**Comment by ckpearson** [comment] 2019-11-12 09:25
I know this is closed, but I'm also encountering this.

POSIX may define it that way, but I'd argue nobody **uses** it that way.

If you receive output on stderr the assumption is that an **error** has been reported, and something therefore has gone wrong.

It means integration with webpack via command line execution is next to useless without excusing the error false positives.

I think it would be good to have progress reported via the standard output, because it's part of standard information, you've kicked off a build, therefore you'd like to know how that's doing...

**Comment by ronnyfm** [comment] 2019-11-26 14:19
Any fix for this? I keep explaining that this is not an error, but anyways, the partner sees `ERROR` in the output and is asking for a fix.

**Comment by kaleidocore** [comment] 2020-05-28 22:11
This issue is nowhere near resolved, and it's fantastically annoying. On every run my console gets spammed with red FAIL messages, and it's impossible to spot any real errors in all that mess, making the entire feature _completely useless!_

Whoever thought this was a good idea have completely misunderstood the meaning and purpose of **stderr**. That POSIX interpretation is just asinine.

> POSIX defines:
> 
>     * standard output = for writing conventional output
>     * standard error = for writing diagnostic output
> 
> progress is a diagnostic output so it belongs to standard error.

So, according to the same interpretation, information about what a program is currently doing is considered _**unconventional?**_ Wait, have you forgotten I could use _any_ printed information to diagnose _something?_ Let's get rid of stdout altogether and only use stderr for everything!

Someone please fix this.

**Comment by kemmis** [comment] 2020-08-25 16:09
+10000000

Please reconsider this. This isn't just an argument about a preference or matter of style. This is causing severe issues downstream. Please at least add an option to allow the progress to be sent to std out rather than error. Please meet us half way here. 

*begging*

**Comment by chuyik** [comment] 2020-11-25 09:28
Please reconsider this, assets compiled info should not be displayed to stderr.

![image](https://user-images.githubusercontent.com/6262943/100208332-91c73d00-2f43-11eb-90e1-508d32b53eb5.png)

**Comment by evilebottnawi** [comment] 2020-11-25 11:18
@chuyik stats are writting in `stdout`  always

**Comment by ThaDaVos** [comment] 2021-04-21 18:34
Why hasn't this been picked up yet... maybe because the issue is closed...

**Comment by sokra** [comment] 2021-04-21 20:01
https://webpack.js.org/configuration/other-options/#stream

**Comment by SomeoneIsWorking** [comment] 2021-12-21 11:25
> https://webpack.js.org/configuration/other-options/#stream

Can't do this with Vue for some reason

     configuration.infrastructureLogging has an unknown property 'stream'. These properties are valid: object { debug?, level? }

**Comment by alexander-akait** [comment] 2021-12-21 11:27
@SomeoneIsWorking run `npm ls webpack`, you have old version of webpack

**Comment by SomeoneIsWorking** [comment] 2021-12-21 11:28
> @SomeoneIsWorking run `npm ls webpack`, you have old version of webpack

Yes, it occurred to me seconds after writing the comment that I replaced the explicit webpack 5 version after migrating from webpack-cli to vue-cli which uses webpack 4
