### ISSUE TITLE
Adding file specific lines at top of build(both entry and vendors) files

### ISSUE THREAD

**Issue by krishna5737** [webpack/webpack#7867] opened 2018-08-09 10:51 UTC
## Feature request

**What is the expected behavior?**
Want to add different-different lines at top of different output files of webpack build

**What is motivation or use case for adding/changing the behavior?**
- Adding some lines(lines will be file specific) at top of specific files which needs to be there at starting of .js file for my application to work

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

BannerPlugin works in same manner but it doesn't allow adding specific lines at specific file.
//Let's assume entry files are a.js , b.js and
I want to append require(test1.js) at the top of a.js and require(test2.js) at the top of b.js

then we have to check if(["file"]== test1.js)) which will always return false (considering ["file"] is a placeholder) so I can't append separate texts in 2 different files.

I also tried with switch(using count flag for entry files considering first entry file will be built first) but during _**webpack--watch**_ it fails because then webpack only builds the file having changes

**Comment by montogeek** [comment] 2018-08-09 13:40
You may want to create a plugin for that.

**Comment by sokra** [comment] 2018-08-09 15:29
Duplicate of #7848

**Closed by sokra** 2018-08-09 15:29 UTC

**Comment by krishna5737** [comment] 2018-08-09 15:31
@montogeek I am new to JS, if your team can make some upgrade to BannerPlugin or you can suggest me some solution, it will be great help to me.

**Comment by krishna5737** [comment] 2018-08-09 15:33
@sokra  Solution was still missing there

**Comment by sokra** [comment] 2018-08-10 09:36
https://github.com/webpack/webpack/issues/7848#issuecomment-410608881

> The BannerPlugin will work for you. You can pass a function to generate a header per file.
