### ISSUE TITLE
ProfilingPlugin output dosen't displayed in Chrome

### ISSUE THREAD

**Issue by BATCOH** [webpack/webpack#11780] opened 2020-10-21 22:00 UTC
# Bug report

**What is the current behavior?**
JSON produced by ProfilingPlugin is shown in Chrome with one single "Evaluate Script" line without any additional info.
Although events.json is pretty large, contains a lot of lines, timestamps, and looks like a valid JSON file.
Maybe there are some changes in Chromium itself related to this issue.
![Screenshot 2020-10-22 at 00 26 18](https://user-images.githubusercontent.com/281098/96791184-a96d4c00-1400-11eb-8862-c4f00730639b.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create new project with `npx create-react-app test-project`.
1. Eject (`cd test-project && npm run eject`)
1. Add `new webpack.debug.ProfilingPlugin()` to plugins section at  config/webpack.config.js
1. Start dev server with `npm start` then shutdown it (or just `npm run build`).
1. Drag and drop generated events.json into the Chrome DevTools Profiler.

Or just unarchive and use [attached events.json](https://github.com/webpack/webpack/files/5418853/events.json.zip)

P.S. I can reproduce issue in all my projects, with different configs, and none of them uses CRA. It's just easy-to-check example with wide used and probably well tested config. 

**What is the expected behavior?**
I exepect to see some additional info, eg timings for each used plugin, "Bottom-up" list, etc.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: v14.10.1
Operating System: macOS Catalina 10.15.7
Additional tools: Google Chrome 86.0.4240.80 (Official Build) (x86_64)

**Comment by evilebottnawi** [comment] 2020-10-22 10:04
> I exepect to see some additional info, eg timings for each used plugin, "Bottom-up" list, etc.

Sorry it is out of scope `ProfilingPlugin`, please read what is `profiling` https://developer.mozilla.org/en-US/docs/Tools/Performance

**Comment by grantila** [comment] 2020-10-23 07:24
Then what's the purpose/scope of the plugin, @evilebottnawi? I used it, got a 500mb file, shows nothing in chrome event viewer.

**Comment by evilebottnawi** [comment] 2020-10-23 11:06
@grantila What do you want to see? I don't understand your problem

**Comment by grantila** [comment] 2020-10-23 11:08
What am I *supposed* to see? What is the purpose of this plugin? I don't see anything. That's not expected.

**Comment by BATCOH** [comment] 2020-10-23 11:53
Well, according to [docs](https://webpack.js.org/plugins/profiling-plugin/): "It will then display timeline stats and calls per plugin!".
And there is no timeline stats and no calls per plugin.

At least docs have to be changed if this is valid and expected behavior.

**Comment by evilebottnawi** [comment] 2020-10-23 12:26
hm, something wrong with chome, investigate

**Comment by evilebottnawi** [comment] 2020-10-23 12:36
![Screenshot from 2020-10-23 15-35-29](https://user-images.githubusercontent.com/4567934/97004254-74b6dd00-1545-11eb-83c2-017dde751bab.png)

No problems on webpack@4 and webpack@5, please open an issue in `create-react-app`, also we have tests on this

**Comment by evilebottnawi** [comment] 2020-10-23 12:38
You have

**Comment by evilebottnawi** [comment] 2020-10-23 12:56
@BATCOH 

> P.S. I can reproduce issue in all my projects, with different configs, and none of them uses CRA. It's just easy-to-check example with wide used and probably well tested config.

Can you provide example or link?

**Comment by BATCOH** [comment] 2020-10-23 18:05
@evilebottnawi 
I made a minimal repo with webpack@5 and the issue is still there.
https://github.com/BATCOH/webpack-profiling-example

**Comment by evilebottnawi** [comment] 2020-10-23 18:06
Thanks!

**Comment by evilebottnawi** [comment] 2020-10-24 13:00
@BATCOH All works fine too :confounded: 
![Screenshot from 2020-10-24 15-59-52](https://user-images.githubusercontent.com/4567934/97082391-f8d69680-1611-11eb-833d-26aca2bda895.png)

**Comment by BATCOH** [comment] 2020-10-25 00:56
I ran some tests in different environments and finally found something useful.

It’s all about node version.
In node v14.5.0 and below everything fine. Issue appears since 14.6.0 and above, including latest 15.0.1.

I've read the [14.6.0 changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.6.0), but it's hard for me to say what exact change could lead to such effect.

**Comment by evilebottnawi** [comment] 2020-10-26 11:12
Thanks, it is real weird, maybe regression on node side...

**Comment by keepitterron** [comment] 2021-01-20 10:45
I can reproduce this on OSX. With OP's repo all works fine with 14.5 but it fails with 14.6

The odd thing is: on the project where I found out profiling was not working anymore, it does not make any difference which Node version I use. I went back all the way to node 12 (using 14.15 by default) and the profile.json file is not readable by chrome 🤔 

did you find out anything more @BATCOH ?

**Comment by sokra** [comment] 2021-01-20 18:21
So I spend way to much time investigating in this and here are my findings:

- Problem in the profiles: timestamps between the cpu profile and the custom events differ.
- They both are specified as relative to an unknown point in time. Usually this is inferred from the system boot, but there is no guarantee.
- The timestamp of custom events is received from `process.hrtime`, but the timestamp in the profile is calculated by v8 via some [internal timing methods](https://github.com/nodejs/node/blob/900c9f504184d5232dc503b1a94898c37a08acef/deps/v8/src/base/platform/time.cc#L724) by @bmeurer.
- This is only a problem in MacOS and only if you suspended your system before (more on that later)
- It was introduced in this node.js commit: https://github.com/nodejs/node/commit/a9ca4204e0fff3783211dec65e4548318a9395e3, which updates libuv.
- In libuv it's caused by https://github.com/libuv/libuv/commit/4685be236b032ec6a60553a99d4365ab25dc368a by @bnoordhuis
- Since this commit `process.hrtime` uses [`mach_continuous_time`](https://developer.apple.com/documentation/kernel/1646199-mach_continuous_time), while v8 uses [`mach_absolute_time`](https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time).
- They are very equal, except for the fact that mach_continuous_time includes the suspended time while mach_absolute_time does not.
- That's where the difference comes from.
- I was unable to reproduce this on CI as it doesn't suspend...

I wonder if the libuv fix should also applied to the v8 code base?

Anyway, I will fix that in webpack by adjusting the profile timestamps

**Comment by keepitterron** [comment] 2021-01-20 18:25
thanks for the detailed explanation (and links!) @sokra 
this is golden! 🙏🔥

**Comment by sokra** [comment] 2021-01-20 18:30
So switch your computer off and on should fix the problem (ironically). 😉 

Could you try to confirm that? I don't have a mac so I can't really test that. I made above conclusions based on reading the source code, but that could be wrong?

**Comment by keepitterron** [comment] 2021-01-20 18:40
I'm restarting my laptop and finding out there's a system update. will test as soon as that's completed 👍

**Comment by keepitterron** [comment] 2021-01-20 18:59
haha this is unbelievable, your assumptions are absolutely correct @sokra !
rebooting fixes the issue!

**Comment by bmeurer** [comment] 2021-01-20 19:08
@sokra Awesome investigation! It never occurred to me that using `mach_absolute_time` might be a problem (I actually think I copied this from Chromium originally).

@psmarshall @paullewis We should investigate this and check what's the best way to fix this.

cc @chybie

**Closed** 2021-01-20 20:17 UTC
Labels: bug, webpack-4, webpack-5

**Comment by alexander-akait** [comment] 2023-05-18 14:07
@leimonio Can you create reproducible test repo, sounds like format was changed, need to investigate
