### ISSUE TITLE
harmony re-export written before harmony import when re-exporting a umd module from an ES6 module

### ISSUE THREAD

**Issue by rob-bateman** [webpack/webpack#3509] opened 2016-12-17 02:50 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When bundling an ES6 module that re-exports a UMD module while also requiring to import that module for further reference in the ES6 module, the resulting bundle tries to re-export the module _before_ the ```__webpack_require__``` import is made. Behaviour is observed in webpack@2.1.0-beta.28 and webpack@2.2.0-rc0

eg in my project AwayJS, the following code is generated in the awayjs-full.bundle.js when bundling the awayjs/lib/view module, causing a runtime error.

    /* harmony namespace reexport (unknown) */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_6__awayjs_view__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_6__awayjs_view__[key]; }) }(__WEBPACK_IMPORT_KEY__));
    Object.defineProperty(exports, "__esModule", { value: true });
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__awayjs_core__ = __webpack_require__(7);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__awayjs_core___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__awayjs_core__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__awayjs_graphics__ = __webpack_require__(8);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__awayjs_graphics___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1__awayjs_graphics__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__awayjs_stage__ = __webpack_require__(11);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__awayjs_stage___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2__awayjs_stage__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__awayjs_scene__ = __webpack_require__(9);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__awayjs_scene___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_3__awayjs_scene__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__awayjs_renderer__ = __webpack_require__(10);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__awayjs_renderer___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_4__awayjs_renderer__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__awayjs_materials__ = __webpack_require__(12);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__awayjs_materials___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_5__awayjs_materials__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__awayjs_view__ = __webpack_require__(15);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__awayjs_view___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_6__awayjs_view__);

notice the var ```__WEBPACK_IMPORTED_MODULE_6__awayjs_view__``` is attempted to be re-exported _before_ it is defined

**If the current behavior is a bug, please provide the steps to reproduce.**

    git clone https://github.com/awayjs/awayjs-examples.git
    cd awayjs-examples
    npm install
    npm run build

**What is the expected behavior?**

when bundling the same code in webpack@2.1.0-beta.27, the awayjs/lib/view module produces code in the awayjs-full.bundle.js that looks like this:

    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__awayjs_core__ = __webpack_require__(7);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__awayjs_core___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__awayjs_core__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__awayjs_graphics__ = __webpack_require__(8);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__awayjs_graphics___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1__awayjs_graphics__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__awayjs_stage__ = __webpack_require__(11);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__awayjs_stage___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2__awayjs_stage__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__awayjs_scene__ = __webpack_require__(9);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__awayjs_scene___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_3__awayjs_scene__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__awayjs_renderer__ = __webpack_require__(10);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__awayjs_renderer___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_4__awayjs_renderer__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__awayjs_materials__ = __webpack_require__(12);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__awayjs_materials___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_5__awayjs_materials__);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__awayjs_view__ = __webpack_require__(15);
    /* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__awayjs_view___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_6__awayjs_view__);
    /* harmony namespace reexport (unknown) */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_6__awayjs_view__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_6__awayjs_view__[key]; }) }(__WEBPACK_IMPORT_KEY__));

in this case, the re-export of ```__WEBPACK_IMPORTED_MODULE_6__awayjs_view__``` is made _after_ the var is defined, which is obviously correct.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

node v4.4.4, also tried with v6.9.1

If instead of using the pre-bundled umd module for @awayjs/view (the module being re-exported) i use the es6 module-based source, the latest webpack works without issue. However, this appears to be because the bundler can now detect exactly which exports it requires, and does this directly rather than iterating through all import keys as is done here.

Using UMD modules here is important for improving the speed of rebuilds so i'd prefer to stick to that option as a default if possible.

**Comment by aitboudad** [comment] 2016-12-17 16:49
In addition of `harmony re-export` I get the following error after upgrading to RC:

```console
Uncaught TypeError: Cannot convert undefined or null to object
```

![selection_047](https://cloud.githubusercontent.com/assets/1753742/21288346/af1f1cfe-c478-11e6-80dd-a93c87f866c2.png)
![selection_048](https://cloud.githubusercontent.com/assets/1753742/21288347/b1c67b5a-c478-11e6-82b7-efe34415026c.png)

**Comment by Kovensky** [comment] 2016-12-21 06:34
It looks like you are writing `export * from 'some-module'`.

It is actually _not possible_ to implement `export * from`, while preserving the order of imports, without either knowing the list of exports (which webpack doesn't as it's not an ES6 module) or using a `Proxy` (impossible to polyfill, needs engine support).

**Comment by sokra** [comment] 2016-12-21 22:06
@rob-bateman this looks like a webpack bug. Do you have a test repo where this bug happens?

**Comment by bebraw** [comment] 2016-12-28 14:42
@rob-bateman Any update? A test repo would help a ton.

**Comment by rob-bateman** [comment] 2016-12-31 22:22
@Kovensky i don't really follow how what you describe would cause the problem. The ```export *``` line is adding all module classes in ```__WEBPACK_IMPORTED_MODULE_6__awayjs_view__``` to the ```exports``` object in regular javascript, and this is a completely separate process from importing the module (and doesn't result in potential object clashes regardless of order).

I'm also not requiring the exports in the for loop to occur in any order, the issue is simply that webpack is trying to use the ```__WEBPACK_IMPORTED_MODULE_6__awayjs_view__``` object before it is written from the ```__webpack_require__```function.

If the written ```__WEBPACK_IMPORTED_MODULE_6__awayjs_view__``` import really cannot be moved, then a separate import variable should be set by webpack above the ```export *``` line so that the for loop can use that instead.

@bebraw yes, i should be able to knock up a quick test repo(s) next week.

**Comment by TheLarkInn** [comment] 2017-01-09 16:10
Pinging for update. This could be one of the last issues on our milestone and we want to hunt this down if we can get an example. Thank you so much.

**Comment by gund** [comment] 2017-01-09 16:16
If I correctly understand there is an issue when webpack generates sometimes code where he tries to access import before it actually imports it?

Because I had this issue with my library and what I did is just reordered position of exports.
If that is the issue I can try to provide real case repro.

Please let me know if that will make sense. Thanks.

**Comment by sokra** [comment] 2017-01-11 14:26
I think this issue is fixed in master branch. Please reopen if not.

**Closed by sokra** 2017-01-11 14:26 UTC
Labels: P0: Critical, X0: need more information, X9: waiting on confirmation

**Comment by aryzing** [comment] 2017-03-04 17:54
I believe I could be having this issue...

Steps to reproduce:
```sh
git clone https://github.com/aryzing/anccre.git
cd anccre
git checkout da78dbc
yarn
yarn build
yarn start # watch enabled in webpack, so will have to open new term window for this
```
Then navigate to `localhost:6121`.

The build will succeed, but there will be an error in the console about an undefined import.

Note. `Components` is a webpack alias for `/src/components` and `Containers` for `/src/containers`.

The component called `Dummy` is imported from both `/src/components/AukParents/AukParents.jsx` and `/src/containers/Dummy/Dummy.js`. The latter import resolves to `undefined`.

**Comment by jvega** [comment] 2017-05-29 19:04
@gund was right, reordering the exports the issue is resolved when exists a circular reference

```js
// index.js
export {default as First} from './first'
export {default as Second} from './second'

// first.js
export default first = () => {
    return 'first'
}

// second.js
import { First } from './index'
console.log(First) // ---> undefined
export default second = () => {
    return 'second'
}
```
if we reorder 

```js 
// index.js
export {default as Second} from './second'
export {default as First} from './first'
```

it works!!!
