### ISSUE TITLE
Release new node-libs-browser + webpack with bumped crypto-browserify dependency

### ISSUE THREAD

**Issue by philikon** [webpack/webpack#1568] opened 2015-10-29 21:22 UTC
The `crypto-browserify` version that's shipping with webpack (dependency via `node-libs-browser`) is seriously outdated and missing much functionality. See https://github.com/webpack/node-libs-browser/issues/34 for background, though this issue only talks about one particular problem.

I've created https://github.com/webpack/node-libs-browser/pull/36 to address the dependency issue in `node-libs-browser`. It'd be great to get a new release of `node-libs-browser` and accordingly a new release of `webpack` with those updated dependencies.

**Comment by ThaNarie** [comment] 2015-12-31 16:28
Any chance this can be picked up, the current `crypto-browserify` version doesn't work with `use strict` so our build fails in IE10.
Releasing a `0.5.4` version of `node-libs-browser` with https://github.com/webpack/node-libs-browser/pull/36  will also fix that issue.

**Comment by philikon** [comment] 2016-01-01 01:11
Agreed. Pretty please? :)

**Comment by martindederer** [comment] 2016-01-13 10:06
I am looking forward to this too. Is there anything that is preventing the implementation of the proposed solution?

**Comment by mroswald** [comment] 2016-01-13 10:15
No, but a workaround is to declare node-libs-browser from github master as a dependency of your application. that overrides the subdependency of webpack (worked for me)

...
"node-libs-browser": "webpack/node-libs-browser"

**Comment by martindederer** [comment] 2016-01-13 10:35
@mroswald Thanks for the pointer. I went with shrinkwrap overriding the crypto-browserify dependency to a current version though.

**Comment by vihangm** [comment] 2016-01-21 03:24
Any updates here? Chrome's Dev and Canary channels now throw when trying to use crypto.
`Failed to execute 'getRandomValues' on 'Crypto': parameter 1 is not of type 'ArrayBufferView'.`

A release would be nice to alleviate this issue.

**Comment by martindederer** [comment] 2016-02-01 09:24
According to the commit log this issue should be resolved since version 2.0.5-beta of webpack because webpack depends on node-libs-browser "^1.0.0" which in turn depends on crypto-browserify "^3.11.0".

**Comment by kripod** [comment] 2016-02-28 17:22
I would like to use the RSA functionality of the crypto API, which is already provided by the latest version of [crypto-browserify][https://github.com/crypto-browserify/crypto-browserify].

Please update the crypto dependency as soon as possible!

**Comment by hitchcott** [comment] 2016-05-11 09:10
@mroswald Your solution worked for me - thanks.

Can this be merged? I've had a nightmarish few hours trying to iron out an annoyingly subtle bug this is causing with `eth-lightwallet`.

**Comment by lastperson** [comment] 2016-08-16 10:54
Wasn't able to figure out @mroswald solution, but here is what worked for me:
Create `npm-shrinkwrap.json` with following contents, and update versions as needed (maybe you are using another version of webpack)
```
{
  "dependencies": {
    "webpack": {
      "version": "1.13.1",
      "from": "webpack@1.13.1",
      "dependencies": {
        "node-libs-browser": {
          "version": "1.0.0",
          "from": "node-libs-browser@0.5.3"
        }
      }
    }
  }
}
```
After that, `npm install` will use 1.0.0 of node-libs-browser inside of webpack.

**Comment by runn1ng** [comment] 2016-09-15 16:01
This is getting super annoying. Hacking inside shrinkwrap like this is unmaintainable. I will use beta webpack from now on, since it's just impossible to remember to rewrite the shrinkwrap all the damn time

**Comment by bebraw** [comment] 2017-03-25 09:28
Based on https://github.com/webpack/node-libs-browser this should be fixed now. Please re-open if you still encounter problems.

**Closed by bebraw** 2017-03-25 09:28 UTC
Labels: enhancement

**Comment by runn1ng** [comment] 2017-03-27 19:46
Thanks a lot! Yes, I can confirm that it's fixed. :1st_place_medal:

**Comment by Benno007** [comment] 2017-05-20 04:39
It seems like this made my bundle ~ 250kb larger by adding bn.js, elliptic and a few others into my production app.js. 👎
