### ISSUE TITLE
Webpack 4.19.1: undefinedresolvePathname is not defined (but 4.19.0 works!)

### ISSUE THREAD

**Issue by sorenhoyer** [webpack/webpack#8052] opened 2018-09-19 06:09 UTC
# Bug report

**What is the current behavior?**

The first time we npx start our project after a fresh npm install it seems to work. Subsequent attempt fail with a blank page and the following error (no compiler errors):

![image](https://user-images.githubusercontent.com/2083553/45733687-f1966080-bbe1-11e8-8c89-069f9f732218.png)

This started right after 4.19.1 was published yesterday, as soon as people did an npm install.

**If the current behavior is a bug, please provide the steps to reproduce.**

In our project we see this bug on all computers, and the fix is the same. To explicitly `npm install webpack@4.19.0` after the npm install script concludes.

**What is the expected behavior?**

npx start should always start up the website (not just the first time after a fresh npm install) and not result in a blank page + the error in the screenshot above. .

**Other relevant information:**
webpack version:  4.19.1
Node.js version: 8.11.4
Operating System: Windows 10 Pro 64 Bit
Additional tools:

"webpack-cli": "^3.0.8",
"webpack-dev-server": "^3.1.4",
"webpack-hot-middleware": "^2.22.2",
"webpack-merge": "^4.1.3"

**Comment by shincysl** [comment] 2018-09-20 04:34
Not sure if this is the same issue. We use hard-source plugin. The first time, webpack compiles successfully. But when run webpack again, there are syntax errors in the emitted code. The problem code looks like "undefinedfunction".
There are no changes in hard-source plugin. We just updated webpack from 4.19.0 to 4.19.1.

**Comment by mape** [comment] 2018-09-20 05:06
I'm having the same issue as @shincysl when using the [hard-source](https://github.com/mzgoddard/hard-source-webpack-plugin) plugin after updating from `4.19.0` to `4.19.1`. I tried creating a barebone project to reproduce the issue but for whatever reason it doesn't show the same symptoms as my main project.

**Comment by ooflorent** [comment] 2018-09-20 08:45
Could you confirm the error is gone if you remove `hard-source-webpack-plugin`?

**Comment by sorenhoyer** [comment] 2018-09-20 09:16
Great! The common denominator seems to be hard-source-webpack-plugin - we also use that! @ooflorent It does indeed seem to be working fine without it - just tested.

**Comment by sokra** [comment] 2018-09-20 16:33
@mzgoddard Do you know what causes this? Maybe we can find a backward-compatible change.

**Comment by kirschre** [comment] 2018-09-20 20:03
@ooflorent @sokra I'm running into the same issue as the users above. Little bit of extra debugging info - it seems `hard-source-webpack-plugin` can occasionally cause `dep.prefix` to be `undefined` [here](https://github.com/webpack/webpack/blob/cec5bfb01c025a28062646e18467293e4d6b93ab/lib/dependencies/HarmonyExportExpressionDependency.js#L38), which ends up getting directly inserted into the string output. Not sure why yet but I'll try to dig a little further.

**Comment by domoritz** [comment] 2018-09-26 01:32
I'm getting an error `Uncaught SyntaxError: Unexpected token {` with this code:

```
/***/ "./node_modules/d3-array/src/ascending.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = (undefinedfunction(a, b) {
  return a < b ? -1 : a > b ? 1 : a >= b ? 0 : NaN;
});


/***/ }),
```

Yes, I am also using hard-source.

**Comment by sokra** [comment] 2018-09-27 09:41
There is already a PR in hard-source-webpack-plugin fixing this: https://github.com/mzgoddard/hard-source-webpack-plugin/pull/444

Sorry that this is causing issues, hard-source-webpack-plugin relies on webpack internals for serialization. Internals may change in non-major version so it's a bit harder to keep in sync...

**Comment by sh4d1t0** [comment] 2018-09-27 16:14
I reverted to 4.19.0 and not working in production, 4.17.1 neither, only develop.
This is my repo: https://github.com/sh4d1t0/react-initial you can check the commits.

So I deleted hard-source-webpack-plugin and works again

**Comment by sibelius** [comment] 2018-11-07 17:56
it is a problem with `hard-source-webpack-plugin `

**Comment by sibelius** [comment] 2018-11-15 21:06
@sokra we can close this, this happens because of an old cache when using hard-source-webpack-plugin

**Closed** 2018-11-15 21:17 UTC
