### ISSUE TITLE
dynamic async import (require.ensure) should work on server side

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#3496] opened 2016-12-16 03:04 UTC
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

```
import('./pages/' + pageName + '.jsx').then(module => cb(null, module.default)).catch(ex => console.error(ex));
```

Throws:  **TypeError: __webpack_require__.e is not a function** on node.js

A workaround is:
```
  if (IS_BROWSER) {
    return (nextState, cb) => {
      import('./pages/' + pageName + '.jsx').then(module => cb(null, module.default)).catch(ex => console.error(ex));
    }
  } else {
    return (nextState, cb) => {
      require('./pages/' + pageName + '.jsx');
    }
  }
```

**What is the expected behavior?**
The import function (same for the deprecated functions require.ensure, System.import) should work natively on server side when target is "node".

**If this is a feature request, what is motivation or use case for changing the behavior?**

Node.js version: 7
Webpack version: 2.1, 2.2

**Comment by TheLarkInn** [comment] 2016-12-17 16:44
So missing context support for target node @sokra?

**Comment by TheLarkInn** [comment] 2016-12-21 17:05
@aight8 I tried reproducing this locally but I was not able to do so. Would you be able to provide a minimal reproducible example that I can test against.

**Comment by TheLarkInn** [comment] 2016-12-21 17:32
I'm going to remove this from release blocker until we get a response, I've added tests to cover for this better and I'll submit those.

**Comment by sokra** [comment] 2016-12-28 14:07
I wonder why this doesn't work because most of our tests are compiled with `target: node` and work fine.

I close this until we get more information.

**Closed by sokra** 2016-12-28 14:07 UTC
Labels: bug, webpack-2, X0: need more information

**Comment by jdrelick-leafgroup** [comment] 2017-01-03 22:00
So I've been working closely with import() and have a couple notes to contribute to this thread:

1. Node will complain about import(), but can be re-written to require.ensure() using the 'dynamic-import-node' babel plugin

2. Including 'dynamic-import-node' in .babelrc will cause code-splitting not to work, so I start my server using `babel-node server.js --plugins=dynamic-import-node` so it used only for the server, and the client code will be left alone and continue to use import() instead of require.ensure

3. When using eslint, Webpack 2 itself (not eslint, interestingly enough), will say: 
Parsing error: 'import' and 'export' may only appear at the top level

The dynamic import() in react-router getComponent() handlers is being treated the same as a static import statement, and therefore the parsing error occurs. 

I know this is a recent change, going from System.import() to import(), so I just wanted to share my findings in case anyone else is encountering these issues.
