### ISSUE TITLE
Support subpath export patterns in package.json

### ISSUE THREAD

**Issue by lcrosetto** [webpack/webpack#11616] opened 2020-10-09 17:40 UTC
## Feature request

**What is the expected behavior?**

Support patterns in subpath exports, as described here:

https://nodejs.org/api/packages.html#packages_subpath_export_patterns

**What is motivation or use case for adding/changing the behavior?**

Subpath exports are already implemented in webpack 5 ( #9509 ) however patterns were not implemented. 

**How should this be implemented in your opinion?**

As described in the nodejs docs.

**Are you willing to work on this yourself?**

No, but I can review / test.

**Comment by evilebottnawi** [comment] 2020-10-22 14:08
Related https://github.com/nodejs/node/pull/35747

**Comment by bmeck** [comment] 2020-10-22 14:45
I'm not sure I understand how this fixes path searching. Example of problem w/ collision of preact expecting searching but react transforms appending `.js` recently occured; given:

```json
{
  "exports": {
    "./hooks": {
      "browser": "./hooks/dist/hooks.module.js",
      "umd": "./hooks/dist/hooks.umd.js",
      "require": "./hooks/dist/hooks.js",
      "import": "./hooks/dist/hooks.mjs"
    }
  }
}
```

I'm unclear how `import("react/hooks")` [really Preact] would be fixed with patterns, it would require Preact to update, which it already could do w/o patterns but has chosen not to.

**Comment by evilebottnawi** [comment] 2020-10-22 14:48
@bmeck hm, I don't understand you, what is the problem here

**Comment by bmeck** [comment] 2020-10-22 14:59
react transforms now include the file extension in transpilation (e.g. `import "react/hooks.js";`) instead of the old `import "react/hooks"`; preact implemented an exports maps with only the non-file extension form so the specifier `"react/hooks.js"` generated by transpilers isn't found. The fix was in https://github.com/webpack/enhanced-resolve/pull/260 which added back searching. Searching made *both* `"react/hooks.js"` and `"react/hooks"` resolve, and you need both to resolve. With pattern's they don't add a specific capability that eases having both those specifiers to my knowledge.

**Comment by evilebottnawi** [comment] 2020-10-22 15:03
Resolving with extensions only for cjs by default, if you use `import` and don't disable `fullySpecified` all will work fine

**Comment by sokra** [comment] 2020-10-22 15:09
The mentioned PR doesn't add back searching for import "react/hooks"; only for commonjs require like Node.js does.

**Comment by guybedford** [comment] 2020-10-26 15:55
@sokra CommonJS require only does searching for trailing `/` subpath matches (which are now being deprecated), not exact matches.

**Comment by evilebottnawi** [comment] 2020-10-26 16:07
@guybedford import do the same, no differents between `CommonJS` and `ES` for `exports`

**Comment by thw0rted** [comment] 2020-12-15 10:58
Just to check, for now if we want `exports` to be respected by Webpack we must use the (now deprecated in Node) "subpath folder mappings" syntax (i.e. `"./path/"`), and package files that are written using only the new "subpath patterns" syntax (i.e. `"./path/*"`) will be ignored by Webpack.  Is that correct?

**Comment by alexander-akait** [comment] 2020-12-15 12:53
> package files that are written using only the new "subpath patterns" syntax (i.e. "./path/*") will be ignored by Webpack

Yep, use old syntax, we need improve this

**Comment by thw0rted** [comment] 2020-12-18 15:20
This seems like a pretty big problem.  If the `exports` field is present, Webpack must fail when the caller tries to `require` something that isn't exported, but it also can't understand all of the entries under `exports`.  It looks like I can hack around this by setting `options.resolve.exportsFields = []` (i.e., pretend the `exports` field does not exist) but that behavior forces fallback to `module` or `main` fields, and the use of aliasing for subresources.  It's also a very blunt tool since I'd have to completely ignore `exports` for all packages just to work around one broken one.  (Is there some way I can ignore the `exports` field for one package that I'm not thinking of?)

**Comment by alexander-akait** [comment] 2020-12-18 15:25
What is the problem? Just use old syntax, Very small packages uses new syntax right now, because it is experemental

**Comment by thw0rted** [comment] 2020-12-18 15:34
I have two related problems, one of which is directly relevant to this ticket.  I'm consuming libraries that use the new syntax.  One of them simply fails to expose some resources that they meant to -- they should fix this, but in the meantime I'm stuck consuming a package with a "bad" `exports` field.  Another library uses the new (subpath export pattern) syntax, which means that, since Webpack does not support it, the `exports` field *looks* like it doesn't expose all the right resources, which puts me in the same place as the former library.

As I say, the only workaround I've figured out is to totally disable `exports` parsing by modifying `resolve.exportsFields`.  I was just saying that it might be helpful to have a way to override / ignore `exports` on a per-dependency basis.

**Comment by alexander-akait** [comment] 2020-12-18 15:43
@thw0rted please provide simple reproducible test repo, I want to look, support subpath export patterns in package.json is not hard task

**Comment by alexander-akait** [comment] 2021-01-12 12:56
Fixed by https://github.com/webpack/enhanced-resolve/pull/279

**Closed by alexander-akait** 2021-01-12 12:56 UTC
Labels: enhancement, webpack-5

**Comment by bilalkhalidshaikh** [comment] 2021-02-01 13:53
http://192.168.0.102:4000
