### ISSUE TITLE
Webpack: How to don't bundle node_modules, but use them normally in node.js?

### ISSUE THREAD

**Issue by bitplanets** [webpack/webpack#603] opened 2014-12-02 18:00 UTC
# Architecture

I would like to share code between client and server side. I have defined aliases in the webpack config:    

```
resolve: {
    // Absolute paths: https://github.com/webpack/webpack/issues/109
    alias: {
        server : absPath('/src/server/'),
        app    : absPath('/src/app/'),
        client : absPath('/src/client/'),
    }
},
```
# Problem

Now on the server side I need to include webpack in order to recognize the correct paths when I require a file. For example

```
require('app/somefile.js')
```

will fail in pure node.js because can't find the app folder.
# What I need (read the What I need updated section)

I need to be able to use the webpack aliases. I was thinking about making a bundle of all the server part without any file from node_modules. In this way when the server starts it will use node_modules from the node_modules folder instead of a minified js file (Why? 1st: it doesn't work. 2nd: is bad, because node_modules are compiled based on platform. So I don't want my win files to go on a unix server).

Output:
- Compiled `server.js` file without any node_modules included.
- Let the `server.js` to use node_modules;
# What I need updated

As I've noticed in https://github.com/webpack/webpack/issues/135 making a bundled server.js will mess up with all the io operation file paths. 

A better idea would be to leave node.js server files as they are, but replace the `require` method provided with a custom webpack `require` which takes in account configurations such as aliases (others?)... Can be done how require.js has done to run on node.js server.
# What I've tried

By adding this plugin in webpack

```
 new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"ignore", /* filename= */"server.bundle.js")
```

Entries:

```
entry: {
    client: "./src/client/index.js",
    server: "./src/server/index.js",
    ignore: ['the_only_node_module'] // But I need to do that for every node_module
},
```

It will create a file server.js which only contains my server code. Then creates a server.bundle.js which is not used. But the problem is that webpack includes the `webpackJsonp` function in the `server.bundle.js` file. Therefore both the client and server will not work.

It should be a way to just disable node_modules on one entry.
# What I've tried # 2

I've managed to exclude the path, but requires doesn't work because are already minified. So the source looks like `require(3)` instead of `require('my-module')`. Each require string has been converted to an integer so it doesn't work.

In order to work I also need to patch the require function that webpack exports to add the node.js native require function (this is easy manually, but should be done automatically).
# What I've tried # 3

In the webpack configuration:

```
{target: "node"}
```

This only adds an `exports` variable (not sure about what else it does because I've diffed the output).
# What I've tried # 4 (almost there)

Using

```
require.ensure('my_module')
```

and then replacing all occurrences of `r(2).ensure` with require. I don't know if the `r(2)` part is always the same and because of this might not be automated.
# Related
- https://www.bountysource.com/issues/1660629-what-s-the-right-way-to-use-webpack-specific-functionality-in-node-js
- https://github.com/webpack/webpack/issues/135
- http://webpack.github.io/docs/configuration.html#target
- https://github.com/webpack/webpack/issues/458
- http://stackoverflow.com/questions/26063480/how-to-simultaneously-create-both-web-and-node-versions-of-a-bundle-with-web
- http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/

Thanks

**Comment by bebraw** [comment] 2015-11-15 11:22
@bitplanets Safe to close?

**Comment by lingz** [comment] 2016-01-30 16:09
There's a edge case not handled by the solution proposed by @sokra because modules with "/" in their name will not get properly replaced. You need to use a function that identifies slashes and checks if the base name is in the node_modules folder also:

```
var Fs = require('fs')
var nodeModules = {}
Fs.readdirSync('node_modules').forEach(function (module) {
  if (module !== '.bin') {
    nodeModules[module] = true
  }
})
var nodeModulesTransform = function(context, request, callback) {
  // search for a '/' indicating a nested module
  var slashIndex = request.indexOf("/");
  var rootModuleName;
  if (slashIndex == -1) {
    rootModuleName = request;
  } else {
    rootModuleName = request.substr(0, slashIndex);
  }

  // Match for root modules that are in our node_modules
  if (nodeModules.hasOwnProperty(rootModuleName)) {
    callback(null, "commonjs " + request);
  } else {
    callback();
  }
}

...
externals: nodeModulesTransform
```

You can see a complete webpack config with this working here:
https://gist.github.com/lingz/14ad8ea44998f5009d5d

**Comment by ericclemmons** [comment] 2016-02-05 19:17
Just wasted an hour on this.  I thought that `resolve.root` and `resolve.alias` worked on the server but it doesn't.

So much for sharing code between both server & client :(

Unless there's a fix for this, it'd probably be best to put a note in the docs about how it's `target: "web"` only.

**Comment by ericclemmons** [comment] 2016-02-05 19:19
Holy crap!  Luckily, somehow found a fix here:

> kriasoft/react-starter-kit#249

```js
externals: fs.readdirSync("node_modules"),
```

**Comment by ericclemmons** [comment] 2016-02-05 19:34
Another version here:

```js
      externals: function(context, request, callback) {
        // Absolute & Relative paths are not externals
        if (request.match(/^(\.{0,2})\//)) {
          return callback();
        }

        try {
          // Attempt to resolve the module via Node
          require.resolve(request);
          callback(null, request);
        } catch(e) {
          // Node couldn't find it, so it must be user-aliased
          callback();
        }
      },
```

**Comment by liady** [comment] 2016-02-18 00:14
You can also use [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals):

```js
var nodeExternals = require('webpack-node-externals');
...
module.exports = {
    ...
    target: 'node', // in order to ignore built-in modules like path, fs, etc. 
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder 
    ...
};
```

**Comment by acarl005** [comment] 2016-04-28 20:11
Why blacklist a bunch of npm packages in `externals`? The cleanest way is to just use a regexp that matches things that don't start with a period. All of your own modules should be a relative path and should start with either `./` or `../`.

```javascript
module.exports = {
  entry: { ... },
  target: 'node',
  output: { ... },
  externals: /^[^.]/,
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        query: {
          presets: [ 'es2015', 'stage-0' ],
        },
      },
    ],
  },
  context: __dirname,
  node: {
    __filename: true,
  }
}

```

**Comment by liady** [comment] 2016-04-28 20:37
@acarl005 I personally use a lot of aliases in Webpack that point to different parts of my app:
```js
// webpack.config.js
...
resolve: {
  alias: {
    'components': './src/components',
    'services': './src/services',
    ...
  }

// Root.js
import "TextBox" from "components/TextBox";
```
If I'm externalizing using a regex, it will leave un-bundled those modules as well, since they are falsely recognized as "not starting with period".
(It is also explained [here](https://github.com/liady/webpack-node-externals#qa)).

Going through the actual node modules guarantees the most stable *externals* config.

**Comment by acarl005** [comment] 2016-10-13 18:54
@liady thanks for clarifying. i didn't know about the alias feature.

**Comment by javie007** [comment] 2017-01-17 03:08
In my opinion, we don't need bundle in node environment. If the result are many files, we don't need tree-shaking.

**Comment by Download** [comment] 2017-04-09 14:57
But using a bundle on the server side has some advantages. Doing HMR on the server side during development is one. It would be great if there was a simpler way to just tell webpack 'exclude everything in `node_modules``. Currently it's a difficult configuration item to get right.

**Comment by MikeBailleul** [comment] 2017-05-04 02:18
@Download: the solution provided by @liady seems pretty simple to me. More about webpack config file for backend [here](http://stackoverflow.com/a/43202748) 
Also, what are the other advantages when using a bundle on server side?

And can someone explain to me why we need to exclude node_modules? Wouldn't it be more efficient to bundle every required module just like we do on the client side?
Even if features like tree shaking are not useful on server side, I don't see any cons doing it. Am I missing something here?

**Comment by coderas** [comment] 2017-05-04 15:32
@MikeBailleul need to use the same instance of a shared deps across two or more apps (like react) ? Or leverage caching for vendor bundles ?

**Comment by Download** [comment] 2017-05-04 19:30
@MikeBailleul Other advantages: You have a single file to distribute that will just run. No `npm install` needed.

And a single file app starts faster (significantly so in some cases) because [require is slow](https://kev.inburke.com/kevin/node-require-is-dog-slow/).

Also, going through the 'compile' process for the server side can help you use ES2015 features and still support older Node JS versions (same as with browsers basically). 

You can minify it and have smaller footprint etc etc.

It all depends on what you want to achieve. But there can be many such advantages depending on what your requirements are.

**Comment by dizel3d** [comment] 2017-08-04 08:33
Obviously, it would be useful to have `this` context in a function of externals handling like in loaders. The context would have [resolveSync](https://webpack.js.org/api/loaders/#this-resolvesync) at least.
```js
externals: [
    function(context, request, callback) {
        // get absolute path to required file
        const resourcePath = this.resolveSync(context, request);

        // don't bundle node_modules
        if (/node_modules/.test(resourcePath)) {
            return callback(null, 'commonjs ' + request);
        }
        callback();
    }
]
```
Is there any problem to add the feature?

**Comment by BDGrace** [comment] 2019-07-19 19:53
Just don't tell webpack about the node_modules you want to use:
eval("require")("module with dynamic require statements or optional dependendencies...")

**Comment by evilebottnawi** [comment] 2020-08-10 18:01
Let's close in favor the `externals` option, if you have some problems with `externals` please open a new issue with reproducible test repo, thanks for using webpack

**Closed by evilebottnawi** 2020-08-10 18:01 UTC
Labels: question
