### ISSUE TITLE
[BUG] webpack 4.20.0 breaks many apps, please fix it.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#8450] opened 2018-12-03 08:07 UTC
It seems the responsible thing to do is to provide a backwards-compatibility patch for https://github.com/webpack/webpack/issues/8082 rather than not doing anything for 2 months and counting.

I accept that people make mistakes, everyone makes them. We're human.

But please, take responsibility and don't just let things like this sit for 2 months.

**Comment by sokra** [comment] 2018-12-03 10:06
The problem is fixed in the latest version of webpack-cli. Upgrade it.

**Comment by ematipico** [comment] 2018-12-03 13:43
The problem was never there. When that version was released, in the change log there were also instructions to upgrade the webpack-cli otherwise there would be problems.

**Comment by evilebottnawi** [comment] 2018-12-03 13:45
Answers above

**Closed by evilebottnawi** 2018-12-03 13:45 UTC

**Comment by connor4312** [comment] 2018-12-03 16:21
Perhaps the 48 links and 97 references in the linked issue indicate that something might have gone wrong?

**Comment by ematipico** [comment] 2018-12-03 17:04
@connor4312 `webpack` maintainers provided a new feature AND a fix for that (external dep, as the the cli it's on a different repo) released almost at the same time. Now, things could in different ways:

1. Feature needed? The developer upgrades also the cli (it's good practice to read the changelog)
2. Feature not needed? No need to upgrade

Now, we need all to understand that `webpack` is a particular library where the cli and the library are in different repositories and are very tight together. Considering that,  I'd say upgrading that upgrade them at the same time should be the best practice OR paying to them more attention.

**Comment by connor4312** [comment] 2018-12-03 17:06
>  The problem was never there. When that version was released, in the change log there were also instructions to upgrade the webpack-cli otherwise there would be problems.

I mean, that's true of any breaking change (when there's a good changelog). That doesn't mean the change is not breaking or that it should not be a major, rather than minor, semver revision.

> Considering that, I'd say that upgrading them at the same time should be the best practice OR paying to them more attention.

The problem is that npm's default and best practice is to lock to minor revisions. The issue here is that people who were locked to minor versions of `webpack` and `webpack-cli` experienced a breaking change. That's why, as can we seen on the linked issue, hundreds of consumers have been affected by this.

**Comment by ematipico** [comment] 2018-12-03 17:10
You just hit the very point, the same point I wanted to expose (but not related to this issue). Locking to minor versions 😅

**Comment by MacKentoch** [comment] 2018-12-12 05:55
Thank you @sokra upgrading cli fixed 👍
