### ISSUE TITLE
Bundle size increased after upgrading from 4.0.1 to 4.6.0 - due to comments in built files

### ISSUE THREAD

**Issue by asolopovas** [webpack/webpack#7114] opened 2018-04-24 11:08 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**

The bundle size was 400 KiB after upgrade of webpack from 4.0.1 to 4.6.0 the size increased to 739 KiB

**If the current behavior is a bug, please provide the steps to reproduce.**

I can't provide access to the repository as its private. But can show my webpack config...
`webpack production config`
https://gist.github.com/asolopovas/b499a052eff4581704fff4bc52b1d4c5
`second part of config with loader rules`
https://gist.github.com/asolopovas/b0933ae085f954e9d05e4371d58a3d98

The funny thing is that If I roll back straight away to 4.0.1 the bundle size remains the same at 739KiB I have restored my lockfile and only then the bundle size get back to its original 400 KiB size. But the upgrade of webpack immediately triggers the increase in size.

**What is the expected behavior?**
To have similar bundle size to previous veriosn

Operating System: Windows 10 x64, Node: v9.11.1

**Comment by evilebottnawi** [comment] 2018-04-24 11:55
@asolopovas can you diff between files?

**Comment by asolopovas** [comment] 2018-04-24 12:12
Files are exactly same, literally as soon as I do yarn upgrade webpack@4.6.0 bundle size increases, I think it changes the yarn.lock file so if I roll back to 4.0.1 it still generates bundle by 339KiB bigger.

**Comment by asolopovas** [comment] 2018-04-24 12:13
I have upgraded every single package I had in my app and only when I upgrade webpack it happens.

**Comment by asolopovas** [comment] 2018-04-24 12:34
https://drive.google.com/drive/folders/15sgjkSkt6g9I3iOxFaWPjNtCDRABenqr?usp=sharing

**Comment by asolopovas** [comment] 2018-04-24 12:54
If I use webpack-bundle-analyzer the main chunk after update at 928.74 KiB and before update at  928.72Kib. But http://chrisbateman.github.io/webpack-visualizer/ shows main chunk as 371.6k (was 400 before I added loadash plugin) and after updating its 659.6k which reflects real situation.

**Comment by montogeek** [comment] 2018-04-24 13:13
@asolopovas Try using http://webpack.github.io/analyse/ to found more differences. Just to make sure since we don't a reproducible repo, Can you please report actual directory size using `du -sh dist`?

**Comment by montogeek** [comment] 2018-04-24 13:30
It is so weird, take for example `_typed-array.js`, it changes from 7k to 13kb, or `index.js` file from `algoliasearch`, from 15k to 27k, it seems like either `NODE_ENV` is not working so you are getting unnecessary code or dependencies `node_modules` are being bundled as well.

**Comment by montogeek** [comment] 2018-04-24 13:34
I guess from your webpack config that you are not using a `.babelrc` file?
Also, How are you running your command?

**Comment by asolopovas** [comment] 2018-04-24 13:34
This what gets generated in updated webpack output
``` 
(window.webpackJsonp=window.webpackJsonp||[]).push([[0],{704:
/*!***********************************************************!*\
  !*** C:/code/dev.test/node_modules/lodash/fp/get.js ***!
  \***********************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,o,r){var t=r(/*! ./convert */42)("get",r(/*! ../get */786));t.placeholder=r(/*! ./placeholder */37),n.exports=t},785:
/*!*************************************************************!*\
  !*** C:/code/dev.test/node_modules/lodash/_baseGet.js ***!
  \*************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,o){n.exports=function(n,o){return null==n?void 0:n[o]}},786:
/*!********************************************************!*\
  !*** C:/code/dev.test/node_modules/lodash/get.js ***!
  \********************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(n,o,r){var t=r(/*! ./_baseGet */785);n.exports=function(n,o,r){var e=null==n?void 0:t(n,o);return void 0===e?r:e}}}]);
```

This gets generated in old one 
```
(window.webpackJsonp=window.webpackJsonp||[]).push([[0],{704:function(n,o,r){var t=r(42)("get",r(786));t.placeholder=r(37),n.exports=t},785:function(n,o){n.exports=function(n,o){return null==n?void 0:n[o]}},786:function(n,o,r){var t=r(785);n.exports=function(n,o,r){var e=null==n?void 0:t(n,o);return void 0===e?r:e}}}]);
```

**Comment by montogeek** [comment] 2018-04-24 13:37
Cann you try adding `{ "modules": false }` to your `babel-preset-env` config?

**Comment by asolopovas** [comment] 2018-04-24 13:40
You mean in .babelrc?

**Comment by whtsky** [comment] 2018-04-24 13:42
I think that's related to https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/250 which gets merged into `uglify-webpack-plugin` in v1.2.4
and webpack uses `uglify-webpack-plugin` since 4.3.0: https://github.com/webpack/webpack/commit/44dfc682693e177a549cb0949979e833f30e64b1

**Comment by montogeek** [comment] 2018-04-24 13:43
I doesn't look like you are using one (https://github.com/webpack/webpack/issues/7114#issuecomment-383932261), update it on your webpack rules config.

If you also have a `.babelrc` file, try deleting it.

**Comment by asolopovas** [comment] 2018-04-24 13:45
@montogeek  if I add it to .babelrc it doesn't change a thing but if I do it in rules 

```
ERROR in ./app.js
Module build failed: ReferenceError: [BABEL] C:\code\db.3oak.co.uk\resources\assets\js\app.js: Using removed Babel 5 option: foreign.modules - Use the corresponding module transfor
m plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
```

**Comment by whtsky** [comment] 2018-04-24 13:46
So setting `uglifyOptions.output.comments` back to `false` might solve the problem
```js
  new UglifyJsPlugin({
    uglifyOptions: {
      output: {
        comments: false
      }
    }
  })
```

**Comment by montogeek** [comment] 2018-04-24 13:48
It should be:
```js
presets: ['env', { modules: false }]
```

Also try @whtsky solution, might be that.

**Comment by asolopovas** [comment] 2018-04-24 13:50
@whtsky Sorry to be lame, does it mean that I should remove     
```
new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false,
    }),
```
And use UglifyJsPlugin instead?

**Comment by asolopovas** [comment] 2018-04-24 13:51
@montogeek If I add `modules:false` to loader options it throws an error on build on which I commented above.

**Comment by asolopovas** [comment] 2018-04-24 13:53
@whtsky it does fix the error I use your approach.

**Comment by asolopovas** [comment] 2018-04-24 13:55
It looks like @4.0.1 version it was removing comments by itself and then stopped doing that.

**Comment by evilebottnawi** [comment] 2018-04-24 13:55
Why difficult do diff between files and looks what changes? Also legal comments is good practice

**Comment by whtsky** [comment] 2018-04-24 13:56
@asolopovas you don't need to remove them. Just add it like
```diff
+ const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  entry: {
    main: [
      'babel-polyfill',
      'app',
    ],
  },
  context: utils.resolve('resources/assets/js'),
  optimization: {
    minimize: true,
    splitChunks: {
      chunks: 'async',
      minSize: 1000,
      minChunks: 2,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      name: true,
      cacheGroups: {
        default: {
          minChunks: 1,
          priority: -20,
          reuseExistingChunk: true,
        },
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10,
        },
      },
+    minimizer: [
+      new UglifyJsPlugin({
+        cache: true,
+        parallel: true,
+        uglifyOptions: {
+          output: {
+            comments: false
+          }
+        }
+      })
+    ]
    },
};
```

**Comment by whtsky** [comment] 2018-04-24 13:57
Yeah I agree legal comments is a good practice but current implementation includes a lot of non-legal comments in build hence produce very huge output ( like the example above )

**Comment by montogeek** [comment] 2018-04-24 14:00
@whtsky I thought about that when I saw those comments, but discarded that possibility, 384 kb in space just for comments is a lot.

**Comment by asolopovas** [comment] 2018-04-24 14:00
@evilebottnawi I agree that was stupid not to have a look at diff between files first, sorry for wasted time. @whtsky thanks for resolution

**Comment by evilebottnawi** [comment] 2018-04-24 14:03
@whtsky can you create issue in uglify repo what comments should be removed?

**Closed** 2018-04-24 14:02 UTC

**Comment by whtsky** [comment] 2018-04-24 14:09
@evilebottnawi I'm glad to do it tomorrow with a reproduction repo.
though I found extracting legal infos by extracting legal comments using uglifyjs might not be that useful in practice since a lot of library doesn't provide the correct legal comment, like [ant-design](https://github.com/ant-design/ant-design)

**Comment by whtsky** [comment] 2018-04-25 04:47
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/278
