### ISSUE TITLE
WebpackOptionsValidationError does not throw correctly on Node 7.2.1 (webpack 2.2.0-rc.1)

### ISSUE THREAD

**Issue by scottdj92** [webpack/webpack#3522] opened 2016-12-19 18:11 UTC
Webpack 2.2.0-rc.1 has an error messaging bug.

Current behavior is throwing an error, but it does not display where the error comes from, nor does it display the recommended fixes.

0. Add some obvious error in your webpack config such as using `modulesDirectories` instead of `modules` under `resolve`.
1. Ensure you have Node 7.2.1 (latest version as of 12/19/2016).
2. run `webpack-dev-server --hot --inline` `--colors` and `--progress` arguments optional.
3. See that the error is thrown, but no explanation as to why it throws is given.
4. Switch to LTS (6.9.2 as of 12/19/2016) and run the same command.
5. See the error being thrown, but now we have a description of what the error is.

The expected behavior is that it should only ouput the error in the CLI, rather than leveraging Node's internal error messaging.

Tested on OS X 10.11.6, Node 7.2.1 & Node 6.9.2, and using iTerm2 emulator.

**Comment by SpaceK33z** [comment] 2016-12-24 19:02
Does this also happen when you do the same in `webpack` instead of `webpack-dev-server`? If it's dev-server specific please post in the [webpack-dev-server repo](https://github.com/webpack/webpack-dev-server/issues).

Note that Node.js v7 has other known issues in dev-server (which the README warns about).

**Comment by scottdj92** [comment] 2016-12-27 15:43
Hmm, seems to be working fine on Node 7.3.0. I tried building the project using `webpack` and `webpack-dev-server`

**Comment by SpaceK33z** [comment] 2016-12-27 16:09
Interesting. Since no others complained about this, I'm closing this.

**Comment by atrefz** [comment] 2017-01-05 09:57
I have this same bug under node v7.3.0 with webpack v2.2.0-rc3

**Comment by mjbates7** [comment] 2017-01-05 17:10
I also get the same issues as @atrefz above.

**Comment by SpaceK33z** [comment] 2017-01-05 17:14
Okay, re-opening. If someone could do a PR while maintaining node v4+ compatibility, that would be great.

**Comment by codepunkt** [comment] 2017-01-09 09:08
Same as @atrefz 

webpack 2.2.0-rc.3, node 7.2.0, 7.3.0 and 7.4.0 - WebpackOptionsValidationError message is completely missing. 6x LTS versions are fine.

**Comment by SpaceK33z** [comment] 2017-01-09 10:57
@codepunkt we know it's happening, if someone would like to submit a PR that would really be welcome... Shouldn't be too difficult.

**Comment by timse** [comment] 2017-01-22 12:31
what is the error that is throw?

i cant reproduce this at all I do get npm errors on v7 though. but that is an npm/node version manager issue

**Comment by archangel-irk** [comment] 2017-02-02 21:25
I have the same error with empty config (for example).

If I use webpack from cli I receive:
```
node_modules/webpack/bin/convert-argv.js:488
  throw new Error("'output.filename' is required, either in config file or as --output-filename");
                   ^

Error: 'output.filename' is required, either in config file or as --output-filename
```

If I use webpack from node I receive:
```
node_modules/webpack/lib/webpack.js:19
  throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
```

for node I used webpackDevMiddleware and webpackHotMiddleware
```js
const webpackConfig = require('./webpack.config');
const compiler = webpack(webpackConfig, (err, stats) => {
  if (err) {
    console.error(err.stack || err);
    if (err.details) {
      console.error(err.details);
    }
    return;
  }

  const info = stats.toJson();

  if (stats.hasErrors()) {
    console.error(info.errors);
  }

  if (stats.hasWarnings()) {
    console.warn(info.warnings);
  }
});
const devMiddleware = webpackDevMiddleware(compiler, {
  // Display no info to console (only warnings and errors)
  noInfo: true,

  // Public path to bind the middleware to
  // use the same as in webpack
  publicPath: webpackConfig.output.publicPath,
});

app.use(devMiddleware);
app.use(webpackHotMiddleware(compiler));
```

**Comment by scottdj92** [comment] 2017-02-02 21:59
There's been a new addition to webpack, it now enforces configuration validation. @archangel-irk you need to pass in a config. If you can, please share it with us.

**Comment by archangel-irk** [comment] 2017-02-03 07:07
> There's been a new addition to webpack, it now enforces configuration validation. @archangel-irk you need to pass in a config. If you can, please share it with us.

Thank you, I know about additional validation in webpack 2. My config doesn't matter, we discuss about throwing errors and difference between cli and node runs.

**Comment by 3DEsprit** [comment] 2017-02-03 23:38
I was encountering this error with Node 7.4.0 and 2.2.0. 

While it may be known now, the error stopped after I upgraded Node to 7.5.0. Now everything works again without any errors.

**Comment by sokra** [comment] 2017-02-17 10:44
fixed by #4257

**Closed by sokra** 2017-02-17 10:44 UTC
Labels: P2: Very Important, S2: Inconvenient, webpack-2, X5: work required (PR / Help Wanted)

**Comment by chenfanggm** [comment] 2017-03-12 18:39
How can I apply this to my webpack before there's a release?

**Comment by scottdj92** [comment] 2017-03-13 13:18
@chenfanggm you can set your package.json's webpack version to the git url, and npm will pull the latest code from master.

**Comment by muskand** [comment] 2017-03-15 15:09
Are we expecting a release any time soon?
