### ISSUE TITLE
Uncaught ReferenceError: React app throwing error when reading from hard-source cache

### ISSUE THREAD

**Issue by gauravkg15** [webpack/webpack#8092] opened 2018-09-26 18:00 UTC
# Bug report

**What is the current behavior?**
React app doesn't load and throws this console error.
![screen shot 2018-09-26 at 10 43 28 am](https://user-images.githubusercontent.com/23143990/46099049-a4cefe80-c17a-11e8-9317-65a1e5c923db.png)

![screen shot 2018-09-26 at 10 48 48 am](https://user-images.githubusercontent.com/23143990/46099316-50784e80-c17b-11e8-8f78-74a6d14a607e.png)

Temporary fixable by disabling the hard-source-webpack-plugin from your Webpack config. Your react app will take a lot longer to build since its not reading from a cache anymore

**If the current behavior is a bug, please provide the steps to reproduce.**
Run an npm start, load your page, kill npm, run npm start again so webpack reads from the hard-source cache, load your page, and inspect to see the console error 

**What is the expected behavior?**
I can run webpack and kill it any number of times, and when reading from the hard-source cache, the react app still builds and doesn't throw an unknown error

**Other relevant information:**
webpack version:  4.20.2
Node.js version: 10.11.0
Operating System: MacOS High Sierra 10.13.6
Additional tools:

**Comment by montogeek** [comment] 2018-09-26 20:56
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment] 2018-09-27 03:52
Duplicate of #8052

**Closed by sokra** 2018-09-27 03:52 UTC
