### ISSUE TITLE
Webpack source maps are broken for debugging in Firefox

### ISSUE THREAD

**Issue by Stuk** [webpack/webpack#1194] opened 2015-06-25 04:32 UTC
I've put together a quick repo to demonstrate the problem: https://github.com/Stuk/webpack-sourcemaps-firefox

And here's a gif of the issue in action:

![screencap](https://cloud.githubusercontent.com/assets/48019/8346824/1b3e9ada-1ab7-11e5-8848-271aa7933b2c.gif)

I've checked Uglify, and Firefox has no issues there. I've tried the different config options for `devtool`:
- `eval` - works
- `cheap-eval-source-map` - works
- `cheap-source-map` - does not work
- `cheap-module-eval-source-map` - works
- `cheap-module-source-map` - does not work
- `eval-source-map` -  works
- `source-map` - does not work

So seems like eval is file, but an external sourcemap for multiple files does not.

Any thoughts about what's going on?

I've also filed an issue on Bugzilla, in case this is a FF devtools issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1177329

**Comment by sokra** [comment] 2015-06-27 18:54
Propably a FF issue...

**Comment by mllocs** [comment] 2015-06-29 09:23
this might fix the issue: https://github.com/mishoo/UglifyJS2/pull/738

**Comment by tirithen** [comment] 2015-11-10 21:43
:+1:

**Comment by bebraw** [comment] 2015-11-14 18:13
@Stuk Can you still see this issue?

**Comment by Stuk** [comment] 2015-11-17 17:56
@bebraw yep. I just checked on FF 42.0 and webpack 1.12.6, and I can still see this issue using the repo in the description. It seems like breakpoints sometimes work... but are very unreliable.

**Comment by amarandon** [comment] 2016-01-10 19:14
Here with Firefox 45.0a2 I'm not able to get any source map to work with Firefox. I tried with source maps generated by uglify and babel and they both work in Chrome but not in Firefox. It's ironic since they're both based on the [source-map](https://github.com/mozilla/source-map) package which is also the one used by Firefox.

**Comment by adamziel** [comment] 2016-01-11 14:42
@amarandon I have the same issue

**Comment by amarandon** [comment] 2016-01-11 15:30
@adamziel Actually it works in the debugger, it's just that error messages in the console point to the compiled code: https://youtu.be/pgS3x1hGPZ0 
I've contacted the developer on Twitter: https://twitter.com/alex_marandon/status/686514228572864512

**Comment by es6Test** [comment] 2016-02-26 11:44
Also having no luck with chrome anymore.

**Comment by maxdow** [comment] 2016-02-26 11:47
in my case chrome is working since sourcemaps are correctly defined. I can confirm the issue with FF..

**Comment by es6Test** [comment] 2016-02-26 12:00
here is my config that breaks chrome:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    'babel-polyfill',
    './app/app.js'
  ],
  output: {
    publicPath: '/',
    filename: 'dist/main.js'
  },
  debug: true,
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.js$/,
        include: path.join(__dirname, 'app'),
        loader: 'babel',
        query: {
          presets: ['es2015']
        }
      },
      { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
      { test: /\.css$/, loader: 'style-loader!css-loader' }

    ]
  },
  resolve: {
    extensions: ["", ".webpack.js", ".web.js", ".js", ".css",".styl"]
  }
};
```
```
"devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-core": "^6.1.20",
    "babel-loader": "^6.1.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-1": "^6.3.13",
    "css-loader": "^0.23.1",
    "material-ui": "^0.14.0",
    "style-loader": "^0.13.0",
    "stylus-loader": "^1.5.1",
    "tape": "^4.2.2",
    "webpack": "^1.12.12",
    "webpack-dev-server": "^1.12.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.1.19",
    "moment": "^2.11.2",
    "normalize.css": "^3.0.3"
  }```

**Comment by bogas04** [comment] 2016-04-03 09:16
Can we please fix this? I don't want to choose Chrome as the browser only coz of this issue.

**Comment by Stuk** [comment] 2016-04-03 12:13
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1177329 this should be fixed in FF nightly builds. Afraid I can't check as I'm on vacation at the moment

**Comment by bogas04** [comment] 2016-04-03 12:15
I'm on 48.0a1 (2016-04-02) and it doesn't seem to work here sadly!

**Comment by bogas04** [comment] 2016-04-03 13:05
Screenshots:

Vilvadi Browser (Effectively Chrome)
![screen shot 2016-04-03 at 6 34 35 pm](https://cloud.githubusercontent.com/assets/6177621/14232495/c65723e0-f9ca-11e5-8e90-bae6cacc0546.png)
Firefox Nightly 48.0a1 (2016-04-2)
![screen shot 2016-04-03 at 6 34 42 pm](https://cloud.githubusercontent.com/assets/6177621/14232496/c65ce906-f9ca-11e5-9d83-4552618217e1.png)

**Comment by jontonsoup** [comment] 2016-04-08 16:48
can confirm this works in ff nightly and not in chrome Version 51.0.2700.0 dev (64-bit)

**Comment by activescott** [comment] 2016-06-20 07:09
Using `devtool: 'eval'` it is not working in Firefox 48.0b1 (beta channel) but is working for me in Chrome 51.0.2704.103 (64-bit).

**Comment by aCandidMind** [comment] 2016-07-19 12:35
Using FF 46.0 on Ubuntu.
eval-source-map - _sort of works_
source-map - _sort of works_
Where _sort of works_ means, I can find the original JSX source files (which have no syntax highlighting), set a breakpoint into them and they are triggered. But the console always shows the useless bundle lines.

**Comment by spacem** [comment] 2016-08-28 23:23
Since sourcemaps were not working I switched to chrome which was fine for a while but then also stopped working. Someone said on chrome to fix it just delete these files:
chrome-devtools_devtools_0.localstorage
chrome-devtools_devtools_0.localstorage-journal

Deleting them made sourcemaps start working again on chrome (in52.0.2743.116 m). Not sure really what that does but I wonder is there a similar fix for firefox?

**Comment by ricochet1k** [comment] 2016-10-22 03:41
Firefox 50+ has fixed this, but it is not yet enabled by default:
- Fixed in: https://bugzilla.mozilla.org/show_bug.cgi?id=670002
- Announcement: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Source_maps
- Enable by default: https://bugzilla.mozilla.org/show_bug.cgi?id=1289570

**Comment by SpaceK33z** [comment] 2016-12-07 13:08
Can anyone verify that the issue is fixed? See also @ricochet1k's comment above.

**Comment by wallacyyy** [comment] 2017-02-03 13:28
I was not enable to make this work. @SpaceK33z

**Comment by gabrielmicko** [comment] 2017-03-27 11:03
For me sourcemaps work finally inside FF with this config:

`
output: {
	path: buildPath, //Path where the bundle should be exported
	filename: 'bundle.js', //Filename
	sourceMapFileName: 'bundle.js.map', //Filename
	publicPath: '/js/' //Where the js gets loaded from
},
devtool: 'source-map',
`

Also please read this article:
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

I published an edit for the article which is not reviewed yet, but it is about setting **devtools.sourcemap.locations.enabled** to **true** at the about:config section.

Enjoy.

**Comment by rahulthewall** [comment] 2017-03-31 22:15
@gabrielmicko Thanks a lot! I can come back to FF now :)

**Comment by spookylukey** [comment] 2017-12-06 14:07
The key point here is that 'eval-source-map' is partially broken for Firefox (you can set break points in the original sources, but stack traces from exceptions point uselessly to the compiled version, and typically to an eval at that). 'source-map' works fine, and 'inline-source-map' also works. I haven't tried all the options.

With Chrome, both work.

Please can we re-open, even if it is just a documentation fix.

**Comment by kud** [comment] 2017-12-07 12:23
The only thing which works everywhere for me is: `cheap-module-inline-source-map`

**Comment by wlach** [comment] 2018-01-30 01:02
Ran into this today. FWIW, I filed a bug in Firefox with a reproducible test case: https://bugzilla.mozilla.org/show_bug.cgi?id=1434081. This affects a bunch of Mozilla projects so I'm hoping to apply some leverage to get this fixed.

**Comment by robertjk** [comment] 2018-02-13 13:16
I have similar issue - source maps of CSS are not loaded properly in Firefox Developer Tools (they do load properly in Chrome Developer Tools). I'm presented with errors like below:

`Source map error: Error: sourceMapURL could not be parsed Resource URL: blob:null/b9a1fdd6-c0a3-4426-9df0-d50f1e8dc670 Source Map URL: data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL3JvYmVydC9wcm9ncmFtbWluZy93ZWJwYWNrLXBsYXlncm91bmQvc3JjL2NvbXBvbmVudC1hL2NvbXBvbmVudC1hLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtJQUNJLGNBQWM7SUFDZCx1QkFBdUI7SUFDdkIsa0JBQWtCO0NBQ3JCOzs7QUFHRDtJQUNJLG1CQUFtQjtJQUNuQixpQkFBaUI7SUFDakIsaUJBQWlCO0NBQ3BCOzs7QUFHRDtJQUNJLG1CQUFtQjtDQUN0QiIsImZpbGUiOiJjb21wb25lbnQtYS5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuQ29tcG9uZW50QSB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgIGZsZXgtd3JhcDogbm93cmFwO1xufVxuXG5cbi5Db21wb25lbnRBLUhlYWRlciB7XG4gICAgbWFyZ2luLWJvdHRvbTogM3B4O1xuICAgIGJhY2tncm91bmQ6ICNlZWU7XG4gICAgZm9udC1zaXplOiAxLjVlbTtcbn1cblxuXG4uQ29tcG9uZW50QS1Cb2R5IHtcbiAgICBwYWRkaW5nLWxlZnQ6IDEwcHg7XG59XG4iXSwic291cmNlUm9vdCI6IiJ9[Learn More]`

I found that the loader causing the problem is `style-loader` - if I remove it (and use `extract-text-webpack-plugin` instead) the source maps work fine. So it seems to me it's the issue with `style-loader`, not the `webpack` itself.

**Comment by evilebottnawi** [comment] 2018-02-13 13:18
@robertjk can you create issue in `style-loader` with reproducible test repo, thanks!

**Comment by robertjk** [comment] 2018-02-13 13:18
@evilebottnawi  Okay, I'll try to.

**Comment by robertjk** [comment] 2018-02-13 14:15
@evilebottnawi : https://github.com/webpack-contrib/style-loader/issues/303

**Comment by GDIBass** [comment] 2018-06-02 20:01
Developer version didn't work for me.  I'm still not seeing sass sources (works in Chrome).

**Comment by viorelsfetea** [comment] 2018-06-28 13:20
I'm having the exact same problem as @wis. the map file is there, I can access it by hand, but the extensions debugging window can't see it. Does anybody have any ideas?

**Comment by jasonLaster** [comment] 2018-06-29 02:35
CC @rpl

**Comment by chrisnicola** [comment] 2019-01-18 19:38
@rpl so there is no way to just get webpack sourcemaps working with webpack-dev-server

**Comment by aromer** [comment] 2019-02-10 17:48
I can confirm that this is still an issue in Firefox Developer Edition 66.0b6 (64-bit) and works properly in Chrome.

**Comment by chrisnicola** [comment] 2019-02-12 21:58
@aromer I've noticed that it works somewhat intermittently in FDE. It is usually working for me with `eval-source-map` but occasionally fails to work and ends up behaving like the non-DE Firefox showing compiled output instead of the original source.

Restarting often fixes the issue for me though.

**Comment by hp8wvvvgnj6asjm7** [comment] 2019-04-27 20:57
Same here for FF Developer Edition

**Comment by rmader** [comment] 2019-05-28 07:51
AFAICS this got fixed in FF 67, can anybody confirm?

**Comment by digitarald** [comment] 2019-05-30 21:07
👋🏻 Firefox DevTools PM here.

I am collecting any remaining source-map issues after we fixed a whole lot in the past releases (summarized in my [hacks article](https://hacks.mozilla.org/2019/05/faster-smarter-javascript-debugging-in-firefox/)). I was glad to see that this a few issues mentioned here seem to be addressed, but I want to make sure.

We need your help 🙏. Please post any remaining source map issues with the webpack configurations, potentially STRs or even open source projects that are affected. Feel free to reach out directly.

**Comment by belka-ew** [comment] 2019-06-11 18:57
@digitarald This example still produces a source map error: https://github.com/robertjk/webpack-firefox-source-map-error

> Source map error:: TypeError: Invalid URL: .
> Resource URL: blob:http://localhost:8080/043335f6-a69e-4f8d-bf28-9d20827bce60
> Source Map URL:
> data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9zcnYvaHR0cGQvY2FyYXVzL3dlYnBhY2stZmlyZWZveC1zb3VyY2UtbWFwLWVycm9yL3NyYy9jb21wb25lbnQtYS9zcmMvY29tcG9uZW50LWEvY29tcG9uZW50LWEuc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFJQTtFQUVJLGNBQWE7RUFDYix1QkFBc0I7RUFDdEIsa0JBQWlCLEVBWXBCO0VBVkc7SUFDSSxtQkFYSTtJQVlKLGlCQUFnQjtJQUNoQixpQkFBZ0IsRUFDbkI7RUFFRDtJQUNJLG1CQWhCTSxFQWlCVCIsImZpbGUiOiJjb21wb25lbnQtYS5zY3NzIiwic291cmNlc0NvbnRlbnQiOlsiJG1hcmdpbjogNXB4O1xuJHBhZGRpbmc6IDEwcHg7XG5cblxuLkNvbXBvbmVudEEge1xuXG4gICAgZGlzcGxheTogZmxleDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgIGZsZXgtd3JhcDogbm93cmFwO1xuXG4gICAgJi1IZWFkZXIge1xuICAgICAgICBtYXJnaW4tYm90dG9tOiAkbWFyZ2luO1xuICAgICAgICBiYWNrZ3JvdW5kOiAjZWVlO1xuICAgICAgICBmb250LXNpemU6IDEuNWVtO1xuICAgIH1cblxuICAgICYtQm9keSB7XG4gICAgICAgIHBhZGRpbmctbGVmdDogJHBhZGRpbmc7XG4gICAgfVxuXG59XG4iXSwic291cmNlUm9vdCI6IiJ9

Firefox 68.0b9 (64-Bit)

**Comment by shaddyz** [comment] 2019-10-25 19:04
I'm having issues with locating source maps in firefox only. Here's an example of the warning:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: webpack:///./node_modules/rxjs/_esm5/index.js?
Source Map URL: index.js.map
```

**Comment by darkship** [comment] 2019-12-02 12:48
I had this issue too with ` devtool: "inline-source-map"`. 

> Source map error: Error: Invalid URL: webpack://[name]/../build_config/congig.js
Resource URL: http://localhost:3000/bundles/bundle.vendor.js
Source Map URL: data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly9bbmFtZV0vLi4vYnVpbGRfY29uZmlnL2xvZ2dpbmdDb25maWcuanMiLCJ3Z....

Using the plugin `new webpack.SourceMapDevToolPlugin({ filename: false})` and `devtool: false` option somehow fixed my sourcemap issue on FF. 

I also noticed that chrome had "[name]" as sourcemap root node and with the plugin it was named "webpack"
![sourcemap_chrome](https://user-images.githubusercontent.com/3523710/69960448-c6a7dc00-1509-11ea-99c1-0622392bc62a.PNG)

I hope this helps some of you.

**Comment by loganfsmyth** [comment] 2019-12-02 23:31
@darkship Whatever is causing `[name]` to still be in the URL is the problem. Something either in your config or in a plugin you're using is creating an invalid URL. `[name]` isn't valid in a URL like that, and Chrome seems to not be validating that properly.

**Comment by sbusch** [comment] 2019-12-16 08:41
I had the same problem with `[name]` in the generated sourcemap, but in production build using devtool: 'source-map'`.

I was using `output.library` with `[name]` as value.

Specifying [`output.devtoolNamespace`](https://webpack.js.org/configuration/output/#outputdevtoolnamespace) fixed the problem. I defined an arbitrary string, debugging with FF works. Not tested with Chrome / Safari.

**Comment by tomchiverton** [comment] 2020-03-10 14:04
@digitarald - I have an internal project where devtool: 'eval-source-map' works in Chrome and not FireFox, which is a shame.
No errors in the FF console.
Happy to share more details privately.

**Comment by digitarald** [comment] 2020-03-19 20:28
@tomchiverton feel free to hit me up on [nickname] at mozilla.com. You could also create a reduced test case (on glitch or in a gist) if you have a moment.

**Comment by tomchiverton** [comment] 2020-03-24 10:54
@digitarald Cheers, sent you some details

**Comment by WilsonNet** [comment] 2020-04-29 15:29
@digitarald here, my issue.

This is the error that I get by using ` server.sockWrite(server.sockets, 'content-changed');` from chokidar to refresh webpack dev server in Firefox 76.0b8 (64 -bits).

![image](https://user-images.githubusercontent.com/25280488/80614270-a296eb00-8a14-11ea-83f3-34bfa90d371a.png)


DevServer options:

```javascript
devServer: {
    before(app, server) {
      const files = ['./**/*.php'];
      chokidar
        .watch(files, {
          alwaysStat: true,
          atomic: false,
          followSymlinks: false,
          ignoreInitial: true,
          ignorePermissionErrors: true,
          persistent: true,
          usePolling: true,
        })
        .on('all', function () {
          server.sockWrite(server.sockets, 'content-changed');
        });
    },
    index: '',
    open: true,
    host: 'localhost',
    proxy: {
      '**': {
        target: 'http://template-start.name.testserver',
        changeOrigin: true,
      },
    },
  }
```

It works on Chrome and Brave.

**Comment by adjenks** [comment] 2020-05-13 19:36
Sourcemaps work fine in chrome for me, still fail in FF.

**Comment by digitarald** [comment] 2020-05-13 22:18
@adjenks any more details on your project setup?

**Comment by theAdhocracy** [comment] 2020-05-14 12:17
I'm also still seeing these errors in Firefox, precisely the same as @belka-ew above. Works fine in Chrome. I'm using webpack via Gatsby 2.21.21, and using Yarn 1.22.1 if that matters at all. I'm not doing anything else unusual (i.e. Gatsby defaults).

**Comment by loganfsmyth** [comment] 2020-05-14 23:54
@theAdhocracy Errors like `TypeError: Invalid URL: .` _should_ be fixed on Firefox Nightly right now, if you want to try that to verify.

**Comment by theAdhocracy** [comment] 2020-05-15 14:08
@loganfsmyth Yep, just downloaded the latest version of Nightly and the errors are gone. That's excellent news 👍

**Comment by lschnoller** [comment] 2020-06-01 13:21
I have a vue app and source-map works perfectly with chrome but i still can't make it work with FF v76.0.1, v77.0b9 developer ed. nor 78.0a1 nightly build. It works fine with js files but not with vue files. In my vue.config.js i have set configureWebpack: {
    devtool: "source-map", ... } What could be happening here? PLEASE HELP! THANKS

**Comment by digitarald** [comment] 2020-06-01 17:48
> I have a vue app and source-map works perfectly with chrome but i still can't make it work with FF v76.0.1, v77.0b9 developer ed. nor 78.0a1 nightly build. It works fine with js files but not with vue files. In my vue.config.js i have set configureWebpack: {
> devtool: "source-map", ... } What could be happening here? PLEASE HELP! THANKS

I assume you don't see any source map errors in Console? Just as second validation step, could you run your code through https://sourcemaps.io/ ? If it all shows up green, you could send the `.map` and `.js` files to me.

**Comment by lschnoller** [comment] 2020-06-03 13:46
> I assume you don't see any source map errors in Console? Just as second validation step, could you run your code through https://sourcemaps.io/ ? If it all shows up green, you could send the `.map` and `.js` files to me.
Hi @digitarald! i don't see any source map errors in Console. I have run the code through https://sourcemaps.io/ and got lots of errors that i can't figure out. Bottomline is the sourcemap works fine with chrome but not in FF, any other ideas?

**Comment by azukaar** [comment] 2020-06-03 15:46
Also broken for me in FF with any devtool value.
Sourcemaps appear but error points to bundled code

**Comment by lschnoller** [comment] 2020-06-03 19:06
> @lschnoller thanks for sharing your project via email. So far is looks like this issue is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1642397 , which causes multiple `vue` files with similar names to show up as only one entry. Workaorund until we fix it (79, current nightly) is opening the files via `Cmd-P` quick open – can you confirm that this works?

Hi @digitarald! Correct. 'Cmd-P' works. It seems the wrong files are being hidden. In the file browser i get listed for example the file index.vue?xyz but not the source-mapped .vue file. It would be awesome to gray out all the .vue?xyz extra extensions and display the .vue files normally.

**Comment by zuzusik** [comment] 2020-06-05 21:28
I am seeing cases like this in both Firefox nightly <sub>(79.0a1 (2020-06-05) (64-bit))</sub> and stable <sub>(77.0.1 (64-bit))</sub>:

<img width="382" alt="Screen Shot 2020-06-05 at 5 19 30 PM" src="https://user-images.githubusercontent.com/4233080/83923799-f81b9180-a750-11ea-90b9-c7701e23f85a.png">

I am building with Angular CLI, which uses Webpack under the hood. I am on macOS.

As you see - the positions are invalid - I can't set breakpoint on line 77. The workaround is to set it on line 78, but this is just a guess game - I need to guess every time.

**Comment by loganfsmyth** [comment] 2020-06-05 21:37
@zuzusik If you can make a reproduction example, filing a new FF debugger bug in https://bugzilla.mozilla.org would be ideal.

**Comment by lschnoller** [comment] 2020-06-12 13:41
@digitarald hi! is there any update on this? (was there a release of some kind where we could look at it?). Thanks

**Comment by adjenks** [comment] 2020-06-12 19:05
Maybe they're just waiting for Firefox to fix it. Would be nice if vue/webpack changed their method to make it backwards compatible though.

**Comment by digitarald** [comment] 2020-07-01 21:07
📯 The [fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1642397) for missing `.vue` files landed in today's Nightly and will ride the trains with Firefox 80.

**Comment by lschnoller** [comment] 2020-07-02 18:15
@digitarald Just checked out the nightly build and it's looking good! I could find the vue files and even place a breakpoint on an await (async) call, which cannot be done in chrome. One great thing that would be awesome that still doesn't work is to be able to step over an await (async) call and get to the next operation in your code instead of getting into the middle of an internal library js file.

**Comment by zuzusik** [comment] 2020-07-02 19:04
@loganfsmyth FYI: I have figured out [mentioned issues](https://github.com/webpack/webpack/issues/1194#issuecomment-639829859) - it was because I didn't have sourcemaps processing enabled in [ng-annotate-loader](https://www.npmjs.com/package/ng-annotate-loader). This loader changes output code, so for source maps to match, it also should be enabled to process them, and that's not a default setting in underlying `ng-annotate` tool.

I was thinking this is particularly the issue of `Firefox`, cause _somehow_ `Google Chrome` is able to recover from that situation (well, we all know how good they are in supporting different weird cases).

Sorry for late heads-up and thanks for all your work on making `Firefox` better for devs! Maybe one day I will finally switch back to it (moved to Chrome since Firebug has gone, made several attempts to come back, latest one with Firefox 77, but still it's not there for me)

**Comment by evilebottnawi** [comment] 2020-08-31 18:07
Is anyone still having problems? Firefox 71 fixed many issue with source maps, need feedback

**Comment by belka-ew** [comment] 2020-08-31 18:10
> Is anyone still having problems? Firefox 71 fixed many issue with source maps, need feedback

Works fine for me on the Developer Edition.

**Comment by jasonLaster** [comment] 2020-08-31 19:34
@evilebottnawi @belka-ew I'm so glad that sourcemaps are working better.

Big props to @loganfsmyth!

**Comment by evilebottnawi** [comment] 2020-09-01 10:23
I'll keep the problem open for a while (2 weeks) for feedback, then I close, but if you find something not working, please let us know

**Comment by rtouze** [comment] 2020-11-13 07:37
I had the issue until now. I removed the line `devtool: 'inline-source-map'` from webpack configuration file and it works (it uses _eval_ by default, does'nt it?).

**Comment by alexander-akait** [comment] 2021-02-10 12:58
Closing due to inactivity. Please test with latest `v5` and feel free to reopen if faced with the problem again (will be great if you provide reproducible test repo, this allow to fix a problem ASAP). Thanks!

**Closed by alexander-akait** 2021-02-10 12:58 UTC
Labels: bug
