### ISSUE TITLE
Missing assets in entrypoint.auxiliaryAssets part of stats object in production mode

### ISSUE THREAD

**Issue by geldmacher** [webpack/webpack#12099] opened 2020-12-02 13:59 UTC
# Bug report

**What is the current behavior?**
In production mode font files from CSS files, which are imported in an entrypoint JS file, are not listed in `stats.entrypoints['entrypointIdentifier'].auxiliaryAssets`.

Example CSS file:
```
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  font-display: swap;
  src: local('Roboto Light'), local('Roboto-Light'),
  url('../Assets/Fonts/Roboto/roboto-v18-latin-300.woff2') format('woff2'),
  url('../Assets/Fonts/Roboto/roboto-v18-latin-300.woff') format('woff'),
  url('../Assets/Fonts/Roboto/roboto-v18-latin-300.ttf') format('truetype')
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Webpack in production mode or with `optimization.sideEffects = true`.

**What is the expected behavior?**
The font files should be part of auxiliaryAssets regardless of production/development mode or sideEffects setting. 

Example part of the stats object:
```
stats.entrypoints['entrypointIdentifier'].auxiliaryAssets: [
    {
      name: 'Assets/roboto-v18-latin-300.815babff.woff2'
    },
    {
      name: 'Assets/roboto-v18-latin-300.a0de923c.ttf'    
    },
    {
      name: 'Assets/roboto-v18-latin-300.d4c409df.woff'
    },
]
```

**Other relevant information:**
webpack version: 5.9.0
Node.js version: 15.2.1
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment] 2020-12-02 14:05
Please create fully reproducible test repo

**Comment by geldmacher** [comment] 2020-12-02 14:58
Sure: https://github.com/geldmacher/webpack_issue_12099_test_repo
See console output in build process for missing auxiliaryAssets.

**Comment by sokra** [comment] 2020-12-02 21:27
Yeah, this can be fixed in mini-css-extract-plugin.

The problem is that currently assets are attached to the JS module, which is empty and therefore removed from the chunks and with it the assets. Which is probably correct as assets in a unused module are probably not needed. It probably shouldn't even emit these assets, but that's another story (and we can't change this without a breaking change).

So in the end the assets need to be attached to the CssModule instead of the JS module in mini-css-extract-plugin.

@alexander-akait Here are the changes I did to fix it. Assets are passed through the CssDependency to the CssModule and attached there.

``` diff
 // in loader.js
   childCompiler.runAsChild((err, entries, compilation) => {
+    const assets = Object.create(null);
+    const assetsInfo = new Map();
+
     for (const asset of compilation.getAssets()) {
-      // buildInfo stuff
+      assets[asset.name] = asset.source;
+      assetsInfo.set(asset.name, asset.info);
     }
```

``` diff
 // in loader.js
+      let lastDep;

       for (const dependency of dependencies) {
         if (!dependency.identifier) {
           // eslint-disable-next-line no-continue
           continue;
         }

         const count = identifierCountMap.get(dependency.identifier) || 0;

-        this._module.addDependency(new CssDependency(dependency, dependency.context, count));
+        this._module.addDependency(lastDep = new CssDependency(dependency, dependency.context, count));

         identifierCountMap.set(dependency.identifier, count + 1);
       }

+      lastDep.assets = assets;
+      lastDep.assetsInfo = assetsInfo;
```

``` diff
 class CssDependency extends Dependency {
   constructor(...) {
     super();
     ...
+    this.assets = undefined;
+    this.assetsInfo = undefined;
   }

+ // changes in serialize and deserialize
```

``` diff
 class CssModule extends Module {
   constructor({
     context,
     identifier,
     identifierIndex,
     content,
     media,
     sourceMap,
+    assets,
+    assetsInfo
   }) {
     super(_utils.MODULE_TYPE, context);
     this.id = '';
     this._context = context;
     this._identifier = identifier;
     this._identifierIndex = identifierIndex;
     this.content = content;
     this.media = media;
     this.sourceMap = sourceMap;
-    this.buildInfo = {};
+    this.buildInfo = {
+      assets,
+      assetsInfo
+    };
     this.buildMeta = {};
  } // no source() so webpack 4 doesn't do add stuff to the bundle

+ // changes in serialize and deserialize
```

**Comment by geldmacher** [comment] 2020-12-03 09:26
Sounds logic to me. I applied your fix to my local mini-css-extract-plugin. Seems to work. Hope this gets merged. Thanks a lot! =D

**Comment by alexander-akait** [comment] 2020-12-04 12:05
Fixed https://github.com/webpack-contrib/mini-css-extract-plugin/pull/662, release will be today

**Closed by alexander-akait** 2020-12-04 12:05 UTC
Labels: webpack-5
