### ISSUE TITLE
file does not match the corresponding path on disk - File does not exist

### ISSUE THREAD

**Issue by domoritz** [webpack/webpack#5073] opened 2017-06-16 04:47 UTC
I'm reporting a bug. 

**What is the current behavior?**

When I change files (recompiled in a linked package), webpack chokes with

```
Error in ./src/index.js
Module not found: [CaseSensitivePathsPlugin] `some file.js` does not match the corresponding path on disk - File does not exist.

 @ ./src/index.js 29:16-36
```

**What is the expected behavior?**

I'd expect webpack to just happily restart. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm using webpack 1.13.2 and server 1.16.1. 

I filed this issue with the app I'm working on at https://github.com/vega/vega-editor/issues/129.

**Comment by RamYadlapalli** [comment] 2017-06-16 18:31
It is may not be a webpack issue, did you try restarting webpack-dev-server? if yes is it woking after that?

**Comment by domoritz** [comment] 2017-06-16 19:19
Yes, it works after restarting but webpack chokes again once files change
again.

**Comment by domoritz** [comment] 2017-06-16 23:09
So it could be an issue with webpack-dev-server.

**Comment by kahlilashanti** [comment] 2017-07-21 00:07
is there a fix for this issue that domoritz is referring to?

**Comment by sokra** [comment] 2017-07-21 20:47
File an issue for the CaseSensitivePathsPlugin.

**Comment by basaa88** [comment] 2018-01-18 07:52
npm install --save-dev case-sensitive-paths-webpack-plugin

It should do the trick

**Comment by tomtom92** [comment] 2018-02-01 23:07
I am having the same issue with React. I created an app using `create-react-app`, and am not using webpack to compile. I have tried renaming the React node package, deleting it, reinstalling it, and the same error continues. Therefore, maybe it isn't a webpack issue? Using node v8.9.1, React v16.2.0

**Comment by evilebottnawi** [comment] 2018-02-28 16:18
Problem related to `CaseSensitivePathsPlugin`. Close in favor https://github.com/Urthen/case-sensitive-paths-webpack-plugin/issues/22

**Closed by evilebottnawi** 2018-02-28 16:18 UTC

**Comment by Farbod29** [comment] 2018-06-24 18:03
check the pass of remote and your local system be same if you have capital S in Src path change it to small.
Error in ./src/index.js

**Comment by NikulGoyani369** [comment] 2018-07-06 16:07
./src/Pages/PlayQuiz.js
Module not found: `C:\Users\abc\project\client\src\Components\Comments.js` does not match the corresponding path on disk `components`.

@Farbod29  I got the same error on my project when I run.

anyone help or suggest something what shall I do?

**Comment by llezhava** [comment] 2018-09-28 12:06
> File an issue for the CaseSensitivePathsPlugin.

I just renamed the folder and it worked. Thanks :)

**Comment by danfoust** [comment] 2018-12-22 16:55
The issue for me was I accidentally capitalized the package name after from in the import statement.

**Comment by jchain** [comment] 2019-01-22 22:52
If you use cygwin, change to your project folder without using `~`. It works for me.

**Comment by ajhool** [comment] 2019-03-27 19:14
If you're using `create-react-app` and Visual Studio Code and you're seeing this bug after changing the casing on a filename, this timeless solution worked for me...

1. Restart your dev server (eg. `ctrl + C` ... `yarn start`)

2. Restart Visual Studio Code

**Comment by jcrommar** [comment] 2019-04-02 17:37
Tried all the solutions on this thread and nothing works. Only thing I can think of is npm vs yarn as someone already mentioned. : (

**Comment by Oyatullo** [comment] 2019-05-01 21:32
./src/Card.js
Cannot find file: 'index.js' does not match the corresponding name on disk: '.\node_modules\React\react'.
can someone help with this

**Comment by irenapopova** [comment] 2019-05-30 07:49
Hallo,
any hints how I can solve this issue with localhost? I cannot open my react app
thanks

Failed to compile
./src/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/React/react'.

**Comment by dbslone** [comment] 2019-06-25 00:05
@irenapopova in your webpack config file are you using `externals`? I had the same issue and noticed I had:

```
externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
```

because my target library is `commonjs2` I needed to change it to the following:
```
externals: {
    react: 'react',
    'react-dom': 'react-dom',
  },
```

if your using multiple targets you should refer to [Webpack Externals](https://webpack.js.org/configuration/externals/#object)

**Comment by EmmaREKS** [comment] 2019-07-04 15:53
some one should help me with this
./src/App.js
Cannot find file: 'search.js' does not match the corresponding name on disk: '.\src\Components\components'.

**Comment by vasireddybharath** [comment] 2019-08-23 16:29
I had the same issue. It was because I used small case in folder name in my import statement. When in fact it should have been upper case.
Replaced "import Layout from './component/MainLayout'; to
                 "import Layout from './Component/MainLayout'; worked for me.

**Comment by EmmaREKS** [comment] 2019-08-27 02:48
Thanks alot

**Comment by Blac-Panda** [comment] 2019-09-10 16:47
> I had the same issue. It was because I used small case in folder name in my import statement. When in fact it should have been upper case.
> Replaced "import Layout from './component/MainLayout'; to
> "import Layout from './Component/MainLayout'; worked for me.

This worked for me. Thanks

**Comment by Guste** [comment] 2019-11-05 06:46
> npm install --save-dev case-sensitive-paths-webpack-plugin
> 
> It should do the trick

This worked for me. Thanks.

**Comment by raydot** [comment] 2019-12-30 23:29
https://stackoverflow.com/questions/55149843/error-cannot-find-file-index-js-does-not-match-the-corresponding-name-on-dis fixed the problem with my build.  Basically it's:
`import React from "react"` and not
`import React from "React"`

**Comment by medhatdawoud** [comment] 2020-02-18 21:46
> Problem related to `CaseSensitivePathsPlugin`. Close in favor [Urthen/case-sensitive-paths-webpack-plugin#22](https://github.com/Urthen/case-sensitive-paths-webpack-plugin/issues/22)

This worked for me as well, I pulled a project which was not mine and the folder was in a different case 'capitalized' and the code was using 'smallcase', renaming the folder fixed it to me, thanks

**Comment by kyle-west** [comment] 2020-04-07 19:15
I was having this issue too once I unlinked and then re-relinked all the npm packages involved I stopped getting the error.

**Comment by kameshk61** [comment] 2020-04-15 07:12
So the issue is because you are not importing correctly. Like in my case it was :

`import {Dropdown} from '**react-Bootstrap**'`

I corrected it to 

`import {Dropdown} from '**react-bootstrap**'`

Since import statement are case sensitive

**Comment by Berci-Ionut** [comment] 2020-04-29 07:05
For me the problem was that I was importing by mistake something like
import { MyComponent } from "../components/MyComponent/MyComponent";
but in the component I was just exporting the class as default ( export default MyComponent )
So I had to switch to
import MyComponent from "../components/MyComponent/MyComponent";
Is pretty dumb, I know, but maybe this can help other too

**Comment by subhash00** [comment] 2020-06-09 11:01
I had similar problem but changing the file name work for me.

**Comment by oseisaac** [comment] 2020-10-08 07:49
What worked for me as to Restart `npm start` and there move the file missing out of the folder and back, then it compiled fine.

**Comment by shanytc** [comment] 2020-10-18 16:15
**myComponent.ts:**
const MyComponent = {...}

If importing from "index.ts", make sure u export with lower case.

**index.ts:**
export * from "/myComponent";

**Comment by Charles-Chiakwa** [comment] 2021-03-04 21:59
This mostly an issue with CaseSensitivePathsPlugin. Be sure your file name is capital case instead of small case. 
if you `import MyComponent from "../components/MyComponent"` be sure your file name is `MyComponent` in not `myComponent`

**Comment by devlopernabin** [comment] 2021-03-30 06:26
all your review are worthless to me 😪

**Comment by frunox** [comment] 2021-04-17 04:22
I just transferred my code to a new laptop and now I'm getting this error.  The code ran fine on the other laptop.  If I change the case of one file name, I just get an error with another file.

I now get the error with files in the node_modules folder.

**Comment by code-driving** [comment] 2021-05-10 07:11
This solved the same issue:
npm install --save-dev case-sensitive-paths-webpack-plugin

**Comment by FlorianCassayre** [comment] 2021-11-10 20:44
On Windows this can be due to a name conflict, namely two files in the same directory having the same name but in a different case.

**Comment by Adhithyashine** [comment] 2022-07-24 05:51
> This mostly an issue with CaseSensitivePathsPlugin. Be sure your file name is capital case instead of small case. if you `import MyComponent from "../components/MyComponent"` be sure your file name is `MyComponent` in not `myComponent` or vice versa

Really helpful, Thank you...

**Comment by rovertnet** [comment] 2022-12-08 13:17
Quand j'essaye d'executer ça m'afficher ""Module not found: Error: Cannot find file: 'Cart.css' does not match the corresponding name on disk: '.\src\styles\Styles'."

**Comment by sarianpour** [comment] 2022-12-31 21:56
i had the same issue because instead of Login.css i was calling login.cs

**Comment by sangar3** [comment] 2023-02-23 03:30
If anybody is still having this error 2023 like me: 


the folder was corrupt causing an error, so delete it and make a new one to fix the issue.

**Comment by Gorilla218** [comment] 2025-02-04 20:09
I finally found it! https://reactdev.space/questions/creating-a-react-component-that-leverages-the-power-of-vega-data
