### ISSUE TITLE
Migrating source code on typescript/flow

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#9196] opened 2019-05-28 09:53 UTC
## Feature request

Hi! I'm new to webpack community, but I want to improve my knowledge of how it works "under the hood". I faced with problem when I don't understand where which type is using for and it's look like for new contributors it is very difficult as well + strictly typed code has less likelihood to fall into deoptimization. So my question is - Do you have any ideas/roadmap to migrating source code on TypeScript/<del>Flow</del>? May be create some JSDocs? Looks like migrating `tapable`, `enhanced-resolve` don't look as something difficult.

**What is the expected behavior?**

More types!

**What is motivation or use case for adding/changing the behavior?**

1. Type systems improve your code by making it easier to read.
2. Strictly typed code has less likelihood to fall into deoptimization

**How should this be implemented in your opinion?**

 Looks like migrating `tapable`, `enhanced-resolve` don't look as something difficult. In webpack core repo there are types already in some files. For instance, part of compiler definition has JSDoc, but still it is a large task for webpack core.

**Are you willing to work on this yourself?**

Yes. Bigger community => Faster releases 😁

**Comment by sokra** [comment] 2019-05-28 19:08
enhanced-resolve could need some typing.

If you want to take care about that, do it similar to webpack:

* Source code is in JS
* Types are provided via JSDOC
* Typescript is used as linting step

**Comment by glen-84** [comment] 2019-06-07 09:12
Duplicate of #3277 (?)

**Comment by evilebottnawi** [comment] 2019-06-07 10:05
Yes, close in favor https://github.com/webpack/webpack/issues/3277

/cc @vankop feel free to any discussion in https://github.com/webpack/webpack/issues/3277

**Closed by evilebottnawi** 2019-06-07 10:05 UTC
