### ISSUE TITLE
When watching files - new errors and warnings don't show when output hash remains the same.

### ISSUE THREAD

**Issue by thetrevdev** [webpack/webpack#2538] opened 2016-05-23 23:56 UTC
https://github.com/webpack/webpack/blob/18929db92ab3176735447f0059982ed6200317b7/bin/webpack.js#L313
Output is prevented here based on the hash being identical.

Using preLoader eslint and loader babel.
Babel is formatting the final output of the file.  This means I can change the formatting of a file that effects the eslint preloader but doesn't actually alter the final output.  I am not seeing my eslint errors even though new errors are present.

**Comment by sth** [comment] 2017-01-22 03:08
A workaround is to make sure that babel always creates different output even on trivial changes. If webpack sees different output from babel it will display the new messages.

I have a small plugin for babel that does this by adding a hash of the input to the output: [babel-plugin-add-filehash][1]. I use it and it works well, the errors get updated even on white space changes.

This only helps if you use babel, not with other loaders, and it will become obsolete once the issue is fixed in webpack itself.

[1]: https://github.com/sth/babel-plugin-add-filehash

**Comment by sokra** [comment] 2017-07-20 14:29
An option to fix this issue is to make warnings and error to contribute to the build hash (but not to the chunk hash).

**Closed** 2017-08-11 15:46 UTC
Labels: bug
