### ISSUE TITLE
Compiler.js    TypeError: Function has non-object prototype 'null' in instanceof check

### ISSUE THREAD

**Issue by jackIsZlg** [webpack/webpack#11767] opened 2020-10-21 03:11 UTC
when I 
 const webpack = require('webpack');
 const compiler = webpack(CONFIG);
 console.log(compiler);

**it can not console.log; and it has a error: TypeError: Function has non-object prototype 'null' in instanceof check**

Then I debug in **wepack/lib/Compiler.js**: 
```javascript
// wepack/lib/Compiler.js
class Compiler {
	/**
	 * @param {string} context the compilation path
	 */
	constructor(context) {
		this.hooks = Object.freeze({
			/** @type {SyncHook<[]>} */
			initialize: new SyncHook([]),
                        // shouldEmit: new SyncBailHook(["compilation"]),
			// done: new AsyncSeriesHook(["stats"]),
                        .......
		});
		console.log(this)
       }
       .........
 }
```
**it tell me that TypeError: Function has non-object prototype 'null' in instanceof check;**

so next, I find path: **webpack/node_modules/tapable/lib/SyncHook.js**,   Comment out this line of code
```
........
function SyncHook(args = [], name = undefined) {
	const hook = new Hook(args, name);
	hook.constructor = SyncHook;
	hook.tapAsync = TAP_ASYNC;
	hook.tapPromise = TAP_PROMISE;
	hook.compile = COMPILE;
	return hook;
}

// SyncHook.prototype = null;

module.exports = SyncHook;

```

it worked， Results printing：
```
Compiler {
  hooks: {
    initialize: Hook {
      _args: [],
      name: undefined,
      taps: [],
      interceptors: [],
      _call: [Function: CALL_DELEGATE],
      call: [Function: CALL_DELEGATE],
      _callAsync: [Function: CALL_ASYNC_DELEGATE],
      callAsync: [Function: CALL_ASYNC_DELEGATE],
      _promise: [Function: PROMISE_DELEGATE],
      promise: [Function: PROMISE_DELEGATE],
      _x: undefined,
      compile: [Function: COMPILE],
      tap: [Function: tap],
      tapAsync: [Function: TAP_ASYNC],
      tapPromise: [Function: TAP_PROMISE],
      constructor: [Function: SyncHook]
    }
  }
}
```
I think it is bug, the same to:  
   SyncHoo.js
   SyncBailHook.js
   AsyncParallelHook.js
   AsyncSeriesHook.js
   AsyncSeriesBailHook.js

webpack version:  5.1.3
Node.js version: v14.14.0
Operating System: mac
Additional tools:

**Comment by jackIsZlg** [comment] 2020-10-21 03:13
only in webpack-5

**Comment by sokra** [comment] 2020-10-21 06:46
Looks like a Node.js bug. Logging an object should never crash. The same works in the browser:

``` js
function X () {}
X.prototype = null;
x = {};
x.constructor = X;
console.log(x);
```

Node.js:

```
Uncaught TypeError: Function has non-object prototype 'null' in instanceof check
    at Function.[Symbol.hasInstance] (<anonymous>)
    at getConstructorName (internal/util/inspect.js:535:13)
    at formatRaw (internal/util/inspect.js:803:23)
    at formatValue (internal/util/inspect.js:793:10)
    at inspect (internal/util/inspect.js:326:10)
    at formatWithOptionsInternal (internal/util/inspect.js:1994:40)
    at formatWithOptions (internal/util/inspect.js:1878:10)
    at Object.value (internal/console/constructor.js:306:14)
    at Object.log (internal/console/constructor.js:341:61)
```

Browser:

```
{constructor: ƒ}
```

**Comment by sokra** [comment] 2020-10-21 06:51
There are more cases to this problem in Node.js:

```
console.log({ constructor: () => {} })

const X = function() {}
X.prototype = null;
console.log({ constructor: X })
```

**Comment by jackIsZlg** [comment] 2020-10-21 06:54
> There are more cases to this problem in Node.js:
> 
> ```
> console.log({ constructor: () => {} })
> 
> const X = function() {}
> X.prototype = null;
> console.log({ constructor: X })
> ```

How should that be solved?  It's better to be compatible

**Comment by sokra** [comment] 2020-10-21 06:55
Report it to Node.js, that's probably a simple fix.

**Comment by jackIsZlg** [comment] 2020-10-21 07:07
Well, I've already mentioned that to node.js, hope it can be solved

**Comment by evilebottnawi** [comment] 2020-10-21 10:47
@jackIsZlg Please put link to the issue

**Comment by baylesa-dev** [comment] 2020-10-22 14:11
The related issue in node.js: https://github.com/nodejs/node/issues/35730

**Comment by chuyik** [comment] 2020-11-24 11:33
Come across the same issue, is there any workaround?

**Comment by evilebottnawi** [comment] 2020-11-24 11:41
@chuyik What is workaround can be for Node.js bug?

**Comment by chuyik** [comment] 2020-11-24 11:47
This bug raises when called:
```js
const webpack = require('webpack')
webpack(config, (err, stats) => {})
```

But if I use `webpack-cli` to build instead of calling the API above, it works.
I didn't look into `webpack-cli` source code, but I think the CLI may call the same function internally.

**Comment by evilebottnawi** [comment] 2020-11-24 11:52
@chuyik What is the Node.js verison, I can't reproduce

**Comment by chuyik** [comment] 2020-11-24 11:59
@evilebottnawi 
Try with these code in node 14.12, webpack 5.6.0:
```js
const webpack = require('webpack')
webpack({}, (err, stats) => {
  console.log('err..', err)
  console.log('stats..', stats)
})
```

**Comment by evilebottnawi** [comment] 2020-11-24 12:46
@chuyik yep, works fine on node `12.19.0`, we should wait fix, don't know why Node.js team doesn't mark it high priority, because other projects can be affected this

**Comment by evilebottnawi** [comment] 2020-11-24 12:50
@chuyik But it happens only `stats` contains errors

**Comment by chuyik** [comment] 2020-11-25 00:37
@evilebottnawi It also happens when `stats` only contains warnings.
```js
webpack(config).run((err, stats) => {
  stats?.hasErrors() // false
  stats?.hasWarnings() // true
})
```

**Comment by LeiSe7en** [comment] 2020-12-03 02:58
I have the same issue here. When i just create a simple webpack plugin and do `console.log(compiler)` in `apply`method .
`"webpack": "^5.9.0"`
` "webpack-cli": "^4.2.0"`
`Node version: v14.15.1`

And the error is : 
```
[webpack-cli] TypeError: Function has non-object prototype 'null' in instanceof check
```

**Comment by TokugawaTakesi** [comment] 2020-12-10 05:03
Simple reproduction without applied code:

```javascript
{ 
  plugins: [
    new class {
       apply(compiler): void {

        console.log("ok!!");
        // console.log(compiler);

         compiler.hooks.run.tapAsync("~~~", (compilation, callback) => {
            console.log("-----");
            callback();
          });
        }
    }()
  ]
}
```

Uncomment the `console.log(compiler)` - and Webpack will brake.
How simple to break the building :)

**Comment by shangxinbo** [comment] 2020-12-11 14:01
node 14.13.0
webpack 5.10.0

[webpack-cli] TypeError: Function has non-object prototype 'null' in instanceof check
    at Function.[Symbol.hasInstance] (<anonymous>)
    at getConstructorName (internal/util/inspect.js:535:13)
    at formatRaw (internal/util/inspect.js:803:23)
    at formatValue (internal/util/inspect.js:793:10)
    at formatProperty (internal/util/inspect.js:1679:11)
    at formatRaw (internal/util/inspect.js:1007:9)
    at formatValue (internal/util/inspect.js:793:10)
    at formatProperty (internal/util/inspect.js:1679:11)
    at formatRaw (internal/util/inspect.js:1007:9)
    at formatValue (internal/util/inspect.js:793:10)

**Comment by jasonwilliams** [comment] 2020-12-16 19:16
Was closed in Node here:
https://github.com/nodejs/node/issues/35730

Does anyone have a workaround until NodeJS updates?

**Comment by alexander-akait** [comment] 2020-12-17 12:40
> Does anyone have a workaround until NodeJS updates?

No

> Also, why does this only happen in Webpack 5?

Because we rely on JS behaviour and here Node.js has bug

**Comment by davebenvenuti** [comment] 2021-01-24 07:07
> Does anyone have a workaround until NodeJS updates?
 
It seems you can `console.log(stats.toJson())`

https://webpack.js.org/api/node/#error-handling

**Comment by alexander-akait** [comment] 2021-02-05 14:31
Fixed in `10`/`12`/`15`, for `14` here commit https://github.com/nodejs/node/commit/f206505e9d59b072de552310264ab4c3e8a361c5, nothing to fix on our side

**Closed by alexander-akait** 2021-02-05 14:31 UTC

**Comment by TokugawaTakesi** [comment] 2021-03-24 09:35
@alexander-akait 

Thank you for the notification.
I am sorry, but what means `10/12/15`? How we can to know in which version of NodeJS this bug fixed? (Current LTS is `14.16.0`)

**Comment by alexander-akait** [comment] 2021-03-24 10:52
Should be fixed in latest versions

**Comment by wind8866** [comment] 2021-04-07 09:43
是 node 的问题，我升级到最新的 14.16.1，就不会报错了。
It's a nodejs problem, I upgraded to 14.16.1 version, no error will be reported.
