### ISSUE TITLE
Native support for webpack.config.coffee

### ISSUE THREAD

**Issue by kmalakoff** [webpack/webpack#475] opened 2014-09-15 20:23 UTC
Can webpack natively read webpack.config.coffee?

**Comment by iboozyvoozy** [comment] 2015-02-05 18:51
No news for coffee support?

**Comment by wmertens** [comment] 2015-03-11 13:19
Since webpack is just `require`-ing the config file, this needs two things:
- The `coffee-script` module required before loading the config file
- `require`-ing the default config as `webpack.config`, so that it could be a `.js` or a `.coffee` (or even a `.json` I think)

Opened PR #872

**Comment by akre54** [comment] 2015-03-11 13:31
For anyone interested, [this is how liftoff requires config files](https://github.com/tkellen/js-liftoff/blob/master/index.js#L112-L129). I'm not familiar enough with webpack's internals but if I got pointed in the right direction I could try and whip something up.

**Comment by wmertens** [comment] 2015-03-11 15:30
I just updated my PR so that it automagically works when the config file
ends in .coffee as well.

**Comment by akre54** [comment] 2015-03-11 15:35
The problem is your PR requires passing a `--coffee` flag instead of detecting the file and its extension automatically. Your code also would have to be repeated for every compile-to-js variant (TypeScript, LiveScript, etc). Is there any reason *not* to use node-interpret for this?

**Comment by wmertens** [comment] 2015-03-11 16:26
No go right ahead and create a PR :-) No reason why mine can't be merged
and removed later - if you specify webpack.config.coffee as the
configuration file it just works either way.

**Comment by monder** [comment] 2015-04-06 12:35
Added PR with [node-interpret](https://github.com/tkellen/node-interpret)

**Comment by wmertens** [comment] 2015-04-07 09:09
so now this can be closed right?

**Closed** 2015-04-07 09:21 UTC

**Comment by nickperkinslondon** [comment] 2016-08-22 15:15
For anyone doing this...

    // webpack.config.js
    require('coffee-script/register');
    module.exports = require("./webpack.config.coffee");

I would recommend using a different name for your coffee file just so it never accidentally gets compiled and over-writes your js file.
