### ISSUE TITLE
Getting started produces an error

### ISSUE THREAD

**Issue by thany** [webpack/webpack#4557] opened 2017-03-24 09:47 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When following the [Getting Started](https://webpack.js.org/guides/get-started/) it produces an error when calling `webpack` at the end:
```
d:\test\webpack-demo>.\node_modules\.bin\webpack app/index.js dist/bundle.js
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "d:\\test\\webpack-demo" is not an absolute path!
 - configuration.output.path: The provided value "d:\\test\\webpack-demo\\dist" is not an absolute path!
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow the Getting Started guide to the letter, and be on Windows (not sure if being on Windows is absolutely required to repro though)

**What is the expected behavior?**
I would expect the results listed in the Getting Started guide. It suggests that it should "just work" so I come to expect that as well.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10
Node 7.7.4
NPM 4.4.1
Webpack 2.3.1

When I `npm i --save-dev webpack@beta`, I get version 2.2.0, which is **older**, but that one does work. So it looks like a regression in 2.3.1. I'm completely virgin to webpack, so I'm not sure what 2.3.1 is, or why a stable version is higher than beta, or if this behaviour is normal at all. So please be gentle ;)

**Comment by michael-ciniawsky** [comment] 2017-03-24 09:58
@thany #4530 You need to start your shell with using **uppercase**  drive letters `d:\ => D:\` or stay with `v2.2.0`  for the moment 😛. Please don't install `@beta` versions, the reason there is no _newer_ version is simply because the last _in_ beta version for webpack v2 was `v2.2.0` and their is no new beta atm. `npm i package` (@latest) && `npm i package@beta` (beta) are unrelated **tags**

**Comment by thany** [comment] 2017-03-24 14:36
The issue remains though. If 2.2.0 is te latest stable as well as latest beta, then `npm i webpack` should install that version. This doesn't explain (or solve) the installation of a broken 2.3.1.

And if I shouldn't install beta versions, what should I then do to get the latest **stable** webpack? For *all* node modules I've come across so far, I've been able to just `npm i package` and be done. That never installs some unstable beta/alpha version, but always the latest stable.

As for the uppercase solution: Windows is case-insensetive, so it shouldn't matter 😉

**Comment by michael-ciniawsky** [comment] 2017-03-24 14:58
@thany Yep agreed this is inconvenient. Either the getting started guide needs an update or #4533 gets merged 😛, but it seems there where known issues with lowercase drive letters before and that's the reason why it was **breaking** changed. In any case nothing a beginner should have to  bother with. `npm i webpack@2.2.1` should install the latest version compatible with the getting started guide in your case (windows) 🙃

**Comment by bebraw** [comment] 2017-03-25 05:47
Can you try against 2.3.2?

**Comment by vachi** [comment] 2017-03-28 10:13
@bebraw getting same thing on 2.3.2

**Comment by StasGoshtein** [comment] 2017-03-30 18:06
+1 Getting this one on webpack 2.3.2

**Comment by kelleysy** [comment] 2017-04-01 20:23
I am getting same on 2.3.2

**Comment by smithkl42** [comment] 2017-04-19 21:32
Getting the same on 2.4.1.

**Comment by maogongzi** [comment] 2018-01-12 02:09
still getting this error on 3.10.0...

and seems it happens not all the time, in our team several Windows machines work fine while some others don't.

**Comment by evilebottnawi** [comment] 2018-05-06 17:30
Don't reproducible for `webpack@3` and `webpack@4`. 
@madeinfree can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment] 2018-05-07 09:39
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2018-05-07 09:39 UTC
Labels: S4: Broken, X0: need more information, bug, webpack-2
