### ISSUE TITLE
10x slowdown in sealing between `5.96.1` and `5.97.0`

### ISSUE THREAD

**Issue by benjaminblack** [webpack/webpack#19035] opened 2024-12-04 00:38 UTC
# Bug report

Something odd happened between `5.96.1` and `5.97.0`: our build time increased by an order of magnitude. Specifically, the progress grinds to a halt at 70% (sealing), takes about five minutes, and then proceeds quickly to 100%.

**What is the current behavior?**

In `5.97.0`:
```
webpack 5.97.0 compiled successfully in 305755 ms
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Please forgive my lack of knowledge, but I don't even know where to start to try to figure out what could be causing this. Webpack is a black box to me. At the very least, here is a semver dump of relevant build-time dependencies:

```
        "@babel/cli": "^7.25.9",
        "@babel/core": "^7.26.0",
        "@babel/preset-env": "^7.26.0",
        "@babel/preset-react": "^7.25.9",
        "@babel/preset-typescript": "^7.26.0",
        "@svgr/webpack": "^8.1.0",
        "babel-loader": "^9.2.1",
        "browserslist": "^4.24.2",
        "css-loader": "^6.11.0",
        "dotenv-webpack": "^8.1.0",
        "loader-utils": "^3.3.1",
        "mini-css-extract-plugin": "^2.9.2",
        "postcss": "^8.4.49",
        "postcss-loader": "^8.1.1",
        "postcss-modules-values": "^4.0.0",
        "postcss-normalize": "^13.0.1",
        "postcss-preset-env": "^10.1.1",
        "resolve-url-loader": "^5.0.0",
        "sass": "~1.77.8",
        "sass-loader": "^16.0.3",
        "style-loader": "^4.0.0",
        "webpack": "~5.96.1",
        "webpack-bundle-analyzer": "^4.10.2",
        "webpack-cli": "^5.1.4",
        "webpack-manifest-plugin": "^5.0.0",
        "webpack-node-externals": "^3.0.0"
```

**What is the expected behavior?**

In `5.96.1`, this was the compilation time:

```
webpack 5.96.1 compiled successfully in 21454 ms
```

**Comment by alexander-akait** [comment] 2024-12-04 08:50
Please provide the result - https://webpack.js.org/plugins/profiling-plugin/, because unfortunately it is impossible to determine the cause from your information 

And please never miss the points from the issue template, otherwise it will be closed, thank you

The only thing which was changed between these versions is and can and related to `seal` - https://github.com/webpack/webpack/blob/main/lib/util/Queue.js, but it shouldn't have changed the time so much

**Comment by ximex** [comment] 2024-12-04 09:15
same here. 15s vs 426s
this is the log that is displayed when it stops for long time
`[webpack-dev-server] [FlagDependencyExportsPlugin] 70% - sealing (finish module graph).`

**Comment by alexander-akait** [comment] 2024-12-04 09:19
@ximex Can you locally revert and use - https://github.com/webpack/webpack/blob/v5.96.1/lib/util/Queue.js

**Comment by headless-kjh** [comment] 2024-12-04 09:39
same here. 

#9 0.571 > react-scripts build
#9 0.571 
#9 1.748 Creating an optimized production build...
#9 725.2 Compiled with warnings.

**Comment by alexander-akait** [comment] 2024-12-04 09:43
Please avoid **same here**, it doesn't help at all, there is a question - https://github.com/webpack/webpack/issues/19035#issuecomment-2516655581

**Comment by alexander-akait** [comment] 2024-12-04 13:53
Can someone apply this change https://github.com/webpack/webpack/pull/19040 locally and check performance again?

**Comment by 6d7a** [comment] 2024-12-04 14:41
@alexander-akait #19040 brings a significant performance boost for me:
v5.97.0: `✨ Done in 301.77s.`
issue-19035: `✨  Done in 31.63s`

**Comment by ximex** [comment] 2024-12-04 14:55
@alexander-akait yes with this patch it has about the same performance as before

**Comment by benjaminblack** [comment] 2024-12-04 16:00
@alexander-akait sorry, I will not omit any issue template points in the future.

`af1fd12efe6a625cc3edae667f36228af958edec` does indeed fix the regression:

```
webpack 5.97.0 compiled successfully in 23498 ms
```

**Comment by andrewstec** [comment] 2024-12-05 05:23
There is something else going on in this ecosystem leading to longer build times, which I noticed today after wiping out my yarn.lock files and testing my build after upgrading Webpack. This, however, does not look like Webpack. It is just a side-effect to upgrading packages and you likely have to trace this more @benjaminblack .

So far, I think this is a babel issue. It simply looks like a Webpack issue if one upgrades Webpack and their yarn.lock changes dependencies. 

I spent 2 hours debugging and I don't know where this issue is introduced, so unfortunately I can't say more. However, I suspect this issue can be closed.

**Comment by axetroy** [comment] 2024-12-05 05:58
It is indeed slower, I wrote a benchmark in https://github.com/sindresorhus/yocto-queue/issues/10

We should revert this Queue implementation

**Comment by sunilkhokhar** [comment] 2024-12-05 08:53
#19040 This change works for me. It reduces the compilation time of "npm run build" from 442741ms to 28587ms.

**Comment by Gabriel-Conti** [comment] 2024-12-05 12:38
Same here [#19040](https://github.com/webpack/webpack/pull/19040) This change works for me
I went 
from :  384996 ms (6.4 minutes)
to:  132458 ms (2.20 minutes)

**Comment by alexander-akait** [comment] 2024-12-05 14:01
Fixed by https://github.com/webpack/webpack/pull/19040, release will be soon

**Closed by alexander-akait** 2024-12-05 14:01 UTC
Labels: question, won't fix

**Comment by alexander-akait** [comment] 2024-12-05 14:21
https://github.com/webpack/webpack/releases/tag/v5.97.1

**Comment by ximex** [comment] 2024-12-05 14:33
confirm that 5.97.1 works again
