### ISSUE TITLE
undefinedrootReducer is not defined

### ISSUE THREAD

**Issue by sh4d1t0** [webpack/webpack#8095] opened 2018-09-26 21:49 UTC
I have the next error in production mode:
undefinedrootReducer is not defined at Module.<anonymous> (..../dist7server.js:1:6328)

the log is:

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start-production' ]
> 2 info using npm@6.4.1
> 3 info using node@v10.10.0
> 4 verbose run-script [ 'prestart-production',
> 4 verbose run-script   'start-production',
> 4 verbose run-script   'poststart-production' ]
> 5 info lifecycle react-initial@1.0.0~prestart-production: react-initial@1.0.0
> 6 info lifecycle react-initial@1.0.0~start-production: react-initial@1.0.0
> 7 verbose lifecycle react-initial@1.0.0~start-production: unsafe-perm in lifecycle true
> 8 verbose lifecycle react-initial@1.0.0~start-production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/shadito/Documentos/Sitios/react-initial/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/us$
> 9 verbose lifecycle react-initial@1.0.0~start-production: CWD: /home/shadito/Documentos/Sitios/react-initial
> 10 silly lifecycle react-initial@1.0.0~start-production: Args: [ '-c',
> 10 silly lifecycle   'npm run build && NODE_ENV=production BABEL_ENV=production babel-node src/server' ]
> 11 silly lifecycle react-initial@1.0.0~start-production: Returned: code: 1  signal: null
> 12 info lifecycle react-initial@1.0.0~start-production: Failed to exec start-production script
> 13 verbose stack Error: react-initial@1.0.0 start-production: `npm run build && NODE_ENV=production BABEL_ENV=production babel-node src/server`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:182:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:182:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:962:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 14 verbose pkgid react-initial@1.0.0
> 15 verbose cwd /home/shadito/Documentos/Sitios/react-initial
> 16 verbose Linux 4.14.71-1-MANJARO
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start-production"
> 18 verbose node v10.10.0
> 19 verbose npm  v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error react-initial@1.0.0 start-production: `npm run build && NODE_ENV=production BABEL_ENV=production babel-node src/server`
> 22 error Exit status 1
> 23 error Failed at the react-initial@1.0.0 start-production script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

my repository is: https://github.com/sh4d1t0/react-initial
I don't know what I'm doing wrong

**Comment by sokra** [comment] 2018-09-27 03:52
Duplicate of #8052

**Closed by sokra** 2018-09-27 03:52 UTC
