### ISSUE TITLE
webpack-dev-server compiles twice on startup

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#12283] opened 2020-12-29 12:24 UTC
# Bug report

**What is the current behavior?**

It seems like that the watcher does not work correctly with inline entries like in the following webpack config:

```js
module.exports = {
  entry: {
    main: "./src/index.js",
    inline: "data:text/javascript,"
  },
  mode: "development",
};
```

Based on [the findings](https://github.com/jantimon/html-webpack-plugin/issues/1576#issuecomment-752041388) of @pvdstel it marks the inline script to be removed and therefore **triggers a second compilation**.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the webpack config above and start the webpack-dev-server locally or open this [codesandbox](https://codesandbox.io/s/webpack-5-double-compilation-b14b9?file=/webpack.config.js:0-631) which shows the following result:

![webpack_5_double_compilation_-_CodeSandbox](https://user-images.githubusercontent.com/4113649/103283404-c44bd600-49d8-11eb-98e2-04b34c1f5ff8.png)

As you can see `watcher.on("initial-missing"` triggers because webpack watches inline `data:` entries:

![DevTools_-_Node_js](https://user-images.githubusercontent.com/4113649/103286075-f3197a80-49df-11eb-8a18-d205ba13720f.png)

**What is the expected behavior?**

The compilation should only trigger once.

**Other relevant information:**

webpack: "5.11.1",
webpack-cli: "4.3.0",
webpack-dev-server: 4.0.0-beta.0

node: v10.23.0

**Comment by alexander-akait** [comment] 2020-12-29 13:11
@sokra watchpack watches `data:` URLs (in missing files)

**Comment by jantimon** [comment] 2020-12-30 09:14
I created a fix which prevents the double compilation here: https://github.com/webpack/watchpack/pull/186

The fix is directly added to watchpack - can you please take a look if that's a reasonable approach?

**Comment by sokra** [comment] 2020-12-30 17:15
webpack should not pass data urls to watchpack. This need to be fixed in webpack

**Comment by jantimon** [comment] 2020-12-31 11:42
Watchpack is executed from NodeWatchFileSystem.js in the `watch` method - do you think this would be the correct place to ignore `data:` urls?

https://github.com/webpack/webpack/blob/911ec1aa67011e25aa1449610f5b0b557edd5459/lib/node/NodeWatchFileSystem.js#L84

**Comment by alexander-akait** [comment] 2020-12-31 11:44
We should not put `data` url in files

**Comment by jantimon** [comment] 2020-12-31 11:46
One step back would be the `Watching` class in `lib/Watching`:

https://github.com/webpack/webpack/blob/911ec1aa67011e25aa1449610f5b0b557edd5459/lib/Watching.js#L222

**Comment by sokra** [comment] 2020-12-31 11:58
These data urls should not end up in `fileDependencies`. I guess the problem is in `loader-runner` which adds the `resource` to `fileDependencies`. But `loader-runner` doesn't differ between data urls and other resources and it probably shouldn't do that.

I guess it would be best if the `readResource` had this responsibility and no longer loader-runner itself. I guess that would be a breaking change for loader-runner and we need to release a new major for that (should be fine). Best if we pass the loader context to `readResource` so it could call `addDependency` and similar methods.

**Closed** 2021-01-07 22:30 UTC
Labels: bug, webpack-5
