### ISSUE TITLE
Webpack 4 splitChunks causes reused chunks to not be executed

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#7230] opened 2018-05-08 00:20 UTC
# Bug report

I am working in a complicated app that has a bunch of bundles on every page. Most of these are "global" bundles and appear on every page. So, I have configured webpack to prevent any modules that appear in these bundles from appearing in any other bundle via splitChunks. More context on this here: https://stackoverflow.com/questions/49163684/how-to-configure-webpack-4-to-prevent-chunks-from-list-of-entry-points-appearing

**What is the current behavior?**

It seems that when I configure splitChunks in this way, it causes the global bundles to not be executed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a branch on a repo that reproduces this issue: https://github.com/lencioni/webpack-splitchunks-playground/tree/splitchunks-execution-problem

In this repro case, it currently logs the following to the console:

```
core module
core module b
non-core module
non-core b2
non-core module b
```

In the debugging I've done, it seems that this splitChunks configuration causes the `executeModules` part of the bundle that the runtime chunk is looking for to be `undefined`.

**What is the expected behavior?**

The code in the "global" bundles should be executed, which should cause the console log to look more like this:

```
core module
core bundle
core module b
core bundle b
core bundle c
non-core module
non-core b2
non-core module b
```

**Other relevant information:**
webpack version:  4.8.1
Node.js version: 8.9.1
Operating System: Mac
Additional tools:

**Comment by lencioni** [comment] 2018-05-08 15:25
I've gotten this to behave slightly better by adding this to my chunkGroup test:

```js
if (module.depth === 0) {
  return false;
}
```

but it still doesn't work as expected.

**Comment by lencioni** [comment] 2018-05-08 15:29
This seems to maybe be happening intentionally here: https://github.com/webpack/webpack/blob/2986ab1a18e895ac3f2546ac0c70bf73c0fdb679/lib/optimize/SplitChunksPlugin.js#L559-L565

However it isn't clear to me from the code or the commit message (added by https://github.com/webpack/webpack/commit/18ae73dad4bb761593a9f5529a182601e1b57520) why this behavior exists.

**Comment by IanVS** [comment] 2018-05-11 16:00
@amakhrov if you got it working, do you mind sharing your config?  I am still struggling to convert to webpack 4 because of this issue.

**Comment by amakhrov** [comment] 2018-05-11 18:46
@IanVS here you go:
```
// =========
// site/common-entry.js
import session from './common/global-session';
import initHeader './common/header';

initHeader(session);

// =========
// site/page1-entry.js
import session from './common/global-session';
// ... do some page-specific stuff here

// =========
// html site/page1
<script src="/site/common.js">
<script src="/site/common-entry.js">
<script src="/site/page1-entry.js">

// =========
// html other/other2
// no site/common here - it's not relevant in the context of "other/" area
<script src="/other/other2-entry.js">

// =========
// finally, webpack config:

entry: {
	'site/common-entry': 'root/site/common-entry.js',
	'site/page1-entry': 'root/site/page-entry1.js',
	'other/other2-entry': 'root/other/other-entry.js',
}
optimization: {
	runtimeChunk: {
		name: 'runtime',
	},
	splitChunks: {
		cacheGroups: {
			common: {
				name: 'site/common',
				test: (module, chunks) => {
					const names = chunks
						.map(c => c.name)
						.filter(Boolean);

					const usedByCommonEntry = names.some(name => name === 'site/common-entry');
					return usedByCommonEntry;
				},
				chunks: chunk => {
					const name = chunk.name;
					if (name) {
						// this setup only applies to a subset of entry points, not to everything defined in config.entry
						return name.startsWith('site/');
					}

					// TODO: no name - is it on-demand chunks? not sure. in the meantime, exclude them from this common chunks setup
					return false;
				},
				enforce: true,
				// only extract modules that are also reused by other chunks!
				minChunks: 2,
				priority: -20,
			},
		}
	}
},
```

**Comment by expressiveco** [comment] 2018-05-21 15:42
I tried it all the ways around but could not get a single vendors chunk. So, i have following two extract vendors and vendors-entry as @amakhrov. Are there any solution to get a single vendor chunk?
```
entry: {
  "vendors-entry": path.resolve(__dirname, "src/vendors.ts"),
  main: [path.resolve(__dirname, "src/index.ts") ],
}
optimization: {
splitChunks: {
  cacheGroups: {
      vendors: {
        name: "vendors",
        chunks: "all",
        minChunks: 2,
        minSize: 0
      }
  }
},
runtimeChunk: { name: "manifest" },

```

**Comment by amakhrov** [comment] 2018-05-21 16:33
@expressiveco your config looks ok to me. It should create a `vendor.js` chunk (in addition to the `vendor-entry.js` and `main.js` entry chunks), containing modules that are shared across the both entry chunks.

What doesn't go as expected here for you?

**Comment by expressiveco** [comment] 2018-05-21 18:33
So I want vendors and vendors-entry chunks combined into a single chunk. As you concerned, it is not sensible to have multiple chunks when they will be included in all pages.

**Comment by amakhrov** [comment] 2018-05-21 18:45
The workaround is to get rid of `vendor-entry` entry chunk, and import it from your real entry point(s):
```
// main.js
import 'path/to/vendor-entry'; // this will execute all vendor-specific bootstrap code

console.log('main.js entry point')
// rest of main.js logic

// webpack.config
entries: {
  main: 'path/to/main'
},
cacheGroups: {
  vendor: {
    test: // only include vendor modules: using a regexp or a function
    minChunks: 1, // extract a vendor module into the 'vendor' chunk even if it's only used in a single entry chunk (main.js)
  }
}
```

**Comment by expressiveco** [comment] 2018-05-21 19:53
So, how should be the test function? My vendors.ts contains imports for moduless. How could i simply test for them, one by one for each module?

**Comment by amakhrov** [comment] 2018-05-21 20:09
It depends on how you define 'vendor' modules.

See the test function in my example above. The function takes the name of the module and the array of chunks which have this module included.

If you want to extract all modules used by your vendor-entry file, you would do smth like
```
test: (module, chunks) => {
  const names = chunks
    .map(c => c.name)
    .filter(Boolean);

  return names.some(name => name === 'path/vendor-entry');
}
```

**Comment by expressiveco** [comment] 2018-05-22 11:10
@amakhrov now i have following(minChunks:2) per your recommendation, but main.js is around 3mb and vendors.js is 700kb but i want to all those code in vendors.js instead main.js.

And when minChunks:1, everything is in vendor.js but subPageEntry could not access to the output.library variable, it is undefined.

```
entry: {
    main: path.resolve(__dirname, "src/index.ts"),
    subPageEntry: path.resolve(__dirname, "subPageEntry.ts"),
},

splitChunks: {
    cacheGroups: {
        vendors: {
            test: (module, chunks) => {
                const names = chunks
                    .map(c => c.name)
                    .filter(Boolean);

                return names.some(name => name === 'main');
            },
            name: "vendors",
            chunks: "all",
            minChunks: 1,
            minSize: 0,
        }
    }
},
runtimeChunk: { name: "manifest" },

- index.ts
import "./vendors.ts";
import "./index.less";
import "../Scripts/Master.ts"

- vendors.ts
import "./vendor-styles.ts";
import "jquery";
import "bootstrap";
```

**Comment by expressiveco** [comment] 2018-05-25 10:35
Finally, i could get a single vendors bundle that contains all vendor code while keeping the code of top-level entries in their own bundle.
Also, my library(ProjectLib) is in its own bundle instead of vendors.
```
- main.ts
import "vendors.ts";
... some common code for application

- vendors.ts
import "jquery";
import "bootstrap";
import "datatables.net";

- page1.ts
import "ProjectLib/MyPlugin.ts"

- page2.ts
import "ProjectLib/MyCommon.ts"

- webpack.dev.js
const ProjectLibDir = path.resolve(__dirname, "ProjectLib");
entry: {
    main: path.resolve(__dirname, "main.ts"),
    page1: path.resolve(__dirname, "page1.ts"),
    page2: path.resolve(__dirname, "page2.ts"),
},
optimization: {
    splitChunks: {
        cacheGroups: {
            projectLib: {
                test: (module, chunks) => {
                    if (module.depth === 0) {
                        return false;
                    }

                    return module.context == ProjectLibDir;
                },
                name: "projectLib",
                chunks: "all",
                minChunks: 1,
                minSize: 0,
                priority: 20,
                enforce: true
            },
            vendors: {
                test: (module, chunks) => module.depth > 0,
                name: "vendors",
                chunks: "all",
                minChunks: 1,
                minSize: 0,
                priority: 10,
                enforce: true
            }
        }
    },
    runtimeChunk: { name: "manifest" },
},
```

**Comment by fabd** [comment] 2018-09-04 13:58
IF somehow you do not need the common bundle to be included and executed on its own on some pages of your site, then there is a very simple fix, am I right? You basically just "require" the common bundle, from your other entry points.

Now, IF you have pages where you include just the common bundle (say, it contains Vue) and you don't need the other specific bundles, then this common bundle won't run. So if it contains something like `window.Vue = Vue`... then that won't be executed.

So in the first scenario, where we *always include some other bundle with the common bundle*, then the simple fix appears to be just one import / require statement from the non-common bundle(s):

```
// WEBPACK CONFIG
module.exports = {
  // ...
  entry: {
    'common-bundle':   './lib/front/common-bundle.js',
    'page1-bundle':  './lib/front/page1-bundle.js'
  }
  // ...
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          name: 'common-bundle',
          chunks: 'initial',
          minChunks: 2
        }
      }
    }
  }

// FILE common-bundle.js

import Vue from 'vue'
window.Vue = Vue
console.log("hi from common-bundle")

// FILE page1-bundle.js

console.log("hi from page1-bundle");
import CommonBundle from './common-bundle.js'
```

Console output:
```
hi from common-bundle
hi from page1-bundle
```

So with Webpack 4 it's just annoying if you have a vendor / common bundle that you sometimes want to use alone on a page, then you have to create another entry point, and another JS request on the page.

Am I following this correctly?

**Comment by sergei-startsev** [comment] 2018-12-03 22:43
You could use [DllPlugin](https://webpack.js.org/plugins/dll-plugin/#dllplugin) and [DllReferencePlugin](https://webpack.js.org/plugins/dll-plugin/#dllreferenceplugin) for code splitting and [ExecutableDllPlugin](https://github.com/sergei-startsev/ExecutableDllPlugin) to execute a bundle with shared modules.

**Comment by xuqingkuang** [comment] 2019-02-21 10:16
I was meet the same issue, and I am looking forward to the merge request could be accepted.

**Comment by snapwich** [comment] 2019-08-23 22:51
Running into this same issue and it's preventing us from updating https://github.com/prebid/Prebid.js from webpack v3 to v4.

We have a unique (until I saw this thread, maybe some here are doing the same) issue where we have 100+ entry points with 1 entry point being the "core" module that contains shared code across all of the other entry points. This allows us to split our code into jsonp fragments and build dynamic bundles at runtime through concatenating the resulting build files depending on which additional code we want. This pattern is the foundation for our [Prebid.js code module system](https://github.com/prebid/Prebid.js#build-optimization).

I can emulate the right build output using splitChunks in webpack 4 (verified with the webpack-bundle-analyzer) except that in the webpack 4 bundle the "core" module entry point is never executed even though the other entry points are.

I have a simple reproduction of our issue here that I made before I found this issue: https://github.com/snapwich/webpack4-chunk-bug

As @lencioni mentioned as well, I can confirm that removing this code from the splitChunks plugin seems to fix the issue:
```javascript
// If the chosen name is already an entry point we remove the entry point
const entrypoint = compilation.entrypoints.get(chunkName);
// commenting this code out fixes the issue
// if (entrypoint) {
// 	compilation.entrypoints.delete(chunkName);
// 	entrypoint.remove();
// 	newChunk.entryModule = undefined;
// }
```

**Comment by sergei-startsev** [comment] 2019-08-24 07:20
@snapwich [DllPlugin](https://webpack.js.org/plugins/dll-plugin/#dllplugin) /[DllReferencePlugin](https://webpack.js.org/plugins/dll-plugin/#dllreferenceplugin) provided by webpack should give you more control over code splitting. You could use them with [ExecutableDllPlugin](https://github.com/sergei-startsev/ExecutableDllPlugin) to execute particular entry points within the resulted bundle.

**Comment by sumit116** [comment] 2019-08-26 12:33
@snapwich , I found that you are using enforce: true in splitchunks cacheGroups which is not allowing the common chunk (entry) to execute. Removing it worked for me.

**Comment by IMalyugin** [comment] 2019-12-24 15:35
Had the same issue in context of:
- multiple entry points
- common bundle
- expose-loader for SiteHeader and SiteFooter

Problem: When SiteHeader and SiteFooter are added to common bundle entrypoint, they do not get exposed as a result. Even when i use them along with appropriate entryPoint.

**Suggested solution**: is probably to move exposed header and footer on to another entrypoint, but that requires reworking server-side for which pages to render.

**Accepted solution**: we went with **adding SiteHeader and SiteFooter to every entrypoint** by a function like this:
```
const addEntryToEach = (extra, entries) => Object.keys(entries).reduce((result, entryName) => ({
  ...result,
  [entryName]: [
    ...entries[entryName],
    ...extra,
  ],
}), {});
```

Looking like this in the end:
```
module.exports = {
   entry: {
     vendor: [...],
     ...addEntryToEach([path.resolve(__dirname, './global-exports.js')], {
       common: [ ... ],
       ...myEntryPoints
     })
  ...
};
```

**Comment by Shubham819** [comment] 2020-06-12 09:29
Hi, can Any1 help me convert common chunk to split chunks
I am using webpack 4
New webpack. Optimize. Commonschunkplugin
({
Name: pollyfills,
Chunks : pollyfills
})
New webpack. Optimize. Commonschunkplugin
({
Name: vendor,
Chunks : main, 
Minchunks:module => utils. IsexternalLib(module) 
}) 
New webpack. Optimize. Commonschunkplugin
({
Name: [pollyfills, vendor]. Reverse,
Chunks : pollyfills
})

**Comment by burzum** [comment] 2020-06-15 14:45
We have the same problem and no solution to it. 😞 

Webpack version: ^4.34.0
Node.js version: 12.8.0
Operating System: Windows, Ubuntu and OSX

```js
	optimization: {
		splitChunks: {
			chunks: 'all',
			minSize: 30000,
			minChunks: 1,
			maxAsyncRequests: 5,
			maxInitialRequests: 3,
			automaticNameDelimiter: '~',
			name: true,
			cacheGroups: {
				commons: {
					test: /[\\/]node_modules[\\/]/,
					name: 'js/public/wa-common',
					chunks: 'all'
				}
			}
		}
	},
```

**Comment by IMalyugin** [comment] 2020-06-15 15:24
Did you try the solution I mentioned above? It helped us overcome current webpack limitations. The whole idea is that, by stating that each entry point has your common chunks. The EXECUTION part lands inside each of the entry point scripts, while your common chunk still keeps the common code. And when used together, you get the desired effect.

**Comment by vankop** [comment] 2021-09-15 20:06
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.

**Closed by vankop** 2021-09-15 20:06 UTC
