### ISSUE TITLE
Compile stuck at optimize chunk assets

### ISSUE THREAD

**Issue by raulferras** [webpack/webpack#537] opened 2014-10-15 07:21 UTC
I've started having problems to compile my build when `--optimize-minimize` is enabled.
I see that I've reached +/-205 build modules, and then the compilation gets stuck at `80% optimize chunk assets` for a very long time (+40minutes).  
If I wait enough, it ends up node failing with "fatal error: js allocation failed - process out of memory"

I guess it has to do with the uglifyjs plugin as I said this only happens when using `--optimize-minime` flag (When compiling through my grunt task, this also fails).

**Comment by jkimbo** [comment] 2015-01-05 19:10
I've just come across the same problem with a large project with 26 entry points. If I disable source maps it works but hangs with source maps enabled. My current hypothesis is that because webpack keeps all the sourcemaps in memory as it is compiling it results in node hitting the 1.4Gb limit in v8. I'm not familiar with how the internals work but can the maps not be flushed to the files on disk instead of keeping them in memory?

**Comment by jkimbo** [comment] 2015-01-06 12:07
I've managed to solve the issue by externalising some of the big libraries (React and jQuery). That seems to have reduced the memory usage considerably and I can now compress the bundles with source maps.

**Comment by jhnns** [comment] 2015-01-07 09:28
Probably it's sufficient to flag libraries with [noParse](http://webpack.github.io/docs/configuration.html#module-noparse)

**Comment by jkimbo** [comment] 2015-01-27 15:24
@sokra so I've created a fairly contrived example repo that manages to reproduce the problem here: https://github.com/jkimbo/webpack-memory-issue 

It has 20 entry points each of which requires fairly large libraries and then it runs it through the uglify plugin with sourcemaps. I realise it is in no way optimised but hopefully it can help debug this issue.

**Comment by pr0ton** [comment] 2015-01-30 08:04
I am seeing a similar issue as well.

**Comment by pago** [comment] 2015-01-30 15:48
I have the same problem without UglifyJS (continuous development build). The problem occurs after a couple of rebuilds and I believe I have an idea of where it leaks memory.

In my case, the count of ModuleNotFoundError objects created is growing at an extremely high pace. That error is thrown because of moment.js so I excluded it from parsing (noParse) and as a result the heap size stays stable (instead of growing further). If I read the dump in node-inspector correctly, it might be in the cache object of the Compilation module.

That's as much as I could find out so far.

**Comment by sokra** [comment] 2015-01-31 15:36
You can try to disable the cache with `cache: false`.

**Comment by shprink** [comment] 2015-04-13 14:53
Having the same.

**Comment by shprink** [comment] 2015-04-13 16:56
Ended up downgrading webpack-dev-server to 1.7.0 and webpack to 1.7.3 to make it work.

**Comment by sokra** [comment] 2015-04-13 17:25
Regarding the original issue:

``` js
new UglifyJsPlugin({
  sourceMap: false
})
```

should help...

**Comment by margielm** [comment] 2015-05-11 19:40
Have the same issue here, without UglifyJsPlugin. 
Do you have any idea when can this be fixed?

anyway. Thanks for the webpack! incredible pice of art.

**Comment by roman01la** [comment] 2015-07-06 12:42
Same issue, `sourceMap: false` doesn't make any difference, removing UglifyJS plugin helps.

**Comment by jedwards1211** [comment] 2015-07-29 22:18
I don't think it's UglifyJS or memory; my webpack config suddenly started hanging at only module 67, when it was successfully building over 400 modules before.  Ironically it still works with webpack dev server and various plugins; but my config that's hanging has *no* plugins.

**Comment by jedwards1211** [comment] 2015-07-29 22:23
Here's my config that hung it.

`webpack.config.base.js` (if I use this config by itself it doesn't hang):

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: [
    'babel/polyfill',
    './app',
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/assets/',
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel?stage=0',
        exclude: /node_modules|vendor/,
      }, 
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }, 
      {
        test: /\.sass/,
        loader: 'style-loader!css-loader!sass-loader?indentedSyntax&outputStyle=expanded&' +
        "includePaths[]=" +
        (path.resolve(__dirname, "./node_modules"))
      }, 
      {
        test: /\.scss/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&' +
        "includePaths[]=" +
        (path.resolve(__dirname, "./node_modules"))
      }, 
      {
        test: /\.(png|jpg)$/,
        loader: 'url-loader?limit=8192'
      },
    ],
  },
};
```

`webpack.config.js`:

```
var path = require('path');
var webpack = require('webpack');
var config = require('./webpack.config.base');
var _ = require('lodash');

var getWindowReact = path.resolve(__dirname, 'getWindowReact');

module.exports = _.assign({}, config, {
  resolve: _.assign({}, config.resolve, {
    alias: _.assign({}, config.resolve.alias, {
      'react$': getWindowReact,
      'react/addons$': getWindowReact,
    }),
  }),
});
```
`getWindowReact.js`:

```
// my boss wants me to use React from a CDN
export default window.React;
```

**Comment by jedwards1211** [comment] 2015-07-30 00:19
@jhnns unfortunately `noParse` won't work for React because it uses `require` extensively

**Comment by jedwards1211** [comment] 2015-07-30 00:20
@sokra I was thinking, if only I could make Webpack print out the modules one by one as it encounters them, then I could see which one it's hanging on, and maybe that would give me a clue what to investigate next.

**Comment by jedwards1211** [comment] 2015-07-30 00:22
Another note, my compilation gets stuck before the optimizing chunk assets part.  Who knows, there might be several unrelated issues here.

**Comment by Monokai** [comment] 2015-08-16 16:25
I have exactly the same issue, and also at the exact same percentage (80%). Dev builds work fine.

**Comment by jedwards1211** [comment] 2015-08-16 19:16
@Monokai As far as I've seen it always says 80% for optimizing chunk assets.

**Comment by johann-sonntagbauer** [comment] 2015-08-18 05:43
@jedwards1211 @Monokai  I faced the same problem. The main thing on my side is a bug in the libsass transpiler. Following workaround solves the problem for me:
`UV_THREADPOOL_SIZE=100 npm run build`
Maybe this tweek of the node internal threadpools helps.

**Comment by jedwards1211** [comment] 2015-08-18 13:46
@johann-sonntagbauer Fortunately there's a new release of sass-loader with a workaround that doesn't require `UV_THREADPOOL_SIZE=100`, info about it here: https://github.com/jtangelder/sass-loader/pull/132

**Comment by jedwards1211** [comment] 2015-08-18 13:48
@johann-sonntagbauer and I thought `node-sass` couldn't hang webpack at the "optimizing chunk assets" stage, only beforehand.  Am I wrong?

**Comment by johann-sonntagbauer** [comment] 2015-08-19 08:31
@jedwards1211 thx for the note about jtangelder/sass-loader#132 :+1:

**Comment by Monokai** [comment] 2015-08-19 08:40
@johann-sonntagbauer @jedwards1211 Strange, because I'm using Less, instead of Sass. Could it be that the Less loader has the same issues?

**Comment by johann-sonntagbauer** [comment] 2015-08-19 12:27
@Monokai sorry that i have overlooked that detail. simply thought that the error looks quite similar to mine and wanted to share the workaround. To be honest I don't dig into it. For the less compiler i can't give any hint, because I have never used it. Perhaps there could be a similar issue but I don't know, sorry.

**Comment by jedwards1211** [comment] 2015-08-19 14:59
@Monokai I don't know.  As far as I understand `node-sass`' issue comes from doing the parsing in C and using `libuv` to run renderers in parallel.  I'm guessing nothing inside the Less loader does that?   It's crazy stuff, I don't know when one needs to run renderers in parallel, but it certainly seems unnecessary for a Webpack loader.

**Comment by fresheneesz** [comment] 2015-10-08 22:00
If this is an Uglify issue, maybe its related to this: https://github.com/mishoo/UglifyJS2/issues/636 ? Doesn't look like they've released it on npm yet tho.

**Comment by zoomchik** [comment] 2015-10-18 16:34
I had the same issue. After updating the css-loader to 0.19.0 version, it disappeared.

**Comment by bebraw** [comment] 2015-11-15 11:28
@raulferras Safe to close?

**Comment by sparty02** [comment] 2015-11-16 23:20
I just updated to ```webpack@1.12.6``` and that fixed it for me!

**Comment by fresheneesz** [comment] 2015-11-17 04:42
@bebraw The css-loader can't be the only problem here. My issue, for example, seems to be related to uglify, since I'm not using the `css-loader`.

**Comment by bebraw** [comment] 2015-11-17 06:39
@fresheneesz I think the uglify dependency of webpack was updated a while ago. Hopefully that fix you linked to made it in. Perhaps it's worth giving it a go again.

**Comment by roman01la** [comment] 2015-11-17 10:37
I had an issue also related to UglifyJS. Mainly because I have a minified lib in modules, so Uglify takes like 5 minutes to parse it. Notice that it still works, just takes longer to process everything.

**Comment by blacksonic** [comment] 2016-01-02 18:40
Try disabling minimize for some of the loaders. I had that issue with html and adding html?minimize=false to the loaders solved it.

**Comment by SenHeng** [comment] 2016-01-03 23:42
I'm getting a similar problem after adding d3 to a very simple hello world repo.
I've let it run for 10 minutes but it didn't seem like it was proceeding and I was afraid my laptop might overheat so I shut it down.

https://github.com/SenHeng/ng1xts/commit/4277d1ccb04134534779e8b2fa0a520b59d3574d

**Comment by jontonsoup** [comment] 2016-01-05 03:14
@raulferras did you ever resolve this issue?

**Comment by fresheneesz** [comment] 2016-01-06 01:23
I still have this problem with webpack 1.12.9, which uses uglify-js 2.6.1. Honestly I don't know what to do with this other than put up with my build time being literally 100 times longer than it was before.

**Comment by mattboehm** [comment] 2016-01-07 01:29
Using

    new UglifyJsPlugin({
        sourceMap: false
    })

Burns 100% of the cpu for >45minutes before I gave up and killed the process.

Running `uglifyjs` on webpack's output completes in a matter of seconds.

**Comment by fresheneesz** [comment] 2016-01-07 02:32
Adding some logs into the [UglifyJsPlugin.js file](https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js), I see that its stopping and taking forever at line 88: `ast = ast.transform(compress);`. In my current test, its hanging for perhaps 2 minutes before moving on to the next file and hanging again.

**Comment by jontonsoup** [comment] 2016-01-07 04:48
I narrowed it down to packages that seem to have already been compressed/minified.

Best,
Jon

**Comment by fresheneesz** [comment] 2016-01-07 09:11
I definitely don't have any already-minified sources in my package.

**Comment by abhinavsingi** [comment] 2016-01-11 18:19
Faced same issue of ```80% optimize chunk assets```
I'm not using Uglify plugin
Works when I don't include devtool - (but that is very much required!)
Looks like as suggested above source-map might be causing this.
Any workarounds or fixes?

**Comment by abhinavsingi** [comment] 2016-01-14 14:29
@sokra : Any updates on this ``` 80% optimize chunk assets ``` issue?

**Comment by ericgio** [comment] 2016-01-19 01:12
I was running into a similar issue when trying to run a production config on a remote server. It worked fine locally, but the process would hang at `78% optimize chunk assets` then be killed after some time. setting `sourceMap: false` seemed to work, though I now get the following UglifyJs error: `TypeError: Cannot read property 'sections' of null`

**Comment by fresheneesz** [comment] 2016-01-19 01:42
@ericgio Where are you using `sourceMap: false`? I don't see that option in any of the docs. Trying it at the top level of the config, I don't see a difference.

**Comment by ericgio** [comment] 2016-01-19 08:17
@fresheneesz: I added it to the UglifyJS plugin config as suggested a few posts up. I actually found the root cause of my problem, which may be what others were experiencing. It turns out I was using the `UglifyJsPlugin` in the config file but also running `webpack -p`, so optimizing twice. When I removed the `-p` from the CLI command, everything worked. More here: https://github.com/webpack/webpack/issues/1385#issuecomment-160553651

**Comment by abhinavsingi** [comment] 2016-01-19 15:06
I'm not using ```UglifyJsPlugin``` and also not running webpack with the param ```p``` but it's still stuck at ```80% optimize chunk assets```
My project is quite big though - Will that matter?

**Comment by fresheneesz** [comment] 2016-01-19 22:04
@abhinavsingi Ah thanks. Yeah it doesn't help for me, unfortunately. I'm also not running from CLI. Here are my options for reference:

```
{ context: '/home/vagrant/backend',
  entry: '././git/frontend/App',
  output:
   { path: '/home/vagrant/backend/git/frontend/public',
     filename: 'App.bundle.[chunkhash].js',
     pathinfo: false,
     jsonpFunction: undefined },
  plugins:
   [ OccurrenceOrderPlugin { preferEntry: true },
     DedupePlugin {},
     UglifyJsPlugin { options: { sourceMap: false } },
     ProgressPlugin { handler: [Function] },
     ContextReplacementPlugin {
       resourceRegExp: /.*$/,
       newContentResource: undefined,
       newContentRecursive: undefined,
       newContentRegExp: /NEVER_MATCH^/ },
     BannerPlugin { options: { raw: true, entryOnly: true }, banner: '' } ],
  cache: false,
  devtool: undefined,
  watch: false,
  module: { wrappedContextCritical: true } }
```

**Comment by max-mykhailenko** [comment] 2016-03-03 16:36
If you using postcss-functions you must apply they before another postcss modules. I have this bug in this context.
How you can debug this problem:
* comment modules
* In order disable loaders (babel, scss, postcss, less etc). Get sources without processing.

**Comment by max-mykhailenko** [comment] 2016-03-03 16:41
Also you can have this problem if you are using extract plugin and it has incorrect loaders. For example without first array argument `['css', 'scss|less|etc']`

**Comment by liaohuqiu** [comment] 2016-03-18 17:16
Try to remove `dev-tool: source-map`, then it will be much faster. But I'm still trying to figure out how can keep `source-map`.

**Comment by bharley** [comment] 2016-04-20 20:27
I am also experiencing this problem when Webpack tries to compress node includes which have already been minified. Has anyone figured out a decent workaround for this?

**Comment by fresheneesz** [comment] 2016-04-20 21:51
I haven't : (

**Comment by brenwell** [comment] 2016-04-27 11:35
I had the same problem as everyone, adding `UglifyJsPlugin { options: { sourceMap: false } }` didn't work sadly, the problem was my pre-minified Three.js dependency. I was requiring `Three.min.js` and changing it to the `src/Three.js` files fixed for me instantly, thanks everyone for all the clues

**Comment by JsonHunt** [comment] 2016-05-04 19:07
I was able to resolve the "additional chunk assets" slowness by adding this line in webpack-config:

```
module: {
   noParse: new RegExp("node_modules"),
   ....
```

**Comment by Restuta** [comment] 2016-05-04 21:14
@JsonHunt are you sure that is what resolved it and that it's the same issue? It didn't do anything for my project (https://github.com/Restuta/rcn.io main-page branch)

**Comment by JsonHunt** [comment] 2016-05-04 21:28
@Restuta Try specifically excluding dev dependencies. I am seeing massive speed boost. See my updated comment above

**Comment by Restuta** [comment] 2016-05-04 21:29
@JsonHunt already excluded https://github.com/Restuta/rcn.io/blob/main-page/webpack.config.prod.js#L104 this doesn't solve this particular issue of chunk assets hanging

**Comment by JsonHunt** [comment] 2016-05-04 21:33
@Restuta noParse requires an array of regular expressions, not strings

**Comment by Restuta** [comment] 2016-05-04 21:42
@JsonHunt it works with strings as well, you can see it yourself, if I would remove those it would not compile

**Comment by dougcalobrisi** [comment] 2016-05-04 21:43
If still getting stuck/crashing due to OOM at 78%, after removing any pre-minified assets, you may want to try running WebPack with more memory than Node's default and a larger thread pool. You can use the _UV_THREADPOOL_SIZE_ environment variable to set the size of the thread pool, and Node's _--max_old_space_size=SIZE_IN_MB_ argument to increase the Node's memory limit.

For example:
```bash
UV_THREADPOOL_SIZE=100 node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config config/webpack/production.js
```

Additionally, I use the following configuration for the UglifyJS plugin for production and it works fine when given enough resources as noted above...it just takes a good bit longer than desired:

```javascript
new webpack.optimize.UglifyJsPlugin({
            sourceMap: false,
            minimize: true,
            compress: {
                drop_debugger: true,
                warnings: false,
                drop_console: true
            }
})
````

I know much of this has been mentioned in this issue, but wanted to put the core workarounds that I found together in one place for people searching.

**Comment by sunlei33** [comment] 2016-05-16 03:01
not to minimize for compress-already code, that will make the process extremely slow. This is an known issue for uglifyjs, see this https://github.com/mishoo/UglifyJS2/pull/1024, the pull request has just been merged to master, not been published to npm I think.

**Comment by twhid** [comment] 2016-05-19 22:10
We're also running into this issue and have worked-around exactly as @dougcalobrisi suggests. It's slow, but at least it doesn't die.

**Comment by dougcalobrisi** [comment] 2016-05-20 14:41
@Tzaphkiel - Does the big dependency you added to your project have any pre-minified files? If so, that is likely the cause, as @sunlei33 recently mentioned about the UglifyJS issue. 

If not, try using the workarounds for increasing the number of threads and allocated memory for the node process running webpack, as I summarized above. I have encountered the exact same issues.

**Comment by Tzaphkiel** [comment] 2016-05-20 14:46
@dougcalobrisi  - Ok, thx, that might be it, the project I'm trying to include is alloy-editor which contains ckeditor, etc. and has indeed minimized files.

Is there a plan to fix this ? I saw something about UglifyJS having a fix in master but nothing released in npm yet... the dep. would still have to be adapted in webpack dependency no ? 

My workaround for the moment is simply to turn off compress in the plugin definition for UglifyJS...
This is tedious and impractical :(

**Comment by dougcalobrisi** [comment] 2016-05-20 15:10
@Tzaphkiel - You could clone the current master repo for UglifyJS and then use [npm link](https://docs.npmjs.com/cli/link) to create a globally installed version of the current master of UglifyJS, then delete the current UglifyJS dep in node_modules/ of your project and then install the linked version. 

I haven't actually tried this, it's just off the top of my head, but should work. Something like this:

```
#clone the master repo and link it
mkdir ~/modules
git clone git://github.com/mishoo/UglifyJS2.git ~/modules/uglifyjs
npm link ~/modules/uglifyjs

#move to your project, remove the old uglifyjs dep, link the new one, and confirm the symlink shows
cd <path of your project>
rm -rf node_modules/uglifyjs
npm link uglifyjs
ls -l node_modules/uglifyjs
````

At that point your project should have the uglifyjs dependency in your project's node_modules symlinked to the globally installed version of the current master branch of UglifyJS. You'll want to unlink it once they have pushed a new release to npm.

Let me know if that works or not for you. As I said I haven't actually tested it, so no guarantees. Likely very helpful for others if it works, though.

**Comment by ConAntonakos** [comment] 2016-06-04 20:23
Just happened to me. And I tested it again after removing `devtool: inline-source-map`, and the build compilation worked great and much quicker.

**Comment by chshawkn** [comment] 2016-06-13 18:15
```
watch: true 
```
make this happens. Disable watch solved problem for me.

**Comment by FrendEr** [comment] 2016-06-15 08:12
@dougcalobrisi how can I know webpack's default memory and thread pool that Node provides ? And how much should I set will be best ? `UV_THREADPOOL_SIZE=100` or `UV_THREADPOOL_SIZE=10` ? The same to `max_old_space_size`

**Comment by dougcalobrisi** [comment] 2016-06-15 18:01
@FrendEr - I believe the default heap allocation is 1.76gb for a 64bit environment. You could check it using `v8.getHeapStatistics()` - docs: [https://nodejs.org/api/v8.html](https://nodejs.org/api/v8.html)

As for the default thread pool size, I believe that is coming from libuv which has a default of 5 threads.

**Comment by FrendEr** [comment] 2016-06-16 13:14
@dougcalobrisi thanks! I use `UV_THREADPOOL_SIZE=100 node --max_old_space_size=4096` to make my webpack run 8s reduce to 6.5s at `additional chunk assets`, but it still hangs at 78%.

**Comment by FrendEr** [comment] 2016-06-21 10:25
@sunlei33 uglify-js@2.6.3 has merge the issue#1024 and publish, but it has no effect on build optimization

**Comment by FrendEr** [comment] 2016-06-21 14:24
```
compilation.plugin("additional-chunk-assets", function() {
  handler(0.78, "additional chunk assets");
});
```

I found the code in `ProgressPlugin.js`, I think UglifyJS takes much time to optimize code, but the reson for `webpack hang at 78%` just because the code above. It won't update before it turn to next step call `optimize-chunk-assets`

**Comment by theatlasroom** [comment] 2016-06-29 05:29
Had this same issue, building was taking 10mins+ and as a few people have noted, i took out my minified dependencies and it now builds in ~10s :D.

**Comment by d3viant0ne** [comment] 2016-06-29 05:54
Had the same general issue as @theatlasroom and when the same direction to try and troubleshoot which oddly enough solved the issue. <shrug>

**Comment by rturk** [comment] 2016-11-15 12:06
Increasing swap worked for me!

**Comment by unformatt** [comment] 2016-11-19 00:08
@rturk can you elaborate?

**Comment by fresheneesz** [comment] 2016-12-21 11:13
@unformatt I also found out that I didn't have any swap space enabled on my digital ocean centos machine, which was causing the out-of-memory killer to kill my install script. Increasing swap fixed that problem for me. It still hangs for a bit at 78-80% tho.

**Closed** 2017-01-11 17:17 UTC
Labels: bug, difficult

**Comment by fresheneesz** [comment] 2017-01-11 20:23
@sokra Could you comment on why you closed this? Has a fix from uglify been pulled in to fix the problem with already-compiled files?

**Comment by MoiraG** [comment] 2017-03-05 15:03
removing the --progress option worked for me

**Comment by kevmt** [comment] 2017-03-31 15:04
In some cases and digging, i've fixed mine by insuring that the `names` has unique entries..

```
if (Mix.extract) {
    module.exports.plugins.push(
        new webpack.optimize.CommonsChunkPlugin({
            names: Mix.entryBuilder.extractions.concat([
                path.join(Mix.js.base, 'manifest').replace(/\\/g, '/')
            ]).filter(function (item, pos, self) {
                return self.indexOf(item) == pos;
            }),
            // minChunks: ({resource}) => /node_modules/.test(resource)
            minChunks: Infinity
        })
    );
}
```

Hope it helps.

**Comment by chouhan** [comment] 2017-05-02 02:45
webpack asset optimization continuously loops on 'ng serve'. I was expecting it would do once, then start my app at localhost:4200

Any Ideas?

Did npm update, and got all latest node_modules. Here is my 

// package.json

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "package.json from the documentation, supplemented with testing support",
  "angular-cli": {},
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "pree2e": "webdriver-manager update",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.1.0",
    "@angular/common": "^4.1.0",
    "@angular/compiler": "^4.1.0",
    "@angular/compiler-cli": "^4.1.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "^4.1.0",
    "@angular/http": "^4.1.0",
    "@angular/platform-browser": "^4.1.0",
    "@angular/platform-browser-dynamic": "^4.1.0",
    "@angular/platform-server": "^4.1.0",
    "@angular/router": "^4.1.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.15",
    "angular-in-memory-web-api": "~0.2.1",
    "angular2-jwt": "^0.1.28",
    "angular2-logger": "^0.5.1",
    "auth0-lock": "^10.10.2",
    "bootstrap": "4.0.0-alpha.5",
    "core-js": "^2.4.1",
    "jquery": "1.9.1 - 3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-rc.4 - 5.0.1",
    "systemjs": "0.19.40",
    "tether": "^1.3.7",
    "typescript": "^2.3.2",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.36",
    "@types/node": "^6.0.46",
    "@types/selenium-webdriver": "^2.53.33",
    "angular-cli": "^1.0.0-beta.22-1",
    "canonical-path": "0.0.2",
    "concurrently": "^3.1.0",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.4.1",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "~4.0.13",
    "rimraf": "^2.5.4",
    "ts-node": "^1.7.2",
    "tslint": "^3.15.1",
    "typescript": "~2.0.10",
    "webdriver-manager": "^11.1.0",
    "@types/google-maps": "^3.2.0"
  },
  "repository": {}
}

**Chouhan:mockii_node rakeshchouhan$** ng serve
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

Your global Angular CLI version (1.0.0-beta.28.3) is greater than your local
version (1.0.0-beta.22-1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
                                                                                                                                                                                                                                                              Hash: 2a5559aa5e7694288411                                                                                                                                                                                                                                                        
Time: 17424ms
chunk    {0} 0.chunk.js, 0.bundle.map 54 kB {7} {6} {5} {2} {4} {3} {1} [rendered]
chunk    {1} 1.chunk.js, 1.bundle.map 22.1 kB {3} {4} {2} {5} {6} {0} {7} [rendered]
chunk    {2} 2.chunk.js, 2.bundle.map 17.8 kB {5} {4} {3} {1} {6} {0} {7} [rendered]
chunk    {3} 3.chunk.js, 3.bundle.map 4.62 kB {1} {4} {2} {5} {6} {0} {7} [rendered]
chunk    {4} 4.chunk.js, 4.bundle.map 3.77 kB {2} {3} {1} {5} {6} {0} {7} [rendered]
chunk    {5} 5.chunk.js, 5.bundle.map 4.43 kB {6} {2} {4} {3} {1} {0} {7} [rendered]
chunk    {6} 6.chunk.js, 6.bundle.map 4.43 kB {0} {5} {2} {4} {3} {1} {7} [rendered]
chunk    {7} main.bundle.js, main.bundle.map (main) 172 kB {9} [initial] [rendered]
chunk    {8} styles.bundle.js, styles.bundle.map (styles) 9.72 kB {10} [initial] [rendered]
chunk    {9} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial] [rendered]
chunk   {10} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
webpack: Compiling...
                                                                 Hash: 2a5559aa5e7694288411                                                                                                                                                                             
Time: 830ms
chunk    {0} 0.chunk.js, 0.bundle.map 54 kB {7} {6} {5} {2} {4} {3} {1}
chunk    {1} 1.chunk.js, 1.bundle.map 22.1 kB {3} {4} {2} {5} {6} {0} {7}
chunk    {2} 2.chunk.js, 2.bundle.map 17.8 kB {5} {4} {3} {1} {6} {0} {7}
chunk    {3} 3.chunk.js, 3.bundle.map 4.62 kB {1} {4} {2} {5} {6} {0} {7}
chunk    {4} 4.chunk.js, 4.bundle.map 3.77 kB {2} {3} {1} {5} {6} {0} {7}
chunk    {5} 5.chunk.js, 5.bundle.map 4.43 kB {6} {2} {4} {3} {1} {0} {7}
chunk    {6} 6.chunk.js, 6.bundle.map 4.43 kB {0} {5} {2} {4} {3} {1} {7}
chunk    {7} main.bundle.js, main.bundle.map (main) 172 kB {9} [initial]
chunk    {8} styles.bundle.js, styles.bundle.map (styles) 9.72 kB {10} [initial]
chunk    {9} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial]
chunk   {10} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
webpack: Compiled successfully.
webpack: Compiling...                                            Hash: 2a5559aa5e7694288411                                                                                                                                                                             
Time: 396ms
chunk    {0} 0.chunk.js, 0.bundle.map 54 kB {7} {6} {5} {2} {4} {3} {1}
chunk    {1} 1.chunk.js, 1.bundle.map 22.1 kB {3} {4} {2} {5} {6} {0} {7}
chunk    {2} 2.chunk.js, 2.bundle.map 17.8 kB {5} {4} {3} {1} {6} {0} {7}
chunk    {3} 3.chunk.js, 3.bundle.map 4.62 kB {1} {4} {2} {5} {6} {0} {7}
chunk    {4} 4.chunk.js, 4.bundle.map 3.77 kB {2} {3} {1} {5} {6} {0} {7}
chunk    {5} 5.chunk.js, 5.bundle.map 4.43 kB {6} {2} {4} {3} {1} {0} {7}
chunk    {6} 6.chunk.js, 6.bundle.map 4.43 kB {0} {5} {2} {4} {3} {1} {7}
chunk    {7} main.bundle.js, main.bundle.map (main) 172 kB {9} [initial]
chunk    {8} styles.bundle.js, styles.bundle.map (styles) 9.72 kB {10} [initial]
chunk    {9} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial]
chunk   {10} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
webpack: Compiled successfully.
webpack: Compiling...                                            Hash: 2a5559aa5e7694288411                                                                                                                                                                             
Time: 359ms
chunk    {0} 0.chunk.js, 0.bundle.map 54 kB {7} {6} {5} {2} {4} {3} {1}
chunk    {1} 1.chunk.js, 1.bundle.map 22.1 kB {3} {4} {2} {5} {6} {0} {7}
chunk    {2} 2.chunk.js, 2.bundle.map 17.8 kB {5} {4} {3} {1} {6} {0} {7}
chunk    {3} 3.chunk.js, 3.bundle.map 4.62 kB {1} {4} {2} {5} {6} {0} {7}
chunk    {4} 4.chunk.js, 4.bundle.map 3.77 kB {2} {3} {1} {5} {6} {0} {7}
chunk    {5} 5.chunk.js, 5.bundle.map 4.43 kB {6} {2} {4} {3} {1} {0} {7}
chunk    {6} 6.chunk.js, 6.bundle.map 4.43 kB {0} {5} {2} {4} {3} {1} {7}
chunk    {7} main.bundle.js, main.bundle.map (main) 172 kB {9} [initial]
chunk    {8} styles.bundle.js, styles.bundle.map (styles) 9.72 kB {10} [initial]
chunk    {9} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial]
chunk   {10} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]
webpack: Compiled successfully.

**Comment by d3viant0ne** [comment] 2017-05-02 02:52
@chouhan - Questions regarding the angular-cli belong in whatever medium the have designated for support requests.

**Comment by chouhan** [comment] 2017-05-02 18:37
@d3viant0ne - I did not get you. Are you expecting me to rewrite the question in a proper format?

I am looking for a solution to the above issue posted.

**Comment by d3viant0ne** [comment] 2017-05-02 19:12
I'm not expecting you to rewrite the question, I am saying you are posting it in the wrong place.

Your question is related to the `angular-cli` of which webpack is a part but the right place to look for a solution related to `ng serve` is https://github.com/angular/angular-cli.

There is a ton of code on top of the cli's default webpack configuration that could be related to the output you are getting and considering you can't directly modify the cli's webpack configuration, this is an issue that will need to be handled by that team in whatever forum they have designated for support requests.

That said, first off I would get off of the `beta` build of the CLI and onto `@angular/cli@latest`. There were a significant number of performance improvements in the release candidates that may have a positive effect on the above which is exactly what they are going to tell you.

Secondly, don't mismatch the global cli version with the application cli version particularly with the beta builds. There are numerous resolved issues pre-final release caused by version mismatches.

Beyond those two things, you need to ask your question in the proper forum. i.e. the angular-cli repository.

**Comment by richardstirring44** [comment] 2025-02-08 03:40
> Could try to run uglifyjs on the output files? Maybe it's an uglifyjs bug...





https://angulardev.space/questions/optimizing-your-angular2-bundle-with-webpack-best-practices-for-minimizing-code-size
