### ISSUE TITLE
Wrong `this` reference

### ISSUE THREAD

**Issue by ipy** [webpack/webpack#2084] opened 2016-02-22 08:50 UTC
```
define(function (require, exports, module) {
	var Test = {
		test: function() {
			console.log(this); // print the Test object
			require([], function(){
				console.log(this); // print the global/window object
			}.bind(this));
		}
	};
	return Test;
});
```
```
require('./test').test();
```

As the above code, the `bind` operation to the amd require callback is useless. It prints the global context instead of the parameter passed to the `bind` function.
Tested in webpack 1.12.13 and 2.0.7-beta.

**Comment by micschro** [comment] 2016-02-22 14:56
This seems to be a serious problem, because not only does the `thisArg` binding
not work, but using a require callback like `require([],function(){}.bind(this))`
also causes webpack to ignore any nested requires:
```javascript
require([], function() {
  require([], function() {
  });
}.bind(this));
```  
is transformed like this:
```javascript
!/* require */(/* empty */function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = []; (function() {
  require([], function() {
  });
}.bind(this).apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}());
```
i.e., the nested require isn't "webpacked" at all.

Looking at the code in `AMDRequireDependenciesBlockParserPlugin.js`,
it seems like the AMD Plugin processes only require callbacks of type
"FunctionExpression":
```javascript
if(expr.arguments[1].type === "FunctionExpression") {
 ...
 this.walkStatement(expr.arguments[1].body);
}
```
However, if a bind expression is used, `expr.arguments[1].type` is actually a
"CallExpression". 

A possible workaround is to to create a local variable for `this`:
```javascript
var that = this;
require([], function() {
  that.foo();
});
```
But that means we would have to adapt a lot of code to make our project work with webpack,
which I think wouldn't go well with the basic idea of webpack.  

This might be a duplicate of #1234, but I think the fact that the bind expression 
causes nested `require`s to be ignored really aggravates the problem.

**Closed** 2016-02-22 17:47 UTC
Labels: bug

**Comment by micschro** [comment] 2016-02-22 18:04
Thank you very much for the fast fix!
I didn't try it yet, but looking at the changeset, it seems like it will fix `function(){}.bind(this)`,
but I suppose
```javascript
var foo = new Foo();
require([], function() {
  // this isn't foo
}.bind(foo));
```
still would not work, or would it?

**Comment by sokra** [comment] 2016-02-22 18:46
That works fine.
