### ISSUE TITLE
What is the lowest version of Node Webpack 2 is compatible with?

### ISSUE THREAD

**Issue by jpea-imvu** [webpack/webpack#4071] opened 2017-01-20 21:07 UTC
?

**Comment by sokra** [comment] 2017-01-20 21:41
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by sokra** 2017-01-20 21:41 UTC

**Comment by dmitriid** [comment] 2017-01-21 12:08
@sokra The entirety of the issue is in the issue title. What help would adhering to the template bring in this case?

@jpea-imvu minimum supported NodeJS version is now 4.3. Mentioned in passing in the [announcement](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.176peuf8o)

@TheLarkInn This is another reason why that blog post is not a release announcement ;)

**Comment by dmitriid** [comment] 2017-01-21 12:11
@sokra Here's how the question would look like in the template:

----

**Do you want to request a *feature* or report a *bug*?**

neither

**What is the current behavior?**

not relevant

**If the current behavior is a bug, please provide the steps to reproduce.**

not relevant

**What is the expected behavior?**

not relevant

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature request

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Not relevant


What is the lowest version of Node Webpack 2 is compatible with?

**Comment by halt-hammerzeit** [comment] 2017-01-27 21:00
Just look at the `engine` property of `package.json`

**Comment by TheLarkInn** [comment] 2017-01-27 22:09
Good opportunity for a first PR if you feel it might be better displayed on our readme.

**Comment by michael-ciniawsky** [comment] 2017-01-27 22:17
Will be displayed in the README correctly when webpack v2 is released under the latest tag, currently still pointing to `>=0.6` => webpack v1
