### ISSUE TITLE
How should we handle import.meta

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#6719] opened 2018-03-10 00:14 UTC
Hey, @sokra @ooflorent, @Kovensky @ljharb:

It looks like `import.meta` has landed in Stage 3 and [Babel has just landed it also](https://github.com/babel/proposals/issues/10). It looks like there is already an acorn plugin that allows for the syntax support. 

First piece is: Should we add this or wait? 

Second piece is: Are there webpack specific things we should consider for this syntax. I feel like platforms (Electron, etc.) are going to start shoving a bunch of crap (which use to be globals) in these objects that we would automatically _use_ to treat as Externals. Is there specific handlings that we need to be concerned here.

**Comment by Kovensky** [comment] 2018-03-10 00:54
I actually don't think `import.meta` will be that abused; at least I hope not.

It is mostly useful for things that are actually _not_ global but still need to exist in every module anyway; for example their own filename, or even the `require` function as it needs to be bound to the module's dirname.

In webpack's use case, it'd be useful to put `import.meta.hot` in it. AFAIK it's our only extension to the `module` object, which we could then remove from scope entirely. We could also put `import.meta.moduleId` there if that would be useful.

`__dirname` and `__filename` will not be available, instead there will be a per-module `import.meta.url`.

The problem is how to deal with them -- they have to be absolute URLs that are parseable by using the WHATWG URL constructor (`new URL(import.meta.url)` will throw if it's not absolute, with protocol scheme and all).

This could mean that, if `import.meta.url` is used by a bundled module, that we would be forced to always enable the `NamedModulesPlugin`, or maybe something even more drastic such as supporting `import()`s using a pseudo `webpack:` protocol.

We don't necessarily have to put `url` there, though; it's not part of the JS spec. We could just say it's something that's only available when the file is not bundled, and instead use some other key if modules really need to know their dirname.

**Comment by ljharb** [comment] 2018-03-10 01:14
I think that until node and all browsers have shipped it unflagged, webpack shouldn’t handle it. Users who want to use it early can use a custom babel transform for it - just like import()

**Comment by tilgovi** [comment] 2018-03-12 04:03
I just stumbled into `module` not being defined in an .mjs file, trying to use the HMR API. `import.meta` seems like a reasonable place for it.

**Comment by enjikaka** [comment] 2018-04-07 17:08
For my use case `import.meta` would be used to have clear isolation between HTML, CSS and JS in components;

```
components/
     fancy-button/
        fancy-button.js
        fancy-button.html
        fancy-button.css
```

Where fancy-button.js would do something like;

```
class extends HTMLElement {
    async connectedCallback () {
        const sDOM = this.attachShadow({ mode: 'closed });
        const cssText = await fetch(new URL('fancy-button.css', import.meta.url)).then(r => r.text());
        const rawMarkup = await fetch(new URL('fancy-button.html', import.meta.url)).then(r => r.text());
        this.sDOM.innerHTML = `
            <style>${cssText}</style>
            ${rawMarkup}
        `;
    }
}
```

Provided webpack would output this into a build folder keeping the component file structure intact (splitting chunks etc - still separate files, just the JS handled in webpack); I guess it would make sense for webpack to, in runtime, replace ` import.meta.url` when not available in running browser with a path to where webpack wrote the component? When bundling I assume it would be more problematic maybe. 🤔I guess this kinda overlaps with regular html/css imports in webpack, but as only importing JS is the modules spec maybe it makes sense that webpack has this behvaiour for import.meta.url?

**Comment by web-padawan** [comment] 2018-04-16 12:46
I'm working with the Polymer 3 preview and trying to use `import.meta.url` inside of the static property of the component like this:
```js
static get importPath() {
  return import.meta.url
}
```
The use case is to build the component which can detect whether it has been loaded from it's file (as it is performed by Polymer CLI when serving locally) or from a bundle (either Webpack or Rollup, etc). 

As a developer, I would expect the `import.meta.url` to contain a path ending with the filename (e. g. the name of the file where the component has been bundled into), and to be able to execute some logic depending on that, without having to rely on `process.env` stuff.

**Comment by ljharb** [comment] 2018-04-16 14:32
Since files can be loaded in the browser too, that doesn’t seem like a robust detection mechanism.

**Comment by jdalton** [comment] 2018-04-17 17:12
I think a good first step would be to support parsing it at least. There are [acorn plugins](https://github.com/acornjs/acorn#existing-plugins) for it.

**Comment by ljharb** [comment] 2018-04-18 01:36
It looks dual-licensed as that and Apache 2, so it’d be fine.

**Comment by Kovensky** [comment] 2018-04-18 01:42
It's dual-licensed with "and" so both licenses apply. But this is getting into lawyer territory 🤔

**Comment by ljharb** [comment] 2018-04-18 01:45
https://github.com/acornjs/acorn-import-meta/blob/master/package.json#L15 says “or”

**Comment by jdalton** [comment] 2018-04-18 01:52
\cc @adrianheine – there's more license concerns deviating from the MIT license of Acorn proper.

**Comment by adrianheine** [comment] 2018-04-18 06:41
Hi, if you want to use acorn-import-meta, you can choose under which license you want to use it. It is released under AGPLv3 _and_ Apache2, so you can choose the one _or_ the other :)

**Comment by rtsao** [comment] 2018-05-15 20:19
It would be nice to achieve consensus on how to use `import.meta` as a replacement for the current de facto standard of using [static (build-time) `process.env.NODE_ENV` checks](https://github.com/facebook/react/blob/1eed302d346bfb8f5db8d88b0e7096d8999d3548/packages/react-dom/npm/index.js#L31) for dead-code elimination of in-browser development-only code.

Are there any existing efforts to create such a proposal?

**Comment by web-padawan** [comment] 2018-06-13 13:57
@Kovensky Is there any progress on this? As of now, Webpack is still failing to parse `import.meta`:

```
Module parse failed: Unexpected token (145:21)
You may need an appropriate loader to handle this file type.
|       key: "importMeta",
|       get: function get() {
>         return import.meta;
|       }
|     }, {
```

This makes `import.meta` totally unusable and it seems rather strange for the spec draft moved to Stage 3 already last September.

**Comment by ooflorent** [comment] 2018-06-13 14:23
@web-padawan Only stage 4 features are currently supported (except dynamic imports). We are waiting for `import.meta` to stabilize in node and in browsers before implementing it.

**Comment by daKmoR** [comment] 2018-12-02 19:50
hey, we just released a "temporary" loader - e.g. until webpack supports it out of the box that is.
Take it for a spin and use `import.meta.url` today. Let us know if you find it's useful for you or if you encounter any bugs.
npm: https://www.npmjs.com/package/@open-wc/webpack
github: https://github.com/open-wc/open-wc/tree/master/packages/webpack

**Comment by manucorporat** [comment] 2019-04-18 11:37
Any update on this one? `import.meta` is already an important part of the platform and any dependency using it will make webpack automatically to crash.

Could at least update the webpack's parser to not crash?

**Comment by matthewp** [comment] 2019-05-08 18:29
I think at this point basing decisions on stage version isn't the best way to go.  `import.meta` is currently supported in Safari, Chrome, and Firefox. And in EdgeChromium. So we're at near 100% browser support. Unfortunately it seems that more goes into stage versions than just "stability", so its not the best signal.

**Comment by joeldenning** [comment] 2019-05-11 23:43
The SystemJS community would also enjoy seeing `import.meta` implemented, especially for webpack entry modules so that they can know from what URL they were downloaded from and dynamically set the public path accordingly. See https://github.com/systemjs/systemjs/issues/1939

Is there consensus on what `import.meta.url` would be for both entry modules and for all other modules? Since webpack modules are compiled down by the time they hit the browser, does it even make sense for any module except the entry module to be able to use `import.meta.url`?

**Comment by joeldenning** [comment] 2019-05-11 23:45
I would be happy to look into what it would take to PR this -- parsing import.meta and replacing with whatever value is decided on.

**Comment by rjgotten** [comment] 2019-07-05 11:50
> @joeldenning 
> does it even make sense for any module except the entry module to be able to use `import.meta.url`?

Yes, it does. E.g. in cases where code may want to perform XmlHttpRequest or fetch relative to a module's build-time location. In other cases, you may want it for logging purposes.

------

In a broader sense; `import.meta` is _intentionally extensible_ and platforms are expected to leverage it for platform-specific conveniences.

One such convenience may be the ability to register per-module runtime configuration in a curated manner. RequireJS and AMD accomplish this by importing the special `"module"` meta-module and pulling up runtime configuration for that one module using `module.config()` from a central configuration registry set up through one or more preceding `require.config()` calls.

Webpack doesn't have anything in the sense of externalized runtime-accessed configuration. With `import.meta` there's a standardized extension point where you can add a `config()` method or `config` getter property and make that happen.

**Comment by rjgotten** [comment] 2019-07-09 17:52
> @web-padawan 
> As a developer, I would expect the `import.meta.url` to contain a path ending with the filename (e. g. the name of the file where the component has been bundled into)

As Webpack transpiles ES modules into bundles, shouldn't the expectation be that `import.meta.url` represents what the module's URL would have been had it been loaded as an actual separate ES module?

I.e. using the Webpack public path and output path to assemble a root-relative URL and then add the relative _development_ location of the file, that is: starting from the root context?

I.e. in pseudocode:
```
import.meta.url := publicPath + outputPath + path.relative(rootContext, resource)
```

**Comment by ljharb** [comment] 2019-07-09 17:56
Only if that url resolves - otherwise people might try `import(import.meta.url)`, directly or indirectly, and expect it to work.

**Comment by rjgotten** [comment] 2019-07-09 18:04
> people might try `import(import.meta.url)`

Ooh; inception-y. :-)

**Comment by Pauan** [comment] 2019-07-09 18:11
@ljharb Since `import.meta.url` is scoped per module (just like `import()`), and since Webpack knows what `import.meta.url` is, it can in fact make `import(import.meta.url)` work.

It wouldn't even be difficult, since `import.meta.url` is just a constant. And even things like `import(import.meta.url + "/foo")` would work, since Webpack has support for that.

**Comment by ljharb** [comment] 2019-07-09 18:22
@Pauan `export const url = import.meta.url` and in another module, importing it and passing it into `import()`? If that works, great.

**Comment by Pauan** [comment] 2019-07-09 18:27
@ljharb No, it doesn't. Webpack disallows dynamic imports like that.

Not just `import.meta.url`, but [*any* sort of `import(foo)` is disallowed at compile time](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import).

Therefore, if you use `import.meta.url` in a static way, it will work. If you use it in a fully dynamic way, you will get a compile-time error. So there's no problem, everything is consistent with the way Webpack handles `import()`.

**Comment by tilgovi** [comment] 2019-10-26 17:15
`import.meta.url` is not quite constant, because I would expect it to be based on the public path, which may be set dynamically by `__webpack_public_path__`. I could see that being implemented by injecting a module-level, read-only, property to access the correct value at runtime, but it would not then be possible to use it in `import.meta.url`.

However, I think we may be missing something important here. If someone wants to use `import.meta.url` as part of a dynamic `import()` statement, they maybe don't want it to be transformed to a chunk reference. If the code is written to use the runtime value of `import.meta.url` then it probably makes sense to do a runtime dynamic `import()`.

Taking those things together, if `import.meta.url` were made into a getter accessible within a module, it would not be possible to use it in a compile-time `import()`, but could still be possible to use it in an `import( /* webpackIgnore: true */ )`.

**Comment by tilgovi** [comment] 2019-10-26 17:16
> import.meta.url is not quite constant, because I would expect it to be based on the public path, which may be set dynamically by __webpack_public_path__. I could see that being implemented by injecting a module-level, read-only, property to access the correct value at runtime, but it would not then be possible to use it in import.meta.url.

On the other hand, what even is the URL of a module that is part of a bundle? Maybe it doesn't make sense to support it.

**Comment by tilgovi** [comment] 2019-10-26 17:17
> On the other hand, what even is the URL of a module that is part of a bundle? Maybe it doesn't make sense to support it.

Or perhaps only support it for entry points.

**Comment by rjgotten** [comment] 2019-10-28 07:55
>On the other hand, what even is the URL of a module that is part of a bundle?

Its original path. Webpack is a compilation step and should endeavour not to change *meaning* of code - i.e. semantics. In that sense `import.meta.url` for webpack-ed code should reflect the original paths rooted at whatever was the compilation root.

Mapping the compilation root to the runtime location, that's what `publicPath` is for.

**Comment by web-padawan** [comment] 2019-10-28 08:23
See also [webpack-import-meta-loader](https://github.com/open-wc/open-wc/blob/master/packages/webpack-import-meta-loader/webpack-import-meta-loader.js) which converts `import.meta.url` to the following: `${window.location.protocol}//${window.location.host}/relative/path/to/file.js`

Note: this is the same as posted above by @daKmoR (updated link to the correct location).

**Comment by jkrems** [comment] 2020-02-04 05:02
> In webpack's use case, it'd be useful to put import.meta.hot in it.

After some experiments with "native ESM code that could be enhanced by webpack", I think it would be better to reverse this. E.g. something like `__HOT__(import.meta)` could be compiled away but would also be valid ESM code that could reasonably run on its own. I have an example here: https://github.com/jkrems/embracejs/blob/7232ca46ea7d436707da35a7f2c1837020d60e3d/examples/hot-reload/static/model.mjs. In a perfect world the hot API could even be a normal package consumed like others..?

**Comment by sokra** [comment] 2020-02-04 10:39
`__HOT__(import.meta)` would crash in a bundler/native which doesn't support HMR. `__HOT__` would be unknown and throw a ReferenceError.

So you probably have to write code like:

``` js
if(typeof __HOT__ !== "undefined) {
  __HOT__(import.meta).accept();
}
```

---

In the code you linked you are using a different HMR API, compared to what bundler currently use. The current HMR API doesn't seem to be easily polyfillable without rewriting source code in a preprocessing step. Any preprocess step could rewrite `import.meta.hot` too.

A new HMR API which can be used with native ESM might be a idea, but I don't have a good idea how this could be, without having serve limitations like number and names of exports can't be changed, boilerplate code for each module needed, etc. If I would implement something like that, it would be a preprocessing step which rewrites module code on server-side. Server-side is needed anyway for watching and signaling.

**Comment by dcleao** [comment] 2020-03-07 00:42
Would it make sense for the `import.meta.url` of each module contained in a bundle to be:

  `my/bundle/url.js#relative/path/to/file.js`

In a way this makes sense to me, as there is a parallel with anchors for HTML documents referring to the id of a contained element.

**Comment by rjgotten** [comment] 2020-03-07 20:14
@dcleao your idea seems nice, but it makes me worry a bit about URL encoding.

The original module URL may already contain a fragment identifier and with this patter you'd end up with something that has two.

Technically, this is correct, as splitting the URL should be done by treating everything after the _first_ `#` as the fragment identifier, which is the entire original URL, including an optional secondary `#` delimiter and fragment identifier, so you wouldn't strictly need to encode the second `#`.

But how many developers will know that and expect it to not be encoded?
Or the dual of that problem: if Webpack decides to encode a secondary `#` anyway; how many developers that _do_ know it is not necessary - will _mistakingly_ apply that knowledge and fail to decode it. 

I.e. it seems like one of those double-encoding/-decoding hazards waiting to happen. 

So maybe just cop out and offer some webpack-specific properties on `import.meta` as well, to avoid consumers having to deconstruct the full thing and get the parsing/decoding wrong.

E.g.

```
import.meta.url // -> "my/bundle/url.js#relative/path/to/file.js"
import.meta.webpack.bundle // -> "my/bundle/url.js"
import.meta.webpack.resource // -> "relative/path/to/file.js"
```

Technically that should be fine, as `import.meta` is afaik allowed to contain platform-specific extensions.

**Comment by web-padawan** [comment] 2020-07-22 12:33
This appears to be addressed by #11075 and available since `v5.0.0-beta.21`

**Comment by hsablonniere** [comment] 2020-07-22 12:34
Crossing fingers for a backport to v4 ;-)

**Comment by evilebottnawi** [comment] 2020-07-22 12:59
@hsablonniere unfortunately no backport, a lot of stuff require to rewrite

**Closed** 2020-07-26 20:57 UTC

**Comment by hsablonniere** [comment] 2020-08-06 22:10
@evilebottnawi fair enough 😉

**Comment by kaleidawave** [comment] 2020-10-16 15:18
Is there anyway to prevent webpack injecting to `import.meta.url` ??? Trying to dynamically fetch a required asset:

```ts
fetch(join(dirname(import.meta.url), "bundle/x.txt"))
```

Webpack compiles it to: 

```ts
typeof window?fetch((0,e.join)((0,e.dirname)("file:///C:/Users/......./src/index.ts"),"bundle/x.txt"))
```

 _(I swapped part of the path with `....`)_

Which is completely useless. I don't know where this code is held so I can't compile away `import.meta.url` I only know that static asset `x.txt` will always be in the adjacent folder. I just want to leave it there untampered. Is it webpack or ts-loaded doing this???

**Comment by evilebottnawi** [comment] 2020-10-16 15:30
No, it is expected, don't mix node and browser code

**Comment by joeldenning** [comment] 2020-10-16 15:34
@kaleidawave you may be interested in using `__webpack_public_path__` in your code, instead of `import.meta.url`. The webpack public path is similar to the browser implementation of `import.meta.url`. See https://webpack.js.org/guides/public-path/#root

**Comment by kaleidawave** [comment] 2020-10-16 15:51
@joeldenning Okay, but would that variable need to be set manually by everyone who uses the library...? 

@evilebottnawi ok true but the problem is that 99% of this lib is **not** environment specific. There is ~2 sections (quite high up the call stack) that need to make fs calls. My current thinking is that at this point can split whether `window` is defined. The following should work if webpack doesn't change `import.meta.url`

```ts
/// <reference lib="dom"/>
import { join, dirname } from "path";

if (typeof window !== "undefined") {
    // @ts-ignore ts does not like during node compiliation `import.meta.url` 
    fetch(join(dirname(import.meta.url), "/bundle/x.txt"))
        .then(x => x.text())
        .then(x => console.log(x));
} else {
    console.log(require("fs").readFileSync(join(__dirname, "/bundle/x.txt")).toString());
}
```

Creating a branch of the library to not rely on fs calls is not possible. A solution would be to send down a function down that handles fs access and have separate web and node entry point where that function argument is different....? But I want to know why `import.meta.url` is compiled away as [according to mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) it seems pretty dynamic....?

**Comment by evilebottnawi** [comment] 2020-10-16 15:56
`import.meta.url` woks according spec

**Comment by Pauan** [comment] 2020-10-16 15:57
@kaleidawave If you're making a library, you generally won't compile it with Webpack. Your library will just use regular ES6 modules + dynamic `import()` + `import.meta.url`, and you leave it up to the application to use Webpack (or Rollup, or Browserify, or...)

The reason why `import.meta.url` is compiled is because *all* ES6 modules (including dynamic `import()`) are compiled by Webpack, because this is necessary in order to compile ES6 -> ES5.

It would help if you explained more what your goal is, so we can help you achieve that goal (rather than getting stuck on a particular implementation).

**Comment by joeldenning** [comment] 2020-10-16 16:06
> Okay, but would that variable need to be set manually by everyone who uses the library...?

Libraries are generally not compiled by webpack, and generally there is no good way to guarantee that runtime assets will be downloaded from the correct URL when publishing a webpack library.

**Comment by kaleidawave** [comment] 2020-10-16 16:09
Interesting, looks like webpack isn't for this project....

@evilebottnawi I would counter that:

Say I have `/src/index.js`:

```js
console.log(import.meta.url)
```

And its webpack'd to `/out/index.js`. Then take some html file not compiled by webpack

```html
<script type="module" src="/src/index.js?hello='x'"></script>
<script type="module" src="/out/index.js?hello='x'"></script>
```

Will log this:

```
> http://127.0.0.1:8080/src/index.js?hello=%27x%27
> file:///C:/Users/.../src/index.js
```

Unless I making the mistake that a webpack output is not to be used with non webpacked'd assets (as I need it to be) then it is not inline with the spec...

**Comment by Pauan** [comment] 2020-10-16 16:16
@kaleidawave The point of Webpack is that all of your code is compiled with Webpack. It needs complete knowledge of all your code in order to compile the modules correctly. That's why the application is supposed to use Webpack, not libraries.

It sounds like you're misunderstanding what Webpack does. Webpack is intended to take all of your ES6 modules and bundle them up into a single file (I'm leaving out some details about chunks, but that's the general idea).

Webpack does not generate ES6 modules, Webpack generates raw ES5 code. So you don't use Webpack with `<script type="module">`, and you're not supposed to mix the compiled Webpack code with source code (unless they are completely separate).

Like I said, it would help if you explained what your goal is, so we can help you to achieve it.

**Comment by evilebottnawi** [comment] 2020-10-16 16:22
> Webpack does not generate ES6 modules, Webpack generates raw ES5 code. 

We are working on it :smile:

**Comment by sokra** [comment] 2020-10-16 18:04
We recently added this syntax: `new URL("bundle/x.js", import.meta.url)` to reference assets. x.js will be copied into the output directory and webpack will generate code that will create an valid URL to that asset at runtime (using public path and the base URL).
Maybe this is something useful for your case.

Using `import.meta.url` on its own isn't that useful as it's unclear what the meaning should be: URL of the bundle or URL of the module. Since the individual modules doesn't exist anymore at runtime and there are usually multiple bundles we decided to go with the module URL.

**Comment by rjgotten** [comment] 2020-10-16 22:28
> @sokra
> Using `import.meta.url` on its own isn't that useful as it's unclear what the meaning should be: URL of the bundle or URL of the module.

There's nothing unclear there. Read the spec. It's supposed to be the runtime base URL from which the module was loaded:

https://html.spec.whatwg.org/multipage/webappapis.html#hostgetimportmetaproperties
https://html.spec.whatwg.org/multipage/webappapis.html#concept-script-base-url

Anything else is wrong.

As I mentioned further back in this thread, the correct solution would've been to put webpack specific properties onto `import.meta` (which the spec _allows_ !!) and then offer an `import.meta.url`that uses a hash fragment to separate the bundle URL and the module identifier:

```js
import.meta.url // -> "my/bundle/url.js#relative/path/to/file.js"
import.meta.webpack.bundle // -> "my/bundle/url.js"
import.meta.webpack.resource // -> "relative/path/to/file.js"
```

**Comment by Pauan** [comment] 2020-10-17 07:09
@rjgotten You are confusing the bundle with modules. The bundle is not an ES6 module. `import.meta.url` must always refer to the current module, so it is incorrect to have it refer to the bundle.

In addition, that would create fragmentation within the ecosystem. Right now Webpack uses standard ES6 modules, standard ES6 dynamic `import()`, and standard `import.meta.url`. That means you can take ES6 code and run it directly in the browser, *or* you can compile it with Webpack and it will work correctly either way.

With your proposal, now there would be a difference in behavior with `import.meta.url` when it is used in Webpack (compared to running directly in the browser), which would break things and create a split between browser code and Webpack code.

So it would have to be the other way around: `import.meta.url` is always the module URL. And then Webpack could add a new `import.meta.webpack.bundle` which would point to the bundle file.

**Comment by rjgotten** [comment] 2020-10-17 13:55
>With your proposal, now there would be a difference in behavior with import.meta.url when it is used in Webpack (compared to running directly in the browser)

That difference is already there considering @kaleidawave showing that Webpack emits a `file://` protocl url for `import.meta.url` which makes even less sense. Might as well emit the custom `webpack://` protocol used for source maps at that point, which atleast offers some modicum of 'closed environment' internal consistency.

**Comment by evilebottnawi** [comment] 2020-10-17 14:15
> import.meta.webpack

Where is it in the specification? :smile: 

@rjgotten What is the your problem, please stop arguing and show your problem

**Comment by Pauan** [comment] 2020-10-17 14:20
@rjgotten Wrong. It is a syntax error to use `import.meta.url` in a script. Try it yourself in the browser if you don't believe me. Bundles are not the same as modules, period. It is simply incorrect to treat them as modules.

> That difference is already there considering @kaleidawave showing that Webpack emits a file:// protocol url for import.meta.url which makes even less sense.

That is because they are not compiling their entire code with Webpack (which is incorrect). When *all* of the code and assets are compiled with Webpack (as it should), then using `import.meta.url` works the same. With your proposal `import.meta.url` would *never* work the same, ever.

> Might as well emit the custom webpack:// protocol used for source maps at that point, which at least offers some modicum of 'closed environment' internal consistency.

That may be a good idea, perhaps @sokra could explain the reasoning for using `file://`. But it's somewhat irrelevant, since the assets and URLs are handled internally by Webpack, so it doesn't matter what the URL or protocol is.

**Comment by evilebottnawi** [comment] 2020-10-17 14:46
> That may be a good idea, perhaps @sokra could explain the reasoning for using file://. But it's somewhat irrelevant, since the assets and URLs are handled internally by Webpack, so it doesn't matter what the URL or protocol is.

Yep, also we support `file://` protocol, you can use it in code, so we used it

**Comment by sokra** [comment] 2020-10-17 17:41
The spec says

> the URL from which the script was obtained

And thats exactly what we return. The module was obtained from the filesystem. That's where it's located.

The bundle is a kind of transport format.

Webpack also supports `import("file://...")`, so this is consistent with `import.meta.url`, e.g. you can do `import(import.meta.url + "/../other.js")` (please don't do that).

It also makes sense for `console.error("error in " + import.meta.url)`. For other scenarios it doesn't make sense. I don't think there is a solution that makes everybody happy. We had similar discussions with `__filename`.

Webpack tries it's best to map urls to there public counterpart if some exist. E.g. assets have a public URL and we use it. JS modules are bundled so they don't have a public counterpart.

**Comment by alex-shamshurin** [comment] 2021-03-11 13:17
We can handle with `import.meta` with this babel plugin
```
function () {
      return {
        visitor: {
          MetaProperty(path) {
            path.replaceWithSourceString('process')
          },
        },
      }
    },
```

**Comment by echofriend** [comment] 2021-07-11 00:19
Webpack team,
Your import.meta support has issues.
Following your instructions to import web workers as per your documentation "https://webpack.js.org/guides/web-workers/#example" is not working for me.

The moment I add this line "const worker = new Worker(new URL('./myworker.js', import.meta.url));", I get this error on webpack-cli    :    "Critical dependency: Accessing import.meta directly is unsupported (only property access is supported)"

The whole js fails to work. Please fix this if its a bug.

**Comment by alexander-akait** [comment] 2021-07-12 09:41
@echofriend Please provide reproducible example
