### ISSUE TITLE
Typo in dependencies results in a undescriptive error message

### ISSUE THREAD

**Issue by nemtsov** [webpack/webpack#5414] opened 2017-07-31 18:55 UTC
This is a bug report in webpack 3.4.1 (and webpack@beta).

**What is the current behavior?**
In the [following gist](https://gist.github.com/nemtsov/b1df26c3ed6025879590e34c399f9f2a) there are two configs, one depending on another. If you provide an incorrect dependency name, the error message is `Cannot read property 'hash' of null`, which does not describe the root cause of the issue and makes it difficult to debug.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/nemtsov/b1df26c3ed6025879590e34c399f9f2a

**What is the expected behavior?**

An error message that describes the root cause, e.g., `Undefined dependency "commonBAD" in "build/a.js"`

**Comment by sokra** [comment] 2017-07-31 21:14
Yep send a PR.

**Comment by ssuman** [comment] 2017-07-31 21:52
I would like to work on this PR.

**Comment by TheLarkInn** [comment] 2017-08-03 05:02
@ssuman by all means feel free to do so!!!!!

**Comment by dericcain** [comment] 2017-08-09 21:55
@ssuman Are you going to tackle this? If not, I'll jump on it.

**Comment by ssuman** [comment] 2017-08-10 20:57
@dericcain please go ahead

**Comment by dericcain** [comment] 2017-08-11 01:11
@TheLarkInn I've been digging around and I don't really see where I should start. Any hints?

p.s. This is labeled as `My First Commit` so my Imposter Syndrome is really kickin' in 😨

**Comment by JLHwung** [comment] 2017-08-22 05:53
I can not reproduce the error on webpack 3.5.5, actually it does not complain even if I delete the `dependencies` property.

@nemtsov If this can be reproduced on your environments with latest webpack, could you print the stack trace of `Cannot read property 'hash' of null`? It would greatly help us narrow down the issues.

Besides, I could not find any introduction of `dependencies` on https://webpack.js.org/configuration/. @TheLarkInn Could you explain us the usage?

We use dll-plugin on a large project without `dependencies` settings and it works well.

**Comment by nemtsov** [comment] 2017-08-31 14:36
I just tried it with webpack 3.5.5 and get the same error. I updated the gist above with clarifications. Here's the stack that I get when I run with `--verbose`:

```
➜  webpack_test ./node_modules/.bin/webpack --version
3.5.5

➜  webpack_test ./node_modules/.bin/webpack --verbose
/usr/local/src/webpack_test/node_modules/webpack/lib/MultiStats.js:14
		this.hash = stats.map(stat => stat.hash).join("");
		                                  ^

TypeError: Cannot read property 'hash' of null
    at MultiStats.hash.stats.map.stat (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiStats.js:14:37)
    at Array.map (<anonymous>)
    at new MultiStats (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiStats.js:14:21)
    at runWithDependencies (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiCompiler.js:154:19)
    at /usr/local/src/webpack_test/node_modules/async/dist/async.js:1074:9
    at /usr/local/src/webpack_test/node_modules/async/dist/async.js:421:16
    at eachOfArrayLike (/usr/local/src/webpack_test/node_modules/async/dist/async.js:991:9)
    at eachOf (/usr/local/src/webpack_test/node_modules/async/dist/async.js:1051:5)
    at _asyncMap (/usr/local/src/webpack_test/node_modules/async/dist/async.js:1067:5)
    at Object.map (/usr/local/src/webpack_test/node_modules/async/dist/async.js:1056:16)
    at runCompilers (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiCompiler.js:97:13)
    at MultiCompiler.runWithDependencies (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiCompiler.js:105:3)
    at MultiCompiler.run (/usr/local/src/webpack_test/node_modules/webpack/lib/MultiCompiler.js:145:8)
    at processOptions (/usr/local/src/webpack_test/node_modules/webpack/bin/webpack.js:383:13)
    at yargs.parse (/usr/local/src/webpack_test/node_modules/webpack/bin/webpack.js:387:2)
    at Object.Yargs.self.parse (/usr/local/src/webpack_test/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/usr/local/src/webpack_test/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by peerhenry** [comment] 2017-09-20 10:14
It says "No one assigned" but it looks like rrharvey is working on this? #5651

**Comment by davidfurlong** [comment] 2017-10-15 18:28
is this error message always a result of a missing dependency? Just got it and am trying to debug

**Comment by sokra** [comment] 2017-10-16 08:27
closed by

**Closed** 2017-10-16 08:28 UTC
Labels: bug, D0: My First Commit (Contrib. Difficulty), D1: Easy (Contrib. Difficulty), D2: Medium (Contrib. Difficulty), P3: Important, S1: Confusing, webpack-3, X5: work required (PR / Help Wanted)

**Comment by jakelauer** [comment] 2018-04-10 15:38
@davidfurlong Did you manage to figure your situation out? I'm running into it as well.

**Comment by davidfurlong** [comment] 2018-04-10 16:54
> @davidfurlong Did you manage to figure your situation out? I'm running into it as well.

I have no idea anymore, sorry :/ Guess it was resolved somehow
