### ISSUE TITLE
updating to version 1.8.10 causes new error in CommonsChunkPlugin

### ISSUE THREAD

**Issue by bdefore** [webpack/webpack#1016] opened 2015-04-27 23:05 UTC
Version 1.8.9 succeeds but when updating to 1.8.10 I get an error:

```
ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk
```

The bundle js is not output.

My build output from deploying to Heroku (this error is on line 514):
https://gist.github.com/bdefore/838bbe5be65dcb114014

**Comment by sokra** [comment] 2015-04-28 10:33
This indicates a wrong configuration.

**Comment by dimsmol** [comment] 2015-04-28 14:49
But even [Explicit vendor chunk](http://webpack.github.io/docs/list-of-plugins.html#2-explicit-vendor-chunk) example from documentation is broken by [this change](https://github.com/webpack/webpack/commit/84b34151da63c18021ae7b6fdfacf12a8c9ec08b#diff-1f5e5440c51d8accc603eb6f399cf08b)

So, it's indeed either a bug or at least backward-incompatible change.

Anyway, what can we use as a workaround?
Adding `children: true` seems to work, but is it correct solution?

**Comment by sokra** [comment] 2015-04-28 15:00
It's not broken:

I added it to the examples in the repo:
https://github.com/webpack/webpack/commit/300ee8db48da55ce20e4a06629330f97d33005e4
https://github.com/webpack/webpack/tree/master/examples/explicit-vendor-chunk

**Comment by bdefore** [comment] 2015-04-28 15:20
Previously I was sending two parameters to CommonsChunkPlugin. Has this changed to one object parameter? If so, what is the API for that? I tried changing it to specifying a single object with `name` and `minChunks` properties but the error still occurs. 

Here's my full configuration object, in case it helps: https://gist.github.com/bdefore/ccc0fe63309e9ff8d11d

**Comment by sokra** [comment] 2015-04-28 15:24
yep. You configuration is wrong. Either remove the `CommonsChunkPlugin` for `app` or use `children: true` for it.

**Comment by dimsmol** [comment] 2015-04-29 10:06
> It's not broken.
> I added it to the examples in the repo:

You're right, sorry.

But it becomes broken if I add second vendor entry like this:

```js
var path = require("path");
var CommonsChunkPlugin = require("../../lib/optimize/CommonsChunkPlugin");
module.exports = {
	entry: {
		vendor: "./vendor",
		vendor1: "./vendor1",
		pageA: "./pageA",
		pageB: "./pageB",
		pageC: "./pageC"
	},
	output: {
		path: path.join(__dirname, "js"),
		filename: "[name].js"
	},
	plugins: [
		new CommonsChunkPlugin({
			name: "vendor",
			minChunks: Infinity
		}),
		new CommonsChunkPlugin({
			name: "vendor1",
			minChunks: Infinity
		})
	]
}
// says:
// ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk
```

What I'm trying to achieve is to split my vendor libs into several entries for caching reasons (some of them are getting changed much more often than others). Also different sets of my pages may need different vendor libs.

How to do it right?

PS It looks like using `children: true` don't do what I want.

PPS
```js
		new CommonsChunkPlugin({
			file: "vendor.js",
			chunks: ["vendor"]
		}),
		new CommonsChunkPlugin({
			file: "vendor1.js",
			chunks: ["vendor1"]
		})
```

Doesn't work as well - it extracts webpack bootstrap from both vendor files to additional chunk, making them unusable.

PPPS Tried to start from [Multiple Commons Chunks](https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks) example, which uses old-style syntax. It gave me other results, but not what I need anyway.

**Comment by dimsmol** [comment] 2015-04-29 10:42
> It's not broken.

You're right, sorry.
I had a modified version with several `CommonsChunkPlugin`s.

**Comment by sokra** [comment] 2015-04-29 10:51
I added a shorthand syntax for multiple CommonsChunkPlugins with 1.8.11:

https://github.com/webpack/webpack/tree/master/examples/two-explicit-vendor-chunks

**Comment by dimsmol** [comment] 2015-04-29 10:52
> I added a shorthand syntax for multiple CommonsChunkPlugins with 1.8.11

Great, thanks! )

**Comment by nerdgrass** [comment] 2015-05-03 19:00
So I'm getting the same error, but everything still works. My goals are somewhat different - I'm trying to get the common bundle into a directory for js in the build folder. I have the following config:
```
entry: {
  article_editor: './src/article-editor/app.js'
 },
output: {
  path: path.join(__dirname, "./dist/article-editor"),
  filename: 'js/[name].bundle.js',
 ...
},
plugins: [
    new webpack.optimize.CommonsChunkPlugin('js/common.bundle.js'),
  ...
],
```
I originally had the JS directory in the output path, but I needed to move that in order to get my sass to compile in a folder other than `/js`. So I moved it to the output filename and it worked for the page-specific JS, but not the common js. So I added it in `CommonsChunkPlugin('js/common.bundle.js')` and this works, but throws the error mentioned here: 'ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk (js/common.bundle.js)'

Seems pretty straightforward, but I'm not sure what the solution is (should I just change modes?) or if I'm just doing this terribly wrong. Pretty new to webpack, sincere apologies if I've missed an obvious answer somewhere.

**Comment by sokra** [comment] 2015-05-03 19:16
@nerdgrass Could I see the remaining plugins? Your use case is equal to the [multiple-entry-points example](https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points#webpackconfigjs), which works fine.

The error is thrown when the commons chunks already exists and is not an entry chunk, i. e. when it's an additional chunk or already affected by another CommonsChunkPlugin.

**Comment by nerdgrass** [comment] 2015-05-04 00:18
here's my config:
```
var configuration = {
  entry: {
    article_editor: './src/article-editor/app.js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ["babel-loader"],
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract("style-loader", sassLoaders.join("!")),
      },
    ]
  },
  output: {
    path: path.join(__dirname, "./dist/article-editor"),
    publicPath: 'dist/article-editor/index.html',
    filename: 'js/[name].bundle.js',
    chunkFilename: '[id].chunk.js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('js/common.bundle.js'),
    new ExtractTextPlugin("./css/[name].css"),
  ],
  resolve: {
    root: path.join(__dirname, 'js'),
    extensions: ["", ".js", ".scss"],
    modulesDirectories: ["src", "node_modules"],
  }
};
```

Eventually, there will be multiple entry points (multiple client-side apps in the same repo with shared components), for now its just `article-editor`. The error goes away when I remove the `js/` from `js/common.bundle.js`, weirdly enough. 

And thanks for the example, that's actually what I based this on. The documentation for webpack is pretty extensive and useful :)

**Comment by sokra** [comment] 2015-05-11 15:13
See new extract-text-webpack-plugin version.

**Comment by DelvarWorld** [comment] 2015-09-07 23:48
I'm getting this too, and can't figure out what the problem is.

config:

    entry: {
        app: './app/main.js',
        vendor: './app/vendor/vendor.js',
        editor: './app/vendor/editor.js',
        home: './app/vendor/homepage.js'
    },
    ...
    plugins: [
        new webpack.optimize.CommonsChunkPlugin( 'common.bundle.js' ),

Error:

    ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk (common.bundle.js)

I `require('./common');` in all of the entry point files listed above. I still get the error.

**Comment by DelvarWorld** [comment] 2015-09-08 00:01
Ok, that error was because I was using an older version of `extract-text-webpack-plugin`, 0.6.0. Upgrading to 0.8.2 "fixed" it. However, my common bundle *only* has the webpack boilerplate in it. This process is very hard to debug because it's not obvious what causes what problems or what behavior. The undocumented syntax for `CommonsChunkPlugin` doesn't help.

**Comment by DelvarWorld** [comment] 2015-09-08 00:57
Ah, so this is entirely undocumented and confusing, it's because `minChunks` default is the *total* number of entry points you have, so if you don't require files in *every* entry point file, it won't get extracted to to the commons chunk. I don't see any reason why the default shouldn't be 2?

**Comment by kawing-chiu** [comment] 2015-12-26 16:22
@sokra  Hi, I'm trying to combine the [two-explicit-vendor-trunk](https://github.com/webpack/webpack/tree/master/examples/two-explicit-vendor-chunks) example with code splitting. But cannot make it to work.

I have two pages:

* / : needs only `vendor.js`
* /d3 : needs both `vendor.js` and `d3.js`

The goal is: when visiting /, only `app.js` and `vendor.js` are loaded. When the user navigates to /d3, `d3.js` is loaded as needed. Here is how I try:

[webpack](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/webpack_config/webpack.dev.config.js) [config](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/webpack_config/common.config.js):
```
entry: { 
  vendor: [ 
    'react',
    'react-dom',
    'react-router',
    ...
  ],
  d3: [ 
    'd3',
  ],
  app: [
      './src/js/index',
  ],
},
plugins: [ 
  new webpack.optimize.CommonsChunkPlugin({
    names: ['d3', 'vendor'],
    minChunks: Infinity,
  }),
  ...
],
```
[Router.jsx](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/src/js/Router.jsx) (I'm using react-router):
```
export default (
  <Router history={createBrowserHistory()}>
      ...
      <Route path="d3" getComponent={(location, callback) => {
        require.ensure([], (require) => {
          callback(null, require('./pages/D3'));
        });
      }} />
      ...
  </Router>
);
```
So how can I make it to work? I need this configuration because d3 is too large, and I need to do long-term cache on both `vendor.js` and `d3.js`.

**Comment by antoniomercado** [comment] 2016-02-09 21:52
As I've learned the hard way, order matters when defining your vendor chunks in the CommonsChunkPlugin. for example...
```
{
   entry: {
		"vendor1": [
			"jquery", 
			"lodash"
		],
		"vendor2" : [
			"angular"
		],
		"bundle": "./src/app.js"
	},
  plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			names: ["vendor2", "vendor1"],
                        minChunks: Infinity
		}),
		new HtmlWebpackPlugin({
			title: 'My App Title',
			template: 'index.html',
			favicon: './assets/images/favicon.ico',
			inject: 'body',
			chunks: [
				"vendor1",
				"vendor2",
				"bundle"
			]
		})
	]
}
```

This configuration works. Notice how in the `new webpack.optimize.CommonsChunkPlugin` invocation the vendor chunks are in reverse order. If i swap them I get errors in my resulting index.html 
Seems like a bug in the CommonsChunkPlugin internals. Thoughts?

**Comment by bbottema** [comment] 2016-02-15 21:51
@antoniomercado Thank you so much for sharing this, I was splitting my head over this. Have had any new insights into managing this properly?

**Comment by antoniomercado** [comment] 2016-02-15 22:05
@bbottema I ended up scrapping the idea of splitting up the vendor chunks because I had a `webpack.config.production.js` which had slight variations of this config and even with this "trick" i couldn't get it to sort properly, so i said screw it! Currently I just have one vendor file that I'm packing everything into. I will for sure need to revisit this sometime in the near future because the vendor file is becoming quite large. If anyone else has any insights into this issue or if anyone can post examples of their configs with split up vendor files that would be greatly appreciated.

**Comment by ace-han** [comment] 2016-02-17 02:38
@antoniomercado Thanks a million!!!

Reversing the order of the chunks will do the trick.

**Comment by johnnyreilly** [comment] 2016-02-18 16:24
Having to reverse the order makes this very confusing...

**Comment by evisong** [comment] 2016-05-18 08:21
I have 4 common trunks output. Writing into the single one CommonChunkPlugin instance is the right solution. Yes, the order matters, just like loader chain, the order should be reversed: 

      new webpack.optimize.CommonsChunkPlugin({
        names: ['libScoped', 'lib', 'polyfills', 'vendor'], 
        minChunks: Infinity,
        filename: `../${LIB_DEST}/[name].js?[hash]`
      }),

**Comment by webtrix** [comment] 2016-06-15 09:39
@antoniomercado thanks so much!! Have been searching for a solution for hours...

Don't really understand why Webpack doesn't mention this in the docs or something, because it's not logical to have to reverse the order of the chunks to get the result that you want.

Anyhow.. got finally working now

**Comment by sdhhqb** [comment] 2016-07-28 05:46
@antoniomercado  thanks a lot!!!

In case anyone met the same situation. Don't forget to set output config like this.
```
output: {
	path: './build/',
	filename: '[name].js',
},
```
According to the docs. [output.filename](http://webpack.github.io/docs/configuration.html#output-filename).

> multiple entries
> 
> If your configuration creates more than a single “chunk” (as with multiple entry points or when using plugins like CommonsChunkPlugin), you should use substitutions below to ensure that each file has a unique name.

**Comment by vdh** [comment] 2016-09-23 05:25
So through a lot of trial and error, I've ended up with a rather monolithic config for multiple common chunks with cache busting (truncated where possible…):

```js
import webpack from 'webpack';
import AssetsPlugin from 'assets-webpack-plugin';
import ChunkManifestPlugin from 'chunk-manifest-webpack-plugin';
import WebpackMd5Hash from 'webpack-md5-hash';


export default {
  entry: {
    polyfills: ['babel-polyfill'],
    react: ['react', 'react-dom'],
    page: '(insert path here…)',
    // insert more pages here…
  },
  plugins: [
    // Generates path-based module ids instead of fluctuating integer ones
    new webpack.NamedModulesPlugin(),
    // Without this, the entry chunk hash changes due to the changing manifest
    new WebpackMd5Hash(),
    // Extracts the manifest from the entry chunk
    new ChunkManifestPlugin(),
    // Moves every node module into a vendor chunk,
    // And caches the names of their original chunks for further chicanery
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: (module) => {
        const { userRequest, chunks } = module;
        const check = typeof userRequest === 'string' &&
          userRequest.indexOf('/node_modules/') >= 0;
        // eslint-disable-next-line no-param-reassign
        module.originalChunkNames = chunks.map(({ name }) => name);
        return check;
      },
    }),
    // Moves the react and react-dom modules (and their deps)
    // back into their original chunk
    new webpack.optimize.CommonsChunkPlugin({
      name: 'react',
      chunks: ['vendor'],
      minChunks: ({ originalChunkNames }) => originalChunkNames.includes('react'),
    }),
    // Moves babel-polyfill (and its deps) back into their original chunk
    new webpack.optimize.CommonsChunkPlugin({
      name: 'polyfills',
      chunks: ['vendor', 'react'],
      minChunks: ({ originalChunkNames }) => originalChunkNames.includes('polyfills'),
    }),
    // Moves the entry (webpack bootstrap) out into its own dedicated chunk.
    // This could be rolled into polyfills but at this point it created
    // less headaches during the debugging of this whole thing…
    new webpack.optimize.CommonsChunkPlugin({
      name: 'entry',
      chunks: ['vendor', 'react', 'polyfills'],
      minChunks: Infinity,
    }),
    // Creates a JSON map of the chunk names to their built files
    new AssetsPlugin(),
    // May be redundant now that NamedModulesPlugin is used…?
    new webpack.optimize.OccurenceOrderPlugin(),
  ],
};
```

Which enables loading of the manifest (via inline script) followed by `entry`, `polyfills`, `react`, & `vendor`… before finally loading one of the desired `page` entry points. Each of these 4 chunks will only change their hash when their contents change. (e.g. only `vendor` and `page` will get a new hash if a new vendor module is added to `page`, and `react` only changes if the library does.) Each one depends on the others higher-up the chain, so as mentioned earlier, some of them could be rolled together for less complexity (`entry` & `polyfills`).

Some observations after going through all this:

1. The calculation of which chunk became the special "entry" chunk that has the webpack bootstrap was extremely confusing. It took me a long while to grasp that there was some sort of baton-passing or re-thievery of the bootstrap going on between multiple instances of the `CommonsChunkPlugin` plugin. It wasn't *just* the order, they also had to be chained together to move the bootstrap down the chain to the last one…
2. The bug/side effect of the entry chunk's hash changing even after the manifest was removed added another level of headache on top of trying to understand the movements of the bootstrap. Hence why it ended up siphoned off into it's own `entry` chunk.
3. It was only through trial and error I managed to get a bit of a handle on how the `chunks` option works, and the `children` option is still a mystery to me. The `chunks` documentation mentions "The chunk must be a child of the commons chunk", and `children` says "If true all children of the commons chunk are selected", but what exactly *is* a parent/child relationship in this plugin? And how do these options relate to "While running in normal mode it's not allowed to use a non-entry chunk"? "Normal mode" (or "mode" in general) is not mentioned outside of the error message.
4. It feels ugly that I've had to do a lot of custom magic via `minChunks` and `module` mutation just to be able to create multiple common chunks. It's easy to make examples of multiple static common chunks(via `names`), or __one__ dynamic common chunk (via a `minChunks` function), but it feels very hard trying to combine those two configs together in a way that makes sense.
5. Due to the scale of debugging, I still haven't accounted yet for creating a common chunk for shared internal code…
6. `babel-polyfill` modifies globals, so has a special need to be loaded early before other libraries, but there isn't much documentation on how to load special cases like this for non-trivial entry points.

(Sorry for the barrage of words…)

**Comment by SpaceK33z** [comment] 2016-12-28 18:58
Going to close this since the original question was answered and this became a place to discuss semi-related issues. **If you still have an issue, please file a new issue so we can actually do something see it and do something about it.** For questions, please refer to StackOverflow.

**Closed by SpaceK33z** 2016-12-28 18:58 UTC
Labels: question
