### ISSUE TITLE
Issue when upgrading to  1.12.3

### ISSUE THREAD

**Issue by kamalbennani** [webpack/webpack#1596] opened 2015-11-06 15:12 UTC
```
ERROR in ./main.js
Module not found: Error: Cannot resolve module 'node_modules/webpack/buildin/module.js' in /home/---/Bureau/Dev/-----
 @ ./main.js 1:0-49
```

it's was working perfectly with 1.12.2

Node Version used : 0.10.40

**Comment by ppoliani** [comment] 2015-11-06 15:21
+1

**Comment by zallek** [comment] 2015-11-06 16:04
+1

**Comment by Davorak** [comment] 2015-11-06 18:13
I getting a very similar error message, when using a configuration that uses the webpack-dev-server in development.  When I use my production build everything is working fine.

Let me know if there is something I can do to help narrow down where the issue is coming from.

with both node 4.1.2 and 4.2.1

**Comment by joashc** [comment] 2015-11-07 01:02
same deal with node 5.0.0

**Comment by catkins** [comment] 2015-11-07 02:16
I'm having the same issue on node v0.12.2 on OSX Yosemite.

For me steps to reproduce

```sh
git clone git@github.com:FormidableLabs/spectacle.git
cd spectacle
npm install
npm start
```

Then in the output from `npm start`

```
  # ... other modules being built
  [488] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
  [489] ./~/style-loader/addStyles.js 6.09 kB {0} [built]
  [490] ./themes/default/index.css 1.05 kB {0} [built]
  [491] ./~/css-loader!./~/postcss-loader!./themes/default/index.css 582 bytes {0} [built]
  [492] ./~/highlight.js/styles/monokai_sublime.css 993 bytes {0} [built]
  [493] ./~/css-loader!./~/postcss-loader!./~/highlight.js/styles/monokai_sublime.css 2.78 kB {0} [built]

ERROR in ./index.jsx
Module not found: Error: Cannot resolve module 'node_modules/webpack/buildin/module.js' in /Users/catkins/Developer/javascript/realtime-apps-with-rethinkdb-melbourne-nodejs
 @ ./index.jsx 1:0-49
webpack: bundle is now VALID.
```

After manually installing `1.12.12` as suggested by @Davorak the bundle is built again without errors.

**Comment by kolodny** [comment] 2015-11-08 01:43
+1

**Comment by niftylettuce** [comment] 2015-11-08 05:18
+1

**Comment by figalex** [comment] 2015-11-08 06:46
+1

**Comment by herman-rogers** [comment] 2015-11-09 09:22
+1

**Comment by ehd** [comment] 2015-11-09 10:13
@sokra We've hit this problem as well, reinstalling the environment didn't help. Did some digging but couldn't find the exact cause of the problem. This line looks like it could be responsible:

https://github.com/webpack/webpack/compare/v1.12.2...v1.12.3#diff-3e392a298aac97e71e5ecb5dfa287f98R90

Maybe could use `path.resolve` instead of `path.join` and [`__dirname`](https://nodejs.org/docs/latest/api/globals.html#globals_dirname)?

**Comment by PEM--** [comment] 2015-11-10 19:16
Dawn, it failed on me too.

**Comment by sokra** [comment] 2015-11-10 20:30
@ehd Thanks for this hint.

I hope it's fixed now.

**Comment by ehd** [comment] 2015-11-10 22:57
@sokra Wonderful, thank you!

**Comment by PEM--** [comment] 2015-11-11 08:43
Thanks guys! :+1:

**Closed** 2015-11-13 21:02 UTC

**Comment by IAkumaI** [comment] 2016-01-12 15:02
It's come back in 1.12.10 (Windows 7);
Node: 5.4.0
```
ERROR in ./app.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/webpack/buildin/module.js in D:\PhpStorm\..../src
 @ ./app.jsx 1:0-54
```

Errors was only if start `webpack-dev-server` and only with react hot reload (i tried react-hot-loader and babel-preset-react-hmre).
After install v 1.12.2 the bug has gone.

**Comment by sokra** [comment] 2016-01-12 16:24
@IAkumaI Let me guess:

* You are either using `+ "/src"` instead of `path.join(..., "src")` (windows has "\" as path separator)
* You are overwriting `resolve.extension` and missed `""` (empty string) in the array (as noted on the hint one the configuration documentation page)

**Comment by IAkumaI** [comment] 2016-01-12 16:27
```
resolve: {
        extensions: ['', '.js', '.jsx'],
        modulesDirectories: ["node_modules", "src"],
    },
```

And i use `path.resolve('src')` instead of `+ '/src'`

**Comment by sokra** [comment] 2016-01-13 08:21
What does `--display-error-details` print?

**Comment by HyosokaPoipo** [comment] 2016-08-04 17:54
I have the same issues
![1a](https://cloud.githubusercontent.com/assets/7435137/17412438/f67a3aac-5aa6-11e6-818e-6064ac9c3c6e.png)

I have added
 extensions: ['', '.js', '.jsx'],
 modulesDirectories: ["node_modules", "src"],

but the errors are still there... and I don't know how to apply "path.resolve('src')" to my webpack.config.js..

Please help.. :)
