### ISSUE TITLE
Using --bail makes module build errors more cryptic.

### ISSUE THREAD

**Issue by redfin-sasha-aickin** [webpack/webpack#711] opened 2015-01-22 23:17 UTC
We use `--bail` so that webpack will report errors to our build script (without --bail, it doesn't give an error exit code).

Unfortunately, when you use `--bail`, the error result from unparseable JavaScript loses the line that tells you what file the error occurred in.

Example output without `--bail`:

```
Hash: 91ed442d775c1a722525
Version: webpack 1.4.13
Time: 3094ms
                                        Asset    Size  Chunks             Chunk Names
<snip>
    + 286 hidden modules

ERROR in ./pages/MyPage.js
Module build failed: Error: Parse Error: Line 7: Unexpected token ;
    at throwError (/Users/sashaaickin/code/main/corvair/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
    at throwUnexpected (/Users/sashaaickin/code/main/corvair/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)
<snip>
    at parseProgramElement (/Users/sashaaickin/code/main/corvair/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6185:16)
 @ ./target-entrypoints/MyPageEntry.js 4:17-68
```

With `--bail`, the output looks like:

```
ModuleBuildError: Module build failed: Error: Parse Error: Line 7: Unexpected token ;
    at throwError (/Users/sashaaickin/code/main/corvair/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
    at throwUnexpected (/Users/sashaaickin/code/main/corvair/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)
<snip>
    at /Users/sashaaickin/code/main/corvair/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:15
    at runSyncOrAsync (/Users/sashaaickin/code/main/corvair/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:158:12)
```

Note that without --bail, the file with the syntax error (MyPage.js) is named, but not in the latter. This makes it hard to debug problems that come from our build script, because the error log does not tell us what file the problem is in.

**Comment by sapegin** [comment] 2015-03-23 14:46
Even more cryptic with loaders such as eslint-loader.

Without `--bail`:

```
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.7.3
Time: 1157ms
    + 1 hidden modules

ERROR in ./app/app.js

  5:78  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/app.js
Module build failed: Error: Module failed because of a eslint error.
    at lint (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/eslint-loader/index.js:54:15)
    at Object.module.exports (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/eslint-loader/index.js:80:3)
```

With `--bail`:

```
ModuleBuildError: Module build failed: Error: Module failed because of a eslint error.
    at lint (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/eslint-loader/index.js:54:15)
    at Object.module.exports (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/eslint-loader/index.js:80:3)
    at DependenciesBlock.onModuleBuildFailed (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:303:19)
    at nextLoader (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:263:31)
    at /Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:285:15
    at runSyncOrAsync (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:171:4)
    at nextLoader (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:283:3)
    at Storage.finished (/Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at evalmachine.<anonymous>:272:14
    at /Users/admin/Dropbox/Projects/Misc/deliveryhero-test/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

**Comment by ctumolosus** [comment] 2015-06-03 02:45
I find this to be an undesirable effect as well.

**Comment by josephfinlayson** [comment] 2015-09-29 14:20
Is this going to be fixed?

**Comment by jhuntoo** [comment] 2016-03-04 11:09
Any updates on this ?

This is a real pain, --bail is needed so that CI builds will fail when they should. However tslint-loader will not tell why it's failing.

This has been reported here : https://github.com/wbuchwalter/tslint-loader/issues/18
and here: https://github.com/AngularClass/angular2-webpack-starter/issues/374

For authors of  loaders looking for a workaround, see how eslint-loader resolved this https://github.com/MoOx/eslint-loader/issues/53, by returning the errors or warnings in the exception message itself.

e.g. https://github.com/MoOx/eslint-loader/blob/master/index.js#L73

**Comment by jhuntoo** [comment] 2016-03-04 11:50
AN issue with the workaround, when a loader returns an error and webpack bails, only the first error returns which could be tedious if you have a lot of errors and have to keep re running the build. Is there a way that webpack could allow a loader to report all errors and bail after all errors are known ?

**Comment by KeitIG** [comment] 2016-07-20 08:13
Hello ! Any news on this ?

**Comment by PhiLhoSoft** [comment] 2016-08-01 16:27
I don't have this problem. Either it depends on config (I also use eslint-loader), or it has been fixed.

I have:

> Hash: df6a9e09957b40770a92
> Version: webpack 1.13.1
> Time: 38200ms
>    [0] multi vendor 232 bytes {1} [built]
>        factory:0ms building:1ms = 1ms
>  [187] ./Project/app/scripts/features/settings ^\.\/.*\.html$ 729 bytes {0} [built]
>        ... -> factory:253ms building:121ms
>     + 232 hidden modules
> 
> ERROR in ./Project/app/scripts/services/slug.js
> 
> D:\Sources\Project\app\scripts\services\slug.js
>   185:15  error  Missing semicolon  semi
> 
> ✖ 1 problem (1 error, 0 warnings)

on Windows 10.
My build launches `webpack --bail --progress --profile`

**Comment by khronic** [comment] 2016-10-04 15:56
Hey guys just wondering if there is any new update on this item?

**Comment by wyattjoh** [comment] 2016-11-09 14:27
Also experiencing the same issue here.

**Comment by domenkozar** [comment] 2017-02-23 12:53
Same here.

**Comment by jmitchell** [comment] 2017-02-23 18:53
Here's a silly workaround. Given a webpack call without `--bail` called `$RUN_WP`,

    $RUN_WP && $RUN_WP --bail

The first run gives you the detailed feedback about the error, and the second ensures you get a non-zero exit code when there's an error. This shouldn't be necessary, and is a hack.

**Comment by timraasveld** [comment] 2017-05-22 13:09
Based on @jmitchell's suggestion, I do the following to enable Bash command chaining, but only print the pretty (non `--bail`) error if it fails.
```bash
(webpack && webpack --bail 2>/dev/null) && nwjs .

**Comment by McGiogen** [comment] 2018-04-04 13:54
Any progress about this request? We will never build two times just to improve the logs...

**Comment by Janpot** [comment] 2018-04-07 14:11
I'm trying to reproduce this but adding the `--bail` flag makes no difference for me. Is this happening on the latest version? Does anybody have an example of a repo where this happens?

**Comment by ooflorent** [comment] 2018-05-09 06:45
I'm closing this issue since the problem is not reproducible using webpack 4 and webpack 3 is on maintenance mode.

**Closed by ooflorent** 2018-05-09 06:45 UTC
Labels: bug
