### ISSUE TITLE
support for esmodules as output for the web?

### ISSUE THREAD

**Issue by RebeccaStevens** [webpack/webpack#8010] opened 2018-09-10 04:21 UTC
## Feature request

When outputting content targeting the `web` platform, it would be nice to have the option to output an es module for modern browsers. (I don't believe there is currently a way to do this - if there is it needs better documentation :P).

**What is the expected behavior?**
Ideally, I would like to be able to have webpack output two entry files, an esmodule as well as what it currently outputs.  
Then in the `index.html` file, both files can be loaded like this:

```html
<head>
  <script nomodule src="bundle.js" async></script>
  <script type="module" src="bundle.mjs" async></script>
</head>
```

**What is motivation or use case for adding/changing the behavior?**
Supporting the modern web.

**How should this be implemented in your opinion?**
Maybe something like this:

```js
// webpack.config.js

const config = {
  //...
};

const webConfig = Object.assign({}, config, {
  target: 'web',
  //...
});

const webModuleConfig = Object.assign({}, config, {
  target: 'web-module',
  //...
});

module.exports = [
  webConfig, webModuleConfig,       
];
```

**Are you willing to work on this yourself?**
Maybe but probably not. I'm still a novice when it comes to the webpack eco-system so I'd probably be at a loss on how to implement this.

**Comment by sokra** [comment] 2018-09-10 13:05
What should be the difference between `target: 'web'` and `target: 'web-module'`?

**Comment by CarterLi** [comment] 2018-09-11 02:13
+1

It's extremely useful in development env.

1. Code generation should be faster because browers with ES6+ module support should support all latest ES6 features; no babel needed.
2. We can drop sourcemaps in dev-env because less code is changed when targeting ES6 module. Sourcemaps generally slow down the code generation and never work correctly as they should be.  
![image](https://user-images.githubusercontent.com/6134068/45333978-4bc46f80-b5ab-11e8-9e58-1cdad37d564f.png)

**Comment by haggholm** [comment] 2019-02-07 18:11
Another nice feature that this could enable is deployment of multiple Babel configs (or equivalent). Create one build for modern browsers, leveraging native support for `async`/`await`, ES collections, and so on, and output as an ES module; create another build that supports legacy browsers at the expense of size and ugliness, loading with `nomodule`.

Of course, this would presumably require multi-config (for different Babel plugins), rather than parallel outputs for a single build, but I’d gladly pay that price.

**Comment by moderndeveloperllc** [comment] 2019-04-26 02:26
@RebeccaStevens Just a note that the [webpack-babel-multi-target-plugin](https://www.npmjs.com/package/webpack-babel-multi-target-plugin) has this functionality. It would be nice if this was in the main package though!

**Comment by moderndeveloperllc** [comment] 2019-10-14 22:45
I guess a comment is needed to keep this going. Not sure any webpack devs are interested in this though.

**Comment by evilebottnawi** [comment] 2019-10-15 11:22
@moderndeveloperllc partial implemented in `webpack@5` and in our roadmap

**Comment by ulivz** [comment] 2019-10-25 06:54
@evilebottnawi Thanks for the great work! I've expected this for a long time, could I ask that when would we get the stable version of outputting es modules?

**Comment by pravdomil** [comment] 2019-11-14 22:53
it's in todo https://github.com/webpack/webpack/blob/0d4607c68e04a659fa58499e1332c97d5376368a/lib/LibraryTemplatePlugin.js#L200

**Comment by merrywhether** [comment] 2020-02-13 01:43
It would be really cool if we could standardize on a way for package authors to indicate module/nomodule builds as well. Seems like the best way would be to piggyback on Node's upcoming conditional exports syntax to describe the relevant entry points: https://nodejs.org/api/esm.html#esm_conditional_exports

**Comment by vankop** [comment] 2020-08-09 16:42
duplicate of https://github.com/webpack/webpack/issues/2933

**Closed by vankop** 2020-08-09 16:42 UTC

**Comment by evilebottnawi** [comment] 2020-08-10 10:43
@vankop not sure it is fully duplicate, because this issue about ES modules bundle output without library building, #2933 for library, but I agree, let's track ES module syntax for output in the one issue
