### ISSUE TITLE
Library included multiple times in bundle code

### ISSUE THREAD

**Issue by tstirrat15** [webpack/webpack#8886] opened 2019-03-08 17:00 UTC
# Bug report

## Note
This is a similar issue to #2134, but the context is not exactly the same, so I chose to open another issue.

## What is the current behavior?
Here's the configuration for the server bundle: https://gist.github.com/tstirrat15/38a1ab2b768406496284d5fdfbef63a6

When I run our production build and inspect the output, I see:

```javascript
// ...
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
// ...
/* WEBPACK VAR INJECTION */(function(module) {/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
// ...
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_2__);
// ...
```
Where `__webpack_require__(0)` is:
```javascript
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 868);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports) {

module.exports = require("react");

/***/ }),
// ...
```

This indicates that there are at least 3 instances of React floating around during execution. This hasn't been a problem in the past, but with recent changes to the React context API, React now needs to be a singleton.

In #2134, I found a recommendation to use `optimization: { runtimeChunk: 'single' }`, and when I tried that, I only found a single instance of React in the bundle, which was good. However, running `node build/server.js` immediately exited 0 without waiting for requests.

Is there something obvious that I'm missing? If so, I'd be happy to add it to documentation.

## If the current behavior is a bug, please provide the steps to reproduce.
I don't have a minimal repro yet. My impression is that it's the result of the confluence of a bunch of different things, rather than an easily localized bug.
## What is the expected behavior?
A single instance of React, or a working server build with `runtimeChunk: 'single'`.

## Additional context
* This is an isomorphic React app, with the majority of code being shared between frontend and backend, using two different entrypoints.
* We make extensive use of code-splitting

Please let me know if there's any additional context that would be helpful.

## Other relevant information:
webpack version:  4.29.6
Node.js version: 8.15.1
Operating System: Ubuntu
Additional tools: (like?)

**Comment by tstirrat15** [comment] 2019-03-08 20:32
When I use `runtimeChunk: 'single'`, I get three output files:

* `server.js`: Contains the webpack require bootstrap code
* `0.server.js`: seems to contain most of the app code
* `1.server.js`: seems to contain the import + runtime code.

However, the call of the bootstrap function in `server.js` is empty:
```javascript
// ...
/******/ 	// uncaught error handler for webpack runtime
/******/ 	__webpack_require__.oe = function(err) {
/******/ 		process.nextTick(function() {
/******/ 			throw err; // catch this error by using import().catch()
/******/ 		});
/******/ 	};
/******/ })
/************************************************************************/
/******/ ([]);
//# sourceMappingURL=server.js.map
```
I assume that second-to-last line is where it should be doing something with the other chunks?

**Comment by tstirrat15** [comment] 2019-03-13 20:19
I looked at the client bundle as well, and it's exhibiting the same problem. What are potential causes of this?

**Comment by elmeerr** [comment] 2019-04-01 06:29
I'm facing the same issue!! Any update on this?

**Comment by evilebottnawi** [comment] 2019-04-01 08:27
It is open source feel free investigate

**Comment by tstirrat15** [comment] 2019-04-02 14:21
I'd love to, but so far the investigations that I've done haven't borne any fruit. Do you have any recommendations on where to start looking? I've messed around with `runtimeChunk`, and that's the only thing that I've found that other issues/SO answers have pointed to.

I've got a few ideas of things that I can try - such as cutting down on my project until something changes, or seeing if I can repro with create-react-app - but those seem like blunt instruments, especially compared to something that someone who's already familiar with the internals would come up with.

Again, I'm happy to do the legwork, but I would love having a bit of direction beforehand.

Unless you're saying that I'm unlikely to find that sort of guidance from the maintainers, in which case I can go tool around myself.

**Comment by tstirrat15** [comment] 2019-04-05 17:30
How does `require` work on nodejs? Will consecutive calls to require produce a reference to the same object?

Additionally, I noticed that the webpack require references an entry in a big ol' array of import code. Is that meant to provide a caching mechanism as well? Is it possible that the webpack require array closures are messing up the node require caching somehow?

**Comment by evilebottnawi** [comment] 2019-04-05 17:45
Can you provide minimum reproducible test repo with notes about that you actually have and what you expected, thanks

**Comment by tstirrat15** [comment] 2019-04-05 20:44
I'm working on a minimal reproduction repo.

One thing I did notice, though, was that when I included `react` in the exceptions to our `externals` configuration, the problem went away. Seems like it might have something to do with the interaction between node's `require` and the webpack require internals?

**Comment by tstirrat15** [comment] 2019-04-23 15:26
More examples of people seeing this issue here:

https://github.com/facebook/react/issues/13991

The fix described above didn't end up working - I ran into the same hooks error described in the issue above. What did fix it was removing `react` from externals and then adding aliases for resolution:

```javascript
const config = {
  // ...
  resolve: {
    // Force webpack to resolve all references to react to the same package.
    // This should fix the problems we're seeing with hooks/context failing.
    alias: {
      react: path.resolve(path.join(__dirname, '../node_modules/react')),
      'react-dom': path.resolve(path.join(__dirname, '../node_modules/react-dom')),
    },
  },
  // ...
};
```

Which still seems to point to some issue with webpack internals. Is this being tracked anywhere else?

**Comment by evilebottnawi** [comment] 2019-10-15 11:42
bump for future investigation

**Comment by vankop** [comment] 2020-08-09 17:14
duplicate of https://github.com/webpack/webpack/issues/985

**Closed by vankop** 2020-08-09 17:14 UTC
