### ISSUE TITLE
Chunks dynamically generated by import() do not affected by CommonsChunkPlugin

### ISSUE THREAD

**Issue by rzcoder** [webpack/webpack#4360] opened 2017-02-23 13:17 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Chunks generated by `System.import` or `import` do not affected by CommonsChunkPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**
[demo rep](https://github.com/rzcoder/webpack_chunks_issue)

*sources structure*
```
src
  |- modules
  |     |- module0.js
  |     |- module1.js
  |- index.js
```
*webpack.config.js*
```js
const path = require('path');
const webpack = require("webpack");

module.exports = {
    entry: {
        index: './src/index.js'
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: 'dist/'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: "vendors",
            minChunks: function(module) {
                return module.resource && (/node_modules/).test(module.resource);
            }
        })
    ]
};

```
*index.js*
```js
for (let i = 0; i < 2; i++) {
    System.import("./modules/module" + i).then((module) => module.default());
}
```

*modules/module0.js* && *modules/module1.js*
```js
import * as _ from "lodash";
export default () => console.log(_.random(100));
```

Generated chunks for module0 & module1 both has copy of `lodash` and vendors.js is empty.

**What is the expected behavior?**
Dynamically generated chunks must be affected by CommonsChunkPlugin in same way as entry points.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 7.0.0, webpack 2.2.1, OSX

**Comment by sokra** [comment] 2017-02-28 16:28
duplicate of #4392

**Closed by sokra** 2017-02-28 16:28 UTC
