### ISSUE TITLE
Error: Chunk.entry was removed. Use hasRuntime()

### ISSUE THREAD

**Issue by nareshbhatia** [webpack/webpack#2764] opened 2016-07-13 13:33 UTC
Just upgraded from 2.1.0-beta.15 to 2.1.0-beta.17. When I run my build using

    webpack -p --env prod

I am getting the following error

    Error: Chunk.entry was removed. Use hasRuntime()

Any ideas what is going on?

I have a demo this afternoon and need to get this working. Can't go back to beta.15 because I was starting to see a different error there. Thanks in advance for your help.

**Comment by nareshbhatia** [comment] 2016-07-13 13:38
Adding the stack trace, if that helps:

```
    at Chunk.Object.defineProperty.get (/Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Chunk.js:34:9)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/nbhati/projects/idea-tracker-client/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins (/Users/nbhati/projects/idea-tracker-client/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.seal (/Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:535:7)
    at Compiler.<anonymous> (/Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compiler.js:436:15)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:434:10)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:410:12
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:325:10
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:52:16
    at done (/Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:246:17)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:44:16
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:325:10
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:52:16
    at done (/Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:246:17)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:44:16
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:325:10
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:52:16
    at done (/Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:246:17)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:44:16
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:325:10
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:52:16
    at done (/Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:246:17)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:44:16
    at /Users/nbhati/projects/idea-tracker-client/node_modules/webpack/lib/Compilation.js:325:10
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:52:16
    at done (/Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:246:17)
    at /Users/nbhati/projects/idea-tracker-client/node_modules/async/lib/async.js:44:16
```

And here's my prod config:

```
'use strict';

const webpack = require('webpack');
const merge = require('webpack-merge');
const webpackCommon = require('./webpack-common.config');

module.exports = merge(webpackCommon, {
    devtool: 'none',

    plugins: [
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.AggressiveMergingPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                unused: true,
                dead_code: true,
                warnings: false,
                screw_ie8: true
            }
        }),
        new webpack.NoErrorsPlugin(),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('production'),
            '__DEV__': false
        }),
        new webpack.optimize.CommonsChunkPlugin({
            minChunks: 2,
            name: 'vendor'
        })
    ]
});
```

**Comment by JonatanSalas** [comment] 2016-07-13 13:46
I'm experiencing the same issue with a MERN 2 production build, using latest version of webpack (2.1.0-beta.17). 

@nareshbhatia revert to the version that was working for you, I will do the same. 

Maybe this is a minor bug and the next beta versions will solve this.

**Comment by nareshbhatia** [comment] 2016-07-13 13:57
I will try to revert to beta.15 which is what I was using earlier. But that started showing up another error. Let me run that again, and I will report back.

**Comment by JonatanSalas** [comment] 2016-07-13 14:04
@nareshbhatia  If beta version related to 2.1.0 doesn't work, you could revert to Webpack 2.0.0-beta, which was working well too. I have done this, in order to get working again the build of my application. 

I will wait for version 2.1.0 to be more stable, and then I will do the upgrade.

**Comment by Kovensky** [comment] 2016-07-13 14:10
I suppose this is part of why sokra has avoided marking ExtractTextWebpackPlugin as webpack2-compatible.

**Comment by sokra** [comment] 2016-07-13 14:25
install extract-text-webpack-plugin@^2.0.0-beta

**Comment by nareshbhatia** [comment] 2016-07-13 14:32
Sorry, I am a newbie to this. Couldn't find 2.0.0-beta in the list of releases. I used v2.0.7-beta. Now I am getting this error. (I remember that I was getting the same error with 2.1.0-beta.15, which is why I tried to move up to 2.1.0-beta.17.)

```
Hash: dd465add87b933394a2d
Version: webpack 2.0.7-beta
Time: 36064ms
    + 945 hidden modules

WARNING in vendor.js from UglifyJs
Dropping unreachable code [./~/mobx/lib/mobx.js:1275,0]
Declarations in unreachable code! [./~/mobx/lib/mobx.js:1275,0]
Dropping unreachable code [./~/mobx/lib/mobx.js:1388,0]
Declarations in unreachable code! [./~/mobx/lib/mobx.js:1388,0]

ERROR in chunk main [initial]
vendor.js
Template cannot be applied as TemplateArgument: HarmonyImportDependency
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Comment by Kovensky** [comment] 2016-07-13 14:34
He means `webpack-extract-text-plugin`'s `2.0.0-beta`, not `webpack`'s

https://github.com/webpack/extract-text-webpack-plugin/commit/d301fd0c350356cb8652e12a9b9de7c72924fa3c

**Comment by nareshbhatia** [comment] 2016-07-13 14:48
Ah, I see. Thanks for clarifying, @Kovensky.

Ok I tried webpack@^2.1.0-beta.17 + extract-text-webpack-plugin@^2.0.0-beta. The "Chunk.entry was removed" error is now gone. But I am still seeing the other error with HarmonyImportDependency:

```
Hash: 30a29233bf7d9d6db319
Version: webpack 2.1.0-beta.17
Time: 25646ms
    + 946 hidden modules

ERROR in chunk main [initial]
[name].js
Template cannot be applied as TemplateArgument: HarmonyImportDependency
Child html-webpack-plugin for "index.html":
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

Any ideas?

**Comment by sokra** [comment] 2016-07-13 14:54
That's something else. As workaround remove the DedupePlugin

**Comment by nareshbhatia** [comment] 2016-07-13 14:58
Yep, just saw that (https://github.com/webpack/webpack/issues/2644). Problem solved. Thank you all for helping out. Keep up the great work!

**Comment by niieani** [comment] 2016-07-14 16:30
Updating the Extract Text Plugin to 2.0.0-beta worked for the most part, however another problem has appeared, extracting CSS build with SASS plugin stopped working: https://github.com/webpack/extract-text-webpack-plugin/issues/211
It works correctly when not using ExtractTextPlugin, so it must be either a Webpack or Extract Text Plugin problem.

**Comment by dschissler** [comment] 2016-07-17 19:10
I'm just getting into the hell storm now and I see version `2.0.0-beta.0` but not `2.0.0-beta`.  I'm committed to upgrading.

**Closed** 2016-07-20 12:24 UTC
Labels: bug, webpack-2

**Comment by vwrobel** [comment] 2016-07-22 14:32
@JonatanSalas: Would that be possible to share the versions of webpack and extract-text-plugin that work to build your MERN 2 project? Thanks a lot!

**Comment by rpoitras** [comment] 2016-07-24 19:00
@niieani, just got SASS working with this combo. I'm not chunking yet and hot updates not working but .scss are packed in .css in my distribution directory.  Also using a global .scss with component level .scss.  All combined into the [name].[id].style.css.

webpack.config.js:
```
module: {
      loaders: [
       {
          test: /\.scss$/,
          loader: ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: ['css', 'sass']
          })
        },
...
plugins: [
      new ExtractTextPlugin({
        filename: '[name].[id].style.css',
        allChunks: true
      })
...
```
package.json:
   ```
...
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^2.0.0-beta",
    "node-sass": "^3.8.0",
    "sass-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "webpack": "^2.1.0-beta.20",
...
```

**Comment by niieani** [comment] 2016-07-24 19:03
@rpoitras actually this was fixed in https://github.com/webpack/extract-text-webpack-plugin/commit/d40c13115f1d591558cbe4837b570642356cc178. But thanks for the write-up.

**Comment by jspizziri** [comment] 2016-09-15 19:52
If anyone's using `webpack-split-by-path` you'll have to upgrade that to `^0.1.0-beta` as well. See here https://github.com/BohdanTkachenko/webpack-split-by-path/pull/22

**Comment by denji** [comment] 2016-12-10 13:49
Beta will pull more more recent releases submodules for webpack2@beta
```sh
# with "-D" (devDependencies), default: (dependencies)
yarn add [ | -D] extract@beta # with
# "--save-dev" (devDependencies) / with "--save" (dependencies)
npm i [--save | --save-dev] webpack@beta

yarn install webpack-split-by-path@beta
npm i webpack-split-by-path@beta

yarn install extract-text-webpack-plugin@beta
npm i extract-text-webpack-plugin@beta
# …………
```

**Comment by galensheen** [comment] 2016-12-24 05:41
How to resolve this issue, I met now but no idea for it.

**Comment by kachkaev** [comment] 2016-12-30 16:52
@galensheen What helped me was installing `extract-text-webpack-plugin@^2.0.0-beta` as @sokra has suggested earlier:

```bash
yarn add extract-text-webpack-plugin@^2.0.0-beta
```

Here is my current very simple webpack config, which seems to work:

```js
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  entry: {
    a: './assets/a.js',
    b './assets/b.js'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules/
    }, {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader'
      }),
    }, {
      test: /\.less$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader!less-loader'
      }),
    }]
  },
  output: {
    path: "./build",
    filename: "[name].js"
  },
  plugins: [
    new ExtractTextPlugin({
      filename: "[name].css",
      allChunks: true
    })
  ]
};
```

**Comment by galensheen** [comment] 2016-12-31 10:31
@kachkaev Thanks, I will try with extract-text-webpack-plugin@^2.0.0-beta

**Comment by developer94404** [comment] 2017-01-30 15:12
I get this error when trying to run it with npm 4, node 7.4.0, webpack 2.2.0, and latest extract-text-plugin (1.0.1)

I am disabling use of extract-text-plugin for now, as it seems to be a extract-text-plugin issue and not webpack's issue .. ?

**Comment by deefour** [comment] 2017-01-30 16:18
@developer94404 as others in this thread have pointed out, you need to install a webpack2.0-compatible version of the plugin.

```
npm install extract-text-webpack-plugin@^2.0.0-beta --save-dev
```

**Comment by itisrita** [comment] 2017-02-06 13:41
In case somebody will try to find solution - _extract-text-webpack-plugin@^2.0.0-beta_ did not work for  me, but  executing  _npm install --save-dev extract-text-webpack-plugin@^2.0.0-rc.3_ works

**Comment by michaelryancaputo** [comment] 2017-02-06 15:48
rc3 worked for me as well, however, running `npm i extract-text-webpack-plugin@^2.0.0-beta` added rc3 to my package.json file

**Comment by StephanBijzitter** [comment] 2017-02-23 10:23
I can confirm that I also needed the third release candidate.
Without rc3, the error would indeed disappear but the entire process crashed.
rc3 does everything well.
