### ISSUE TITLE
BUG: "export 'default' (imported as 'selection_enter') was not found in './enter'

### ISSUE THREAD

**Issue by kukjevov** [webpack/webpack#4817] opened 2017-05-04 13:28 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Currently if you try to use d3.js library, webpack will generate warning:
*"export 'default' (imported as 'selection_enter') was not found in './enter'*

That is not so big problem, but when you run javascript generated by webpack it will fail with error:
SyntaxError: function statement requires a name

Problem is using ES2015 import default and export default which is not working.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/kukjevov/webpack-error-sample

**What is the expected behavior?**
It should work

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
nodejs: 7.10, webpack 2.5.0, Windows 10

**Comment by sokra** [comment] 2017-05-06 20:15
You testcase compiles fine for me... ?

**Comment by kukjevov** [comment] 2017-05-08 19:37
As i wrote down it compiles with warnings. But these warnings ends up in browser with syntax error as mentioned above:
SyntaxError: function statement requires a name

Thanks :)

**Comment by gmatroskin** [comment] 2017-05-11 17:57
Having the same issue with `d3-shape` module

```
WARNING in /Users/gshtilma/src/flurry/corona-ui/~/d3-shape/src/order/descending.js
4:9-18 "export 'default' (imported as 'ascending') was not found in './ascending'
```

Files in question:

https://github.com/d3/d3-shape/blob/master/src/order/descending.js
https://github.com/d3/d3-shape/blob/master/src/order/ascending.js

**Comment by gmatroskin** [comment] 2017-05-11 18:35
had a similar issue, but realized it was caused by module (`d3-shape`) being written in ES6 & being  excluded from babel-loader in my config, fixing that got rid of the warning - possible you have a similar issue @kukjevov

**Comment by kukjevov** [comment] 2017-05-11 19:13
Well i have temporarily solved it by using import {} from 'd3' as whole library. There is no problem, but with partial 'd3-shape' etc it is not working. But it was working in older versions of Webpack. So this is not critical for me, but i was thinking maybe it is good to look at that if it can cause problems.

Thanks :)

**Comment by morlay** [comment] 2017-05-18 09:17
Have the same issue.
Node 7.10 Webpack 2.5.1
With "d3-shape" 
```
4:9-18 "export 'default' (imported as 'ascending') was not found in './ascending'
```
maybe it is because of the unamed function

```js
# d3-shape/src/constant.js
export default function(x) {
  return function constant() {
    return x;
  };
}
```
will pack to
```
/******/ ([
/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
"use strict";
function(x) {
  return function constant() {
    return x;
  };
}
/***/ }),
/* 1 */
```
the `export default` is missing.
when i named it, it works well.

**Comment by morlay** [comment] 2017-05-18 09:53
Sorry, it may be registry mirror issue, use install from npm registry work well, but use `https://registry.npm.taobao.org` will got this issue.

**Comment by scottbedard** [comment] 2017-06-08 01:29
I am experiencing this issue as well with 2.6.1

**Comment by frenzzy** [comment] 2017-06-23 06:58
I had the same issue, but it was because I used multi compiler mode (webpack.config.js returns array of configs) and also:

1. For one of compilers the same module did not contain the default export, for example:
    ```js
    // moduleName/package.json
    {
      "main": "./server.js",
      "browser": "./browser.js"
      // ...
    }

    // moduleName/server.js
    export default 'example'

    // moduleName/browser.js
    // no default export here
    ```

2. [The resolve configuration object](https://webpack.js.org/configuration/resolve/) had shared between multiple configs, like so:
    ```js
    // webpack.config.js
    const resolve = {};

    module.exports = [
      {
        target: 'web',
        resolve: resolve,
        // ...
      },
      {
        target: 'node',
        resolve: resolve,
        // ...
      },
    ];
    ```


FYI @sokra 
Maybe webpack should not mutate resolve section of config?

**Comment by pksjce** [comment] 2017-07-11 14:50
@kukjevov - Your test error repo compiles and shows "Hello World, 4" as I tried it with `webpack 3.1`. Don't see any warnings. Can you confirm too?

**Comment by marvinhagemeister** [comment] 2017-07-18 16:25
I just stumbled upon the same error at work with `react`:

```bash
WARNING in ./components/Button/index.js
56:2-7 "export 'default' (imported as 'React') was not found in '../../..'
```

Haven't managed to narrow it down to a small test case yet, though.

**Comment by Luixo** [comment] 2017-10-07 22:46
Got the same problem!
`export 'compose' was not found in 'redux'`
The issue was that one of my folders in project was named `redux`.

**Comment by xierenyuan** [comment] 2017-10-18 12:27
@morlay  我使用淘宝镜像以遇到这个问题呢。  你更换了源好呢吗?

**Comment by nerdess** [comment] 2017-11-09 21:47
this might be of use for someone. had a similar issue when i was updating an old create-react-app application. had to change all occurrences of

module.exports = Blabla;

to 

export default Blabla;

**Comment by zebulonj** [comment] 2018-02-14 21:52
In case anyone stumbles across this thread... you'll also see the error reported here if you try to process the `babel-runtime` itself through (i.e., by not excluding it from the babel-loader in webpack).

**Comment by xiaoshude** [comment] 2018-10-02 14:00
maybe babel has compiled some files which should not be compiled!

**Comment by pwnreza** [comment] 2019-01-17 13:03
> In case anyone stumbles across this thread... you'll also see the error reported here if you try to process the `babel-runtime` itself through `babel-plugin-transform-runtime` (i.e., by not excluding it from the babel-loader in webpack).

@zebulonj You are the best. Only your solution worked for me !! Thank you very much !!

**Comment by zachstronaut** [comment] 2019-03-11 15:10
So I've been working on this vue-cli project for days that uses webpack. I had a simple config file that was module.exports = {stuff} and now today for some reason webpack started up with this problem and I had to switch it over to export default {stuff} ... I have no idea why for days the old style export was fine and all of a sudden when I run the dev environment today it was not. That's pretty odd!?

**Comment by chuilee** [comment] 2019-04-22 12:45
[https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-commonjs](url) it works for me

**Comment by sigod** [comment] 2019-05-14 11:14
In our Node project, we use a CommonJS module that is included on both server-side and client-side. Everything worked fine until we added `@babel/plugin-transform-runtime`. It started showing compilation warning mentioned here. And in the browser it just fails with `Uncaught TypeError: Cannot assign to read-only property 'exports' of object '#<Object>'`.

I've discovered that it can be fixed by adding `@babel/plugin-transform-modules-commonjs`.

**Comment by hpeikari** [comment] 2019-07-02 14:22
@sigod , that solved our issue! Thank you!

**Comment by RyKilleen** [comment] 2019-07-25 15:52
In my case, this occurred while updating to Babel 7. The key was adding `modules: 'commonjs'` to the presets in our `babel.config.js` file.

```
presets: [
        '@babel/preset-react',
        ['@babel/preset-env', {
          modules: 'commonjs',
          ...
```

**Comment by steve-taylor** [comment] 2019-10-12 02:08
> I've discovered that it can be fixed by adding `@babel/plugin-transform-modules-commonjs`.

> The key was adding `modules: 'commonjs'` to the presets in our `babel.config.js` file.

Both these options made my warnings/errors go away and also made my bundle size explode from 472 KiB (without using `@babel/plugin-transform-runtime`) to 865 KiB.

Quoting the [docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime):

> A plugin that enables the re-use of Babel's injected helper code to save on codesize.

When you tell Babel to transform ES modules to CommonJS, you're disabling Webpack's tree shaking, which is enabled by default in production builds. Although the bundle size saving provided by `@babel/plugin-transform-runtime` are not insignificant, it pales in comparison to Webpack's tree shaking.

The real fix here is to simply not use `@babel/plugin-transform-runtime` until this issue is fixed or someone shows us how to use the tools properly.

**Comment by sivanZhang** [comment] 2020-01-02 01:28
const Cesium = require('cesium/Cesium')
so easy

**Comment by jsonchou** [comment] 2020-01-08 14:37
@zebulonj @sigod  @steve-taylor 

I use @babel/plugin-transform-modules-commonjs for a long time, and my project (ssr project) run well until someday i found tree shaking feature lost with this babel plugin. 

I remove it and tree shaking come back, but get some WARNING like this issue.

~~~
    WARNING in ../_base/modules/commonMixins.js 12:4-10
    "export 'default' (imported as 'config') was not found in '../config/commonConfig'
~~~

have you guys ever check your project's tree shaking feature.

**Comment by michaelalhilly** [comment] 2020-09-01 04:00
> export default { .... }

Worked for me and makes sense. Thanks @Arish-theGalaxyBea !

**Comment by evilebottnawi** [comment] 2020-09-02 12:47
I want to close this issue, because there are a lot of difference problems without configurations/reproducible test repos. Most of problems related to https://github.com/webpack/webpack/issues/4817#issuecomment-492194612. Anyway if you faced with this issue again, feel free to open new issue with reproducible test repo and we will help you, thanks for using webpack

**Closed by evilebottnawi** 2020-09-02 12:47 UTC

**Comment by jardicc** [comment] 2020-12-29 01:29
In my case, it was solved when I used "awesome-typescript-loader" instead of "ts-loader". I am not sure what is a difference between those loaders

**Comment by CommanderXL** [comment] 2021-02-21 08:55
If you using `@babel/plugin-transform-runtime` in your project，and one of your dependency in the `node_module` or file in your src dir that has been compiled for commonJs style by some bundle util like Webpack、Rollup. Your should exclude the file for the `babel-loader`. You can find the reason [here](https://babeljs.io/docs/en/options#sourcetype).

**Comment by flyskywhy** [comment] 2022-03-10 08:43
`rm -fr node_modules/.cache/*` may fix this issue as describe in doc [Upgrade to react-scripts@5 and Add Web Workers support](https://github.com/flyskywhy/g/blob/master/i%E4%B8%BB%E8%A7%82%E7%9A%84%E4%BD%93%E9%AA%8C%E6%96%B9%E5%BC%8F/t%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BD%93%E9%AA%8C/%E7%94%B5%E4%BF%A1/Tool/%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80/JavaScript/React%E4%BD%BF%E7%94%A8%E8%AF%A6%E8%A7%A3.md#upgrade-to-react-scripts5-and-add-web-workers-support) and `npm run web-fresh` in APP PixelShapeRN commit [Add Web Workers support for CRA v5 (and Webpack 5)](https://github.com/flyskywhy/PixelShapeRN/commit/3ea44d17d4978f53be833d0e24b07c6f09a1736f)
