### ISSUE TITLE
Errors appear duplicated in browser console

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#3008] opened 2016-09-18 09:13 UTC
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX

**Current behavior:**

Errors in the browser console appear duplicated, regardless of the loader:

<img width="584" alt="screen shot 2016-09-18 at 12 04 43" src="https://cloud.githubusercontent.com/assets/810438/18614527/ad7c0eb0-7d98-11e6-991e-bc63c04ff8d3.png">

<img width="543" alt="screen shot 2016-09-18 at 12 09 33" src="https://cloud.githubusercontent.com/assets/810438/18614536/c7d36bf0-7d98-11e6-8b67-8037429b3876.png">

**Expected/desired behavior:**

The error message should not be printed twice.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

``` sh
npm i -g create-react-app
create-react-app mystuff --scripts-version 0.5.1
cd mystuff
npm start
```

Then make a syntax error in `src/App.js` or `src/App.css` and inspect browser output.
You can find the config [here](https://github.com/facebookincubator/create-react-app/blob/bf12c41675cd278a9910e734f82d03e7fe0faf2f/config/webpack.config.dev.js).
- **What is the expected behavior?**

The error message should not be printed twice.
- **What is the motivation / use case for changing the behavior?**

Seeing it printed twice is confusing and annoying.
- **Browser:** all
- **Language:** all
---

(I file this in Webpack repo because the error string is passed to WDS already in this form.)

**Comment by gaearon** [comment] 2016-09-25 13:25
For now, I’m working around it like this:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/formatWebpackMessages.js

**Comment by SpaceK33z** [comment] 2016-11-04 23:06
I'll take a look at this soon, so assigning to me so I don't forget. If anyone wants to work at this, feel free to do so.

**Comment by SpaceK33z** [comment] 2016-11-05 19:48
This took some debugging, but I finally found where the issue is :). webpack-dev-server uses `stats.toJson()` (without parameters), gets the `errors` property from the resulting object and then passes that to the WebSocket to display the error. This `errors` property is an array of errors.

However, if `.toJson()` is used without options, it defaults to adding "error details" in the `errors` items. These details cause the duplicated message.

To fix this, I see two options:

1) Have webpack-dev-server use `.toJson({ errorDetails: false })`
2) or let the `.toJson()` method default to `errorDetails = false`.

I think option 1 is the most safe one, so I'll fix this in WDS.

**Comment by SpaceK33z** [comment] 2016-11-05 19:53
Fixed! This will be released with webpack-dev-server v2.

**Closed** 2016-11-05 19:52 UTC
Labels: bug, P2: Very Important, S2: Inconvenient, X4: work required
