### ISSUE TITLE
Chunk file names with new System.import syntax?

### ISSUE THREAD

**Issue by sikanhe** [webpack/webpack#2151] opened 2016-03-07 22:17 UTC
Is it possible to specify a name or uses the filename as chunk name for code splitting in webpack 2.0?

**Comment by kesne** [comment] 2016-03-09 05:25
This is a duplicate of #1949.

**Comment by bebraw** [comment] 2016-12-24 07:21
Closing as duplicate.

**Closed by bebraw** 2016-12-24 07:21 UTC
Labels: question, webpack-2
