### ISSUE TITLE
Expected compiled code Use Directly native es6 module

### ISSUE THREAD

**Issue by zhangenming** [webpack/webpack#7422] opened 2018-05-29 03:05 UTC
## Feature request

**What is the expected behavior?**
Expected compiled code Use Directly native es6 module

**What is motivation or use case for adding/changing the behavior?**

Because the browser environment supports

**How should this be implemented in your opinion?**
add a option

**Are you willing to work on this yourself?**
yes

**Comment by ooflorent** [comment] 2018-05-29 06:39
Duplicate of #2933

**Closed by ooflorent** 2018-05-29 06:39 UTC
