### ISSUE TITLE
Question: dynamically require a node module (ensure)

### ISSUE THREAD

**Issue by adjavaherian** [webpack/webpack#1500] opened 2015-10-08 00:59 UTC
I'm using the d3 library.  Its pretty big, so I only want to download the chunk on demand.  I can create the split point with require.ensure, but I'm lost as to how you actually get the library into the scope of the module.  This is as close as I can get, the chunk is downloaded, but d3 is always undefined. Any help would be greatly appreciated.

```javascript

var React = require('react');
var d3;

require.ensure([], function(require){

    d3 = require('d3');

});

var Chart = React.createClass({
    render: function() {
        var props = this.props;
        var width = props.width;
       
        //d3 is undefined here
        var xScale = d3.scale.linear().domain([
            0, 111
        ]).range([
            0, width
        ]);

        return (
            <g>
            </g>
        );
    }
});

module.exports = Chart;
```

**Comment by bebraw** [comment] 2015-10-08 08:48
The problem is that `require.ensure` is async. It will be `undefined` until loaded. At the very least you will need a check against this case at your `render` method.

You may also want to use lifecycle methods, such as `componentDidMount` (`require.ensure` here) and `componentWillUnmount` (clean up) for more control. This allows you to load D3 only when your component is loaded, not sooner.

**Comment by adjavaherian** [comment] 2015-10-09 22:21
Thanks @bebraw, this works in componentDidMount.  

```javascript
        require.ensure([], function(require){
            var d3 = require('d3');

            var xScale = d3.scale.linear().domain([
                0, medianIncome
            ]).range([
                0, width
            ]);

            newState.incomeBarWidth = xScale(medianIncome);
            newState.rentBarWidth = xScale(medianR);

            newState.medianRLabel = {
                text: '$' + Math.round(medianR),
                x: props.rBarWidth,
                y: height / 2
            };

            self.setState(_.extend(self.state, newState));

        }, 'd3');
```

**Comment by sokra** [comment] 2015-10-13 07:22
There is also https://github.com/webpack/react-proxy-loader whey loads react components on demand.

**Comment by adjavaherian** [comment] 2015-10-13 07:24
Thanks @tobias, its a library that’s used in a react module, so the require.ensure works well.

**Comment by bebraw** [comment] 2015-11-14 12:09
Closing given we managed to resolve this. :+1:

**Closed by bebraw** 2015-11-14 12:09 UTC
