### ISSUE TITLE
DefinePlugin process with object shorthand property incorrectly

### ISSUE THREAD

**Issue by lwr** [webpack/webpack#16764] opened 2023-03-01 07:26 UTC
# Bug report

**What is the current behavior?**

- config
```js
module.exports = {
    plugins : [
        new webpack.DefinePlugin({foo : 'aFoo', bar : 'aBar', crash : 'other.prop'})
    ]
}
```
- source code
```js
console.log({foo : foo, bar : bar}); // correct
console.log({foo, bar}); // incorrect
console.log({crash}); // SyntaxError: Unexpected token '.'
```
- translated code
```js
console.log({foo : aFoo, bar : aBar}); // correct
console.log({aFoo, aBar}); // incorrect
console.log({other.prop}); // SyntaxError: Unexpected token '.'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

the shorthand property should expand before translate with DefinePlugin,
and only property value can be translated

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 19.6.1
Operating System: macOs 13.2.1 (22D68)
Additional tools:

**Comment by alexander-akait** [comment] 2023-03-08 14:53
Yeah, thank you for an issue, duplicate of https://github.com/webpack/webpack/issues/14800, we have a PR, so let's close in favor https://github.com/webpack/webpack/issues/14800 and I will put a link on this PR to not lose your cases and add them to test cases

**Comment by vankop** [comment] 2023-03-10 06:44
@alexander-akait I guess this is another issue, it affects only DefinePLugin

**Closed** 2023-05-23 20:59 UTC
Labels: bug, X1: Inspection required, webpack-5
