### ISSUE TITLE
 [webpack-cli] TypeError: cli.isMultipleCompiler is not a function

### ISSUE THREAD

**Issue by dominikabieder** [webpack/webpack#15951] opened 2022-06-14 07:01 UTC
I'm getting `TypeError: cli.isMultipleCompiler `is not a function when running an app via docker. The node modules are installed, I'm using
```
"webpack": "5.72.1",
"webpack-cli": "4.9.2",
"webpack-dev-server": "4.8.0"
```
Any ideas what could be causing it?

Here's the full error
```
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
shared             |     at Command.<anonymous> (/app/node_modules/@webpack-cli/serve/lib/index.js:146:35)
shared             |     at async Promise.all (index 1)
shared             |     at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```

**Comment by snitin315** [comment] 2022-06-14 07:02
Please upgrade to the latest version of webpack-cli that is 4.10.0

**Comment by dominikabieder** [comment] 2022-06-14 07:05
I did, the error is still there

**Comment by snitin315** [comment] 2022-06-14 07:16
Duplicate of https://github.com/webpack/webpack-cli/issues/3294

```diff
   "webpack": "5.72.1",
-  "webpack-cli": "4.9.2",
+  "webpack-cli": "4.10.0", 
   "webpack-dev-server": "4.8.0"
```

**Comment by alexander-akait** [comment] 2022-06-14 12:59
Answer above, feel free to feedback

**Closed by alexander-akait** 2022-06-14 12:59 UTC

**Comment by CTaylorEason** [comment] 2022-06-20 14:41
Could someone show me the steps for how to update my webpack-cli to 4.10.0? I'm having the same issue, and I don't know how to properly update it in my IDE.

**Comment by CTaylorEason** [comment] 2022-06-20 22:22
Found the answer! Here is how you update your webpack-cli for anyone else who was curious. 

First, check your version of webpack by running this command in the terminal of your IDE: webpack --version. You should see a list that appears like this: 
webpack: 5.71.0
webpack-cli: 4.10.0     
webpack-dev-server 4.8.0

If your webpack-cli reads anything below 4.10.0, then you need to update it to the latest version for npm to run properly on your localhost with JHipster. Here's how to update it. 

Run this command in the terminal of your IDE: npm install webpack-cli@4.10.0

[Right now, the latest version is 4.10.0, but for the future updates when you run this command, change the version at the end of the command line to updated to that current version: npm install webpack-cli@(INSERT NEW VERSION DIGITS HERE).

Then re-run webpack --version, and see if your webpack has updated to the version that you entered above. 

**********
EXTRA NOTES: 

Why did you have this error? According to webpack.js.org: "Note that this is not a recommended practice. Installing globally locks you down to a specific version of webpack and could fail in projects that use a different version."

So, if you ran a command like this: npm install --global webpack, then there is a good chance that you were locked down to a specific version. This might have been the error. That's what I believe happened to me anyway. I ran npm install -g, or something of that nature. 

Sources for your journey and research that relate to the material above: 
1) https://webpack.js.org/guides/installation/
2) https://stackabuse.com/npm-install-specific-version-of-a-package/

*********

Hope this helps! Best of blessings to ya!

**Comment by maiabdu** [comment] 2022-07-02 04:44
fixed, but shows this error: Could not find a canister id to forward to.

**Comment by clairerhoda** [comment] 2022-07-28 15:10
> 

You can also just change the version in the package-lock.json file from "webpack-cli": "4.9.0" to "webpack-cli": "4.10.0". Then go into your terminal and run _**npm install**_ to update the changes.

**Comment by iSalah-YT** [comment] 2022-10-03 18:44
npm install --save-dev webpack-cli   this is work for me thx guys

**Comment by husayt** [comment] 2022-10-20 16:26
switching from npm to yarn helped me in this instance.

**Comment by andriihuchko** [comment] 2022-11-23 19:48
I resolved the issue simply running this command: npm install --save-dev webpack-cli

**Comment by navalega0109** [comment] 2023-07-18 22:32
> webpack --version

Even I'm Facing same issue after installing - `npm install webpack-cli@4.10.0`.
But I'm getting this error - **Could not find a canister id to forward to.**  after running my app in browser - [](http://localhost:8000/)

Let me know if issue is fixed for you. I know this has to be because of package-lock.json as this file not getting updated.
Any idea how to update package -lock.json?

**Comment by navalega0109** [comment] 2023-07-18 23:09
> 

I've resolved this issue.
Check the link to create [Canister](https://forum.dfinity.org/t/error-could-not-find-a-canister-id-to-forward-to/6302)

**Issue**

but now I'm facing new issue affter dfx deploy and npm start when I run the app on -  -[localhost](http://localhost:8080/), It is asking me username and password and I'm not sure which username and password is required here.

**Comment by anshvarma07** [comment] 2023-08-01 19:12
It's simple just find webpack-cli in package.json file and change version to latest version for today 2 August 2023 it's 5.1.4
change and save the file then write npm install then npm start it will surely work.

**Comment by ToruKiyono** [comment] 2023-12-16 09:48
npm upgrade --save-dev  webpack-cli webpack-dev-server
