### ISSUE TITLE
"watch" option doesn't work if config exports an array of builds

### ISSUE THREAD

**Issue by LendsMan** [webpack/webpack#2099] opened 2016-02-24 19:29 UTC
I have a webpack configs for two builds with  `watch: true` options. 
If I try `module.exports = {/*1st build*/}` or `module.exports = {/*2st build*/}` everything is fine.
But when I try to combine them into one like this:
`module.exports = [{/*1st build*/},{/*2d build*/}]`
and run `webpack` command it doesn't watch for changes. It just stops working like there is no `watch: true` option there.
But if I run `webpack --watch` it works and watches for changes.

Shouldn't those `watch: true` options work from inside the config? Or is `webpack --watch` the only way to do it?

**Comment by madHamish42** [comment] 2016-04-12 11:57
I have the exact same problem on Linux with webpack version 1.12.14

As far as I can see from the code of 'webpack.js' in 'webpack/bin' the reason for this is the following test at around line 180:
	if(options.watch) {...
	
The 'options' object is an array in the case of multiple configs, so this will always evaluate to false.

**Comment by bebraw** [comment] 2016-12-24 07:08
Can you try this against webpack 2 beta? Thanks.

**Comment by bebraw** [comment] 2017-01-17 08:14
Duplicate of #2664. Closing.

**Closed by bebraw** 2017-01-17 08:14 UTC
Labels: bug
