### ISSUE TITLE
throwing an error if I disable source map in uglifyjs plugin

### ISSUE THREAD

**Issue by thisguychris** [webpack/webpack#1385] opened 2015-08-24 01:59 UTC
I think this is a more appropriate location to file this issue:
https://github.com/webpack/extract-text-webpack-plugin/issues/98

I disabled extract text plugin and it still gives an error.  Its probably in webpack.

So just re posting this:

 I get an error if I turn off source map in 

``` javascript
new webpack.optimize.UglifyJsPlugin({
    compress: {
        warnings: false
    }
    , sourceMap: false
  })
```

I'm trying to disable source map since my build takes 5 minutes long.  Removing it yields 1 minute 40 seconds.

Here's part of my stack trace

``` javascript
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/var/www/project/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
    at Array.forEach (native)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:136:4)
    at Tapable.applyPluginsAsync (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/Compilation.js:564:9)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/var/www/project/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Tapable.applyPluginsAsync (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/Compilation.js:560:8)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/var/www/project/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at done (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:248:21)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:44:16
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:270:6
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at done (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:248:21)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:44:16
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:267:13
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:187:20
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:239:13
    at _arrayEach (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:91:13)
    at _each (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:215:22)
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:241:11
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:187:20
```

**Comment by SimenB** [comment] 2015-08-24 07:14
What's your `devtool`?

**Comment by deezahyn** [comment] 2015-08-24 09:52
I don't have it on my webpack config since this is for production.

**Comment by sokra** [comment] 2015-08-26 10:41
try to reinstall all dependencies.

**Comment by deezahyn** [comment] 2015-08-27 02:08
@sokra just tried reinstalling dependencies.  Still getting the same error on build:

```javascript
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer 
```

**Comment by deezahyn** [comment] 2015-08-27 02:26
@sokra I've setup a sample repo to reproduce the bug:
https://github.com/deezahyn/webpack-production-test

**Comment by angelomichel** [comment] 2015-09-04 08:59
I am getting the same error here when using sourcemap false and --optimize-minimize (if I leave the optimize out it works).

**Comment by hanai** [comment] 2015-11-26 07:07
same error

**Comment by sercaninaler** [comment] 2015-11-27 10:25
+1

**Comment by indiejoseph** [comment] 2015-11-30 02:33
+1

**Comment by sokra** [comment] 2015-11-30 08:28
when using `new UglifyJsPlugin` **and** `--opimize-minimize` (or `-p`) you are adding the UglifyJsPlugin twice. Omit the CLI option.

**Comment by sercaninaler** [comment] 2015-12-17 13:54
Thanks so much @sokra, This helped me!

**Comment by macbury** [comment] 2016-04-12 14:27
+1

**Comment by guzmonne** [comment] 2016-04-21 14:52
Thanks @sokra it also fixed it for me

**Comment by Intey** [comment] 2016-05-02 14:27
Have similar issue, but i don't specify `sourceMap: false`. Only when i declare this, build pass.

**Comment by Zjaaspoer** [comment] 2016-05-22 11:38
Thanks @sokra, you fixed this bug for me too :)

**Comment by jquintozamora** [comment] 2016-11-20 18:13
Thanks @sokra it also fixed it for me as well

**Comment by hypery2k** [comment] 2016-11-22 09:01
you can also try this:
```
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      filename: null, 
      lineToLine: true,
      module: false,
      test: /\.(ts|map|js)($|\?)/i 
    }),
```

**Comment by thisguychris** [comment] 2016-11-27 12:42
@sokra removing `-p` does indeed fixes it for me.  Is this intended behavior though? if a flag in cli doe the same thing in config, it will just apply it twice?

I'll gladly make a PR if you can just give me pointers where to look.  Let me know if we don't plan to fix this, and I'll have this close.

**Comment by johnnyghost** [comment] 2016-11-29 13:59
Thanks @sokra!

**Comment by xiguaaxigua** [comment] 2017-01-22 03:04
thanks @sokra , fixed this bug

**Comment by luoyjx** [comment] 2017-03-15 07:50
+1
fix by remove `-p`

**Comment by deot** [comment] 2017-03-27 14:34
+1
fix by remove -p

**Comment by ulfryk** [comment] 2017-05-05 10:01
@sokra thank you vey much :D

**Comment by isaac2004** [comment] 2017-06-02 10:25
Is there a fix coming for this? In my opinion Webpack should be smart enough to omit one or the other f both are present.

**Comment by roeycohen** [comment] 2018-02-12 11:15
when using yarn, you could add this to your package.json file:
```
"resolutions": {
    "webpack/uglifyjs-webpack-plugin": "^1.1.8"
  },
```
this will replace webpack original dependency with a more recent one, so you could still use -p switch.

**Comment by ReeganExE** [comment] 2018-02-21 16:31
With **Webpack 4**, `mode: 'production'` will automatically add optimizations plugins.

If you get the following warning/error message when building with  `mode: 'production'`, try fixing by below instruction.
```
TypeError: Cannot read property 'sections' of null 👉 Remove `new UglifyJsPlugin` from config
schema id ignored LoaderOptionsPlugin              👉 Remove `new LoaderOptionsPlugin` plugin from config
schema id ignored SourceMapDevToolPlugin           👉 Remove `devtool` config
```

**Comment by damianobarbati** [comment] 2018-02-25 13:10
@ReeganExE if I remove `new UglifyJsPlugin` from config then how can I customize uglify options? (webpack@4)

**Comment by ashtrie** [comment] 2018-02-26 12:27
do not remove UglifyJsPlugin, just add `sourceMap: true` to its config

**Comment by damianobarbati** [comment] 2018-02-26 12:53
@ashtrie thanks but I don't get it: where do I define uglify-es configuration? 
All I have are package.json and webpack.config.js to configure my project.

Plus sourcemaps seems to link to transpiled code and not original source: not sure whether uglify or webpack issue (https://github.com/webpack/webpack/issues/6567#issuecomment-368487038)

**Comment by ReeganExE** [comment] 2018-02-26 12:56
@damianobarbati, you might pass it as `minimizer` option rather than push it as plugin part.
```js
const configs = {
  mode: "production",
  entry: "./index",
  output: {
    filename: "bundle.js"
  },
  optimization: {
    minimize: true,
    minimizer: [
      new UglifyJsPlugin({
        sourceMap: true,
        uglifyOptions: {
          // ...
        }
      })
    ]
  }
};
```

**Comment by damianobarbati** [comment] 2018-02-26 13:14
Thanks @ReeganExE, I made it.

**Comment by pbrain19** [comment] 2018-02-26 17:52
None of the fixes above have worked for me. Here are my configs and error. Any idea why it wouldn't work 

`    
const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const uglify = require('uglify-js');

const env = process.env.NODE_ENV;
const root = 'src';

/**
 * @param {Boolean} tranformCopy - boolean to signal if build should minify copied js
 */
module.exports = (tranformCopy) => {

    return {
        mode: 'production', 
        resolve: {
            modules: ['node_modules', 'bower_components', (path.resolve(__dirname, './src/app'))],
            alias: { 'chart.js': 'Chart.js/Chart.js' }
        },
        entry: {
            app: [
                'babel-polyfill',
                path.join(__dirname, root, 'clutch.js')
            ],
            vendorjs: path.join(__dirname, root, 'vendor.js'),
            vendorstyle: path.join(__dirname, root, 'style.js'),
            templates: path.join(__dirname, root, 'templates.js')
        },
output: {
    filename: '[name].[chunkhash].js',
    publicPath: '/',
    path: path.resolve(__dirname, 'build'),
    chunkFilename: '[name].[chunkhash].js'
},
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /(node_modules|bower_components)/,
                    use: [
                        'ng-annotate-loader',
                        {
                            loader: 'babel-loader',
                            options: {
                                cacheDirectory: true
                            }
                        }
                    ],
                    parser: {
                        amd: false
                    }
                },
                {
                    test: /\.html$/,
                    include: path.resolve(__dirname, 'src', 'app'),
                    use: [
                        {
                            loader: `ngtemplate-loader?relativeTo=${path.resolve(__dirname, 'src', 'app')}`
                        },
                        {
                            loader: 'html-loader'
                        }
                    ]
                },
                {
                    test: /\.(scss|sass)$/,
                    exclude: /(node_modules|bower_components)/,
                    use: ['style-loader',
                        {
                            loader: 'css-loader'
                        },
                        'sass-loader']
                },
                {
                    test: /\.css$/,
                    use: ['style-loader',
                        {
                            loader: 'css-loader'
                        }
                    ]
                },
                {
                    test: /\.(eot|ttf|woff|woff2)$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: '[name].[ext]',
                                outputPath: 'fonts/'
                            }
                        }
                    ]
                },
                {
                    test: /\.(svg|png|jpg|jpeg|ico)$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: '[name].[ext]',
                                outputPath: 'img/'
                            }
                        }
                    ]
                }
            ]
        },
        plugins: [
// Injects bundles in your index.html instead of wiring all manually.
    new HtmlWebpackPlugin({
        template: 'src/index.html',
        inject: 'body',
        minify: {
            caseSensitive: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            minifyJS: true,
            keepClosingSlash: true,
            collapseBooleanAttributes: true,
            preserveLineBreaks: false
        }
    }),
            // copies moment locales into public folder.
            new CopyWebpackPlugin([
                {
                    from: 'node_modules/moment/locale/*.js',
                    to: 'locale/moment'
                },
            ]),

            // copies angular-i18n locales into public folder.
            new CopyWebpackPlugin([
                {
                    from: 'node_modules/angular-i18n/*.js',
                    to: 'locale/angular-local',
                    flatten: true
                },
            ]),

            // copies language files to into public folder.
            new CopyWebpackPlugin([
                {
                    from: 'src/locale/*.js',
                    to: 'locale/dashride'
                },
            ]),

            // ensures only english locale loaded from moment.
            new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/),

            // injects modules by alias into each file.
            new webpack.ProvidePlugin({
                $: 'jquery',
                _: 'lodash',
                Chart: 'Chart.js/Chart.js',
                'chart.js': 'Chart.js/Chart.js',
                moment: 'moment',
                jQuery: 'jquery',
                'window.jQuery': 'jquery'
            })
        ]
    };
};

`

The error is 

`TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/home/paul/Documents/dashride-dispatch/node_modules/source-map/lib/source-map-consumer.js:20:19)
    at /home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/index.js:141:27
    at Array.forEach (native)
    at UglifyJsPlugin.optimizeFn (/home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/index.js:122:142)
    at _err0 (eval at create (/home/paul/Documents/dashride-dispatch/node_modules/tapable/lib/HookCodeFactory.js:1:0), <anonymous>:12:1)
    at /home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/index.js:262:11
    at step (/home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /home/paul/Documents/dashride-dispatch/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at /home/paul/Documents/dashride-dispatch/node_modules/worker-farm/lib/farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by ReeganExE** [comment] 2018-02-28 09:59
```js
new HtmlWebpackPlugin({
    template: 'src/index.html',
    inject: 'body',
    minify: {
        // ...
        minifyJS: true,
        // ...
    }
})
```
@pbrain19, try removing  `minifyJS: true` from your `HtmlWebpackPlugin` config.

**Comment by evilebottnawi** [comment] 2018-03-15 15:32
Closing due original problem was solved. If you have problem please create new issue or use stackoverflow or slack. Thanks everyone :+1:

**Closed by evilebottnawi** 2018-03-15 15:32 UTC
Labels: bug

**Comment by pardoman** [comment] 2018-08-01 00:50
Another way I was able to get rid of this issue was by removing `devtool: 'source-map'` from webpack config.
