### ISSUE TITLE
Nested (array) output.library is failing

### ISSUE THREAD

**Issue by jaguilar87** [webpack/webpack#8099] opened 2018-09-27 08:58 UTC
# Bug report

▶️ You can try this repo to reproduce the bug: https://github.com/jaguilar87/webpack-issue-8099

**What is the current behavior?**
Since `4.20.0` I am unable to build using nested output.library:

```js
{
       entry: {
            a: path.resolve(__dirname,  'a.js'),
            b: path.resolve(__dirname, 'b.js'),
       },
       output: {
            jsonpFunction: `webpackJsonp__[name]`,
            library: ['globalVariable', '[name]'],
            filename: `[name]--[chunkhash].js`,
            path: path.resolve(__dirname, 'dist'),
            publicPath: '/',
        },
...
```

The output file starts with:
`var undefined = ...`

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the previous configuration and try to build a package.

**What is the expected behavior?**
The output file should start with:
```
var globalVariable = typeof globalVariable === "object" ? globalVariable : {}; globalVariable["a"] = ...
```

**Other relevant information:**
webpack version:  4.20.0-4.20.2
Node.js version:  v9.6.1
Operating System: Mac OS High Sierra

**Comment by montogeek** [comment] 2018-09-27 10:58
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by jaguilar87** [comment] 2018-09-27 12:41
> Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

Thanks for the suggestion,

Here's the repo: https://github.com/jaguilar87/webpack-issue-8099

You can see the results on https://github.com/jaguilar87/webpack-issue-8099/blob/master/dist/a--86076cc50f07890984bf.js

**Comment by sokra** [comment] 2018-10-01 07:47
Duplicate of #8111

Opportunity to send a PR

**Comment by sokra** [comment] 2018-10-01 07:48
Opportunity to send a PR

**Closed by sokra** 2018-10-01 07:47 UTC
Labels: Send a PR
