### ISSUE TITLE
Tree shaking not working for functions executed in JS file when compared with Rollup

### ISSUE THREAD

**Issue by ankurp** [webpack/webpack#4784] opened 2017-04-26 13:36 UTC
**Do you want to request a *feature* or report a *bug*?**

This is a bug where the same project can tree shake and remove unused code when bundled with Rollup but it does not when bundle is generated with webpack 2. To replicate and give an example I have created a repo to replicate this bug https://github.com/ankurp/rollup-webpack-test/

**What is the current behavior?**

Webpack 2 should remove code that is not used even if a function or class defined in a JS file gets executed. For example the following code below should remove the square function and the `getSquare` function which it does when bundled with Rollup but when bundling with Webpack 2 it includes `getSquare` because that function is invoked in the `math.js` file. This is the wrong behavior when compared with rollup which removes that unused function as well.

```js
// math.js
function getSquare() { return x => x * x; }
export const square = getSquare();
export const cube = x => x * x * x;

// index.js
import { cube } from './math';
console.log(cube(3));
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Best way to reproduce is to run `yarn` and then `yarn build` in this repo https://github.com/ankurp/rollup-webpack-test/

The repo has three basic JS files to replicate this bug and also generates both rollup and webpack output for comparison with optimized compressed builds on which tree shaking is performed.

**What is the expected behavior?**

Webpack 2 should remove `getSquare` function from the bundle as it is not imported or used.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is a bug that needs to be fixed so that the tree shaking feature works as expected.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This was run using webpack 2.

**Comment by mbilokonsky** [comment] 2017-04-26 13:46
paging @TheLarkInn who knows everything about webpack.

**Comment by jouni-kantola** [comment] 2017-04-26 23:56
@ankurp: I added a manifest chunk to strip out the webpack runtime. When I run your example with webpack `2.2.0` (as you use in your repo), I get the following output, which represents the bug you've reported:
```javascript
webpackJsonp(
  [0, 1],
  [
    function(n, t, r) {
      "use strict";
      r(1);
      r.d(t, "a", function() {
        return u;
      });
      var u = function() {
        return 1;
      };
    },
    function(n, t, r) {
      "use strict";
      function u() {
        return function(n) {
          return n * n;
        };
      }
      var e = (u(), function(n) {
        return n * n * n;
      });
      e(3);
    },
    function(n, t, r) {
      "use strict";
      Object.defineProperty(t, "__esModule", { value: !0 });
      var u = r(0);
      console.log(r.i(u.a)());
    }
  ],
  [2]
);
```

With webpack `2.4.1`, I get the following output:
```javascript
webpackJsonp(
  [0],
  [
    function(n, t, e) {
      "use strict";
      e(2);
      e.d(t, "a", function() {
        return u;
      });
      var u = function() {
        return 1;
      };
    },
    function(n, t, e) {
      "use strict";
      Object.defineProperty(t, "__esModule", { value: !0 });
      var u = e(0);
      console.log(e.i(u.a)());
    },
    function(n, t, e) {
      "use strict";
    }
  ],
  [1]
);
```

Update to the latest version of webpack and have another go.

**Comment by ankurp** [comment] 2017-04-27 00:08
Thanks will try and let everyone know.

**Comment by ankurp** [comment] 2017-05-03 14:29
This is not fixed 100%. I see that in my example it was able to remove the code but when I use it in a react app with one component it is not able to tree shake. I will update the example as it is still an issue.

**Comment by ankurp** [comment] 2017-05-03 14:58
I updated the example in my repo and now exporting a react component https://github.com/ankurp/rollup-webpack-test/blob/master/app/lib.js#L2 and I see the ReactComponent does not get removed even when it is not used at all in the index.js which is the entry point https://github.com/ankurp/rollup-webpack-test/blob/master/app/index.js

**Comment by ankurp** [comment] 2017-05-03 15:00
@TheLarkInn any help regarding this would be appreciated as I am using the latest version of webpack. If this is a known issue please let us know as well so we can consolidate the issues.

**Comment by ankurp** [comment] 2017-05-03 15:09
One other thing I noticed is that when you extend from React.Component, unused code does not get removed. But if I use stateless component then the component code is removed as it is not used.

**Comment by jouni-kantola** [comment] 2017-05-03 15:55
Now that you're using a class instead these issues come into play:
webpack: https://github.com/webpack/webpack/issues/4080
uglify: https://github.com/mishoo/UglifyJS2/issues/1261

**Comment by markbrocato** [comment] 2017-05-31 21:09
Here is another very simple example which illustrates the bug:  

https://github.com/markbrocato/webpack-tree-shaking-exports/blob/master/README.md

The presence of any function call in an export's declaration results in webpack being unable to shake it out of the tree.

**Comment by dmitriid** [comment] 2017-09-15 10:34
The bug is still there, another simple example https://github.com/dmitriid/webpack-dec-tree-shaking

**Comment by istiti** [comment] 2017-10-24 21:06
+++++++++++++  1

@TheLarkInn

**Comment by xiachaoxulu** [comment] 2017-11-16 09:52
so， how to do？

**Comment by DevSide** [comment] 2017-12-08 16:35
I use  explicit` /*#__PURE__*/ `as a workaround.

```js
const getSquare = /*#__PURE__*/ function getSquare () { return x => x * x; }
export const square = getSquare();
```

**Comment by edmorley** [comment] 2018-03-13 00:15
This works now for me with webpack 4.

ie:
1. `yarn add webpack webpack-cli`
2. Create these files:
```js
// src/index.js
import { cube } from './math';
console.log(cube(3));
```

```js
// src/math.js
function getSquare() { return x => x * x; }
export const square = getSquare();
export const cube = x => x * x * x;
```

```js
// webpack.config.js
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
  mode: 'production',
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          warnings: true,
          mangle: false,
          output: {
            beautify: true,
            comments: true
          }
        }
      })
    ]
  }
};
```
3. Run `yarn webpack`

The command output includes:
```
Dropping unused variable square [main.js:81,6]
```

And `dist/main.js` has contents:
```js
/******/ !function(modules) {
    // webpackBootstrap
    // ...
/************************************************************************/
/******/ ([ 
/* 0 */
/***/ function(module, __webpack_exports__, __webpack_require__) {
    "use strict";
    __webpack_require__.r(__webpack_exports__);
    // CONCATENATED MODULE: ./src/index.js
    console.log((x => x * x * x)(3));
}
/******/ ]);
```

**Comment by edmorley** [comment] 2018-10-18 12:01
I believe this can be closed since it should be fixed in webpack 4 (see above).

**Comment by evilebottnawi** [comment] 2018-10-18 12:16
@edmorley Thanks!

**Closed by evilebottnawi** 2018-10-18 12:16 UTC

**Comment by josdejong** [comment] 2018-12-01 10:17
@edbedbe I encountered a very similar issue of webpack 4.26.1 not being able to do tree shaking. I'm not sure if this can actually be improved or not, whether it's possible to detect that a specific function call doesn't have side effects.

```js
// index.js
import { cube } from './math'

console.log('cube(3) = ' + cube(3))
```

```js
// math.js
export function factory (name, deps, fn) {
  const instance = function (args) {
    return fn(deps, args, 'TEST3')
  }

  fn.factoryName = name + 'TEST4'
  return instance
}

export const hello = factory('TEST1', {}, () => {
  return 'TEST2'
})

export const cube = x => x * x * x
```
Run webpack cli:
```
webpack index.js -o index.bundle.js --mode production
```
This generates a bundle `index.bundle.js` containing the strings "TEST1", "TEST2", "TEST4". In the code, only the exported function `cube` is used. The functions `factory` and `hello` are not used can be removed from the bundle.

A working workaround is to use `export const hello = /*#__PURE__*/ factory(...)` (see https://github.com/webpack/webpack/issues/4784#issuecomment-350308570)

Repo with code reproducing this issue: https://github.com/josdejong/webpack_tree_shaking_issue
