### ISSUE TITLE
The new webpack default watcher (previously new webpack.NewWatchingPlugin()) doesn't work correctly in v1.13.0

### ISSUE THREAD

**Issue by sgarcia-dev** [webpack/webpack#2439] opened 2016-05-05 13:35 UTC
See:
http://stackoverflow.com/questions/29292492/why-is-webpack-watch-not-updating-when-specific-files-are-updated
and:
http://stackoverflow.com/questions/37051262/webpack-w-or-webpack-dev-server-doesnt-update/37051963#37051963

Personally, ran into this on windows 7 and node v6.0

**Comment by neclepsio** [comment] 2016-05-18 12:40
I have the same problem, and maybe found the cause and a workaround. I'm using Windows too, I followed what in https://webpack.github.io/docs/troubleshooting.html. 

Using OldWatchPlugin was not possible for me because of https://github.com/TypeStrong/ts-loader/issues/155. 

I added a debug line to Compiler.js:

```
Watching.prototype.watch = function(files, dirs, missing) {
        console.log(files);
	this.watcher = this.compiler.watchFileSystem.watch(files, dirs, missing, this.startTime, this.watchOptions, function(err, filesModified, contextModified, missingModified, fileTimestamps, contextTimestamps) {
```

The file names I want to watch are printed with the correct path separator:

```
...
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\public\\css\\styles.css',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\public\\images\\angular.png',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\app\\app.component.css',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\app\\app.component.html',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\app\\app.component.ts',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\index.html',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\main.ts',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\polyfills.ts',
  'd:\\Users\\neclepsio\\Desktop\\New folder (2)\\src\\vendor.ts',
...
```

But, when I renamed "New Folder (2)" to New_folder_2, it started working.

**Comment by SpaceK33z** [comment] 2016-10-12 19:16
Dupe of #2258.

**Closed by SpaceK33z** 2016-10-12 19:16 UTC
Labels: bug
