### ISSUE TITLE
WebpackMissingModule generates a syntax error when preceded by new

### ISSUE THREAD

**Issue by tleef** [webpack/webpack#6191] opened 2017-12-24 00:15 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
[WebpackMissingModule](https://github.com/webpack/webpack/blob/master/lib/dependencies/WebpackMissingModule.js) generates a syntax error when preceded by `new`

*From [node-mongodb-native](https://github.com/mongodb/node-mongodb-native/blob/6eede9885ec8b50bf54681c6aba0fc28c8721e7c/lib/collection.js#L3001-L3005)*

```
collection = new require('./db')(
  doc.db,
  self.s.db.s.topology,
  self.s.db.s.options
).collection(doc.collection);
```
will produce
```
collection = new !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())('./db')(
  doc.db,
  self.s.db.s.topology,
  self.s.db.s.options
).collection(doc.collection);
```
which throws
```
"SyntaxError: Unexpected token !"
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Download [this gist](https://gist.github.com/tleef/96a8b914bcb3280da21ecc2e0371f467/archive/addae66ed9c6af1bec02a6fae30e4e777edfe5f7.zip)
2) Unzip and cd into the directory
3) `yarn install`
4) `yarn run webpack`
5) `node dist/index.js`

**What is the expected behavior?**
To generate code that is free of this syntax error

One possible fix is to replace
```
`!(function webpackMissingModule() { ${exports.moduleCode(request)} }())`
```
with
```
`(!(function webpackMissingModule() { ${exports.moduleCode(request)} }()))`
```
or something similar

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js version: v8.9.1
webpack version: ^3.10.0
OS: macOS High Sierra 10.13.2

**Comment by NugzarGaguliya** [comment] 2017-12-27 12:22
Have you find solution?

**Comment by sokra** [comment] 2017-12-27 16:22
Yeah, that's probably a bug.

But consider that `new require('./db')()` is wrong anyway, because it equal to `var x = new require('./db'); x();`, that's probably not the highest priority...

**Comment by simonbuchan** [comment] 2018-02-14 00:40
Same bug with `require.foo = foo`, which gets turned into `!(function ...)().foo = foo` which is also a syntax error. This pattern is used in [`react-native`](https://github.com/facebook/react-native/blob/d220118dbd7a936942f0cd3db69bf03f39333d6c/Libraries/Performance/Systrace.js#L324), and has to be worked around when used by, e.g. haul, with [a custom babel transform](https://github.com/callstack/haul/blob/a4d48d7b1b3f8df433b8b13e3abe619c4b8d3051/src/utils/fixRequireIssues.js)

**Comment by ooflorent** [comment] 2018-04-04 15:42
@simonbuchan That's interesting. Could you open a new issue with this?

**Comment by simonbuchan** [comment] 2018-04-04 18:57
Do you mean for the non-calling usage of `require` as a random property bag? I'm not sure that *should* be fixed, it's one of many silly things react native do that they shouldn't, and I don't see a good way to fix that without breaking other uses but I'll open a separate issue later today so it can be discussed.

**Comment by ooflorent** [comment] 2018-04-04 19:30
@simonbuchan yes, this usage. It should be fixed because webpack should not emit invalid JS.

**Comment by simonbuchan** [comment] 2018-04-04 19:36
Well that bit is the bit that would be fixed by fixing this bug, which is why it's here, but just adding parens wouldn't mean the RN code in question would behave as expected - that's the part I was referring to.

**Comment by Janpot** [comment] 2018-04-05 05:07
@simonbuchan I can't seem to reproduce that invalid code in latest webpack. Are you using a specific configuration? In any case, It may not immediately look like it, the root cause is different than this issue.
@ooflorent It seems related to https://github.com/webpack/webpack/issues/5209. Which I can't seem to reproduce as well.

**Closed** 2018-04-09 06:24 UTC

**Comment by mzealey** [comment] 2019-01-03 15:32
This happened for me when I was including a file that didn't exist

**Comment by DamienCassou** [comment] 2020-02-18 14:31
> This happened for me when I was including a file that didn't exist

same for me. I would have prefer `webpack` to crash immediately instead of producing code failing in production.
