### ISSUE TITLE
watchOptions.ignored RegExp doesn't seem to work in Webpack 5

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack#12394] opened 2021-01-11 15:20 UTC
# Bug report

**What is the current behavior?**
Files matching `RegExp` set to `watchOptions.ignored` is not ignored and triggers rebuilds.

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone this repo:
https://github.com/JonWallsten/monorepo-new/tree/webpack-5-issue
Start dev server as instructed in README.md
Change file `ignored.ts`

**What is the expected behavior?**
Changing files matching the pattern in `watchOptions.ignored` should not trigger a rebuild.

**Other relevant information:**
webpack version:  5.12.3
webpack-cli version:  4.3.1
webpack-dev-server version:  3.11.1
Node.js version: 14.15.1
Operating System: Windows 10
Additional tools: Angular

**Comment by alexander-akait** [comment] 2021-01-11 15:32
No problems on webpack side, check plugins and loaders

**Comment by JonWallsten** [comment] 2021-01-11 15:36
The webpacks watcher is not causing the rebuild? Can you who triggered the rebuild if you debug the code somehow? For example in the WatchRun hook?

**Comment by alexander-akait** [comment] 2021-01-11 15:43
Please simplify the configuration as soon as possible in the future for bug reporting and watch what happens, most of bugs you will found yourself, big repos = take a long time = other developers don't get help

**Comment by JonWallsten** [comment] 2021-01-11 15:47
Sure, I'll strip it down as much as possible.
So just to check, even to a file is ignored it should still trigger a change in watchpack?
Then the loader should ignore it? Or am I misunderstanding you? 
![image](https://user-images.githubusercontent.com/5993909/104203607-a183dd80-542c-11eb-96c6-9f856efd04b1.png)
![image](https://user-images.githubusercontent.com/5993909/104203512-83b67880-542c-11eb-9095-e06440e727e6.png)

**Comment by alexander-akait** [comment] 2021-01-11 15:49
I can't reproduce, all works fine on linux (ubuntu)

**Comment by alexander-akait** [comment] 2021-01-11 15:53
Something wrong with merging configurations, because in watchpack we have `{ aggregateTimeout: 0 }` options

**Comment by JonWallsten** [comment] 2021-01-11 15:54
Yeah, I noticed that. But since I reloaded the page by mistake my original ticket got lost including that screenshot:
![image](https://user-images.githubusercontent.com/5993909/104204533-ac8b3d80-542d-11eb-8332-d3165fd467a3.png)

**Comment by alexander-akait** [comment] 2021-01-11 15:56
Because somebody change file, no magic here

**Comment by JonWallsten** [comment] 2021-01-11 15:57
> Because something changes file, no magic here

Yeah, that's fine. It was the difference between the watchOptions that caught my eye.

**Comment by alexander-akait** [comment] 2021-01-11 16:13
In future you can use:
```
infrastructureLogging: {
            level: 'log'
        },
```

and webpack-cli will report what is changed

**Comment by JonWallsten** [comment] 2021-01-11 16:15
If I'm not mistaken we tried to use that last time when we investigated the ResolverCache issue and it didn't work. But I will try again next time. Thanks!

**Comment by alexander-akait** [comment] 2021-01-11 16:26
Found problem, move `watchOptions` to `devServer.watchOptions`, old version of `webpack-dev-middelware` (v3) is not respected global `watchOptions` configuration, it is fixed in v4 (https://github.com/webpack/webpack-dev-middleware/blob/master/src/index.js#L57), but we are still working on updating webpack-dev-server

**Closed by alexander-akait** 2021-01-11 16:26 UTC
