### ISSUE TITLE
Scaling to large codebases

### ISSUE THREAD

**Issue by unindented** [webpack/webpack#1905] opened 2016-01-19 11:17 UTC
I have a codebase with ~2000 JS files (no loaders), ~500 CSS files (`style!css!postcss!`), and ~500 Mustache templates (`mustache!`). The build time on a beefy box is ~5min. What are my options to decrease this time?

The build is CPU-bound as far as I can tell. Webpack runs single-threaded, but I can't think of a way around that.

The thing is, on a certain build, only a handful of files have changed from the previous one. When webpack is in `watch` mode, it can rebuild super quickly (I'm guessing because it only builds the parts that are affected by the change). Couldn't the same strategy be applied to normal builds?

@sokra @bebraw Does anything in Webpack 2 address this? If it doesn't, could you give me some pointers on persisting the dependency tree across builds to achieve fast builds? Or maybe some other ideas that you have?

**Comment by bebraw** [comment] 2016-01-19 11:19
Maybe `DllPlugin` could fit your use case? See https://webpack.github.io/docs/build-performance.html and https://github.com/webpack/webpack/tree/master/examples/dll .

**Comment by unindented** [comment] 2016-01-19 11:25
I'll look into that, thank you!

Manually maintaining the list of files that don't change isn't ideal, so if you have plans for the future please let me know!

**Comment by bebraw** [comment] 2016-01-19 11:28
> Manually maintaining the list of files that don't change isn't ideal, so if you have plans for the future please let me know!

Maybe that's something that could be [globbed](https://www.npmjs.com/package/glob)?

**Comment by unindented** [comment] 2016-01-19 11:29
For vendor files yes, but that's just a small part of this codebase...

**Comment by bebraw** [comment] 2016-01-19 11:48
Ok. Here's one direction: https://github.com/amireh/happypack, https://github.com/trivago/parallel-webpack .

**Comment by unindented** [comment] 2016-01-19 11:56
I'll look into those too, thank you so much!

**Comment by Globegitter** [comment] 2016-01-19 16:16
@unindented I guess this issue could be of interest to you as well: https://github.com/webpack/webpack/issues/250

**Comment by unindented** [comment] 2016-01-19 16:48
@Globegitter thanks for the heads up!

**Comment by karlnp** [comment] 2016-01-19 21:00
Move source dirs in your config.module.resolve from `moduleDirectories` to `root` where possible - it should cut down quite a bit on compilation time on incremental compiles, since the aggregate delay of searching moduleDirectories seems to be significant. see #1574 and particularly https://github.com/webpack/webpack/issues/472#issuecomment-55706013

**Comment by unindented** [comment] 2016-01-20 13:11
@karlnp I only have `node_modules` in the `moduleDirectories` directive...

**Comment by unindented** [comment] 2016-01-20 14:06
@bebraw Your advice to go back to version `0.14` of `css-loader` in some other thread was actually pretty effective. It has cut down the build time by ~30%.

**Comment by larryhe** [comment] 2016-02-09 03:23
Hi @unindented , did your build time get shorter? I have the similar issue as yours. Our project has a huge codebase with over 900 modules. rebuild the whole project takes about 3 minutes which is absolutely acceptable given that we have a huge code base. But the biggest problem is incremental build time is incredibly long and each time whatever file you change, you have to wait about 3 minutes for webpack to finish compile and bundle. I tried all the tips on http://webpack.github.io/docs/build-performance.html but seems not working. I thought it might be each of our chunk is too big or all the code mangled together and each file changed will cause the whole application to rebuilt. So I wrote a really small test file and split it out in entry file. But still whenever I change the test file, it took almost 3 minutes to build the test module, which does not make any sense at all. because incremental build is similar to rebuild. you said when webpack is in watch mode, it can rebuild super quickly. so my question is how many seconds is your incremental build?  Could you share your webpack.config here?  My webpack.config is as following. Did not get any ideas on how to shorten my incremental build yet. we didn't care too much about rebuild time though. Thanks. 

```
'use strict'
var webpack = require('webpack')
var path = require('path')
var excludes = require('./excludes');


module.exports = {
    'entry': {
        'common.base': ['cssua', 'jquery','backbone', 'underscore'],
        'entry1': 'entry1',
        'entry2': 'entry2',
        'entry3': 'entry3'
    },
    'output': {
        'pathinfo': true,
        'path': path.join(__dirname, 'dist'),
        'publicPath': '/resources/dist/',
        'filename': '[name].js'
    },
    cache: true,
    plugins: [
        new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),
        new webpack.ProvidePlugin({ _: 'underscore'}),
        new webpack.ProvidePlugin({ cssua: 'cssua'}),
        new webpack.optimize.CommonsChunkPlugin({name: 'common.base', minChunks: 2}),
        new webpack.SourceMapDevToolPlugin({
            filename: '[file].map',
            exclude: excludes,
            columns: false, // no columns in SourceMaps
            module: true // use SourceMaps from loaders
        })
    ],
    'resolve': {
        'root': [
            path.join(__dirname, './')
        ],
        'alias': {
            'cssua': 'lib/cssua',
            'backbone': 'lib/backbone/backbone',
            'underscore': 'lib/underscore/underscore',
            'backbone.paginator': 'lib/backbone.paginator/lib/backbone.paginator',
            'jquery': 'lib/jquery/dist/jquery',
            'snap.svg': 'lib/Snap.svg/dist/snap.svg'
        }
    },
    module: {
        'noParse': [/moment.js/, /base64.js/],
        'loaders': [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: excludes,
                query: {
                    cacheDirectory: true,
                    presets: 'es2015',
                    compact: false
                }
            },
            {
                'test': /\.hbs$/,
                'loader': 'handlebars-loader',
                'query': {
                    runtime: 'handlebars/runtime',
                    helperDirs: [
                        __dirname + "/templates/helpers"
                    ],
                    partialDirs: [
                        __dirname
                    ]
                }
            },
            {
                'test': /base64/,
                'loader': 'imports?this=>window'
            },
            {
                'test': /snap.svg/,
                'loader': 'imports?this=>window,fix=>module.exports=0'
            }
        ]
    }
}
```

**Comment by abhinavsingi** [comment] 2016-02-13 16:32
@larryhe @unindented : My codebase of >5k modules takes build time of ~10 minutes - same time gets spend on incremental builds - tried every optimization out there - all the cache methods too.
But due to severe lack of documentation of `webpack` and it's codebase - it's very difficult to debug things as to what can be causing such slowness.
`css-loader` downgrade did help.
Is `webpack` even suitable for such huge codebases?

**Comment by unindented** [comment] 2016-02-15 14:37
@larryhe @abhinavsingi Sorry for taking so long to respond, I missed the email notifications.

In my experience, the value used for `devtool` is very important when rebuilding. I haven't used `SourceMapDevToolPlugin`, but maybe it's also the source of your issues?

The config I use for `webpack-dev-server` looks like this:

```js
{
  "entry":{
    "xxx-requirejs-accounts-main":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/accounts_main.js"
    ],
    "xxx-requirejs-complete":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/complete.js"
    ],
    "xxx-requirejs-embed-aware-activation":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/embed_aware_activation.js"
    ],
    "xxx-requirejs-home-main":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/home_main.js"
    ],
    "xxx-requirejs-messages-main":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/messages_main.js"
    ],
    "xxx-requirejs-network-admin":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/network_admin.js"
    ],
    "xxx-requirejs-notes-main":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/notes_main.js"
    ],
    "xxx-requirejs-public-homepage-variant-a":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/public_homepage_variant_a.js"
    ],
    "xxx-requirejs-public-main":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/public_main.js"
    ],
    "xxx-requirejs-signup":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/main/signup.js"
    ],
    "xxx-dynamic-basic-bootstrap":[
      "./bootstrap/lib/environment/bootstrap_basic.js"
    ],
    "xxx-dynamic-cdn-bootstrap":[
      "./bootstrap/lib/environment/bootstrap_api.js"
    ],
    "xxx-platform-buttons":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/environment/platform_buttons.js",
      "./bootstrap/lib/environment/bootstrap_basic.js"
    ],
    "xxx-platform-feed":[
      "./bootstrap/lib/ready.js",
      "./bootstrap/lib/environment/platform_feed.js",
      "./bootstrap/lib/environment/bootstrap_basic.js"
    ],
    "platform_embed":[
      "./platform/lib/xxx_shim.js",
      "./platform/lib/embed_bootstrap.js",
      "./bootstrap/lib/environment/bootstrap_platform.js"
    ],
    "platform_js_sdk":[
      "jquery-real",
      "./platform/lib/xxx_shim.js",
      "./platform/lib/jquery_adapter.js",
      "./platform/lib/platform_session.js",
      "./platform/lib/embed_bootstrap.js",
      "./platform/lib/bootstrap.js",
      "./bootstrap/lib/environment/bootstrap_platform.js"
    ]
  },
  "output":{
    "path":"dist/releases/stable",
    "pathinfo":true,
    "filename":"[name].js",
    "chunkFilename":"[name].js"
  },
  "contentBase":"dist/releases/stable",
  "debug":true,
  "devtool":"eval",
  "watch":true,
  "stats":{
    "hash":false,
    "timings":false,
    "assets":false,
    "chunks":false,
    "modules":false,
    "reasons":true,
    "children":false
  },
  "resolve":{
    "extensions":[
      "",
      ".js"
    ],
    "modulesDirectories":[
      "node_modules"
    ],
    "alias":{
      "colorbox$":"vendor/lib/colorbox-1.3.15",
      "imagesloaded$":"imagesloaded/imagesloaded.pkgd",
      "jquery$":"core/lib/adapters/jquery_adapter",
      "jquery-real$":"jquery/dist/jquery",
      "org/cometd$":"cometd-jquery/org/cometd",
      "jquery-cometd$":"cometd-jquery/jquery/jquery.cometd",
      "jquery-datepicker$":"eyecon-datepicker/js/jquery.datepicker-2009.05.22",
      "jquery-dotdotdot$":"dotdotdot",
      "jquery-dragsort$":"dragsort",
      "jquery-truncate$":"truncate/jquery.truncate",
      "jquery-typeahead$":"typeahead",
      "jquery-watermark$":"core/lib/adapters/jquery_watermark_adapter",
      "jquery-watermark-real$":"jquery-watermark/jquery.watermark",
      "plupload$":"vendor/lib/plupload-2.1.6",
      "resig-class$":"resig_class/class",
      "socket.io$":"vendor/lib/socket.io-0.9.10",
      "squire-rte$":"squire-rte/build/squire-raw",
      "svg4everybody$":"svg4everybody/dist/svg4everybody",
      "triejs$":"triejs/src/trie",
      "twemoji$":"core/lib/adapters/twemoji_adapter",
      "twemoji-real$":"twemoji/twemoji.npm",
      "velocity$":"velocity-animate"
    }
  },
  "resolveLoader":{
    "extensions":[
      "",
      ".js"
    ],
    "modulesDirectories":[
      "grunt/lib/loaders",
      "node_modules"
    ],
    "alias":{
      "text":"raw-loader"
    }
  },
  "module":{
    loaders: [
      // Compile `.html` files as Mustache templates.
      {
        test: /\.html$/,
        exclude: /(assets\/pages|node_modules)\//,
        loader: 'mustache'
      },
      // Process `.css` files with PostCSS.
      {
        test: /\.css$/,
        exclude: /node_modules\//,
        loader: ExtractTextPlugin.extract('style', [
          'css',
          'postcss',
          'wrap?css'
        ].join('!'))
      },
      // Process `.json` files as JSON.
      {
        test: /\.json$/,
        exclude: /node_modules\//,
        loader: 'json'
      },
      // Expose globals for Workfeed.
      {
        test: require.resolve('jquery'),
        loader: [
          'expose?$',
          'expose?jQuery'
        ].join('!')
      },
      // Allow loading of `video.js` on demand.
      {
        test: /\.(eot|svg|ttf|woff)$/,
        include: /node_modules\/([^\/]+\/)*video\.js\//,
        loader: 'file?name=[name]' + (!isDebug ? '-[hash:20]' : '') + '.[ext]'
      },
      {
        test: /\.css$/,
        include: /node_modules\/([^\/]+\/)*video\.js\//,
        loader: [
          'style',
          'css'
        ].join('!')
      },
      // Fix bad assumptions in external libraries.
      {
        test: require.resolve('imagesloaded/imagesloaded.pkgd'),
        loader: 'imports?this=>window'
      },
      {
        test: require.resolve('cometd-jquery/org/cometd'),
        loader: 'imports?this=>window'
      },
      {
        test: require.resolve('cometd-jquery/jquery/jquery.cometd'),
        loader: 'imports?this=>window'
      },
      {
        test: path.resolve(root, 'vendor/lib/plupload-2.1.6'),
        loader: 'imports?this=>window'
      }
    ]
  },
  plugins: [
    // Automatically provide dependencies to files expecting certain globals
    // to just be there.
    new webpack.ProvidePlugin({
      '$': 'jquery-real',
      'jQuery': 'jquery-real',
      'window.$': 'jquery-real',
      'window.jQuery': 'jquery-real',
      '_': 'underscore',
      'window._': 'underscore',
      'io': 'socket.io'
    }),
    // Define variables and replace them at compile time.
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(environment),
      }
    }),
    // Extract CSS content into a separate file.
    new ExtractTextPlugin('[name]' + (!isDebug ? '-[contenthash:20]' : '') + '.css')
  ]
}
```

Build time is ~1min. Rebuild times are ~5s.

**Comment by abhinavsingi** [comment] 2016-02-15 16:11
@unindented : I've not even set the value of `devtool` (also tried with setting it to false) - but still it's taking too much time - I've a lot of dynamic requires. Could that be a problem?

**Comment by unindented** [comment] 2016-02-15 16:53
@abhinavsingi Maybe? My approach would be to disable things one by one, and measure as you go.

**Comment by abhinavsingi** [comment] 2016-02-15 18:31
@unindented I have multiple dynamic requires - some also have same name - loading all via `bundle-loader`. Have tried disabling things approach too - didn't quite work out

**Comment by abhinavsingi** [comment] 2016-02-16 22:18
@unindented @larryhe : What's your number of bundles created by webpack? I have >150

**Comment by larryhe** [comment] 2016-02-17 00:01
@abhinavsingi , we have four entry points totally and some of modules have dynamic require, after going through webpack, totally 25 bundles created. Thanks.

**Comment by larryhe** [comment] 2016-02-17 00:44
I just profiled and debugged webpack and found most of time spent on incrementation build (over 93%) is in apply function of RemoveParentModulesPlugin.js as following:  Could @sokra share us some clues to improve it?  Thanks for your time. 
```
RemoveParentModulesPlugin.prototype.apply = function(compiler) {
	compiler.plugin("compilation", function(compilation) {
		compilation.plugin(["optimize-chunks", "optimize-extracted-chunks"], function(chunks) {
			chunks.forEach(function(chunk) {
				chunk.modules.slice().forEach(function(module) {
					if(chunk.entry) return;
					var parentChunksWithModule = allHaveModule(chunk.parents, module);
					if(parentChunksWithModule) {
						module.rewriteChunkInReasons(chunk, parentChunksWithModule);
						chunk.removeModule(module);
					}
				});
			});
		});
	});
};
```

**Comment by unindented** [comment] 2016-02-17 13:00
@abhinavsingi You can see in my config above, we output 16 bundles.

**Comment by abhinavsingi** [comment] 2016-02-17 18:37
@larryhe Yes - maximum time is spent on that particular plugin and not just while incremental build but also 1st time builds. It keeps on optimizing chunks recursively and uses lot of memory in the process which results in issues when number of chunks is very high.

**Comment by sokra** [comment] 2016-02-17 20:18
> I just profiled and debugged webpack and found most of time spent on incrementation build (over 93%) is in apply function of RemoveParentModulesPlugin.js as following

That's actually a good news. Looks like we only need to optimize that function to get a huge performance improvment...

**Comment by sushant24** [comment] 2016-02-19 04:58
The functions hasModule, allHaveModule and addToSet use contains check on arrays to check for already checked/selected modules(which has O(n) worst case complexity). Using maps might reduce the time taken. Something like this maybe - 

```
function hasModule(chunk, module, checkedChunksMap, pushedChunksMap, identifier) {
	if(chunk.modules.indexOf(module) >= 0) return [chunk];
	if(chunk.entry) return false;
	return allHaveModule(chunk.parents.filter(function(c) {
		return checkedChunksMap[c.debugId] !== identifier;
	}), module, checkedChunksMap, pushedChunksMap, identifier);
}

function allHaveModule(someChunks, module, checkedChunksMap, pushedChunksMap, identifier) {
	var chunks = [];
	for(var i = 0; i < someChunks.length; i++) {
		checkedChunksMap[someChunks[i].debugId] = identifier;
		var subChunks = hasModule(someChunks[i], module, checkedChunksMap, pushedChunksMap, identifier);
		if(!subChunks) return false;
		addToSet(chunks, subChunks, pushedChunksMap, identifier);
	}
	return chunks;
}

function addToSet(set, items, pushedChunksMap, identifier) {
	items.forEach(function(item) {
		if(pushedChunksMap[item.debugId] !== identifier) {
			set.push(item);
			pushedChunksMap[item.debugId] = identifier;
		}
	});
}

function RemoveParentModulesPlugin() {}
module.exports = RemoveParentModulesPlugin;

RemoveParentModulesPlugin.prototype.apply = function(compiler) {
	compiler.plugin("compilation", function(compilation) {
		compilation.plugin(["optimize-chunks", "optimize-extracted-chunks"], function(chunks) {
			var identifier = 1,
				pushedChunksMap = {},
				checkedChunksMap = {};
			chunks.forEach(function(chunk) {
				chunk.modules.slice().forEach(function(module) {
					if(chunk.entry) return;
					var parentChunksWithModule = allHaveModule(chunk.parents, module, checkedChunksMap, pushedChunksMap, identifier++);
					if(parentChunksWithModule) {
						module.rewriteChunkInReasons(chunk, parentChunksWithModule);
						chunk.removeModule(module);
					}
				});
			});
		});
	});
};

```

**Comment by larryhe** [comment] 2016-02-19 18:42
Hi @sushant24 , Thanks for the patch. It works like a magic. the build performance improved dramatically after applying the patch on my local. especially incremental build time reduced to 
to 16883ms from 127200ms. Over 7 times faster. See below build stats before and after applying the patch. I will continue profiling based on this patch and see if we can improve it further. Also @sokra when are you going to release this patch? Thanks. 
Before applying the patch. 
```
Version: webpack 1.12.13
Time: 127200ms
                   Asset     Size                    Chunks             Chunk Names
             3.bundle.js  3.79 MB               3, 7, 8, 22  [emitted]
             4.bundle.js  5.07 MB  4, 5, 11, 17, 20, 21, 23  [emitted]
         vault.main.bundle.js  3.16 MB                    25, 20  [emitted]  vault.main
         3.bundle.js.map  4.13 MB               3, 7, 8, 22  [emitted]
         4.bundle.js.map  5.58 MB  4, 5, 11, 17, 20, 21, 23  [emitted]
       vault.main.bundle.js.map  3.49 MB                    25, 20  [emitted]  vault.main
    + 976 hidden modules
Hash: 96936016214a11d6e076
Version: webpack 1.12.13
Time: 167169ms
                   Asset     Size                    Chunks             Chunk Names
             3.bundle.js  3.79 MB               3, 7, 8, 22  [emitted]
             4.bundle.js  5.07 MB  4, 5, 11, 17, 20, 21, 23  [emitted]
    vault.main.bundle.js  3.16 MB                    25, 20  [emitted]  vault.main
         3.bundle.js.map  4.13 MB               3, 7, 8, 22  [emitted]
         4.bundle.js.map  5.58 MB  4, 5, 11, 17, 20, 21, 23  [emitted]
vault.main.bundle.js.map  3.49 MB                    25, 20  [emitted]  vault.main
    + 976 hidden modules
```  
After applying the patch
```
Hash: bb5f928df937d122a8d5
Version: webpack 1.12.13
Time: 12383ms
                   Asset     Size  Chunks             Chunk Names
    vault.main.bundle.js  3.16 MB       3  [emitted]  vault.main
vault.main.bundle.js.map  3.49 MB       3  [emitted]  vault.main
    + 976 hidden modules
Hash: b4c56be43a3393ef3054
Version: webpack 1.12.13
Time: 17970ms
                   Asset     Size  Chunks             Chunk Names
    vault.main.bundle.js  3.16 MB       3  [emitted]  vault.main
vault.main.bundle.js.map  3.49 MB       3  [emitted]  vault.main
    + 976 hidden modules
Hash: 4f3a5d89f279553cfd7f
Version: webpack 1.12.13
Time: 12234ms
```

**Comment by sushant24** [comment] 2016-02-19 18:57
@larryhe I forgot to mention that we would also need to add a debugId to Chunk.js to identify a chunk uniquely. So it will be something like this - 
```
var debugId = 1;

function Chunk(name, module, loc) {
	this.id = null;
	this.ids = null;
	this.debugId = debugId++;
	this.name = name;
	this.modules = [];
	this.chunks = [];
	this.parents = [];
	this.blocks = [];
	this.origins = [];
	this.files = [];
	this.rendered = false;
	this.entry = false;
	this.initial = false;
	if(module) {
		this.origins.push({
			module: module,
			loc: loc,
			name: name
		});
	}
}
```

**Comment by larryhe** [comment] 2016-02-19 19:26
Hi @sushant24, Thanks for reminding this. after adding debugId, it's much slower (52479ms) . because checkedChunksMap will be much bigger (before adding debugId, it has only one item). I will keep profiling and see if we could improve it further. Thanks.

**Comment by larryhe** [comment] 2016-02-19 22:02
Below is my latest profiling information after applying @sushant24 's patch on my local. Still hasModule and allHaveModule function of RemoveParentModulesPlugin.js takes over 80% of total successive build time slightly better than before applying the patch. We could definitely optimize it further. @sokra any suggestions for us? Thanks for your time. 
![screen shot 2016-02-19 at 1 54 51 pm](https://cloud.githubusercontent.com/assets/52333/13190191/903353d8-d710-11e5-984f-2640bcd9e908.png)

**Comment by sokra** [comment] 2016-02-20 13:02
Yes, we can reverse the logic. Instead iterating each module and check all parent chunks, we can iterate each chunk and mark available modules in each child chunk. Than we remove thix modules in a second step. This should reduce the complexity...

**Comment by sokra** [comment] 2016-02-24 23:10
Could you try `webpack@2.1.0-beta.4`?

**Comment by larryhe** [comment] 2016-02-25 01:21
Hi @sokra , after installing webpack@2.1.0-beta.4, I can not even compile and I got a bunch of resolving error on my local as following. Looks like this version can not resolve alias? Thanks for your time. 

```
ERROR in ./es6/main.js
Module not found: Error: Can't resolve 'jquery' in '/Users/me/workspace/github/webpack-es6-demo/es6'
 @ ./es6/main.js 3:14-31

ERROR in ./es6/main.js
Module not found: Error: Can't resolve 'underscore' in '/Users/me/workspace/github/webpack-es6-demo/es6'
 @ ./es6/main.js 7:18-39 1:0-21
```

**Comment by Furizaa** [comment] 2016-03-01 16:55
I've got `webpack@2.1.0-beta.4` to build out project (we don't have any aliases) but it doesn't change the build time much.

1.12.12 : ~90000ms
2.1.0-beta.4: ~83000ms

I guess thats because the majority of our build time is spend in the css-loader or less-loader. We've got around 1200 modules.

Still a welcome change though!

**Comment by abhinavsingi** [comment] 2016-03-01 22:44
@Furizaa : which version of `css-loader` are you using? Try downgrading to 0.14.5, if you're using any higher version?

**Comment by blowery** [comment] 2016-03-19 15:24
Folks who land here might want to take a peek at a monkey-patch I worked up to speed up this plugin. It replaces the indexOf seaches, which are O(n), with O(1) set lookups and by indexing the modules contained by a chunk. Brought our rebuild times down by 10x and our initial build down by 2x.

https://github.com/Automattic/wp-calypso/pull/4154

While working that up, I noticed a _lot_ of places in webpack that use indexOf to search arrays. You could get some massive speedups by replacing those with map lookups, either using Set like in my PR to wp-calypso, or just plain object maps. Bulking up item removal from collections also got us some nice speed boosts.

We also tried the patch in https://github.com/webpack/webpack/issues/1905#issuecomment-186051932 but the indexOf in the first line is what eats 98% of the time spent in the plugin. Making that an indexed lookup is what fixes it.

I also backported the new implementation in webpack2, but it has a lurking infinite recursion bug (I think), at least with wp-caplyso's chunk structure (which is apparently cyclic). Even giving node 8 gigs of memory wouldn't get it to run.

Code in the PR is technically GPL, but I'm sure I'd be able to contribute it to webpack under the MIT.

**Comment by blowery** [comment] 2016-03-19 15:53
Added https://github.com/webpack/webpack/pull/2210 which applies most of the work in https://github.com/Automattic/wp-calypso/pull/4154 directly to webpack, without using lodash or native `Set`.

**Comment by blowery** [comment] 2016-03-22 13:17
One last note: we ended up fixing our build time issues a different way. It turns out we had a bunch parenting dependency loops because of how we use require.ensure. We had one file that both did all of the ensure calls and was required by normal modules to load new modules. Let's call it `sections`.

Say we have chunks entry, A, and B. entry would require `sections`, which has `ensure` calls to load A and B. This makes entry a parent of both A and B.

A and B both also require `sections`, in case they need to load each other. This ends up making A and B parents of each other. 

Now explode this out to 30 chunks and 1600 modules. When RemoveParentModulesPlugin runs across this graph, it has to check a ton of modules across a ton of parents, since each chunk's parents are effectively all of the other chunks.

We broke the dependency cycle in https://github.com/Automattic/wp-calypso/pull/4195 by separating out the loader from the require.ensure calls. This way A and B depend not on `sections` but on `sections-loader`, which has no dependencies. 

For folks running in to perf issues, take a look at your chunk dependencies. If there's a bunch of interlinked deps, trying to find these chains and breaking them can help quite a bit. Our builds went from 90s full / 50s rebuild to 30s full / 5s rebuild.

**Comment by MagicDuck** [comment] 2016-07-30 00:29
We are also in the situation where the incremental build is a too slow and am reaching out to see if anybody has suggestions...
Any help is much appreciated!

It seems to have something to do with the number of modules in the app. Initially we were quite happy with the speed, but as we fixed up more of our legacy code so that proper deps would be created and they would be included in the build, the time went up.

Our app has ~4000 modules. I have confirmed that only the particular file I am editing gets rebuilt on the incremental build by setting the appropriate stats flags in the devServer config. It still takes about 8s. I am not sure what could be taking so long... Based on the info on this thread I tried removing pretty much all of our require.ensure() statements so we only have 2 chunks in order to take out the cyclical dependency problem. The time went to down to 5s, but I still feel this is too slow for development. I tried to profile a little bit with my limited level of skill and it seems that Compilation.processModuleDependencies() is taking 90% of the time... (here's my profile output: 
[20160729T165048.zip](https://github.com/webpack/webpack/files/391584/20160729T165048.zip))

Funny enough, adding the ExtractTextPlugin seems to help with the speed. I am not sure what it does internally (reducing the number of modules in the graph?), but after adding it, the first incremental build is slower (15s), but subsequent ones are faster (5s), without it it's always around 6-7s.

**Comment by MagicDuck** [comment] 2016-08-03 03:02
hmm, I was able to shave a bit more than a second by caching the matcher calls in LoadersList.js. Probably not the best thing to do in terms of memory footprint, but it goes a little bit faster.
What I find scary though is the rebuild speed if you make a syntax errorand save a file at a critical point in the dependency graph. It causes almost a full rebuild of all modules taking close to a minute in our case.
@sokra: any guidance on the best way to solve these incremental build performance issues would be invaluable. I can attempt to implement....
Note that I tried beta.20, but it was even slower in addition to rebuilding twice for every change, so it took like 10s x 2.

**Comment by khankuan** [comment] 2017-01-23 06:18
@MagicDuck could you share a little on how you're profiling webpack? Thanks!

**Comment by trusktr** [comment] 2017-01-23 18:37
@unindented Is that 5-minute time for a straight full build? How long does it take for `webpkac --watch` builds that only compile the new files? What about for webpack-dev-server, how long does it take between file change and auto-refresh? I'm just curious to know because I'm also looking to use webpack and want to consider what'll happen with a large code base.

**Comment by unindented** [comment] 2017-01-23 21:02
@trusktr yup, 2-5 minutes for a full build (depending on how fast your CPU is). A partial build with `webpack --watch` or `webpack-dev-server` is 5-6 seconds.

**Comment by MagicDuck** [comment] 2017-01-25 04:00
@khankuan i am running webpack through node-inspector. I dont have the full command handy atm, but its just like debugging any node app. I have to give it a ton of memory though, about 4gb. It runs very slow. Then i use the profiler built into the chrome dev tools ... i usually only profile an incremental build and then switch to the flame chart view, i found that one to be the most useful, especially the "aggregated self time".
We ended up rewriting some of the internals of webpack and monkey patching in order to get more palatable build times. It's still not that great though. I don't think performance and scalabilty was a priority i  webpack.

**Comment by khankuan** [comment] 2017-01-28 07:21
@unindented did you have cacheDirectory true for babel loader?

I went ahead to try webpack 2. Seems like I've got 30% speedup. And then more speedup with sourcemaps.

**Comment by hccampos** [comment] 2017-01-29 19:30
@MagicDuck could you share some of the modifications you did to the webpack internals? As @khankuan said, webpack 2 should be much faster and I am sure any further suggestions for performance improvements would be greatly appreciated by everyone.

**Comment by MagicDuck** [comment] 2017-01-30 20:44
@hccampos I'll try webpack 2 again at some point when I get time. Like I said, I tried the beta before with no significant difference.

For the following, keep in mind that we started converting to webpack about 6 months ago, and the version of webpack we have stabilized on for the time being is 1.13.0. (although I tried 1.14.0, and refrained from upgrading due to seeing no benefits). So things might have changed in the code base, but I am guessing there might still be a lot that is applicable.

I've put my webpack patches in a gist: https://gist.github.com/MagicDuck/5061fbf17406526521dae3771a4803ad
Notes about the patches:
 - one of them is sourcemaps, not technically webpack, but I still added it for completeness. Btw., some of the internals of the sourcemapping code is horrendous in terms of performance ... this is vague memories now, but I remember seeing places where super large strings are split on newline to create arrays when they could have been iterated in place.
- In my experience, one of the worst offenders for performance was that Chunk.modules is an array as opposed to a set. If you have fat chunks (which we can't help atm due to legacy), this causes terrible performance due to all the O(n) array searches and the array manipulation.

Some comments about our code/observations we made:
- we have about 6000 modules atm
- there is a lot of legacy code that had to be ported. Dependecies are quite ugly, lots of circular dependecies which result in very fat chunks. Had to resort to writing a plugin to split fat chunks into parallel slices until that problem is resolved: https://gist.github.com/MagicDuck/481a420c509f0c128e0ef99680e980c9
- html-webpack-plugin is a pig. Each extra entry point would add 2000ms for the incremental build. So we simply wrote our own plugin to emit html based on mustache templates that takes a fraction of the time: https://gist.github.com/MagicDuck/f57ea85bc859d873158c5a8bc12b7466
- Each extra entry point slows down the incremental build because it has to produce the extra bootstrap chunks. I hope this could be optimized since it severely limits the utillity of the "entries:" feature
- like I mentioned above, Compilation.processModuleDependencies() is taking a lot of time if you have convoluted dependency chains, I think the algorithm could be improved. I tried looking at it, but it seemed too complex though...
- we used to use babel cacheDir and/or happypack at some point, but had to give them up because of the "EMFILE: too many open files" error on windows :(, once we got past a certain number of modules. We are now looking into writing our own caching mechanism.
- sourcemap computation is super slow, especially since the cheaper variants don't work in chrome anymore. So I wrote a plugin to generate indexed sourcemaps: https://github.com/webpack/webpack/issues/3087 . For production, we still use devtool: "source-map" which is quite slow...
- we are looking into parallelizing UglifyJs atm. I think webpack could get a huge boost from parallelization.
- webpack is very memory hungry. We have to build with  --max_old_space_size=4096

Hope that helps :)

**Comment by khankuan** [comment] 2017-01-31 12:55
@MagicDuck you'll definitely have more insights on optimizing. I'm curious if there is a chance that making index.js makes dependency checks slow. Example:
```
import { Button } from 'uikit';
```
Lets say `uikit` has 1000 components. Does that statement create an indirect dependency for the file to all the 1000 components?

**Comment by MagicDuck** [comment] 2017-02-01 00:10
@khankuan hmm, due to working mostly with legacy code, I haven't used the new style imports yet, but I think the answer is yes unless you have that awesome tree shaking feature working, which I keep hearing about. It's a different story if your uikit is modularized, it's dependency graph is sane and you do something equivalent to:
`var Button = require('uikit/Button');    (import Button from 'uikit/Button' ?)`

You can verify this by generating the stats json and uploading to the webpack analyzer. Then check the module/graph.

**Comment by designxtek** [comment] 2017-04-19 17:58
I have 1100 modules and 7 entry points. I'm getting 16minute build times.

**Comment by MagicDuck** [comment] 2017-04-19 18:45
Ouch!  Is it mostly the sourcemapping? How much memory are you giving the nodejs process?

**Comment by designxtek** [comment] 2017-04-19 20:40
I turned off source mapping. I'm giving it 4gb of memory. I've downgraded the css-loader to 0.14.5.

I'm running this through Parallels.

The commons chunk is 1.39MB which is what I need to trim down. I'm planning on moving rarely changed modules into NPM.

The build speed is random. Right now it is anywhere from 7min-16min.

**Comment by MagicDuck** [comment] 2017-04-20 03:32
Are you using happypack?

**Comment by designxtek** [comment] 2017-04-20 15:54
I am not. My project contains typescript using ts-loader.

**Comment by TrySound** [comment] 2017-04-20 17:12
@designxtek ts-loader is very slow. Not quite webpack regression. Try [https://github.com/s-panferov/awesome-typescript-loader](awesome-typescript-loader). Seems like it's more efficient.

**Comment by tuan** [comment] 2017-04-20 17:16
Try awesome typescript loader. For our project with 2000+ modules, and 5
entries, the build time was 4 minutes. After we switched to awesome
typescript loader, the build time reduced by 30%.

**Comment by MagicDuck** [comment] 2017-04-20 21:30
Happypack is independent of babel, so could help...

**Comment by hccampos** [comment] 2017-04-20 21:40
Happy pack does not, and probably never will, work with TS

**Comment by MagicDuck** [comment] 2017-04-21 03:04
I see ... wasnt aware...

**Comment by designxtek** [comment] 2017-04-24 22:19
I noticed I can get my build to 3 minutes if I run
`npm cache clean`
which is weird.

If I run webpack without that back to back then it gets slower.

**Comment by designxtek** [comment] 2017-04-24 23:06
Wow Awesome-Typescript-Loader builds under 1 minute for me

**Comment by abergs** [comment] 2017-06-22 14:11
@hccampos @MagicDuck @designxtek  Happypack now supports TS

**Comment by sokra** [comment] 2017-08-12 09:05
Most of the things mentioned in this issue has been addressed for webpack 3 or are open PRs with breaking changes for webpack 4. Thanks for the investigations.

If you have another idea for an improvement please open a new PR or issue.

We also started a new documentation page with performance tips. It's far from complete, so if you want to contribute your experience here that would be great.

**Closed** 2017-12-23 08:42 UTC
Labels: performance

**Comment by pleerock** [comment] 2018-01-04 14:56
I have similar issues with as discussed in angular/angular-cli#5618 . Our project consist of around 2600 files and over 300 chunks and `RemoveParentModulesPlugin` execution takes about 1 hour. We are not able to use neither `build` neither `serve` processes without waiting an hour.

First 10 minutes of CPU profiling of this process:

![webpack-perf-issues](https://user-images.githubusercontent.com/1753397/34525647-7ddc472c-f0c1-11e7-890d-acab2555384a.png)

**Comment by sokra** [comment] 2018-01-04 15:05
@pleerock Please try with latest webpack version and open a new issue when this still occurs

**Comment by pleerock** [comment] 2018-01-04 18:35
@sokra do you mean latest 4 alpha version or latest 3.x version?

**Comment by MagicDuck** [comment] 2018-01-05 04:57
@pleerock i believe @sokra made some improvements to that plugin in 3.8.x

**Comment by pleerock** [comment] 2018-01-05 05:30
@MagicDuck those tests are from webpack@3.10.0

**Comment by MagicDuck** [comment] 2018-01-05 09:40
@pleerock 1 hour seems rather long for even the worst algorithm unless there is a very bad bug. I wonder if  it's spending most of the time garbage collecting cause it's on the edge of the memory limit. Are you giving node enough memory? (max_old_space_size)

**Comment by pleerock** [comment] 2018-01-05 20:07
@MagicDuck yes, max_old_space_size is being set by me to 8gb
