### ISSUE TITLE
Firefox source map not displayed correctly 

### ISSUE THREAD

**Issue by dassio** [webpack/webpack#11301] opened 2020-08-10 09:54 UTC
# Bug report

**What is the current behavior?**
when debuging an vuejs project with firefox , the genereate source map is not dispalyed correctly. on chrome it is Ok 

i have two generated bundle: `main.js` `chunk-verndor.js` and two source map: `main.js.map`, `chunk-vendor.js.map`

this is the screen shot for firefox :
![Screenshot from 2020-08-10 10-37-04](https://user-images.githubusercontent.com/733502/89769802-b4992700-daf5-11ea-88d3-f0d9a8b0d32f.png)
the displayed text:
`import mod from "-!../../node_modules/cache-loader/dist/cjs.js??ref--12-0!../../node_modules/thread-loader/dist/cjs.js!../../node_modules/babel-loader/lib/index.js!../../node_modules/cache-loader/dist/cjs.js??ref--0-0!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./FileChart.vue?vue&type=script&lang=js&"; export default mod; export * from "-!../../node_modules/cache-loader/dist/cjs.js??ref--12-0!../../node_modules/thread-loader/dist/cjs.js!../../node_modules/babel-loader/lib/index.js!../../node_modules/cache-loader/dist/cjs.js??ref--0-0!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./FileChart.vue?vue&type=script&lang=js&"`

this is the screenshot for chrome:
![Screenshot from 2020-08-10 10-39-44](https://user-images.githubusercontent.com/733502/89769896-e0b4a800-daf5-11ea-95ed-e0111693ea98.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
build vuejs with source map

**What is the expected behavior?**
firefox should display like chrome 

**Other relevant information:**
webpack version:  4.44.1
Node.js version: v10.21.0
Operating System: ubutun 20 
Additional tools: @vue/cli 4.4.6

**Comment by evilebottnawi** [comment] 2020-08-10 10:42
Duplicate of #1194, please provide minimum reproducible test repo in #1194 issue and we will create new issue in firefox bug tracker

**Closed by evilebottnawi** 2020-08-10 10:42 UTC
