### ISSUE TITLE
ProfilingPlugin file shows nothing in Chrome 66

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack#7450] opened 2018-05-30 14:35 UTC
# Bug report

**What is the current behavior?**
The generated events.json does not show anything in the Performance tab in Chrome 66.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `webpack --plugin webpack/lib/debug/ProfilingPlugin`, load file in the Performance tab in Google Chrome, check output of it. There are no commands listed.

**What is the expected behavior?**
We should see the infos from the JSOn file.

**Other relevant information:**
webpack version:  4.10.2
Node.js version: 10.2.1
Operating System: macOS X 10.13.4
Additional tools:

**Comment by montogeek** [comment] 2018-05-30 16:55
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by DanielRuf** [comment] 2018-05-30 17:06
I wrote a small example. The generated events.json is the following:

<details>
<summary>events.json</summary>

```
[{"ts":26497699015,"pid":12051,"tid":12051,"ph":"I","name":"TracingStartedInPage","id":1,"cat":"disabled-by-default-devtools.timeline","args":{"data":{"sessionId":"-1","page":"0xfff","frames":[{"frame":"0xfff","url":"webpack","name":""}]}}},
{"ts":26497699165,"pid":12051,"tid":12051,"ph":"I","name":"TracingStartedInBrowser","id":2,"cat":"disabled-by-default-devtools.timeline","args":{"data":{"sessionId":"-1"}}},
{"ts":26497765342,"pid":12051,"tid":12051,"ph":"b","name":"EntryOptionPlugin","id":3,"cat":"blink.user_timing"},
{"ts":26497765951,"pid":12051,"tid":12051,"ph":"e","name":"EntryOptionPlugin","id":3,"cat":"blink.user_timing"},
{"ts":26498353562,"pid":12051,"tid":12051,"ph":"b","name":"NodeSourcePlugin","id":4,"cat":"blink.user_timing"},
{"ts":26498354010,"pid":12051,"tid":12051,"ph":"e","name":"NodeSourcePlugin","id":4,"cat":"blink.user_timing"},
{"ts":26498354016,"pid":12051,"tid":12051,"ph":"b","name":"AMDPlugin","id":5,"cat":"blink.user_timing"},
{"ts":26498354146,"pid":12051,"tid":12051,"ph":"e","name":"AMDPlugin","id":5,"cat":"blink.user_timing"},
{"ts":26498354614,"pid":12051,"tid":12051,"ph":"b","name":"NodeEnvironmentPlugin","id":6,"cat":"blink.user_timing"},
{"ts":26498355761,"pid":12051,"tid":12051,"ph":"e","name":"NodeEnvironmentPlugin","id":6,"cat":"blink.user_timing"},
{"ts":26498359589,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":7,"cat":"blink.user_timing"},
{"ts":26498359770,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":7,"cat":"blink.user_timing"},
{"ts":26498364464,"pid":12051,"tid":12051,"ph":"b","name":"JsonpTemplatePlugin","id":8,"cat":"blink.user_timing"},
{"ts":26498366950,"pid":12051,"tid":12051,"ph":"e","name":"JsonpTemplatePlugin","id":8,"cat":"blink.user_timing"},
{"ts":26498366960,"pid":12051,"tid":12051,"ph":"b","name":"FetchCompileWasmTemplatePlugin","id":9,"cat":"blink.user_timing"},
{"ts":26498367642,"pid":12051,"tid":12051,"ph":"e","name":"FetchCompileWasmTemplatePlugin","id":9,"cat":"blink.user_timing"},
{"ts":26498367650,"pid":12051,"tid":12051,"ph":"b","name":"WarnNoModeSetPlugin","id":10,"cat":"blink.user_timing"},
{"ts":26498367997,"pid":12051,"tid":12051,"ph":"e","name":"WarnNoModeSetPlugin","id":10,"cat":"blink.user_timing"},
{"ts":26498368003,"pid":12051,"tid":12051,"ph":"b","name":"SplitChunksPlugin","id":11,"cat":"blink.user_timing"},
{"ts":26498369039,"pid":12051,"tid":12051,"ph":"e","name":"SplitChunksPlugin","id":11,"cat":"blink.user_timing"},
{"ts":26498371666,"pid":12051,"tid":12051,"ph":"b","name":"FunctionModulePlugin","id":14,"cat":"blink.user_timing"},
{"ts":26498371985,"pid":12051,"tid":12051,"ph":"e","name":"FunctionModulePlugin","id":14,"cat":"blink.user_timing"},
{"ts":26498371992,"pid":12051,"tid":12051,"ph":"b","name":"NodeSourcePlugin","id":15,"cat":"blink.user_timing"},
{"ts":26498372172,"pid":12051,"tid":12051,"ph":"e","name":"NodeSourcePlugin","id":15,"cat":"blink.user_timing"},
{"ts":26498372179,"pid":12051,"tid":12051,"ph":"b","name":"LoaderTargetPlugin","id":16,"cat":"blink.user_timing"},
{"ts":26498372249,"pid":12051,"tid":12051,"ph":"e","name":"LoaderTargetPlugin","id":16,"cat":"blink.user_timing"},
{"ts":26498372255,"pid":12051,"tid":12051,"ph":"b","name":"JavascriptModulesPlugin","id":17,"cat":"blink.user_timing"},
{"ts":26498372850,"pid":12051,"tid":12051,"ph":"e","name":"JavascriptModulesPlugin","id":17,"cat":"blink.user_timing"},
{"ts":26498372859,"pid":12051,"tid":12051,"ph":"b","name":"JsonModulesPlugin","id":18,"cat":"blink.user_timing"},
{"ts":26498372975,"pid":12051,"tid":12051,"ph":"e","name":"JsonModulesPlugin","id":18,"cat":"blink.user_timing"},
{"ts":26498372981,"pid":12051,"tid":12051,"ph":"b","name":"WebAssemblyModulesPlugin","id":19,"cat":"blink.user_timing"},
{"ts":26498373190,"pid":12051,"tid":12051,"ph":"e","name":"WebAssemblyModulesPlugin","id":19,"cat":"blink.user_timing"},
{"ts":26498373198,"pid":12051,"tid":12051,"ph":"b","name":"SingleEntryPlugin","id":20,"cat":"blink.user_timing"},
{"ts":26498373283,"pid":12051,"tid":12051,"ph":"e","name":"SingleEntryPlugin","id":20,"cat":"blink.user_timing"},
{"ts":26498373291,"pid":12051,"tid":12051,"ph":"b","name":"CompatibilityPlugin","id":21,"cat":"blink.user_timing"},
{"ts":26498373520,"pid":12051,"tid":12051,"ph":"e","name":"CompatibilityPlugin","id":21,"cat":"blink.user_timing"},
{"ts":26498373527,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyModulesPlugin","id":22,"cat":"blink.user_timing"},
{"ts":26498374652,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyModulesPlugin","id":22,"cat":"blink.user_timing"},
{"ts":26498374662,"pid":12051,"tid":12051,"ph":"b","name":"AMDPlugin","id":23,"cat":"blink.user_timing"},
{"ts":26498376253,"pid":12051,"tid":12051,"ph":"e","name":"AMDPlugin","id":23,"cat":"blink.user_timing"},
{"ts":26498376264,"pid":12051,"tid":12051,"ph":"b","name":"CommonJsPlugin","id":24,"cat":"blink.user_timing"},
{"ts":26498377027,"pid":12051,"tid":12051,"ph":"e","name":"CommonJsPlugin","id":24,"cat":"blink.user_timing"},
{"ts":26498377044,"pid":12051,"tid":12051,"ph":"b","name":"LoaderPlugin","id":25,"cat":"blink.user_timing"},
{"ts":26498377171,"pid":12051,"tid":12051,"ph":"e","name":"LoaderPlugin","id":25,"cat":"blink.user_timing"},
{"ts":26498377184,"pid":12051,"tid":12051,"ph":"b","name":"LoaderPlugin","id":26,"cat":"blink.user_timing"},
{"ts":26498377475,"pid":12051,"tid":12051,"ph":"e","name":"LoaderPlugin","id":26,"cat":"blink.user_timing"},
{"ts":26498377482,"pid":12051,"tid":12051,"ph":"b","name":"NodeStuffPlugin","id":27,"cat":"blink.user_timing"},
{"ts":26498377821,"pid":12051,"tid":12051,"ph":"e","name":"NodeStuffPlugin","id":27,"cat":"blink.user_timing"},
{"ts":26498377830,"pid":12051,"tid":12051,"ph":"b","name":"RequireJsStuffPlugin","id":28,"cat":"blink.user_timing"},
{"ts":26498378105,"pid":12051,"tid":12051,"ph":"e","name":"RequireJsStuffPlugin","id":28,"cat":"blink.user_timing"},
{"ts":26498378151,"pid":12051,"tid":12051,"ph":"b","name":"APIPlugin","id":29,"cat":"blink.user_timing"},
{"ts":26498378441,"pid":12051,"tid":12051,"ph":"e","name":"APIPlugin","id":29,"cat":"blink.user_timing"},
{"ts":26498378452,"pid":12051,"tid":12051,"ph":"b","name":"ConstPlugin","id":30,"cat":"blink.user_timing"},
{"ts":26498378935,"pid":12051,"tid":12051,"ph":"e","name":"ConstPlugin","id":30,"cat":"blink.user_timing"},
{"ts":26498378951,"pid":12051,"tid":12051,"ph":"b","name":"UseStrictPlugin","id":31,"cat":"blink.user_timing"},
{"ts":26498379248,"pid":12051,"tid":12051,"ph":"e","name":"UseStrictPlugin","id":31,"cat":"blink.user_timing"},
{"ts":26498379260,"pid":12051,"tid":12051,"ph":"b","name":"RequireIncludePlugin","id":32,"cat":"blink.user_timing"},
{"ts":26498379575,"pid":12051,"tid":12051,"ph":"e","name":"RequireIncludePlugin","id":32,"cat":"blink.user_timing"},
{"ts":26498379585,"pid":12051,"tid":12051,"ph":"b","name":"RequireEnsurePlugin","id":33,"cat":"blink.user_timing"},
{"ts":26498379917,"pid":12051,"tid":12051,"ph":"e","name":"RequireEnsurePlugin","id":33,"cat":"blink.user_timing"},
{"ts":26498379926,"pid":12051,"tid":12051,"ph":"b","name":"RequireContextPlugin","id":34,"cat":"blink.user_timing"},
{"ts":26498380672,"pid":12051,"tid":12051,"ph":"e","name":"RequireContextPlugin","id":34,"cat":"blink.user_timing"},
{"ts":26498380685,"pid":12051,"tid":12051,"ph":"b","name":"ImportPlugin","id":35,"cat":"blink.user_timing"},
{"ts":26498381403,"pid":12051,"tid":12051,"ph":"e","name":"ImportPlugin","id":35,"cat":"blink.user_timing"},
{"ts":26498381413,"pid":12051,"tid":12051,"ph":"b","name":"SystemPlugin","id":36,"cat":"blink.user_timing"},
{"ts":26498381777,"pid":12051,"tid":12051,"ph":"e","name":"SystemPlugin","id":36,"cat":"blink.user_timing"},
{"ts":26498381869,"pid":12051,"tid":12051,"ph":"b","name":"EnsureChunkConditionsPlugin","id":37,"cat":"blink.user_timing"},
{"ts":26498382460,"pid":12051,"tid":12051,"ph":"e","name":"EnsureChunkConditionsPlugin","id":37,"cat":"blink.user_timing"},
{"ts":26498382473,"pid":12051,"tid":12051,"ph":"b","name":"RemoveParentModulesPlugin","id":38,"cat":"blink.user_timing"},
{"ts":26498383029,"pid":12051,"tid":12051,"ph":"e","name":"RemoveParentModulesPlugin","id":38,"cat":"blink.user_timing"},
{"ts":26498383046,"pid":12051,"tid":12051,"ph":"b","name":"RemoveEmptyChunksPlugin","id":39,"cat":"blink.user_timing"},
{"ts":26498383242,"pid":12051,"tid":12051,"ph":"e","name":"RemoveEmptyChunksPlugin","id":39,"cat":"blink.user_timing"},
{"ts":26498383259,"pid":12051,"tid":12051,"ph":"b","name":"MergeDuplicateChunksPlugin","id":40,"cat":"blink.user_timing"},
{"ts":26498383518,"pid":12051,"tid":12051,"ph":"e","name":"MergeDuplicateChunksPlugin","id":40,"cat":"blink.user_timing"},
{"ts":26498383528,"pid":12051,"tid":12051,"ph":"b","name":"FlagIncludedChunksPlugin","id":41,"cat":"blink.user_timing"},
{"ts":26498383832,"pid":12051,"tid":12051,"ph":"e","name":"FlagIncludedChunksPlugin","id":41,"cat":"blink.user_timing"},
{"ts":26498383842,"pid":12051,"tid":12051,"ph":"b","name":"OccurrenceOrderPlugin","id":42,"cat":"blink.user_timing"},
{"ts":26498384458,"pid":12051,"tid":12051,"ph":"e","name":"OccurrenceOrderPlugin","id":42,"cat":"blink.user_timing"},
{"ts":26498384469,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":43,"cat":"blink.user_timing"},
{"ts":26498384919,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":43,"cat":"blink.user_timing"},
{"ts":26498384933,"pid":12051,"tid":12051,"ph":"b","name":"FlagDependencyExportsPlugin","id":44,"cat":"blink.user_timing"},
{"ts":26498385280,"pid":12051,"tid":12051,"ph":"e","name":"FlagDependencyExportsPlugin","id":44,"cat":"blink.user_timing"},
{"ts":26498385307,"pid":12051,"tid":12051,"ph":"b","name":"FlagDependencyUsagePlugin","id":45,"cat":"blink.user_timing"},
{"ts":26498385622,"pid":12051,"tid":12051,"ph":"e","name":"FlagDependencyUsagePlugin","id":45,"cat":"blink.user_timing"},
{"ts":26498385630,"pid":12051,"tid":12051,"ph":"b","name":"ModuleConcatenationPlugin","id":46,"cat":"blink.user_timing"},
{"ts":26498387323,"pid":12051,"tid":12051,"ph":"e","name":"ModuleConcatenationPlugin","id":46,"cat":"blink.user_timing"},
{"ts":26498387337,"pid":12051,"tid":12051,"ph":"b","name":"NoEmitOnErrorsPlugin","id":47,"cat":"blink.user_timing"},
{"ts":26498387477,"pid":12051,"tid":12051,"ph":"e","name":"NoEmitOnErrorsPlugin","id":47,"cat":"blink.user_timing"},
{"ts":26498387484,"pid":12051,"tid":12051,"ph":"b","name":"DefinePlugin","id":48,"cat":"blink.user_timing"},
{"ts":26498388284,"pid":12051,"tid":12051,"ph":"e","name":"DefinePlugin","id":48,"cat":"blink.user_timing"},
{"ts":26498388299,"pid":12051,"tid":12051,"ph":"b","name":"UglifyJSPlugin","id":49,"cat":"blink.user_timing"},
{"ts":26498388477,"pid":12051,"tid":12051,"ph":"e","name":"UglifyJSPlugin","id":49,"cat":"blink.user_timing"},
{"ts":26498388484,"pid":12051,"tid":12051,"ph":"b","name":"TemplatedPathPlugin","id":50,"cat":"blink.user_timing"},
{"ts":26498388948,"pid":12051,"tid":12051,"ph":"e","name":"TemplatedPathPlugin","id":50,"cat":"blink.user_timing"},
{"ts":26498388961,"pid":12051,"tid":12051,"ph":"b","name":"RecordIdsPlugin","id":51,"cat":"blink.user_timing"},
{"ts":26498389987,"pid":12051,"tid":12051,"ph":"e","name":"RecordIdsPlugin","id":51,"cat":"blink.user_timing"},
{"ts":26498390007,"pid":12051,"tid":12051,"ph":"b","name":"WarnCaseSensitiveModulesPlugin","id":52,"cat":"blink.user_timing"},
{"ts":26498390299,"pid":12051,"tid":12051,"ph":"e","name":"WarnCaseSensitiveModulesPlugin","id":52,"cat":"blink.user_timing"},
{"ts":26498391774,"pid":12051,"tid":12051,"ph":"b","name":"SingleEntryPlugin","id":53,"cat":"blink.user_timing"},
{"ts":26498394820,"pid":12051,"tid":12051,"ph":"b","name":"NormalModuleFactory","id":54,"cat":"blink.user_timing"},
{"ts":26498394935,"pid":12051,"tid":12051,"ph":"e","name":"NormalModuleFactory","id":54,"cat":"blink.user_timing"},
{"ts":26498395370,"pid":12051,"tid":12051,"ph":"b","name":"NormalModuleFactory","id":55,"cat":"blink.user_timing"},
{"ts":26498395723,"pid":12051,"tid":12051,"ph":"e","name":"NormalModuleFactory","id":55,"cat":"blink.user_timing"},
{"ts":26498523418,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":56,"cat":"blink.user_timing"},
{"ts":26498523667,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":56,"cat":"blink.user_timing"},
{"ts":26498523674,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":57,"cat":"blink.user_timing"},
{"ts":26498523757,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":57,"cat":"blink.user_timing"},
{"ts":26498526230,"pid":12051,"tid":12051,"ph":"b","name":"LoaderTargetPlugin","id":58,"cat":"blink.user_timing"},
{"ts":26498526304,"pid":12051,"tid":12051,"ph":"e","name":"LoaderTargetPlugin","id":58,"cat":"blink.user_timing"},
{"ts":26498526311,"pid":12051,"tid":12051,"ph":"b","name":"LoaderPlugin","id":59,"cat":"blink.user_timing"},
{"ts":26498526522,"pid":12051,"tid":12051,"ph":"e","name":"LoaderPlugin","id":59,"cat":"blink.user_timing"},
{"ts":26498544744,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyDetectionParserPlugin","id":60,"cat":"blink.user_timing"},
{"ts":26498545079,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyDetectionParserPlugin","id":60,"cat":"blink.user_timing"},
{"ts":26498545088,"pid":12051,"tid":12051,"ph":"b","name":"UseStrictPlugin","id":61,"cat":"blink.user_timing"},
{"ts":26498545192,"pid":12051,"tid":12051,"ph":"e","name":"UseStrictPlugin","id":61,"cat":"blink.user_timing"},
{"ts":26498566552,"pid":12051,"tid":12051,"ph":"b","name":"NormalModuleFactory","id":62,"cat":"blink.user_timing"},
{"ts":26498566801,"pid":12051,"tid":12051,"ph":"e","name":"NormalModuleFactory","id":62,"cat":"blink.user_timing"},
{"ts":26498566819,"pid":12051,"tid":12051,"ph":"b","name":"NormalModuleFactory","id":63,"cat":"blink.user_timing"},
{"ts":26498567048,"pid":12051,"tid":12051,"ph":"e","name":"NormalModuleFactory","id":63,"cat":"blink.user_timing"},
{"ts":26498602681,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":64,"cat":"blink.user_timing"},
{"ts":26498602962,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":64,"cat":"blink.user_timing"},
{"ts":26498602969,"pid":12051,"tid":12051,"ph":"b","name":"SideEffectsFlagPlugin","id":65,"cat":"blink.user_timing"},
{"ts":26498603076,"pid":12051,"tid":12051,"ph":"e","name":"SideEffectsFlagPlugin","id":65,"cat":"blink.user_timing"},
{"ts":26498605446,"pid":12051,"tid":12051,"ph":"b","name":"LoaderTargetPlugin","id":66,"cat":"blink.user_timing"},
{"ts":26498605761,"pid":12051,"tid":12051,"ph":"e","name":"LoaderTargetPlugin","id":66,"cat":"blink.user_timing"},
{"ts":26498605768,"pid":12051,"tid":12051,"ph":"b","name":"LoaderPlugin","id":67,"cat":"blink.user_timing"},
{"ts":26498605813,"pid":12051,"tid":12051,"ph":"e","name":"LoaderPlugin","id":67,"cat":"blink.user_timing"},
{"ts":26499551788,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyDetectionParserPlugin","id":68,"cat":"blink.user_timing"},
{"ts":26499552586,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyDetectionParserPlugin","id":68,"cat":"blink.user_timing"},
{"ts":26499552594,"pid":12051,"tid":12051,"ph":"b","name":"UseStrictPlugin","id":69,"cat":"blink.user_timing"},
{"ts":26499552634,"pid":12051,"tid":12051,"ph":"e","name":"UseStrictPlugin","id":69,"cat":"blink.user_timing"},
{"ts":26499553512,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyImportDependencyParserPlugin","id":70,"cat":"blink.user_timing"},
{"ts":26499554348,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyImportDependencyParserPlugin","id":70,"cat":"blink.user_timing"},
{"ts":26499554572,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyImportDependencyParserPlugin","id":71,"cat":"blink.user_timing"},
{"ts":26499554907,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyImportDependencyParserPlugin","id":71,"cat":"blink.user_timing"},
{"ts":26499554948,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyImportDependencyParserPlugin","id":72,"cat":"blink.user_timing"},
{"ts":26499555043,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyImportDependencyParserPlugin","id":72,"cat":"blink.user_timing"},
{"ts":26499555058,"pid":12051,"tid":12051,"ph":"b","name":"HarmonyImportDependencyParserPlugin","id":73,"cat":"blink.user_timing"},
{"ts":26499555094,"pid":12051,"tid":12051,"ph":"e","name":"HarmonyImportDependencyParserPlugin","id":73,"cat":"blink.user_timing"},

```
</details>

**Comment by sokra** [comment] 2018-05-30 17:57
@samccone

**Comment by samccone** [comment] 2018-06-01 15:14
Cheers, feel free to assign me the issue (also if you do not see any motion on this during the next 4 days  please ping it so it pops back into my queue)

**Comment by samijaber** [comment] 2018-06-21 19:21
I'm bumping into this issue as well. The first thing I did was check if my `events.json` is valid. It wasn't because it ended with a trailing comma and without closing the main JSON array. It seems to be the same in @DanielRuf 's case. 

However, even after manually fixing that, Chrome (v67 in my case) shows nothing.

**Comment by spalger** [comment] 2018-06-22 17:16
@samccone I had the same issue, fixed it by removing the `noStream: true` config option passed to the `Tracer` class. It seems that only the first 140 calls to `this._push` in `Tracer#flush()` actually get written to the file, even though there are some 240k in my trace.

**Comment by DanielRuf** [comment] 2018-06-22 23:04
> @samccone I had the same issue, fixed it by removing the noStream: true config option passed to the Tracer class. It seems that only the first 140 calls to this._push in Tracer#flush() actually get written to the file, even though there are some 240k in my trace.

This is interesting. Is this some race condition where we need some async / await around it?

**Comment by DanielRuf** [comment] 2018-06-22 23:32
`noStream` probably makes no sense as a stream is expected and consumed.

**Comment by DanielRuf** [comment] 2018-06-22 23:34
See https://github.com/webpack/webpack/pull/7584 and https://github.com/samccone/chrome-trace-event/blob/master/examples/event-log.js#L16

I guess the old documenation and readme (it is unclear to me where the current repository of chrome-trace-event is) was / is not right.

**Comment by DanielRuf** [comment] 2018-06-22 23:45
@spalger should I add you as Co-Author as you debugged this a bit further? Unfortunately had not yet the time but the PR should fix it in general.

I am unsure if there are just not so many users of this internal plugin (it can not be used for webpack-cli by its name, just by its internal path) or if there was a change.

At least the example and docs of chrome-trace-event are somehow different.

**Comment by spalger** [comment] 2018-06-23 02:45
Thanks for submitting that PR @DanielRuf! @samccone has confirmed my suspicion though, the solution needs to continue buffering the events but fix writing them to disk at the end of the webpack compilation.

**Comment by DanielRuf** [comment] 2018-06-23 08:45
So what would be the right solution as this is not the right approach then?

**Comment by samccone** [comment] 2018-06-23 17:05
Hi all, I am actively looking into this issue right now, once I have created a simple test case that can reproduce the issue I will post a status update, after that hopefully the fix will be straightforward, thank you all for the reports and the information, it is very much appreciated.

**Comment by samccone** [comment] 2018-06-23 17:20
### Repro case

```
webpack/examples/chunkhash: ../../bin/webpack.js
```

With this patch applied
```diff
diff --git a/examples/chunkhash/webpack.config.js b/examples/chunkhash/webpack.config.js
index cc34d559..85b8b1fd 100644
--- a/examples/chunkhash/webpack.config.js
+++ b/examples/chunkhash/webpack.config.js
@@ -1,4 +1,6 @@
 var path = require("path");
+var webpack = require("../../");
+
 module.exports = {
 	// mode: "development || "production",
 	entry: {
@@ -11,5 +13,10 @@ module.exports = {
 		path: path.join(__dirname, "dist"),
 		filename: "[name].chunkhash.js",
 		chunkFilename: "[name].chunkhash.js"
-	}
+	},
+	plugins: [
+		new webpack.debug.ProfilingPlugin({
+			outputPath: "events.json" 
+		})
+	]
 };
```

### Observations

1. no cpu profile is being dumped
2. user timing information is correctly being dumped to the trace

![image](https://user-images.githubusercontent.com/883126/41811996-0f29e3a4-76cf-11e8-984f-f441670022d3.png)

**Comment by samccone** [comment] 2018-06-23 18:31
Perhaps, I feel that the patch above addresses the root problem in a way that does not work around the problem :)

**Comment by DanielRuf** [comment] 2018-06-23 18:31
> we are calling end() and then writeStream right after we call flush on the trace object

Ah right. Yes this does not make much sense and we have to wait for the proper `finish` event.

**Comment by DanielRuf** [comment] 2018-06-23 18:32
> Perhaps, I feel that the patch above addresses the root problem in a way that does not work around the problem :)

I'll test it now.

**Comment by DanielRuf** [comment] 2018-06-23 18:37
Looks good now but there is still a trailing comma.
[events.zip](https://github.com/webpack/webpack/files/2130127/events.zip)

**Comment by samccone** [comment] 2018-06-23 18:41
Correct, this is a long standing TODO in the original project before I forked it
https://github.com/samccone/chrome-trace-event/blob/master/lib/trace-event.ts#L141

But does not break anything as chrome devtools handles this just fine :)

PRs welcome!

**Comment by DanielRuf** [comment] 2018-06-23 19:06
> samccone/chrome-trace-event:lib/trace-event.ts@master#L141

This is not the cause =) I will test this further and try to find a solution.

**Comment by DanielRuf** [comment] 2018-06-23 20:12
> But does not break anything as chrome devtools handles this just fine :)

What about our tools which would consume or parse the output? ;-)
I've created a PR. Looks good with your other PR so far.

**Closed** 2018-06-24 08:43 UTC
