### ISSUE TITLE
webpack is huge and slow ? how to make it faster and smaller

### ISSUE THREAD

**Issue by zhoujianlin8** [webpack/webpack#1826] opened 2015-12-31 03:31 UTC
1.can do it like babel6, the plugins are out of webpack，and not load it by default ,not use it by default,and we can ctr not use some plugins by default 
2. dev-middleware  complier all source the first time , can do it lazy,
3. watch changed and  complier , how to make it more faster,complier the changed file and the right enter file not all, cache the enter file complier content, cache all file complier content  .....
- forget my poor english

**Comment by zhoujianlin8** [comment] 2016-01-11 02:13
when dev i found  the cache has done  but when the project is huge  'Compilation.prototype.seal' it takes to many times   the chunks too many    can you  support multichunks plugin ,(like  the react as a multichunks not much chunks )    the less the chunks the faster wrap the assets

在动态编译过程中，在大型项目中由于依赖关系太多模块文件太多 ，导致合成assets 文件过程太慢，是否可以通过支持缓存模块包集合的方式，比如react模块缓存为react 与对应的文件 而现在react还是由很多chunk模块 与依赖关系每次都得重新合成

**Comment by bebraw** [comment] 2016-12-24 07:39
Can you open small, focused PRs related to those issues?

I'm closing this as the issue is too vague to tackle otherwise.

**Closed by bebraw** 2016-12-24 07:39 UTC
Labels: enhancement
