### ISSUE TITLE
DefinePlugin doesn't work inside React Components

### ISSUE THREAD

**Issue by tadjik1** [webpack/webpack#1977] opened 2016-02-02 16:27 UTC
Hey there. I have a very strange issue with my build. My global variables replaced by webpack inside "normal" files, but not replaced inside files with react.

My config looks like this (it's too big and not interesting):

``` javascript
const GLOBALS = {
  __API__: 'https://my-domain.com/api',
  __ENV: 'development',
  'process.env.NODE_ENV': '"production"'
};

const serverConfig = {
  ...
  module: {
    ...config.module,
    loaders: [
      ...config.module.loaders,
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        cacheDirectory: true,
        query: {
          babelrc: false,
          presets: ['react', 'es2015-node5', 'stage-0'],
          plugins: []
        } 
      },
      sassLoader.development
    ]
  },
  plugins: [
    ...config.plugins,
    new webpack.DefinePlugin({
      '__SERVER__': true,
      ...GLOBALS
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
};
```

And I see inside my build file for node that into some files variable **SERVER** was replaced. It's a normal file without jsx and react. But into another files with react and jsx - not. So a catch an error
`ReferenceError: __SERVER__ is not defined`

For example inside my `redux/modules/window/windowReducer.js`

```
const initialState = {
  viewport: {
    width:  true ? 1366 : window.innerWidth, // Default width for server-side rendering
    height:  true ? 768 : window.innerHeight // Default height for server-side rendering
  },

  body: {
    scrollTop:  true ? 0 : document.body.scrollTop,
    scrollHeight:  true ? 0 : document.body.scrollHeight
  }
};
```

But inside `components/Player/index.js`

```
...
render() {
  if (__SERVER__) return null;

  ...
}
```

**Comment by bebraw** [comment] 2016-02-02 17:06
That's strange. Maybe as workaround you could do something like:

```javascript
const SERVER = __SERVER__;

...
render() {
  if (SERVER) return null;
}
```

**Comment by tadjik1** [comment] 2016-02-03 12:44
@bebraw hah, it works! I'm bit nervous about it, will it work in future versions? Why it's happened?

**Comment by bebraw** [comment] 2016-02-03 13:00
@tadjik1 I'm not exactly sure why it doesn't work within `render()`. Let's leave this open as a bug.

An alternative way to deal with it would be to define a `resolve.alias` and go through a `require`. In this case you would push your configuration (`__SERVER__`) to a custom module which you would swap based on the environment. The cool thing about this approach is that it would allow you to implement easy feature flags and things like that.

**Comment by tadjik1** [comment] 2016-02-03 13:19
@bebraw it doesn't work not only inside ```render()```, inside *any* react component lifecycle method (constructor, componentWillReceiveProps, etc.)

**Comment by bebraw** [comment] 2016-02-03 13:57
Yeah, it could have something to do with ES6 classes. If you look at DefinePlugin code, you can see it's not just a simple replace operation. Most likely the code relies on ES5 semantics.

**Comment by davidpelayo** [comment] 2016-02-05 11:35
@bebraw could you post the references you have been looking at here please?

**Comment by bebraw** [comment] 2016-02-05 11:39
@davidpelayo Here's [the source](https://github.com/webpack/webpack/blob/431a4c791ce8cedebd9df60b0fcf3293c5b180b4/lib/DefinePlugin.js). Especially understanding that `compiler.parser` part should help to understand why the code fails in this particular case.

**Comment by davej** [comment] 2016-03-06 17:41
I'm having this issue too:

```js
config.plugins.push(
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('development')
    }
  })
);
```

In application code, I'm doing something like this:

```js
import React, { Component } from 'react';

export default class App extends Component {
  includeDevTools() {
    if (process.env.NODE_ENV !== 'production') {
      const DevTools = require('./DevTools');
      return <DevTools />;
    }
    return null;
  }

  render() {
    return (
      <div>
        {this.props.children}
        {this.includeDevTools()}
      </div>
    );
  }
}
```

And I get the error, "can not find module `'./DevTools'`".
It's easily fixed by adding the plugin `babel-plugin-transform-es2015-classes` which suggests that webpack just has a problem understanding the ES2015 class semantics.

**Comment by OGPoyraz** [comment] 2016-06-17 11:11
Any update on this issue ?

**Comment by sokra** [comment] 2016-07-11 08:43
> webpack just has a problem understanding the ES2015 class semantics.

That's the problem. Should be fixed in webpack 2 afaik.

**Comment by alex-shamshurin** [comment] 2016-11-01 14:02
+1

**Comment by CallMeXYZ** [comment] 2016-11-07 08:24
+1

**Comment by agusputra** [comment] 2016-11-20 07:05
+1

**Comment by davej** [comment] 2016-11-20 11:02
> +1

Please use the 'thumbs up' button on the original issue at the top instead. It increases visibility to webpack maintainers sorting issues by 'thumps up' reactions. Also, it doesn't spam people who are already subscribed to this issue. :-)

**Comment by elbertcastaneda** [comment] 2016-11-30 20:37
+

**Comment by dropbeardan** [comment] 2018-01-03 04:51
Not sure if ongoing concern, I am currently running:
react: ^16.2.0,
webpack: ^3.8.1

As suggested by #2427, I am able to get the correct response via the following:

> const buildEnv = process.env.NODE_ENV;

> new webpack.DefinePlugin({
>'process.env.NODE_ENV': JSON.stringify(buildEnv),
> baseURL: JSON.stringify('hello')
> });

> render() {
>
> console.log('process.env.NODE_ENV', process.env.NODE_ENV);
> // dev
> console.log('baseURL', baseURL);
> // hello

**Comment by ooflorent** [comment] 2018-05-09 06:51
This is fixed. Since webpack 3, the parser now fully understands ES6 semantics.

**Closed by ooflorent** 2018-05-09 06:51 UTC
Labels: bug

**Comment by godban** [comment] 2018-08-25 20:50
I can reproduce this issue by passing a global variable into dynamic import, like

```jsx
componentDidMount() {
        import(`to/${__SPACE__}/shuttle.svg`).then(...
```

however linking it to another variable solves the issue

```jsx
const space = __SPACE__;

...
componentDidMount() {
        import(`to/${space}/shuttle.svg`).then(...

```

**Comment by liyokuna** [comment] 2018-12-12 11:06
Hey !
I am running into this issue awkardly.
Actually I move from webpack 3.0.0 to 4.17.1.
And my webpack config haven't change much.
this is my function, the way it is, untouched

```
    new webpack.DefinePlugin({
      // Environment helpers
      'process.env': {
        ENV: JSON.stringify(ENV)
      },
      NGBOOSTED_VERSION: JSON.stringify(require(root('package-dist.json')).version),
      BOOSTED_VERSION: JSON.stringify(require(root('package.json')).dependencies.boosted),
      ANGULAR_VERSION: JSON.stringify(require(root('package.json')).dependencies[ANGULAR_V_KEY]),
      NGBOOTSTRAP_VERSION: JSON.stringify(require(root('package.json')).dependencies[NGBOOTSTRAP_V_KEY])
    }),
```
And those variables like NGBOOSTED_VERSION are **undefined**.

I check on the website and I didn't see new stuff or changes. And i am suprised. Anyone have any idea of what causes that trouble ?
