### ISSUE TITLE
Sourcemaps in chrome off by 1 line

### ISSUE THREAD

**Issue by Phoenixmatrix** [webpack/webpack#1487] opened 2015-10-01 22:12 UTC
Using babel loader (and nothing else), and both `inline-source-map` and `source-map`, when setting breakpoints, things are off by one line (eg: if I put a breakpoint on the first line of a function in the original code, once the breakpoint is hit, I'm actually outside of the function. If i put a breakpoint on the second line inside the function, I can inspect the state and everything is as if I was at the first line).

Seems like there has been similar issues last year that had been fixed. Regression maybe?

**Comment by Phoenixmatrix** [comment] 2015-10-01 22:42
As a note: eval-source-map works, so it is potentially limited to inline-source-map and source-map.

Problem with eval-source-map is the query string makes Chrome lose saved breakpoints between refreshes, so its not a great option for us(and i don't think it works with CSS).

**Comment by Phoenixmatrix** [comment] 2015-10-01 23:01
And another detail... looking at the sourcemaps with http://sokra.github.io/source-map-visualization, even going really far in (hundreds of files), everything still seems to match. 

Is it a known Chrome bug or something?

**Comment by Phoenixmatrix** [comment] 2015-10-02 13:40
Adding some more info as I'm debugging this: I made a small project, with the same dependencies and webpack config (just babel loader and inline-source-map), and it works fine, no offset by 1 issues... So something gets quirky in the big project, but I can't pinpoint what.

**Comment by dmitry** [comment] 2015-10-02 13:59
Deactivate requires step by step. I've debugged https://github.com/webpack/webpack/issues/1479 in such way :)

**Comment by Phoenixmatrix** [comment] 2015-10-02 14:45
Ouf that will take a while, it isn't a small app.

That being said, i just compiled our code with Browserify, and the sourcemaps worked fine, with no line offset. So at this point i'm really confused, but its basically a webpack issue.

**Comment by pmowrer** [comment] 2015-10-02 15:53
@Phoenixmatrix Debugging basically the same problem this morning. Most sourcemap configurations appear to be off by one line in Chrome (though trying to step around reveals its off by a lot more off than that). Only `eval` and `sourcemap` seem to work reliably while all of the `cheap` options are busted.

Firefox appears to get it right for the most part.

**Comment by Phoenixmatrix** [comment] 2015-10-02 17:01
So recap:

sourcemap doesn't work for me either. I'm having trouble getting Firefox to hit breakpoints in sourcemapped files at all, so i haven't been able to test it yet.

* In a small project with the same webpack config and the same mix of files, everything worked.
* With eval-source-map, everything worked (except eval source map sucks when refreshing, unless you have a debugger statement in addition to breakpoints, because of a reported chrome bug)
* with inline-source-map/source-map, in our big project, off by 1 (maybe more as you mentionned)
* Same big project, with Browserify, with inline sourcemaps, everything worked.

Analyzing the source map in the anayzer, the lines that are broken in Chrome debugger, are actually mapped properly.

So its something specific to webpack and inline-source-map/sourcemap, that Chrome specifically (If I go by what you said and Firefox works, since I can't get it to work) doesn't like. The sourcemap is possibly "By the spec", but hits the wrong button in Chrome.

**Comment by dmitry** [comment] 2015-10-02 17:04
Have you tried to check after which file it starts to offset?

**Comment by Phoenixmatrix** [comment] 2015-10-02 17:09
I'm having trouble figuring out a methodology for it. There's offset right in my entry point. And in the sourcemap analyzer, 100% of the lines map properly.

I'm going to try to remove requires to see which file hits the issue, and what its location in the output, as that may be able to shed some light on this. If you have any other ideas to debug it, let me know.

**Comment by pmowrer** [comment] 2015-10-02 17:41
The problem I see is most likely https://github.com/huston007/ng-annotate-loader/issues/10. If I disable `ng-annotate-loader`, the problem goes away...

**Comment by Phoenixmatrix** [comment] 2015-10-02 19:20
Yeah, in my case I'm only using babel-loader and coffee-loader, and the source map in the analyzer look correct. So I'm suspecting a different issue.

**Comment by thousand** [comment] 2015-11-10 01:14
I'm having a similar issue and not using any loaders :)

**Comment by outdooricon** [comment] 2016-02-12 11:30
@Phoenixmatrix did you have any luck on this?

**Comment by Phoenixmatrix** [comment] 2016-02-12 13:14
Unfortunately I kind of took the easy way out and am using the eval
devtool, since it ends up being closer to what I want in the end anyway...
and just dealing with the off by 1 in production.

On Fri, Feb 12, 2016 at 6:30 AM Johnathon Sanders <notifications@github.com>
wrote:

> @Phoenixmatrix <https://github.com/Phoenixmatrix> did you have any luck
> on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpack/webpack/issues/1487#issuecomment-183287024>.
>
-- 
-Francois Ward

**Comment by sesteva** [comment] 2016-02-20 22:40
+1

**Comment by dennisfrostlander** [comment] 2016-03-04 21:22
+ 1
In my case it surfaced after upgrading from webpack 1.10.5 + babel 5 to webpack 1.12.12 + babel 6. 
Devtool source-map, eval-source-map and others result in breakpoints jumping in latest Chrome both on mac and windows. The only devtool which appears to be working is eval.

**Comment by duro** [comment] 2016-03-05 19:58
+1 I have been getting this issue for months. I cannot figure out for the life of me what is causing it.

**Comment by danwad** [comment] 2016-03-09 14:49
Ah, thanks @dennisfrostlander, eval is so much better!

This has been bothering me since I started with webpack a few weeks ago. I assumed this was as good as debugging with webpack could get (breakpoints jumping up and down by random amounts) since I'd tried various starter configurations, all having the same issue. I just thought everyone else was dealing with it better than me...

**Comment by outdooricon** [comment] 2016-03-10 17:08
is it safe to assume that everyone who is running into this problem is using Babel-loader? I know I am

**Comment by kabalage** [comment] 2016-03-10 17:10
@outdooricon me too

**Comment by dennisfrostlander** [comment] 2016-03-11 11:43
@outdooricon I am also using babel-loader, and what's more important - it only happens with Babel 6. When I use exact same version of webpack with latest Babel 5, then everything works perfectly.
So now I have a strong suspicion that this is actually a Babel bug.

@danwad yes, while eval is much better in terms of breakpoints, you lose all the nice es6 syntax in source code inspector...

**Comment by Phoenixmatrix** [comment] 2016-03-11 13:53
I had it happen with Babel5 in a codebase that when ran through browserify wouldn't have the issue. So it's not babel6 related, and isn't purely a babel thing. It's probably something Babel outputs that Webpack doesn't handle properly.

The worse is that going through the sourcemap analyzer, the sourcemaps are correct...so it's really some weird edge case in Webpack.

**Comment by bORm** [comment] 2016-03-11 15:18
+1

**Comment by bORm** [comment] 2016-03-11 15:58
http://stackoverflow.com/questions/35637324/breakpoints-in-files-in-chrome-not-being-hit-when-using-webpack-sourcemaps

**Comment by danwad** [comment] 2016-03-15 08:29
`devtool: 'cheap-source-map'` as per @bORm's answer on SO seems to work too.

**Comment by bORm** [comment] 2016-03-15 10:58
@danwad `'cheap-source-map'` shows transformed code

**Comment by danwad** [comment] 2016-03-15 11:47
@bORm Ah! Quite right..

After digging through [SourceMapDevToolPlugin.js](https://github.com/webpack/webpack/blob/v1.12.14/lib/SourceMapDevToolPlugin.js) a bit more, your approach is roughly equivalent to `devtool: 'cheap-module-source-map'`

**Comment by asulaiman** [comment] 2016-03-16 19:29
Eval doesnt play well if you are using ng annotate. Somehow removes the ngInject comment which is pivotal to ngAnnotate implementation perhaps?

**Comment by Phoenixmatrix** [comment] 2016-03-16 20:14
@asulaiman for Eval and ngAnnotate, use the ngInject form where it is -inside- of the function (as the first line). That works beautifully.

**Comment by asulaiman** [comment] 2016-03-16 20:35
Tried with the following - 

`module
    .config(($stateProvider) => {
        /*ngInject*/
        var templateDir = 'app/admin/home/dashboard/templates';

        $stateProvider
            .state('admin|home.dashboard', {
                url: '/admin/dashboard',
                templateUrl: templateDir + '/dashboard.tpl.html',
                controller: DashboardCtrl,
                controllerAs: 'dashboardCtrl'
            });
    });`

Stil fails to annotate $stateProvider.

**Comment by Phoenixmatrix** [comment] 2016-03-16 20:44
oh right, I always used it as string, not comment. Sorry :)

**Comment by asulaiman** [comment] 2016-03-17 13:33
like this?
```

module
    .config(($stateProvider) => {
        /*ngInject*/
        var templateDir = 'app/admin/home/dashboard/templates';

    $stateProvider
        .state('admin|home.dashboard', {
            url: '/admin/dashboard',
            templateUrl: templateDir + '/dashboard.tpl.html',
            controller: DashboardCtrl,
            controllerAs: 'dashboardCtrl'
        });
});
```
Still no dice. :(

**Comment by TroutZen** [comment] 2016-04-13 08:17
+1 using babel-loader

**Comment by danwad** [comment] 2016-04-13 08:20
I am surprised there aren't so many people pulling their hair out over this. Is it only affecting a few of us? I have resorted to using `devtool: 'eval'`

**Comment by danwad** [comment] 2016-04-19 10:37
I think this is now tracked in this babel issue: https://phabricator.babeljs.io/T7210

**Comment by everthis** [comment] 2016-04-30 18:31
+1

**Comment by bebraw** [comment] 2016-08-28 07:50
Given it's an upstream (Babel) issue, I'm closing this. If you want to track the progress, follow https://phabricator.babeljs.io/T7210 .

**Comment by Phoenixmatrix** [comment] 2016-08-28 14:03
I didn't track this issue in a long time because I just use `eval` sourcemaps now (so I can't tell if its still happening), but it was never a babel issue: compiling the exact same code using the same version of Babel in Browserify  would work fine, but in Webpack would be off by 1 line. Also the issue linked above seem to be a different issue altogether.

**Comment by varemenos** [comment] 2017-05-12 10:09
I'm having the same issue but not using babel-loader

  here are the loaders I use:

`cssrules-loader`, `postcss-loader`, `sass-loader`, `pug-loader`, `svg-inline-loader` and `json-loader`

**Comment by pwang2** [comment] 2017-07-18 16:39
+1 and any updates?

**Comment by alecgibson** [comment] 2018-10-03 15:11
In case anyone else stumbles across this thread, we were having a similar issue using Webpack + Babel + ngAnnotate. Moving to the [Babel plugin][1] (as opposed to the Webpack plugin) seems to have solved it for us.

[1]: https://github.com/schmod/babel-plugin-angularjs-annotate

**Comment by nitwhiz** [comment] 2018-12-12 12:00
same thing using ts-loader

**Comment by Bkucera** [comment] 2019-06-10 05:42
I think its an issue with the generated `eval` code. I was able to easily reproduce the following off-by-one error:

using  `devtool: 'eval'` 

This produces the correct eval translation:
![19-06-10_01:39::09](https://user-images.githubusercontent.com/14625260/59174738-9cf49600-8b20-11e9-88d7-de9ab1457670.png)
![19-06-10_01:39::21](https://user-images.githubusercontent.com/14625260/59174742-9f56f000-8b20-11e9-99c3-fc6b13e0ee72.png)
This does not, notice the three `\n`'s before the `const`
![19-06-10_01:35::17](https://user-images.githubusercontent.com/14625260/59174743-a120b380-8b20-11e9-908e-b8a2e1b1f37e.png)
![19-06-10_01:38::14](https://user-images.githubusercontent.com/14625260/59174745-a251e080-8b20-11e9-8364-3e4abcf144b4.png)

which causes the stack trace line nums to be off by one

**Comment by alexander-akait** [comment] 2021-01-15 15:24
Somebody still have the problem with this?

**Comment by vankop** [comment] 2021-09-15 19:31
Stale issue. Feel free to report new issue with reproducible repo.

**Closed by vankop** 2021-09-15 19:31 UTC
Labels: bug, S4: Broken, P2: Very Important
