### ISSUE TITLE
Using `externals` as `script` generate unexpected code

### ISSUE THREAD

**Issue by Kyr** [webpack/webpack#12465] opened 2021-01-20 21:15 UTC
# Bug report

**What is the current behavior?**

Resulting bundle contains unexpected non-es5 instruction: `async`/`await`, arrow function; that does not match expected target, e.g., having defaults target `browserslist` with `android 36`, result:
<details>
<summary>
<code>
module.exports = (async () => {
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var foo_bar__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(299);
foo_bar__WEBPACK_IMPORTED_MODULE_0__ = await Promise.resolve(foo_bar__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var foo_bar__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(foo_bar__WEBPACK_IMPORTED_MODULE_0__);

foo_bar__WEBPACK_IMPORTED_MODULE_0___default()();
</code>
</summary>

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["myLib"] = factory();
	else
		root["myLib"] = factory();
})(globalThis, function() {
return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ 5579:
/***/ ((module, __webpack_exports__, __webpack_require__) => {

"use strict";
module.exports = (async () => {
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var core_js_modules_es_object_to_string_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(1539);
/* harmony import */ var core_js_modules_es_object_to_string_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(core_js_modules_es_object_to_string_js__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var core_js_modules_es_promise_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(8674);
/* harmony import */ var core_js_modules_es_promise_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(core_js_modules_es_promise_js__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var regenerator_runtime_runtime_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(5666);
/* harmony import */ var regenerator_runtime_runtime_js__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(regenerator_runtime_runtime_js__WEBPACK_IMPORTED_MODULE_2__);
/* harmony import */ var foo_bar__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(5299);
foo_bar__WEBPACK_IMPORTED_MODULE_3__ = await Promise.resolve(foo_bar__WEBPACK_IMPORTED_MODULE_3__);
/* harmony import */ var foo_bar__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(foo_bar__WEBPACK_IMPORTED_MODULE_3__);


function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }

function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }


foo_bar__WEBPACK_IMPORTED_MODULE_3___default()();

/*
  skip other code

Added following core-js polyfills:
  es.object.to-string { "android":"36" }
  es.promise { "android":"36" }

Based on your code and targets, added regenerator-runtime.
*/
});
```

</details>

**STR**

Configure webpack to resolve some package as external via `script`
```
    externalsType: "script",
    externals: {
      'foo-bar': 'FooBar@https://example.com/foo-bar.js'
    },
``` 
Configure target via `target: ['web', 'es5']` or via browserslist:
```
  "browserslist": [
    "android >= 36"
  ],
```
Run on code:
```
import Foo from 'foo-bar';

Foo();

(async () => {
  await Promise.resolve();
})();
```

**What is the expected behavior?**

Resulting bundle does not contains unexpected instruction. Expecting to have bundle where **all** code match expected target, via `target`: ['web', es5']` or default, based on browserslist, as same as transpiled source.  

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 14

**Comment by Mjinx** [comment] 2021-01-26 11:23
Been having a similar issue, but in my case its only effecting the vendor modules which are being bundled as my main code is written in TS, which compiles to es5 correctly.

using target: ["web", "es5"] doesn't help either. 

webpack 5.11.1

**Comment by alexander-akait** [comment] 2021-01-26 11:36
We need covert `async` to `Promise().then()`, should be not hard, feel free to send a PR

**Comment by akgupta0777** [comment] 2021-02-04 08:14
how webpack handles async functions ?

**Comment by ruppysuppy** [comment] 2021-02-05 03:14
> We need covert async to Promise().then(), should be not hard, feel free to send a PR

@alexander-akait I would like to work on this issue. Could you tell me which files I need to work on? I am new to the webpack code-base

**Comment by alexander-akait** [comment] 2021-02-05 10:27
It is not easy task, we need regenerator and run it after code was generated

**Comment by akgupta0777** [comment] 2021-02-05 14:46
Where do we get this regenerator from ?

**Comment by ruppysuppy** [comment] 2021-02-06 03:50
I am willing to give it a shot. I do have a decent bit of experience working on a few open source projects, but since I am haven't worked on webpack before, I would require some help getting started.

**Comment by akgupta0777** [comment] 2021-02-06 04:20
@ruppysuppy I will recommend you to read docs and setup instructions in setup.md file to get a headstart

**Comment by ruppysuppy** [comment] 2021-02-06 04:43
>  Could you tell me which files I need to work on?

@akgupta0777  I need help with this, I can get it setup

**Comment by sokra** [comment] 2021-02-07 18:04
As workaround use `import(/* webpackMode: "eager" */ "foo-bar")` instead. This avoids using async modules, which currently need async await in the generated code.

**Comment by ruppysuppy** [comment] 2021-02-08 03:56
This issue seems a bit daunting for a beginner at webpack as @alexander-akait mentioned, I am skipping working on it.

**Comment by aoisummer** [comment] 2021-03-16 05:26
I found a similar problem:
```js
// Generated code in dev mode

/* webpack/runtime/async module */
// ...
var obj = { [webpackThen]: function(fn, reject) { queueFunction(queue, fn), dep.catch(reject); } };
```
This is a ES6 method, may not be compatible with `target: ['web', 'es5']`

webpack: 5.26.0
node: 14.16.0
browser: IE 11

**Comment by alexander-akait** [comment] 2021-03-16 12:10
@aoisummer Please read our docs, you need polyfills for IE 11

**Comment by alexander-akait** [comment] 2021-07-01 12:03
I think we should print warning in this case, still valid

**Comment by vankop** [comment] 2022-04-06 14:49
all async modules on webpack side behave as top-level-await ( in case if `import x from "async-module"` )

_______

we discussed this internally so.. supporting promises on webpack side would require huge code transformation, that webpack in current version can not perform. There is a [PR](https://github.com/webpack/webpack/pull/15612 ) to add warning in case when output environment does not supports async/await.

As user you can:
- build for environment that supports async/await
- don't using top-level-await

**Comment by williamjacobszoon** [comment] 2022-04-13 03:29
@aoisummer did you find a solution to bellow?

> I have the same problem
> 
> ```js
> var obj = { [webpackThen]: function(fn, reject) { queueFunction(queue, fn), dep.catch(reject); } };
> ```
> 
> This is a ES6 method, may not be compatible with `target: ['web', 'es5']`
> 

@alexander-akait Could you please share the link of the documentation where it's referring about polyfills would fix this issue? We are struggling on this issue as we have a requirement to build the project into es5 and we use externals heavily

**Comment by vankop** [comment] 2022-04-13 07:37
@williamjacobszoon you should use dynamic import (`import()`) then.. As I said transforming top-level-await (async/await => promises) is not possible in current webpack design.. 

maybe you can use `babel` for this (for es5 builds transform chunks after compiling..)

**Comment by williamjacobszoon** [comment] 2022-04-14 05:55
@vankop Could you please share some input on how to use babel on runtime chunk? I tried it didn't work for runtime chunk. Appropriate your help on this matter

**Comment by vankop** [comment] 2022-04-14 10:46
not sure about correct config.. I think `@babel/preset-env` will be enough

**Comment by williamjacobszoon** [comment] 2022-04-15 04:34
@vankop still not working with babel loader as per my understanding the runtime is not loaded via loaders so it's not going through the babel loader.

I was expecting, Webpack would generate code according to the target option specified in the config in all aspects and seems like It is not.

Shouldn't this be a major bug in webpack as It's no honoring the target set by the config when it's generating the webpack related code (runtime/helpers)?

**Comment by vankop** [comment] 2022-04-15 08:32
@williamjacobszoon not `babel-loader`, just use babel on output ( only for es5 )

______

better use `import()` instead of top-level-await

**Comment by vankop** [comment] 2022-04-15 08:33
> I was expecting, webpack would generate code according to the target option specified in the config in all aspects and seems like it is not.

It does. By in case of top-level-await it is not possible in current design ( transform async to promises ), so you have 2 options https://github.com/webpack/webpack/issues/12465#issuecomment-1090360739

**Comment by williamjacobszoon** [comment] 2022-04-15 09:37
@vankop I'm kind of disappointed see your response. because non of these things are explained in the documentation about using externals will cause the output to be not compatible with es5. I'm getting to know all these things at the final phase of our application development now I have to restructure the whole app again 😭

**Comment by vankop** [comment] 2022-04-15 09:40
>  because non of these things are explained in the documentation about using externals

yeah, sorry about this.. changing `import x from "x"` to `import("x")` should not be a big problem.

**Comment by aoisummer** [comment] 2022-04-16 06:48
> @aoisummer did you find a solution for below?
> 
> > I have the same problem
> > ```js
> > var obj = { [webpackThen]: function(fn, reject) { queueFunction(queue, fn), dep.catch(reject); } };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is a ES6 method, may not be compatible with `target: ['web', 'es5']`
> 
> @alexander-akait Could you please share the link of the documentation where it's referring about polyfills would fix this issue? We are struggling on this issue as we have a requirement to build the project into es5 and we use externals heavily

I try to reproduce that today, but it has been fixed in newer version. This issue still exists, which means the feature `externals script` cannot run when your browser does not support async function. Here is my test code:

```
// webpack.config.js
module.exports = {
    mode: 'development',
    target: ['web', 'es5'],
    externalsType: 'script',
    externals: {
        react: 'React@https://cdn.jsdelivr.net/npm/react@17/umd/react.development.js',
        'react-dom': 'ReactDOM@https://cdn.jsdelivr.net/npm/react-dom@17/umd/react-dom.development.js',
    },
};
```

webpack: 5.72.0
node: 16.14.2
browser: IE 11

**Comment by williamjacobszoon** [comment] 2022-04-16 07:18
@aoisummer Thanks for the update.

I just found out there is separate issue raised for top-level await generation on es5 target.

[Compile top-level await to ES5 #11874](https://github.com/webpack/webpack/issues/11874)

https://github.com/webpack/webpack/blob/main/lib/async-modules/AwaitDependenciesInitFragment.js

**Comment by vankop** [comment] 2022-04-16 12:21
yeah, lets close this in favor of #11874

**Closed by vankop** 2022-04-16 12:21 UTC
Labels: webpack-5
