### ISSUE TITLE
`resolve.extensionAlias` is not taking in account for the dynamic imports expressions evaluation

### ISSUE THREAD

**Issue by majo44** [webpack/webpack#17068] opened 2023-04-26 13:22 UTC
# Bug report

**What is the current behavior?**
For the dynamic imports which contains some expression, the `resolve.extensionAlias` configuration option is not used to resolving the imports.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
// Config
const config = {
    ...
    resolve: {
        extensions: [ '.ts', '.tsx', '.js', '.jsx' ],
        extensionAlias: {
            '.js': [ '.js', '.ts', '.tsx' ]
        }
    }
  ...
};
```

```js
// Input:
// /index.ts
const x = 'a';
import(`./lazy-${x}.js`);
// /lazy-a.ts
export {}
```

```js
// Output:
...
/***/ "./. lazy recursive ^\\.\\/lazy\\-.*\\.js$":
/*!*****************************************************!*\
  !*** ././ lazy ^\.\/lazy\-.*\.js$ namespace object ***!
  \*****************************************************/
/***/ ((module) => {

function webpackEmptyAsyncContext(req) {
	// Here Promise.resolve().then() is used instead of new Promise() to prevent
	// uncaught exception popping up in devtools
	return Promise.resolve().then(() => {
		var e = new Error("Cannot find module '" + req + "'");
		e.code = 'MODULE_NOT_FOUND';
		throw e;
	});
}
webpackEmptyAsyncContext.keys = () => ([]);
webpackEmptyAsyncContext.resolve = webpackEmptyAsyncContext;
webpackEmptyAsyncContext.id = "./. lazy recursive ^\\.\\/lazy\\-.*\\.js$";
module.exports = webpackEmptyAsyncContext;

/***/ })
...
(() => {
/*!******************!*\
  !*** ./index.ts ***!
  \******************/
const x = 'a';
__webpack_require__("./. lazy recursive ^\\.\\/lazy\\-.*\\.js$")(`./lazy-${x}.js`);
})();
...
```

When we will change the code to use `.ts` extension in the import like:
```js
...
import(`./lazy-${x}.ts`);
...
```

Or we remove the the extension from the import expression like
```js
...
import(`./lazy-${x}`);
...
```

The output code is fine and contains the resolution map like:

```js
// Output:
...

/***/ "./. lazy recursive ^\\.\\/lazy\\-.*\\.ts$":
/*!*****************************************************!*\
  !*** ././ lazy ^\.\/lazy\-.*\.ts$ namespace object ***!
  \*****************************************************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {
var map = {
	"./lazy-a.ts": [
		"./lazy-a.ts",
		"lazy-a_ts"
	]
};
...
```

The full gist: https://gist.github.com/majo44/e774abdc4aea027d11df1ee8582e97ee

**What is the expected behavior?**

In case of es module javascript/typescript code the extensions formally are obligatory, the typescript resolution logic also supports the '.js' extensions. Webpack perfectly handling that for the static imports and for the dynamic imports without expressions by using of provided `extensionAlias` configuration property. Unfortunately it is not align with the resolution of dynamic imports with expressions. The expectation is to properly resolve the dynamic imports with expression by taking the `extensionAlias` in consideration. 

**Other relevant information:**
webpack version:  5.80.0
Node.js version:  v18.16.0
Operating System: Windows 11

**Comment by alexander-akait** [comment] 2023-04-26 13:26
Yeah, duplicate of https://github.com/webpack/webpack/issues/13865, it doesn't work with good with `enhanced-resolve`

**Closed by alexander-akait** 2023-04-26 13:26 UTC

**Comment by alexander-akait** [comment] 2023-04-26 13:28
So `exports`, `extensionAlias` and some other stuff doesn't work correctly, the main problem we can't undestan what is ``./lazy-${x}.js`, is it file or maybe you have `const x = folder/foo/bar/baz`, so it is very limited, please think double - do you real need it? It doesn't mean we don't want to fix it, it means it is hard to handle all possible cases

**Comment by majo44** [comment] 2023-04-28 01:11
So maybe the `webpackInclude` should be obligatory ? and matched globs count limited to some number like 10, 20 ,30 ?, with option to overwrite by config. My case is internationalisation, where we working on huge monorepo, where each logical component is separate package, compiled from ts to js, and has own internationalisation, and is responsible for loading it. We supports several languages, but is not obligatory that each component has internationalisation for each language. So for now we are repeating: 
```
await loadLazyI18nResources(i18n, {
    [Lang.EN]: () => import('./foo.i18n-en.js'),
    [Lang.NL]: () => import('./foo.i18n-nl.js'),
    ...
}); 
````
instead 
```
await loadLazyI18nResources(i18n, lng => import(`./foo.i18n-${lng}.js`)); 
```
Also in our case process of translations generation is automated, so new `foo.i18n-<lng>.ts` is added to source code automatically by editors tool, but loader has to be updated manually what is error prone.
