### ISSUE TITLE
Webpack v5 - Module federation issue with loading chunks

### ISSUE THREAD

**Issue by brussev** [webpack/webpack#11663] opened 2020-10-13 07:03 UTC
**What is the current behavior?**
I moved from 5.beta.17 to the official 5.0.0 webpack version and the module federation project fails with with different errors as I think the main one is `ChunkLoadError: Loading chunk src_components_admin_users_index_js failed.`.
Funny thing is that sometimes it works sometimes not. Sometimes its loading all the chunks sometimes not..

Both host and plugin projects live in S3 bucket and when I try to connect from my local pc to the s3 bucket for the plugin everything works smoothly. I don't know how this chunk name was created as I don't see it in the s3 bucket.
I am developing a host and plugin project using module federation since the beginning and everything was ok until I move to 5.0.0.
**The 1st error which I get is:** 
`GET ... 404
ChunkLoadError: Loading chunk src_components_admin_users_index_js failed.`. --> But there is not a chunk with this name at all..

**2nd error which I get and it is super weird is about duplicated graphql packages.**
![Screenshot 2020-10-13 at 9 48 43](https://user-images.githubusercontent.com/45165261/95825285-4a8d4000-0d39-11eb-922f-21380503d199.png)

** I had the same issue in the beginning but forcing the dep to be singleton worked perfectly before.

**If the current behavior is a bug, please provide the steps to reproduce.**

Host project: webpack.config:
```
/** @type {import('webpack').Configuration} */
module.exports = {
    output: {
        publicPath: dotenv.parsed.REACT_APP_PUBLIC_PATH,
        uniqueName: 'platform',
        filename: '[name].js',
        library: 'platform',
        chunkFilename: '[name][chunkhash].js'
    },
    devtool: 'source-map',
    cache: false,
    resolve: {
        extensions: ['.jsx', '.js', '.json'],
        alias: {... }
    },
    module: {
        rules: [
              .... loaders,
             // I leave this one here as I needed to do in order to run the project locally after migration to 5.00
            {
                test: /\.m?js/,
                resolve: {
                    fullySpecified: false
                }
            }
        ]
    },
    plugins: [
        new ModuleFederationPlugin({
            name: 'platform',
            library: { type: 'var', name: 'platform' },
            filename: 'remoteManifest.js',
            remotes: {
                app1: 'app1'
            },
            exposes: {
                 ....Components..
            },
            shared: {
                ...dependencies,
                react: {
                    eager: true,
                    singleton: true,
                    requiredVersion: dependencies.react
                },
                'react-dom': {
                    eager: true,
                    singleton: true,
                    requiredVersion: dependencies['react-dom']
                },
                'react-router-dom': {
                    eager: true,
                    singleton: true,
                    requiredVersion: dependencies['react-router-dom']
                },
                '@apollo/client': {
                    singleton: true,
                    requiredVersion: dependencies['@apollo/client']
                },
                graphql: {
                    singleton: true,
                    requiredVersion: dependencies['graphql']
                },
            }
        }),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, 'public/index.html'),
            filename: './index.html',
            inject: true,
            favicon: path.resolve(__dirname, 'public/favicon.ico')
        })
    ]
};
```
**webpack.config remote plugin:**
```

/** @type {import('webpack').Configuration} */
module.exports = {
    output: {
        path: DIST_DIR,
        uniqueName: 'plugin',
        filename: '[name].js',
        library: 'plugin',
        chunkFilename: '[name][chunkhash].js',
        publicPath: dotenv.parsed.REACT_APP_PUBLIC_PATH
    },
    devtool: 'source-map',
    resolve: {
        extensions: ['.jsx', '.js', '.json'],
        alias: {}
    },
    devServer: {
        historyApiFallback: true,
        inline: true,
        port: parseInt(dotenv.parsed.PORT)
    },
    module: {
        rules: [
            loaders...,
            {
                test: /\.m?js/,
                type: 'javascript/auto',
                resolve: {
                    fullySpecified: false
                }
            }
        ]
    },
    plugins: [
        new ModuleFederationPlugin({
            name: 'app1',
            library: { type: 'var', name: 'app1' },
            filename: 'remoteManifest.js',
            remotes: {
                platform: 'platform'
            },
            exposes: {
              ....components
            },
            shared: {
                ...dependencies,
                react: {
                    singleton: true,
                    requiredVersion: dependencies.react
                },
                'react-dom': {
                    singleton: true,
                    requiredVersion: dependencies['react-dom']
                },
                '@apollo/client': {
                    singleton: true,
                    requiredVersion: dependencies['@apollo/client']
                },
                graphql: {
                    singleton: true,
                    requiredVersion: dependencies['graphql']
                }
            }
        })
    ]
};
```

**And my package.json: ( they look pretty much the same in both ):**
```
"scripts": {
    "start": "webpack-dev-server --mode development --liveReload",
    "build:prod": "webpack --mode production",
    "generate": "graphql-codegen --config codegen.yml",
    .. more scripts...
  },
  "dependencies": {
    "@apollo/client": "^3.2.3",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/runtime": "^7.11.2",
    "dotenv": "^8.2.0",
    "exceljs": "^4.1.1",
    "file-saver": "^2.0.2",
    "graphql": "15.3.0",
    "jsdoc": "^3.6.4",
    "json-loader": "^0.5.7",
    "lodash": "^4.17.19",
    "mini-css-extract-plugin": "^0.9.0",
    "moment": "^2.27.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-flexa": "^0.9.1",
    "react-router-dom": "5.2.0",
    "react-select": "^3.1.0"
  },
```
**Code to get remote scripts:** 

```
export const useDynamicScript = () => {
    const [ready, setReady] = useState(false);
    const [failed, setFailed] = useState(false);

    useEffect(() => {
        const fetchManifests = async (urls) => {
            Promise.all(urls.map((url) => loadScript(url))).then(() => setReady(true));
        };
        setReady(false);
        setFailed(false);

        let urls = Object.entries(process.env)
            .filter((x) => x[0].endsWith('PACKAGE'))
            .map((y) => y[1]);

        fetchManifests(urls);
    }, []);

    return {
        ready,
        failed
    };
};

export const loadComponent = (scope, module) => {
    return async () => {
        // Initializes the share scope. This fills it with known provided modules from this build and all remotes
        await __webpack_init_sharing__('default');
        const container = window[scope]; // or get the container somewhere else
        // Initialize the container, it may provide shared modules
        await container.init(__webpack_share_scopes__.default);
        const factory = await window[scope].get(module);
        const Module = factory();

        return Module;
    };
};

const loadScript = (url) =>
    new Promise((resolve) => {
        const element = document.createElement('script');
        element.async = true;
        element.src = `${url}remoteManifest.js`;
        element.type = 'text/javascript';

        document.head.appendChild(element);

        element.addEventListener('load', resolve, {
            once: true
        });
    });
```

What I tried? 
- Connecting to the s3 bucket from my local machine and everything works perfectly.
- Adding resolutions in the package.jsons in both of the projects.
- Clean installs multiple times
- Singleton/Eager in both of them ( another topic is that I dont think its needed - just tried everything which I could think of) 

**What is the expected behavior?**

It should load normally as its in local mode.

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 12.10
Operating System: 
Additional tools: Hosted in S3 bucket

**Comment by sokra** [comment] 2020-10-13 08:17
> ChunkLoadError: Loading chunk src_components_admin_users_index_js failed.

Did you deploy a development build? That filename is something a development build would generate...

I didn't see anything obvious in your config. Sounds more like a deployment problem....

Some things are weird in your config, but I don't think they case that problem.

``` diff
     output: {
         publicPath: dotenv.parsed.REACT_APP_PUBLIC_PATH,
+        // uniqueName should be unneeded when your "name" in package.json is unique
         uniqueName: 'platform',
         filename: '[name].js',
-        library: 'platform',
         chunkFilename: '[name][chunkhash].js'
     },
 // ...
                react: {
                    eager: true,
                    singleton: true,
-                   requiredVersion: dependencies.react
                },
```

`requiredVersion` should be automatically inferred (`requiredVersion` might be different when some node_modules use react too). Some for the other dependencies.

`eager: true` should be avoid otherwise they will load multiple times.

**Comment by brussev** [comment] 2020-10-13 08:31
@sokra thanks for the fast anser. Exactly! Both of the builds are flagged with mode production and S3 bucket does not have anything related with these names so I don't know how it was searching for them.
Also do you have an idea why I can get duplicated graphql deps when I marked it singleton?

Note: I know about eager is not needed and I just tried everything which I could think of before posting an issue.

**Comment by sokra** [comment] 2020-10-13 08:37
> Also do you have an idea why I can get duplicated graphql deps when I marked it singleton?

As long it's marked as singleton, that should not happen. Probably also related to the deployment or server caching issue...

**Comment by brussev** [comment] 2020-10-13 11:22
Do you see somewhere an issue with the loading of the scripts? 
At the moment it seems to work if I go and load specific component first.. and then the others work too but if I don't nothing works..It's super weird. Do I need to use new syntax and mark `@app2/path` in the webconfig?

**Comment by brussev** [comment] 2020-10-13 11:23
Some of these are shown also..
![Screenshot 2020-10-13 at 14 23 39](https://user-images.githubusercontent.com/45165261/95854481-b2568180-0d5f-11eb-9f73-d636aa04f6ed.png)

**Comment by brussev** [comment] 2020-10-13 11:46
> As long it's marked as singleton, that should not happen. Probably also related to the deployment or server caching issue...

Regarding cache issue - cloudfront is purged and it shouldnt be that.

**Comment by ScriptedAlchemy** [comment] 2020-10-13 14:40
You’re missing a dynamic import. It looks like. 

Check my examples repo for module federation and confirm you’re following patterns established there

**Comment by brussev** [comment] 2020-10-13 15:59
@ScriptedAlchemy I am using the dynamic import as shown in the code or I am missing smth?
I have been using your example as a template actually [Dynamic import example](https://github.com/module-federation/module-federation-examples/blob/master/dynamic-system-host/app1/src/App.js) 
I just pass multiple urls as I have multiple plugins (defined them in env variables) in the useDynamicScript hook?

P.S. Everything works smoothly in the development mode.

App.js

```
const App = () => {

    const { ready, failed } = useDynamicScript();

    if (!ready) {
        return (
                <Loading />
        );
    }

    return (
        <div> Code... </div>
    );
};

render(<App />, document.getElementById('app'));
```

```

export const useDynamicScript = () => {
    const [ready, setReady] = useState(false);
    const [failed, setFailed] = useState(false);

    useEffect(() => {
        const fetchManifests = async (urls) => {
            Promise.all(urls.map((url) => loadScript(url))).then(() => setReady(true));
        };
        setReady(false);
        setFailed(false);

        let urls = Object.entries(process.env)
            .filter((x) => x[0].endsWith('PACKAGE'))
            .map((y) => y[1]);

        fetchManifests(urls);
    }, []);

    return {
        ready,
        failed
    };
};

export const loadComponent = (scope, module) => {
    return async () => {
        // Initializes the share scope. This fills it with known provided modules from this build and all remotes
        await __webpack_init_sharing__('default');
        const container = window[scope]; // or get the container somewhere else
        // Initialize the container, it may provide shared modules
        await container.init(__webpack_share_scopes__.default);
        const factory = await window[scope].get(module);
        const Module = factory();

        return Module;
    };
};

const loadScript = (url) =>
    new Promise((resolve) => {
        const element = document.createElement('script');
        element.async = true;
        element.
```src = `${url}remoteManifest.js`;
        element.type = 'text/javascript';

        document.head.appendChild(element);

        element.addEventListener('load', resolve, {
            once: true
        });
    });

**Comment by ScriptedAlchemy** [comment] 2020-10-14 03:40
What happens if you comment out the exposed modules? Also is the entrypoint  using import(bootstrap) ? 

If so. Then delete the library config on MF. That's caused me problems. You might also want to consider using the updated syntax. Just to rule out potential issues. 

If I expose a top level file then also consume that - I'll get errors sometimes. My shared-routing/shell webpack config shows me exposing and sharing a module so everything works. 

You might also want to consider trying to have the host load its own remote too. I've got projects that use the hosts own remote to boot up. You could try that. 

I recently updated the whole repo to v5 stable. So it might be with checking the now merged PR to get a sense of what changes I made. It's probably good to try the auto mode and url syntax for remotes in the webpack MF config. Just to confirm it's not a problem with remotes not attaching themselves. You might want to try catch the init method. If it's running more then once for some reason then it might be causing issues trying to re-init every time you get a component. My demo likely loads one thing from another remote. So it might just be that loadComponent triggered multiple times and it's attempting to reattach share scope to something that's already attached. I've not seen this in the browser but remember putting a catch on the init for node. Without a repo it's harder to debug dynamic remotes.

**Comment by brussev** [comment] 2020-10-14 10:42
It's using entrypoint yes and the exposed modules are usually uncommented - I just reduced the code for the issue reporting.
I will try the new syntax as you said and check what you have commited with the webpack v5 PR but is the old syntax gonna be deprecated?
Regarding the multiple components getting loaded at the same time - isn't the module federation solving this issue? This is my current view of the app and it's actually loading multiple components at once is present?

![Screenshot 2020-10-14 at 11 05 22](https://user-images.githubusercontent.com/45165261/95961013-28fd8880-0e0d-11eb-8e15-46cc6ac3a93c.png)

Regarding the main issue: For now I solved my issue with using 5.0.31.beta and using development build in stage ( no other change ) only for the host and the remotes are correctly build with prod mode, which I don't like at all.. its super weird how this is working smoothly with dev build.. I will try what you said asap and continue in this thread. 
Thanks again for the fast responses.

**Comment by ScriptedAlchemy** [comment] 2020-10-14 15:39
Old syntax won't be deprecated. It's just more specific because I don't think it works without library being defined as var. so if webpack or something changes, it might be harder to debug. That's why I rule out issues by using née syntax so webpack manages the order just to make sure. 

And what I mean is The issue isn't with MF necessarily, but with my loadComponent code which might be reinitializing share scope over and over as you use the hook. Init only needs to happen once and same with initialize sharing. The only thing we really repeat is the get call to the container. So if you're using loadConponent it might be reinitializing that container over and over and over every time you want to load a new component. 

If graph is the issue when sharing. It might be worth looking at what that package uses under the hood or if it got a peer dep that it wants. It seems like it should just work but it's worth debugging a few of these to see if something helps.

**Closed** 2020-11-27 18:29 UTC
Labels: webpack-5

**Comment by alex-vukov** [comment] 2020-12-09 13:37
> And what I mean is The issue isn't with MF necessarily, but with my loadComponent code which might be reinitializing share scope over and over as you use the hook. Init only needs to happen once and same with initialize sharing. 
@ScriptedAlchemy from this I understand that ```container.init(__webpack_share_scopes__.default);``` needs to happen only once per container but how about ```__webpack_init_sharing__('default')```? Does it need to be called once per container or only once in the lifetime of the application?

**Comment by elenasch** [comment] 2021-04-10 12:17
I was having a similar issue to `404 ChunkLoadError: Loading chunk src_components_admin_users_index_js failed`,  with host app  running in hot replace mode but remote app without it. 
What finally helped was removing the `optimization.runtimeChunk = 'single'` setting

**Comment by smasala** [comment] 2021-05-31 13:32
Since NG 12 - I'm also having a similar issue where it's trying to load the lazy loaded module on the host rather than the remote.

**Comment by cjones26** [comment] 2022-10-13 19:01
> Since NG 12 - I'm also having a similar issue where it's trying to load the lazy loaded module on the host rather than from the remote origin.

Did you ever figure out why this was happening?  I'm seeing the same exact issue.

**Comment by cjones26** [comment] 2022-10-13 19:15
Looks like this is related to `output.publicPath`.  Changing this from `/` to `auto` in my remote module fixed the issue:

```
output: {
  publicPath: 'auto',
},
```

https://webpack.js.org/guides/public-path/#automatic-publicpath

**Comment by maitrungduc1410** [comment] 2022-12-20 03:47
I'm having same issue, even I already set `publicPath: 'auto'`.

I realized that when I build in production mode, few chunks are missing, but they're referenced in `remoteEntry.js`. Weird

**Comment by lucasdu4rte** [comment] 2023-07-20 17:11
I'm having the same issue as you @maitrungduc1410 , I will try to use https://www.npmjs.com/package/webpack-retry-chunk-load-plugin.
But I'm not safe about this because this problem comes from removeEntry.js generated by Module federation.

**Comment by skstef** [comment] 2024-04-03 21:45
The problem still persists

Webpack v.5.90.3

**Comment by ScriptedAlchemy** [comment] 2024-04-10 20:15
You can control the lifecycle of federation via federation runtime plugins. Offline remote should work as well.

https://github.com/module-federation/module-federation-examples/blob/master/runtime-plugins/offline-remote/app1/offline-remote.ts

**Comment by yajgana** [comment] 2024-04-23 19:46
Why would a retry work when the requested file is for the wrong host?

Really confused here on why the host would try to load the chunk file of the remote in the wrong address. It is requesting from the host address instead of the remote. Doesn't `_webpack_require_` somehow provide the correct address to load the files?
