### ISSUE TITLE
Webpack stucks and keep spawning hundreds of nodejs processes

### ISSUE THREAD

**Issue by KangZiRu** [webpack/webpack#7167] opened 2018-05-01 10:15 UTC
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
Webpack is stuck when running the command and keep spawning nodejs processes.
The nodejs processes can up to 300 processes or even more, until I force stop it by using Ctrl+C.

The commands I mentioned above are:
`webpack --mode development`
`webpack --mode production`
or other basic commands.

I tried to run `webpack --mode developmenta` , but webpack doesn't tell me typo on *developmenta*. It keeps stuck and spawing bunch of nodejs processes.

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce, I just run the basic command as I told above.

**What is the expected behavior?**
The webpack bundles my scripts as usual.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node: 9.3.0
webpack: 4.2.0
webpack-cli: 2.0.12

I don't know what happened, but yesterday, my webpack is running as usual, nothing weird. But today, it happens to all of my projects.
Is it related to cache problems?

**EDIT**
There is only one directory affected to this problem. The directory itself is just normal directory (no node_modules, package.json, git, etc.) with several projects located inside.

**Comment by sokra** [comment] 2018-05-01 12:51
webpack shouldn't spawn processes at all.

Is the webpack command really executing webpack?

Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by KangZiRu** [comment] 2018-05-02 01:46
I think I can't create a github repo, because the problem is located in webpack itself. I confirmed that there is a infinite loop that causes this problem. I confirmed it by using simple `console.log` in `node_modules/webpack/bin/webpack.js` and `node_modules/webpack-cli/bin/webpack.js`.

Here is the screenshot (not working one):
![image](https://user-images.githubusercontent.com/10009075/39501400-c8c76142-4de4-11e8-84c7-f3d530340929.png)

While the working one:
![image](https://user-images.githubusercontent.com/10009075/39501426-f83fd5c6-4de4-11e8-9c84-11ece8e19b1d.png)

**Comment by PlayMa256** [comment] 2018-05-02 12:27
I tried to reproduce the problem, and there is something weird in between because, if i run `webpack --mode developmenta` as you ran, `webpack-cli` yells saying developmenta [is not a known choice](http://prntscr.com/jcqqpi) for mode and stops the proccess upfront. `Webpack/bin/webpack.js` is only called once, the flow is: `webpack/bin/webpack.js` -> `webpack-cli/bin/webpack.js` -> `webpack/lib/webpack.js` and the compilation process starts. This does not goes to `webpack/bin/webpack` again. Were you able to reproduce this in a small project? That is easier so people can reproduce and fix this issue.

**Comment by KangZiRu** [comment] 2018-05-03 07:26
Yes, it should be the expected behavior, but in this case, whatever you input in the cli, it won't run the command. Instead it only spawning bunch of nodejs processes through the `require("webpack-cli")` I mentioned above.

**Comment by sokra** [comment] 2018-05-03 07:33
Sound like a bug in webpack-cli @ev1stensberg

**Comment by ev1stensberg** [comment] 2018-05-03 08:10
This is fixed

**Comment by evilebottnawi** [comment] 2018-05-03 09:25
@ev1stensberg i.e. we can close this issue?
@KangZiRu friendly ping, update `webpack-cli` to latest version and check again

**Comment by TheLarkInn** [comment] 2018-05-04 07:26
@ev1stensberg can you please reference PR # for this issue so they are linked together?

**Comment by ev1stensberg** [comment] 2018-05-04 08:11
#377 this PR made the bug, reverted it for now ( sadly )

**Comment by KangZiRu** [comment] 2018-05-04 15:37
Sorry for the late reply.  I upgraded to  `webpack-cli@2.1.2` and now it works as charm.

**Closed** 2018-05-04 16:15 UTC
