### ISSUE TITLE
input filesystem

### ISSUE THREAD

**Issue by tcurdt** [webpack/webpack#1562] opened 2015-10-28 17:38 UTC
I am using the node API and would like to take control of the loading of the input files.
I was hoping to be able to do something along the lines of

```
resolve = function(absPathFrom, includeArgument, cb) {
  var absPathTo = path.resolve(absPathFrom, includeArgument);
  var content = fs.readFileSync(absPathTo, 'utf-8');
  cb(null, content);
}
```

but seems like implementing a full filesystem along the lines of https://github.com/webpack/memory-fs/blob/master/lib/MemoryFileSystem.js is needed.

Is that correct? Or is there an easier way?

**Comment by tcurdt** [comment] 2015-10-29 00:10
Just to explore a bit I was trying

    var mock = {};

    [
      "statSync",
      "readdirSync",
      "mkdirpSync",
      "mkdirSync",
      "rmdirSync",
      "unlinkSync",
      "readlinkSync",

      "stat",
      "readdir",
      "mkdirp",
      "mkdir",
      "rmdir",
      "unlink",
      "readlink",

      "meta",
      "existsSync",
      "readFileSync",
      "_remove",
      "writeFileSync",
      "join",
      "normalize",
      "exists",
      "readFile",
      "writeFile",
    ].forEach(function(name){
      mock[name] = function() {
        console.log('CALLED', name);
      }
    });

    compiler.inputFileSystem = mock;

but somehow nothing is getting called when I compile

      compiler.run(function(err, stats) {
          console.log('BUNDLED', err);
      });

**Comment by aackerman** [comment] 2015-10-29 00:45
Can you be clearer about what you're trying to accomplish. Are you implementing a plugin or looking to modify the existing behavior for the node environment?

**Comment by tcurdt** [comment] 2015-10-29 01:54
@aackerman  I am trying to use webpack from node to bundle files that are in memory - not on the file system.

**Comment by tcurdt** [comment] 2015-11-06 10:47
Any idea why the input filesystem is not being used? Here is a more complete example how I try to use `webpack`:

    var compiler = Webpack({
      output: {
        path: "/",
        filename: "bundle.js"
      },
      entry: [
        './index.js'
      ]
    });

    var mock = {};

    [
      "statSync",
      "readdirSync",
      "mkdirpSync",
      "mkdirSync",
      "rmdirSync",
      "unlinkSync",
      "readlinkSync",

      "stat",
      "readdir",
      "mkdirp",
      "mkdir",
      "rmdir",
      "unlink",
      "readlink",

      "meta",
      "existsSync",
      "readFileSync",
      "_remove",
      "writeFileSync",
      "join",
      "normalize",
      "exists",
      "readFile",
      "writeFile",
    ].forEach(function(name){
      mock[name] = function() {
        console.log('CALLED', name);
      }
    });

    compiler.inputFileSystem = mock;
    compiler.outputFileSystem = new MemoryFS();

    compiler.run(function(err, stats) {
      if (err) {
        ...
      } else {
        console.log('BUNDLED');
        ...
      }
    });

**Comment by DatenMetzgerX** [comment] 2015-12-17 16:47
I struggled with the same. If you take a look into the `lib/node/NodeEnvironmentPlugin.js`, then you can see that webpack uses multiple file systems for different files. This is very flexible but is not very obvious how to use... But, it's exactly what you need

The important lines are:

```js
compiler.resolvers.normal.fileSystem = compiler.inputFileSystem;
compiler.resolvers.context.fileSystem = compiler.inputFileSystem;
compiler.resolvers.loader.fileSystem = compiler.inputFileSystem;
```

Most certainly you don't want to override the loader filesystem (except you want to use dynamic loader implementation, but that sounds sick). Theres also a Watcher filesystem, in case you want to use webpack in watch mode....

A working configuration looks like

```js
var compiler = webpack(options);
compiler.inputFileSystem = fs;
compiler.resolvers.normal.fileSystem = compiler.inputFileSystem;
compiler.resolvers.context.fileSystem = compiler.inputFileSystem;
compiler.outputFileSystem = fs;
```

**Comment by tcurdt** [comment] 2015-12-18 00:21
Ah! That I did miss. Will give that a try and report back! Thanks, @DatenMetzgerX

**Comment by christianalfoni** [comment] 2016-02-15 22:48
Hi guys,

Did you figure this out? I am trying to use the webpack middleware to run with "in memory input filesystem". Though not having any luck.

**Comment by tcurdt** [comment] 2016-02-16 12:53
@christianalfoni haven't had the time look into it again.
I'll try to get my code up on github and will report back.
Please let me know if you are faster ;)

**Comment by christianalfoni** [comment] 2016-02-19 00:54
I been at this for a few hours and I make it work partly. The problem is loaders. The loaders resolve relatively to the file that you are resolving. That means if loaders are coming from actual file system and the file you want to resolve is in the "in memory" file system, you got a problem. The paths wont match. I tried to add "in memory" filesystem to loader as well, but no luck. Does not seem to find them at all, which I find very strange.

**Comment by DatenMetzgerX** [comment] 2016-02-19 12:08
I managed to get it working in a test case. The loaders are loaded from the real filesystem and the entry file is loaded from the memory fs

see [this gist](https://gist.github.com/DatenMetzgerX/2a96ebf287b4311f4c18) for the extracted test case.

**Comment by christianalfoni** [comment] 2016-02-19 12:36
I just managed it as well, https://github.com/christianalfoni/webpack-bin. Some of the loaders are actually also run from from within your bundled code. Like with style and css loader. The way I solved this is to expose the loaders on the same path as on the filesystem, though they are indeed inside the memory filesystem. That way it does not matter if webpack loads from memory or actual file system, its the same path.

https://github.com/christianalfoni/webpack-bin

I also made a video on what we hope to achieve with this:

https://www.youtube.com/watch?v=QE5LWnmDg3Q

**Comment by danbucholtz** [comment] 2016-10-30 06:12
@DatenMetzgerX and others,

Were you able to get `watch` functionality to work with the in-memory FS? I have seen the `watch` trigger the initial build but never a subsequent build on change.

Here is my very small POC:

```
var MemoryFileSystem = require("memory-fs");
var webpack = require('webpack');
//var fs = require('fs');
var fs = new MemoryFileSystem();
var fileContent = 'Initial Content';
var count = 0;

var path = require('path');

var directory = path.join(process.cwd(), 'dist');
var entryPoint = path.join(directory, 'entry.js');

function writeFile(content) {
  fs.writeFileSync(entryPoint, content);
  //console.log(content);
  var theContent = fs.readFileSync(entryPoint).toString();
  console.log('theContent: ', theContent);
}

//fs.mkdirSync(directory);
fs.mkdirpSync(directory);
writeFile(fileContent);

setInterval(() => {
  count++;
  fileContent = fileContent + '\n' + `This function has been called ${count} times` + '\n';
  writeFile(fileContent);
}, 2500);



var compiler = webpack({
  entry: entryPoint,
  output: {
    path: directory,
    filename: 'bundle.js'
  },

  resolve: {
    extensions: ['.js', '.json']
  },
});
/*compiler.inputFileSystem = fs;
compiler.resolvers.normal.fileSystem = compiler.inputFileSystem;
compiler.resolvers.context.fileSystem = compiler.inputFileSystem;
compiler.outputFileSystem = fs;
*/

compiler.watch({}, function (error, stats) {
  if (error) {
    console.log('Webpack callback error');
  } else {
    console.log('Webpack callback success');
  }
});
```

Thanks,
Dan

**Comment by DatenMetzgerX** [comment] 2016-10-30 07:32
I used MemoryFS but as i remember (see [here](https://github.com/DatenMetzgerX/webpack-angular-translate/blob/master/test/plugin.specs.js#L449)) MemoryFS does not support "watch" itself. Meaning, it does not trigger change events whenever a file has changed.... You have to invalidate the watch state yourself (what is sufficient for unit tests but will not for production)

**Comment by danbucholtz** [comment] 2016-10-31 20:01
@DatenMetzgerX, thanks for the info. Hmm. That is a bummer. So there is basically no way to use the in-memory FS and have the really fast incremental builds?

I have my code and assets already in memory due to external process before we get to webpack. It would be really awesome to use an incremental build without having to write to disk to trigger an update. Back to the drawing board 😄 .

Thanks,
Dan

**Comment by DatenMetzgerX** [comment] 2016-10-31 20:27
I think you should create a plugin that adds the files to the bundle... Normally you can use the emit phase to emit your assets. But you are than responsible for watching your dependencies yourself

**Comment by LukeSheard** [comment] 2017-12-30 23:21
Did anyone ever get a working demo of an in-memory FS replacement then?

**Comment by danbucholtz** [comment] 2018-01-02 21:21
@lukeapage,

We do in Ionic.

Here's the project:
https://github.com/ionic-team/ionic-app-scripts

Here's the overriding of the file system:
https://github.com/ionic-team/ionic-app-scripts/blob/master/src/webpack/ionic-environment-plugin.ts#L54-L55

Here is my implementation of the watching system.
https://github.com/ionic-team/ionic-app-scripts/blob/master/src/webpack/watch-memory-system.ts

Thanks,
Dan

**Comment by lukeapage** [comment] 2018-01-03 05:45
I think you meant to mention @lukesheard

**Comment by evilebottnawi** [comment] 2018-06-06 09:31
Closing due it is question. Feel free to open new issue if you have some problems with using `inputFileSystem` or `outputFileSystem`. Thanks!

**Closed by evilebottnawi** 2018-06-06 09:31 UTC
Labels: question
