### ISSUE TITLE
chunkhash changes if style is changed even if style is completely removed by ExtractTextPlugin

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#672] opened 2015-01-09 10:45 UTC
If we have a JS file that requires some style file, it's chunkhash depends on style file and it's correct.

But if we completely removing styles from the chunk with ExtractTextPlugin, chunkhash must not change on style changes anymore.

However, currently it changes and it means that client will redownload unchanged JS file on any style change because chunk file name containing chunkhash will change.

For extracted style file itself it's not a problem because we can use [contenthash] there. But there is no such an option for chunk file name.

**Comment by farism** [comment] 2015-09-17 23:56
+1

**Comment by ksespinola** [comment] 2015-09-23 20:01
+1

**Comment by lcxfs1991** [comment] 2016-01-16 09:06
same issue here. Has it been resolved?

**Comment by xiafandeshen** [comment] 2016-01-27 07:22
+1

**Comment by matthewdavidson** [comment] 2016-01-28 16:49
+1

**Comment by idiotstrike** [comment] 2016-02-14 00:22
+1

**Comment by juancarlosfarah** [comment] 2016-03-07 16:39
+1

**Comment by vinesone** [comment] 2016-03-07 22:26
+1

**Comment by griser** [comment] 2016-04-05 19:05
+1

**Comment by jackyon** [comment] 2016-04-08 08:11
+1

**Comment by quentin-berlemont** [comment] 2016-04-19 19:23
+1

**Comment by stephenzhao** [comment] 2016-04-25 07:49
＋1

**Comment by Poky85** [comment] 2016-06-09 21:03
+1

**Comment by huangshuwei** [comment] 2016-06-24 06:07
+1

**Comment by huangshuwei** [comment] 2016-06-24 06:38
same issue here. Has it been resolved?

**Comment by ngault** [comment] 2016-06-25 00:14
+1

**Comment by e-cloud** [comment] 2016-07-06 13:44
So, what's the difficulty of this issue? @sokra

**Comment by lcxfs1991** [comment] 2016-07-06 13:48
@sokra actually this can be resolved by using contenthash of extract-text-webpack-plugin.

**Comment by e-cloud** [comment] 2016-07-06 13:56
@lcxfs1991 , the point seems to be focused on the chunk hash changes rather than style file output. Once you change style, the js file name will change.

**Comment by ensecoz** [comment] 2016-07-10 08:06
+1

**Comment by ouqinglai** [comment] 2016-07-13 07:02
+1

**Comment by ouqinglai** [comment] 2016-07-13 07:14
use [webpack-md5-hash](https://github.com/erm0l0v/webpack-md5-hash) plugin can fix it

**Comment by gbhasha** [comment] 2016-08-08 12:37
+1

**Comment by khronic** [comment] 2016-09-27 16:09
+1

**Comment by anztrax** [comment] 2016-10-31 08:00
👍

**Comment by igorskuhar** [comment] 2016-12-30 18:07
+1

**Comment by fanyegong** [comment] 2017-01-09 11:31
+1

**Comment by NikitaEgorov** [comment] 2017-03-17 11:25
+1

**Comment by aleshchev** [comment] 2017-03-17 11:41
+1

**Comment by ovaldi** [comment] 2017-05-22 01:48
+1

**Comment by minaseem** [comment] 2017-05-23 08:33
+1

**Comment by tomassantos** [comment] 2017-06-07 20:55
+1

**Comment by alerd** [comment] 2017-06-29 08:59
include manifest in "names" array 
```
 new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor',' manifest']
    })
```

**Comment by aronwoost** [comment] 2017-10-24 13:47
+1

**Comment by behrens4ft** [comment] 2018-01-09 15:35
+1

**Comment by marapper** [comment] 2018-01-19 17:28
Is it still relevant? webpack 3.2+

Before 
- start.d395a0e3f23b51e053fc.6ff8406df2b1b3d2d64d863c42d52f60.css
- start.d395a0e3f23b51e053fc.js

After
- start.d395a0e3f23b51e053fc.691904d4bbec16a4b8cdcdc94b80e13b.css
- start.d395a0e3f23b51e053fc.js

```
//index.js
import './style.css';
console.log('!');

//style.css
.s {
  color: #FFF;
}
.s2 {
  color: #FFF;
}
//webpack.config.js
const webpack = require('webpack');

const ExtractTextPlugin = require('extract-text-webpack-plugin');

const path = require('path');
const DIST_PATH = path.join(__dirname, 'dist');
const extractCss = new ExtractTextPlugin('[name].[chunkhash].[contenthash].css');

module.exports = {
    devtool: 'source-map',
    entry: {
        start: './src/index.js',
    },
    output: {
        path: DIST_PATH,
        filename: '[name].[chunkhash].js',
    },
    resolve: {
        extensions: ['.js', '.jsx', '.json'],
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader?cacheDirectory',
            },
            {
                test: /\.jsx$/,
                loader: 'babel-loader?cacheDirectory',
            },
            {
                test: /\.css$/,
                loader: extractCss.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                sourceMap: true,
                                // cssnano
                                minimize: true,
                                importLoaders: 1,
                            },
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                sourceMap: true,
                            },
                        },
                    ],
                }),
            },
        ],
    },
    plugins: [
        extractCss,
    ],
};
```

**Comment by charlesswanson** [comment] 2018-04-15 18:41
+1 for fixing this in webpack as I have problems getting the workarounds to work.

The suggestion of using webpack-md5-hash introduces a new problem for me. Changing chunk1's .css no longer changes chunk1's js. However, my webpack config uses 

> runtimeChunk: 'single'

and the runtime.hash.js filename doesn't change even though its contents have changed to reference the chunk1.newhash.css filename. I think the problem is due to this webpack-md5-hash issue: https://github.com/erm0l0v/webpack-md5-hash/issues/7

**Comment by evilebottnawi** [comment] 2018-05-06 18:33
Please use `contenthash` instead `hash` and `chunkhash` (for `output.filename` and `output.chunkFilename`). Ref https://github.com/webpack/webpack.js.org/issues/2096. 

Also don't use `ETWP` for extract styles for `webpack@4` use instead https://github.com/webpack-contrib/mini-css-extract-plugin/. Also use `contenthash` for options https://github.com/webpack-contrib/mini-css-extract-plugin/#long-term-caching

Thanks everyone! Feel free create new issue if problem still exists even you use `contenthash`.

**Closed by evilebottnawi** 2018-05-06 18:33 UTC
Labels: bug, difficult
