### ISSUE TITLE
Cannot use 'chunkhash' in webpack dev server

### ISSUE THREAD

**Issue by yannispanousis** [webpack/webpack#2393] opened 2016-04-25 11:53 UTC
We are starting multiple entrypoints in the same webpack dev server and expect 'chunkhash' to be available but instead it causes this error:

```
ERROR in chunk app1 [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

ERROR in chunk app2 [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

ERROR in chunk app3 [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)

ERROR in chunk app4 [entry]
[name].[chunkhash].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```

As I understand this option should be available, as it is in a production build, so is it a bug?

For now we have made it use 'hash' in dev server and 'chunkhash' in production build.

Thanks!
Yannis

**Comment by sokra** [comment] 2016-04-29 16:10
Something prevents to from using chunkhash. i. e. HMR?

**Comment by jhnns** [comment] 2016-05-03 18:03
I can confirm that this problem is related to using `[chunkhash]` in conjunction with `webpack-dev-server --hot --inline`.

Since this is the expected behavior, I'm closing it.

**Closed by jhnns** 2016-05-03 18:03 UTC
Labels: question

**Comment by Zhastreaus** [comment] 2017-03-29 23:31
@jhnns 's answer solves the issue. This should be closed now.

**Comment by Getitdan** [comment] 2017-06-17 13:27
You shouldn't use [chunkhash] with webpack-dev-server. Also, remove `new webpack.NamedModulesPlugin()` from plugins in Webpack's config, or you'll get an error while separating the manifest to another file. "Don’t use [chunkhash] in development since this will increase compilation time.", from [docs](https://webpack.js.org/guides/caching/).

**Comment by zhenghuahou** [comment] 2017-11-01 04:00
I also encountered this side of the problem. There may be this reason：
http://tips.tutorialhorizon.com/2016/10/31/cannot-use-chunkhash-for-chunk-in-name-chunkhash-js-use-hash-instead/
