### ISSUE TITLE
(node:24724) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by 20170911** [webpack/webpack#9685] opened 2019-09-11 06:38 UTC
# Bug report
## (node:24724) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at FasterUglifyPlugin.apply (D:\work\web\React\...\node_modules\webpack-parallel-uglify-plugin\index.js:27:12)
    at webpack (D:\work\web\React\web-rtc-html\node_modules\webpack\lib\webpack.js:51:13)
    at Object.<anonymous> (D:\work\web\React\...\build\dev.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

### How do I eliminate Deprecation Warning when I use ```webpack-parallel-uglify-plugin```

**Other relevant information:**
webpack version:  4.39.3
Node.js version: v10.16.3
Operating System: windows 10
Additional tools:"webpack-parallel-uglify-plugin": "^1.1.2"

**Comment by sokra** [comment] 2019-09-11 07:29
Duplicate of https://github.com/gdborton/webpack-parallel-uglify-plugin/issues/58

**Closed by sokra** 2019-09-11 07:29 UTC
