### ISSUE TITLE
Total Different Output with 4.x and 5.22 Beta and the application stops working with libraryTarget:'system'

### ISSUE THREAD

**Issue by ajaybeniwal** [webpack/webpack#11148] opened 2020-07-09 15:56 UTC
# Bug report

I am trying to upgrade my project from 4.x to 5.22 beta and the application stops working with libraryTarget as 'system' , i am loading the module using System.JS dynamically and the exported methods are missing in the 5.X 

```
try {
				// eslint-disable-next-line no-undef
				const fetchedModule = await window.System.import(modulePath);
				setModule(fetchedModule);
			} catch (moduleError) {
				console.log(moduleError);
				setError(true);
			}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/ajaybeniwal/WebpackFailError

**What is the expected behavior?**
The application should work without any issues after the upgrade

**Other relevant information:**
webpack version:  "webpack": "5.0.0-beta.22",
Node.js version: 
Operating System: Mac
<img width="933" alt="Screenshot 2020-07-09 at 11 30 03 PM" src="https://user-images.githubusercontent.com/658004/87062514-b5f9da00-c23f-11ea-8f97-f0024168c937.png">
<img width="970" alt="Screenshot 2020-07-09 at 11 29 46 PM" src="https://user-images.githubusercontent.com/658004/87062522-b7c39d80-c23f-11ea-91d7-06485bdfc6f5.png">

Additional tools:

**Comment by sokra** [comment] 2020-07-09 17:03
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ScriptedAlchemy** [comment] 2020-07-09 22:20
We are using system output targets with module federation and rollup. I can revalidate if there are any problems with the latest beta and report back

**Comment by ajaybeniwal** [comment] 2020-07-10 05:23
One Update i notice is this issue is coming only when i run my project locally with webpack dev server , when i build the JS file and serve the production build the error is gone
"webpack-dev-server": "3.11.0",

```
/* eslint-disable no-undef */
const merge = require('webpack-merge');
const common = require('./webpack.common.config.js');
const { NoEmitOnErrorsPlugin } = require('webpack');

module.exports = merge(common, {
	mode: 'development',
	devtool: 'inline-source-map',
	devServer: {
		contentBase: './dist',
		hot: true,
		port: 4010,
		headers: {
			'Access-Control-Allow-Origin': '*',
		},
		disableHostCheck: true,
	},
	plugins: [new NoEmitOnErrorsPlugin()],
});
```

**Comment by evilebottnawi** [comment] 2020-07-10 11:19
@ajaybeniwal Please provide reproducible test repo

**Comment by ajaybeniwal** [comment] 2020-07-11 05:46
Let me try to create reproducible test repo

**Comment by ajaybeniwal** [comment] 2020-07-12 08:00
HI @sokra  @evilebottnawi  @ScriptedAlchemy  i have updated the repository to show simple failing cases with SystemJS build with webpack dev server can u please have a look since i am not able to upgrade webpack in my project because of this issue
https://github.com/ajaybeniwal/WebpackFailError

**Comment by evilebottnawi** [comment] 2020-07-13 12:24
Duplicate of https://github.com/webpack/webpack-dev-server/issues/2484

**Comment by evilebottnawi** [comment] 2020-07-13 12:25
Let's close here, not related to webpack directly, anyway feel free to send a fix

**Closed by evilebottnawi** 2020-07-13 12:25 UTC
