### ISSUE TITLE
Documentation should be explicit about the default configs for development and production modes

### ISSUE THREAD

**Issue by Maximaximum** [webpack/webpack#7123] opened 2018-04-25 17:51 UTC
**Do you want to request a *feature* or report a *bug*?**
*documentation*

**What is the current behavior?**
I've spent quite some time trying to figure out what is the exact configuration that is used when `mode` is set to `production`, but haven't found a clear answer yet. 

I need to tweak a single config option (`collapse_vars`) for the `UglifyJsPlugin` and, as far as I see, there is no way to do it, except for setting `mode` to `none` and explicitly re-defining the whole production config, having the only difference from the default `production` config that `UglifyJsPlugin.uglifyOptions.collapse_vars = false`. But how do I know the default production config? I can't find it in the documentation, so I'm trying to find this out by trial and errors, which is totally counter-productive.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It would be great if on this page https://webpack.js.org/concepts/mode/, instead of some weird diffs there were full and exact configs that are equivalent to setting `mode` to `development` or `production`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
The user should be able to easily copy-and-paste the default config and tweak it to their needs.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by Maximaximum** [comment] 2018-04-25 17:53
Just in case someone is interested, why do I need to set `collapse_vars` to false, is because of this bug: https://github.com/mishoo/UglifyJS2/issues/3096 which has been fixed but not yet released.

**Comment by kzc** [comment] 2018-04-25 20:46
The webpack config is not exactly obvious...

https://github.com/webpack/webpack/issues/6567#issuecomment-368500509

and that example did not detect production mode correctly. You need to do this:

https://github.com/webpack/webpack/issues/6460#issuecomment-364286147

**Comment by montogeek** [comment] 2018-04-25 21:40
It is in the docs https://webpack.js.org/concepts/mode/#usage

**Comment by montogeek** [comment] 2018-04-25 21:40
Also, report documentation issue to https://github.com/webpack/webpack.js.org

**Comment by Maximaximum** [comment] 2018-04-26 08:10
> It is in the docs https://webpack.js.org/concepts/mode/#usage

No, it is not - that's why I've created this issue. See:

> It would be great if on this page https://webpack.js.org/concepts/mode/, instead of some weird diffs there were **full and exact configs** that are equivalent to setting mode to development or production.

On https://webpack.js.org/concepts/mode/#usage page I don't see, for example, the config object being passed to `UglifyJsPlugin` constructor

**Comment by Maximaximum** [comment] 2018-04-26 08:13
@kzc well, the documentation lacks clear information about the `optimization.minimizer` option as well - that's why I was unable to find it :disappointed:

**Comment by Maximaximum** [comment] 2018-04-26 08:14
@montogeek copied this issue to https://github.com/webpack/webpack.js.org/issues/2080

**Comment by montogeek** [comment] 2018-04-26 08:42
We can't duplicate documentation everywhere, UglifyJsPlugin options are on its respective page: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

**Comment by montogeek** [comment] 2018-04-26 08:43
Duplicate of https://github.com/webpack/webpack.js.org/issues/2080

**Closed by montogeek** 2018-04-26 08:42 UTC

**Comment by Maximaximum** [comment] 2018-04-26 09:54
@montogeek well, I can't find any mentions of `optimization.minimizer` option on https://webpack.js.org/plugins/uglifyjs-webpack-plugin/ page anyway

**Comment by montogeek** [comment] 2018-04-26 09:56
@Maximaximum It shouldn't be there, it is a different option, you can use any plugin as `minimizer` option, I don't know if there is more 🤔

**Comment by montogeek** [comment] 2018-04-26 09:57
@Maximaximum I just merged https://github.com/webpack/webpack.js.org/pull/2053, it is already live https://webpack.js.org/configuration/optimization/

**Comment by Maximaximum** [comment] 2018-04-26 10:02
@montogeek Yeah, thanks a lot! :smiley:  Now it's clear about `optimization.minimizer`.

It would be great to resolve https://github.com/webpack/webpack.js.org/issues/2080 as well. :smiley:
