### ISSUE TITLE
ProfilingPlugin output file crashes Chrome devtools

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#7689] opened 2018-07-09 16:46 UTC
# Bug report

**What is the current behavior?**

After running ProfilingPlugin and dragging the events.json file into Chrome devtools Performance tab, devtools crashes and closes after "Processing profile..." This seems to happen on larger builds where the JSON file is 116 MiB, but not on smaller builds where it is < 70 MiB.

I'm not sure if this is a bug in Chrome devtools or the webpack plugin (or both) so I figured I'd start here.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Enable ProfilingPlugin on a large build and run webpack. In my scenario, the generated file is 116.6 MiB.
2. Drag events.json into Chrome devtools Performance tab.
3. Wait for the file to be loaded and processed.
4. Devtools closes without showing the results.

**What is the expected behavior?**

Devtools Performance tab shows flame charts instead of closing.

**Other relevant information:**
webpack version:  4.15.1
Node.js version: 8.9.1
Operating System: macOS 10.13.5
Additional tools: Chrome 67.0.3396.99 (Official Build) (64-bit)

cc @samccone (let me know if you want my events.json file and I can send you one privately)

**Comment by samccone** [comment] 2018-07-12 14:34
Please send me the file samccone at google.com

**Comment by samccone** [comment] 2018-07-20 00:00
@sokra can you close this, I am following up with this bug internally, thanks!

**Comment by lencioni** [comment] 2018-07-20 00:02
Thanks @samccone!

**Closed** 2018-07-20 00:02 UTC

**Comment by diagramatics** [comment] 2018-08-16 02:04
@samccone Is there an issue link where we can track this as well?

**Comment by kachkaev** [comment] 2019-01-18 17:29
Has this been resolved? I'm trying to drag a 256MB `events.json` file into Chrome Dev Tools and am seeing the same issue as reported originally. I understand that the size of my file is somewhat insane, but am still curious if there's any solution to the issue. E.g. it'd be helpful to know how to easily visualize just a chunk of this file etc.

Webpack performance issues are mostly topical for bulky unoptimised apps and ironically it's impossible debug the output due to its enormous size 😅

**Comment by issacgerges** [comment] 2019-01-30 21:31
I was able to open my profiling output by running Chromium (in my case) with increased memory

```
open /Applications/Chromium.app  --args --js-flags="--max_old_space_size=8192"
```

**Comment by sodiumjoe** [comment] 2019-03-22 18:24
Was there an official solution for this? even with the args and `--no-sandbox`, I have a 600M file 😬 that crashes the dev tools.

**Comment by villesau** [comment] 2019-05-10 14:49
@samccone I think this is the same issue: https://github.com/webpack/webpack/issues/9108

In my case dev tools does not crash, but profiler just resets and does not show the result.

**Comment by robatwilliams** [comment] 2020-09-16 09:15
I used the `chrome://tracing` tool to open and analyse a 186MB file covering a 8.5 minute build, to avoid this issue. The mouse navigation didn't work well at this scale so used the keyboard shortcuts. Yes it's big/slow but that's why I want to profile it.

> Webpack performance issues are mostly topical for bulky unoptimised apps and ironically it's impossible debug the output due to its enormous size 😅
Indeed.

**Comment by cseas** [comment] 2023-03-03 06:05
This is still an issue but doesn't look like webpack team can do much about it. Is there a Chromium bug tracker for this?
I have a 640MB `events.json` generated by webpack that doesn't load in Chrome. Sometimes it crashes DevTools, sometimes it's stuck at "Loading profile...".

**Comment by alexander-akait** [comment] 2023-03-07 17:10
@cseas Can you create reproducible test repo?

**Comment by TheLarkInn** [comment] 2023-03-07 17:20
I was on the Edge team for some time and I'm happy to forward a events.json file if you have one somewhere to at least report the bug. @cseas if you can link one I'll do what I can.

**Comment by seanlaff** [comment] 2023-03-28 13:58
I used some jq to find the most common lines 
```bash
cat events.json |jq 'group_by(.name) | map({name: .[0].name, len: . | length}) | sort_by(.len)'
```
and then excluded them to get my events.json down from ~700mb to ~50mb
```bash
cat events.json | grep -Ev 'InnerGraphPlugin|SideEffectsFlagPlugin|CompatibilityPlugin|HarmonyImportDependencyParserPlugin' > events2.json
```
I learned that a good chunk of time was spent in minimization, but other than that it was just thousands of `NormalModuleFactory` spans, so I didn't learn too much in the end.

**Comment by beta3-z** [comment] 2024-01-23 18:15
You can use https://ui.perfetto.dev/ for opening a big events.json. Size was 800+MB in my case. 

P.S. chrome://trace recommends perfetto now :)

**Comment by mrdulin** [comment] 2024-06-20 08:07
Same issue. My `events.json` file size is 499MB, when I drag and drop to the Edge Browser Performance panel, got below error:

![image](https://github.com/webpack/webpack/assets/17866683/c9ec0f46-d5a0-4204-a3e1-9e46553de74e)

@robatwilliams 's way works for large size file. Instead of `chrome://tracing`, it's `edge://tracing` for Edge Browser.

![image](https://github.com/webpack/webpack/assets/17866683/2d6c98ad-f34b-435b-b348-068fa1c08981)
