### ISSUE TITLE
Module federation not working with web workers

### ISSUE THREAD

**Issue by grzesiek-ds** [webpack/webpack#16633] opened 2023-01-12 17:57 UTC
# Bug report

**What is the current behavior?**
Currently it is not possible to consume federated module inside of web worker.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to import federated module inside of web worker script.
Theres a repo with reproduced issue.
https://github.com/grzesiek-ds/webpack-mf-workers 

**What is the expected behavior?**
It should be possible to import federated module inside of web worker script.

**Other relevant information:**
webpack version: `5.74.0` (also applies to `5.75.0`)

It seems that this might be the same issue as in #16173, although I'm not sure.
I've tried to include [mentioned plugin](https://github.com/webpack/webpack/issues/16173#issuecomment-1226431857) in host application webpack config, but it gave no effect.

@edusperoni @ScriptedAlchemy if You have any additional information, or possible fix/workaround, please share.

![image](https://user-images.githubusercontent.com/95348943/212143083-9caf4c08-98e3-40e2-82c8-0f6e418b3908.png)

**Comment by alexander-akait** [comment] 2023-03-18 20:37
Sorry for delay, please avoid duplicate of issues, there is an issue https://github.com/webpack/webpack/issues/16173, as workaround you can use multi compiler mode right now, but yes, it is a bug close in favor https://github.com/webpack/webpack/issues/16173, thank you

**Closed by alexander-akait** 2023-03-18 20:37 UTC

**Comment by grzesiek-ds** [comment] 2023-04-03 21:59
@alexander-akait Could You elaborate on that multi compiler mode? Is it about returning array of configs instead of single config, like in this example?
https://github.com/webpack/webpack/blob/main/examples/multi-compiler/webpack.config.js

As I understand, it would be expected to have separate config for main bundle and each worker script? How could I "inject" these worker bundles into main bundle? I could not find any examples of that.

**Comment by alexander-akait** [comment] 2023-04-03 22:15
Yeah, that is corrent, just set `target: "webworker"`, give `name` for each compiler (i.e. item in the array) and set `dependcies: ["worker"]` to the main compiler, so you loader will be compiled firstly

**Comment by gasymov-rustam-abra** [comment] 2023-07-23 07:02
hi, did you success launch your app with worker and application?
