### ISSUE TITLE
web pack source map not working for some devtool options.

### ISSUE THREAD

**Issue by SemihGk** [webpack/webpack#5491] opened 2017-08-10 21:16 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Sourcemap is not working for some devtool options. Tested options:
**eval:** working
**cheap-eval-source-map:** working
**cheap-source-map:** not working
**cheap-module-eval-source-map:** working
**cheap-module-source-map:** not working
**source-map:** not working
**inline-source-map:** not working
**hidden-source-map:** not working
**nosources-source-map:** not working

**If the current behavior is a bug, please provide the steps to reproduce.**

I reproduced the bug in this repo: https://github.com/SemihGk/waka-player
`npm install -> npm run prod -> watch console messages in localhost:3000`

It's really a weird issue. I am not sure any plugin causes this error. I do not think so. Just in case, you may check that in the repo. It is very basic sample repo and just used a couple webpack plugins such as html-webpack-plugin and copy-webpack-plugin. You can find those plugins' versions in package.json file. I suspect the compatibility between webpack and babel-loader. 

**What is the expected behavior?**
source map should work in all devtool options.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's bug.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

"webpack": "^3.5.1",
Mac OS: 10.12.6
node: 8.2.1
Tested on Chrome 60, Mozilla 54, Safari 10.1

**Comment by NikhilVerma** [comment] 2017-08-17 15:58
I am having the same problem right now.

**Webpack:** ^2.2.0
**Chrome:** 60.0.3112.101 (Official Build) (64-bit)
**OSX:** 10.12.6

**Comment by petermikitsh** [comment] 2017-08-19 18:53
Also experiencing this issue:

Webpack: 3.3.0
Chrome: Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by petermikitsh** [comment] 2017-08-21 15:27
I've explored this further and my sourcemaps are working as expected in Firefox. Just not in Chrome.

**Comment by MACSkeptic** [comment] 2017-08-28 13:39
is that a similar issue to this? https://github.com/webpack/webpack/issues/5569#issuecomment-325262489

**Comment by SemihGk** [comment] 2017-08-29 00:43
@MACSkeptic . Not really. I did not even specify UglifyJsPlugin in my config. Sourcemap is just not working properly when multiple entries are set to webpack. @petermikitsh , I still have the issue in Chrome, Firefox and Safari. That's interesting. Could you provide a sample repo? Maybe, I can test it as well and I can see that is it the same issue that I have?

**Comment by yincu** [comment] 2017-08-30 01:16
#5569  provide a very simple sample repo.  You can see it in it. 
I'm the issuer.   It seems that the `webpack` owner has no time to deal with the bug  or he thinks it's  NOT a  bug. He may think we  just use it in a wrong way , however it's obviouse that the bug is not reasonable.  Now  I feel frustrated.

**Comment by yincu** [comment] 2017-08-30 01:56
I tested your project.  It seemed no bug. 
Browser: Chrome version: 59.0.3071.86
Operating system: windows 7 64bit
![image](https://user-images.githubusercontent.com/31179226/29851744-810079b2-8d68-11e7-8931-426d3ded4c81.png)

**Comment by yincu** [comment] 2017-08-30 01:58
And I updated the chrome to the newest version (60.0.3112.113). It still worked fine.

**Comment by SemihGk** [comment] 2017-08-30 02:09
Hey @yincu . It is already marked as an important bug. You cannot expect them to fix the bug right away as there are tons of bugs are on the list. 

As I described in my first message, watch console.logs carefully. Otherwise, sourcemaps files are already created. 

I just cloned my repo and did run it again. It is still a clear bug as you may see in the screenshot. How about your console? 

<img width="1338" alt="screen shot 2017-08-29 at 10 04 59 pm" src="https://user-images.githubusercontent.com/5814582/29852164-9706ddc6-8d06-11e7-96a0-e7e77c88e847.png">

**Comment by yincu** [comment] 2017-08-30 02:49
I get what you said.  I reproduced the bug. However,  it seems  it may be a browser bug of chrome or  it's NOT a bug.  
When you browser  http://localhost:3000/  page without  a devtool window displayed. You'll get the right source map.  Or if you get what you got in your above post picture.  You can close the devtool window of chrome and  open it again. Boom!  You get what you want.  

The source map files will not be get from the server unless you reopen the devtool window.  These files are not expected to be acccesed  by users when browsering the pages.  They will not be downloaded along with the js or css files. They will only be downloaded when the devtool window is reopend.
These files will only be downloaded and parsed when the devtool window is reopened.

**Comment by SemihGk** [comment] 2017-08-30 13:40
It might be a browser bug, but it happens in other 3 browsers as well. Plus, it works fine with some other sourcemap types. Besides, it works as well if I assign only one entry to be bundled. I am not an expert and I cannot speak in a certain way, but it seems this bug is more related to webpack.

**Comment by yincu** [comment] 2017-08-31 01:41
You could test this way with other sourcemap types to see if it works the same.
The test with the configuration `devtool: 'source-map'` suggests that  it has nothing to do with webpack.

Source maps are used for debugging.  The behavior of Chrome is reasonable .

**Comment by JunyuanZheng** [comment] 2017-10-05 23:31
Got the same issue, `eval` config works.

**Comment by Prestapro** [comment] 2017-10-25 12:39
Also this problem, auto source map not work in chrome canary with webpack.

**Comment by magnusart** [comment] 2017-11-23 14:58
Hi is there a workaround for this? For me `devtool: 'inline-source-map'` works but `devtool: 'source-map'` does not. It produces an nearly empty source map.

**Comment by TomYang1993** [comment] 2017-11-28 17:04
I have noticed your sample app works now
<img width="1023" alt="screen shot 2017-11-28 at 11 56 16 am" src="https://user-images.githubusercontent.com/20257736/33332787-35317c04-d433-11e7-97d0-248d19af651b.png">
it shows exactly the seperate modules, it seems you have one file per entry point except app.js is importing from shaka-player
<img width="1022" alt="screen shot 2017-11-28 at 12 00 46 pm" src="https://user-images.githubusercontent.com/20257736/33333025-cf50d83e-d433-11e7-9063-4ba70ec59a16.png">
And it is working with multiple sets
However, mine still works weird, I have two major entry points, and each one requires/imports a lot of file, I don't know if it's the size or something else causing the problem
<img width="1022" alt="screen shot 2017-11-28 at 11 55 32 am" src="https://user-images.githubusercontent.com/20257736/33333128-1b8b1de0-d434-11e7-8a40-060983947b36.png">

Webpack 3.8.1
angularJS 1.6.5
babel 7.1.2

**Comment by studio174** [comment] 2017-12-11 19:26
@SemihGk I had a similar issue and was able to resolve this by reading through https://github.com/webpack/webpack/issues/5569#issuecomment-325262489 and changing the -d (dev flag) to ```-p```

```
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js -p",
    "clean-js": "rm -rf ./dist/js",
    "quality": "eslint",
    "build": "webpack",
    "build-prod": "webpack --config webpack-production.config.js -p",
    "test": "node scripts/test.js --env=jsdom"
  },
```

**Comment by devssh** [comment] 2018-04-04 08:52
Facing the same problem, it is uglifying when not told to and not having the devtool source map in cheap-source-map, source-map or any devtool option.

**Comment by devssh** [comment] 2018-04-04 10:34
Update: Just fixed it using mode in webpack 4

**Comment by mbonaci** [comment] 2018-04-26 13:05
@devssh so you get sourcemaps even with `devtool: "source-map"`, or what?
Can you post your webpack config?

**Comment by devssh** [comment] 2018-04-26 21:43
Yes Here is my baseConfig 

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: ['./client/src/index.js'],
  output: {
    path: path.join(__dirname, '../server/public'),
    filename: 'static/bundle.js',
    publicPath: '/'
  },
  plugins: [
    new webpack.DefinePlugin({
      'HOST_MACHINE_URL': JSON.stringify(process.env.HOST_URL)
    }),
    new webpack.NoEmitOnErrorsPlugin()
  ],
  module: {
    rules: [
      {
        test: /.html$/,
        loaders: "html-loader"
      },
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /\.(scss|css)$/,
        use: ["style-loader", "css-loader", "sass-loader"]
      },
      {
        test: /\.(eot|ttf|woff2|woff|jpg|png|svg)(\?[a-z0-9]+)?$/,
        use: [{
          loader:'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'static/',    // where the fonts will go
            publicPath: '/'       // override the default path
          }
        }]
      }
    ],
  }
};

```

Now in the dev server 
const baseConfig = require('./webpack.base.conf');

What was added to fix the issue was 
```
baseConfig.mode = 'development';
```

**Comment by cloakedninjas** [comment] 2018-06-27 15:34
For some reason, not sure why, we've run into this bug too, will migrating to Webpack 4 fix this ?

**Comment by nelsonomuto** [comment] 2018-07-05 21:13
Same thing here, can't get any sourcemaps other than `*-eval-*` sourcemaps to work

**Comment by matthiasdailey-ccri** [comment] 2018-09-24 17:59
If the script is within an **iframe**, you have to enable "Search in anonymous and content scripts" in Chrome.

**Comment by Imad-MACHI** [comment] 2020-07-07 18:43
I had the same probleme in chrome, but it worked in firefox

**Comment by evilebottnawi** [comment] 2020-07-07 18:58
Fixed in webpack@4, Firefox has some problems with source maps, here more information https://github.com/webpack/webpack/issues/1194 (fixed in nightly)

I want to close this issue, because it is fixed, but if you faced with the problem again, feel free to open a new issue with reproducible test repo, we have many tests on source maps

**Closed by evilebottnawi** 2020-07-07 18:58 UTC
Labels: P3: Important, bug

**Comment by tomsaleeba** [comment] 2021-05-03 21:01
Running on `webpack==4.41.2`, the fix for me was setting `sourceMap: true` for the TerserPlugin, as [the docs](https://webpack.js.org/configuration/optimization/#optimizationminimizer) highlight:

>         sourceMap: true, // Must be set to true if using source-maps in production

This change meant I started to get source maps for all the available `devtool` values, not just the `eval*` ones.

**Comment by austinhaws** [comment] 2021-05-10 21:39
Webpack 5 loses support for `sourceMap: true`
[Terser Plugin 5.0.0 release Notes](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.0.0)
What is the equivalent option for webpack5?

**Comment by oopses** [comment] 2024-07-01 06:46
> Webpack 5 loses support for `sourceMap: true` [Terser Plugin 5.0.0 release Notes](https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.0.0) What is the equivalent option for webpack5?

Webpack 5 devtools hidden-source-map not generate sourcemap
