### ISSUE TITLE
Vendor content changes when app code changes

### ISSUE THREAD

**Issue by fate-lovely** [webpack/webpack#1597] opened 2015-11-07 04:32 UTC
When I change app code, vendors.js will have a slight change as following image shows, this prevents me from doing long term caching.
It seems that chunk 0 refers to my app chunk, but it's unnecessary to have this in my vendors file.
How am I supposed to do to keep my vendors content same when I just change my app code?
![image](https://cloud.githubusercontent.com/assets/4210829/11013456/79624da8-8549-11e5-969c-30ae58083f9d.png)

**Comment by vlkosinov** [comment] 2015-11-09 15:47
See https://github.com/webpack/webpack/issues/1315#issuecomment-155100976

**Comment by bebraw** [comment] 2015-11-14 12:26
I'm closing this as a duplicate of #1315.

**Closed by bebraw** 2015-11-14 12:26 UTC
