### ISSUE TITLE
Webpack doesn't split third party library code between bundles

### ISSUE THREAD

**Issue by LeeKatz1** [webpack/webpack#11680] opened 2020-10-14 07:46 UTC
# Bug report

**What is the current behavior?**
The code splitting, using Webpack with Loadable plugin, doesn’t split the code to the correct bundle. It happens when both bundles use the same third party library, but each one imports a different code from that library. The actual result is that the main bundle includes both of the imported codes from the third party library.

For example, using React: 

This is the entry point of webpack: index.js
```
import { Component1 } from 'third-party-components-library';
import * as React from 'react';
import loadable from '@loadable/component';

export const MainComponent = () => {
  const LoadableComponent = loadable(() => import('./LoadableComponent'));
  return (
    <Component1>
      <LoadableComponent />
    </Component1>
  );
};
```
This is the loadable component: LoadableComponent.js 
```
import { Component2 } from 'third-party-components-library';
import * as React from 'react';

const LoadableComponent = () => {
  return (
    <Component2/>
  );
};
export default LoadableComponent;
```

Two separated bundles are created:  First for index.js, which is the webpack entry point,  and the second for LoadableComponent.js. The first one includes both codes for Component1 and Component2 from ‘third-party-components-library’. The second one doesn’t include any code from ‘third-party-components-library’. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the loadable-components library via its webpack plugin:
https://loadable-components.com/docs/getting-started/
https://loadable-components.com/docs/api-loadable-webpack-plugin/
The main bundle, which is the bundle that is created from the webpack entrypoint, should import a component from a third party library. The main bundle should include a loadable-component. The loadable-component should import a different component from the same third party library.

**What is the expected behavior?**
The expected behavior is that webpack will split the code between the main bundle and the loadable bundle in a way that each bundle includes only the relevant code from the third party library.
In the context of the previous example:
The main bundle (for index.js entry point) should include only the code for Component1 from 'third-party-components-library' and the second bundle (for LoadableComponent.js) should include only the code for Component2 from 'third-party-components-library'.

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 12.18.0
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment] 2020-10-14 11:06
Please open an issue in `@loadable/webpack-plugin`, if you need help please provide reproducible test repo

**Comment by sokra** [comment] 2020-10-14 17:43
That's a webpack thing, but we don't support that (yet). And probably won't support it in near future.

It's only working if each piece is in an separate file and the main file reexports them and is flagged as side effect free.

**Comment by ScriptedAlchemy** [comment] 2020-10-15 21:18
if theres a static import, then webpack needs to provide it upfront as part of the main bundle since some pages might need it.

**Comment by joshjg** [comment] 2020-11-17 18:59
@sokra - I believe I'm having a similar issue after upgrading from 4.x to 5.x - it worked as expected in 4.x. As a result the main bundle size of our app will increase dramatically in 5.x.

> It's only working if each piece is in an separate file and the main file reexports them and is flagged as side effect free.

The 3rd party package includes `"sideEffects": "false"` and the components are all in separate files. Maybe I'm misunderstanding your comment?

**Comment by joshjg** [comment] 2021-05-10 19:50
@sokra Any idea what change from v4-v5 could cause this? This is blocking my team from upgrading to v5.

**Comment by alexander-akait** [comment] 2021-05-11 13:38
Can you show `third-party-package-b` export?

**Comment by ScriptedAlchemy** [comment] 2021-06-02 00:19
Bump - we still should address this it not already

**Comment by vankop** [comment] 2021-09-15 21:06
Should work with `webpack@5`. Feel free to report new issue with reproducible repo.

take a look into `runtime` feature

**Comment by alexander-akait** [comment] 2021-09-16 11:24
Still valid

**Comment by vankop** [comment] 2021-09-16 11:27
@alexander-akait I actually don't understand what is an issue? original issue fixed in webpack@5

**Comment by alexander-akait** [comment] 2021-09-16 11:29
@vankop Can you provide link on PR?

**Comment by vankop** [comment] 2021-09-16 11:59
@alexander-akait did not find MR. here is demo https://github.com/vankop/webpack-runtime/tree/main/dist 2 separate chunks in output with different tree shaking

**Comment by alexander-akait** [comment] 2021-09-16 12:38
@vankop Try to use original code from the issue

**Comment by alexander-akait** [comment] 2021-09-16 13:00
Related https://github.com/webpack/webpack/issues/7782, small example https://github.com/webpack/webpack/issues/7782#issuecomment-407694117 and bundle, we can move this code to shared chunk, but keep them both in each chunk

**Comment by vankop** [comment] 2021-09-16 13:21
from issue text:
```
What is the expected behavior?
The expected behavior is that webpack will split the code between the main bundle and the loadable bundle in a way that each bundle includes only the relevant code from the third party library.
```
As I said this is possible within different runtimes

If you have one runtime, webpack can not do this, because one module can be executed once

**Comment by alexander-akait** [comment] 2021-09-16 13:34
I don't see how runtime fix this problem

**Closed** 2023-04-23 19:56 UTC
Labels: enhancement, webpack-5

**Comment by joshjg** [comment] 2025-05-13 19:49
@alexander-akait Was there a specific change that resolved this?

**Comment by alexander-akait** [comment] 2025-05-14 09:11
@joshjg No, just outdated, because no activity, what is the problem?

**Comment by joshjg** [comment] 2025-05-14 16:15
@alexander-akait Got it. My issue is closer to #7782 which was linked to this issue.

**Comment by alexander-akait** [comment] 2025-05-16 12:54
@joshjg Can you provide reproducible test repo with steps, I will look
