### ISSUE TITLE
Webpack with minimize : true may inflate bundle by inlining large binary strings multiple times

### ISSUE THREAD

**Issue by IvanZatravkin** [webpack/webpack#18452] opened 2024-06-03 19:36 UTC
# Bug report

**What is the current behavior?**
When using minimize: true webpack inlines some variables.
In our case it inlines WASM bytecode, which is 15 MB string.
It does so 2 times, which inflates bundles size significantly.

This may affect other projects which use packages with WASM as base64 encoded strings.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/ArepQuantori/test-ketcher-minify
Here is a minimal reproducible case. When building with minimize: true bundle size is over 30 MB. By either omitting minimization or using other minimizer bundle size can be made smaller by 15 MB.

**What is the expected behavior?**

Before inlining variables minimizer should check their length and opt-out if inlining inflates bundle significantly. 

**Other relevant information:**
webpack version:  5.91.0
Node.js version: v18.16.0
Operating System: Linux
Additional tools: -

**Comment by alexander-akait** [comment] 2024-06-04 15:58
Something wrong with terser, not webpack

**Comment by alexander-akait** [comment] 2024-06-04 16:17
Yeah, by default we use:
```js
optimization: {
       minimize: true,
       minimizer: [new TerserPlugin({
         terserOptions: {
           compress: {passes: 2, ecma: 2015},
         }
       })],
     },
```

But when you have `{}` we have such configuration:
```
optimization: {
       minimize: true,
       minimizer: [new TerserPlugin({
         terserOptions: {
           compress: {passes: 2, ecma: 2015},
         }
       })],
     },
```

Different in `passes`, and looks like `terser` has a bug somewhere, as workaround you can use `passes: 1` as I provided above, sorry we can't fix it here, please open an issue in the `terser`, feel free to feedback here

/cc @fabiosantoscode maybe do you have time a look, I closed it because it is not fixable here, but I agree, we should not duplicate string here

**Closed by alexander-akait** 2024-06-04 16:17 UTC

**Comment by alexander-akait** [comment] 2024-06-04 16:23
@fabiosantoscode @IvanZatravkin Example code to reproduce it (for an issue):
```js
function createBase64WorkerFactory(base64, sourcemapArg, enableUnicodeArg) {
    var url;
    return function WorkerFactory(options) {
        url = url || createURL(base64, sourcemapArg, enableUnicodeArg);
        return new Worker(url, options);
    };
}

var WorkerFactory = createBase64WorkerFactory('VERY_VERY_VERY_VERY_VERY_STRING', null, false);
```

And replace `VERY_VERY_VERY_VERY_VERY_STRING` on any very long string (for example 32mb) and you will see

**Comment by fabiosantoscode** [comment] 2024-06-04 17:05
@alexander-akait what options did you use to reproduce?

**Comment by alexander-akait** [comment] 2024-06-04 17:27
@fabiosantoscode `compress: {passes: 1, ecma: 2015}` (no problems) and `compress: {passes: 2, ecma: 2015}`` is enough to reproduce

**Comment by fabiosantoscode** [comment] 2024-06-04 18:08
I don't see anything with these options. Both cases result in a file around 32mb. What's happening on your end? Does Terser crash, or does the string get duplicated?

**Comment by alexander-akait** [comment] 2024-06-05 15:21
@fabiosantoscode 

> does the string get duplicated

Yeah, some arguments inlined, but some keeps, but because it is string, it is duplicated

**Comment by alexander-akait** [comment] 2024-06-05 15:22
So size multiple 2

**Comment by fabiosantoscode** [comment] 2024-06-05 21:49
A workaround would be to set `passes: 3`, and I'll release this fix tomorrow.
