### ISSUE TITLE
Support node Conditional Exports 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [webpack/webpack#10555] opened 2020-03-14 14:50 UTC
## Feature request

**What is the expected behavior?**

[resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields) should support [Conditional Exports](https://nodejs.org/api/esm.html#esm_conditional_exports) in nodejs

```json
  "exports": {
    ".": {
      "require": "./dist/my-lib.cjs",
      "import": "./dist/my-lib.mjs"
    }
  }
```

**Comment by sokra** [comment] 2020-03-14 16:48
Yep, we will add support for this in webpack 5.

**Comment by evilebottnawi** [comment] 2020-03-17 17:01
Duplicate of #9509

**Closed by evilebottnawi** 2020-03-17 17:01 UTC
