### ISSUE TITLE
Documentation: possible typo in command in tutorial.

### ISSUE THREAD

**Issue by b-d-m-p** [webpack/webpack#1452] opened 2015-09-16 11:57 UTC
In following the [tutorial](http://webpack.github.io/docs/tutorials/getting-started/), this line:
`webpack ./entry.js bundle.js --module-bind "css=style!css"`
... gives me this error...
`zsh: event not found: css`

This [https://github.com/webpack/webpack/issues/242] says that it need `\`, which works for me, so the command would be:
`webpack ./entry.js bundle.js --module-bind "css=style\!css"`

Hope that helps.

**Comment by shama** [comment] 2015-09-21 23:23
Closing as a duplicate of https://github.com/webpack/docs/pull/42

**Closed by shama** 2015-09-21 23:23 UTC
