### ISSUE TITLE
ReferenceError: Cannot access '<something>' before initialization

### ISSUE THREAD

**Issue by wesselvdv** [webpack/webpack#12724] opened 2021-02-19 20:27 UTC
# Bug report

**What is the current behavior?**

I am not quite sure how to describe what the situation actually is, but the bottom line is that in some rare cases importing a module in the wrong order causes `ReferenceError: Cannot access '<something>' before initialization`.

Enabling both `innerGraph` and `usedExports` seems to allow one to work around the problem.

**If the current behavior is a bug, please provide the steps to reproduce.**

See the reproduction repository: https://github.com/wesselvdv/used-before-initialization

Reproduction steps:

1. yarn build
2. node dist/index

**What is the expected behavior?**

That importing in whatever order always works regardless of optimization strategies enabled or disabled.

**Other relevant information:**
webpack version:  5.23.0
Node.js version:  14.10.1
Operating System: Arch Linux
Additional tools:

**Comment by alexander-akait** [comment] 2021-02-20 13:07
Much like a circular dependency

**Comment by mikearnaldi** [comment] 2021-02-20 13:23
@alexander-akait the issue doesn't present when optimizations are present and also doesn't reproduce without the usage of webpack looks more like a BUG

**Comment by alexander-akait** [comment] 2021-02-20 13:25
Yes, I see, bug (I think)

**Comment by mikearnaldi** [comment] 2021-02-20 13:44
I have it scoped down to the module flag in TS, if the `tsconfig.json` specify `"module": "commonjs"` the bug reproduces, if instead it is set to `"module": "es6"` it does not

**Comment by mikearnaldi** [comment] 2021-02-20 13:47
The repro with the changes are:
https://github.com/wesselvdv/used-before-initialization/tree/repro (commonjs raising the issue)
https://github.com/wesselvdv/used-before-initialization/tree/fine (es6 working as expected)

**Comment by sokra** [comment] 2021-02-20 14:16
There is a circular dependency in `@effect-ts/system`:

`@effect-ts/system/_traced/esm/Layer/definitions.js` exports LayerSuspend,
but before it does that it will import `@effect-ts/system/_traced/esm/Managed`,
which imports `@effect-ts/system/_traced/esm/Managed/methods/api.js`,
which imports `@effect-ts/system/_traced/esm/Layer/core.js`,
which imports LayerSuspend from `@effect-ts/system/_traced/esm/Layer/definitions.js`
(which is not finished yet, as it's circular)
and uses LayerSuspend in initialization in this line:
`export const Empty = /*#__PURE__*/ new LayerSuspend(() => identity())`.

Note that most of these modules are flagged as side effect free and there are also a few `/*#__PURE__*/` annotations, so a lot code might be dropped when optimizations are enabled, which could "fix" this code when e. g. the `Empty` export is unused.

Also note that execution order might change in side effect free modules even in development mode (side effects optimization is also enable in dev mode), so you might get different behavior. There are cases where code with circular dependencies depends on a certain execution order to work properly. This kind of code has an implicit side effect of putting some modules into the module cache.

Also note that when transpiling code from ESM to CJS, it might look like that "fixes" some of the circular dependencies as exports in circular dependencies might return `undefined` instead of throwing a `ReferenceError`.

Here is a simple example of this behavior: [typescript playground](https://www.typescriptlang.org/play?module=1#code/JYWwDg9gTgLgBAbzgDzgXzgMyhEcBEAdAPQDOApgDab4DcAsAFBMDGEAdqRJeYZRAHMAFMgCUDZo3LJIsOG07xUAXjgBGWkA). The typescript transpiled code logs undefined instead of throwing a ReferenceError.

**Comment by mikearnaldi** [comment] 2021-02-20 14:31
The above without webpack works just fine, compiling with tsc and executing with node so with the Empty constant used

**Comment by alexander-akait** [comment] 2021-02-20 14:35
Because `ts` generate wrong code, but when we try to bundle we face this problem

**Comment by mikearnaldi** [comment] 2021-02-20 14:37
It works even when Empty is explicitly used, both in TS and with webpack & es6 module:

https://github.com/wesselvdv/used-before-initialization/commit/03dcc7750be79b95080da003ce6165bc419da0a0

**Comment by mikearnaldi** [comment] 2021-02-20 14:42
> generate wrong code, but when we try to bundle we face this problem

would you mind saying exactly what wrong code does TS generate, if that is true we should raise the issue with the TS team too

**Comment by alexander-akait** [comment] 2021-02-20 14:48
https://github.com/microsoft/TypeScript/issues/20361

**Comment by alexander-akait** [comment] 2021-03-15 14:10
@mikearnaldi I think we can close it... nothing to fix on webpack side here, sorry

**Comment by JustFly1984** [comment] 2021-04-12 10:40
In my case it was circular dependency issue. Sadly typescript or eslint does not warn about circular imports.

**Comment by louisnow** [comment] 2021-04-12 11:01
@JustFly1984 You can try using [this plugin](https://github.com/aackerman/circular-dependency-plugin) to warn about circular imports

**Comment by bennycode** [comment] 2021-04-26 15:28
I also ran into the "ReferenceError" because I had circular imports in my TypeScript code by using [barrels](https://basarat.gitbook.io/typescript/main-1/barrel). I am using barrels now only for exports and don't use them myself in the library code that I write.

Using the "Circular Dependency Plugin" really helped to spot these problems. I also set "optimization.minimize" to "false" and "stats.errorDetails" to "true" in my webpack config, so that I can debug the non-minified code.

**Comment by alexander-akait** [comment] 2021-04-26 15:37
Yep, `Circular Dependency` is the problem sometimes, `Circular Dependency Plugin` should solve the problem, maybe we move it in core in future, we have the issue https://github.com/webpack/webpack/issues/7962, nothing to fix on webpack side here for original issue, sorry, feel free to feedback

**Closed by alexander-akait** 2021-04-26 15:37 UTC
Labels: bug, webpack-5

**Comment by kachar** [comment] 2024-09-27 16:16
Sometimes this problem is caused by importing from the parent directory's index file such as

```tsx
import { something } from '..'
```

**Comment by ghasnhhz** [comment] 2025-02-04 11:55
export let cart = JSON.parse(localStorage.getItem('cart')); 
import { updateCartQuantity } from '../scripts/checkout.js';
JSON.parse(localStorage.getItem('quantity'));


if (!cart) {
    cart = [{
      productId: 'e43638ce-6aa0-4b85-b27f-e1d07eb678c6',
      quantity: 2,
      deliveryOptionId: '1',
    },
    {
      productId: '15b6fc6f-327a-4ec4-896f-486349e85a3d',
      quantity: 1,
      deliveryOptionId: '2'
    }];
}  
I am exporting above code  from a file called cart.js to a file called checkout.js

import { cart } from '../data/cart.js';

But in checkout.js. when i tried to use it like 

cart.forEach((cartItem) => {
  Here some code
 };  
console says can not access cart before initialization. I have not been able to solve this for one day. PLEASE, someone help me
