### ISSUE TITLE
Module not found: Error: Can't resolve 'aws-sdk'  when importing Webpack

### ISSUE THREAD

**Issue by imjacobclark** [webpack/webpack#8400] opened 2018-11-21 08:03 UTC
# Bug report

**What is the current behavior?**

Importing Webpack into an Express application results in errors being thrown.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.dev.js:

```js
const path = require('path');

const server = {
    entry: './index.js',
    mode: "production",
    target: 'node',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].bundle.js',
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: "babel-loader"
            }, {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: "babel-loader"
            }
        ]
    }
};

module.exports = [server];
```

developmentMode.js
```js
import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';

export default (app) => {
    const webpackConfig = require('./webpack.config.dev')[0];

    const compiler = webpack(webpackConfig);

    app.use(webpackDevMiddleware(compiler, {}));
}
```

server.js
```js
import express from 'express';
import ReactDOMServer from 'react-dom/server';
import React from 'react';

import developmentMode from './developmentMode';

import HelloWorld from './src/HelloWorld.jsx';

const app = express();
const port = 3000;

if (process.env.NODE_ENV === "dev") developmentMode(app);

const template = application => `
<html>
    <head>
    </head>
    <body>
        ${application}
    </body>
</body>
`;

const application = ReactDOMServer.renderToString(<HelloWorld />);

app.get('/', (req, res) => res.send(template(application)));

app.listen(port, () => console.log(`Example app listening on port ${port}!`));
```

package.json
```json
{
  "version": "6.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --config webpack.config.dev.js",
    "start": "node dist/main.bundle.js"
  },
  "repository": {
    "type": "git",
  },
  "author": "Jacob Clark",
  "license": "MIT",
  "dependencies": {
    "express": "^4.16.4",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.4.0"
  }
}
```

Running `webpack --config  webpack.config.dev.js` yields the following errors

```
[clarkj84:~/Desktop/jacobclark.xyz]$ npm run build && npm start                                                                                                                                                                 (6.0.0-dev✱) 

> jacobclarkxyz@6.0.0 build /Users/clarkj84/Desktop/jacobclark.xyz
> webpack --config webpack.config.dev.js

Hash: b1078bef90371617b277
Version: webpack 4.26.0
Child
    Hash: b1078bef90371617b277
    Time: 33472ms
    Built at: 21/11/2018 08:01:36
     1 asset
    Entrypoint main = main.bundle.js
       [1] external "path" 42 bytes {0} [built]
       [9] (webpack)/lib/Template.js 7.96 KiB {0} [built]
      [13] external "events" 42 bytes {0} [built]
      [39] (webpack)/lib/dependencies/DependencyReference.js 1.75 KiB {0} [built]
      [45] (webpack)/lib/util/createHash.js 1.92 KiB {0} [built]
      [46] (webpack)/lib/Module.js 10.1 KiB {0} [built]
      [53] (webpack)/lib/ModuleFilenameHelpers.js 5.36 KiB {0} [built]
      [60] (webpack)/lib/Dependency.js 1.97 KiB {0} [built]
      [79] (webpack)/lib/ExternalsPlugin.js 546 bytes {0} [built]
      [87] (webpack)/lib/Stats.js 38.2 KiB {0} [built]
     [110] (webpack)/lib/node/NodeTemplatePlugin.js 880 bytes {0} [built]
     [513] (webpack)/lib/webpack.js 7.71 KiB {0} [built]
     [515] (webpack)-dev-middleware/index.js 2.21 KiB {0} [built]
    [1325] ./webpack.config.dev.js 433 bytes {0} [built]
    [1327] ./index.js + 2 modules 1.13 KiB {0} [built]
           | ./index.js 743 bytes [built]
           | ./developmentMode.js 273 bytes [built]
           | ./src/HelloWorld.jsx 118 bytes [built]
        + 1313 hidden modules
    
    WARNING in ./node_modules/terser-webpack-plugin/dist/worker.js 14:130-137
    Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
     @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
     @ ./node_modules/terser-webpack-plugin/dist/index.js
     @ ./node_modules/terser-webpack-plugin/dist/cjs.js
     @ (webpack)/lib/WebpackOptionsDefaulter.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/fsevents.js 14:13-71
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/worker-farm/lib/child/index.js 49:33-53
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/worker-farm/lib/fork.js
     @ ./node_modules/worker-farm/lib/farm.js
     @ ./node_modules/worker-farm/lib/index.js
     @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
     @ ./node_modules/terser-webpack-plugin/dist/index.js
     @ ./node_modules/terser-webpack-plugin/dist/cjs.js
     @ (webpack)/lib/WebpackOptionsDefaulter.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/loader-runner/lib/loadLoader.js 3:2-28
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/loader-runner/lib/LoaderRunner.js
     @ (webpack)/lib/NormalModule.js
     @ (webpack)/lib/AutomaticPrefetchPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/express/lib/view.js 81:13-25
    Critical dependency: the request of a dependency is an expression
     @ ./node_modules/express/lib/application.js
     @ ./node_modules/express/lib/express.js
     @ ./node_modules/express/index.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js
    Module not found: Error: Can't resolve 'node-gyp' in '/Users/clarkj84/Desktop/jacobclark.xyz/node_modules/fsevents/node_modules/node-pre-gyp/lib/util'
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js
    Module not found: Error: Can't resolve 'npm' in '/Users/clarkj84/Desktop/jacobclark.xyz/node_modules/fsevents/node_modules/node-pre-gyp/lib/util'
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    > <!doctype html>
    | <html>
    | <head>
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$ ./util/nw-pre-gyp/index.html
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    WARNING in ./node_modules/loader-runner/lib/loadLoader.js 3:2-28
    System.import() is deprecated and will be removed soon. Use import() instead.
    For more info visit https://webpack.js.org/guides/code-splitting/
     @ ./node_modules/loader-runner/lib/LoaderRunner.js 7:17-40
     @ (webpack)/lib/NormalModule.js
     @ (webpack)/lib/AutomaticPrefetchPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    ERROR in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/unpublish.js
    Module not found: Error: Can't resolve 'aws-sdk' in '/Users/clarkj84/Desktop/jacobclark.xyz/node_modules/fsevents/node_modules/node-pre-gyp/lib'
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/unpublish.js 16:14-32
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    ERROR in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/publish.js
    Module not found: Error: Can't resolve 'aws-sdk' in '/Users/clarkj84/Desktop/jacobclark.xyz/node_modules/fsevents/node_modules/node-pre-gyp/lib'
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/publish.js 18:14-32
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
    
    ERROR in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/info.js
    Module not found: Error: Can't resolve 'aws-sdk' in '/Users/clarkj84/Desktop/jacobclark.xyz/node_modules/fsevents/node_modules/node-pre-gyp/lib'
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/info.js 14:14-32
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib sync ^\.\/.*$
     @ ./node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js
     @ ./node_modules/fsevents/fsevents.js
     @ ./node_modules/chokidar/lib/fsevents-handler.js
     @ ./node_modules/chokidar/index.js
     @ ./node_modules/watchpack/lib/DirectoryWatcher.js
     @ ./node_modules/watchpack/lib/watcherManager.js
     @ ./node_modules/watchpack/lib/watchpack.js
     @ (webpack)/lib/node/NodeWatchFileSystem.js
     @ (webpack)/lib/node/NodeEnvironmentPlugin.js
     @ (webpack)/lib/webpack.js
     @ ./developmentMode.js
     @ ./index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jacobclarkxyz@6.0.0 build: `webpack --config webpack.config.dev.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jacobclarkxyz@6.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clarkj84/.npm/_logs/2018-11-21T08_01_36_419Z-debug.log
```

**What is the expected behavior?**

Webpack should run without errors.

**Other relevant information:**
webpack version:  4.26.0
Node.js version: 9.4.0
Operating System: OS X 10.12.6
Additional tools: N/A

**Comment by ooflorent** [comment] 2018-11-21 08:11
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by samkelleher** [comment] 2018-11-28 17:37
I have the same issue when webpacking a custom nextjs config because it requires 'next' which itself requires 'webpack'. I've tried combinations without success:
mode: none
exclude /node_modules/
include /src/

**Comment by samkelleher** [comment] 2018-11-28 17:43
I solved this using https://github.com/liady/webpack-node-externals and forcing webpack to ignore all node_modules

**Comment by FritiofGure** [comment] 2019-02-04 07:58
@samkelleher hey! how do you use nodeExternals with next.config.js? I am not getting it to work. Do you push it onto the config or what?

**Comment by legalbridge** [comment] 2019-06-17 19:39
I'm having the same problem as soon as I added a dependency for sqlite3. Not sure how that's related, but my whole app works fine, but as soon as I `import { Database } from 'sqlite3'` I get this error. Note: node-pre-gyp was already present before adding this dependency.

**Comment by nmaxcom** [comment] 2019-07-20 14:44
I'm having the same error. I'm trying to make webpack HMR work with Express and Pug and it's a nightmare. And now this aws-sdk error.

**Comment by rorofino** [comment] 2019-08-02 03:15
Any fix for this?

**Comment by imVinayPandya** [comment] 2019-08-11 09:41
@samkelleher can you please post your solution with next.js, i am also blocked in this error with next.js.

**Comment by samkelleher** [comment] 2019-08-12 14:23
Just use nodeExternals exactly as it's documented in their readme @imVinayPandya

**Comment by mayurssoni2456** [comment] 2019-10-15 12:00
> I'm having the same problem as soon as I added a dependency for sqlite3. Not sure how that's related, but my whole app works fine, but as soon as I `import { Database } from 'sqlite3'` I get this error. Note: node-pre-gyp was already present before adding this dependency.

Hey, I am facing the same error after adding SQLite in my electron react app. Could you please share - how did you fixed this? thank you

**Comment by Saroopashree** [comment] 2019-11-22 10:30
> > I'm having the same problem as soon as I added a dependency for sqlite3. Not sure how that's related, but my whole app works fine, but as soon as I `import { Database } from 'sqlite3'` I get this error. Note: node-pre-gyp was already present before adding this dependency.
> 
> Hey, I am facing the same error after adding SQLite in my electron react app. Could you please share - how did you fixed this? thank you

Hey, I too have the same problem after I tried adding sqlite3 to my electron react app. It would be really helpful if someone shares the fix.

**Comment by Ezulio** [comment] 2020-01-09 16:57
> > > I'm having the same problem as soon as I added a dependency for sqlite3. Not sure how that's related, but my whole app works fine, but as soon as I `import { Database } from 'sqlite3'` I get this error. Note: node-pre-gyp was already present before adding this dependency.
> > 
> > 
> > Hey, I am facing the same error after adding SQLite in my electron react app. Could you please share - how did you fixed this? thank you
> 
> Hey, I too have the same problem after I tried adding sqlite3 to my electron react app. It would be really helpful if someone shares the fix.

me too, can anyone help me?

**Comment by andreesteva** [comment] 2020-02-20 01:41
I fixed this issue by doing `npm install @aws-sdk/eventstream-marshaller` and then in the js `require("@aws-sdk/eventstream-marshaller");`

**Closed** 2020-03-18 07:45 UTC

**Comment by oneacik** [comment] 2020-05-04 10:08
Webpack is adding to compilation every import/require it seems.
When there is used require as an expression (that should executed for example only conditionally), then it will try to bundle it too. That's why for example 'knex' has a lot of problems with webpack, because it has a lot of dependencies being required canditionally during runtime.

My solution for this is to use externals for everything that is to be bundled by webpack, but unneeded. 

Example configuration for 'knex' and 'sqlite3' that also drops aws-sdk:

`  
externals: {
    'aws-sdk': 'aws-sdk',
    pg: 'pg',
    'pg-query-stream': 'pg-query-stream',
    mssql: 'mssql',
    'mssql/lib/base': 'mssql/lib/base',
    'mssql/package.json': 'mssql/package.json',
    mysql: 'mysql',
    mysql2: 'mysql2',
    oracle: 'oracle',
    oracledb: 'oracledb',
    tedious: 'tedious'
  }
`

**Comment by kdlogan19** [comment] 2020-06-20 23:09
> @samkelleher can you please post your solution with next.js, i am also blocked in this error with next.js.

Hey Vinay, were you able to fix the problem? I am having the same issue.

**Comment by mkempinsky** [comment] 2020-07-15 19:05
Before you fall down the rabbit hole.. I ran into this issue because I had `import {render} from 'sass';` in one of my files accidentally. It must have been automatically imported when I typed 'render' at some point. Removing it fixed the issue in my next.js app.

**Comment by antun** [comment] 2020-09-19 03:36
@mkempinsky do you know why adding a simple import statement like that causes Webpack to break like this? In my case, I intentionally added a simple module to my code (https://github.com/peterolson/hanzi-tools) and got this same, long, sequence of errors, that don't seem to be related.

**Comment by robquinn** [comment] 2021-03-26 11:33
It seems the proposed solution in this thread is to use the `webpack-node-externals` package.

I tried that, and it did work. However, I later found out that I cannot use `webpack-node-externals` in my project. I am trying to create a script and run it in a browser; `webpack-node-externals` essentially tells webpack not to bundle `node_modules` as dependencies. However, since my target environment is in the browser, I NEED those `node_modules` packaged into my script as dependencies. So this issue is still unresolved for me.

***How can I fix this error, WITHOUT using `webpack-node-externals`???***
