### ISSUE TITLE
Regression between 1.12.7 & 1.12.8

### ISSUE THREAD

**Issue by JSteunou** [webpack/webpack#1684] opened 2015-11-30 10:07 UTC
Mostly copy / paste from https://github.com/webpack/webpack-dev-server/issues/331

I dont know exactly whats going on but since the last update each time I have a live reload I got a javascript error linked to some async module

Everything was going fine for months, I have a normal app with some async bundle. Build is ok, dev was ok, since the upgrade this morning things are broken only for dev in live reload.

**Comment by JSteunou** [comment] 2015-11-30 10:14
After some trials I found the culprit: https://github.com/webpack/webpack/commit/181da3c004bdb59377d68146240c96f8b6715707

* webpack-dev-server 1.12.0 + webpack 1.12.2 was fine
* webpack-dev-server 1.14.0 + webpack 1.12.9 is broken
* webpack-dev-server 1.14.0 + webpack 1.12.2 is fine
* webpack-dev-server 1.14.0 + webpack 1.12.8 is broken
* webpack-dev-server 1.14.0 + webpack 1.12.7 is fine

I do use the CommonChunk plugin, I have an app and vendor and some `require.ensure` / async chunk.

The error I'm getting is triggering in this

```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// install a JSONP callback for chunk loading
/******/ 	var parentJsonpFunction = window["webpackJsonp"];
/******/ 	window["webpackJsonp"] = function webpackJsonpCallback(chunkIds, moreModules) {
/******/ 		// add "moreModules" to the modules object,
/******/ 		// then flag all "chunkIds" as loaded and fire callback
/******/ 		var moduleId, chunkId, i = 0, callbacks = [];
/******/ 		for(;i < chunkIds.length; i++) {
/******/ 			chunkId = chunkIds[i];
/******/ 			if(installedChunks[chunkId])
/******/ 				callbacks.push.apply(callbacks, installedChunks[chunkId]);
/******/ 			installedChunks[chunkId] = 0;
/******/ 		}
/******/ 		for(moduleId in moreModules) {
/******/ 			var _m = moreModules[moduleId];

/******/ 			// Check if module is deduplicated
/******/ 			switch(typeof _m) {
/******/ 			case "object":
/******/ 				// Module can be created from a template
/******/ 				modules[moduleId] = (function(_m) {
/******/ 					var args = _m.slice(1), templateId = _m[0];
/******/ 					return function (a,b,c) {
/******/ 						modules[templateId].apply(this, [a,b,c].concat(args));
/******/ 					};
/******/ 				}(_m));
/******/ 				break;
```

from `modules[templateId].apply`

> Cannot read property 'apply' of undefined

**Comment by sokra** [comment] 2015-12-02 18:01
hmm... The commit fixes a bug with the CommonsChunkPlugin that other optimization doesn't run correctly.

Does it work without the DedupePlugin?

**Comment by sokra** [comment] 2015-12-22 10:16
pling

**Comment by JSteunou** [comment] 2015-12-22 14:54
Sorry i am in holidays cannot check
Le 22 déc. 2015 11:16 AM, "Tobias Koppers" <notifications@github.com> a
écrit :

**Comment by davidpelayo** [comment] 2016-02-05 11:42
Is it confirmed it does work without the DedupePlugin?

**Comment by bebraw** [comment] 2016-08-15 07:07
@JSteunou Any update on this?

**Comment by JSteunou** [comment] 2016-08-15 17:44
Still stuck with 1.12.7

Le 15 août 2016 09:08, "Juho Vepsäläinen" <notifications@github.com> a
écrit :

**Comment by Phieo** [comment] 2016-08-16 08:05
Don’t use dedupeplugin in  `watch mode` [dedupeplugin](https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin)

**Comment by bebraw** [comment] 2016-12-25 08:05
Closing as DedupePlugin was deprecated.

**Closed by bebraw** 2016-12-25 08:05 UTC
Labels: bug
