### ISSUE TITLE
monorepo with webpack

### ISSUE THREAD

**Issue by karaxuna** [webpack/webpack#7747] opened 2018-07-19 10:18 UTC
I'm trying to create monorepo which will contain components that are built with typescript and sass. Folder structure looks like this:

- packages
    - components
        - src
            - Slider
                - Slider.ts (import 'Slider.scss')
                - Slider.scss
            - Modal
                - Modal.ts (import 'Modal.scss')
                - Modal.scss
        - webpack.config.js
    - app1
        - src
            - index.ts (import Slider from `components/src/Slider/Slider`)
        - webpack.config.js
    - app2
        - src
            - index.ts (import Slider from `components/src/Slider/Slider`)
        - webpack.config.js

I want to use components in app1 and app2. What I tried is building components with DllPlugin and referencing it in app1 and app2 with DllReferencePlugin, it works well for typescript files, but what about scss, images, fonts and other assets? When building app1 or app2, I want their dist folder to include all assets from components. The reason why I'm not importing directly components/src/Modal without dll plugin is that components folder may have different webpack configuration like alias for example. What's the best practice for accomplishing this?

**Comment by evilebottnawi** [comment] 2018-07-19 10:22
@karaxuna please use issue template

**Comment by montogeek** [comment] 2018-07-19 10:30
Duplicate of https://github.com/webpack/webpack/issues/7745.
Please follow the rules.

**Closed by montogeek** 2018-07-19 10:30 UTC
