### ISSUE TITLE
contenthash vs chunkhash

### ISSUE THREAD

**Issue by DrGor** [webpack/webpack#8360] opened 2018-11-09 00:34 UTC
It is recommended to use [contenthash] instead of [chunkhash] in https://webpack.js.org/guides/caching.
However, is it always safe to use [contenthash] given chunk ids might change when a new chunk is added ? See https://github.com/webpack/webpack/issues/4837

So, it is possible to run into a situation when chunk is actually changed (a new chunk id used in the chunk file) but since the extracted content was not changed it generates the same file name(given you use [contenthash]). Now if this file was already cached on client's browser it will use the old chunk id while the new manifest.js refers to the new chunk id.

**Comment by evilebottnawi** [comment] 2018-11-09 10:19
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Use `[contanthash]` always, please create issue with reproducible test repo

**Closed by evilebottnawi** 2018-11-09 10:19 UTC
