### ISSUE TITLE
compute [contenthash] after generate file

### ISSUE THREAD

**Issue by thomasjm** [webpack/webpack#9520] opened 2019-08-04 08:28 UTC
## Feature request

**What is the expected behavior?**

The documentation says that

> The `[contenthash]` substitution will add a unique hash based on the content of an asset. When the asset's content changes, `[contenthash]` will change as well.

However, the `[contenthash]` does **not** actually match the hash of the file, i.e. the result you would get if you ran `md5sum` or `sha256sum` on the file.

This [StackOverflow answer](https://stackoverflow.com/questions/50224845/why-is-the-contenthash-different-in-webpack) explains why: the `[contenthash]` is computed before minification.

The feature request is to compute the `[contenthash]` *after* minification/any other post-processing steps, or at least provide an option to do so. 

**What is motivation or use case for adding/changing the behavior?**

This would have nice properties, such as allowing proxies to validate the integrity of a file just by comparing its hash to the filename.

**How should this be implemented in your opinion?**

Change the point in the process where the `[contenthash]` is computed. I don't know anything about webpack's architecture so I have no idea how hard this is.

**Are you willing to work on this yourself?**

I'm not a webpack developer but if there was some guidance from an expert I could take a stab at it.

**Comment by evilebottnawi** [comment] 2019-08-05 08:48
@thomasjm it is md4 of file for perf reason, why you need `md5`, you can change this using option

> This would have nice properties, such as allowing proxies to validate the integrity of a file just by comparing its hash to the filename.

Please clarify

All work as expected.

**Comment by thomasjm** [comment] 2019-08-05 09:23
I'm not asking to change it to `md5`, it was just an example. I'm aware that you can change the hash algorithm using the `output.hashFunction` option.

I'm asking to make the hash produced by interpolating the `[contenthash]` in the filename match the actual hash of the file, no matter what algorithm you use.

Actually, I just found this plugin that accomplishes what I wanted: https://www.npmjs.com/package/webpack-plugin-hash-output. Perhaps this issue can be closed since the plugin solves it. But I still think it might make sense to make this the default behavior.

**Comment by evilebottnawi** [comment] 2019-08-05 09:25
@thomasjm please provide example where `contenthash` is not match `actual hash of the file`

**Comment by evilebottnawi** [comment] 2019-08-05 09:28
Looks this plugins fix problem what i describe above and we already track this problem https://github.com/webpack-contrib/terser-webpack-plugin/issues/18

**Comment by sokra** [comment] 2019-08-05 10:04
> please provide example where `contenthash` is not match `actual hash of the file` (now we have problem with terser minification only)

It never matches the actual hash of the file. The hash is computed before the file is generated.

I also thought about changing this, but it requires some additional refactorings since plugins (like terser-webpack-plugin) affect the file content after it has been generated by webpack.

Plugin would need to stop doing this and use a different hook instead which allows to alter the file content while generation. One reason is that some files (the main chunk) depend on the hash of other files (on-demand-loaded chunks), as hashes need to be included in source code.

There is a card about this on the webpack 5 board, but I unsure if this will make it into the final version as it breaks a lot of plugins. It also has a performance impact since i. e. minimizing has to be serialized for some files.

**Comment by thomasjm** [comment] 2019-08-05 20:51
Got it, thanks @sokra. I'm happy to close this issue and track the card you mentioned instead. 

(Can you point me to it? I'm looking through https://github.com/webpack/webpack/projects/5 and having trouble finding it.)

**Comment by yale** [comment] 2019-08-07 20:46
+1 to this issue. Since we load our assets from a CDN with long-lived cache headers (roughly following the [Immutable Web App pattern](https://immutablewebapps.org/)), we ran into an issue where customers' browsers will fail to load cached assets since it fails the sub-resource integrity check (same filename, but different expected SHA-256). 

The whole immutable web app pattern relies on the assumption that assets never change - and if they do, they result in a completely new asset file. I had assumed that `[contenthash]` fulfills that requirement, but I guess I didn't dig deep enough. :)

**Comment by glen-84** [comment] 2019-10-12 08:38
Duplicate of #7787 (?).

**Comment by thomasjm** [comment] 2020-01-15 09:01
Could we keep this issue alive? I'd still like to see this change

**Comment by evilebottnawi** [comment] 2020-02-14 15:50
Source map generation not affected on contenthash https://github.com/webpack/webpack/issues/9853 also

**Comment by jdb8** [comment] 2020-03-24 04:15
Just ran into this, and read through the various interlinked issues across this repo + plugin repos that encounter this (e.g. https://github.com/webpack/webpack/issues/7787,  https://github.com/webpack-contrib/terser-webpack-plugin/issues/18).

Regardless of whether this change makes it into webpack 5 or later, is there a recommended way to handle this in plugins today with webpack 4? 

My use case is similar to terser (optimisation of assets, as late as possible in the compilation) and I notice there that a [partial fix](https://github.com/webpack-contrib/terser-webpack-plugin/pull/44) was applied which updates the hash with the version/options of terser, to ensure that the hash changes if the terser plugin options change. This makes sense, but it seems like it makes the assumption that for a given version of terser with the same options, the output contents will always be the same. 

This may be applicable for terser specifically but in cases where a plugin may not be able to guarantee determinism (or worse, may **assume** determinism but has subtle bugs making this not the case), how do we ensure that the files ultimately output to disk by webpack have a `contenthash` that reflects changes made by a plugin? 

Apologies if this isn't the write issue for this question, but I haven't been able to find docs/best practices around updating assets if they've changed during a step such as `optimizeAssets`. I'm currently considering looping over each asset in the compilation that I've modified, and manually updating the name to include the new calculated contenthash (and then deleting the old asset from `compilation.assets` entirely), e.g.:

```js
assets.forEach(asset => {
    const newAssetNameBasedOnHash = loaderUtils.interpolateName(...);
    compilation.assets[newAssetNameBasedOnHash] = compilation.assets[asset];
    delete compilation.assets[asset];
});
```

This feels a bit odd and would also require manually replacing references to the old sourcemaps/etc. in the source with the new hashed names.

Any advice/documentation about what's best here would be greatly appreciated, especially if this isn't going to end up being included in webpack 5 due to backwards-incompatibility concerns as mentioned above.

**Comment by hopperhuang** [comment] 2020-06-30 10:35
@evilebottnawi Will this problem also be fixed in webpack@4 or only will be fixed in webpack@5 ?  I see this problem just labeled as webpack-v5  which make me curious.

**Comment by evilebottnawi** [comment] 2020-06-30 11:13
@hopperhuang it will be fixed in webpack@5/webpack@6, it is not easy to fix because it is big breaking change

**Comment by evilebottnawi** [comment] 2020-08-29 16:24
Fixed by https://github.com/webpack/webpack/pull/11339 using the `optimization.realContentHash` option, it is `true` in production mode by default, in development mode we recommend do not use `hash`s in file names, but this will still work as expected

**Closed by evilebottnawi** 2020-08-29 16:24 UTC
Labels: webpack-5

**Comment by acejs** [comment] 2020-12-22 13:08
@alexander-akait In webpack@4, how can I update [contenthash] based on actual file content. 
Because I want to change `compilation.assets` in `optimizeChunkAssets` hooks, and the modification of the same file may be different each time.
Do you have any suggestion?  Thanks

**Comment by alexander-akait** [comment] 2020-12-22 13:14
No suggestion, it is new feature for webpack@5, consider to update

**Comment by SamMorrowDrums** [comment] 2021-04-09 16:20
I am having this issue with Webpack 5, when I run the build in docker on CI server. Using `RUN npm ci --include dev` to install node modules - so they shouldn't be changing between builds, but regardelss I've done multiple in with in minutes and the main.[contenthash].js is changing. I'll have to see if there is a way I can confirm what parts are changing, but main parts

```
  mode: 'production',
  entry: path.join(process.cwd(), 'app/app.js'),
  output: {
    filename: '[name].[contenthash].js',
    // Compile into js/build.js
    path: path.resolve(process.cwd(), 'build'),
    publicPath: '/'
  },
```

```
optimization: {
    minimize: true,
    minimizer: [
      `...`,
      new CssMinimizerPlugin(),
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production'),
      'process.env.CODE_VERSION': JSON.stringify(process.env.CODE_VERSION),
      'typeof window': JSON.stringify('object'),
      'process.env.NODE_DEBUG':  JSON.stringify(process.env.NODE_DEBUG)
    }),
    new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true
      },
      inject: true // Inject all files that are generated by webpack, e.g. bundle.js
    }),
    new faviconsWebpackPlugin('app/jump-logo.svg'),
    new webpack.ProvidePlugin({
      Tether: 'tether',
      Popper: ['popper.js', 'default'],
      '$': 'jquery',
      jQuery: 'jquery',
    }),
    new MiniCssExtractPlugin({
      filename: '[name].[contenthash].css',
      chunkFilename: '[id].[contenthash].css'
    })
  ],
  resolve: {
    modules: ['app', 'node_modules'],
    extensions: ['.js', '.jsx', '.react.js'],
    alias: {
      'jquery': 'jquery/dist/jquery.slim.min.js',
    }
  },
  target: 'browserslist', // Make web variables accessible to webpack, e.g. window
  stats: true // Show stats in the console
};
```

Not sure if any surprises in there - but I would have thought that I should be seeing reproducible builds. When I run repeatedly on same machine, I get same results and when I change a comment or whitespace in the webpack config file, and push to CI it is getting a different hash on each build.

I'm just curious, I'd love to have the main.js stay the same as it's largest file, and should be cached unless it changes.

**Comment by knockdownpaco617** [comment] 2025-01-31 10:08
https://jqcode.space/questions/streamline-complex-calculations-with-multiple-outputs Reflect on this explanation
