### ISSUE TITLE
2.2.0-rc.4's es6 modules' "module" usage detection seems to be broken

### ISSUE THREAD

**Issue by SEAPUNK** [webpack/webpack#3917] opened 2017-01-11 19:21 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

External modules (symbol-observable, moment) no longer compile with this release.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use webpack 2.2.0-rc.4
2. Compile a script that requires moment or symbol-observable (or another module that triggers this problem)

**What is the expected behavior?**

Bundle compiles fine

---

It doesn't appear that moment and symbol-observable modules actually use `module.exports` at the locations Webpack says there is an error.

For example, `symbol-observable/es/index.js`:

```js
/* global window */
import ponyfill from './ponyfill';

var root;

if (typeof self !== 'undefined') {
  root = self;
} else if (typeof window !== 'undefined') {
  root = window;
} else if (typeof global !== 'undefined') {
  root = global;
} else if (typeof module !== 'undefined') {
  root = module;
} else {
  root = Function('return this')();
}

var result = ponyfill(root);
export default result;
```

Gives the error:

```
./~/symbol-observable/es/index.js
13:9-15 module is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'module' is not allowed.
```

**Comment by terinjokes** [comment] 2017-01-11 20:38
Adding to `symbol-observable`, it looks like `lodash-es` falls into this same bug.

```javascript
import root from './_root.js';

/** Detect free variable `exports`. */
var freeExports = typeof exports == 'object' && exports && !exports.nodeType && exports;
```

**Comment by TheLarkInn** [comment] 2017-01-11 20:38
By exporting And importing this is considering it an esm module. Esm has no access to local `module` or `exports` values even if only used as some sort of UMD wrap, which it appears to be here.

**Comment by jdalton** [comment] 2017-01-11 20:46
Checking for the existence of a variable should not trigger the warning. It's valid JavaScript regardless of context. If possible, it would be better to detect assigning to the free variables in question:
```js
exports.foo = 1;
// or
module.exports = {};
```

**Comment by TheLarkInn** [comment] 2017-01-11 20:47
Was just asking about this. Thanks for the follow-up

**Comment by jdalton** [comment] 2017-01-11 20:49
>  If possible, it would be better to detect assigning to the free variables in question:

Ah, that might still catch UMD juggling which is safe. Maybe instead of a hard error treat it as a warning? Or get fancy and only throw the warning if the assigned `exports` or `module.exports` assignments are done outside of an `if` block.

**Comment by SEAPUNK** [comment] 2017-01-11 20:54
> Or get fancy and only throw the warning if the exports or module.exports assignments are done outside of an if block.

I don't think that would catch all the ways this could happen, may it be in a try/catch, or even indirect assignment a-la `exportMethods(module)`, which looks like what symbol-observable is doing.

I think it's better as a warning, instead of a hard error, with the possibility of disabling the warning on certain locations in the config.

**Comment by TheLarkInn** [comment] 2017-01-11 21:12
@jdalton @SEAPUNK Is the vast majority of this UMD handling or interop checks you are guessing?

**Comment by SEAPUNK** [comment] 2017-01-11 21:14
I think it is. Moment's code where the error appears looks slightly different, but I'd bet that it's the case for it too.

**Comment by jdalton** [comment] 2017-01-11 21:20
> Is the vast majority of this UMD handling or interop checks you are guessing?

For the falsely flagged cases yes. For common UMD patterns see the [umdjs repo](https://github.com/umdjs/umd/tree/master/templates)

**Comment by jdalton** [comment] 2017-01-11 21:22
You may find most UMD cases check for the existence of the free variables before use so tripping a `typeof` check. While non-UMD cases just assign at will without existence checks.

**Comment by TheLarkInn** [comment] 2017-01-11 21:23
🤔 We do have support based on the `module` and `main` field. I'm not saying we shouldn't fix this, but I feel like working together with lib authors to publish according to @defunctzombie 's https://github.com/defunctzombie/package-browser-field-spec

webpack's module resolution pattern respects this resolution spec. Just as workaround?

**Comment by TheLarkInn** [comment] 2017-01-11 21:24
> You may find most UMD cases check for the existence of the free variables before use so tripping a typeof check. While non-UMD cases just assign at will without existence checks.

I think thats a good start.

**Comment by dkrutsko** [comment] 2017-01-11 21:34
It looks like it's also breaking on `module.hot`. Is this normal? are we suppost to use something else now?

```js
if (module.hot)
    module.hot.accept (...);
```

**Comment by jdalton** [comment] 2017-01-11 21:37
In that case I think the warning, (so instead of a straight error a warning), should be triggered since you're assuming the existence of `module`, so not checking it exists before using it.

**Comment by dkrutsko** [comment] 2017-01-11 21:42
@jdalton: You're right. Although shouldn't there be a different way of implementing HMR now? Like through importing the `module.hot` function. Similar to how react-hot-loader does it with `AppContainer`?

**Comment by TheLarkInn** [comment] 2017-01-11 22:28
@SEAPUNK Thank you for submitting your first issue btw!!! 🙇

**Comment by SEAPUNK** [comment] 2017-01-11 22:31
Haha, no problem. I've been using Webpack for a while; it's a great project! Someday I hope to contribute to it.

**Comment by TheLarkInn** [comment] 2017-01-11 22:40
Never too late to start :-D :-D 

The suspect plugin here is: **CommonJSInHarmonyDependencyParserPlugin.js**

![screen shot 2017-01-11 at 4 39 13 pm](https://cloud.githubusercontent.com/assets/3408176/21869290/9456ab64-d81c-11e6-8fe3-45d583b79964.png)

I believe either in the individual DependencyBlocks or here, we need to conditionally hook into only certain types of ast aware logic. Like "Was this a free global access or assignment?".

**Comment by Kovensky** [comment] 2017-01-11 23:24
It looks like it needs `"typeof module"` and `"typeof exports"` plugins to replace them with the constant `"undefined"`. I am not sure, but I _think_ webpack should then detect the rest of the expression is unreachable and not parse it.

**Comment by Kovensky** [comment] 2017-01-11 23:32
@dkrutsko the `module.hot` expression, specifically, is supposed to work.

One thing that won't work is, say, passing the `module` object to a function that then checks for the `hot` property. Would need to use something like `{ get hot () { return module.hot } }` in that case.

**Comment by griffinmichl** [comment] 2017-01-12 00:09
redux and redux-form both use lodash-es, which means they produce this same bug

**Comment by jdalton** [comment] 2017-01-12 00:12
> redux and redux-form both use lodash-es, which means they produce this same bug

That's a maybe. redux uses the `isPlainObject` module of Lodash which may or may not access the `freeModule` code path.

**Comment by griffinmichl** [comment] 2017-01-12 00:13
One or the other is broken by this issue. They're the only libraries using lodash-es in my failing build.

**Comment by sokra** [comment] 2017-01-12 07:18
UMD handling in an ES2015 module doesn't make sense. If you have `import`/`export` in a file, it's not parse-able in any other module style.

So having an UMD handling in a ES2015 module is just wrong.

> could still be validly declared and used as a plain variable, for whatever weird reason someone wants to use it.

The error only occurs if you are using `module` as free var. If you declare it it should be fine.

**Comment by sokra** [comment] 2017-01-12 07:26
yes we could change webpack behavior to be less strict here. But doesn't it make sense to point out these "wrong" usage of UMD?

**Comment by jdalton** [comment] 2017-01-12 07:31
> So having an UMD handling in a ES2015 module is just wrong.

Projects have various builds and environment checks can shake out of that (if UMD is a hangup think of it as generic environment checks).

**Comment by TheLarkInn** [comment] 2017-01-12 15:48
So I'm torn. There are Pros and Cons to this. By keeping the constraint we could have more consistent and standardized way of splitting up esm and cjs code with https://github.com/defunctzombie/package-browser-field-spec

The con is that this is allowed in JS but it comes at the cost of lib authors (which of course we'd want to help them change this). It's valid js like @jdalton said but dose increase parse complexity. 

I'm really on the fence with this. 

(module.hot is a different story though).

**Comment by jdalton** [comment] 2017-01-12 16:15
FWIW `lodash-es` does [work](https://jsbin.com/cazurag/) the latest [Safari Technical Preview](https://developer.apple.com/safari/technology-preview/) which supports `type=module`.
```html
  <script type="module">
    import lodash from "https://unpkg.com/lodash-es@4.17.4/lodash.js";
    import { chunk } from "https://unpkg.com/lodash-es@4.17.4/lodash.js";
    
    log(`lodash.VERSION is ${ JSON.stringify(lodash.VERSION) }`);
    log(`chunk([1, 2, 3, 4], 2) is ${ JSON.stringify(chunk([1, 2, 3, 4], 2)) }`);
  </script>
```

**Comment by TheLarkInn** [comment] 2017-01-12 16:18
Exactly.

**Comment by Kovensky** [comment] 2017-01-12 23:43
@jdalton the way lodash-es detects exports (i.e. by using `typeof`) _is_ supposed to work in webpack 2 (well, it doesn't work because of a bug where it didn't specify typeof' result), but _actually accessing_ it should be a `ReferenceError`.

**Comment by jdalton** [comment] 2017-01-12 23:55
@Kovensky are you thinking out loud?

**Comment by phyllisstein** [comment] 2017-01-13 07:30
For reasons I don't quite understand, this error is being triggered for me by files that use the `export * from 'foo';` syntax. For example, I have a module whose `index.js` looks like this:

```js
// app/flux/selectors/index.js

export * from './fields.js';
```

...and `fields.js`, which has a number of named exports:

```js
import _ from 'lodash/fp';

export const getError = (state, field) => _.get(['fields', field, 'error'], state);

export const getField = (state, field) => _.get(['fields', field], state);

export const getFieldValue = (state, field) => _.get(['fields', field, 'value'], state);

export const isVisited = (state, field) => _.get(['fields', field, 'visited'], state);
```

Webpack 2.2.0-rc.3 emits the following...

```js
/***/ "./app/flux/selectors/index.js":
/* unknown exports provided */
/* all exports used */
/*!*************************************!*\
  !*** ./app/flux/selectors/index.js ***!
  \*************************************/
/***/ function(module, exports, __webpack_require__) {

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_object_define_property__ = __webpack_require__(/*! babel-runtime/core-js/object/define-property */ "../node_modules/babel-runtime/core-js/object/define-property.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_object_define_property___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_object_define_property__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_babel_runtime_core_js_object_keys__ = __webpack_require__(/*! babel-runtime/core-js/object/keys */ "../node_modules/babel-runtime/core-js/object/keys.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_babel_runtime_core_js_object_keys___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_babel_runtime_core_js_object_keys__);




Object.defineProperty(exports, "__esModule", {
  value: true
});

var _fields = __webpack_require__(/*! ./fields */ "./app/flux/selectors/fields.js");

__WEBPACK_IMPORTED_MODULE_1_babel_runtime_core_js_object_keys___default()(_fields).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;

  __WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_object_define_property___default()(exports, key, {
    enumerable: true,
    get: function get() {
      return _fields[key];
    }
  });
});

;

var _temp = function () {
  if (typeof __REACT_HOT_LOADER__ === 'undefined') {
    return;
  }
}();

;

/***/ }
```

...but Webpack 2.2.0-rc.4 aborts with the error that's already been described. I'm pinning to the old version for now, but I'd be grateful for any insight into what's going wrong here.

**Comment by mikecao** [comment] 2017-01-13 17:36
@phyllisstein I'm getting the same error (#3945) but for the opposite reason, I'm not using any import/export syntax. We're both using Babel so the issue could be a false positive somewhere in the babel code.

**Comment by todd-richmond** [comment] 2017-01-13 18:38
recent react-redux 5.0.2 update from 5.0.1 causes this exact lodash-es error to happen for me and the only fix was to hard-code the previous version. The new version included a large set of dependency updates so not sure which initiates the problem

**Comment by niieani** [comment] 2017-01-13 19:32
We have another use case in Aurelia. We have a module which can be bundled/run by Webpack, RequireJS, SystemJS or NodeJS and it "detects" which one it is. Webpack seems to trip up during the Node detection:

```js
if (isNodeLike && typeof module !== 'undefined' && typeof module.require !== 'undefined') {
    var m = module.require('aurelia-loader-nodejs');
    return Promise.resolve(new m.NodeJsLoader());
}
```

It returns the same error. We should have a way to disable this warning when used purposefully.

**Comment by TheLarkInn** [comment] 2017-01-13 21:24
We are working on that as we speak!! Thank you for all the reports!

**Comment by SEAPUNK** [comment] 2017-01-13 21:26
What's the plan of action?

**Comment by TheLarkInn** [comment] 2017-01-13 22:04
My thoughts are:

We will still warn for assignment on global usages of module and exports inside harmony detected modules, however will not warn of `typeof` and other valid cases of JavaScript. (Ie: new declaration, etc.). 

For most cases treating `typeof module` inside of a harmony detected module could also be transformed like with DefinePlugin to `undefined` This would cut out or drop BinaryStatements that have unreachable code. 

I'm going to assign @sokra this unless he wants to give me further guidance and then I will revisit the branch I'm on already.

**Comment by SEAPUNK** [comment] 2017-01-13 22:12
> We will still warn for assignment on global usages of module and exports inside harmony detected modules

Warn as in a compliation error, or a plain warning?

**Comment by TheLarkInn** [comment] 2017-01-13 22:16
Error, sorry we call them warns in their classes but an actual invalid use of cjs exports inside of harmony modules will and should fail.

**Comment by SEAPUNK** [comment] 2017-01-13 22:22
That's what I was concerned about -- I feel that even if doing those typeof checks and such will help not trigger most cases, but I'm almost sure that there will always be another weird 'edge case' that trips this problem.

For instance, consider this code:

```js
import this from 'that'

// badly named variable used in some code
const exports = {} // the variable could even be not defined here, but in some window global

// wouldn't this trip webpack up here as well?
exports.a = 4

// do something with exports later
```

So rather than causing a compilation error, can't it just be a compilation warning? Even if it *could* cause problems at runtime, it's still technically valid JS.

**Comment by niieani** [comment] 2017-01-14 11:09
@TheLarkInn if Webpack only ignores the `typeof module` construct, will the following code behave properly?:

```js
if (typeof module !== 'undefined' && typeof module.require !== 'undefined') {
    var m = module.require('aurelia-loader-nodejs');
    // ...
}
```

Above, we are explicitly checking that both `typeof module` and `typeof module.require` are defined (i.e. this module is being run under NodeJS or Electron), and only then using `module.require` to load a module. Webpack should allow for usages of module as long as they are wrapped in code that will be stripped out. 

Otherwise platform detection features like the one above will not work with Webpack. :(

**Comment by Vanuan** [comment] 2017-01-14 12:31
Introducing a breaking change (which occurred to be a regression) in the last release candidate...
How is this possible? Do you have any integration tests?

**Comment by sokra** [comment] 2017-01-15 00:27
Thanks for all the feedback. I removed the error message and exports/define is now undefined in ESM. module.exports is read-only and undefined in ESM.
I release another RC tomorrow to let you try this version.

**Comment by SEAPUNK** [comment] 2017-01-15 00:34
Awesome, thank you!

**Comment by mutsys** [comment] 2017-01-15 03:08
Super glad to see that this is going to be fixed fast. I tried out rc4 today and discovered that it chokes hard on anything that TypeScript transpiles to ES6/ES2015. No amount of messing around with the form of the exports from any TypeScript source files made any difference.

**Comment by sokra** [comment] 2017-01-15 16:31
published as v2.2.0-rc.5

https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.5

**Comment by TheLarkInn** [comment] 2017-01-15 16:41
Anyone who can test this newest version, please do :). It's likely our final change needed for release.

**Comment by LukeSheard** [comment] 2017-01-15 16:54
@TheLarkInn Seems to fix the problems with `redux-from` that was coming from `lodash-es` when using Typescript!

**Comment by aitboudad** [comment] 2017-01-15 17:16
now I get the following error `Uncaught ReferenceError: exports is not defined` using Typescript
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    ...
}
```

**Comment by griffinmichl** [comment] 2017-01-15 17:19
All good for me (fixes the redux-form issue)

**Comment by sokra** [comment] 2017-01-15 17:26
@aitboudad Do you have more info? At which line?

**Comment by aitboudad** [comment] 2017-01-15 17:38
![selection_052](https://cloud.githubusercontent.com/assets/1753742/21964709/41292c8e-db49-11e6-8782-50882d837386.png)

I'll try to provide a repro

**Comment by aitboudad** [comment] 2017-01-15 17:47
@sokra you can reproduce it with https://github.com/angular/universal-starter

**Comment by mqklin** [comment] 2017-01-15 18:02
@sokra just created [the smallest demo with react-redux](https://github.com/mqklin/webpack2-rc5-bug)
works nicely with rc3

**Comment by TheLarkInn** [comment] 2017-01-15 18:06
Thanks for the reports, fix is in CI, feel free to test against the commit (if you are really anxious for it :smile: ) while it's being reviewed.

**Comment by todd-richmond** [comment] 2017-01-15 18:25
rc5 fails for me at runtime now instead of compile time with the same "exports is not defined" error as above. I'm using ES6 stage2 - not TS, but with redux-form and its lodash-es dependency

**Comment by phoomparin** [comment] 2017-01-15 18:26
Tested @TheLarkInn's commit, and it perfectly resolves the problem. Thanks a lot!

Before applying #3971: ("exports is not defined" error)
![Before](https://cloud.githubusercontent.com/assets/4714175/21965059/8e5d8338-db8a-11e6-9d62-89f1b94b7296.png)

After applying #3971: (Works perfectly)
![After](https://cloud.githubusercontent.com/assets/4714175/21965066/a9a57aec-db8a-11e6-8b1b-e87f9d698c70.png)

**Comment by aitboudad** [comment] 2017-01-15 18:26
@TheLarkInn  seems working only if I target commonjs `"module": "commonjs",` but with `"module": "es2015"` I get the following issue:
![selection_053](https://cloud.githubusercontent.com/assets/1753742/21965068/00ddb79c-db50-11e6-892c-2b2e1860e25d.png)

**Comment by aitboudad** [comment] 2017-01-15 18:54
I think it's another issue, see for more details https://github.com/webpack/webpack/issues/3972

**Comment by jods4** [comment] 2017-01-15 23:24
I can confirm that the example given by @niieani above (Aurelia loader detecting NodeJS) is fixed by rc5.

**Comment by jouni-kantola** [comment] 2017-01-15 23:27
@TheLarkInn: I tried the fix, and now get the runtime error: `Uncaught TypeError: Cannot set property exports of #<Object> which has only a getter`

As I assume that is the expected error, couldn't a more helpful error message be displayed? I.e.:
`module.exports is readonly when using ES2015 modules. Do not mix import with module.exports.`

**Comment by cesarandreu** [comment] 2017-01-15 23:38
I was still getting some errors, but applying #3971 fixed them.

If you don't want to revert but some third-party dependencies have errors, removing 'module' from your main field might help:

```
{
  resolve: {
    mainFields: ['browser', 'main']
  }
}
```

**Comment by jods4** [comment] 2017-01-16 01:09
I don't know if it's related or not at all but I have a parser plugin for `call A.B`. It worked fine but now that ES modules work, if my code looks like
```js
import { A } from "x";
A.B();
```
Then my plugin code is not called anymore. Whereas this would:
```js
// Assume A is global
A.B();
```

Is that expected or an issue?

**Closed** 2017-01-16 02:47 UTC
Labels: bug, P1: Urgent, S5: Regression, webpack-2, X3: discussion required, X4: work required

**Comment by sokra** [comment] 2017-01-16 05:46
@jods4 this is expected, as the parser (and plugins) only look for "free vars". If A is defined it's not a free var.

**Comment by mutsys** [comment] 2017-01-17 21:04
I tried `webpack@2.2.0-rc.7` last night with `typescript@2.2.0-dev.20170117` and all was well. Issue seems to be resolved for me.

**Comment by mmahalwy** [comment] 2017-01-19 20:06
@todd-richmond was this fixed for you?

**Comment by todd-richmond** [comment] 2017-01-19 22:45
@mmahalwy RC7 and GA both resolved my problems - thx

**Comment by Stenvdb** [comment] 2017-03-15 10:18
@phyllisstein I am getting the same error under the exact same conditions. Were you able to solve this? When I try to use export like so `export * from 'foo';` I am getting the exports is not defined error. Using Webpack 2.2.1.

**Comment by phyllisstein** [comment] 2017-03-15 11:13
@Stenvdb IIRC my diagnosis was similar to yours and I wound up removing that plugin. That said, I spent a few minutes trying to get back into that bad state and could not, with either `babel-plugin-transform-runtime@6.23.0` or `babel-plugin-transform-runtime@7.0.0-alpha.1`.

If I'm reading @sokra's [comment](https://github.com/webpack/webpack/issues/3917#issuecomment-272664147) and [the release notes for `v2.2.0-rc.5`](https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.5) correctly, I should think it's actually no longer possible to hit the exact error I was seeing at the time. But unfortunately I've lost all state on this and can't be as useful as I might like. 😕

**Comment by Stenvdb** [comment] 2017-03-15 11:24
@phyllisstein Thanks for the response, I'm also on 6.23.0, in fact did a global update for all packages. But I'm definitely seeing the same error everybody here is talking about, and it's caused by that `export * from` statement. 

If it helps, I'm quite new to this and I'm working on a tutorial for which you can find the source files here: https://github.com/morkro/tetrys
You see in this file the exact stament you and me had that caused this error: https://github.com/morkro/tetrys/blob/master/src/scripts/store/index.js
That can be of help perhaps to reproduce the error (so, when you use that code but with the `transform-runtime` plugin).

**Comment by phyllisstein** [comment] 2017-03-15 11:57
@Stenvdb Yowza, aside from wanting to gently and lovingly discourage you from spending even another second in that repo, it's hard to know what else to say without seeing the code you're working with. If you want to push that to GitHub I'll happily find a moment to take a look, but I don't have enough to go on from here.

**Comment by Stenvdb** [comment] 2017-03-15 13:03
@phyllisstein Wow thanks. I've uploaded my source files: https://github.com/Stenvdb/redux-test
The babel plugin `transform-runtime` is in comment in `config/webpack.config.js`. If you uncomment that and run again you'll see the error.

The repo mentioned above (tetrys) is just some source files for this tutorial btw https://www.sitepoint.com/redux-without-react-state-management-vanilla-javascript/

**Comment by phyllisstein** [comment] 2017-03-17 15:49
@Stenvdb Didn't want to keep polluting this issue; see my PR at <https://github.com/Stenvdb/redux-test/pull/1>. ✨

**Comment by Apidcloud** [comment] 2017-05-30 15:32
Any news on this? I'm also getting the same error when using babel's `transform-runtime`.

**Comment by marlonmarcello** [comment] 2018-02-01 17:45
I think I have the most simple set up and I'm still getting this error.
```
//package.json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "webpack": "^3.10.0"
  }
```
```
//webpack.config.js
module.exports = {
  target: 'web',
  entry: "./src/es6/wtc-swearjar.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: 'bundle.js
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: "babel-loader",
        options: {
          presets: ["env"]
        }
      }
    ]
  }
}
```
