### ISSUE TITLE
Webpack 5: Cache is not shared effectivly between compilations with configurations where only entry differs

### ISSUE THREAD

**Issue by SkReD** [webpack/webpack#13570] opened 2021-06-15 08:25 UTC
# Bug report

**What is the current behavior?**
Assume we have two projects with only index.js files in them, which are having same content:
![image](https://user-images.githubusercontent.com/938036/122017048-4c2c6d80-cdca-11eb-909a-6f0acbb36152.png)

and this webpack config:
```
module.exports = {
  mode: 'production',
  cache: {
    type: 'filesystem'
  },
  infrastructureLogging: {
    level: 'info',
    debug: /webpack\.cache.*/,
  },
  entry: `./${process.env.SRC_DIR}/index.js`,
  plugins: [
    new MiniCssExtractPlugin({ filename:'styles.[chunkhash].css' })
  ],
  output: {
    pathinfo: false,
  },
  module: {
    rules: [{
      test: /\.(js|jsx)$/,
      loader: 'babel-loader',
      options: {
        "plugins": [
          "syntax-dynamic-import",
          "@babel/plugin-proposal-class-properties"
        ],
        "presets": [
            [
                "@babel/preset-env",
                {
                    "modules": false
                }
            ],
            "@babel/preset-react"
        ]
      }
    }]
  },

  optimization: {
    minimizer: [new TerserPlugin({

    })],
  }
}
```
After cache warmup with `webpack5-1` repo we build first `webpack5-1` and then - `webpack5-2`

warmup time:
```
webpack 5 - 1 (warmup) : 5.05401289999485 seconds
```

Full compilation time with cache is then following:
```
webpack 5 - 1: 0.8312232999801635 seconds
webpack 5 - 2: 1.4813145999908448 seconds
```

After that, if we not delete `.cache` folder and again build  `webpack5-1` and then - `webpack5-2` then builds aree took almost the same time
```
webpack 5 - 1: 0.8569822000265122 seconds
webpack 5 - 2: 0.9038357999920845 seconds
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproducing steps in readme section of repo https://github.com/SkReD/webpack5-performance-issue/tree/cache-share-problem

**What is the expected behavior?**
Expect compilation time to be almost the same for both `webpack5-1` and `webpack5-2` with cache from the first one.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 14.17.0
Operating System: windows 10 x64
Additional tools:

**Comment by alexander-akait** [comment] 2021-06-15 11:52
Duplicate of https://github.com/webpack/webpack/issues/10400, unfortunately shared cache is not supported right now

**Closed by alexander-akait** 2021-06-15 11:52 UTC

**Comment by SkReD** [comment] 2021-06-15 12:17
> Duplicate of #10400, unfortunately shared cache is not supported right now
Cant see how its relative because in my case all modules except entry are in one place (root node_modules folder) so even absolute paths should be valid across compilations

**Comment by alexander-akait** [comment] 2021-06-15 12:23
@SkReD yes, but you have different `package.json`, we keep it too in cache for resolutions purposes
