### ISSUE TITLE
You may need an appropriate loader to handle this file type - when ES6 classes contain public or private field declarations

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#10216] opened 2020-01-05 13:27 UTC
**What is the current behavior?**
When using public/private field declarations in an es6 class. Webpack fails to bundle with the below error

```
ERROR in ./index.js 2:9
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class Rectangle {
>   height = 0;
|   width;
| 


ERROR in ./index.js 10:2
Module parse failed: Unexpected character '#' (10:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class RectangleP {
>   #height = 0;
|   #width;
|   constructor(height, width) {
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**index.js**
```js
class Rectangle {
  height = 0;
  width;

  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}

class RectangleP {
  #height = 0;
  #width;
  constructor(height, width) {
    this.#height = height;
    this.#width = width;
  }
}
```

**webpack.config.js**
```js
const { resolve } = require('path');

module.exports = {
    entry: './index.js',
    output: {
      path: resolve(__dirname, 'dist'),
      filename: '[name].js'
    },
    resolve: {
        extensions: [ '.js' ]
    }
}
```

**What is the expected behavior?**
Code gets bundled. 

**Other relevant information:**
webpack version:  4.41.5
Node.js version: v12.12.0
Operating System: macOS Catalina
Additional tools:

**Comment by MarkH817** [comment] 2020-01-05 14:27
https://github.com/tc39/proposal-class-fields
Class fields syntax is currently at stage 3, so you may need to transpile it using `babel`.

You'd need to add this plugin to your babel config: https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

**Comment by alan-agius4** [comment] 2020-01-05 14:58
In my case I don’t want to downlevel since node 12 target does accept these fields are available natively

**Comment by sokra** [comment] 2020-01-05 20:42
We are using acorn (https://github.com/acornjs/acorn) as parser and it only support stage 4 proposals.

**Comment by inoyakaigor** [comment] 2020-01-09 16:09
@sokra is there a way to skip parse a code? I think my problem #10227 is the same.

**Comment by sokra** [comment] 2020-01-11 16:05
yep with the `module.noParse` option, but this also disables `import/export` in your code, so probably doesn't make sense.

Maybe using https://github.com/acornjs/acorn-stage3 in webpack makes sense, at least opt-in.

**Comment by sokra** [comment] 2020-01-11 16:07
Or the ability to add acorn plugins

**Comment by dominiklessel** [comment] 2020-01-21 15:40
> yep with the `module.noParse` option, but this also disables `import/export` in your code, so probably doesn't make sense.
> 
> Maybe using https://github.com/acornjs/acorn-stage3 in webpack makes sense, at least opt-in.

This would be perfect. This little problem also breaks: -> https://github.com/zeit/ncc/issues/499

Personally I could just stay aways from public or private field declarations, but some of my dependencies (namely hapi.js) are already using it …

**Comment by mheiber** [comment] 2020-02-14 16:08
https://github.com/acornjs/acorn/issues/830 this seems to be the acorn issue

**Comment by noinkling** [comment] 2020-02-23 10:23
> Maybe using https://github.com/acornjs/acorn-stage3 in webpack makes sense, at least opt-in.

> Or the ability to add acorn plugins

Yes please. I've been bitten by this at least a few times now, because I always forget that just because Babel can parse something, it doesn't mean Webpack can (why don't you guys use the same parser again?).

In the relevant case my process went something like this:

1. Notice that my installed version of Chrome supports class fields now.
2. Smartly replace `plugin-proposal-class-properties` with `plugin-syntax-class-properties` in my Babel dev config, since I know the proposal is stage 3, meaning the Babel parser will need the syntax plugin to parse it.
3. Get a parsing error.
4. Spend a while wondering how that can possibly be and trying to debug my Babel config.
5. Finally realise I'm looking at a Webpack/Acorn error not a Babel one (mostly my fault, but it's not exactly clear at a glance).
6. Revert.
7. Vow never to make the same mistake.

**Comment by evilebottnawi** [comment] 2020-02-25 10:43
I think it can be solved in a more comfortable way:
- Allow to set plugins for acorn (first PR)
- Resolved minimum supported node using `browserslist`/`package.json` and setup plugins by default (second PR)

**Comment by wycats** [comment] 2020-05-08 15:26
Is there any progress on this feature? I hit this problem today. One reason to want to use native private fields is that the debugging experience of transpiled private fields is pretty painful.

**Comment by evilebottnawi** [comment] 2020-05-08 15:43
@wycats no, feel free to send a PR, it should be easy

**Comment by mforman1** [comment] 2020-06-11 10:50
Acorn released today a new version that supports optional chaining.

**Comment by OnurGvnc** [comment] 2020-07-03 07:45
as a temporary solution;
https://github.com/OnurGvnc/acorn-with-stage3

`package.json`:

```json
{
  ...
  "resolutions": {
    "acorn": "npm:acorn-with-stage3"
  },
  "dependencies": {

```

**Comment by lostpebble** [comment] 2020-09-18 10:38
Just ran into this today, which was strange because I never had the issue before. Turns out my current babel config was missing a plugin I had been using over the past couple years but forgot to copy over. I added that back in and it worked again.

So as another temp fix, add this to your babel config, inside `plugins: []`

```
["@babel/plugin-proposal-class-properties", { loose: true }],
```

**Comment by tobiu** [comment] 2020-09-30 11:58
I need public class fields as well for the neo.mjs framework.

In general, we should re-think the approach to only add stage 4 proposals. While this was fine 1-2 years ago, these days most browser engines already implement the important stage 3 ones.

Let's take a look at public class fields:
![Screenshot 2020-09-30 at 13 37 37](https://user-images.githubusercontent.com/1177434/94680700-7e706a80-0322-11eb-8dea-7f18cd7c666a.png)

At this point, even Opera & Safari support them.

For neo.mjs, there is a design goal to use code which runs directly in all major browsers, resulting in not using Babel at all.

Without the ability to specify acorn plugins as webpack configs, I can not add class fields into the code base, since it breaks the dist builds.

I did try @OnurGvnc 's workaround. While this might work for yarn (not tested), it did not work for me using npm.

In short: https://github.com/rogeriochaves/npm-force-resolutions is using a preinstall hook, which is already a problem, in case the package-lock.json is included inside the .gitignore. Without this file, the preinstall will break.

Well, I could add it into the repo, but even then it did not work for me. The script itself did adjust the acorn dependencies inside the package-lock correctly, but the following npm install reverted the changes and webpack was using the default acorn package again. Maybe I am missing something.

Right now the only thing I can think of what I could do is to fork webpack and create an own npm package just to change the acorn dependency. This feels wrong on too many levels (starting with new webpack versions).

I am hoping that we can get the public class fields included soon (should be easy => just add the acorn-with-stage3 plugin). In case there are reasonable workarounds, please let me know.

Best regards,
Tobias

**Comment by PeteX** [comment] 2020-10-20 20:48
I managed to make this work but it's a bit of a hack.  First of all, install acorn-class-fields:

```
npm i --save-dev acorn-class-fields
```

Next, put this at the top of `webpack.config.js`:
```
const classFields = require('acorn-class-fields');
const acorn = require('acorn');
acorn.Parser = acorn.Parser.extend(classFields);
```
It's important to put this block before you `require` anything to do with webpack.  If you put it further down in the file, webpack will already have created the parser and it won't work.

**Comment by tobiu** [comment] 2020-10-21 11:48
Hi @PeteX,

thanks for your input. I tested this approach and it did not work for me.
I added the changes into the 8 relevant webpack configs and added one public class field into the button class:

https://github.com/neomjs/neo/commit/1d6303c4b654254232b3fec60d611dd125bb51cc

The result is unfortunately still the same:
<img width="1338" alt="Screenshot 2020-10-21 at 13 41 56" src="https://user-images.githubusercontent.com/1177434/96715405-cde70b00-13a3-11eb-9676-5fe02f44d2a1.png">

Am I missing something?

I put the code into a separate testing branch, e.g.:
https://github.com/neomjs/neo/blob/class-fields/buildScripts/webpack/development/webpack.config.appworker.js

I am out of ideas =/

Best regards,
Tobias

**Comment by PeteX** [comment] 2020-10-21 12:55
I don't know why it's working differently for you, @tobiu, sorry.  I'm using private fields via Typescript and webpack 5, so my setup is quite different.  It might be worth poking around in the source for webpack to see when the parser actually gets created.  That's the problem I had at first, the patch was applied too late so webpack already had its parser.

I notice you've got acorn in your package.json.  I'm not sure how npm deals with the case where the same package is requested multiple times with different constraints (so in your case, your own package.json and also webpack's package.json).  It might be that you get the package twice and so you end up patching the wrong one.

**Comment by Buntelrus** [comment] 2020-10-22 16:30
> as a temporary solution;
> https://github.com/OnurGvnc/acorn-with-stage3
> 
> `package.json`:
> 
> ```json
> {
>   ...
>   "resolutions": {
>     "acorn": "npm:acorn-with-stage3"
>   },
>   "dependencies": {
> ```

@tobiu @PeteX The quoted solution from @OnurGvnc works perfectly fine for me. I recommend using yarn as package manager. Add the resolutions entry to _package.json_ and run `yarn install`

**Comment by tobiu** [comment] 2020-10-22 21:17
@Buntelrus If I would create an app, it would do this right away.

The thing with creating an UI framework: it has to run for every dev who wants to use it.
This gets especially tricky in case you create an app via "npx neo-app":

https://github.com/neomjs/create-app

I did not dive deep into yarn yet, but I doubt we can use it for npx calls.

Best regards,
Tobias

**Comment by finngl** [comment] 2020-10-30 15:24
The fix @PeteX worked for me :-)

**Comment by franktopel** [comment] 2020-11-13 08:37
> We are using acorn (https://github.com/acornjs/acorn) as parser and it only support stage 4 proposals.

Acorn supports class fields via a plugin: https://github.com/acornjs/acorn-class-fields

**Comment by JannikZed** [comment] 2021-01-03 12:30
it is amazing, that this issue still persists and nothing seems to work .. at least for me.

**Comment by alexander-akait** [comment] 2021-01-03 13:08
@JannikZed please update webpack to latest version

**Comment by franktopel** [comment] 2021-01-03 13:11
@alexander-akait Your comment suggests that this has been fixed. Why, then, is this issue still open?

**Comment by alexander-akait** [comment] 2021-01-03 13:27
For future improvements like https://github.com/webpack/webpack/issues/10216#issuecomment-590803357, but it is low priority

**Comment by thedriveman** [comment] 2021-01-03 17:10
@alexander-akait Sorry, but I'm confused - Webpack 5.11.1 doesn't seem to support this out of the box; is there a specific temporary solution or am I missing something?

**Comment by alexander-akait** [comment] 2021-01-03 17:13
You can setup babel loader for new syntax (not in Stage 4)

**Comment by thedriveman** [comment] 2021-01-03 17:16
@alexander-akait Thanks, I'm aware to this option, however I believe that this issue revolved around Webpack's ability to parse class fields without transpilation.

**Comment by PeteX** [comment] 2021-01-03 17:49
@alexander-akait the problem for me is that during debugging it's helpful if the private fields are preserved in the generated Javascript.  If this is not done, it's very difficult to inspect private fields in the developer tools.

The workaround I described above still works, but I'm aware that it doesn't work for at least some other people, for reasons that are unclear.

**Comment by thedriveman** [comment] 2021-01-04 00:40
> I managed to make this work but it's a bit of a hack. First of all, install acorn-class-fields:
> 
> ```
> npm i --save-dev acorn-class-fields
> ```
> 
> Next, put this at the top of `webpack.config.js`:
> 
> ```
> const classFields = require('acorn-class-fields');
> const acorn = require('acorn');
> acorn.Parser = acorn.Parser.extend(classFields);
> ```
> 
> It's important to put this block before you `require` anything to do with webpack. If you put it further down in the file, webpack will already have created the parser and it won't work.

@PeteX, @tobiu: I got this solution to work (with Webpack 5.11.1), however it didn't work before I added acorn (currently 8.0.4) as a development dependency to the root of my project. @PeteX, thank you for this suggestion - it will hold well till official support becomes available.

**Comment by martinjlowm** [comment] 2021-02-20 15:14
Just sharing my findings here. I couldn't get the monkey patch to work as the parser is assigned to a variable in Webpack (4.46.0) before the config is loaded: https://github.com/webpack/webpack/blob/v4.46.0/lib/Parser.js#L16. A workaround is to do the patching prior to running Webpack through requiring using `NODE_OPTIONS`, e.g. `NODE_OPTIONS="-r extend-acorn.js" npx webpack` with the content proposed in the previous replies. In case you spin up child Node processes, you can unset NODE_OPTIONS again in the script.

Unfortunately, I had other plugins depending on older versions of acorn, so I went ahead and transpiled the code using Babel and https://babeljs.io/docs/en/babel-preset-env#shippedproposals instead.

**Comment by NathanaelA** [comment] 2021-04-24 19:45
FYI: This is now fixed in at least the current version of Webpack 5.35.1, the underlying acorn parser was recently upgraded to 8.2.x which adds Private/public fields to the parser, and webpack 5 is already set to pull the newest 8.x acorn parser.    As long as your `ecmaVersion` is set to `13` or `latest` (which `latest` appears to be default) then class fields should work.

---

I tested by: (Created new test folder and moved to it)
1. `npm i  webpack@latest`    (Installed 5.35.1)
2. (manually checked node_modules/acorn/package.json -- verified it was >= 8.2.1)
3. Copied the webpack.config.js & index.js file from first issue and added to the bottom of the index.js file:
(Otherwise webpack will actually strip it out. because it isn't used.  :-D )
```
let x = new Rectangle(1,1);
let y = new RectangleP(1,1);
console.log(x,y);
```
4. `webpack`
5. `cd dist`      (Manually looked at output  main.js file and verify it was correct)
6.  `node main`
Output (as expected) was:
![image](https://user-images.githubusercontent.com/850871/115970964-7b7dd700-a50b-11eb-9364-fc3ba6bf01f5.png)

**Comment by tobiu** [comment] 2021-04-25 08:50
Hi @NathanaelA,

just tested this and it does look really good!

![Screenshot 2021-04-25 at 10 27 11](https://user-images.githubusercontent.com/1177434/115987125-00243000-a5b4-11eb-8e08-2ad2fa4050d4.png)

![Screenshot 2021-04-25 at 10 22 42](https://user-images.githubusercontent.com/1177434/115987130-03b7b700-a5b4-11eb-8e9b-73d46f65068e.png)

![Screenshot 2021-04-25 at 10 25 50](https://user-images.githubusercontent.com/1177434/115987135-07e3d480-a5b4-11eb-8ff2-92f2b22f2880.png)

**Comment by muzuiget** [comment] 2021-04-25 09:24
I remove the dependency package `@babel/plugin-proposal-class-properties` in my program then re-pack with latest webpack, my program throw a `XXX is not defined` error.

Here is a minimal code to reproduce the bug:

```
muzuiget:~/test$ cat src/lib.js 
export default {
    name: 'hello',
};
muzuiget:~/test$ cat src/index.js 
import lib from './lib';
class Hello {
    run1() {
        console.log(lib);
    }
    run2 = () => {
        console.log(lib);
    }
}
const hello = new Hello();
hello.run1(); // OK
hello.run2(); // ReferenceError: lib is not defined

```

```
$ node dist/main.js 
{ name: 'hello' }
/home/muzuiget/test/dist/main.js:1
(()=>{"use strict";const n={name:"hello"},l=new class{run1(){console.log(n)}run2=()=>{console.log(lib)}};l.run1(),l.run2()})();
                                                                                                  ^

ReferenceError: lib is not defined
```

**Comment by tobiu** [comment] 2021-04-25 10:27
off topic: i would not recommend using public class fields to define methods.

fields get assigned inside the ctor on instance level and methods belong to the prototype (unless you want to duplicate them for each instance).

**Comment by muzuiget** [comment] 2021-04-25 11:37
This usually use for callback, auto bind the `this` to current instance, this is recommend way on React https://reactjs.org/docs/handling-events.html

**Comment by NathanaelA** [comment] 2021-04-25 17:39
@muzuiget - I'm going to say this is probably a bug in webpack, if you turn off optimization  (`optimization: {minimize: false}`).   in the webpack config you can see webpack thinks the two `lib` values are different variables.  (Hence the output you get above, where one is rewritten properly and the other left as-is)

Interestingly enough if you use `require` instead of `import`, or `const lib = {name: 'hello'};` and remove the `import` it parses everything correctly, only if you use a `import` statement does it think the `lib` value is different.

**Comment by alexander-akait** [comment] 2021-04-26 13:21
@NathanaelA Can you provide example? Yep, it may be bug

**Comment by NathanaelA** [comment] 2021-04-26 13:59
Here is the demo I used from muzuiget -- @alexander-akait  

Webpack.config.js  (Same as first issue, but added disabling minimizing).
```
const { resolve } = require('path');

module.exports = {
    entry: './index.js',
    output: {
      path: resolve(__dirname, 'dist'),
      filename: '[name].js'
    },
    resolve: {
        extensions: [ '.js' ]
    },
    optimization: {minimize: false}
}
```

lib.js
```
export default {
    name: 'hello',
};
```

index.js
```
import lib from './lib';    // This one fails
// const lib = require("./lib"); // This works if un-commented

class Hello {
    run1() {
        console.log(lib);
    }
    run2 = () => {
        console.log(lib);
    }
}
const hello = new Hello();
hello.run1(); // OK
hello.run2(); // ReferenceError: lib is not defined
```

**Comment by sokra** [comment] 2021-04-26 14:27
Since this reached stage 4 only recently and acorn added this only 2 days ago, we need also need to add this to webpack parser to be able to handle webpack constructs in the new syntax (e. g. imports)

**Comment by r002** [comment] 2021-05-11 14:49
I was previously using `"webpack": "^5.24.2"` and encountered this same problem this morning:

![image](https://user-images.githubusercontent.com/45280066/117835174-c571f700-b245-11eb-86c0-fc3b812cbb6a.png)

But as soon as I updated to `"webpack": "^5.35.1"`, Webpack is happy again! 😁

![image](https://user-images.githubusercontent.com/45280066/117835248-d3277c80-b245-11eb-903b-8a66ce360644.png)

Thank you for fixing this!!!  🙏🙏🙏

PS. As a side-note-- So basically, JS has become the `"Everything Language"` at this point?  I honestly didn't even know that private class vars had come to JS until this morning... what a world!  I've been recently working in `Go` (where there are no classes!  Structs here!  Structs there!  Structs everywhere!) so returning to JS recently is kinda like returning to America... a place of [radical freedom](https://existentialcomics.com/comic/35) where everything/anything goes!! 😮

**Comment by alexander-akait** [comment] 2021-05-11 15:07
@r002 Can you update webpack? https://github.com/tc39/proposals/blob/master/finished-proposals.md `Class Fields` on stage 4 and acorn should parse them

**Comment by r002** [comment] 2021-05-11 15:13
> @r002 Can you update webpack? https://github.com/tc39/proposals/blob/master/finished-proposals.md `Class Fields` on stage 4 and acorn should parse them

@alexander-akait Yes, I updated Webpack and that solved the problem!  I was just confirming with you guys that everything's copacetic now-- thank you for updating Webpack to support the new spec!  🙏🙏🙏

**Comment by alexander-akait** [comment] 2021-05-11 15:23
I think we can close it, idea from https://github.com/webpack/webpack/issues/10216#issuecomment-590803357

> Allow to set plugins for acorn (first PR)
> Resolved minimum supported node using browserslist/package.json and setup plugins by default (second PR)

Is not easy, the main problem here - handling new AST nodes, it requires many changes, including parser/plugins for optimizations/etc. Even we allow setup plugins it can still potentially break your code or behave unpredictably. So webpack supports only stage 4, when new syntax will be part of stage 4 webpack will support it. 

Anyway feel free to open new issues when something will be in stage 4, and yes, we are watching this too.

**Closed by alexander-akait** 2021-05-11 15:23 UTC
Labels: Send a PR
