### ISSUE TITLE
Object.assign used when importing json in development mode.

### ISSUE THREAD

**Issue by chaoyzeng** [webpack/webpack#7162] opened 2018-05-01 01:04 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In 'development' mode, importing JSON files generate `Object.assign` in the resulting bundle.

An example of this looks like: `Object.assign({}, _test__WEBPACK_IMPORTED_MODULE_1__, {\"default\": _test__WEBPACK_IMPORTED_MODULE_1__})`

This means that in development mode the resulting bundle does not work with IE (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility)

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a sample repo to reproduce the issue: https://github.com/chaoyzeng/webpack-4-object-assign

You can check for the use of `Object.assign` in the resulting dev build bundle. Note that production mode does not use `Object.assign`

**What is the expected behavior?**

Don't use `Object.assign`, not sure what is the reasoning behind using it in the first place.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack version is 4.6.0

**Comment by evilebottnawi** [comment] 2018-05-02 11:49
сс @sokra looks like important bug

**Comment by anthonyhastings** [comment] 2018-05-11 22:08
Can confirm I've been bit by this issue also; any JSON file that I load gets wrapped in `Object.assign` calls which break in IE11 or older browsers. For me, it was our CI server that noticed the issue first, as our integration tests run on an old version of webkit which, like IE11, seems to have issues with `Object.assign`.

**Comment by anthonyhastings** [comment] 2018-05-24 07:50
I realised when I confirmed @chaoyzeng's bug report, I didn't actually test production builds like he mentioned. I can confirm now that production builds do not use `Object.assign`; only development builds. As my CI runs development builds, I eagerly await the fix for this! 😆

**Closed** 2018-05-29 13:39 UTC
Labels: bug
