### ISSUE TITLE
Specifying `output.filename` disables auto-minify in production mode

### ISSUE THREAD

**Issue by AndyBarron** [webpack/webpack#6732] opened 2018-03-12 17:52 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Specifying `output.filename` in `webpack.config.js` disables output minification in production mode. When commenting out that single line of config, it works as intended.

**If the current behavior is a bug, please provide the steps to reproduce.**
Specify `output: { filename: 'foo.js' } }` and `mode: 'production'` in Webpack config and run `webpack` CLI

**What is the expected behavior?**
Always minify the output bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node 8.9.4, Webpack 4.1.1, macOS 10.12.6

**Comment by chengluyu** [comment] 2018-03-13 07:52
Cannot reproduce with Node v8.9.4 and webpack 4.1.1. Could you attach an example?

**Comment by sokra** [comment] 2018-03-13 08:42
I don't think this is a bug, but a user error instead.

**Comment by AndyBarron** [comment] 2018-03-13 08:48
I am able to reproduce this consistently by un-commenting the file name
line. That said, the file name did have a query string attached to it for
cache busting. I'll try removing that when I get a chance. (I would still
consider that a bug, but I have no idea if that is actually the issue.)

This is a private repository, but I will see if I can assemble a minimal
example as well.

**Comment by sokra** [comment] 2018-03-13 16:10
fixed in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/251

**Closed by sokra** 2018-03-13 16:10 UTC
