### ISSUE TITLE
Add option for webpack watch to detect any new file underneath a specific directory (including in subdirectories) 

### ISSUE THREAD

**Issue by CalculonPrime** [webpack/webpack#16264] opened 2022-09-17 14:42 UTC
## Feature request

**What is the expected behavior?**
If you do "webpack --watch" it's currently only detecting and recompiling when existing files are changed.

**What is motivation or use case for adding/changing the behavior?**
I want to be able to drop new jsx files into the source directory tree, and have them automatically be compiled into the output tree.

**How should this be implemented in your opinion?**
Every directory and subdirectory would have to be watched for new files (in addition to current behavior).  The new feature doesn't necessarily need to support files in new directories that are created after webpack is launched, if that's harder (it probably is).

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment] 2022-09-19 14:13
Duplicate of https://github.com/webpack/webpack/issues/13537, anyway you can use https://webpack.js.org/configuration/dev-server/#devserverwatchfiles for dev server if you use it

**Closed by alexander-akait** 2022-09-19 14:13 UTC

**Comment by CalculonPrime** [comment] 2022-09-19 20:03
I'm not using the dev server in this case.  I posted to the thread you said was a duplicate asking some questions, but there was no response, and that thread appears to be getting closed repeatedly due to inactivity and has to be reopened.

**Comment by CalculonPrime** [comment] 2022-09-19 23:49
Don't there have to be code changes associated with an issue to do a PR?  From what I can tell, no changes have been committed.

**Comment by alexander-akait** [comment] 2022-09-22 22:12
You can send a PR with the new improvement
