### ISSUE TITLE
Webpack 5 creates chunks even though maxChunks set to 1 only with 2 JS entry points

### ISSUE THREAD

**Issue by emkayy** [webpack/webpack#12464] opened 2021-01-20 18:39 UTC
# Bug report
**What is the current behavior?**
When I have one entry point for a JS file, everything is fine. However, as soon as I add another entry point including a JS file (e.g. LESS file entry points won't change anything), webpack creates a chunk file (like `123.bundle.js`), even though I set the `LimitChunkCountPlugin` `maxChunks` to 1. There are no common modules in these 2 entry points and no async imports.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
module.exports = {
    mode: isProd ? 'production' : 'development',

    devServer: {
        publicPath: '/', // webpack bug, should default to '/'
        contentBase: path.join(__dirname, 'build'),
    },

    entry: {
        public: [ src('js/public.js'), src('less/public.less') ],
        video: [ src('less/video.less'), src('js/player.js') ], // adding this js is causing 'public' to code split
        application: src('less/application.less'),
    },

    output: {
        path: path.resolve(__dirname, 'build/'),
        filename: 'js/[name].bundle.js'
    },

    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                options: { presets: [ [ "@babel/preset-env", { "useBuiltIns": "usage", "corejs": 3, } ] ] }
            }
        },
        {
            test: /\.less$/,
            use: [
                MiniCssExtractPlugin.loader,
                'css-loader',
                { loader: 'postcss-loader', options: { plugins: () => isProd ? [autoprefixer(), cssnano()] : [] } },
                'less-loader'
            ]
        },
        { test: /\.eot$/, loader: 'ignore-loader' }
    ]
    },

    plugins: [
        new webpack.optimize.LimitChunkCountPlugin({
            maxChunks: 1
        }),

        new MiniCssExtractPlugin({
            filename: 'css/[name].bundle.css',
            chunkFilename: '[name].css',
        })
    ]
};
```

**What is the expected behavior?**
It's expected to not create any chunks since maxChunks is set to 1.
Also I would expect it to behave consistently, no matter if I have one or many entry points.

**Other relevant information:**
webpack version: 5.10.3
Node.js version: v12.15.0
Operating System: Win7

**Comment by alexander-akait** [comment] 2021-01-21 10:38
Duplicate of https://github.com/webpack/webpack/issues/11671

**Closed by alexander-akait** 2021-01-21 10:38 UTC

**Comment by emkayy** [comment] 2021-01-21 11:33
@alexander-akait Sorry, but this is not a duplicate!
#11671 is about empty JS files for CSS entry points!
This here is something completely different!
Please read carefully before closing.
It's about actual chunks being created despite setting `maxChunks: 1`.
It has nothing to do with #11671!
Please reopen!

**Comment by alexander-akait** [comment] 2021-01-21 11:36
`application: src('less/application.less'),`, always create extra one js file, and `maxChunks` doesn't have effect here

**Comment by alexander-akait** [comment] 2021-01-21 11:43
Also you use https://webpack.js.org/concepts/entry-points/#multi-page-application, so each `entry` will create separate chunk, it is limitation and `maxChunks` will not work in this scenario

**Comment by emkayy** [comment] 2021-01-21 12:02
Yes, but that's not the point!
It's clear that the "application" entry point will create a JS file. But that's not what I'm talking about!
The "public" endpoint gets split into 123.bundle.js and public.bundle.js as soon as I add the "video" endpoint, as mentioned in the code example.
So in this example here, 3 endpoints, 4 JS files!

**Comment by alexander-akait** [comment] 2021-01-21 12:11
What you wrote in the title and what you say are completely different things and please change your tone.

**Comment by alexander-akait** [comment] 2021-01-21 12:13
Again `maxChunks` doesn't make sense using multi page application

**Comment by emkayy** [comment] 2021-01-21 12:55
Sorry, in my opinion, the title and content matches. I wouldn't know how to phrase it in another way!?

So I'll try to explain differently:
I have 2 JS entry points and I want 2 Javascript files. But I am getting 3.
However, If I have just one JS entry point, I get just one JS file -> as expected.
This is the case with both entry points ("public" and "video).

It seems like webpack puts node modules in this extra chunk - for both entry points in one file. Which makes no sense because they don't share any node modules. So A LOT of modules would have to be loaded even though they are not needed for either one entry point.

I hope it's a bit clearer now

**Comment by alexander-akait** [comment] 2021-01-21 13:01
From here https://webpack.js.org/concepts/entry-points/

> Why? In a multi-page application, the server is going to fetch a new HTML document for you. The page reloads this new document and assets are redownloaded. However, this gives us the unique opportunity to do things like using optimization.splitChunks to create bundles of shared application code between each page. Multi-page applications that reuse a lot of code/modules between entry points can greatly benefit from these techniques, as the number of entry points increases.

`splitChunks` automatically move vendor deps to extra chunk in production, because it was rare invalidates and this is recommended, you can disable it, but again, **it is not recommended**, webpack does a lot of things for you and does it very well, changing them can lead to sad things for performance

**Comment by emkayy** [comment] 2021-01-21 14:24
Exactly that's the point. I want to disable it but it doesn't work. And I want to disable it, because in my use case the current behaviour results in sad things for performance in 99% of the cases. Which is that either one JS file has to load all the node modules of the other JS file even though it's not being used.

You say I can disable it but `maxChunks` gets ignored, I tried several settings in `splitChunks` like `cacheGroups: { default: false }`, setting a `minSize` of 50 MB. None of it takes effect. Hence the bug report

https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroups

**Comment by alexander-akait** [comment] 2021-01-21 14:31
`splitChunks: false`

**Comment by emkayy** [comment] 2021-01-21 14:44
Also doesn't work.
If it's supposed to work and just a bug, please add it to the documentation because it says 
**`optimization.splitChunks`**
`object`

**Comment by alexander-akait** [comment] 2021-01-21 14:47
Please create reproducible test repo

**Comment by emkayy** [comment] 2021-01-21 21:02
Here you go: https://github.com/emkayy/webpack-chunks-bug
Hope it helps!
If three is anything else I can do, please let me know!

**Comment by alexander-akait** [comment] 2021-01-22 12:26
You use `require` with callback, it's kind of analogous `await import('module')`, that's why you get this effect, rewrite it on sync `import`/`require`, chunks are async

**Comment by emkayy** [comment] 2021-01-22 17:47
Well, but if I have only one entry point it works. And as you said, I should be able to disable splitChunks entirely.
But with 2 entry points it suddenly ignores the configuration.
Could you please fix it so it is working consistently according to the configuration?

**Comment by alexander-akait** [comment] 2021-01-25 10:47
@emkayy 

> Well, but if I have only one entry point it works. And as you said, I should be able to disable splitChunks entirely.

Because you have two async imports and we don't know how you will inject them, maybe on different pages, maybe on one pages, your config is anti-pattern, I strongly recommend don't do it, you will constantly receive unnecessary invalidations. Do not use aync loading if you don't need to be async

**Comment by emkayy** [comment] 2021-01-25 14:11
It's a migrated project from grunt with requirejs optimizer - so no async and also all packed in one bundle.
And also in webpack it's working if you only have one entry point. This far everything is working as described in the documentation.

> Because you have two async imports and we don't know how you will inject them, maybe on different pages, maybe on one pages
- Exactly, but I know and that's why I configured it to not create any additional chunks / load any modules async. If webpack stuck to the config, everything would be fine.

But as soon as you add the 2nd entry point it doesn't work anymore as described in the webpack docs. The config `maxChunks: 1` means one file, not 2 or any other number of files. But it just gets ignored. Just as other `splitChunks` options.

The two entry points do not share any modules, yet their modules get all bundled into on shared file. This is what creates the biggest performance issue.

So clearly, something is not working as it should.

Not all environments are suitable for this kind of dynamic chunk creation and invalidation is not really a concern in this use case.
It should be possible to control the behaviour of webpack. But in this case it's not possible.

**Comment by alexander-akait** [comment] 2021-01-25 14:47
Duplicate https://github.com/LLGZONE/limitchunkplugin-demo, yep bug

**Comment by emkayy** [comment] 2021-01-27 10:03
Ok, is there a github issue for that so I can track it?

**Comment by alexander-akait** [comment] 2021-01-27 10:34
Yes

**Comment by emkayy** [comment] 2021-01-27 11:26
Could you please link it or put it here in the comments?

**Comment by alexander-akait** [comment] 2021-01-27 11:29
oh, sorry, my mistake, wrong link, here the issue https://github.com/webpack/webpack/issues/11431

**Comment by nl-brett-stime** [comment] 2024-01-26 02:25
How to disable code chunks / splitting in Webpack 5... Use the `output` section of the config, not the `optimization` section:

```
{
  output: {
    chunkFormat: false
  }
}
```

**Comment by drpotato** [comment] 2024-09-16 23:52
@nl-brett-stime you beautiful human. This is the _actual_ fix!

**Comment by jasonpolites** [comment] 2024-12-29 06:26
```
{
  output: {
    chunkFormat: false
  }
}
```

Did not work for me. I still get chunks (and don't want them)
