### ISSUE TITLE
Bug: Path issue on Windows 7 in absolutePath.js

### ISSUE THREAD

**Issue by jakub2** [webpack/webpack#4552] opened 2017-03-23 12:37 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Webpack is a dependency on [this Angular project](https://github.com/AngularClass/angular2-webpack-starter), and when I attempt to run the project on Windows 7 (this is important as it seems to be a problem on Windows 7 only!), I get the following error message. As it turns out, it is an error in Webpack:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "c:\\web-my\\insurance" is not an absolute path!
 - configuration.output.path: The provided value "c:\\web-my\\insurance\\dist" is not an absolute path!
```
I fixed it quickly by modifying line 20 in schemas\ajv.absolutePath.js from:
`const passes = expected === /^(?:[A-Z]:\\|\/)/.test(data);`
to:
`const passes = expected === /^(?:[A-Za-z]:\\|\/)/.test(data);`
I am not sure if this is the best solution, though.

**If the current behavior is a bug, please provide the steps to reproduce.**
Checkout the angular project at https://github.com/AngularClass/angular2-webpack-starter and attempt to run in on Windows 7. Then see your console.

**What is the expected behavior?**
No errors. The paths should work, even on Windows 7.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
The error occurs on Windows 7 (this is probably the key information), node v6.9.2, npm v4.0.5, webpack 2.3.1.

**Comment by timse** [comment] 2017-03-23 12:51
duplicate of #4530

**Closed** 2017-03-23 12:51 UTC
