### ISSUE TITLE
Drop use of peerDependencies

### ISSUE THREAD

**Issue by jupl** [webpack/webpack#570] opened 2014-11-05 02:33 UTC
With peerDependencies appearing to be deprecated/dropped, it should probably be discouraged to use now. (https://webpack.github.io/docs/how-to-write-a-loader.html#use-a-library-as-peerdependencies-when-they-wrap-it) `npm dedupe` would solve the problem of being able to update/lock version without republishing and plugins should be updated to not use peerDependencies anymore.

**Comment by kentcdodds** [comment] 2015-01-18 03:30
I have the exact same issue as @MoOx. Any idea of how to fix this problem? :-/

**Comment by jhnns** [comment] 2015-01-18 11:34
You need to release an alpha version of your loader which bumps the peerDependency. We're about to use this approach at the [sass-loader](https://github.com/jtangelder/sass-loader).

**Comment by MoOx** [comment] 2015-01-19 14:03
So, the peerDep bring the same issue as normal dep, you need to update the version in the package.json in every case. Looks stupid or I am missing something.

**Comment by jhnns** [comment] 2015-01-20 10:05
According to Semver, a version bump from `0.1.0` to `0.11.0` introduced a breaking change. You're free to choose your favorite version between `0.1.0` and `0.10.0`. After that, it needs to be confirmed from the module author, that everything is working fine (which should be a matter of minutes when you have sufficient tests). If you know a better approach without breaking a lot of CI systems – go ahead :grin:

**Comment by MoOx** [comment] 2015-01-20 13:48
> According to Semver, a version bump from 0.1.0 to 0.11.0 introduced a breaking change

Where do you see that ?

The only thing I see is

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Anyway from my experience peerDep don't really solve anything + it's going to be deprecated so why bother?

**Comment by jhnns** [comment] 2015-01-20 14:12
Well, Semver itself says that `0` is a development release, everything may break. But npm in combination with the `^`-symbol treats [minor version bumps as breaking change](https://github.com/npm/node-semver#caret-ranges-123-025-004) in the development phase.

> Many authors treat a 0.x version as if the x were the major "breaking-change" indicator.

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.

I have to admit that peerDependencies are a bit problematic, but – at least for me – they did solve certain use-cases. I hope, they won't deprecate them (it's just an issue currently).

Without peerDependencies the version of loaders must be **in sync** with the library they provide access to. For instance, when LESS publishes a release, the less-loader needs to publish a release as well.

**Comment by MoOx** [comment] 2015-01-20 14:15
I know that 0.x bump might bring breaking changes.

> Without peerDependencies the version of loaders must be in sync with the library they provide access to. For instance, when LESS publishes a release, the less-loader needs to publish a release as well.

It's true for major release only if you use `^X.y.z`. And it makes totally sense since major changes can break things.

It's why we should use 0.x only for very alpha stuff.

**Comment by bebraw** [comment] 2015-11-13 14:21
Any update now that npm 3 is out?

I know for sure `peerDependencies` are still a valid approach (not deprecated). The major difference is that now it's up to the consumer to maintain the matching dependencies. Earlier the process was automatic (it installed peer deps as well).

**Comment by kentcdodds** [comment] 2015-11-13 14:50
I haven't had any issues with `peerDependencies` ever since I learned of [semver.npmjs.com](http://semver.npmjs.com/) and used it to fine-tune my range. npm 3 has definitely smoothed out rough edges as well.

**Comment by jhnns** [comment] 2015-11-13 18:12
I don't think that the situation has changed. Imho we've made good experiences to use `peerDependencies`

**Comment by bebraw** [comment] 2015-11-15 11:25
@sokra Time to close? I don't think `peerDependencies` are going anywhere.

**Comment by bebraw** [comment] 2016-04-08 07:59
`peerDependencies` are still relevant so closing.

**Closed by bebraw** 2016-04-08 07:59 UTC
Labels: question
