### ISSUE TITLE
webpack-dev-server breaks on changing folder structure or renaming files and requires restart

### ISSUE THREAD

**Issue by ingelity** [webpack/webpack#5523] opened 2017-08-15 14:46 UTC
**Do you want to request a *feature* or report a *bug*?**
In my opinion this is a bug because it was working in older versions of webpack.

**What is the current behavior?**
When I rename some file or change folder structure the webpack starts showing "...Module build failed: Error: ENOENT: no such file or directory,...", and it doesn't recover from that, so I have to restart webpack dev server in order to have the hot reloading working again. The documentation suggests explicitly setting watchOptions but didn't work. Is there some cache invalidation that I have to configure or...?
**If the current behavior is a bug, please provide the steps to reproduce.**
Described above and my webpack dev configuration is:
```
const path = require('path');
const webpack = require('webpack');
const config = require('../config');

module.exports = {
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:9001',
    'webpack/hot/only-dev-server',
    path.join(config.projectPath, 'src', 'reactApp'),
  ],
  output: {
    path: path.join(config.projectPath, 'assets'),
    filename: 'bundle.js',
    publicPath: 'http://localhost:9001/',
  },
  devtool: 'cheap-module-eval-source-map',
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin({
      __DEV__: true,
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
    new webpack.ProvidePlugin({ Promise: 'bluebird' }),
  ],
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  module: {
    noParse: /node_modules\/aws-sdk\/dist\/aws-sdk/,
    rules: [...],
  },
};
```
And my server.js file:
```
const devServer = new WebpackDevServer(webpack(webpackConfig), {
  hot: true,
  watchOptions: { poll: true },
  host: 'localhost',
  port: 9001,
  publicPath: 'http://localhost:9001/',
  compress: true,
  noInfo: true,
  stats: { colors: true, errorDetails: true },
  headers: { 'Access-Control-Allow-Origin': '*' },
  historyApiFallback: true,
});

devServer.listen(9001);
```

**What is the expected behavior?**
Like in older versions of webpack, the dev-server should not crash, but pick up the new folder structure.
**If this is a feature request, what is motivation or use case for changing the behavior?**
having to manually restart dev server on any file structure change and wait for it to build a bundle is not useful at all.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
 I'm using webpack 3.3.0 and webpack-dev-server 2.6.1, latest Chrome browser and Ubuntu 14.04.

**Comment by sokra** [comment] 2017-08-16 10:51
The resolvers cache is a bit unsafe to modifications of already successfully resolved modules. You could disable it with `resolve.unsafeCache: false` but that would make it slow. You probably have to live with it.

**Comment by ingelity** [comment] 2017-08-16 11:24
@sokra  
will try. thanks!
this was working well in webpack 1, right?
how come it changed?

**Comment by sokra** [comment] 2017-08-16 13:00
Maybe because of more caching in newer version...

**Comment by palnes** [comment] 2017-09-05 11:26
It really would be nice if it was possible to restart the build from scratch without exiting the watcher (think Ctrl-F5 for the watcher). Bonus points if it can re-parse the config it was started with as well. 🥇

**Comment by kifli01** [comment] 2017-10-17 13:13
@ingelity
Have you found a solution for your problem? Because I have same issue. #5774
Unfortunately I haven't found solution.

**Comment by ErichBSchulz** [comment] 2018-02-27 23:49
This worked for me:
```
watchOptions: {
  aggregateTimeout: 300,
  poll: 1000
}
```

thanks to [SO](https://stackoverflow.com/questions/40573774/webpack-hot-reloading-enoent-no-such-file-or-directory/41565837#41565837)

**Comment by kifli01** [comment] 2018-04-18 16:45
@ErichBSchulz Which webpack version do you use? Could you post your config file?

**Comment by Slapbox** [comment] 2018-08-27 17:55
Wow I've been pulling my hair out trying to figure out what was causing my issue. This was the answer. Thank you @ingelity.

For the maintainers:
```
    "webpack": "^4.17.1",
    "webpack-dev-middleware": "^3.2.0",
    "webpack-dev-server": "^3.1.5",
```

**Comment by F3n67u** [comment] 2018-10-11 16:44
Has the same problem when use webpack@2. But after upgrading webpack to version 3, fixed.

**Comment by pitops** [comment] 2019-01-15 14:32
any fixes?

**Comment by sokra** [comment] 2019-01-15 16:59
This will be fixed in webpack 5

**Comment by pitops** [comment] 2019-01-15 19:48
@sokra Any estimate on when Webpack 5 is released?

**Comment by Slapbox** [comment] 2019-01-18 20:09
@pitops probably not for a while. Here's progress on that front: https://github.com/webpack/webpack/projects/5

**Comment by pitops** [comment] 2019-01-18 20:31
I see thank you @Slapbox

**Comment by evilebottnawi** [comment] 2019-03-15 12:06
Problem still exists? If yep, please create minimum reproducible test repo, thanks!

**Comment by Den-dp** [comment] 2019-05-24 15:40
@evilebottnawi for me the easiest way to reproduce was trying to change file extension, so another loader will be applied, but cache will not be invalidated for the previous loader".
Repo with repro is here https://github.com/Den-dp/webpack-issue-5523-repro and steps are in README too.

**Comment by evilebottnawi** [comment] 2019-05-24 15:51
@Den-dp thanks

**Comment by evilebottnawi** [comment] 2019-05-24 15:52
@webpack-bot move to webpack/webpack-dev-server

**Closed by evilebottnawi** 2019-05-24 15:52 UTC

**Comment by evilebottnawi** [comment] 2019-05-27 14:35
@Den-dp thanks for reproducible test repo, can you open new issue with example? Looks you find bug, problem not related to webpack-dev-server

**Comment by Den-dp** [comment] 2019-05-27 14:39
@evilebottnawi you were quicker! Thanks ;)

**Comment by franciscorode** [comment] 2020-05-23 17:01
I had this problem, I tried to clear the cache but nothing, I solved it by killing the node process, running again it was solved

`killall node`
