### ISSUE TITLE
Why webpack 4 uglify already minified file from /node_modules? How disable it?

### ISSUE THREAD

**Issue by spat-ne-hochu** [webpack/webpack#6619] opened 2018-02-28 10:39 UTC
**Do you want to request a *feature* or report a *bug*?**
I think it bug

**What is the current behavior?**
webpack uglify already minified file (.min.js)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. install some dependency with minified build
```npm i -s three```
2. write alias to minidied file in config
```resolve: {
    extensions: [ '.ts' ],
    alias: {
      three: 'three/build/three.min.js',  // <-----------------------
    }
  },
```
3. run webpack in production mode

part in three.min.js
```THREE.PointsMaterial.");return new Ha(a)};l.ParticleBasicMaterial=function(a){console.warn("THREE.ParticleBasicMaterial has```

after uglify two time:
same part in vendor.min.js
```THREE.PointsMaterial."),new ue(t)},t.ParticleBasicMaterial=function(t){return console.warn("THREE.ParticleBasicMaterial has```

**What is the expected behavior?**
no auto minify already minidied files, parse alias from config and add entries with (min.js) extension to black list before run uglify, when run uglife check this black list.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
package.json
```
"@types/three": "0.89.11",
    "clean-webpack-plugin": "0.1.18",
    "copy-webpack-plugin": "4.4.2",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "webpack-contrib/html-webpack-plugin",
    "three": "0.90.0",
    "ts-keycode-enum": "1.0.4",
    "ts-loader": "4.0.0",
    "typescript": "2.7.2",
    "webpack": "4.0.1",
    "webpack-cli": "2.0.9",
    "webpack-dev-server": "3.1.0",
    "webpack-split-chunks": "^0.2.1"
```

**Comment by sokra** [comment] 2018-02-28 15:46
webpack minimizes the concatenated files, there is no way to differentiate modules in the concatenated file.

**Comment by spat-ne-hochu** [comment] 2018-03-01 09:19
if webpack will not be uglify already minified sources, it be more faster =)
FASTER!

**Comment by evilebottnawi** [comment] 2018-03-01 10:22
@spat-ne-hochu @sokra in theory we can ignore `*.min.js`, but some minified files will be minify better with latest version uglify-es/js

**Comment by Paxa** [comment] 2018-03-04 05:50
Can be disabled like this:
```js
const config = {
   optimization: {
     minimize: false
   },
  ...
};
```

**Comment by axelg12** [comment] 2018-03-04 12:31
@Paxa  I think the desired output is not to disable the minimization but to skip already minified file. But like mentioned above by @sokra there is no way to different modules in already concatenated file.

I think we can therefor close this issue.

**Comment by michael-ciniawsky** [comment] 2018-03-04 12:51
In the worst case this might even negatively impact the file size due to problems 're'uglifying the code within different contexts `module` (per file/package)  <=> `assets` (output)  and the `perf` benefit would be minimal (if there is one at all) or maybe it is even slower in the end in case `uglify` as to rewrite a lot of already uglified code. perf perf perf... :P the main reason minification exists is to optimize the  amount of bytes one has to push over the wire. The sanest approach here is simply to minify the whole asset (e.g`bundle.js`) to optimize the result in terms of file size and chill on +/- 0.0012345ms build performance.

**Closed by michael-ciniawsky** 2018-03-04 12:51 UTC

**Comment by glen-84** [comment] 2018-12-14 17:11
One problem with this is that certain code is not mangle-safe. So, for example, when I import Foundation (6.4.3), it will be bundled, minified (again), but then break at runtime because it relies on `constructor.name` and `Function.prototype.name`.

The fix is to use `keep_fnames: true`, but that then applies to *all* code.

I can't help thinking that minification should happen *before* concatenation, to give developers more control of which files are processed.

**Comment by glen-84** [comment] 2018-12-14 18:49
Ya, I've already written 3 plug-ins for my project, but even if this was possible (doubt it), I can't spend any more time on this.

**Comment by DanielRuf** [comment] 2018-12-14 22:58
Possible duplicate of https://github.com/webpack/webpack/issues/1079
