### ISSUE TITLE
Cannot find module '@webassemblyjs/ast'

### ISSUE THREAD

**Issue by realhoffi** [webpack/webpack#8011] opened 2018-09-11 06:03 UTC
Webpack 4.18.0 , Windows Client :)

Error: Cannot find module '@webassemblyjs/ast'

**Comment by xtuc** [comment] 2018-09-11 06:12
Could you please post the full ouput? Are you using an npm proxy/cache?

**Comment by realhoffi** [comment] 2018-09-11 06:14
internal names for company with *** replaced :)
Error: Cannot find module '@webassemblyjs/ast'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (***\App\node_modules\webpack\lib\wasm\WebAssemblyParser.js:7:11)
    at Module._compile (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (***\App\node_modules\webpack\lib\wasm\WebAssemblyModulesPlugin.js:8:27)
    at Module._compile (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (***\App\node_modules\webpack\lib\WebpackOptionsApply.js:11:34)
    at Module._compile (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (***\App\node_modules\webpack\lib\webpack.js:10:29)
    at Module._compile (***\App\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)

**Comment by realhoffi** [comment] 2018-09-11 06:14
my packages 

{
  "name": "serviceportal",
  "version": "2.0.0",
  "description": "serviceportal",
  "author": "florian hoffmann",
  "sideEffects": false,
  "license": "MIT",
  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "bluebird": "^3.5.2",
    "lodash.clonedeep": "^4.5.0",
    "lodash.debounce": "^4.0.8",
    "office-ui-fabric-react": "^6.67.1",
    "react": "^16.5.0",
    "react-dom": "^16.5.0",
    "react-router-dom": "^4.3.1",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/bluebird": "^3.5.24",
    "@types/lodash.clonedeep": "4.5.4",
    "@types/microsoft-ajax": "0.0.33",
    "@types/node": "^10.9.4",
    "@types/react": "16.4.14",
    "@types/react-dom": "^16.0.7",
    "@types/react-router": "4.0.30",
    "@types/react-router-dom": "4.3.0",
    "@types/requirejs": "^2.1.31",
    "@types/uuid": "^3.4.4",
    "awesome-typescript-loader": "^5.2.1",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "fork-ts-checker-webpack-plugin": "^0.4.9",
    "hard-source-webpack-plugin": "^0.12.0",
    "source-map-loader": "^0.2.4",
    "thread-loader": "^1.2.0",
    "ts-loader": "^5.1.0",
    "tslint": "^5.11.0",
    "tslint-loader": "^3.6.0",
    "typescript": "^3.0.3",
    "webpack": "^4.17.3",
    "webpack-cli": "3.1.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-notifier": "^1.6.0"
  },
  "scripts": {
    "start": "webpack-dev-server --host 0.0.0.0 --port 3000 --hot --inline --config webpack.config.js --devtool source-map",
    "build": "webpack --config webpack.config.js --progress --profile --colors",
    "prod": "webpack -p --config webpack.config.js --progress --colors"
  }
}

**Comment by xtuc** [comment] 2018-09-11 06:35
> What version of @webassemblyjs/ast it is trying to install?

It should be mentionned in the error

**Comment by realhoffi** [comment] 2018-09-11 06:42
i posted the whole error:
https://github.com/webpack/webpack/issues/8011#issuecomment-420158918

**Comment by TobiasHeinen** [comment] 2018-09-11 07:05
@xtuc I believe the new webassemblyjs versioning in general might be broken or not set up correctly with NPM. Trying to install webpack produces:

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @webassemblyjs/wasm-opt@1.7.6
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@webassemblyjs/wasm-edit'
> 
> npm ERR! notarget
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     [error log file path redacted]

Meanwhile `npm i @webassemblyjs/wasm-opt` tries to install version 1.7.5.

**Comment by sokra** [comment] 2018-09-11 07:54
This seem to be a npm caching issue. Please try `npm cache verify`.

**Comment by realhoffi** [comment] 2018-09-11 07:56
PS R:\> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 941 (27284852 bytes)
Index entries: 1318
Finished in 4.277s

now?^^

**Comment by sokra** [comment] 2018-09-11 07:58
see also https://github.com/xtuc/webassemblyjs/issues/450

**Comment by sokra** [comment] 2018-09-11 08:00
> now?^^

Try installing again. Some users reported this fixes the issue.

Could you also post your npm and node version?

**Comment by TobiasHeinen** [comment] 2018-09-11 08:15
Cache verification did not fix the issue, unfortunately.

> [redacted]>npm cache verify
> Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
> Content verified: 4666 (267811269 bytes)
> Index entries: 7591
> Finished in 15.796s
> 
> [redacted]>npm update webpack
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @webassemblyjs/wasm-opt@1.7.6
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@webassemblyjs/wasm-edit'
> 
> npm ERR! notarget
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     [redacted]

I have installed Node version `10.4.0` and npm version `6.1.0`. I will see if updating to 10.10.0 will fix the issue.

**Comment by realhoffi** [comment] 2018-09-11 08:17
IT is actually really slow, when i try to install :( but i come back, when IT IS finished

**Comment by xtuc** [comment] 2018-09-11 10:00
I don't see an issue with the publish itself, https://github.com/xtuc/webassemblyjs/commit/4c7ceb48896fc23cdee62bd8f87d24c4b69c90c9 has bumped/fixed all the version across the project and npm looks fine.

We'll have to ask npm's support I guess.

**Comment by realhoffi** [comment] 2018-09-11 10:14
Working now! I installed the packages Not over vs code, i did it with Powershell directly!

**Comment by xtuc** [comment] 2018-09-11 10:15
FYI I just pinged npm's support. @TobiasHeinen could you please try again? maybe the issue is fixed by now.

**Comment by TobiasHeinen** [comment] 2018-09-11 11:05
No, unfortunately it still does not work.

**Comment by xtuc** [comment] 2018-09-11 12:17
Are you using a registry cache or proxy?

**Comment by realhoffi** [comment] 2018-09-11 12:40
you need to reinstall "npm install" multiple times and try to buiild with webpack! :)

**Comment by TobiasHeinen** [comment] 2018-09-11 13:04
@xtuc I'm behind corporate proxy, but I believe we do not have an overreaching proxy cache. Is there a way to check this?

**Comment by xtuc** [comment] 2018-09-12 05:42
@TobiasHeinen npm updated the cache on their side, could you please try again?

**Comment by TobiasHeinen** [comment] 2018-09-12 05:57
Yep, it's working now!

**Comment by sokra** [comment] 2018-09-12 06:48
@xtuc Do you have more information how this could happen? What can we do to avoid this in future?

**Comment by xtuc** [comment] 2018-09-12 06:50
Not yet, but I asked npm about that.

**Comment by realhoffi** [comment] 2018-09-12 15:20
thanks for the response!
I would like to let this open.

**Comment by dustinmcbride** [comment] 2018-09-13 22:02
+1

**Comment by realhoffi** [comment] 2018-09-14 16:02
yes, still happening...

**Comment by mishaszu** [comment] 2018-09-17 12:04
Same here, still happening.
Can't install Webpack (with flags and without) at all. Clearing cache didn't help.

**Comment by xtuc** [comment] 2018-09-17 12:54
@mishaszu are you using an npm proxy or cache?

**Comment by davidfmatheson** [comment] 2018-09-19 13:06
Seems to be fixed this morning, was it [https://github.com/webpack/webpack/pull/8051](this pull)? Anyway, thanks! This was biting me when using Angular CLI 6.2.2.

**Closed** 2018-09-19 13:16 UTC
