### ISSUE TITLE
HMR: hot update file 404

### ISSUE THREAD

**Issue by Richard-Choooou** [webpack/webpack#9186] opened 2019-05-24 09:50 UTC
Why does the hash are different? the hash of the hot-update files used the previous compiler's hash value.

![image](https://user-images.githubusercontent.com/23492006/58317814-2b8ec500-7e49-11e9-91f8-9c7eb0a75faf.png)

![image](https://user-images.githubusercontent.com/23492006/58318125-c12a5480-7e49-11e9-93ae-852b0fcadeb6.png)

**Comment by Richard-Choooou** [comment] 2019-05-24 09:50
And this is my webpack config
```js
// const baseConfig = require('./webpack.common')
const clientBaseConfig = require('./webpack.client.base')
const serverBaseConfig = require('./webpack.server.base')
const webpack = require('webpack')
const merge = require('webpack-merge')
const path = require('path')

module.exports = [merge(clientBaseConfig, {
    entry: {
        client: [path.resolve(__dirname, '../app/client/client.entry.tsx'), 'webpack-hot-middleware/client?name=client']
    },
    devtool: "inline-source-map",
    output: {
        publicPath: '/',
        filename: '[name].index.[hash].js',
        path: path.resolve(__dirname, '../app/server/static/dist'),
        hotUpdateChunkFilename: 'hot/[hash].hot-update.js',
        hotUpdateMainFilename: 'hot/[hash].hot-update.json'
    },
    mode: "development",
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
}), merge(serverBaseConfig, {
    target: 'node',
    entry: {
        server: [path.resolve(__dirname, '../app/client/server.entry.tsx')]
    },
    devtool: "inline-source-map",
    output: {
        publicPath: './',
        filename: '[name].index.js',
        path: path.resolve(__dirname, '../app/dist'),
        libraryTarget: 'commonjs2'
    },
    mode: "development"
})]
```

**Comment by evilebottnawi** [comment] 2019-05-24 10:21
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by evilebottnawi** 2019-05-24 10:21 UTC

**Comment by k2snowman69** [comment] 2020-07-18 21:49
@Richard-Choooou were you able to figure out the root cause? I'm actually running into a very similar situation and am also having issues finding a solution.

**Comment by aboks** [comment] 2020-09-09 07:09
This might be the same issue as https://github.com/webpack/webpack-dev-server/issues/2355.
