### ISSUE TITLE
UglifyJsPlugin is corrupting some Bootstrap CSS

### ISSUE THREAD

**Issue by kaiyoma** [webpack/webpack#2023] opened 2016-02-09 22:53 UTC
In my project, I'm using a simple Bootstrap dropdown, as described here:

http://getbootstrap.com/javascript/#dropdowns

Here's the markup (with React properties removed):

```
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <span>Info</span>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#" data-value="critical">Critical</a></li>
    <li><a href="#" data-value="error">Error</a></li>
    <li><a href="#" data-value="warning">Warning</a></li>
    <li><a href="#" data-value="info">Info</a></li>
  </ul>
</div>
```

When I enable the Uglify plugin, the caret inside the button no longer appears. In the styles in my Chrome dev tools, I can see that the following style is getting removed by Uglify:

`border-top: 4px dashed;`

And that causes the caret to not appear.

I've tried setting all the compressor options to false, but the problem persists. I've tried disabling minification on my CSS loader, but that doesn't have any effect either. The problem seems to be with UglifyJS.

Any ideas here? I'm not sure how to proceed with debugging.

**Comment by cageygee3** [comment] 2016-02-10 21:16
Here's an interesting data point: if I disable UglifyJSPlugin within webpack, run webpack without the `-p` flag to generate an un-minified JS file, then run `uglify` from the command line on the resulting file, everything works fine! The caret appears in my dropdown and no CSS is corrupted.

```
$ ll bundle.js.full
-rw-r--r-- 1 kyle 197121 3291450 Feb 10 12:07 bundle.js.full

$ ../node_modules/uglify-js/bin/uglifyjs --compress warnings=false --mangle -- bundle.js.full > bundle.js

$ ll bundle.js*
-rw-r--r-- 1 kyle 197121 1190619 Feb 10 13:13 bundle.js
-rw-r--r-- 1 kyle 197121 3291450 Feb 10 12:07 bundle.js.full
```

So it seems the problem isn't with Uglify itself, but rather some side effect of running it within webpack.

**Comment by acthp** [comment] 2016-03-14 19:18
I'm also seeing this. I find it affects bootstrap 3.3.6 but not 3.3.4.

**Comment by bebraw** [comment] 2016-12-31 08:26
Can you try against webpack 2?

**Comment by sloria** [comment] 2017-07-03 19:53
I am seeing this as well with webpack 1.13.0 and bootstrap 3.3.7. Unfortunately, we are unable to upgrade to webpack 2 because we're using an outdated Node version at the moment. Once we upgrade, we'll see if this is still an issue.

**Comment by evilebottnawi** [comment] 2017-12-06 16:20
Fixed in latest `uglifyjs-webpack-plugin`, please use latest `uglifyjs-webpack-plugin` version. Feel free to open issue in https://github.com/webpack-contrib/uglifyjs-webpack-plugin if problems appear again. Thank you!

**Closed by evilebottnawi** 2017-12-06 16:20 UTC
Labels: bug, P2: Very Important, S4: Broken
