### ISSUE TITLE
Dynamic import not transformed when used in unreachable code path.

### ISSUE THREAD

**Issue by artursvonda** [webpack/webpack#5270] opened 2017-07-12 08:57 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Build script fails

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
if (false) {
    import('./module'); // <-- Fails to transform this or remove this
}
```

**What is the expected behavior?**
Probably transforming this expression as well and letting uglify to get rid of it later.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
```
node -v
> v8.1.3
```

I came across this issue because we use feature flags at build time that include specific code if feature is enabled.

**Comment by le0nik** [comment] 2017-07-12 14:01
Related: https://github.com/webpack/webpack/issues/4857

**Comment by sokra** [comment] 2017-07-12 14:03
duplicate of #4857

**Closed by sokra** 2017-07-12 14:03 UTC
Labels: bug
