### ISSUE TITLE
Vendor.js chunk changes everytime on build

### ISSUE THREAD

**Issue by paramsingh88** [webpack/webpack#2794] opened 2016-07-22 16:00 UTC
http://stackoverflow.com/questions/38530831/webpack-vendor-chunk-changing-every-time

**Webpack version:**
"^1.13.1"

**Please tell us about your environment:**
OSX El Capitan

**Current behavior:**

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by somebody32** [comment] 2016-07-22 16:05
There is a huge discussion in this issue about what can cause that: https://github.com/webpack/webpack/issues/1315 
I hope that you can find the solution there.

And the relevant example: https://github.com/webpack/webpack/tree/master/examples/chunkhash

**Comment by paramsingh88** [comment] 2016-07-22 16:15
Its not the same as #1315 as #1315 says that the chunk hash changes while the file contents are the same. My file content changes @somebody32

**Comment by somebody32** [comment] 2016-07-22 16:20
@paramsingh88 see last comment here, could be relevant too: https://github.com/webpack/webpack/issues/959

**Comment by sokra** [comment] 2016-09-09 11:34
duplicate of #1315

**Closed by sokra** 2016-09-09 11:34 UTC
Labels: P1: Urgent, question, X1: Inspection required

**Comment by sokra** [comment] 2016-09-09 11:36
A records file or the `NamedModulesPlugins`/`HashedModulesPlugin` would help here. the problem is ids changing.
