### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).context is not a function

### ISSUE THREAD

**Issue by 1512751361** [webpack/webpack#10747] opened 2020-04-21 14:12 UTC
# Bug report

**What is the current behavior?**
Uncaught TypeError: __webpack_require__(...).context is not a function

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
相同的webpack版本js版的，可以使用这个require.context。转为typescript版本的requie.context 报错 Uncaught TypeError: __webpack_require__(...).context is not a function

**Other relevant information:**
webpack version:  4.41.6
Node.js version: v12.11.1
Operating System: mac
Additional tools: vscode

**Comment by evilebottnawi** [comment] 2020-04-21 14:23
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please fill `If the current behavior is a bug, please provide the steps to reproduce.`

**Closed by evilebottnawi** 2020-04-21 14:23 UTC
