### ISSUE TITLE
ERROR in Entry module not found: Error: Can't resolve './src' with webpack@4.3.0

### ISSUE THREAD

**Issue by idessignflo** [webpack/webpack#6890] opened 2018-03-28 11:22 UTC
**Do you want to request a *feature* or report a *bug*?**
it is bug 

**What is the current behavior?**
This is my webpack.config.js : 
const browserConfig = {
    entry :
      APP_DIR + 'client/index.js',
     
    output : {
      path : BUILD_DIR,
      filename : "[name] bundle.js",
      publicPath:BUILD_DIR,
    },
   };
**If the current behavior is a bug, please provide the steps to reproduce.**

C:\Idessign>webpack
Hash: 18bc2fd105d4883da519
Version: webpack 4.3.0
Time: 116ms
Built at: 2018-3-28 12:58:19

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.
ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\Idessign'

**What is the expected behavior?**
compilation of files
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Version: webpack 4.3.0
node : v8.9.3
windows : 8.1 progetionnel

**Comment by ooflorent** [comment] 2018-03-28 11:58
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by idessignflo** [comment] 2018-03-28 12:10
thanks i do all to have a solution to my problem
Thank you for your support

**Comment by montogeek** [comment] 2018-03-28 12:27
Duplicate of https://github.com/webpack/webpack/issues/6858

**Closed** 2018-03-28 14:15 UTC

**Comment by CryptoCatOkiOKi** [comment] 2019-04-23 23:18
make a empty index.js file in src folder and works

**Comment by geongeorge** [comment] 2019-05-03 15:08
@CryptoCatOkiOKi  You are a lifesaver! But isn't there any way we can name our file other than index.js to not make the empty file?

**Comment by dmitriyshashkin** [comment] 2019-05-28 13:35
Why the error says "Can't resolve './src' " when in fact it can't find "/src/index.js" ? This part is the most confusing

**Comment by Pezhvak** [comment] 2019-06-06 21:29
why would it mislead by saying cannot find './src'? wouldn't it be much better if it says it cannot find index.js?

**Comment by lllumineux** [comment] 2019-08-28 18:25
try using "./src"

**Comment by kimgysen** [comment] 2019-12-07 01:00
I use: 
`webpack --config ./src/client/webpack/webpack.client.prod.js`
As npm script and it works fine on my local Mac, but fails on Heroku with given message from the title. 

I currently have an empty index.js file in my src folder with the comment: 
`// It needs this empty file to avoid errors when building webpack on Heroku.`

I don't think that's normal. Is there nothing that can be done about it?

**Comment by vinWin** [comment] 2020-10-13 22:34
> @CryptoCatOkiOKi You are a lifesaver! But isn't there any way we can name our file other than index.js to not make the empty file?

@CryptoCatOkiOKi, Thank you for the suggestion. it worked. "CryptoCatOkiOKi" === "lifesaver"

**Comment by Nikolov0080** [comment] 2021-02-27 15:20
@CryptoCatOkiOKi  This is weird but works for me too 
best regards!
