### ISSUE TITLE
Is there a way to stop Webpack from creating magic HTML files?

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#1240] opened 2015-07-10 11:42 UTC
Is there a way to stop Webpack from creating magic HTML files?

**Comment by shama** [comment] 2015-07-14 21:47
Could you elaborate on what you mean? What are magic HTML files?

**Comment by dschissler** [comment] 2015-07-14 22:00
webpack-dev-server can list all of the files that it provides.  For each chunk and entry there is a "magic html file" created that is just an empty html file with a script tag to that chunk/entry.

Maybe this should go in webpack-dev-server.

**Comment by dschissler** [comment] 2015-07-14 22:02
I've used the localhost:PORT/webpack-dev-server to review the chunks when there are issues.  With the magic files there are simply 2x the entries and they are pointless.

**Comment by bebraw** [comment] 2016-04-17 07:57
@dschissler Can you open an issue for this at the [webpack-dev-server repo](https://github.com/webpack/webpack-dev-server/issues)? Better close this one as the issue isn't related to the core.

**Closed by bebraw** 2016-04-17 07:57 UTC
Labels: question

**Comment by Dragon-Rider** [comment] 2018-01-09 14:04
@dschissler Hi，Have you solved the problem？There are too many magic files in my "dist' folder.
