### ISSUE TITLE
UglifyJSPlugin is mangling valid CSS

### ISSUE THREAD

**Issue by appsforartists** [webpack/webpack#666] opened 2015-01-07 20:46 UTC
With [these lines enabled](https://github.com/appsforartists/webpack-uglify-css-reduction/blob/master/webpack.config.js#L39-L45) in `webpack.config.js`, this

```javascript
/* 1 */
/*!****************************************************************************!*\
  !*** ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./styles.scss ***!
  \****************************************************************************/
/***/ function(module, exports, __webpack_require__) {

	module.exports =
		".Test{width:calc(100vw / 2 - 6px + 0px);}";
```

get mangled to this

```javascript
/* 1 */
/*!****************************************************************************!*\
  !*** ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./styles.scss ***!
  \****************************************************************************/
/***/ function(module, exports, __webpack_require__) {

	module.exports =
		".Test{width:calc(100vw/2 - 6px + 0)}";

/***/ },
```

The conversion of "0px" to "0" prevents Chrome (and perhaps others) from parsing this style.

[Here's a reduction where you can test it yourself](https://github.com/appsforartists/webpack-uglify-css-reduction/).

**Comment by sokra** [comment] 2015-01-08 07:23
report this to https://github.com/css/csso

**Comment by appsforartists** [comment] 2015-01-08 07:30
Reported.

I don't see the source where `csso` is being imported/used.  Is there a flag to disable it?

**Comment by sokra** [comment] 2015-01-08 08:48
https://github.com/webpack/css-loader/#minification

**Comment by appsforartists** [comment] 2015-01-08 09:02
Hmmm; if minimizing is handled by default by css-loader, how come disabling Uglify fixes this problem?

**Comment by sokra** [comment] 2015-01-08 09:03
#283

**Comment by newtriks** [comment] 2015-12-17 12:08
I found that my z-index values were all getting set to 1 when I used UglifyJsPlugin. I originally thought it was related to the css-loader and a similar bug to https://github.com/webpack/css-loader/issues/114. However, when I went in to the css-loader source and made some tweaks I found that the issue remained, even if I ensure that cssnano was not being used in the process at all. This must be related to the UglifyJsPlugin somehow but I am stuck for a solution?

**Comment by newtriks** [comment] 2015-12-18 15:19
For my particular issue, working from a simple reproducible project I worked backwards removing plugins to see exactly what was breaking on uglification and finally found the root culprit was the cssnext-loader. Removing that solved my problem. It appears that the cssnext-loader is using an older version of cssnano https://github.com/cssnext/cssnext-loader/issues/19 and looks like it maybe getting replaced https://github.com/cssnext/postcss-cssnext/issues/15.

**Comment by prewk** [comment] 2015-12-28 12:34
@newtriks I share your problem with z-indexes, they get set to 1. Please let me know if you find a workaround.

**Comment by rwwagner90** [comment] 2016-02-15 16:47
@prewk could you post your webpack config options for these things? I'm having trouble getting it to work

**Comment by rwwagner90** [comment] 2016-02-15 17:37
@prewk never mind, I got it.

For anyone else who needs it, this is what I did:

```
postcss: function (webpack) {
    require('postcss-import')({addDependencyTo: webpack}),
      require('postcss-url')(),
      require('postcss-cssnext')({
        browsers: ['last 2 versions', 'ie >= 9'],
        compress: true
      })
    require('cssnano')({zindex: false})
  },
```

**Comment by prewk** [comment] 2016-02-15 18:41
@rwwagner90 Glad to hear you found a solution.

**Comment by bebraw** [comment] 2016-09-10 06:35
Looks like a related change was made in webpack 2 at #283. Closing.

**Closed by bebraw** 2016-09-10 06:35 UTC
Labels: bug
