### ISSUE TITLE
Bug with module.exports.__esModule on older browsers

### ISSUE THREAD

**Issue by gfmio** [webpack/webpack#6704] opened 2018-03-08 03:15 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug / Bugfix

**What is the current behavior?**

In old versions of Firefox, Chrome, Safari and Android Browser (afaik), the line `exports.__esModule = true;` will generate the following error when it is executed within a module managed by Webpack: `Uncaught TypeError: Cannot assign to read only property '__esModule' of #<Object>`.

Code example:

```js
(function(module, exports, __webpack_require__) {
    "use strict";
    exports.__esModule = true;
})
```

This line is in particular output in all TypeScript files compiled to ES3. Hence, if you want compatibility with old browsers, you will encounter this issue. But afaik, it's also practice in babel and other projects to use / include this line.

**If the current behavior is a bug, please provide the steps to reproduce.**

Bundle any Webpack module with the above line and execute on an old browser with the issue, e.g. Chrome 15 on BrowserStack.

UPDATE: I just realised that the bug is also non-deterministic and seems to depend on module load order which appears to be non-deterministic as well.

**What is the expected behavior?**

There should not be an error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I'm not entirely sure what the cause of this error is, but defining *any other* export before this line will fix this, for example:

```js
(function(module, exports, __webpack_require__) {
    "use strict";
    exports.foo = "bar";
    exports.__esModule = true;
})
```

Interestingly, the issue is also fixed, if `__esModule` is assigned before the module function call, e.g. by initialising it to `undefined`. This can be done when the exports object is initialised or manually, as in this example from the very beginning of some Webpack output:

```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			// exports: {} // Normal webpack output
/******/ 			exports: { __esModule: undefined } // Proposed fix
/******/ 		};
/******/                // Instead of initialising the object with __esModule, it could also be set here
/******/                // module.exports.__esModule = undefined;
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
```

This way, it should not interfere with webpack's other behaviour and not cause any side effects on other applications, because those checks, if at all present, check for the truthiness of `exports.__esModule`.

While this is just an issue with some old browsers, the fix is quite simple and only costs a handful of bytes.

Is this something you would consider? If so, can I submit a PR with the fix?

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

I've tested both the problem and the fix in Chrome 15 on Win XP on BrowserStack. The output was generated with webpack `v3.5.1`. I haven't had the option of testing webpack 4 since the `extract-text-webpack-plugin` is not yet compatible and so I can't migrate my project yet.

**Comment by sokra** [comment] 2018-03-08 06:51
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by gfmio** [comment] 2018-03-08 16:55
Sorry for that - I thought the inline code was simple enough, so I didn't provide one at first. I've just set up a minimal example for you at [https://github.com/gfmio/webpack-es3-error-example](https://github.com/gfmio/webpack-es3-error-example). It should all be quite self-evident from the readme.

**Comment by xtuc** [comment] 2018-03-08 17:20
cc @kovensky. We saw that in Babel as well, but I can't find the issues anymore sorry.

**Comment by Kovensky** [comment] 2018-03-09 02:15
Yeah, I encountered that when I tested a freshly migrated project in an old Android 4 phone. It was very hard to debug as the only tool I could use was `weinre`, which cannot log synchronous errors that happen before the debugger attaches. I had to change the whole thing to be asynchronous and only start running when I call a function in the console.

After I found a file that was crashing first (`redux-devtools-extension/index.js`), I tried to do various editing directly on the input file to see if I could investigate the causes.

`'__esModule' in exports` was `false`, `Object.isExtensible(exports)` was true, `exports.__esModule` was `undefined`. However, the thing that made this problem even crazier was that editing the file such that it had an `exports.foo = 'bar';` before the `exports.__esModule = true;` statement made the module not crash anymore (some other module started crashing instead).

**Comment by sokra** [comment] 2018-03-09 07:55
This is a super weird issue, but as this is caused by TypeScript or babel, it should be considered to be fixed in these projects.

Anyway I don't see a reason why this should be fixed in the webpack runtime. The next one sets a property `exports.__grrrrr`, should this also be added to the default exports object.

Another reasons is that this is a potential breaking change, because now `Object.keys(exports)` returns `__esModule` by default for every module. Can't do that.

**Closed by sokra** 2018-03-09 07:55 UTC

**Comment by Kovensky** [comment] 2018-03-09 08:00
The problem is that we can't fix it on the babel/typescript side.

Probably the only workaround we can have on it is to have a way to postprocess the MainTemplate's output to inject the custom exports object; or have a callback used to generate extra things in the `module` object body. For example, `exports: Object.defineProperty({}, '__esModule', { writable: true, configurable: true })`.

**Comment by gfmio** [comment] 2018-03-09 13:54
I agree with @Kovensky that this cannot exclusively be solved by those compilers, since anyone could write some code with this line, then triggering the issue, so it's not just limited to compiler projects.

However, I'm not sure if it's an issue Webpack should handle either. But including a polyfill or additional loader that post-processes the output string is brittle, since a) people might not know or find out about it and b) due to other post-processing, the fix might not work as intended. Also, with some more DuckDuckGo-ing, I actually found a number of reports of this problem, so it doesn't seem to be too uncommon.

@sokra I didn't consider `Object.keys()`, sorry about that. I did some more testing and found the following new minimal example:

```js
"use strict";
var exports = {};
exports.__esModule = true; // CRASH
```

It's sufficient for these lines to be the only code in the script and it will trigger the error.
Firstly, the error only occurs in strict mode.
Secondly, it occurs **only** for `__esModule`.
My guess is that these browsers have the key `__esModule` reserved for some reason, but only in strict mode.
It does not occur for any other name, including any other name  starting with two underscores. Very weird.

Again, defining any other property on `exports` before the third line will fix the issue, but that has the problem @sokra outlined.

```js
"use strict";
var exports = {};
var exports.anythingElse = 0;
exports.__esModule = true; // NO CRASH, but Object.keys(exports) == ["anythingElse", "__esModule"]
```

However, the error also goes away if you define assign a property and then delete it, e.g.:

```js
"use strict";
var exports = {};
var exports.anythingElse = 0;
delete exports.anythingElse; // Object.keys(exports) == []
exports.__esModule = true; // NO CRASH and Object.keys(exports) == ["__esModule"]
```

Hence, the ephemeral assignment is no longer detectable via `Object.keys()`. Do you think it would somehow be "visible" via any other means?

**Comment by gfmio** [comment] 2018-03-09 14:30
Actually, having thought about this a bit more: The issue is caused by the exports object being passed into the module loader function. Hence, it is not an issue of the compilers generating the module, but the code loading the module. Hence, I think this should be fixed in Webpack or via some loader or plugin.
