### ISSUE TITLE
Uncaught TypeError: (!0) is not a function

### ISSUE THREAD

**Issue by raimund-schluessler** [webpack/webpack#11897] opened 2020-11-01 16:38 UTC
# Bug report

I hope this is the correct repository and it is actually webpacks fault. If it is not, please excuse me in advance.

**What is the current behavior?**

Webpack production build creates a file which gives the following error: `Uncaught TypeError: (!0) is not a function`. The development build runs fine. The compiled javascript file contains this part which seems the reason for the error:
```js
s._withStripped=(!0)((function(){const e=//stripped the rest
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I tried to build a custom Vue app for Nextcloud containing a component with this javascript part
```Vue
<script>
import { getFilePickerBuilder } from '@nextcloud/dialogs'

export default {
	methods: {
		async selectFolder() {
			const folder = await this.$store.dispatch('getAttachmentFolder')

			const path = await getFilePickerBuilder(t('inventory', 'Select attachment folder'))
				.addMimeTypeFilter('httpd/unix-directory')
				.startAt(folder)
				.allowDirectories(true)
				.build()
				.pick()

			this.$store.dispatch('setAttachmentFolder', { path })
		},
	},
}
</script>
```
Commenting out the `getFilePickerBuilder` line circumvents the issue, however, it's most certainly not the underlying cause as I use `getFilePickerBuilder` at a different place without issues.

As far as I can tell, the build run fine on webpack 4. If it helps, I can upload the complete javascript file which webpack produced.

**What is the expected behavior?**

The file should compile to valid javascript, also in production mode.

**Other relevant information:**
webpack version:  5.3.2
Node.js version: v10.19.0
Operating System: Ubuntu 20.04

**Comment by sokra** [comment] 2020-11-01 18:38
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by raimund-schluessler** [comment] 2020-11-01 19:30
> Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

I will try to do that, although I am not really sure this will work, since I don't know what actually causes the problem. The line in question works fine on other occasions, so it seems to be a special combination with other things that causes it.

What I can say so far is that the code compiles fine when I downgrade webpack to `4.44.2` (from `5.3.2`) and terser-webpack-plugin to `4.2.2` (from `5.0.3`, since it doesn't support webpack@4 anymore).

**Comment by joakimriedel** [comment] 2020-11-01 19:47
This might not help, but I have spent many hours today trying to build a small reproducible sample to post an issue of this exact same bug with the minimizer. Since @raimund-schluessler beat me to it, I'll hijack this issue instead.

For me, it reproduces on this line;

```
import Dropzone from "dropzone"
Dropzone.autoDiscover = false;
```

which gets minimized to 

```
hu._withStripped = (!0)(Nl()).autoDiscover = !1;
```

The offending code is inside a Vue component, all transpiled with Babel and minimized with Terser. It's contained within a pretty large project, and reproduces only when building a production build after upgrading from Webpack 4 to Webpack 5.3.2 and Terser 5.0.3. A development build runs perfectly.

When breaking down my large project into a smaller sample, it does not reproduce and the same line gets translated to:

```
s().autoDiscover=!1
```

which of course works. The **_withStripped** seems to be in @raimund-schluessler code as well, so perhaps this is somehow related to finding the bug.

Could the **_withStripped** part aid somehow in how to build a reproducible sample? What does it mean and is this something that Webpack/Terser exports or is it some other part of the ecosystem?

**Comment by raimund-schluessler** [comment] 2020-11-01 20:20
I managed to create a MWE, you can find it under https://github.com/raimund-schluessler/mwe-webpack-11897.

Just clone the repository, run `npm ci` and `npm run build` afterwards and checkout `js/mwe.js`. I ran it on the bash with `js mwe.js` and got `TypeError: true is not a function`.

Let me know if I can be of any more help.

**Comment by raimund-schluessler** [comment] 2020-11-03 20:02
@sokra Unfortunately the issue is not fixed with webpack 5.4.0 although #11904 is included as far as I know. Please checkout the updated MWE under https://github.com/raimund-schluessler/mwe-webpack-11897. Running the compiled javascript still gives `TypeError: true is not a function`. Please let me know if can help debugging this.

**Comment by joakimriedel** [comment] 2020-11-03 20:17
@sokra @raimund-schluessler can confirm that my similar issue was resolved with 5.4.0, but adding my code in your MWE did not reproduce so perhaps they have different root cause?

**Closed** 2020-11-04 11:45 UTC
Labels: critical-bug, webpack-5

**Comment by raimund-schluessler** [comment] 2020-11-04 12:27
Can I somehow test #11920 before the release of 5.4.1?

**Comment by snitin315** [comment] 2020-11-04 12:29
Yes use the `master` branch of webpack

**Comment by raimund-schluessler** [comment] 2020-11-05 08:42
I can confirm that the issue has been fixed in the MWE as well as in my production build. Thanks a lot!
