### ISSUE TITLE
the error info is not clear enough in the terminal

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#3582] opened 2016-12-26 11:39 UTC
![image](https://cloud.githubusercontent.com/assets/1060733/21481462/cf1d510c-cba2-11e6-998e-8fab89522501.png)

```json
"scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --inline --hot"
  },
```
i wrote npm script in package.json for webpack
but it got wrong
and the info is not clear enough
it's a pain for me

**Comment by juristr** [comment] 2016-12-26 11:43
@zzzgit Hey, the problem is that the port webpack is trying to start it's development server is already in use. Take a look at the line where it says

```
ERROR: listen to EADDRINUSE 127.0.0.1:8080
```

You need to start webpack on a different port or stop your current server running at localhost 8080 😄. This is a standard error you get when you run a node app that wants to listen at a given port.

**Comment by zzzgit** [comment] 2016-12-26 11:45
thanks very much

**Comment by juristr** [comment] 2016-12-26 11:46
@zzzgit plz close the issue if this solves your problem. Thanks 👍 😃

**Closed** 2016-12-26 11:49 UTC
