### ISSUE TITLE
When reloading the page after subsequent builds, module loading is broken

### ISSUE THREAD

**Issue by RaitoBezarius** [webpack/webpack#1982] opened 2016-02-02 21:59 UTC
When you setup a Webpack server with HMR, and use `require.ensure` in the code which will be rebundled.

But then:

``` js
/******/                // Module can be created from a template
/******/                modules[moduleId] = (function(_m) {
/******/                    var args = _m.slice(1), templateId = _m[0];
/******/                    return function (a,b,c) {
/******/                        modules[templateId].apply(this, [a,b,c].concat(args));
/******/                    };
/******/                }(_m));
```

`templateId` is `undefined` for a certain module, I am still investigating the issue atm.
My guess is that:
`require.ensure` put the module in some kind of cache, there was some hot reload which invalidated and finally, when reloading the page, the cache state is lost but Webpack still consider it exists. (sorry for the messy mind, I am not accustomed at all with Webpack internals). The proof is that when I restart the Webpack server (I use Hot middleware), it reworks as expected, until a HMR full reload is necessary which breaks the build.

I could setup a minimal case in a repository so you can check this, but it requires some time.

By tracing the stack call, I have found that it comes from `react-transform-hmr` and more exactly from a dependency which do that:

``` js
var getLength = __webpack_require__(__webpack_module_template_argument_0__),
    isLength = __webpack_require__(__webpack_module_template_argument_1__);

/**
 * Checks if `value` is array-like.
 *
 * @private
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is array-like, else `false`.
 */
function isArrayLike(value) {
  return value != null && isLength(getLength(value));
}

module.exports = isArrayLike;
```

The `getLength` cannot be required, I don't understand why, any ideas?

It seems like a deduping bug?

This problem is _not fixed_, it seems to happen randomly.

**Comment by RaitoBezarius** [comment] 2016-02-03 09:15
This is definitely related to #583 I suppose, disabling DedupePlugin fixes the issue.

**Comment by olofd** [comment] 2016-02-18 08:07
We have the same issue on 1.12.13

**Comment by jarrod268** [comment] 2016-03-09 13:05
Same issue here as well. Disabling the DedupePlugin worked.

**Comment by likezero** [comment] 2016-03-17 06:42
I have the similar issue.
``` javascript
// Execute the module function
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```
when i reload the page after subsequent builds, it reports:
`Uncaught TypeError: Cannot read property 'call' of undefined`

**Comment by acostaf** [comment] 2016-07-01 17:20
HI All 

Just for information, I founf that this error it is a bit misleading, it is not a bug but the way how you build your common chunks. please refer to 

this works for me 

    entry: {
        tradeReporting: './app/tradeReporting/main.ts',
        admin: './app/admin/main.ts',
        polyfills: './app/lib/polyfill.ts'        
    },
    output: { path: './app/lib', filename: '[name]Bundle.js', chunkFilename: "[id].chunk.js" },
    resolve: { extensions: ['', '.ts', '.js'] },
    plugins: [         
         new webpack.optimize.CommonsChunkPlugin({ names: ["vendor", "polyfills"], minChunks: 2 }),

https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks
or 
https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk

**Comment by bebraw** [comment] 2016-12-25 08:00
Closing given DedupePlugin has been deprecated.

**Closed by bebraw** 2016-12-25 08:00 UTC
Labels: bug
