### ISSUE TITLE
webpack@2.2.0-rc.4: Build fails on node < 6

### ISSUE THREAD

**Issue by onnozel** [webpack/webpack#3951] opened 2017-01-14 09:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Node throws an error when webpack runs.

[Error log](https://gist.github.com/onnozel/db6a5bae5960cac1c2c09a5c6a1f4577)

**If the current behavior is a bug, please provide the steps to reproduce.**

[package.json](https://gist.github.com/onnozel/2bf5ba5f7142278d62e6bb632d67b1e5)

[webpack.config.js](https://gist.github.com/onnozel/2111622f2128ad58e7a756d9e308b532)

**What is the expected behavior?**
Webpack should run the build.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack@2.2.0-rc.4
node@5.7.0
Windows 7

The build runs fine when using rc.3 or when using node >= 6.0.0

**Comment by timse** [comment] 2017-01-14 11:09
I would guess that is primarily a Node problem. 

`Buffer.from` was introduced in v5.10 (see: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding) and apparently backported to 4.5 (see: https://github.com/webpack/webpack/issues/3944)

**Comment by michael-ciniawsky** [comment] 2017-01-14 13:00
node 5 is unsupported anyways, does the error also accur with node v4 / v6 ?

**Comment by onnozel** [comment] 2017-01-14 15:31
It does build fine, when using v4.5 / v6+

**Comment by SpaceK33z** [comment] 2017-01-14 17:56
So to be clear, this is only a problem on node v5? v5 is [no longer maintained](https://nodejs.org/en/blog/community/v5-to-v7/#which-brings-me-to-node-js-v5) (the support ended long before v0.12 even), and we tend to follow the Node.js maintenance windows. Perhaps we should change the `engines` field in the package.json to reflect this.

**Comment by sokra** [comment] 2017-01-14 18:58
duplicate of #3944

**Closed by sokra** 2017-01-14 18:58 UTC
