### ISSUE TITLE
Export was not found while working with yarn berry workspaces

### ISSUE THREAD

**Issue by tomsonpl** [webpack/webpack#11172] opened 2020-07-14 12:48 UTC
# Bug report

**What is the current behavior?**

Hi, I am working with webpack 4 and yarn berry workspaces.

whenever I try to import a "package (workspace)" the browser console gives me a warning:

"export 'IAppError' was not found in './src/reduce_request_error'

The app however works, and no other places throw this warning. It happens to all of the packages that we import and export in our index files `index.ts` 

Thanks, 
Best regards.
TC 

**If the current behavior is a bug, please provide the steps to reproduce.**

<img width="770" alt="Zrzut ekranu 2020-07-14 o 14 38 23" src="https://user-images.githubusercontent.com/16632552/87426951-53f2f900-c5e0-11ea-81eb-ac6ffdeaf921.png">
<img width="684" alt="Zrzut ekranu 2020-07-14 o 14 38 43" src="https://user-images.githubusercontent.com/16632552/87426956-55bcbc80-c5e0-11ea-8605-dbe164fa6971.png">
<img width="609" alt="Zrzut ekranu 2020-07-14 o 14 39 09" src="https://user-images.githubusercontent.com/16632552/87426959-56555300-c5e0-11ea-98f7-fc8a33aab800.png">

**What is the expected behavior?**

No warnings... because app works.

Do you think its an issue on your side? 
Thanks in advance,
best regards,
TC

**Other relevant information:**
webpack version:  "^4.43.0",
Node.js version: 12.10
Operating System:  macos
Additional tools: yarn berry

**Comment by evilebottnawi** [comment] 2020-07-14 12:52
Duplicate of #7378

**Closed by evilebottnawi** 2020-07-14 12:52 UTC
