### ISSUE TITLE
Webpack keeps compiling

### ISSUE THREAD

**Issue by alejandronanez** [webpack/webpack#5242] opened 2017-07-08 17:39 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**
My bundle gets compiled several times.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm creating a webpack boilerplate for my personal projects, you can check it on this repo on the `cleanup` branch https://github.com/alejandronanez/webpack-boilerplate/tree/cleanup

1. `npm start`
2. Add a few lines to `src/styles/app.scss` - a few empty new lines will do the trick
3. CTRL + C to stop the process
4. `npm start` again
5. You should start seeing the bundle compiles on a loop for a while, and then it will stop

Here's a GIF with what is happening:

![webpack](https://user-images.githubusercontent.com/464978/27987858-77b8a2d8-63da-11e7-8f5b-897f4f5de977.gif)

**What is the expected behavior?**

The looping should not occur.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
```
node: 8.1.3 && LTS
npm: 5.1.0
OSX: 10.12.5
webpack version: 3.1.0 && 2.6.1
```

**Comment by irowbin** [comment] 2017-07-08 18:19
@alejandronanez  The latest version of `GitBash` on windows 10 happened same as this to me with the  `webpack v2xx & v3xx` so i went back to GitBash version `v2.13.0-64-bit` because the `ctrl+c` is not terminating the `nodejs` and keep running compiling in the background but the window's terminal does the terminate. no idea that the issue is related with this or not.Thanks

**Comment by bebraw** [comment] 2017-07-09 04:49
I managed to get the behavior exactly **once** on iTerm. It's random like that to me and I have no clue what could be causing it.

**Comment by vlasenko** [comment] 2017-07-11 19:42
Probably this is a duplicate of that one:
https://github.com/webpack/watchpack/issues/25

**Comment by bfricka** [comment] 2017-07-18 21:23
I had this exact issue and had to opt out a ton of stuff manually from watchpack.

```js
{
  watchOptions: {ignored: [...lotsOfDirectories]}
}
```

This wasn't happening in the past and it's a really aggravating thing to have to hack like this.

**Comment by awesomenaz** [comment] 2017-07-25 11:35
I am having this exact issue in webpack@3.3.0. Similar to @bfricka wasn't happening in the past.

**Comment by yessky** [comment] 2017-08-01 07:45
a workaround [here](https://github.com/webpack/watchpack/issues/25#issuecomment-319292564)

**Comment by vankop** [comment] 2020-08-09 15:15
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.

**Closed by vankop** 2020-08-09 15:15 UTC
Labels: bug, webpack-2, webpack-3
