### ISSUE TITLE
Webpack5: mod is not defined

### ISSUE THREAD

**Issue by syuilo** [webpack/webpack#10347] opened 2020-02-05 23:17 UTC
# Bug report

**What is the current behavior?**

Building a project in **production mode** using webpack5 results in a `mod is not defined` error at runtime.

If you build with development mode, no errors will occur at runtime.  In webpack4 this error does not occur when building in production mode.

Also, when building with webpack4, there are no deprecation warnings.

So I think this is a bug in webpack5.

![AAA1139D-F2EF-486C-81CF-DF810A18F7A5](https://user-images.githubusercontent.com/4439005/73892003-021fa780-48b9-11ea-9c4d-6fcc498fa60e.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

I haven't created a minimal reproducible repository yet, but here is the actual my project config.

https://github.com/syuilo/misskey/blob/develop/webpack.config.ts

**What is the expected behavior?**

No runtime error

**Other relevant information:**
webpack version:  5.0.0-beta.13
Node.js version: 13.7.0
Operating System: Windows10
Additional tools:

**Comment by sokra** [comment] 2020-02-11 09:13
Impossible to figure out anyway. Please provide more information and a repro.

**Comment by sogehige** [comment] 2020-03-07 00:54
I've got this error as well on both modes `ReferenceError: mod is not defined` which is 

**in production mode:**
```javascript
        /***/
        70651: /***/
        ((__unused_webpack_module,__unused_webpack___webpack_exports__,__webpack_require__)=>{

            "use strict";
            /* harmony import */
            var _node_modules_vue_style_loader_index_js_node_modules_css_loader_dist_cjs_js_node_modules_vue_loader_lib_loaders_stylePostLoader_js_node_modules_vue_loader_lib_index_js_vue_loader_options_login_vue_vue_type_style_index_0_lang_css___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(47469);
            /* harmony import */
            var _node_modules_vue_style_loader_index_js_node_modules_css_loader_dist_cjs_js_node_modules_vue_loader_lib_loaders_stylePostLoader_js_node_modules_vue_loader_lib_index_js_vue_loader_options_login_vue_vue_type_style_index_0_lang_css___WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/
            __webpack_require__.n(_node_modules_vue_style_loader_index_js_node_modules_css_loader_dist_cjs_js_node_modules_vue_loader_lib_loaders_stylePostLoader_js_node_modules_vue_loader_lib_index_js_vue_loader_options_login_vue_vue_type_style_index_0_lang_css___WEBPACK_IMPORTED_MODULE_0__);
            /* unused harmony default export */
            var _unused_webpack_default_export = (mod); /* <==== this line */

            /***/
```

This is caused by inline <style> in .vue file for me. It seems to me like issue with tree shaking and side effects?

**Other relevant information:**
webpack version: 5.0.0-beta.13
Node.js version: 13.10.1
Operating System: Windows10
Additional tools:

**Comment by sodatea** [comment] 2020-03-12 07:59
See this issue: https://github.com/webpack/webpack/issues/10542

A temporary workaround is to turn off `optimization.usedExports`

**Comment by evilebottnawi** [comment] 2020-03-12 08:34
@sodatea It is duplicate problem?

**Comment by sodatea** [comment] 2020-03-12 08:42
Yes, they are the same problem but I've tried to boiled it down to a minimal and more general reproduction so I opened a new issue.

**Comment by evilebottnawi** [comment] 2020-03-12 08:56
Can we close this problem to avoid duplicates?

**Comment by sodatea** [comment] 2020-03-12 08:58
I think so

**Closed** 2020-03-12 09:02 UTC
