### ISSUE TITLE
v4.29.0 : Module parse failed: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by huineng** [webpack/webpack#8660] opened 2019-01-21 07:03 UTC
# Bug report

**What is the current behavior?**

**Error in dynamic import**

```js
Module parse failed: 'import' and 'export' may only appear at the top level (45:8)
You may need an appropriate loader to handle this file type.

ngAfterViewInit() {
      import('./df.tinymce.files')
            .then(() => {
```

**What is the expected behavior?**
Until version 4.29.0 this was working as expected, it's only with this version that this error happens

**Other relevant information:**
webpack version:  v4.29.0
Node.js version: v11.7.0
Operating System: mac
Additional tools: ts 3.2.2

**Comment by sokra** [comment] 2019-01-21 08:53
Looks like related to #8598 

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

cc @kiliancs

**Comment by sokra** [comment] 2019-01-21 09:01
Duplicate of #8656

**Closed by sokra** 2019-01-21 09:01 UTC
