### ISSUE TITLE
`import()` fails at runtime under node when `output.filename` and `output.chunkFilename` have dirs

### ISSUE THREAD

**Issue by marian-c** [webpack/webpack#11009] opened 2020-06-05 22:18 UTC
# Bug report

**What is the current behavior?**

When targeting node (`target: "node"`) `import()`s will fail to work at runtime, the chunk of the imported module can not be located. This happens when there's a directory segment in `output.filename` and `output.chunkFilename`

Error when running the bundle:
```
Error: Cannot find module './js/0-chunk.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- checkout minimal reproduction example: https://github.com/marian-c/webpack-bug
- `$ yarn`
- `$ yarn start`

`yarn start` will clean the destination directory, will run webpack then try to run the bundle

**What is the expected behavior?**

I expect that "running" the bundle under node should not error.

**Other relevant information:**
webpack version:  ^4.43.0
Node.js version:  10.16.0
Operating System: OSX

--- 

This problem does not happen when:
- targeting `web`
- when you don't have a directory segment in the output filenames (in my example the `js/` bit)

---
Relevant config and code for convenience:

```javascript
// webpack.config.js
module.exports = {
  mode: "development",
  output: {
    filename: `js/[name].js`,
    chunkFilename: `js/[id]-chunk.js`,
    path: __dirname + '/dist',
  },
  target: "node",
};

```

```javascript
// src/index.js
export default function main() {
  import('./lazy').then(mod => console.log(mod));
}

main();
```

**Comment by Legends** [comment] 2020-06-06 21:43
I can run your repo by changing webpack.config extension to `.cjs`.
But the app fails with `ReferenceError: window is not defined` due to the dynamic import!
If I change it to a normal `import` it runs as expected.

[Here is the repo](https://github.com/Legends/webpack-pure-es6-without-babel)

**Comment by marian-c** [comment] 2020-06-06 21:56
> I can run your repo by changing webpack.config extension to `.cjs`
If I change the extension of the webpack config to .cjs, even on node 14, it's not being taken into consideration by webpack

> But the app fails with `ReferenceError: window is not defined` (`target:node` we have no window)
> due to the dynamic import `import("./lazy.js").then(mod => console.log(mod));`.

do you get the window error under node? seems odd

> 
> If I change it to a normal `import` it runs as expected.
> 
> [Here is the repo](https://github.com/Legends/webpack-pure-es6-without-babel)
> 
> But I am running on **node v14.4.0**

I can not access your repo, also, the whole issue is around the `import()` function/construct and outputting inside a subfolder of what is `output.path`

Thanks for looking into this but I don't know what to make of your answer

**Comment by Legends** [comment] 2020-06-06 22:11
Sorry, here is the [repo](https://github.com/Legends/webpack-pure-es6-without-babel), it's public now.
Perhaps, I've overseen something, but it works on my machine.

**Comment by DanielRuf** [comment] 2020-06-08 17:40
The problem is the code that is in `dist/js/main.js`: var chunk = require("./js/" + chunkId + "-chunk.js");

I guess `path` should be the absolute toplevel path to all bundles.


The following work:

```
  output: {
    filename: `[name].js`,
    chunkFilename: `[id]-chunk.js`,
    path: __dirname + '/dist/js',
  },
```

```
  output: {
    filename: `../js/[name].js`,
    chunkFilename: `../js/[id]-chunk.js`,
    path: __dirname + '/dist/js',
  },
```

At least there is a conflict between loading chanks from a bundle and setting / calculating (different) paths.

**Comment by alexander-akait** [comment] 2021-02-04 12:52
Fixed in webpack@5, also above idea is right, I recommend do it

**Closed by alexander-akait** 2021-02-04 12:52 UTC

**Comment by Glandos** [comment] 2021-08-24 09:34
So, for people stucked with webpack v4, there is no hope? I am bundling an application with very large vendor chunks (NestJS), and I'd like to share common code in an external chunk, but I'm hit with the same behavior.

**Comment by alexander-akait** [comment] 2021-08-24 10:09
Unfortunately no, you webpack v5 required...
