### ISSUE TITLE
"Cannot read property 'harmonyModule' of null" in watch mode

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#3498] opened 2016-12-16 08:42 UTC
Happens with 2.2.0-rc.0 while running in watch mode / webpack-dev-server under unknown conditions after editing a file. After it occurs, re-editing and saving the file, or a dependency, or a parent does not help. Restarting the webpack-dev-server builds successfully.

```
ERROR in ./src/api/notifications/helpers.ts
Module parse failed: .../node_modules/awesome-typescript-loader/dist/entry.js?{"configFileName":".../src/tsconfig.json","useBabel":true,"sourceMap":true,"verbose":false}!.../src/api/notifications/helpers.ts Cannot read property 'harmonyModule' of null
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'harmonyModule' of null
    at makeHarmonyModule (.../node_modules/webpack/lib/dependencies/HarmonyImportDependencyParserPlugin.js:14:17)
    at Parser.import (.../node_modules/webpack/lib/dependencies/HarmonyImportDependencyParserPlugin.js:25:3)
    at Parser.applyPluginsBailResult (.../node_modules/tapable/lib/Tapable.js:73:27)
    at Parser.walkImportDeclaration (.../node_modules/webpack/lib/Parser.js:547:7)
    at Parser.walkStatement (.../node_modules/webpack/lib/Parser.js:432:32)
    at Parser.<anonymous> (.../node_modules/webpack/lib/Parser.js:413:9)
    at Array.forEach (native)
    at Parser.walkStatements (.../node_modules/webpack/lib/Parser.js:411:13)
    at Parser.parse (.../node_modules/webpack/lib/Parser.js:1142:8)
    at .../node_modules/webpack/lib/NormalModule.js:199:17
    at .../node_modules/webpack/lib/NormalModule.js:164:10
    at .../node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (.../node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at iterateNormalLoaders (.../node_modules/loader-runner/lib/LoaderRunner.js:213:10)
    at .../loader-runner/lib/LoaderRunner.js:228:3
    at context.callback (.../node_modules/loader-runner/lib/LoaderRunner.js:106:13)
 @ ./src/api/notifications/index.ts 3:0-48
```

**Comment by mreishus** [comment] 2016-12-16 16:09
I seem to get it when this happens

1. I cause a legit syntax error, and webpack can't compile and gives me a true error message.
2. I fix the error and save.
3. Instead of rebuilding, now I get the harmony error

**Comment by santihbc** [comment] 2016-12-18 19:30
Same here

**Comment by catchergeese** [comment] 2016-12-18 22:10
The same for me. It happens _sometimes_ when it recompiles a code with syntax errors.

**Comment by dhh** [comment] 2016-12-18 23:55
I seem to get it every time it recompiles code with syntax errors.

**Comment by philostler** [comment] 2016-12-18 23:56
And same here as well

**Comment by liximomo** [comment] 2016-12-19 06:21
same here as well

**Comment by jin5354** [comment] 2016-12-19 06:22
Same here. After corrected a syntax error, I always get this error.

**Comment by timothyallan** [comment] 2016-12-20 02:46
Annnnnd add me to the list as well.

**Comment by MaxiMacko** [comment] 2016-12-20 08:32
I have also the same problem

**Comment by robbert229** [comment] 2016-12-21 00:26
Same.

**Comment by Cap32** [comment] 2016-12-21 07:06
Same 😭

**Comment by maxdow** [comment] 2016-12-21 12:13
Same here . After a full rebuild it works

**Comment by TheLarkInn** [comment] 2016-12-21 15:18
Has anyone checked to see if this is this still an issue in RC1?

**Comment by Kovensky** [comment] 2016-12-21 15:19
@TheLarkInn it indeed does still happen with 2.2.0-rc.1

**Comment by nktssh** [comment] 2016-12-21 15:20
@TheLarkInn checked with `2.2.0-rc.1`, still happen.

**Comment by andreiglingeanu** [comment] 2016-12-21 16:21
@TheLarkInn Yep, can confirm.

**Comment by kingluddite** [comment] 2016-12-22 01:20
I concur.

**Comment by TheLarkInn** [comment] 2016-12-22 06:28
Thank you.

**Comment by TheLarkInn** [comment] 2016-12-22 06:29
Would it be possible to craft a very small reproducible repo for this? If so I could start tackling this if @sokra doesn't already know what the cause is.

**Comment by duivvv** [comment] 2016-12-22 08:44
it happens in my generator https://github.com/devinehowest/generator-devine-boilerplate
just answer No to everything.

mostly when there is a syntax error in my code

**Comment by sokra** [comment] 2016-12-22 10:52
this is maybe fixed by: https://github.com/webpack/webpack/commit/862478e3b4956caa10527d760baf775c2d2f79b2

**Comment by Cap32** [comment] 2016-12-22 11:12
It works!

**Comment by andreiglingeanu** [comment] 2016-12-22 11:15
Just tested, resetting `meta` on subsequent re-compiles fixes the error.

**Comment by nktssh** [comment] 2016-12-22 11:17
can confirm, work as expected with `2.2.0-rc.2` 👍🏻

**Comment by kingluddite** [comment] 2016-12-22 11:42
Nice!

**Comment by sokra** [comment] 2016-12-22 13:49
Good to hear :+1:

**Closed by sokra** 2016-12-22 13:49 UTC
