### ISSUE TITLE
Error when I add ModuleConcatenationPlugin while using dynamic imports

### ISSUE THREAD

**Issue by thecodejack** [webpack/webpack#5760] opened 2017-10-04 09:40 UTC
**Do you want to request a *feature* or report a *bug*?**
**Bug**

Asked this question in SO and gitter but no proper answer.

**What is the current behavior?**
I used dynamic imports(`import()`) feature in my application like following.
```js
  // Make reducers hot reloadable, see http://mxs.is/googmo
  /* istanbul ignore next */
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      import('./reducers').then((reducerModule) => {
        const createReducers = reducerModule.default;
        const nextReducers = createReducers(store.asyncReducers);

        store.replaceReducer(nextReducers);
      });
    });
  }
 ```

I also have babel stage-0 preset added which is expected to have dynamic imports babel plugin. I used webpack 2.5.1 before upgrading webpack 3.6.0 recently. Everything worked fine even after upgrade. 

I wanted to add scope hoisting feature for which added `new webpack.optimize.ModuleConcatenationPlugin()` in my production webpack config. This started throwing following error for all dynamic imports.
```
ERROR in chunk main [entry]
[name].[chunkhash].js
'import' and 'export' may only appear at the top level (42:6)
|   if (false) {
|     module.hot.accept('./reducers', function () {
|       import('./reducers').then(function (reducerModule) {
|         var createReducers = reducerModule.default;
|         var nextReducers = createReducers(store.asyncReducers);
```
Able to resolve the error with `System.import`. But that is deprecated and better way to do is with `import()` since it's in stage-3 now.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Should not throw any error
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack version: 3.6.0
nodejs: 6.11.1

**Comment by sgal** [comment] 2017-10-05 07:11
Could you try to use `babel-plugin-syntax-dynamic-import` directly? The fact that it gets transpiled to `System.import` is disturbing, since webpack 3 can handle `import(...)` statements directly.

.babelrc
```
"presets": [...],
"plugins": [
   ...
   "syntax-dynamic-import"
]
```

**Comment by thecodejack** [comment] 2017-10-05 08:52
@sgal I tried that. But no luck. Not sure if that's the issue coz by just removing line `new webpack.optimize.ModuleConcatenationPlugin()`, again everything works fine.

**Comment by donocode** [comment] 2017-10-05 20:04
Looks like a duplicate of #5663

**Comment by thecodejack** [comment] 2017-10-06 07:56
Just got the usecase after observing my code failure #5663 and this one. Code is failing only when we have dynamic imports inside if statement  which has false set directly like following.

```js
if (false) {
     module.hot.accept('./reducers', function () {
       import('./reducers').then(function (reducerModule) {
         var createReducers = reducerModule.default;
         var nextReducers = createReducers(store.asyncReducers);
```

When I set it to a variable like following, it doesn't throw any error.
```js
const flag = false;
if (flag) {
     module.hot.accept('./reducers', function () {
       import('./reducers').then(function (reducerModule) {
         var createReducers = reducerModule.default;
         var nextReducers = createReducers(store.asyncReducers);
```

Not sure if this is a babel issue or webpack's acorn issue.

**Comment by sokra** [comment] 2017-10-09 08:31
Duplicate of #5663

**Closed by sokra** 2017-10-09 08:31 UTC
