### ISSUE TITLE
Filesystem Cache is throwing TypeError: Cannot read property 'length' of undefined from ResolverCachePlugin

### ISSUE THREAD

**Issue by gtwilliams03** [webpack/webpack#11668] opened 2020-10-13 13:41 UTC
# Bug report

**What is the current behavior?**

Attempting to get the cache working for webpack 5.  I have it working on one of my local repos, but this one (a clone of a different website), is throwing an error:

Relevant config:

```
  cache: {
    type: 'filesystem',
    buildDependencies: {
      config: [ '/Users/xxx/public-web/config/webpack.config.js' ]
    }
  }
```
Throws this error:

```
(node:23491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at getType (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/util/path.js:41:12)
    at Resolver.isPrivate (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:446:10)
    at Resolver.parse (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:430:25)
    at /Users/xxx/public-web/node_modules/enhanced-resolve/lib/ParsePlugin.js:33:29
    at _next0 (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/xxx/public-web/node_modules/webpack/lib/cache/ResolverCachePlugin.js:199:17
    at Hook.eval [as callAsync] (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Resolver.doResolve (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:398:16)
    at doRealResolve (/Users/xxx/public-web/node_modules/webpack/lib/cache/ResolverCachePlugin.js:138:13)
```

Setting the webpack config `config: false` eliminates the error and the build runs normally.  

**If the current behavior is a bug, please provide the steps to reproduce.**

I see directories being created under my working repo in the `node_modules/.cache` folder, but not on my problem repo.  A `.cache` folder is created, but no `webpack` or `webpack/client-development` folders.

**What is the expected behavior?**

Cannot figure out why one repo is throwing this error and the other is not.

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 14.13.1
Operating System: MacOS Catalina 10.15.7
Additional tools:

**Comment by gtwilliams03** [comment] 2020-10-13 14:01
Same computer, same webpack config, different folders.

**Comment by evilebottnawi** [comment] 2020-10-13 14:11
@gtwilliams03 Perhaps we are not processing a specific case, perhaps the configuration would be enough to understand it

**Comment by gtwilliams03** [comment] 2020-10-13 14:17
Here is the output of my webpack config:

```
{
  mode: 'development',
  cache: {
    type: 'filesystem',
    buildDependencies: {
      config: [ '/Users/xxx/public-web/config/webpack.config.js' ]
    }
  },
  optimization: { emitOnErrors: true, concatenateModules: false },
  name: 'client',
  target: 'web',
  devtool: 'source-map',
  resolve: {
    modules: [ '/Users/xxx/public-web/src', 'node_modules' ],
    extensions: [ '.js', '.jsx', '.json' ]
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /\/node_modules\/(?!(@restart\/context|@restart\/hooks|autobind-decorator|sort-keys|email-regex|query-string|split-on-first|strict-uri-encode|react-bootstrap-slider)\/).*\//,
        include: [
          '/Users/xxx/public-web/node_modules/@restart/context',
          '/Users/xxx/public-web/node_modules/@restart/hooks',
          '/Users/xxx/public-web/node_modules/autobind-decorator',
          '/Users/xxx/public-web/node_modules/sort-keys',
          '/Users/xxx/public-web/node_modules/email-regex',
          '/Users/xxx/public-web/node_modules/query-string',
          '/Users/xxx/public-web/node_modules/split-on-first',
          '/Users/xxx/public-web/node_modules/strict-uri-encode',
          '/Users/xxx/public-web/node_modules/react-bootstrap-slider',
          '/Users/xxx/public-web/src'
        ],
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              plugins: [ '@babel/plugin-proposal-class-properties' ],
              presets: [ [ '@babel/preset-env' ], '@babel/preset-react' ]
            }
          }
        ]
      },
      {
        test: /\.scss$/,
        include: /(\/Users\/xxx\/public\-web\/src)/,
        use: [
          { loader: 'style-loader', options: {} },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              modules: { localIdentName: '[name]__[local]___[hash:base64:5]' },
              importLoaders: 1
            }
          },
          { loader: 'postcss-loader', options: { sourceMap: true } },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              sassOptions: {
                includePaths: [ '/Users/xxx/public-web/src/styles' ]
              }
            }
          }
        ]
      },
      {
        test: /\.css$/,
        include: /(\/Users\/xxx\/public\-web\/src)/,
        use: [
          { loader: 'style-loader', options: {} },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              modules: { localIdentName: '[name]__[local]___[hash:base64:5]' },
              importLoaders: 1
            }
          },
          { loader: 'postcss-loader', options: { sourceMap: true } }
        ]
      },
      {
        test: /\.scss$/,
        exclude: /(\/Users\/xxx\/public\-web\/src)/,
        use: [
          { loader: 'style-loader', options: {} },
          { loader: 'css-loader', options: {} },
          { loader: 'postcss-loader', options: { sourceMap: true } },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              sassOptions: {
                includePaths: [ '/Users/xxx/public-web/src/styles' ]
              }
            }
          }
        ]
      },
      {
        test: /\.css$/,
        exclude: /(\/Users\/xxx\/public\-web\/src)/,
        use: [
          { loader: 'style-loader', options: {} },
          { loader: 'css-loader', options: {} },
          { loader: 'postcss-loader', options: { sourceMap: true } }
        ]
      },
      {
        test: /\.(woff|woff2|ttf|eot|svg)(\?v=[a-z0-9]\.[a-z0-9]\.[a-z0-9])?$/,
        use: [ { loader: 'url-loader', options: { limit: 100000 } } ]
      },
      {
        test: /\.(gif|png|jpg)$/,
        use: [ { loader: 'url-loader', options: { limit: 8192 } } ]
      },
      {
        test: /\.m?js$/,
        type: 'javascript/auto',
        resolve: { fullySpecified: false }
      }
    ]
  },
  entry: {
    babelPolyfill: 'babel-polyfill',
    fetchPolyfill: 'whatwg-fetch',
    vendor: [ 'react', 'react-redux', 'react-router-dom', 'redux' ],
    app: [
      '/Users/xxx/public-web/src/main.js',
      'webpack-hot-middleware/client?path=http://192.168.4.62:3050/__webpack_hmr'
    ]
  },
  output: {
    filename: '[name].[fullhash].js',
    path: '/Users/xxx/public-web/dist',
    publicPath: 'http://192.168.4.62:3050/'
  },
  plugins: [
    DefinePlugin {
      definitions: {
        'process.env': { NODE_ENV: '"development"' },
        NODE_ENV: 'development',
        __DEV__: true,
        __PROD__: false,
        __TEST__: false,
      }
    },
    HtmlWebpackPlugin {
      options: {
        template: '/Users/xxx/public-web/src/index.html',
        templateContent: false,
        templateParameters: [Function: templateParametersGenerator],
        filename: 'index.html',
        publicPath: 'auto',
        hash: false,
        inject: 'body',
        scriptLoading: 'blocking',
        compile: true,
        favicon: false,
        minify: { collapseWhitespace: true },
        cache: true,
        showErrors: true,
        chunks: 'all',
        excludeChunks: [],
        chunksSortMode: 'auto',
        meta: {},
        base: false,
        title: 'Webpack App',
        xhtml: false
      },
      childCompilerHash: undefined,
      assetJson: undefined,
      hash: undefined,
      version: 4
    },
    HotModuleReplacementPlugin { options: {} }
  ]
}
```

**Comment by evilebottnawi** [comment] 2020-10-13 14:32
Do you have the error when you run dev server or just simple build? Can you try to remove `webpack-hot-middleware/client?path=http://192.168.4.62:3050/__webpack_hmr`?

**Comment by gtwilliams03** [comment] 2020-10-13 14:45
I get the error when I run a build or dev server.

**Comment by gtwilliams03** [comment] 2020-10-13 14:46
I also get the error with or without the `webpack-hot-middleware` entry.

**Comment by egs33** [comment] 2020-10-13 15:08
I was getting the same error in my project.
But, using `sass` package instead of `node-sass` solved the error. (for sass-loader)

**Comment by evilebottnawi** [comment] 2020-10-13 15:19
@gtwilliams03 maybe you can provide more stack?

**Comment by evilebottnawi** [comment] 2020-10-13 15:20
@egs33 Can you create minimum reproducible test repo?

**Comment by egs33** [comment] 2020-10-13 15:28
@evilebottnawi I made a repository to reproduce. https://github.com/egs33/webpack5-cache-error

**Comment by evilebottnawi** [comment] 2020-10-13 15:31
@egs33 big thanks, found the problem

**Comment by gtwilliams03** [comment] 2020-10-13 16:37
@egs33 Thank you so much!  I was trying to figure out how to break the project apart to come up with a reproducible repo... Much appreciated!

**Comment by evilebottnawi** [comment] 2020-10-13 16:38
@gtwilliams03 anyway try to disable cache and look on your error, you need to fix it

**Comment by gtwilliams03** [comment] 2020-10-13 16:43
@evilebottnawi I don't get any errors when I set `cache: false`?

**Comment by gtwilliams03** [comment] 2020-10-13 16:47
In my OP, I don't get any errors with `cache: false`.  Never have.  That's what has baffled me.

**Comment by evilebottnawi** [comment] 2020-10-13 17:10
@gtwilliams03 this problem happens only when you have resolving errors

**Comment by gtwilliams03** [comment] 2020-10-13 17:15
Sorry for asking a dumb question, but how do I see the resolving errors when they don't show up in the terminal?

**Comment by evilebottnawi** [comment] 2020-10-13 17:31
@gtwilliams03 it should be shown in `stats` or in terminal if you use `webpack-cli`

**Comment by gtwilliams03** [comment] 2020-10-13 18:00
It seems to be failing before the `stats` get returned.

**Comment by evilebottnawi** [comment] 2020-10-13 18:10
@gtwilliams03 maybe do you can create reproducible repo too? I want to investigate, maybe we have two different errors :smile:

**Comment by gtwilliams03** [comment] 2020-10-13 21:32
I am still trying to figure out what module isn't resolving.  The webpack-cli is dying before I can get meaningful output.  

```
58% building 7/8 entries 3440/3600 dependencies 727/939 modules[webpack-cli] Promise rejection: TypeError: Cannot read property 'length' of undefined
```

**Comment by gtwilliams03** [comment] 2020-10-14 01:32
I added `console.log(newRequest)` at line 138 of `ResolverCachePlugin` and this is the last output which prints before it hangs:

```
{
  _ResolverCachePluginCacheMiss: true,
  context: {},
  path: '/Users/xxx/public-web/node_modules/bootstrap/scss',
  request: './utilities/_stretched-link'
}
{
  _ResolverCachePluginCacheMiss: true,
  context: {},
  path: '/Users/xxx/public-web/node_modules/bootstrap/scss',
  request: './utilities/_text'
}
{
  _ResolverCachePluginCacheMiss: true,
  context: {},
  path: '/Users/xxx/public-web/node_modules/bootstrap/scss',
  request: './utilities/_visibility'
}
{
  _ResolverCachePluginCacheMiss: true,
  context: {},
  path: '/Users/xxx/public-web/node_modules/bootstrap/scss',
  request: './_print'
}
{
  _ResolverCachePluginCacheMiss: true,
  context: {
    issuer: '/Users/xxx/public-web/node_modules/bootstrap/scss/bootstrap.scss',
    compiler: 'client'
  },
  path: '/Users/xxx/public-web/node_modules/bootstrap/scss',
  request: '../../css-loader/dist/runtime/api.js'
}
```

**Comment by sokra** [comment] 2020-10-14 03:43
I wonder why webpack-cli suppresses the stack trace...

**Comment by gtwilliams03** [comment] 2020-10-14 04:51
Somehow there is an `undefined` value getting passed into the `ResolverCachePlugin` so line 41 in `enhanced-resolve/lib/util/path` throws an error because p is not a string:

```
switch (p.length)
```

I changed this line to:

```
switch ((p || '').length)
```
and it works fine.  No idea what path I have in my project that is creating the undefined value.

**Comment by sokra** [comment] 2020-10-14 10:29
There shouldn't be a undefined value there. Seems like something is passing `undefined` to `resolve`. Maybe you are able to track this down by inserting a `if(!request)` somewhere higher in the stack trace. Probably a loader via `getResolve()` or `resolve` (see `NormalModule.js` createLoaderContext.

**Comment by gtwilliams03** [comment] 2020-10-14 11:32
OK - I will try that.  Interestingly, when I returned the getPath file to its original state, webpack still ran correctly.  I had to delete the .cache directory in node_modules to get the error to return.

**Comment by gtwilliams03** [comment] 2020-10-14 12:18
Line 423 in Resolver.js (`const parsedIdentifier = parseIdentifier(identifier);`) is returning a string `'undefined'` as the first element `part.request` and the exception throws right after that.

Outputting recent parsedIdentifiers:

```
[ 'react', '', '' ]
[ './isDocument', '', '' ]
[ './mixins/_alert', '', '' ]
[ './mixins/_buttons', '', '' ]
[ './createPopper.js', '', '' ]
[ '../utils/computeOffsets.js', '', '' ]
[ '../enums.js', '', '' ]
[ '../utils/getBasePlacement.js', '', '' ]
[ '../utils/getFreshSideObject.js', '', '' ]
[ '../utils/getVariation.js', '', '' ]
[ '../utils/detectOverflow.js', '', '' ]
[ '../dom-utils/getOffsetParent.js', '', '' ]
[ '../dom-utils/getLayoutRect.js', '', '' ]
[ '../utils/within.js', '', '' ]
[ '../utils/getAltAxis.js', '', '' ]
[ '../utils/getMainAxisFromPlacement.js', '', '' ]
[ '../utils/computeAutoPlacement.js', '', '' ]
[ '../utils/getOppositeVariationPlacement.js', '', '' ]
[ '../utils/getOppositePlacement.js', '', '' ]
[ '../dom-utils/getComputedStyle.js', '', '' ]
[ '../dom-utils/getDocumentElement.js', '', '' ]
[ '../dom-utils/getWindow.js', '', '' ]
[ '../dom-utils/instanceOf.js', '', '' ]
[ '../utils/expandToHashMap.js', '', '' ]
[ '../utils/mergePaddingObject.js', '', '' ]
[ '../dom-utils/contains.js', '', '' ]
[ 'querystring', '', '' ]
[ './util', '', '' ]
[ 'punycode', '', '' ]
[ 'undefined', '', '' ]
[webpack-cli] Promise rejection: TypeError: Cannot read property 'length' of undefined
[webpack-cli] TypeError: Cannot read property 'length' of undefined
    at getType (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/util/path.js:41:12)
    at Resolver.isPrivate (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:446:10)
    at Resolver.parse (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:430:25)
    at /Users/xxx/public-web/node_modules/enhanced-resolve/lib/ParsePlugin.js:33:29
    at _next0 (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/xxx/public-web/node_modules/webpack/lib/cache/ResolverCachePlugin.js:199:17
    at Hook.eval [as callAsync] (eval at create (/Users/xxx/public-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Resolver.doResolve (/Users/xxx/public-web/node_modules/enhanced-resolve/lib/Resolver.js:398:16)
    at doRealResolve (/Users/xxx/public-web/node_modules/webpack/lib/cache/ResolverCachePlugin.js:138:13)
```

**Comment by gtwilliams03** [comment] 2020-10-14 12:24
So `parse(identifier)` at line 412 of Resolver.js is `undefined` - looking to what calls parse...

**Comment by gtwilliams03** [comment] 2020-10-14 12:27
Adding this line to Resolver.js seems to make my build finish with no errors:

```
	parse(identifier) {
		const part = {
			request: "",
			query: "",
			fragment: "",
			module: false,
			directory: false,
			file: false,
			internal: false
		};
		if (!identifier) return part; // <- added this line
		const parsedIdentifier = parseIdentifier(identifier);
```

**Comment by gtwilliams03** [comment] 2020-10-14 12:40
This is the request coming in to ResolverCachePlugin.doResolve: 

```
{
  _ResolverCachePluginCacheMiss: true,
  context: {},
  path: '/Users/xxx/public-web/src/routes/Admin',
  request: undefined
}
```

**Comment by evilebottnawi** [comment] 2020-10-14 12:49
@gtwilliams03 Same problem, thanks!

**Comment by gtwilliams03** [comment] 2020-10-14 13:37
Anything more I can do to help debug?

**Comment by evilebottnawi** [comment] 2020-10-14 13:38
@gtwilliams03 no need, thanks for the issue

**Comment by gtwilliams03** [comment] 2020-10-14 16:41
One last comment (I hope 👍):  Each repo that I have that has a src/routes/Admin folder failed - every other one that did not, worked.  Strange coincidence?  Probably.  But I pass it along.

**Comment by sokra** [comment] 2020-10-20 15:50
@evilebottnawi what's the status of this?

**Comment by evilebottnawi** [comment] 2020-10-20 15:54
@sokra Need fix, easy to reproduce, if a loader can't resolve (or can't ofund), for example using `this.getResolve`, you will got the problem

**Comment by evilebottnawi** [comment] 2020-10-20 15:56
Simple example https://github.com/webpack/webpack/issues/11668#issuecomment-707820520

**Comment by johnthecat** [comment] 2020-10-22 15:02
@sokra Hi, is there any estimate on this issue? Migration in my company is blocked by this bug, but, unfortunately, we do not have free time to do PR ourselves 😔

**Comment by evilebottnawi** [comment] 2020-10-22 15:05
@johnthecat this problem appears when something can't be resolved, it should not blocker for you, because you still need to fix resolving problems

**Comment by joakimriedel** [comment] 2020-10-22 15:43
If this is a resolving problem - could someone please elaborate or post a link on how to debug and find the eventual culprit? I have a fully working build, no errors or warnings (unless I enable filesystem cache with path to config that is..), no runtime errors, but still can't enable file system cache due to this issue.

**Comment by evilebottnawi** [comment] 2020-10-22 15:47
@joakimriedel interesting, can you provide reproducible test repo?

**Comment by joakimriedel** [comment] 2020-10-22 17:22
@evilebottnawi I'll try my best, it's a pretty big project evolved during many years and versions of Webpack so I'll need to break it down a bit first. During the last hour, I got at least the following findings;

At this line: https://github.com/webpack/enhanced-resolve/blob/0f51a8cf62b47cde4f57977cf4a205d832f8da69/lib/ParsePlugin.js#L33

the `request` object is supposed to have a `request `key (`request.request`) but this is the request object sent:

```json
{"_ResolverCachePluginCacheMiss":true,"context":{},"path":"C:/Users/<redacted>/wwwroot/src/css"}
```

This lead me to put a debug log at this line: https://github.com/webpack/enhanced-resolve/blob/0f51a8cf62b47cde4f57977cf4a205d832f8da69/lib/Resolver.js#L398

```js
if (/\/src\/css$/.test(request.path)) {
				console.log(JSON.stringify(hook));
				console.log(JSON.stringify(request));
				console.log(JSON.stringify(message));
			}
```

Which lets me see earlier in the process that the mysterious path comes from resolving `bootstrap/scss/bootstrap` which I do within a scss file like this:

```scss
/* bootstrap scss bundle */
@import "~bootstrap/scss/bootstrap";
```

using the following loader configuration

```js
{
          test: /\.scss$/,
          use: [
            {
              loader: "style-loader", // injects css into DOM
            },
            {
              loader: "css-loader",
              options: { sourceMap: !env.production, importLoaders: 1 },
            },
            {
              loader: "postcss-loader",
              options: {
                postcssOptions: {
                  plugins: [
                    [
                      "postcss-preset-env",
                      {
                        // Options
                      },
                    ],
                  ],
                },
                sourceMap: !env.production,
              },
            },
            {
              loader: "sass-loader",
              options: {
                sourceMap: !env.production,
                sassOptions: {
                  outputStyle: "expanded", // keeps comments, such as autoprefixer commands, in output css file
                },
              },
            },
          ],
        },
```

I suspect some combination of Bootstrap and Webpack and sass-loader is involved. I will need further time to generate a repo, but perhaps others like @johnthecat can confirm if they also use Bootstrap in their configuration?

**Comment by jdelStrother** [comment] 2020-10-22 17:25
I'm seeing similar issues, and also have a .scss file containing:

```
@import "~bootstrap/scss/_functions.scss";
@import "~bootstrap/scss/_variables.scss";
```

**Comment by evilebottnawi** [comment] 2020-10-22 17:26
Thanks I will look at this in near future, a lot of issues :disappointed:

**Comment by evilebottnawi** [comment] 2020-10-22 19:13
Hm, look like bug is not in webpack, problem with `sass-loader`, webpack just generate ugly error, WIP

**Comment by gtwilliams03** [comment] 2020-10-22 19:14
@jdelStrother @joakimriedel Yes - my project also contains `bootstrap` and `react-bootstrap`

**Comment by joakimriedel** [comment] 2020-10-22 19:16
I'm sorry for the bootstrap red herring. It turned out to be fontawesome.

I have a repro here: https://github.com/joakimriedel/webpack-cache-bug-repro

**Comment by evilebottnawi** [comment] 2020-10-22 19:27
Yes, I was right here two problems:
- bug in `sass-loader`
- ugly error from webpack when you run:

```js
const resolve = loaderContext.getResolve(options); 

resolve(context,  undefined);
// and resolve(undefined,  undefined)
```

WIP on first

**Comment by evilebottnawi** [comment] 2020-10-22 20:09
https://github.com/webpack-contrib/sass-loader/pull/896, release will be in near future

**Comment by evilebottnawi** [comment] 2020-10-22 20:20
Please try https://github.com/webpack-contrib/sass-loader/releases/tag/v10.0.4

**Comment by evilebottnawi** [comment] 2020-10-22 20:24
@joakimriedel Found how we can improve your build :smile: small change and your time will be `webpack 5.2.0 compiled with 2 warnings in 168 ms` :smile:

**Comment by joakimriedel** [comment] 2020-10-22 20:51
@evilebottnawi can confirm sass-loader 10.0.4 solves the issue I've had with the cache, webpack 5 feels rock solid now! 🎉

In my real project, compile time went from 14440 ms to 1667 ms using the filesystem cache. (on a threadripper)

I'm really curious about the small change to bring the compile time even further down?

**Comment by evilebottnawi** [comment] 2020-10-22 21:00
@joakimriedel Can you try to disable `parallel` for `terser-webpack-plugin` (https://github.com/webpack-contrib/terser-webpack-plugin#parallel)? I think we need improve creating of workers

**Comment by joakimriedel** [comment] 2020-10-22 21:09
@evilebottnawi yes, that shaved the not-cached run down from 14440 ms to 11523 ms, but cached run still around ~1650 ms. Still, thanks for the tip - appreciate it!

**Comment by evilebottnawi** [comment] 2020-10-22 21:14
@joakimriedel Just interesting how much JS assets you have?

**Comment by joakimriedel** [comment] 2020-10-22 21:24
> @joakimriedel Just interesting how much JS assets you have? Hide for other developers (the solution will not be lost)

Not that big, 73 files, 173 kB in total source, but ~30 entrypoints and everything is processed typescript > babel > ie 11 support.

**Comment by drewlustro** [comment] 2020-10-22 23:55
Is this issue fixed for `enhanced-resolve`  ? I'm still experiencing it.

**Comment by evilebottnawi** [comment] 2020-10-23 11:21
@drewlustro Yes (https://github.com/webpack/enhanced-resolve/pull/261), but you will have error in this case, so we need to find loader with problems, can you provide config/minimum reproducible test repo

**Comment by evilebottnawi** [comment] 2020-10-23 13:28
Fixed in both places (update deps to latest, i.e. `sass-loader` and `enhanced-resolve`), please leave feedback

**Comment by evilebottnawi** [comment] 2020-10-23 19:15
@joakimriedel Can you try https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v5.0.1 and provde some feedback on performance? Try it on `node@12` or `node@14`

**Comment by joakimriedel** [comment] 2020-10-24 09:44
@evilebottnawi might bring some small improvements on a cold cache, but on warm cache it seems to perform equally (node v12.18.4) 

I think most of my processing time is spent exporting json data for async import of CLDR and Globalize.js for our multilingual application. Marking as off-topic but any help improving build times is appreciated, could have a separate thread about this somewhere.

**Comment by evilebottnawi** [comment] 2020-10-24 12:17
@joakimriedel Will be great to look at example, maybe part of application and configurations, hard to say without it

**Closed** 2020-10-26 08:13 UTC
Labels: critical-bug, webpack-5

**Comment by phantoxe** [comment] 2021-09-23 14:15
I JUST UPGRADE WEBPACK in my PROJECT and works fine!
