### ISSUE TITLE
webpack stay pending sometime (dont complete and close process)

### ISSUE THREAD

**Issue by ebrahimiaval** [webpack/webpack#9345] opened 2019-07-01 11:00 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
webpack for equal codes, sometime complete successfully  and sometime stay pending with out any error.
Of course jsut for server config (it's ok in client). 
my server config: 
```
{
                name: 'server',
                mode: 'production',
                target: 'node',
                performance: {hints: false},
                entry: [`${srcDir}/render/server.js`],
                output: {
                    path: distDir,
                    filename: 'server.js',
                    libraryTarget: 'commonjs2',
                    publicPath: distDir,
                },
                module: {
                    rules: [
                        {
                            test: /\.js$/,
                            exclude: /(node_modules[\\\/])/,
                            use: [
                                {
                                    loader: 'babel-loader',
                                }
                            ]
                        },
                        {
                            test: /\.(css|scss)$/,
                            use: [
                                {
                                    loader: 'isomorphic-style-loader',
                                },
                                {
                                    loader: 'css-loader',
                                    options: {
                                        // modules: true,
                                        // localIdentName: '[local]__[hash:base64:5]',
                                        // sourceMap: true
                                        importLoaders: 1
                                    }
                                },
                                {
                                    loader: 'sass-loader',
                                    options: {
                                        // sourceMap: true,
                                        outputStyle: 'compressed',
                                        includePaths: [`${srcDir}/config`]
                                    }
                                }
                            ]
                        }
                    ],
                },
                plugins: [
                    new OptimizeCssAssetsPlugin({
                        cssProcessorOptions: {discardComments: {removeAll: true}}
                    }),
                    new StatsPlugin('stats.json', {
                        chunkModules: true,
                        modules: true,
                        chunks: true,
                        exclude: [/node_modules[\\\/]react/],
                    }),
                ],
    }
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

"webpack": "^4.35.0",
"webpack-cli": "^3.3.5",
"webpack-dev-middleware": "^3.7.0",
"webpack-hot-middleware": "^2.25.0",
"webpack-hot-server-middleware": "^0.6.0"

node: 12.5
os: windows 10

**Comment by evilebottnawi** [comment] 2019-07-01 11:03
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by ebrahimiaval** [comment] 2019-07-01 11:33
edited

**Comment by ebrahimiaval** [comment] 2019-07-01 11:34
> It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

edited

**Comment by evilebottnawi** [comment] 2019-07-01 11:35
Please create reproducible test repo

**Comment by ebrahimiaval** [comment] 2019-07-01 13:42
> Please create reproducible test repo

this is like my project. webpack is good in node 11 but in 12 sometime stay pendding.

https://github.com/ebrahimiaval/dev-rssr

**Comment by ebrahimiaval** [comment] 2019-07-02 05:41
i think we should waiting for webpack 5

**Closed** 2019-07-02 05:41 UTC
