### ISSUE TITLE
[webpack.cache.PackFileCacheStrategy] doesn't works after second edits

### ISSUE THREAD

**Issue by alessiofnes** [webpack/webpack#19077] opened 2024-12-17 12:33 UTC
# Bug report

I'm running a React JS (v19) app with webpack, cache enabled and HRM.  
After compiling app on local env the first edit on any source file is detected and correctly showed on the browser, from the second one webpack detect the file modification, compile, reload browser page but without showing the modification on browser.

I'm using the following webpack config

```
mode: 'development',
cache: {
    type: 'filesystem',
    buildDependencies: {
        config: [__filename]
    }
},
entry: path.join(APP_DIR, 'system', 'main.jsx'),
output: {
    publicPath: "",
    path: BUILD_DIR,
    filename: 'main.[contenthash].js',
    chunkFilename: './chunks/[name].[contenthash].chunk.js'
},
devtool: 'source-map',
resolve: {
    modules: ['node_modules'],
    descriptionFiles: ['package.json'],
    alias: {
        Root: path.resolve(APP_DIR),
        Application: path.resolve(APP_DIR, 'application'),
        System: path.resolve(APP_DIR, 'system')
    },
    extensions: ['.js', '.jsx'],
},
infrastructureLogging: {
    level: 'verbose'
},
module: {
    rules: [
        {
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                options: {
                    plugins: [require.resolve('react-refresh/babel')].filter(Boolean),
                },
            },
        },
        ...
    ]
},
devServer: {
    static: path.join(ROOT_DIR, 'www'),
    hot: true,
    liveReload: true,
    watchFiles: ['./src/**/*'],
    historyApiFallback: true
},
plugins: [
    new ReactRefreshWebpackPlugin(),
    new HtmlWebpackPlugin({
        template: './src/index.ejs',
        inject: false,
        templateParameters: (compilation, assets, options) => ({
                title: `${BRAND_NAME} Area Clienti`,
                prefix: BRAND_PATH,
                files: assets,
                options: options,
                webpackConfig: compilation.options,
                webpack: compilation.getStats().toJson()
        })
    }),
    new MiniCssExtractPlugin({
        filename: '[name].[contenthash].css',
    }),
    new CleanWebpackPlugin()
],
optimization: {
    runtimeChunk: 'single',
    splitChunks: {
        chunks: 'all',
        cacheGroups: {
            vendor: {
                test: /[\\/]node_modules[\\/]/,
                name: 'vendors',
                chunks: 'all',
                priority: -10
            },
        },
    }
}
```

With all modules at the last stable version
```
"dependencies": {
    ...
    "react": "^19.0.0",
    "react-confirm-alert": "^3.0.6",
    "react-cookie-consent": "^9.0.0",
    "react-dom": "^19.0.0",
    "react-ga4": "^2.1.0",
    "react-otp-input": "^3.1.1",
    "react-pdf": "^9.1.1",
    "react-perfect-scrollbar": "^1.5.8",
    "react-player": "^2.16.0",
    "react-router-dom": "^7.0.2",
    "react-select": "^5.8.3",
    "react-simple-wysiwyg": "^3.2.0",
    "react-window": "^1.8.10"
    ...
},
"devDependencies": {
    ...
    "@babel/core": "^7.26.0",
    "@babel/preset-env": "^7.26.0",
    "@babel/preset-react": "^7.26.3",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.15",
    "babel-loader": "^9.2.1",
    "html-webpack-plugin": "^5.6.3",
    "react-refresh": "^0.16.0",
    "webpack": "^5.97.1",
    "webpack-bundle-analyzer": "^4.10.2",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^5.1.0"
    ...
}
```
After starting app with
```
webpack serve --hot --mode development --port 8081 --progress
```
everything works right.  

After first source file edits, these are webpack 'verbose' logs (the paths were partially obscured)

```
[webpack-cli] File '~/src/application/components/MyComponents.jsx' was modified
[webpack-cli] Changed time is Tue Dec 17 2024 12:41:20 GMT+0100 (timestamp is 1734435680007)
[webpack-dev-middleware] Compilation starting...
[webpack-cli] Compiler starting...
[webpack-cli] Compiler is using config: '~/webpack.config.js'
<i> [webpack-dev-middleware] wait until bundle finished: /
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 20.484878 ms
<t> [webpack.cache.PackFileCacheStrategy] check build dependencies: 0.516767 ms
<t> [webpack.cache.PackFileCacheStrategy] restore cache content metadata: 56.262336 ms
[webpack-cli] Compiler finished
[MemoryWithGcCachePlugin] 17726 active entries, 2054 recently unused cached entries
[webpack-dev-middleware] Compilation finished
assets by status 9.93 MiB [cached] 459 assets
assets by status 19.7 MiB [emitted]
assets by path *.js 19.5 MiB
assets by info 62.8 KiB [hmr] 8 assets
asset vendors.b943b7055dd020963268.js 18.1 MiB [emitted] [immutable] (name: vendors) (id hint: vendor) 1 related asset
asset main.b943b7055dd020963268.js 1.32 MiB [emitted] [immutable] (name: main) 1 related asset
asset runtime.b943b7055dd020963268.js 61.7 KiB [emitted] [immutable] (name: runtime) 1 related asset
assets by path ./chunks/*.js 197 KiB
asset ./chunks/src_application_modals_pim_modalAssetPim_jsx.2526266c28b06d07f8e8.chunk.js 50.1 KiB [emitted] [immutable] 1 related asset
asset ./chunks/src_application_******_jsx.6cbe4c8a60cb55548a9a.chunk.js 31.8 KiB [emitted] [immutable] 1 related asset
asset ./chunks/src_application_******_jsx.008cdf3b3fe565ed954f.chunk.js 31.4 KiB [emitted] [immutable] 1 related asset
asset ./chunks/src_application_******_jsx.0f5ac0a01c09ba09f441.chunk.js 31 KiB [emitted] [immutable] 1 related asset
+ 3 assets
asset index.html 3.08 KiB [emitted]
asset runtime.583c47f78b1ead73e333.hot-update.json 318 bytes [emitted] [immutable] [hmr]
Entrypoint main 20.3 MiB (20.9 MiB) = 6 assets 16 auxiliary assets
cached modules 22.9 MiB (javascript) 106 KiB (asset) 851 KiB (css/mini-extract) [cached] 3611 modules
runtime modules 44.1 KiB 20 modules
~/src/application/components/MyComponents.jsx 4.91 KiB [built] [code generated]
webpack 5.97.1 compiled successfully in 4945 ms
[webpack-cli] Compiler is watching files for updates...

```
and everything works right.  

Trying with another file edits the webpack log shows

```
[webpack-cli] File '~/src/application/components/MyComponents.jsx' was modified
[webpack-cli] Changed time is Tue Dec 17 2024 12:42:18 GMT+0100 (timestamp is 1734435738161)
[webpack-dev-middleware] Compilation starting...
[webpack-cli] Compiler starting...
[webpack-cli] Compiler is using config: '~/webpack.config.js'
<i> [webpack-dev-middleware] wait until bundle finished: /
[webpack-cli] Compiler finished
[MemoryWithGcCachePlugin] 14685 active entries, 5095 recently unused cached entries
[webpack-dev-middleware] Compilation finished
assets by status 29.6 MiB [cached] 470 assets
Entrypoint main 20.3 MiB (20.9 MiB) = runtime.b943b7055dd020963268.js 61.7 KiB vendors.470086947626c3e91d67.css 693 KiB vendors.b943b7055dd020963268.js 18.1 MiB main.aaffc9ff0f733312ddf9.css 161 KiB main.b943b7055dd020963268.js 1.32 MiB 15 auxiliary assets
cached modules 22.9 MiB (javascript) 106 KiB (asset) 851 KiB (css/mini-extract) 44.1 KiB (runtime) [cached] 3632 modules
webpack 5.97.1 compiled successfully in 1177 ms
[webpack-cli] Compiler is watching files for updates...
```

From now on, for any changes to the source files, the log is always similar to this above, the browser reloads the page but does not show the change made.  

I would expect the cache to be used for fast compilation and show changes made to source files.

If set `cache: false` works always correctly but with very long compile times as expected.

---

webpack version: 5.97.1  
Node.js version: 22.11.0  
Operating System: Mac OS 14.4.1 (23E224)

**Comment by alessiofnes** [comment] 2024-12-17 13:55
Found w

**Comment by Aryan681** [comment] 2024-12-18 13:38
I’ve **Reproduced** this issue and identified it as a caching/HMR problem . Here changes are not reflected in the browser after the second file edit, even though Webpack recompiles successfully. This seems to be related to caching/HMR.

Here’s what I’ve observed:

- After the initial file change, everything works as expected.
- After subsequent changes, Webpack detects the file modifications, but the browser doesn’t show the updates despite a page reload.

![{88456C3E-CA24-4A4A-BC87-1361E53B7198}](https://github.com/user-attachments/assets/1a68e89c-0d40-4205-a02a-153a2a0c7410)


I’d like to investigate this further and propose a solution. Would it be possible to assign this issue to me?

**Comment by alexander-akait** [comment] 2024-12-18 14:28
Please create a reproducible repository, without it it is difficult for me to identify the problem

I see only:
- `watchFiles: ['./src/**/*'],` and `hot: true`, so any change in JS file will trigger full reload 

So HMR state will be losed

**Comment by Aryan681** [comment] 2024-12-18 14:53
Hello,  

I’ve created a repository to reproduce the issue: [webpack-hmr-issue](https://github.com/Aryan681/webpack-hmr-issue). Below are the steps to set up the project and reproduce the issue on your system:

---

### **1. Clone the Repository**
```bash
git clone https://github.com/Aryan681/webpack-hmr-issue.git
cd webpack-hmr-issue
```

### **2. Install Dependencies**
Ensure you have `Node.js` installed (version 22.11.0 or compatible). Then, install the required dependencies:
```bash
npm install
```

### **3. Run the Development Server**
Start the development server with:
```bash
npm start
```

This will launch the application in your default browser at `http://localhost:8080`.

---

### **4. Observe the Issue**
1. Make any changes  to the JavaScript or JSX files located in the `src/` directory .
2. Save the file and after the 1st change ,notice that the Hot Module Replacement (HMR) does not work as expected:
-    [webpack.cache.PackFileCacheStrategy] doesn't work after second edits.





Let me know if there are any questions or further issues! I’d be happy to assist in debugging and resolving this problem.
@alexander-akait

**Comment by alexander-akait** [comment] 2024-12-18 16:59
Remove:
- `watchFiles: ['./src/**/*']`, `watchFiles` is just to refresh the page for additional files that I am not involved in the bundling, for example PHP.
- Use `import App from "./app";` instead `import App from "./App";`, paths are case independent in macos only, but some unofficial webpack's plugins may be written without taking this into account (I recommend using linter), relying on this behavior is also not safe because there may be developers on your team using a different operating system. We do not validate this automatically because it can greatly slow down performance and recommend using other utilities for this.

After these changes all works fine.

Feel free to feedback

**Closed by alexander-akait** 2024-12-18 16:59 UTC
Labels: question
