### ISSUE TITLE
Dynamic Import Retry

### ISSUE THREAD

**Issue by childrentime** [webpack/webpack#18505] opened 2024-06-17 08:08 UTC
## Feature request

**What is the expected behavior?**

When regular JS resources fail to load, retrying their errors is quite straightforward - you can simply listen to the `window.error` event. However, this approach does not work for JS resources that are dynamically imported.

To achieve this, one would need to perform complex hacks on webpack's internal functionality, such as defining a plugin to manipulate `RuntimeGlobals.require`.

**What is motivation or use case for adding/changing the behavior?**

There is a desire for a standardized way to address this issue.

https://stackoverflow.com/questions/56772771/how-to-manually-load-webpack-async-chunks-when-any-dynamic-import-fails-to-load
https://stackoverflow.com/questions/62063737/what-is-the-best-practice-for-dealing-with-a-failed-dynamic-import-in-webpack
https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/blob/master/src/index.ts

**How should this be implemented in your opinion?**

Add a webpack configuration option, such as dynamic.hosts. When a request for a dynamically imported JS resource fails, it will automatically retry requests to other CDN domains in the hosts.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment] 2024-06-19 13:48
Duplicate of https://github.com/webpack/webpack/issues/5115#issuecomment-310213277, you can make a small helper to implement this or yes, you can use create a plugin for this, I don't think we should implement it in the core, because fallback logic can be very different

Anyway feel free to feedback

**Closed by alexander-akait** 2024-06-19 13:48 UTC
