### ISSUE TITLE
ModuleConcatenation bailout: Module is not an ECMAScript module

### ISSUE THREAD

**Issue by pronebird** [webpack/webpack#7449] opened 2018-05-30 12:03 UTC
# Bug report

**What is the current behavior?**

I receive a lot of stuff like this:

```
chunk    {0} main.bundle.js (main) 1.92 MiB [entry] [rendered]
        > ./app/main.js main
       [2] external "path" 42 bytes {0} [depth 1] [built]
           ModuleConcatenation bailout: Module is not an ECMAScript module
```

Which then fails to build the bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by montogeek** [comment] 2018-05-30 12:11
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by montogeek** [comment] 2018-05-30 12:11
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by montogeek** 2018-05-30 12:11 UTC

**Comment by pronebird** [comment] 2018-05-30 12:22
@montogeek you don't have to close issues that you don't have an answer for. Somebody else may come by with the same issue and help resolve it. I have a very basic configuration for compiling node code.
