### ISSUE TITLE
Fails to parse BigInteger Literal

### ISSUE THREAD

**Issue by chrisui** [webpack/webpack#9077] opened 2019-04-29 23:05 UTC
# Bug report

**What is the current behavior?**

```
const bigInteger = 0n;
```

Causes the following error:

```
Module parse failed: Identifier directly after number (0:20)
You may need an appropriate loader to handle this file type.
```

Compiling from [typescript ](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html) to `esnext`.

[Repro Repo](https://github.com/chrisui/bigint-literal-webpack-issue)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

```
const bigInteger = 0n;
```

A script with the above contents should be parsed and emitted without error.

**Other relevant information:**
webpack version:  4.30.0
Node.js version: 8.11.3
Operating System: Windows 10
Additional tools: typescript, awesome-typescript-loader

**Comment by evilebottnawi** [comment] 2019-04-30 10:01
Can you create minimum reproducible test report?

**Comment by chrisui** [comment] 2019-04-30 11:17
@evilebottnawi is there a specific format for a test report? Happy to provide. If you attempt to build a bundle with that one line script above it will fail.

**Comment by evilebottnawi** [comment] 2019-04-30 11:24
reproducible test repo without typescript, maybe bug in typescript, but i don't think

**Comment by chrisui** [comment] 2019-04-30 13:14
That syntax is not typescript.

https://github.com/tc39/proposal-bigint
http://2ality.com/2017/03/es-integer.html#core-parts-of-the-proposal

**Comment by evilebottnawi** [comment] 2019-04-30 13:19
I know what is not typescript syntax, typescript - is transpiler and can have problems also, we use BigInt in our project and no problems with webpack, so i ask you create minimum reproducible test repo without typescript

**Comment by chrisui** [comment] 2019-04-30 13:39
@evilebottnawi gotcha. Here's a repro https://github.com/chrisui/bigint-literal-webpack-issue

```
$ npm install
$ npm run build

Hash: e61d89767dc3ddcef2e7
Version: webpack 4.30.0
Time: 76ms
Built at: 04/30/2019 2:39:14 PM
 1 asset
Entrypoint main = main.js
[0] ./src/index.js 168 bytes {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/index.js 1:20
Module parse failed: Identifier directly after number (1:20)
You may need an appropriate loader to handle this file type.
> const bigInteger = 0n;
```

**Comment by evilebottnawi** [comment] 2019-04-30 13:45
hm, we support stage 4 only without babel/transpiler (except dynamic imports), but BigInt in stage 3

**Comment by chrisui** [comment] 2019-04-30 14:12
Ah, makes sense. 

Bit of a shame since Stage 3 is all but complete but understandable.

**Comment by evilebottnawi** [comment] 2019-04-30 14:17
Sometimes proposals on stage 3 were declined, so i don't think it is good idea support this out of box

**Comment by evilebottnawi** [comment] 2019-09-23 18:42
I am closing issue, as i written above, it will be resolved when `acorn` implement this out of box, right now i recommend use babel-loader, anyway thanks for issue. Anyway thanks for issue

**Closed by evilebottnawi** 2019-09-23 18:42 UTC

**Comment by AndreasGassmann** [comment] 2019-12-16 12:35
It looks like this is already at stage 4: https://github.com/tc39/proposal-bigint

**Comment by azizj1** [comment] 2020-01-15 12:50
Is there a workaround to using it with babel?

**Comment by AndreasGassmann** [comment] 2020-01-15 13:19
@azizj1 I didn't find any last month, I ended up changing the code to use `BigInt(1)` instead of `1n`

**Comment by azizj1** [comment] 2020-01-15 13:55
I was able to use `@babel/plugin-syntax-bigint` plugin to workaround it.

**Comment by talalalamdar** [comment] 2020-10-23 13:02
Worked for me after updating my node version to v`10.4.0`, my old version was v10.2.0

**Comment by headfire94** [comment] 2023-09-27 17:35
> @azizj1 I didn't find any last month, I ended up changing the code to use BigInt(1) instead of 1n

@AndreasGassmann do you know if any plugin exist to replace it automatically?
