### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack#12964] opened 2021-03-23 11:26 UTC
# Bug report

**What is the current behavior?**

There's an issue report https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/328 on `react-refresh-webpack-plugin`, and I happened to encounter it as well.

At fist glance it seems to be a bug over there, however, it might be a bug in webpack after I debug with a breakpoint. 

![image](https://user-images.githubusercontent.com/1091472/112138846-f69e5580-8c0c-11eb-9c58-4fc588a9abff.png)

![image](https://user-images.githubusercontent.com/1091472/112138428-7546c300-8c0c-11eb-9697-45c991c3a147.png)

Hence I'm reposting it here.

**If the current behavior is a bug, please provide steps to reproduce.**

See https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/328#issuecomment-804797961 for the steps.

**What is the expected behavior?**

No error should happen.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment] 2021-03-23 12:36
That's a webpack bug

**Comment by sokra** [comment] 2021-03-23 16:29
It's a problem when new split chunks where introduced. These would need to be downloaded. It's a bit tricky to decide which one are relevant. I need to think about that a bit.

**Comment by sokra** [comment] 2021-03-24 12:41
Ok while this is still an issue. webpack 5.28.0 will make it appear much less often.

Another bug made modules losing it's side effects information on rebuild which causes a large change to the module graph, which caused the change in split chunks.

**Comment by Haraldson** [comment] 2021-03-25 12:54
I closed my issue in `pmmmwh/react-refresh-webpack-plugin` as it’s obviously not an issue with that plugin. As per my closing comment in that issue, I have chipped away and have made a [pretty minimal repro](https://github.com/Haraldson/refresh-minimal-repro) available. Hope it can be of some value.

**Comment by Dave3of5** [comment] 2021-03-25 13:15
I'm seeing something similar with splitChunks set to 'all' I'm getting a similar error (I'm not using this plugin though). With splitChunk removed the output works correctly.

**Comment by csvan** [comment] 2021-03-29 22:42
Seeing this error in conjunction with Module Federation, though it most likely isn't due to that alone.

Strange thing is I don't recally seeing this on versions earlier than 5.27, but it is now constant.

**Comment by csvan** [comment] 2021-03-29 22:58
Unlike @Dave3of5 however, removing `splitChunks: 'all'` does not solve the issue.

**Comment by alexander-akait** [comment] 2021-03-31 11:59
@csvan Can you provide small repo?

**Comment by sokra** [comment] 2021-04-01 18:57
This error message is pretty general. Please don't think this is the same issue when you get the same error message. Create new issues.

**Comment by darkyndy** [comment] 2021-04-15 15:50
I also noticed this issue, when using `ModuleFederationPlugin` and some specific settings for the `splitChunks`.

`splitChunks.chunks` -> should not be set or set to `async` (default) , anything else will cause the error mentioned
`splitChunks.maxSize` -> should not be set, if this is set will cause the error mentioned

**Comment by ryan-olejnik** [comment] 2021-04-26 02:24
I am also having this issue when using the `ModuleFederationPlugin` on the host app.

**Comment by juanger** [comment] 2021-05-18 20:11
I got a workaround by creating a custom chunkIds plugin (based on the NamedChunkIdsPlugin) that ensures each of my federated modules uses different chunk ids even for files that have the same name (I append a federated module name to the chunk ids)

I have a setup like the following:

* FederatedModuleA and FederatedModuleB use FileX
* FileX imports FileY
* The FederatedModuleA chunk for FileX doesn't contain FileY (not sure why, maybe because the file is big and sometimes it gets split into multiple chunks?)
* The FederatedModuleB chunk for fileX does contain FileY
* When FederatedModuleB tries to load FileX, it already has it in installedChunks (from FederatedModuleA), proceeds to evaluate it but it fails to import FileY with `Cannot read property 'call' of undefined`.

My federated modules are generated in separate compilers and include some files that have the same name (and sometimes the same content) but are not marked as shared (FileX and FileY). Upon inspection, the generated chunks for each of them are named the same, but have different content (even if the original files had the same content).

As a result, the imports inside the chunk fail depending on which one is loaded first because the names clash in installedChunks, it thinks it already installed it, but it evaluated the one with different content and it is not loading some of its dependencies in that context. Also, I think something weird is going on with installedChunks, since it contains `0` for things that were not loaded from that entrypoint (leaking context?).

@sokra @alexander-akait My setup is difficult to reproduce but maybe these details give some more info for potential fixes?

**Comment by alexander-akait** [comment] 2021-05-19 11:21
@juanger Sorry no, you should not got `Cannot read property 'call' of undefined`, if you got this problem, it means bug in webpack or problem in configuration, maybe you can provide configuration (or the main idea how you use module federation with configurations)? Also will be great to look at `output` options

**Comment by ydmitry** [comment] 2021-05-29 11:10
Have the same issue with prod build, with using module federation and it's shared packages. When I change one line of code - like calling the method of already imported class, it breaks with the same error in the topic. When remove - everything is fine. What changed - the build itself, new numbers for chunks, etc.

Not really possible create reproducible repo as it need to have many dependencies in it and number of chunk should be specific during the build. Can't share repo when it reproduces as it's private...

**Comment by alexander-akait** [comment] 2021-05-29 12:41
@ydmitry What is webpack version?

**Comment by ydmitry** [comment] 2021-05-29 13:17
@alexander-akait tried with 5.38.1. It also uses Angular 12 (tried with 11 too), shared packages are in monorepo configured with TS config paths into ts files. It can be Angular CLI issue, but how can be explained that if I remove one specific method call (not import, and import is still used after removing), it works OK?

**Comment by alexander-akait** [comment] 2021-05-29 13:20
@ydmitry With the maximum probability, I think that you have circular dependencies

**Comment by ydmitry** [comment] 2021-05-29 18:06
@alexander-akait Fixed circular dependencies those were found with `madge`, but it did't help. But after set `optimization.splitChunks` to `false` - it seems to working now

**Comment by AHRL** [comment] 2021-06-30 07:25
Is this problem solved?

**Comment by sokra** [comment] 2021-06-30 07:29
afaik yes

**Closed by sokra** 2021-06-30 07:29 UTC
Labels: bug, webpack-5

**Comment by AHRL** [comment] 2021-06-30 11:33
I updated webpack from 4.29.6 to 5.40.0. The local build succeeded. But when I published my project, a similar error occurred.
![image](https://user-images.githubusercontent.com/31957724/123953592-f7980d80-d9d9-11eb-88a4-9570a68f3af3.png)

**Comment by AHRL** [comment] 2021-06-30 11:44
I updated webpack from 4.29.6 to 5.40.0. The local build succeeded. But when I published my project, a similar error occurred.What could be the cause of the error?
![image](https://user-images.githubusercontent.com/31957724/123954877-7fcae280-d9db-11eb-8b2f-6fd426259e8d.png)
![image](https://user-images.githubusercontent.com/31957724/123954939-983afd00-d9db-11eb-8427-5589d6b18fd6.png)

**Comment by alexander-akait** [comment] 2021-06-30 11:50
@AHRL please provide reproducible example?

**Comment by AHRL** [comment] 2021-06-30 12:09
@alexander-akait 
https://codesandbox.io/s/trusting-tree-q39oi?file=/build/webpack.dev.conf.js
Here are some of my configurations.

**Comment by alexander-akait** [comment] 2021-06-30 12:11
@AHRL Weird, files are empty...

**Comment by AHRL** [comment] 2021-06-30 13:16
@alexander-akait sorry,please retry.

**Comment by AHRL** [comment] 2021-07-01 03:39
@alexander-akait 
I modified my configuration. 
`
runtimeChunk: {
            name: 'manifest'
        },
`
![image](https://user-images.githubusercontent.com/31957724/124060337-6bc8c480-da5f-11eb-8fae-85b9125bae04.png)
This is mainifest file.   https://codesandbox.io/s/trusting-tree-q39oi?file=/manifest.js

**Comment by AHRL** [comment] 2021-07-01 05:11
![image](https://user-images.githubusercontent.com/31957724/124068851-da148380-da6d-11eb-9ca8-9dc318568296.png)

**Comment by AHRL** [comment] 2021-07-01 05:33
I solved this problem by adding the following configuration.Thanks~
`
concatenateModules: false
`

**Comment by alexander-akait** [comment] 2021-07-01 15:47
It should work without using `concatenateModules: false`

**Comment by alexander-akait** [comment] 2021-07-01 15:54
You use webpack v4 due `vue-cli-service`, run `npm ls webpack` and look at output, `vue-cli-service` still use `webpack` v4, you have mixed version and get a lot of problems with it like above

**Comment by alexander-akait** [comment] 2021-07-01 15:55
Original bug was solved
