### ISSUE TITLE
Webpack fails silently when named import doesn't exist

### ISSUE THREAD

**Issue by aherriot** [webpack/webpack#3158] opened 2016-10-17 14:24 UTC
**I'm submitting a feature request**
**Webpack version:**
2.1.0-beta.21

**Please tell us about your environment:**
Linux

**Current behavior:**
When I try to import a named import, it fails silently if the name import does not exist. I wish webpack would fail loudly when it cannot find the import at build time

For example:

```
// file1.js
const var1 = 'var1'
export { var1 }
```

and

```
// file2.js
import { var2 } from './file1'
// at this point, var2 is undefined at runtime because it was never exported from file1.js
```

**Desired behavior:**
Instead, I want it to fail at build time. Is there a webpack option or some other technique I can use to catch this error sooner?
- **What is the motivation / use case for changing the behavior?**
  This will catch typos at build time, and prevent a lot of headaches caused by undefined imports.
- **Browser:** [all ] 
- **Language:** [ES6/7]

**Comment by TheLarkInn** [comment] 2016-10-17 17:32
Would you mind updating to webpack 2.1.0-beta.25 and confirm this is an issue or not still?

**Comment by aherriot** [comment] 2016-10-17 19:20
This issue still persists with webpack2.1.0-beta.25 and if I remember correctly it all existed in webpack 1, though I didn't test it.

**Comment by sokra** [comment] 2016-10-18 10:48
Babel configuration?

**Comment by aherriot** [comment] 2016-10-18 13:04
This issue is not specific to only files that use the babel loader. I am thinking that I can write a custom loader to check for this, but it would be nice if webpack checked for undefined imports by default, or at least through an option.

**Comment by Kovensky** [comment] 2016-10-19 01:13
The issue is with webpack 2's harmony imports handler.

I can see, in the code, that there is [some code to deal with that case](https://github.com/webpack/webpack/blob/master/lib/dependencies/HarmonyImportSpecifierDependency.js#L30), but it doesn't seem to get invoked in cases like in the sample.

The only thing helping in those cases is eslint-plugin-imports.

**Comment by SpaceK33z** [comment] 2017-01-28 19:15
@Kovensky do you know if this issue is still relevant? And if not, could you close it?

**Comment by aherriot** [comment] 2017-01-29 02:13
Simple webpack examples seem to work, but I have a complex project at work that has this problem still. I am not sure what the difference is.

**Comment by SpaceK33z** [comment] 2017-01-29 09:23
@aherriot is that with the latest 2.2.0 version?

**Comment by adrianhelvik** [comment] 2017-06-14 17:55
The behaviour is still the same. This is a really useful feature in native ES2015 modules and in the most recent version of create-react-app. Is there a way to enable it? Including it as a default would definitely warrant a major version bump, but in my opinion it is the right choice to do asap considering that's the way the native implementation works.

**Comment by sokra** [comment] 2017-08-22 07:07
There is a warning for this case now

**Closed by sokra** 2017-08-22 07:07 UTC
Labels: webpack-2, X0: need more information, X9: waiting on confirmation

**Comment by aherriot** [comment] 2017-08-22 19:37
@sokra What version was this fixed in?

**Comment by pascalpp** [comment] 2017-11-28 20:00
@aherriot did you ever figure this out in your project? I'm trying to migrate a large CommonJS codebase to wepback3 and ES modules, can't figure out how to get these warnings.

**Comment by pascalpp** [comment] 2017-11-28 21:01
I simplified my entry point and my config a lot, and figured out that the warning is generated by webpack if I disable babel-loader. With babel-loader enabled for .js files, the warnings are suppressed or swallowed somehow. I'm currently searching the babel-loader repo for answers on that.

**Comment by Zephir77167** [comment] 2018-01-19 09:58
Bumping into this as well, babel-preset-env's `modules: false` doesn't fix it in my case.

https://github.com/webpack/webpack/issues/6339

**Comment by matthieu-foucault** [comment] 2018-02-20 18:47
Having the same issue with `webpack 3.11.0` and `babel 6.26`

**Comment by Vasikaran** [comment] 2018-04-09 20:44
@matthieu-foucault This issue were fixed in latest webpack and not documented yet. You can use strictExportPresence options in module configuration which throws an error when imported modules doesn't exist in the exported file. But it took a huge time even I'm running webpack in development mode.

**Comment by matthieu-foucault** [comment] 2018-04-09 20:51
Thanks for the info! I decided to go the long way around and use Typescript to fix this issue (among other things that were becoming hard to maintain given the size of our project) 🙂

**Comment by harrywhite4** [comment] 2019-03-05 05:28
strictExportPresence works great and is documented now https://webpack.js.org/configuration/module/#module-contexts

**Comment by fatso83** [comment] 2020-09-03 11:26
@harrywhite4 `strictExportPresence` is deprecated and the docs do not mention what is replacing it for this use case. We had some failing builds, and it took a long while for us to to notice the warning about a missing member in an import.

**Comment by sokra** [comment] 2020-09-03 16:44
It's not deprecated. Seems like this sneaked into the wrong docs section. Maybe you can send a PR to the docs to fix it.
