### ISSUE TITLE
copy only, prevent bundle and binary asset corruption

### ISSUE THREAD

**Issue by ray007** [webpack/webpack#11104] opened 2020-06-30 06:32 UTC
**Do you want to request a *feature* or report a *bug*?**

Not sure if it's a problem with webpack or my use of it, but asking on [stackoverflow](https://stackoverflow.com/questions/62450742/q-how-to-prevent-nativescript-webpack-build-from-corrupting-binary-resources) and gitter didn't get me any help so far. Neither did an issue at https://github.com/NativeScript/nativescript-cli/issues/5328.

**What is the current behavior?**

I have a nativescript application with an embedded webapplication, which is shown in a webview.
The webapplication is already build and should only be copied, which is done with the `CopyWebpackPlugin`, but webpack still tries to bundle the webapplication. I wouldn't have noticed if for the corruption of the used splash-image and icon-font.

The files are getting copied *and* webpack tries to bundle them. The result has unusable binary resources.

There's a line on the console saying
```
[BABEL] Note: The code generator has deoptimised the styling of C:\devel\path\to\tnsApp\app\webassets\webapp.js as it exceeds the max of 500KB.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Config and (part of) build output at https://gist.github.com/ray007/9303feab03b3ce60979e41a6b3fa9286

The [`webpack.config.js`](https://gist.github.com/ray007/9303feab03b3ce60979e41a6b3fa9286#file-webpack-config-js) file was proviced by nativescript when creating the app, [`webapp.webpack.config.js`](https://gist.github.com/ray007/9303feab03b3ce60979e41a6b3fa9286#file-webapp-webpack-config-js) was added by me to copy the embedded webapp.

**What is the expected behavior?**

The files are getting copied, no attempt to bundle or modify resources is made.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

The webpack version depended on by `nativescript-dev-webpack` is `4.27.0`. Node version is `v12.18.1`.

Edit: use template for issue.

**Comment by evilebottnawi** [comment] 2020-06-30 11:11
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Do not ignore issue template and it is not `CopyWebpackPlugin` repo

**Comment by ray007** [comment] 2020-06-30 12:47
Updated issue using template. Since the files do get copied it should not be an issue of the `CopyWebpackPlugin`.

**Comment by sokra** [comment] 2020-06-30 13:47
The problem is this context `[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 534 bytes {bundle} [built]`. It includes all files matching this regexp. Probably added by something nativescript specific.

You could try `--display-reasons` to get more info.

**Comment by ray007** [comment] 2020-07-01 10:24
@sokra thanks for your help! Still don't know why the binary files apparently got corrupted, but I now know how to avoid the bundling (see https://github.com/NativeScript/nativescript-cli/issues/5328#issuecomment-652333508).

**Comment by evilebottnawi** [comment] 2020-07-07 15:24
Close in favor https://github.com/NativeScript/nativescript-cli/issues/5328, unfortunately we can’t fix it on our side

**Closed by evilebottnawi** 2020-07-07 15:24 UTC

**Comment by ray007** [comment] 2020-07-08 06:46
That webpack tries to bundle the stuff is definitely the issue with the config/scripts generated by nativescript.
I'm still baffled by the corrupted binary files, but I can't imagine how that could be a nativescript issue.

**Comment by evilebottnawi** [comment] 2020-07-08 10:36
@ray007 We don't touch content of binary files, What do you mean `corrupted`?

**Comment by ray007** [comment] 2020-07-08 14:07
I mean interactive testing with debugger in the webview showed that I got data with `$.get(path)`, but using it as image source showed no image, and using it as font-source got me an error on the console.
Now that it's not being bundled, things work as expected.
