### ISSUE TITLE
Incorrect __WEBPACK_IMPORTED_MODULE_ placement

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#3769] opened 2017-01-04 23:36 UTC
I have this in my bundle:

```js
/* harmony reexport (binding) */ if(__webpack_require__.o(__WEBPACK_IMPORTED_MODULE_3_simpler_redux_form__, "reducer")) __webpack_require__.d(exports, "form", function() { return __WEBPACK_IMPORTED_MODULE_3_simpler_redux_form__["reducer"]; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3_simpler_redux_form__ = __webpack_require__(26);
```

As can be seen from this code the order of these two lines is incorrect: it should have defined the variable first and only then check the `if` condition.

This is `rc.3`

**Comment by bebraw** [comment] 2017-01-05 04:54
Can you provide a minimal project generating this type of code so we can fix?

**Comment by halt-hammerzeit** [comment] 2017-01-05 11:17
The error goes away if I perform these changes:

```js
// export { reducer as form } from 'simpler-redux-form'
import { reducer } from 'simpler-redux-form'
export { reducer as form }
```

**Comment by DodekaHydra** [comment] 2017-01-06 02:02
@halt-hammerzeit This fix saved me from hours of pain. Thank you!

**Comment by sokra** [comment] 2017-01-06 03:48
I can't reproduce this bug. 😢  I would be great the get a testcase from you.

**Comment by halt-hammerzeit** [comment] 2017-01-06 09:03
@sokra Well, I have this big boilerplate project of mine:
https://github.com/halt-hammerzeit/webapp/blob/master/frontend/code/reducers/index.js#L6
And I don't think I would reduce it to something smaller because it's all complex and interconnected.
There are running instructions in case you'll be interested but I guess you always have better things to do like fixing those blockers for 2.2 release.

Maybe other people coming here from Google will post their projects and they would be smaller.

**Comment by DodekaHydra** [comment] 2017-01-06 20:05
Hm. I tried reproducing it from the `harmony` example and did not succeed.

Both @halt-hammerzeit and I use vendor-dlls in our projects, but removing mine from the build did not get rid of the error.

Not sure what else to try.

**Comment by sokra** [comment] 2017-01-08 22:59
Ok I've got the problem. `Array.sort` is unstable in node.js and that's the problem when sorting dependencies in a module.

**Comment by halt-hammerzeit** [comment] 2017-01-08 23:06
@sokra Can you tell us more on why is `Array.sort` "unstable"?
I.e. does it return random order for equal elements? I would assume that's the issue.
I.e. internally you have some kind of `weights` (or `priorities`) for dependencies and then you sort them with their weight descending, but for `default` and named exports you had equal `weight`s so their order was random in Node.js after `Array.sort`

**Comment by Panya** [comment] 2017-01-09 02:01
@halt-hammerzeit "unstable" is the correct term for that. See https://en.wikipedia.org/wiki/Sorting_algorithm#Stability

**Comment by TheLarkInn** [comment] 2017-01-09 16:10
Closing with #3852

**Closed by TheLarkInn** 2017-01-09 16:10 UTC
Labels: bug, P1: Urgent, S4: Broken, webpack-2, X0: need more information
