### ISSUE TITLE
WebAssembly with Reference Types cannot be parsed

### ISSUE THREAD

**Issue by CryZe** [webpack/webpack#15566] opened 2022-03-20 19:40 UTC
Reopened #13559

# Bug report
WebAssembly modules with enabled Reference Types cannot be loaded. The webpack version I tested this with is 5.38.1

For a minimal reproduction I created this repository: https://github.com/Tarnadas/webpack-5-wasm-reftypes

The error message is the following:

```
ERROR in ./pkg/webpack_5_wasm_reftypes_bg.wasm
Module parse failed: Internal failure: parseVec could not cast the value
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Internal failure: parseVec could not cast the value
    at new CompileError (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseVec (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:328:15)
    at parseTypeSection (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:360:22)
    at parseSection (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1363:24)
    at Object.decode (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1712:25)
    at decode (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/@webassemblyjs/wasm-parser/lib/index.js:248:21)
    at WebAssemblyParser.parse (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/webpack/lib/wasm-async/AsyncWebAssemblyParser.js:48:19)
    at /home/marior/projects/webpack-5-wasm-reftypes/node_modules/webpack/lib/NormalModule.js:1018:26
    at processResult (/home/marior/projects/webpack-5-wasm-reftypes/node_modules/webpack/lib/NormalModule.js:745:11)
    at /home/marior/projects/webpack-5-wasm-reftypes/node_modules/webpack/lib/NormalModule.js:809:5
 @ ./pkg/webpack_5_wasm_reftypes.js 1:0-58 4:0-21
 @ ./src/index.js 1:0-16

webpack 5.38.1 compiled with 1 error in 572 ms
error Command failed with exit code 1.
```

I used Rust with wasm-bindgen, which provides a cli option to enable reference types. Instead of directly using wasm-bindgen, I’ve been using wasm-pack, but since it’s unmaintained, you will need my fork to pass the cli option down to wasm-bindgen. You can see my PR for wasm-pack here: [rustwasm/wasm-pack#888](https://github.com/rustwasm/wasm-pack/pull/888)

By looking at the error message, it seems to be a problem with the wasm parser library. I checked its repository and couldn’t find any mentions about reference types unfortunately, so I’m not sure how to proceed with this.

**Comment by vankop** [comment] 2022-03-21 08:36
I think parser does not support them.. (`@webassemblyjs/wasm-parser`) . Right now there is no workaround for this.

**Comment by enomado** [comment] 2022-03-24 14:44
Why webpack try to parse it? can we just use file-loader?

**Comment by vankop** [comment] 2022-03-24 15:45
> Why webpack try to parse it?

There are some exports optimization.. so webpack parsing wasm.

> can we just use file-loader?

yes, sure. also in webpack@5 there is `asset` type.

**Comment by sokra** [comment] 2022-04-07 11:11
@xtuc

**Comment by CryZe** [comment] 2022-10-22 10:55
Last time you at least gave a warning, and it's marked as completed?? This has to be the worst bot ever.

**Comment by CryZe** [comment] 2023-02-06 00:54
Ok dude

**Comment by alexander-akait** [comment] 2024-07-23 15:42
We can't fix it on our side, but you can use:
```
module: {
      rules: [
        {
         // You can provide better regexp
          test: /\.wasm$/,
          type: "asset/resource"
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: [
            {
              loader: "babel-loader",
            }
          ]
        }
      ]
    }
```    

But you lose some optimizations. Feel free to feedback

**Comment by bes** [comment] 2024-10-15 20:16
In two days (2024-10-17) Rust 1.82 will be released, and reference types will be on by default. The only way to build without reference types will be to use nightly and rebuild the standard library without reference types support.

**Comment by bes** [comment] 2024-10-17 17:40
Rust 1.82.0 is now released with the following note

> The WebAssembly target features multivalue and reference-types are now both enabled by default. These two features both have subtle changes implied for generated WebAssembly binaries. For the multivalue feature, WebAssembly target support has changed when upgrading to LLVM 19. Support for generating functions with multiple returns no longer works and -Ctarget-feature=+multivalue has a different meaning than it did in LLVM 18 and prior. There is no longer any supported means to generate a module that has a function with multiple returns in WebAssembly from Rust source code. For the reference-types feature the encoding of immediates in the call_indirect, a commonly used instruction by the WebAssembly backend, has changed. Validators and parsers which don't understand the reference-types proposal will no longer accept modules produced by LLVM due to this change in encoding of immediates. Additionally these features being enabled are encoded in the target_features custom section and may affect downstream tooling such as wasm-opt consuming the module. Generating a WebAssembly module that disables default features requires -Zbuild-std support from Cargo and more information can be found at rust-lang/rust#128511.

https://github.com/rust-lang/rust/releases/tag/1.82.0

**Comment by Havunen** [comment] 2024-10-18 07:39
I just updated to 1.82 and now this problem started happening, what is the recommended solution?

**Comment by CryZe** [comment] 2024-10-18 09:01
This is btw not just a Rust issue, as it should affect C, C++, Zig and co. the same way as it got changed in LLVM to be turned on by default.

**Comment by CryZe** [comment] 2024-10-18 09:12
@Havunen can you try with the beta compiler? I'm weirdly not able to reproduce it with 1.83 or 1.84.

**Comment by bes** [comment] 2024-10-18 19:35
> Stripping solves the problem:
> 
> ```toml
> [profile.release]
> strip = true
> ```
> 
> This isn't great for debug builds however, as you usually want the debug symbols. I believe the reason why stripping works isn't because it does any stripping, but because it likely optimizes the overlong immediates encoding back to how it was before LLVM 19. Running `wasm-opt` probably behaves the same way.

@CryZe What problem did you solve by stripping? I tried stripping but I still get the same error:

```
Can't import the named export '__wbindgen_start' (imported as 'wasm') from default-exporting module (only default export is available)
```

**Comment by CryZe** [comment] 2024-10-18 19:37
Without the babel-loader workaround that you tried.

**Comment by bes** [comment] 2024-10-18 19:37
Sorry, yeah, I just tried that and it worked (edited my reply)

**Comment by bes** [comment] 2024-10-18 20:37
Just as a FYI, it's still not possible to actually _use_ reference types (as far as I can tell). Stripping, gets me as far as "my old binary without reference types works".

To get reference types to even pass compile/wasm-pack/wasm-opt I needed to:

```
//.cargo/config.toml
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+bulk-memory,+mutable-globals"
]

// Cargo.toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz', '--enable-bulk-memory']

// Shell / Building
  wasm-pack build \
    --release \
    --weak-refs \
    --reference-types \
    --target bundler \
    --scope "myscope" .
```

But then webpack says

```
Module parse failed: Internal failure: parseVec could not cast the value
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Internal failure: parseVec could not cast the value
```

I don't need reference types, I just wanted to see how far I would get.

**Comment by stephanemagnenat** [comment] 2024-10-21 09:21
> I believe the reason why stripping works isn't because it does any stripping, but because it likely optimizes the overlong immediates encoding back to how it was before LLVM 19.

I can confirm this, as switching back to WebAssembly MVP features with:
```
[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os', '-mvp', '--strip-target-features']
```

does *not* solve the problem. I did not find a way to use wasm-opt to change the immediate encoding back to something supported by webpack.

**Comment by stephanemagnenat** [comment] 2024-10-21 09:24
Note that in big projects with a workspace having multiple crates, the current webpack limitation is really annoying, because due to a [cargo limitation](https://doc.rust-lang.org/cargo/reference/profiles.html#profiles), the strip option must be specified at the workspace level, so that would affect all crates including the ones not compiled for WASM targets. As @CryZe mentioned, that is really a problem for debugging.

**Comment by CryZe** [comment] 2024-10-21 09:27
On the weekend I tracked down the issue back into `wasm-bindgen` which apparently uses the `target_features` section to detect if it should automatically enable its full reference types support. I opened a PR that ensures that you still have to opt into that manually, so that should fix all issues that were caused by Rust 1.82: https://github.com/rustwasm/wasm-bindgen/pull/4213

**Comment by alexander-akait** [comment] 2024-10-21 16:09
@bes can you make a reproducible example so that I can examine it?

@stephanemagnenat 

> Note that in big projects with a workspace having multiple crates, the current webpack limitation is really annoying, because due to a [cargo limitation](https://doc.rust-lang.org/cargo/reference/profiles.html#profiles)

This is not our limitation because we simply cannot run the parser, it crashes with an error, this should be fixed in `@webassemblyjs/wasm-parser`, that's why I ping @xtuc

**Comment by bes** [comment] 2024-10-21 17:11
@alexander-akait here you go https://github.com/bes/webpack-wasm-reference-types-1.82-poc

**Comment by xtuc** [comment] 2024-11-06 16:56
Version 1.13.1 has been published with reference types. We need to update in webpack.

**Comment by alexander-akait** [comment] 2024-11-06 19:47
@xtuc I tried `1.13.1` update and still get - `Error: Internal failure: parseVec could not cast the value`, repro - https://github.com/bes/webpack-wasm-reference-types-1.82-poc

**Comment by alexander-akait** [comment] 2024-11-06 20:12
The same - https://github.com/webpack/webpack/pull/18940

**Comment by xtuc** [comment] 2024-11-06 21:07
Thanks for checking @alexander-akait . I'm having a look.

**Comment by mateuszJS** [comment] 2024-11-06 23:30
@xtuc Works for me!
```
    "@webassemblyjs/ast": "^1.14.1",
    "@webassemblyjs/wasm-edit": "^1.14.1",
    "@webassemblyjs/wasm-parser": "^1.14.1",
   ```
https://github.com/mateuszJS/rust-webpack-v5-template/tree/webpack-v5-migration
Thank you for great work 👍

**Comment by stephanemagnenat** [comment] 2024-11-07 09:37
@xtuc works for me as well! Thank you very much!

**Closed** 2024-11-07 15:51 UTC
Labels: bug, webpack-5, Send a PR, wasm

**Comment by ivnsch** [comment] 2024-12-22 06:23
I'm still getting the error "Module parse failed: Internal failure: parseVec could not cast the value"

https://github.com/ivnsch/molsimnext

the only way to fix it is still the workaround
```
[profile.release]
strip = true
```

**Comment by alexander-akait** [comment] 2024-12-25 15:27
@ivnsch what version do you use?

**Comment by ivnsch** [comment] 2025-01-04 06:14
> @ivnsch what version do you use?

Version of webpack? It's a newly created project (`npx create-next-app@latest`). The webpack version is hidden for some reason, nowhere to be seen in the lock file, `npm explain webpack`, `npx webpack --version` etc. It might be `5.96.1` (it's confirmed that it's using webpack, because the webpack section in next.config.ts is executed).

I also tried specifying these dependencies as per post above:
```
    "@webassemblyjs/ast": "^1.14.1",
    "@webassemblyjs/wasm-edit": "^1.14.1",
    "@webassemblyjs/wasm-parser": "^1.14.1",
```

**Comment by j2ghz** [comment] 2025-02-03 15:47
Apart from the `@webassemblyjs/*` dependencies also check your `webpack` version. I was on 5.96.1 (latest nextjs), whereas [5.97.0](https://github.com/webpack/webpack/releases/tag/v5.97.0) seems to have the fix:
> [WASM] Don't crash WebAssembly with Reference Types (sync and async)
> [WASM] Fixed wasm loading for sync and async webassembly

<details>
  <summary>My problem before applying the fix above:</summary>
  
```
Module parse failed: Internal failure: parseVec could not cast the value
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Internal failure: parseVec could not cast the value
```

from my pnpm lockfile:
```yaml
packages:
  '@webassemblyjs/ast@1.14.1':
    resolution: {integrity: sha512-nuBEDgQfm1ccRp/8bCQrx1frohyufl4JlbMMZ4P1wpeOfDhF6FQkxZJ1b/e+PLwr6X1Nhw6OLme5usuBWYBvuQ==}

  '@webassemblyjs/wasm-edit@1.14.1':
    resolution: {integrity: sha512-RNJUIQH/J8iA/1NzlE4N7KtyZNHi3w7at7hDjvRNm5rcUXa00z1vRz3glZoULfJ5mpvYhLybmVcwcjGrC1pRrQ==}

  '@webassemblyjs/wasm-parser@1.14.1':
    resolution: {integrity: sha512-JLBl+KZ0R5qB7mCnud/yyX08jWFw5MsoalJ1pQ4EdFlgj9VdXKGuENGsiCIjegI1W7p91rUlcB/LB5yRJKNTcQ==}

snapshots:
  webpack@5.96.1:
    dependencies:
      '@types/eslint-scope': 3.7.7
      '@types/estree': 1.0.6
      '@webassemblyjs/ast': 1.14.1
      '@webassemblyjs/wasm-edit': 1.14.1
      '@webassemblyjs/wasm-parser': 1.14.1
```
</details>
