### ISSUE TITLE
EnvironmentPlugin: destructuring process.env doesn't work

### ISSUE THREAD

**Issue by EvgenyOrekhov** [webpack/webpack#5392] opened 2017-07-27 16:59 UTC
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
Destructuring `process.env` doesn't work.
`console.log(MY_VAR);` logs `undefined`

**Steps to reproduce.**

webpack.config.js

```js
const path = require("path");
const {EnvironmentPlugin} = require("webpack");

module.exports = {
    entry: "./main.js",
    output: {
        path: path.resolve(__dirname),
        filename: "bundle.js"
    },
    plugins: [
        new EnvironmentPlugin(["MY_VAR"])
    ]
};
```

main.js

```js
const {MY_VAR} = process.env;
console.log(MY_VAR); // logs undefined
console.log(process.env.MY_VAR); // logs "test"
```

command

```bash
MY_VAR=test webpack
```

**What is the expected behavior?**
`console.log(MY_VAR);` should log "test"

Node.js version: 8.2.1
webpack version: 3.4.1
OS version: Ubuntu 17.04

**Comment by ismail-syed** [comment] 2017-08-06 04:34
@EvgenyOrekhov 
With 
```
new EnvironmentPlugin(["API_BASE_URL"])
```

Running `node bundle.js` I'm getting 
```
undefined
undefined
```

With 
```
new EnvironmentPlugin(["MY_VAR"])
```
I get the documented output of 
```
undefined
test
```

Should the `webpack.config.js` have `new EnvironmentPlugin(["MY_VAR"])`

**Comment by EvgenyOrekhov** [comment] 2017-08-06 17:47
@ismail-syed Yes, sorry, copy-paste error.

**Comment by VojtechStep** [comment] 2017-08-11 15:34
That's because under the hood, EnvironmentPlugin uses DefinePlugin to perform text replacement, which means that it only swaps the text `process.env.MY_VAR` for whatever the value is. It isn't smart enough to figure out you're actually using the variable.

**Comment by sylv3r** [comment] 2018-04-06 22:29
Any news here since summer 2017 ?

Just bumped into the problem and it's kind of (very) annoying when you have dozen of `env` variables (literally).

Will try to work on a PR if nobody's on it.

**Comment by jt3k** [comment] 2018-05-11 16:02
I'm still waiting

**Comment by busticated** [comment] 2018-11-06 23:42
i have a similar issue i think?

i have code like:

```javascript
if (process && process.env && process.env[key]){
    json = process.env[key];
}
```

i currently use the `webpack.DefinePlugin` as such:

```javascript
new webpack.DefinePlugin({
    'process.env': {
        MY_CONFIGS: JSON.stringify(process.env.MY_CONFIGS)
    }
})
```

which ends up replacing every instance of `process.env` with:

```javascript
Object({ MY_CONFIGS: '{"stuff": "things"}' })
```

where `'{"stuff": "things"}'` ends up being a more significant json string.

is there a way to simply _set_ a key on `process.env` without replacing _every_ usage with the value?

**Comment by lutzk** [comment] 2018-11-06 23:57
@busticated 
```
new webpack.DefinePlugin({
    'process.env.MY_CONFIGS': JSON.stringify(process.env.MY_CONFIGS)
})
```

**Comment by busticated** [comment] 2018-11-07 00:04
@lutzk - that's what i thought as well but since i'm doing a dynamic lookup - `process.env[key]` - webpack never actually sees the `process.env.MY_CONFIGS` token and thus cannot replace it.

**Comment by lutzk** [comment] 2018-11-07 00:13
ah ok that might be
but in your example you replace the whole process.env obj:

youre telling the plugin to set `'process.env' = { MY_CONFIGS: JSON.stringify(process.env.MY_CONFIGS) }`

thats why `process.env` is then `Object({ MY_CONFIGS: '{"stuff": "things"}' })`

**Comment by george-norris-salesforce** [comment] 2018-11-14 23:08
Had this working with envify / Gulp. Moving to Webpack breaks all that..

**Comment by NitroBAY** [comment] 2019-11-13 13:13
I know the people asking for what's up or say +1 are annoying but this is "P2: Very Important" issue yet there is no update for 2 years now so @sokra or the rest of the maintainers what do you think about this issue. Maybe fix it in the V5 ?
Why not replacing process.env by an object instead of replacing process.env.NAMEOFTHEVARIABLE ?

**Comment by vankop** [comment] 2020-03-29 21:08
Automatic Node.js Polyfills removed in `webpack@5`, see https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed

**Comment by xeptore** [comment] 2020-08-17 16:19
@vankop Hi! what if someone still wants to use `webpack<5`? i know it's something related to compilers/transpilers (e.g. babel), but any ideas on how to solve this?

**Comment by evilebottnawi** [comment] 2020-08-17 16:24
@xeptore can you provide reproducible test repo with example of the problem?

**Comment by xeptore** [comment] 2020-08-18 09:01
@evilebottnawi of course, here is the link to it:  
https://gitlab.com/the-xeptore/sandbox/webpack-env-destruction  
sorry for late response.

**Comment by evilebottnawi** [comment] 2020-08-18 10:44
@xeptore To be honestly it is the bug and feature, `EnvironmentPlugin` (and `EnvironmentPlugin`) just find `something.other.value` and replace it on provided value, so destructuring is not working, but I think we can improve it

**Comment by xeptore** [comment] 2020-08-18 12:13
@evilebottnawi yes. it's replacing based on tokens, and destructing is not **_exactly_** what it should replace. i play around with parsed version of both examples in [this gist](https://astexplorer.net/#/gist/36dd41ed35f214fa2e0c910769d68d36/afff7148ea8cabfbfbb1c4a266c85c8eff010d40) and it doesn't seem to be much difference between those trees. maybe one step further :)

**Comment by KaKi87** [comment] 2020-12-15 19:21
Hello,
Why not just defining the `process` variable ?
Since it doesn't exist in browser, it will not create any conflict.
Thanks

**Comment by vankop** [comment] 2021-11-23 12:26
closing in favor of https://github.com/webpack/webpack/issues/14800 

pls track problem there

**Closed by vankop** 2021-11-23 12:26 UTC
Labels: enhancement, P4: Nice To Have
