### ISSUE TITLE
ERROR TypeError: (void 0) is not a function - in production build

### ISSUE THREAD

**Issue by navin11** [webpack/webpack#10827] opened 2020-05-04 12:10 UTC
I am working on a simple d3.js project.
In the production build, I am getting this error.

Webpack.config.js

```
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');


module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'example.bundle.js',
    libraryTarget: 'var',
    library: 'ExampleProject',
    libraryExport: 'default'
  },
  devtool: 'inline-source-map',
  devServer: {
    contentBase: path.resolve(__dirname, 'dist'),
    compress: true,
    watchContentBase: true,
    port: 9000
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new ExtractTextPlugin({ filename: 'style.css' }),
    new HtmlWebpackPlugin({
      inject: false,
      hash: true,
      template: './src/index.html',
      filename: 'index.html'
    })
  ]
};
```

Package.json

```
{
  "name": "es6_example",
  "version": "1.0.0",
  "description": "",
  "main": "dist/example.bundle.js",
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production ",
    "start": "webpack-dev-server --mode development --watch-poll",
    "prepublish": "npm run build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "clean-webpack-plugin": "^1.0.0",
    "css-loader": "^1.0.1",
    "d3": "^5.7.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "html-webpack-plugin": "^3.2.0",
    "node-sass": "^4.10.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  }
}

```

Help will be much appreciated.

**Comment by evilebottnawi** [comment] 2020-05-04 12:13
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment] 2020-05-04 12:14
Migrate on `terser-webpack-plugin`

**Closed by evilebottnawi** 2020-05-04 12:13 UTC

**Comment by navin11** [comment] 2020-05-04 13:09
@evilebottnawi 

Thank you for the instant response, I have updated the issue with your bug report template.

I have replaced _uglifyjs-webpack-plugin_ with _terser-webpack-plugin_, even though I could see the issue.

**Comment by L3P3** [comment] 2021-02-13 18:05
@alexander-akait I also get this error, please reopen the issue it is not closed!

**Comment by alexander-akait** [comment] 2021-02-14 14:50
@L3P3 No, it was fixed, without reproducible test repo and can't repo
