### ISSUE TITLE
dynamic import react components exclude css

### ISSUE THREAD

**Issue by yinjun1991** [webpack/webpack#10945] opened 2020-05-22 03:39 UTC
In my project, some react components are dynamic imported:
```
// src/lazy-component/index.tsx
import './index.css';

export default function LazyComponent(props) {
  // ...
}

// src/App.tsx
import './App.css';
const LazyComponent = React.lazy(() => import('./lazy-component'));

export default App(props) {
  // ...
}
```

I want to bundle all css files to one css file, include `lazy-component/index.css` and `App.css`, 
but load `lazy-component/index.tsx` lazily, because the css file is so small, not worth to send another https request.

So in webpack.config.js:
```
optimization: {
  splitChunks: {
    chunks: 'async',
    name(_1, _2, cacheGroupKey) {
      return cacheGroupKey;
    },
    cacheGroups: {
      'lazy-component': {
        test(module) {
          // I mean to exclude the less/css/scss and image files to this cacheGroup.
          return /lazy-component(.*)?\.(ts|tsx|js|jsx|json)$/.test(module.resource);
        }
      }
    }
  }
},
module: {
  rules: [
    { test: /\.css/, use: [ MiniCssExtractPlugin.loader, 'css-loader' ] },
  ]
},
plugins: [
        new MiniCssExtractPlugin({
            filename: '[name].css',
            chunkFilename: '[name].css',
        }),
]
```

But, after building, I get these files:
```
lazy-component.css  // I don't want split lazy-component.css
lazy-component.js
main.js
main.css
```

So i wonder how to avoid the `lazy-component.css` splitting, thank you.

**Comment by seivan** [comment] 2020-05-22 09:08
@yinjun1991 I think it's good practice to actually show your config, otherwise you're lettting people guess what the hell is going on.

I could be wrong here, but that seems about right, why wouldn't you get a CSS file? 
Unless this is a bug, maybe you could into [`style-loader`](https://webpack.js.org/loaders/style-loader/) to inject the styles onto the DOM instead of generating a `css` file.

**Comment by yinjun1991** [comment] 2020-05-22 10:48
> @yinjun1991 I think it's good practice to actually show your config related to this, otherwise you're letting people guess what the hell is going on, how does your CSS rules look like for instance?
> 
> I could be wrong here, but that seems about right, why wouldn't you get a CSS file?
> Unless this is a bug, maybe you could into [`style-loader`](https://webpack.js.org/loaders/style-loader/) to inject the styles onto the DOM instead of generating a `css` file.

Thanks for your reply, I use plugins to split css chunk to a single file.
Maybe my issue is a little obscure, forgive my unskilled english. I update the issue.

**Comment by evilebottnawi** [comment] 2020-05-22 11:25
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment] 2020-05-22 11:26
Please respect time of other developers, without full confiugration/reproducible test repo we can't help, thanks

**Closed by evilebottnawi** 2020-05-22 11:25 UTC
