### ISSUE TITLE
webpack hangs in middle when '--p' is used always on 68%

### ISSUE THREAD

**Issue by S1E-** [webpack/webpack#2012] opened 2016-02-06 09:47 UTC
I am using vuejs Loader. When I run the command "production"  === "webpack --p --progress". It always get struck at 68% and keeping stucking there forever. Can anyone suggest why is this happening and how can I resolve this. 

![capture](https://cloud.githubusercontent.com/assets/8401877/12866007/9c34b98c-cce4-11e5-9a7f-8b8dfbacbfda.PNG)

**this is my web.config.js**

```
var webpack = require('webpack');
var StatsWriterPlugin = require("webpack-stats-plugin").StatsWriterPlugin;
var OfflinePlugin = require('offline-plugin');


module.exports = {
  entry: {
    build: './src/index.js',
    restJS: './src/restJS.js'
  },
  output: {
    path: './dist',
    publicPath: 'dist/',
    filename: '[name].js'
  },
  module: {
    loaders: [{
      test: /\.vue$/,
      loader: 'vue'
    }, {
      test: /\.js$/,
      loader: 'babel',
      exclude: /node_modules/,
      query: {
        presets: ['es2015'],
        plugins: ['transform-runtime']
      }
    }, {
      // edit this for additional asset file types
      test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff(\d*)\??(\d*)$|\.ttf\??(\d*)$|\.wav$|\.mp3$|\.eot\??(\d*)$|\.svg\??(\d*)$|\.html$/,
      loader: "file-loader"
    }, {
      test: /\.scss$/,
      loader: "style!css!sass"
    }, {
      test: /\.css$/,
      loaders: ["style", "css"]
    }]
  }

};

```

**this is my package.json**

```
{
  "name": "",
  "version": "",
  "description": "",
  "author": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack --progress --colors --watch",
    "watch" : "webpack --progress --colors",
    "dev": "webpack-dev-server --watch --inline --hot",
    "build": "webpack --progress --colors --watch --optimize-dedupe --optimize-max-chunks 15 --optimize-min-chunk-size 10000",
    "analysis":"webpack  --json | analyze-bundle-size",
    "production": "webpack --p --progress"
  },
  "dependencies": {
    "babel-plugin-transform-runtime": "^6.1.18",
    "css-loader": "^0.23.0",
    "file-loader": "^0.8.5",
    "google-maps": "^3.1.0",
    "hammerjs": "^2.0.4",
    "install": "^0.3.0",
    "jade": "^1.11.0",
    "jquery": "^2.1.4",
    "materialize-css": "^0.97.3",
    "node-sass": "^3.4.2",
    "npm": "^3.5.0",
    "opentok": "^2.3.0",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "template-html-loader": "0.0.3",
    "testimonial": "^2.0.1",
    "url-loader": "^0.5.7",
    "vide": "^0.4.1",
    "vue": "^1.0.10",
    "vue-async-data": "^1.0.2",
    "vue-hot-reload-api": "^1.2.1",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^7.1.4",
    "vue-resource": "^0.1.17",
    "vue-router": "^0.7.7",
    "vue-validator": "^1.4.4",
    "webfont-medical-icons": "^0.9.3",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-runtime": "^6.2.0"
  }
}

```

**Comment by bebraw** [comment] 2016-02-06 11:37
Maybe as a workaround you could get a non-minified output from Webpack and then pass it through Uglify separately. I know that's not neat but at least it would allow you to get ahead.

Possibly related issue: #537.

**Comment by S1E-** [comment] 2016-02-06 12:25
I am getting an non-minified file and then minifying with php but after this also its size is still 1MB

**Comment by bebraw** [comment] 2016-02-06 12:44
Check out the bundle carefully. It's probably bringing things there you might want to include.

Based on your setup it will inline CSS within the bundle. Consider setting up `ExtractTextPlugin` to get a separate bundle for CSS.

**Comment by S1E-** [comment] 2016-02-06 13:08
@bebraw after extracting css, build.js is reduce by 18kb so practically its still of 1MB.

**Comment by bebraw** [comment] 2016-02-06 13:11
@S1E- Yeah. There is something else going on. Perhaps some of your vendor dependencies are heavy or it includes code you don't want it to. There are tools like [Webpack Chart](https://alexkuz.github.io/webpack-chart/) that can give you a better idea.

**Comment by S1E-** [comment] 2016-02-06 13:17
Size analysis of my build.js is 
![capture](https://cloud.githubusercontent.com/assets/8401877/12866830/20ff6f96-cd02-11e5-983e-323ba956986e.PNG)

**Comment by S1E-** [comment] 2016-02-06 13:22
webpack chart map of build.js
![capture](https://cloud.githubusercontent.com/assets/8401877/12866850/b90e6cba-cd02-11e5-95f7-1d07f66a7072.PNG)

**Comment by bebraw** [comment] 2016-02-06 13:26
Particularly materialize-css and crypto-js seem really big. You could try to analyze how you are using those. Maybe you just need a smaller subset of each.

You can load a dependency like jquery as an [external](https://webpack.github.io/docs/configuration.html#externals). There are also [code splitting techniques](https://webpack.github.io/docs/code-splitting.html) you can leverage.

To get back to the original issue, it would help a lot if you could set up a simplified test case that demonstrates the hang. Strip as much code as you can. This will make it easier to debug.

**Comment by S1E-** [comment] 2016-02-06 13:32
Can you please suggest me to some resource? Where I can see that how I can I write a test to debug this issue.

**Comment by bebraw** [comment] 2016-02-06 13:36
Essentially it would be about dropping as much material from your project while retaining the hang. At some point it will stop failing so you may need to step back.

You can try eliminating entire pieces of the project like styling for instance. There isn't any specific resource as it's just generic debugging to pinpoint the cause. :+1:

Hopefully this process helps you to understand **what** triggers the issue.

**Comment by S1E-** [comment] 2016-02-06 13:42
I have already tried that, all the files included in the bundled are used somewhere so when I remove any one of them then webpack throws error 'required file not found'

**Comment by bebraw** [comment] 2016-02-06 13:46
Yeah, you would have to perform the changes on code level on a separate branch. No other way.

**Comment by S1E-** [comment] 2016-02-06 13:56
OK and thanks

**Comment by sokra** [comment] 2016-02-08 08:38
You could try the 2.0.7-beta version, which displays the module name in the progress thing. Maybe this helps to identify the point where it hangs..

**Comment by buremba** [comment] 2016-02-17 00:41
I tried 2.0.7-beta but the message is similar, no mention of the module name. It was "additional asset processing"

**Comment by jkyoutsey** [comment] 2016-03-01 01:14
I'm seeing the same issue and not uglifying.  Today I did an npm install, first time in about a week.  So I think something changed recently to cause this.

I consistently see this:
`10% 0/2 build modulests-loader: Using typescript@1.7.5 and /Users/JARVIS/src/project7/tsconfig.json
 68% 120/123 build modules`

68% or 69% is the consistent mark with 119-121/123 built.
Isn't there any way to get more info on what's going on under the covers?

**Comment by Restuta** [comment] 2016-03-13 02:55
Facing same issue, but I noticed one thing that it's not happening for 
`devtool: 'eval'`, but _is_ happening for both:
`devtool: 'source-map'`
and
`devtool: 'cheap-module-source-map'`

**Comment by bebraw** [comment] 2016-12-24 07:22
Can you try against the current beta version of webpack 2?

**Comment by clemgrim** [comment] 2017-01-02 14:57
Hello, I have the same issue with webpack 2.2.0-rc.3 and webpack.2.1.0-beta.28
It's blocking at 91%. No minification, no sourcemaps.
I'm using extract plugin (2.0) and awesome typescript loader.

**Comment by bebraw** [comment] 2017-01-02 15:06
@clemgrim Could you set up a project so it's easier to debug what's going on?

**Comment by clemgrim** [comment] 2017-01-05 09:37
Here is my config:

```js
// load required modules
var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');

// load plugins
var CopyWebpackPlugin = require('copy-webpack-plugin');
var AssetsPlugin = require('assets-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var NgAnnotatePlugin = require('ng-annotate-webpack-plugin');

module.exports = function(options) {
   return {
        entry: {
            home: '/some/path/home.ts', // there're more entries
            vendor: '/some/path/vendor.ts')
        },
        output: {
            path: '/some/path/dist',
            filename: '[name].js',
            chunkFilename: '[id].chunk.js',
            publicPath: '/dist/',
            jsonpFunction: 'jsp'
        },
        resolve: {
            extensions: ['.ts', '.js'],
            modules: ['/some/path', 'node_modules'],
            unsafeCache: true
        },
        resolveLoader: {
            moduleExtensions: ['-loader']
        },
        module: {
            loaders: [
                {
                    test: /\.ts$/,
                    loader: 'awesome-typescript',
                    exclude: [/node_modules/]
                },
                {
                    test: /\.html/,
                    loader: 'html',
                    exclude: [/node_modules/]
                },
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract({fallbackLoader: 'style', loader: options.prod ? 'css!postcss' : 'css'})
                },
                {
                    test: /\.scss/,
                    loader: ExtractTextPlugin.extract({fallbackLoader: 'style', loader: options.prod ? 'css!postcss!sass' : 'css!sass'})
                }
            ],
            noParse: [
                /angular.*\.js$/,
                /moment.*\.js$/,
                /ui-select.*\.js$/,
                /pdfjs-dist.*\.js$/,
                /ngmap.*\.js$/,
                /ng-file-upload.*\.js$/
            ]
        },
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({names: ['vendor']}),
            new ExtractTextPlugin(options.prod ? '[name]-[chunkhash].css' : '[name].css'),
            new webpack.DefinePlugin({PRODUCTION: !!options.prod}),
            new AssetsPlugin({filename: 'manifest.json', path: absPath('data/webpack')}),
            new webpack.LoaderOptionsPlugin({
               minimize: options.prod,
               debug: false,
               options: {
                  htmlLoader: {
                     ignoreCustomFragments: [/\{\{.*?}}/],
                     attrs: false
                  },
                  postcss: function () {
                     return options.prod ? [autoprefixer] : [];
                 }
              }
            }),
            new NgAnnotatePlugin({add: true})
        ],
        node: {
            global: false,
            crypto: false,
            module: false,
            clearImmediate: false,
            setImmediate: false
        },
        devtool: false,
        profile: true,
        performance: {
            hints: false
        },
        stats: 'verbose',
        watchOptions: {
            ignored: [
                './node_modules/**/*',
                './module/**/*',
                './public/**/*',
                './vendor/**/*'
            ]
        }
    };
};
```
It takes ~25s (I optimized from 35 to 25s with `noParse` option)
But the  `91% additional asset processing` is taking a very long time, and I can't figure what is done in this step. there's no uglify plugin or whatever.
Note that I'm building 600+ modules

**Comment by dziamid** [comment] 2017-02-16 14:30
Same problem here, hangs on 91% additional asset processing

**Comment by vperron** [comment] 2017-02-24 10:42
Same here for us.

**Comment by mikeengland** [comment] 2017-02-28 14:32
Same for me, but on 66%

**Comment by mstralka** [comment] 2017-02-28 15:27
The weird thing for me is that, with the exact same versions of node, npm, yarn, and all of the packages, I can run this on my Macbook Pro (macOS 10.12.3 with 16 GB RAM and SSD) and it will finish in about 50 seconds.  On my Ubuntu 16.04 servers (8GB RAM AWS with SSD), it takes 15 minutes (hanging at 68% for a long time but it does eventually finish).  So I have to perform the build step on my mac and then rsync the files to the servers.

Has anyone else experienced this where it will work on a Mac in a reasonable amount of time but it's dog slow on a Linux server with the same build tools?

**Comment by mikeengland** [comment] 2017-02-28 16:20
@mstralka I am also experiencing this on a Macbook Pro. Do you know if it is possible to debug this?

I just see the following with the --progress flag set:
`64% building modules 1158/1265 modules 107 active ...e_modules/lodash/isArrayLikeObject.js`

**Comment by mstralka** [comment] 2017-02-28 17:22
@mikeengland unfortunately I don't know how to debug why it works okay on a mac but so slow on Linux.

I do know that it appears to be related to compiling SASS because if I remove the steps that compile my SASS files from the build script, it works much faster on Linux too.  I'm using these SASS-related packages:
`yarn list | grep sass`
```
├─ bootstrap-sass@3.3.7
│  ├─ node-sass@^4.0.0
│  ├─ sass-loader@^6.0.0
├─ node-sass@4.5.0
│  ├─ sass-graph@^2.1.1
├─ sass-graph@2.1.2
├─ sass-loader@6.0.2
```

```
yarn --version
0.21.3
npm --version
4.1.2
node --version
v7.6.0
```

**Comment by mikeengland** [comment] 2017-02-28 17:56
I saw other issues relating to sass compilation on Github. Sadly, I'm not compiling any SASS! It seems that since the webpack 2 upgrade, the npm compilation sporadically takes 5+ mins :(.

**Comment by protoEvangelium** [comment] 2017-03-01 19:15
Same with me, it hangs on 91% and I am using Windows 10 and not compiling SASS.

**Comment by subhash-periasamy** [comment] 2017-03-02 02:34
Facing same issue. Hangs randomly, I am running webpack --config config/webpack.dev.js --progress --profile

**Comment by Lodin** [comment] 2017-03-02 12:38
Same with me. I faced this issue using latest node realises (`7.4.0`, `7.5.0`). Have fixed it moving to the node `6.9.5`.

**Comment by gretzky** [comment] 2017-03-02 17:26
Same here. Switching node versions didn't fix it. It may be worth mentioning that in the past week that I've also had trouble importing external sass modules (i.e. node-bourbon), throwing a path not found.

```
yarn 0.21.3
node 7.6.0
npm 4.1.2
```

**Comment by subhash-periasamy** [comment] 2017-03-02 17:39
Found this in some other thread. I was able to fix it after setting UV_THREADPOOL_SIZE=100 in the env.

**Comment by gretzky** [comment] 2017-03-02 17:41
@subhash-periasamy how did you invoke this? i tried it a few different ways and it didn't work.

**Comment by subhash-periasamy** [comment] 2017-03-02 17:45
make sure you have it in your env. I am using mac so I did:  export UV_THREADPOOL_SIZE=100

**Comment by mstralka** [comment] 2017-03-02 17:56
I think this might be the related issue on node-sass:
https://github.com/sass/node-sass/issues/857

But setting UV_THREADPOOL_SIZE=100 isn't helping on my linux box.  It still hangs for 15 minutes at 69%

**Comment by subhash-periasamy** [comment] 2017-03-02 17:56
@henrahmagix Here you go https://github.com/webpack-contrib/sass-loader/issues/100 
But this thread is pretty old however it helped my scenario. Initially I tried to delete portions of my webpack config to see what is causing the hang and narrowed down to the sass-loader.

Then I started searching for sass-loader hang and came across the thread. Hope it helps!

Below snippet was causing the hang:

```
 {
                test: /\.scss$/,
                loaders: ['raw-loader', 'sass-loader']
             },
             {
                test: /initial\.scss$/,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: 'css-loader!sass-loader?sourceMap'
                })
             },
```

**Comment by obykoo** [comment] 2017-04-02 17:32
I am not using sass-loader and facing same issue with hanging on 91%

**Comment by rdsedmundo** [comment] 2017-04-12 15:00
Same here.

**Comment by ruichao-factual** [comment] 2017-04-14 09:56
Face the same issue, hangs on 91% additional asset processing.  

The issue will not happen if I do one of the following things:
1. Set `devtool` to some value that contains `eval` (`eval`, `eval-source-map
`, `cheap-eval-source-map`, etc.)

2. Remove the `UglifyJsPlugin`.

**Comment by yangdonglai** [comment] 2017-04-18 10:21
I have similar issue , hangs on  91% additional asset processing too long.
My solution is use 'webpack-parallel-uglify-plugin' to replace UglifyJS plugin;
hopes help
```
var ParallelUglifyPlugin = require('webpack-parallel-uglify-plugin');
new ParallelUglifyPlugin({
   cacheDir: '.cache/',
   uglifyJS:{
     output: {
       comments: false
     },
     compress: {
       warnings: false
     }
   }
 })
```

**Comment by andrexx** [comment] 2017-05-16 08:22
Big codebase (jquery + typescript + new code with angular 4)
node: 6.10.x
webpack: 2.5.1

Production build time about 20 min with devtool: source-map. Stuck on "91% additional asset processing"
Change to devtool: cheap-module-source-map didn't help, build time still about 20 min

Change to devtool: cheap-module-eval-source-map helped, the build time was reduced to 2 minutes

**Comment by dziamid** [comment] 2017-06-01 13:20
@andrexx Do you have both ts-loader/awesome-ts-loader and babel-loaders in your setup?

**Comment by andrexx** [comment] 2017-06-12 17:56
@dziamid Only awesome-typescript-loader (^3.1.3)

**Comment by dziamid** [comment] 2017-06-12 18:09
@andrexx Try using ts-loader in traspile-only mode

**Comment by milanchheda** [comment] 2017-06-16 12:21
Having the same problem. Gets stuck at 91% additional asset processing :(

**Comment by yantakus** [comment] 2017-07-07 20:53
@milanchheda Any luck with fixing it?

**Comment by milanchheda** [comment] 2017-07-09 06:06
@yantakus - So I moved from t2.micro to t2.small and it got fixed. I believe, it needs high configuration as the consumption is very high when it merges & combines files.

**Comment by bytewiz** [comment] 2017-08-15 13:12
I also have this problem I hit the `91% additional asset processing` and then it stalls for ~10-15min
I cut it down setting the `devtool` to `eval` just to test it and then the build time was `81s` instead of 10min but there must be a way to skip the asset processing ?

**Comment by foodaka** [comment] 2017-09-11 10:39
Same problem, anyone have a good workaround for this?

**Comment by jeremyk** [comment] 2017-09-14 00:22
I am having the same issue. With the `-p` option, the build takes about 10 minutes, handing around 30% but never in the same spot. Using any of the "eval" source map options fixes it but then the resulting file is much larger.

**Comment by sijakret** [comment] 2017-09-18 12:54
same issue here with node 8.4.0

**Comment by urbanhusky** [comment] 2017-10-17 09:41
Our production build is also failing after `91% additional asset processing` with `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`. 

We cannot skip minification or tree-shaking, as this would yield an unwieldy large application that is quite slow to load.

**Comment by urbanhusky** [comment] 2017-10-17 15:09
# I found a workaround for us
We replaced all `webpack` calls from our build scripts with `node --max-old-space-size=6144 node_modules/webpack/bin/webpack.js`. 
In this case, we increased the node memory limit to 6GB (default seemed to be 1.5GB). Our build was hitting ~3GB, I went with 6GB as a limit to leave some headroom.

## Comparison of old vs "fixed" solution
- from build script (in this case: patched into `dotnet publish` with an `<Exec Command="…">` - because we build an asp.net core application)
- from package.json

### new "fixed" workaround

```
# build script
node --max-old-space-size=6144 node_modules/webpack/bin/webpack.js --config config/webpack.config.vendor.js --env.prod -p

# package.json scripts:
"build-webpack-prod-vendor": "node --max-old-space-size=6144 node_modules/webpack/bin/webpack.js --config ./config/webpack.config.vendor.js --env.prod -p",
```
### previous implementation

```
# build script
node_modules/webpack/bin/webpack.js --config config/webpack.config.vendor.js --env.prod -p

# package.json scripts:
"build-webpack-prod-vendor": "npm-run webpack --config ./config/webpack.config.vendor.js --env.prod -p",
```

# Summary
Replaced `npm-run webpack …` with `node --max-old-space-size=6144 node_modules/webpack/bin/webpack.js …`
Replaced `node_modules/webpack/bin/webpack.js …` with `node --max-old-space-size=6144 node_modules/webpack/bin/webpack.js …`

Adjust `--max-old-space-size=<maximum memory in MB>` accordingly.

**Comment by scipper** [comment] 2017-11-15 07:32
@urbanhusky icreasing the max memory does indeed fixed the hangs on 68-69%. thanks for that!

**Comment by andreialecu** [comment] 2017-12-16 15:15
For everyone experiencing the 91% hang, let's get https://github.com/webpack/webpack/issues/4558 reopened. `node --max-old-space-size=6144` does not help with that problem.

There has been some discussion there, but the issue has been closed prematurely.

**Comment by mnpenner** [comment] 2018-02-27 02:19
I'm getting stuck at 70% with webpack 4.0.1:

```
❯ webpack --progress
 70% building modules 1682/1682 modules 0 active  
```

**Comment by evilebottnawi** [comment] 2018-02-27 09:52
@mnpenner can you create minimum reproducible test repo?

**Comment by montogeek** [comment] 2018-02-27 10:01
@mnpenner Have you tried increasing your NodeJS memory limit? How big is your project?

**Comment by mnpenner** [comment] 2018-02-27 18:32
@evilebottnawi Uhh... we'll see. I'm going to fight with it a bit more first. My config is rather complex.

@montogeek No, I haven't tried that. I should do something like this?

```
❯ node  --max-old-space-size=8192 "node_modules/.bin/webpack" --progress --color --sort-assets-by name --bail
```

Same result. It's not crashing though, so it doesn't seem like it's running out of memory.

My project has 514 "assets" -- I think all or most of those are processed by webpack.

The part I find weird though is that it says "1691/1691 modules 0 active" -- as though it's done. It seems like its getting confused.

I guess I'll wait for the v3 to v4 migration guide. Probably missed something. webpack-dev-server still runs, its just my production build that's hanging.

**Comment by evilebottnawi** [comment] 2018-02-27 18:43
@mnpenner try to enable/disable plugins and loaders

**Comment by jtomaszewski** [comment] 2018-03-27 07:53
@mnpenner I had the same problem and for me the cause was extract-text-webpack-plugin. Switching to mini-css-extract-plugin solved it.

**Comment by mnpenner** [comment] 2018-03-27 19:46
Thanks Jack. That worked for me too (switching to mini css)

On Mar 27, 2018 12:53 AM, "Jack Tomaszewski" <notifications@github.com>
wrote:

@mnpenner <https://github.com/mnpenner> I had the same problem and for me
the cause was extract-text-webpack-plugin. Switching to
mini-css-extract-plugin solved it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webpack/webpack/issues/2012#issuecomment-376430805>,
or mute
the thread

**Comment by evilebottnawi** [comment] 2018-04-19 13:09
FYI `webpack@2` is deprecated. Please upgrade you configuration to latest version and feel free to recreate issue if problem still exists. A lot of difference issues here and difficult support people. Thanks!

**Closed by evilebottnawi** 2018-04-19 13:09 UTC
Labels: P3: Important, S4: Broken, X4: work required, bug, webpack-2

**Comment by Alabit** [comment] 2020-06-03 22:25
I had a similar issue, google pointed me here. Leaving my findings for the future.
For me, it was related to https://github.com/sass/node-sass/issues/857
For me, it only existed on webpack-dev-server with node-sass on Windows.

I resolved it by adding 
`UV_THREADPOOL_SIZE=1024` to my package.json build scripts

```
    "run-dev": "cross-env DEV='true' NODE_ENV=development BABEL_ENV=development NODE_OPTIONS=--max_old_space_size=8192 webpack-dev-server --config webpack.dev.js --progress --color",
    "run-dev-windows": "cross-env DEV='true' NODE_ENV=development BABEL_ENV=development NODE_OPTIONS=--max_old_space_size=8192 UV_THREADPOOL_SIZE=1024 webpack-dev-server --config webpack.dev.js --progress --color",
```

It slowed down my linux builds, so I split it into two scripts. But it turned my windows builds from never-finishing always-hanging to actually-completes (in about 3.5 minutes)

**Comment by denishowew** [comment] 2021-11-09 20:12
> For me, it was related to [sass/node-sass#857](https://github.com/sass/node-sass/issues/857)

Thank you very much for this hint.  webpack was hanging at the end of a run unless I set `stats: 'none'` or didn't apply sass-loader (redundantly) for CSS files.
