### ISSUE TITLE
Tree shaking does not apply to re-exported namespace imports

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#9607] opened 2019-08-20 13:44 UTC
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Given:

`./src/index.js`:

``` js
import { other } from "./proxy";

console.log(other.foo1);
```

`./src/proxy.js`:

``` js
import * as other from "./other";
export { other };
```

`./src/other.js`:

``` js
export const foo1 = 1;
export const foo2 = 2;
```

`./webpack.config.js`:

``` js
const pathHelpers = require("path");

const ROOT_PATH = __dirname;
const TARGET_PATH = pathHelpers.join(ROOT_PATH, "./target/");
const SRC_PATH = pathHelpers.join(ROOT_PATH, "./src/");

const ENTRY_FILENAME = "index.js";
const OUTPUT_FILENAME = "index.js";

const config = {
  mode: "development",
  devtool: "source-map",
  optimization: {
    usedExports: true
  },
  entry: pathHelpers.resolve(SRC_PATH, ENTRY_FILENAME),
  output: {
    path: TARGET_PATH,
    filename: OUTPUT_FILENAME
  }
};

module.exports = config;
```

The resulting output tells us that the unused export `foo2` will not be removed by tree shaking:

``` js
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "foo1", function() { return foo1; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "foo2", function() { return foo2; });
const foo1 = 1;
const foo2 = 2;
```

Repo containing the above: https://github.com/OliverJAsh/tree-shaking-test/tree/proxy

**What is the expected behavior?**

`foo2` should be tree shakeable.

We can achieve this if we bypass the re-export and use a namespace import directly:

`./index.js`:

```diff
-import { other } from "./proxy";
+import * as other from "./other";
```

Result:

``` js
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return foo1; });
/* unused harmony export foo2 */
const foo1 = 1;
const foo2 = 2;
```

Diff:

``` diff
 /* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return foo1; });
-/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "foo2", function() { return foo2; });
+/* unused harmony export foo2 */
 const foo1 = 1;
 const foo2 = 2;
```

**Other relevant information:**
webpack version:  4.39.2
Node.js version: 10.16.3
Operating System: macOS
Additional tools:

This works in Rollup. [Playground example](https://rollupjs.org/repl/?version=1.19.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMG90aGVyJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZwcm94eSU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2cob3RoZXIuZm9vMSklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyb3RoZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBmb28xJTIwJTNEJTIwMSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGZvbzIlMjAlM0QlMjAyJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnByb3h5LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG90aGVyJTIwZnJvbSUyMCU1QyUyMi4lMkZvdGhlciU1QyUyMiUzQiU1Q25leHBvcnQlMjAlN0IlMjBvdGhlciUyMCU3RCUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

For context, the reason you might re-export a namespace import is for dev UX—VS Code can provide import suggestions only for named exports.

This approach is used in libraries [such as fp-ts](https://github.com/gcanti/fp-ts-rxjs/blob/4308683f8d252e44e19c46135ae57ab257fc347c/src/index.ts).

**Comment by sokra** [comment] 2019-08-20 18:42
This has been improved in the `next` branch (webpack 5). In most cases module concatenation plus minimizing will optimize this case too. Your example should optimize fine in production mode.

**Comment by evilebottnawi** [comment] 2019-08-21 10:45
@sokra maybe we should put this as test case to ensure all ok in webpack@5?

**Comment by evilebottnawi** [comment] 2019-12-06 09:06
Just for future test

**Comment by oles** [comment] 2020-02-27 13:47
I had the same issue.
One re-exported file was included in my bundle, with all its imports, even though it was not included from anywhere.

In my case, and in this example, nothing in `vuex-test.js` was imported from anywhere in the app - just the tests.

utilities/index.js
```
...
export * from './string.js'
export * from './company.js'
...
export * from './vuex-test.js'
...
```

components/title.vue
```
<template>
    ...
</template>

<script>
    import {titleCase, processCompanyData} from '../utilities/index.js'
    
    export default {
        ...
    }
</script>
```

Which resulted in my bundle containing `vuex-test.js` and all it imported.

I tried most things. `sideEffects: false` in package.json, but then the css disappeared, and my polyfills got affected as well. Tried giving `sideEffects` various arrays of strings, which just seemed like a bad solution.

Tried the IgnorePlugin, and it worked - sort of! The bundle did not contain `vuex-test.js` and all its import, but now the app did not work - it complained about missing said file.

Finally, after many shots in the dark with various regexes and strings to `test`, `include`, `exclude` in different webpack rules, I found it:

```
{

    ...

    module: {
        rules: [

            ...

            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                options: {
                    presets: ['@babel/preset-env']
                }
            },

            {
                test: /utilities\/vuex-test\.js/,
                sideEffects: false
            }
        ]
    },

    ...

}
```

and it worked. Seems like the trick was an extra rule, and not filling out more options in the main `.js` rules.

Hurray :tada:

**Comment by sokra** [comment] 2020-06-13 16:34
Fixed in webpack 5

**Closed by sokra** 2020-06-13 16:34 UTC

**Comment by eamodio** [comment] 2020-07-25 08:28
@sokra Any chance this could be backported to webpack 4?

**Comment by evilebottnawi** [comment] 2020-07-25 12:31
@eamodio unfortunately, no, you can start to using webpack@5, most of plugins and loader already have compatibility

**Comment by eamodio** [comment] 2020-07-26 04:47
@evilebottnawi OK thanks -- I've tried to upgrade to webpack 5, but I haven't been able to get it to work. See: https://github.com/eamodio/vscode-gitlens/commits/feature/webpack5
https://github.com/eamodio/vscode-gitlens/blob/2bfc0360b46933f715379016aed4084ad4e75fae/webpack.config.js

It looks like webpack 5 doesn't seem to support a config that returns a function that is an array (or something), as I just get output that looks like this:
```
Compilation Results

 Version: 5.0.0-beta.22
 Built: Sun Jul 26 2020 00:41:05 GMT-0400 (Eastern Daylight Time)
 Compile Time: 36ms
 Output Directory: C:\Users\Eric\code\eamodio\vscode-gitlens\dist
 Hash: dbd0e35abb9cf7150b07

┌────────────┬───────────────────────────────┐
│ Entrypoint │ Bundle                        │
├────────────┼───────────────────────────────┤
│ main       │  Bundle Name       │ main.js  │
│            │  Compared For Emit │ false    │
│            │  Bundle size       │ 0.64 kb  │
│            │                               │
│            │ Modules:                      │
│            │                               │
└────────────┴───────────────────────────────┘

[webpack-cli] Module not found: Error: Can't resolve './index.js' in 'C:\Users\Eric\code\eamodio\vscode-gitlens'
```

**Comment by vankop** [comment] 2020-07-26 09:58
@eamodio can you report a new issue with reproducible repo?

**Comment by eamodio** [comment] 2020-07-27 02:37
@vankop Opened https://github.com/webpack/webpack/issues/11231. Thanks!
