### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by adminfyy** [webpack/webpack#3050] opened 2016-09-23 07:59 UTC
**I'm submitting a bug report**

# buildAll.js error
**under the example folder:
using buildAll.js script would appear this kind of error 
"no such file or directory ******.0.js"
because of the template.md  error reference like 'js/0.js'**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
 Windows 10

**Comment by bebraw** [comment] 2016-09-23 09:38
Can you see this in webpack 2 too?

**Comment by adminfyy** [comment] 2016-09-23 10:14
all the same.
lacking some files due to the 
"template.md"

**Comment by zhaoshengjun** [comment] 2016-09-26 12:44
Hi @bebraw ,

I checked the `code-splitted-css-bundle` example and I found the main reason is that the `webpack.config.js` is using `extract-text-webpack-plugin`. This plugin is using some files inside `webpack/lib/`. Due to the folder hierarchy, it cannot find the files so it failed to build.

I've tried to using `resolve` in the `webpack.config.js` but had some trouble to make it work.

If you could point me some direction, I can send a PR to make the examples work again.

Thanks!

**Comment by bebraw** [comment] 2016-09-27 10:04
@zhaoshengjun One way to approach it - figure out when it broke. Once you can see how it worked in the past, you might be able to see how to fix it better.

**Comment by zhaoshengjun** [comment] 2016-09-27 10:18
Sure. I will work on it to see if I can fix it.

**Comment by zhaoshengjun** [comment] 2016-09-28 05:16
I finally got this. The reason is some `template.md` files are use output file, for example, `js/0.js`. But the output file has been changed to `js/0.output.js`.

I will submit a PR soon to fix all these template errors.

**Comment by zhaoshengjun** [comment] 2016-10-02 08:49
hi @adminfyy, if you download the new example folder and run `node buildAll.js`, do you have any error? 
If not, you may close this issue.

**Comment by michelgotta** [comment] 2016-10-05 11:02
Hi @zhaoshengjun and @adminfyy 

There is still a error concerning the `template.md` of the `code-splitted-css-bundle`:

Line 32:
# js/style.css

``` javascript
{{js/style.css}}
```

There is no `js/style.css` for this example, maybe the whole block doesn't make sense here (Maybe copy/pasted from somewhere else) and could be removed? After removing this part the `npm run build:examples` or `node buildAll.js` is doing fine. Could commit this change as PR.

**Comment by zhaoshengjun** [comment] 2016-10-05 12:20
I think the reason might be the timing. The `buildAll.js` is using `child_process` to run the webpack CLI, which will generate the output files in `js` folder. That's why some of the templates are using `{{js/filename}}` . But sometime it may return early and the output files are not there yet. Hence it causes the error. 

If you don't mind, will you try to run the `node buildAll.js` again to see if the `code-splitted-css-bundle` pass?

**Comment by michelgotta** [comment] 2016-10-10 07:56
@zhaoshengjun Just looked at the problem again. Other examples use the `child_process`, too. Running the `node buildAll.js` again doesn't work for me. I will dig a bit deeper to find the problem with the examples.

**Comment by michelgotta** [comment] 2016-10-11 15:55
All examples using the `extract-text-webpack-plugin` in the config failing on my system. I'm trying to rebuild the examples without the usage of this plugin.

**Comment by michelgotta** [comment] 2016-10-13 14:38
Found the main cause for the errors. Examples are just fine, the problem is indeed the `extract-text-webpack-plugin` module. It requires parts of the `webpack` module like this:
`var Chunk = require("webpack/lib/Chunk");`

In our case, we don't have the webpack module in our `node_modules` directory but in the root directory of the repository. By placing a symlink into the `node_modules` folder `ln -s ../ webpack` everything works fine.

@bebraw @adminfyy  @zhaoshengjun: Does anyone know how to deal with such a "self requiring" problem? There is the [require-self](https://www.npmjs.com/package/require-self) module on npm, but I don't think that's a proper solution.

**Comment by bebraw** [comment] 2016-10-13 14:48
@michelgotta That's difficult. I'm not too fond of patching `require`. Perhaps it would be to handle the dependency problem through some other way. I wonder how this has worked in the past.

**Comment by michelgotta** [comment] 2016-10-13 14:52
Another way to get this working (not really fixing) is running `npm install` inside `node_modules/extract-text-webpack-plugin`.

**Comment by michelgotta** [comment] 2016-10-13 15:03
@bebraw I think it is working on all your machines because all devs have linked their webpack dev repository as the global webpack by using `npm link webpack`.

**Comment by zhaoshengjun** [comment] 2016-10-13 15:06
I might try to use `yarn link` before running the `node buildAll.js`. Heard a lot of good things of `yarn`:smile:

**Comment by bebraw** [comment] 2016-10-13 15:10
@michelgotta Ah, ok. I wonder if `extract-text-webpack-plugin` could expose some hooks to make this kind of patching easier.

**Comment by zhaoshengjun** [comment] 2016-10-14 00:56
Just tested on my windows computer, running the `yarn link` and `yarn link webpack` before running `node buildAll.js` FIXED this.

Hi @bebraw , should I submit a PR to update the `README` on example part to include the instructions?

**Comment by bebraw** [comment] 2016-10-14 02:00
@zhaoshengjun Yeah, that could be nice.

@TheLarkInn Do you think this is `wontfix` if the linking requirement is documented?

**Comment by TheLarkInn** [comment] 2016-10-14 05:41
If the linking requirements are documented we could probably close it. I did add this documentation to CONTRIBUTOR.MD

**Comment by michelgotta** [comment] 2016-10-14 07:23
Added some info in the README.md of the examples folder. PR on the way.

I think we can close this one. Solutions are documented.

**Closed** 2016-10-14 07:47 UTC
Labels: bug, P4: Nice To Have, S4: Broken, X5: work required (PR)
