### ISSUE TITLE
With Server-side rendering, 'asset/resource' should suppress emitting of the image file (similar to file-loader emitFile=false)

### ISSUE THREAD

**Issue by ketanhdoshi** [webpack/webpack#12813] opened 2021-03-05 08:44 UTC
## Feature request

**What is the expected behavior?**
When handling images with 'asset/resource' using server-side rendering, we do not want the image file to be emitted, but we do want the image URL to be populated in the HTML in the server bundle. The client bundle can emit the image file.

With file-loader one could do this with the emitFile=false flag, but we cannot do that with Webpack 5 Asset Modules.

'asset/inline' does suppress the output of the image file, but it requires the image to be inlined, which isn't what is desired.

**What is motivation or use case for adding/changing the behavior?**
Webpack 5 Asset Modules deprecated the file-loader. But the emitFile feature of file-loader is not available in Asset Modules. That is a required feature for Server Side Rendering

**How should this be implemented in your opinion?**
Include a flag similar to emitFile with 'asset/resource'

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment] 2021-03-05 11:19
Duplicate of https://github.com/webpack/webpack/issues/12474

**Closed by alexander-akait** 2021-03-05 11:19 UTC
