### ISSUE TITLE
DedupePlugin fails: No template for dependency: TemplateArgumentDependency

### ISSUE THREAD

**Issue by alansouzati** [webpack/webpack#1082] opened 2015-05-19 16:45 UTC
Hi folks,

  Great job with Webpack, this framework is really helping my project to succeed. I'm using version `1.8.11` through `gulp-webpack` and after I've added `react-intl` in my project this problem started to happen:

```
Error: No template for dependency: TemplateArgumentDependency
    at doDep (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/NormalModule.js:116:23)
    at Array.forEach (native)
    at doBlock (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/NormalModule.js:125:22)
    at DependenciesBlock.NormalModule.source (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/NormalModule.js:159:2)
    at Tapable.ModuleTemplate.render (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/ModuleTemplate.js:14:28)
    at Tapable.Template.renderChunkModules (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/Template.js:80:31)
    at Tapable.<anonymous> (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/MainTemplate.js:28:22)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at Tapable.MainTemplate.render (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/MainTemplate.js:111:20)
    at Tapable.createChunkAssets (/Users/alansouza/project-workspace/project/node_modules/gulp-webpack/node_modules/webpack/lib/Compilation.js:784:32)
```

After some investigation and checking out some suggestions in the webpack Gitter chat, I decided to remove the Dedupe Plugin and then everything works again, but my bundle size has increased significantly. 

Any ideas on how to make the DedupePlugin work again? If I get any pointers I could try to solve the issue myself. Any help here is much appreciated. 

Alan

**Comment by benoneal** [comment] 2015-05-20 05:33
Suddenly started getting the same issue, only I'm using 1.4.15 and haven't updated anything: 
```
node_modules/gulp-webpack/node_modules/webpack/lib/NormalModule.js:116
		if(!template) throw new Error("No template for dependency: " + dep.Class.nam
		                    ^
Error: No template for dependency: TemplateArgumentDependency
```
I'm guessing some dependency updated with breaking changes without bumping the version enough, but that's just a stab in the dark because I'm having a lot of trouble tracking down the source of this sudden error.

**Comment by cheapsteak** [comment] 2015-06-18 21:21
Having a similar issue  
Running `webpack` works, however, `webpack-dev-server` breaks with the "No template.." error, and removing the dedupe plugin fixes it

**Comment by gajus** [comment] 2015-08-25 18:22
I am getting the same issue. Replicating it is kinda hard.

`./foo/index.js`

```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

// import ReactDOM from 'react-dom';
```

`/bar/index.js` 

```js
import Foo from './../foo/index.js';
```

Where `foo` and `bar` are separate modules.

Using this webpack.config.js:

```js
var webpack = require('webpack'),
    path = require('path'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    devServer;

devServer = {
    contentBase: __dirname + '/endpoint',
    colors: true,
    quiet: false,
    noInfo: false,
    publicPath: '/',
    historyApiFallback: true,
    host: '127.0.0.1',
    port: 8000,
    hot: true
};

module.exports = {
    devtool: 'source-map',
    debug: false,
    devServer: devServer,
    context: __dirname + '/src',
    entry: {
        app: [
            './'
        ]
    },
    output: {
        path: __dirname + '/endpoint',
        filename: '[name].js',
        publicPath: devServer.publicPath
    },
    plugins: [
        new ExtractTextPlugin('app.css', {
            allChunks: true
        }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.OldWatchingPlugin(),
        // new webpack.NewWatchingPlugin(),
        // https://github.com/webpack/docs/wiki/optimization#deduplication
        new webpack.optimize.DedupePlugin(),
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            {
                test: /\.js$/,
                include: path.resolve(__dirname, './src'),
                loader: 'babel'
            }
        ]
    },
    resolve: {
        extensions: [
            '',
            '.js'
        ]
    }
};
```

`babel-loader` is required.

**Comment by gajus** [comment] 2015-08-25 18:23
Removing `new webpack.optimize.DedupePlugin()` makes it work.

**Comment by chaseadamsio** [comment] 2015-09-03 22:40
Has anyone figured out _why_ this is causing this issue? I'm getting the same issue but deduping would be awesome rather than just getting rid of the plugin.

**Comment by gajus** [comment] 2015-09-11 11:05
Since this is happening only when using `webpack-dev-server`, a simple solution would be to include the plugin only when running `webpack` command.

**Comment by miaojing** [comment] 2015-09-16 02:42
I'm getting the same issue, I use it in webpack-dev-middleware.

**Comment by caccialdo** [comment] 2015-09-28 12:39
Getting the same error without using `webpack-dev-server` here. We deactivated the plugin but it would be nice to be able to use it.

**Comment by caccialdo** [comment] 2015-09-28 12:55
`rm-rf node_modules && npm i` solved the issue. Please ignore my previous message.

**Comment by nnnnathann** [comment] 2015-10-26 18:20
+1

**Comment by matthewmueller** [comment] 2015-11-11 02:25
+1

**Comment by le0pard** [comment] 2015-11-14 09:24
get the same issue today. `npm shrinkwrap` not safe from this.

**Comment by kyhwsk** [comment] 2015-11-26 03:54
+1

**Comment by coopy** [comment] 2015-12-29 17:44
I was having the same issue using Webpack 1.11.0. Upgrading to 1.12.9 seems to have fixed the problem. You folks should try again with a newer version and see if this issue can be closed.

**Comment by tribou** [comment] 2016-02-24 05:25
I just hit this issue after adding `twilio@^2` to my project which, in turn, required adding `json-loader`.  Commenting out the `Webpack.optimize.DedupePlugin` works as a temporary fix.  Just updated to `webpack@1.12.14` as well but still no luck.

Did anyone ever find the root cause to this issue?

**Comment by princed** [comment] 2016-02-24 07:45
@tribou https://github.com/webpack/webpack/issues/959#issuecomment-172795166

**Comment by tribou** [comment] 2016-02-27 18:44
Thanks!

For anyone encountering this in the future, the comment referenced above says:

> `Error: No template for dependency: TemplateArgumentDependency` happens when you have multiple webpack copies installed and used the DedupePlugin from a different copy.

I was using a `serverless-webpack-plugin` which had it's own `webpack` dependency it was using to bundle files.  However, I had manually installed and `require`d webpack in my project's webpack config as well (like you normally would with webpack).  Consequently, when I removed my explicitly installed version of webpack with `npm rm --save-dev webpack`, the plugin was able to `require` it's own scoped `webpack` dependency instead which worked.

I'll alert the `serverless-webpack-plugin` repo to this issue to figure out how to make it easier to use in the future.

**Comment by mouhsinelonly** [comment] 2016-05-11 13:46
did anyone fix this issue , everything works fine on my locale machine but when i try to compile on the server i receive this error 
i've deleted node_modules multiple times and did npm install,but with no luck

**Comment by tribou** [comment] 2016-05-11 23:14
Do you have any dependencies that are requiring webpack? Also, did you install webpack globally on your local machine?

**Comment by BerndWessels** [comment] 2016-05-12 01:53
I'm seeing this too

    ERROR in chunk app [entry]
    [name].bundle.js
    No template for dependency: TemplateArgumentDependency

But unfortunately there are no other useful information and I removed the Dedupe Plugin already.

Any idea what can I do to fix it?

Everything is locally installed.

**Comment by tribou** [comment] 2016-05-12 02:30
The issue I encountered above was that a dependency I was using didn't have webpack correctly listed as a `peerDependency`. Maybe verify that any webpack-related plugins or dependencies in your repo have webpack listed as a peer dep.

**Comment by BerndWessels** [comment] 2016-05-12 02:49
@tribou Thanks, I will look at that too.

But I guess my problem is a bit weirder - since exactly the same project copied to another machine (including node_modules) works fine on one machine but has this error on the other machine.

**Comment by arlair** [comment] 2016-06-21 07:28
In case this helps anyone, I think my issue was related to using `npm link`. See here: http://stackoverflow.com/questions/37915849/webpack-chunkrendererror-no-template-for-dependency-templateargumentdependenc/

**Comment by bebraw** [comment] 2016-12-24 07:27
I'm closing this as there's no `DedupePlugin` in webpack 2 anymore.

**Closed by bebraw** 2016-12-24 07:27 UTC
Labels: bug
