### ISSUE TITLE
namedChunksPlugin + dynamic import overwrites node_modules/babel-loader/lib/index.js

### ISSUE THREAD

**Issue by Francesco-Lanciana** [webpack/webpack#5017] opened 2017-06-06 12:56 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using the namedChunksPlugin on a web application involving dynamic imports, the chunk ID created leads to node_modules/babel-loader/lib/index.js being overwritten with the output of the lazy-loaded module.
As a result the first time you run "npm run build" the build succeeds, however the lazy-loaded module is not located in the build folder where it should be. As node_modules/babel-loader/lib/index.js is now the lazy-loaded module the second build fails with the following output:

<img width="1100" alt="screen shot 2017-06-02 at 5 14 38 pm" src="https://cloud.githubusercontent.com/assets/20393195/26829565/68d7b4f0-4b09-11e7-9aa1-73c1ab1d6bad.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
Below is a link to the repository with a minimal project that can reproduce the error.
https://github.com/Francesco-Lanciana/webpack-chunks-fault
run "npm run build" to build.

**What is the expected behavior?**
There should be five files written to the build folder. These are the index.html, and the app, vendor, manifest, and lazy-loaded module (named lazy.js).
The actual file names are dependent on the chunk name and an 8 digit hash, i.e.
[chunkName].[hash:8].[extension]

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
If namedChunksPlugin is removed then the problem no longer happens. Therefore the plugin must be the cause. I've had a look at the namedChunksPlugin and from what I can tell the nameResolver is somehow resolving the name of the lazy-loaded chunk to 
"../node_modules/babel-loader/lib/index.js??ref--0!/Users/frankface/WebpackWS/webpack-demo-min/app/lazy.js"

This must somehow be a result of babel-loader syntax-dynamic-import and the fact that we didn't supply a name for this chunk in the same way we did for the other chunks (vendor, manifest). In that case it uses the absolute path of the file which the babel-loader plugin appended some stuff to.

I used a quick hack and cut out the
"../node_modules/babel-loader/lib/index.js??ref--0!/"
substring of the chunk.id and it no longer overwrites index.js in babel-loader/lib/

My best guess is that when webpack outputs the bundles it uses the chunk.id, however that substring is interpreted to be the output path/filename and it overwrites the babel-loader file instead of simply outputting to the build folder.

Thanks for the help in advance, I'm a bit stumped on what to do with this one.

**Comment by sokra** [comment] 2017-06-07 12:37
cc @timse

**Comment by timse** [comment] 2017-06-07 13:55
i'll look into it!

**Comment by timse** [comment] 2017-06-09 23:34
heya, so the problem is with the function you pass into the `NamedChunksPlugin`

```
 return chunk.modules.map(m => path.relative(m.context, m.request)).join('_');
```

this creates things like :
```
../node_modules/babel-loader/lib/index.js??ref--0!/Users/timsebastian/Development/webpack-bugs/webpack-chunks-fault/app/lazy.js
```

therefore you would want to change the function to either also replace the "/" or to hash the output or something that prevents it from creating files that override your node modules

**Comment by timse** [comment] 2017-06-09 23:34
i'll close this issue for now, feel free to reopen.

**Closed by timse** 2017-06-09 23:34 UTC

**Comment by Francesco-Lanciana** [comment] 2017-06-13 02:52
Ahhh yep that would do it, il try hashing the output. Thanks a ton for the help

**Comment by lili21** [comment] 2017-10-30 03:19
@Francesco-Lanciana  did you fix this ?

**Comment by hinok** [comment] 2017-10-31 12:21
Just had exactly the same problem after implementing tips from https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31

Using some kind of hashing resolves the problem 👍 

@timse Maybe it's worth to update your article and add there a link to this issue?

**Comment by Francesco-Lanciana** [comment] 2017-11-01 00:21
I have implemented a fix but I'm not 100% confident that it's the right thing to do.

Pretty much that chunk.modules.map function takes a chunk and must return an id of that chunk. At the moment it outputs the difference between the context (I think its the absolute path of your application) and request (still confused as to what this is, but I think it’s the absolute path of the chunks entry point). This id naming causes files to be overwritten as the name is a path (E.g. "../node_modules/babel-loader/lib/index.js??ref--0!/Users/frankface/WebpackWS/webpack-demo-min/app/lazy.js”), which then causes the subsequent build to fail when the overwritten file is important.

I changed it to instead just output the id as the name of the chunk file. For example I dynamically import lazy.js from index.js so the id of that chunk would be lazy.js.  

Just replace the NamedChunksPlugin plugin with this:

      new webpack.NamedChunksPlugin((chunk) => {
        if (chunk.name) {
          return chunk.name;
        }
        return chunk.modules.map(m => {
           var pathComponents = m.request.split('/');
           return pathComponents[pathComponents.length-1];
         }).join('_');
      }),

I hope that helps. Using a hash as an id would also work nicely.

**Comment by lili21** [comment] 2017-11-01 05:36
@Francesco-Lanciana Thanks. that helps.

**Comment by cedeber** [comment] 2018-01-04 19:03
As `chunk.modules` is deprecated, here is a fixed and optimized version:
```js
new webpack.NamedChunksPlugin(
  chunk => chunk.name || chunk.mapModules(m => path.basename(m.request, ".ts")).join("_"),
)
```
Don't forget to remove or change the file extension in `path.basename` as needed.
