### ISSUE TITLE
Invalid code generation in 5.0.0-beta.14 with unused default exports

### ISSUE THREAD

**Issue by Pajn** [webpack/webpack#10573] opened 2020-03-18 09:40 UTC
# Bug report

**What is the current behavior?**
With 5.0.0-beta.14 the generated code for https://github.com/bvaughn/react-virtualized/blob/1a85f588420378aee32216e1c7f51d61155eb2b6/source/CellMeasurer/index.js
is:
```
/* harmony import */ var _CellMeasurer__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./CellMeasurer */ "./node_modules/react-virtualized/dist/es/CellMeasurer/CellMeasurer.js");
/* harmony import */ var _CellMeasurerCache__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./CellMeasurerCache */ "./node_modules/react-virtualized/dist/es/CellMeasurer/CellMeasurerCache.js");


/* unused harmony default export */ var _unused_webpack_default_export = (CellMeasurer);
```

This crashes with error `ReferenceError: CellMeasurer is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**
I have not tried to create a minimal reproduction but we just import `react-virtualized` with:

```ts
import {
  AutoSizer,
  Column,
  Table,
  TableCellProps,
  TableHeaderProps,
} from "react-virtualized"
```

**What is the expected behavior?**
That it would generate a bundle without reference errors :) It worked fine in 5.0.0-beta.13

I assume the unused default export would either have to be removed completely or rewritten to export `_CellMeasurer__WEBPACK_IMPORTED_MODULE_0__`

**Other relevant information:**
webpack version:  5.0.0-beta.14
Node.js version: 12.16.1
Operating System: Ubuntu 20.04
react-virtualized: 9.21.2

**Comment by Mistyyyy** [comment] 2020-03-18 13:10
duplicated #10542

**Comment by evilebottnawi** [comment] 2020-03-18 13:18
@Mistyyyy thanks

duplicate of #10542

**Closed by evilebottnawi** 2020-03-18 13:18 UTC
