### ISSUE TITLE
[BUG] Webpack freezes, runs forever (reproducible). Not sure why.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1312] opened 2015-07-30 01:05 UTC
For some reason, webpack just freezes and nothing happens. I'm not sure why.

To reproduce, just clone https://g.trusktr.io/trusktr/webpack-issue-1312.git, then run `webpack` in it's root. No need to run `npm install`, the node_modules folder is commited to the repo and everything is already installed.

Any idea why it freezes?

**Comment by trusktr** [comment] 2015-07-30 01:09
There's no output from `webpack --verbose`. It just starts then doesn't do anything.

**Comment by trusktr** [comment] 2015-07-30 03:02
I've tried different things. Seems like when I add the React dependency it just freezes.

**Comment by sokra** [comment] 2015-08-05 10:50
One thing that is propably wrong in the config is the `raw` loader combined with the glslify loader.

**Comment by sokra** [comment] 2015-08-05 10:51
But that's propably not the isse...

**Comment by trusktr** [comment] 2015-08-05 18:36
@sokra The `raw` loader combined with the `glslify` loader works great.

**Comment by bebraw** [comment] 2016-08-15 07:10
@trusktr Is this relevant still?

**Comment by trusktr** [comment] 2016-12-26 18:13
@bebraw Not sure, but I can just re-open it if encountered again.

**Comment by redevill** [comment] 2017-04-07 17:32
I am trying webpack for the first time, and the result was a hang :(
**Environmental Context -** Followed this install procedure/setup:
http://www.sochix.ru/how-to-integrate-webpack-into-visual-studio-2015/
VS2015 with update 3
VM Windows 7 Enterprise N SP1
npm -v = 4.2.0 global
node -v = 7.8.0 (64) global but using nvm to manage versions
webpack v = 2.3.3 local (node_modules of the project root)
babel-core v = 6.24.0 local
babel-loader v = 6.4.1 local
webpack-dev-server v = 2.4.2


FWIW:
Using this config (with the intent to have multiple input files) causes it to hang -
"use strict";
var path = require('path');

module.exports = {
    entry: {
        MgmtMainBundle: "./Scripts/Incident/MgmtMain.js"
    },
    output: {
        path: path.resolve(__dirname, './Scripts/dist"'),
        filename: "[name].js"
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: "babel-loader"
            }
        ]
    }
};

Changing to a standard single file as follows - runs
"use strict";
var path = require('path');

module.exports = {
    entry: "./Scripts/Incident/MgmtMain.js",
    output: {
        filename: "./dist/bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: "babel-loader"
            }
        ]
    }
};

**Comment by Ali-architrave** [comment] 2019-04-12 15:01
I am facing the same issue, have anyone got it solved? if yes can you help me to understand it? thanks, @bebraw looks like you had some reason to close this one?

**Comment by evilebottnawi** [comment] 2019-04-12 15:17
@Ali-architrave can you create minimum reproducible test repo?

**Comment by bebraw** [comment] 2019-04-12 18:22
@Ali-architrave There wasn't enough info to reproduce.

**Comment by Ali-architrave** [comment] 2019-04-15 06:32
@bebraw thanks, I still facing the same situation when trying to bundle a big app at once, its slow in this case, and it won't work if I try to build several bundles together, (` having an array as output od webpack config file)`

**Comment by Rickgrendel** [comment] 2019-05-02 13:52
I have the same issue when i use the dynamic `import()` the one with the promise. Webpack freezes and uses all my processor power.

**Comment by Ali-architrave** [comment] 2019-05-03 10:01
@evilebottnawi @bebraw, unfortunately, I can not provide you with a live example as I need a big  app to do so, but FYI the app I am working on is like 6 MB in one bundle,  I did three things to make it work:
1 - increase node memory (--max_old_space_size=8192)
2- using `thread-loader` to reduce the parallel jobs
3- I used to use an array as an output of `webpack-config` file to build two builds (legacy and modern) but I changed that to be just one build

hopefully, this information can help :)

**Comment by evilebottnawi** [comment] 2019-05-06 09:54
/cc @bebraw please stop reopen old issues, It is very uncomfortable and may confuse developers, we need open new issues on new problems, thanks

@Ali-architrave we still need reproducible test repo, maybe some of your loaders/plugins have memory leak and using memory ineffective way, please open new issues with reproducible test repo, thanks

**Closed by evilebottnawi** 2019-05-06 09:54 UTC
Labels: bug
