### ISSUE TITLE
Module exposed via ModuleFederationPlugin gets initialized twice

### ISSUE THREAD

**Issue by alex-vukov** [webpack/webpack#17246] opened 2023-05-23 05:51 UTC
# Bug report

**What is the current behavior?**

The issue is related to the Module Federation plugin. I have two applications `app1` and `app2`. `app1` exposes a module named `test.js` using the ModuleFederationPlugin. Both `app1` and `app2` use this module. The module named `test`contains a console.log() on top-level (i.e. outside of any function) which is expected to run only once the first time when the module is imported. However, the console.log() is triggered twice. First time when `test.js` is imported by `app1` and second time when it's imported by `app2`. I can see that the `__webpack_require__` is triggered twice for the same file in the two apps.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is a link to the repo which reproduces the problem:
https://github.com/alex-vukov/mf-issue
To reproduce it run the following steps:
1. npm install
2. npm start
3. Open localhost:3001 and open dev tools.
4. Reload the page and you'll see the console warning 'test.js loaded' logged twice.

In`app1` the `test.js` file is used only in `App.js` and is exposed in `ModuleFederationPlugin` in the webpack config file. In `app2` the same `test.js` file is dynamically imported inside `Button.js` and a function from it is used. That's when the duplicate initialization happens.

**What is the expected behavior?**

Expected behavior is that an exposed module should behave just like a regular module and should only be initialized once. `__webpack_require__` should somehow synchronise the cache for the already loaded exposed modules between the two bundles. This issue is directly causing problems with sharing Redux stores between applications where the store is usually initialized at the top-level of the store.js file.

**Other relevant information:**
webpack version:  5.83.1
Node.js version: 18.16.0
Operating System: Linux Ubuntu
Additional tools:

**Comment by alexander-akait** [comment] 2023-05-23 13:52
Maybe this https://github.com/webpack/webpack/pull/16625?

**Comment by alexander-akait** [comment] 2023-05-23 14:36
Okay, I looked deeply, it is not your case, just use in `app1`:
```
window['app1'].get('./test').then((factory) => {
    const module = factory();
    module.test();
});
```

instead `import foo from './test';`

Webpack doesn't know nothing about your sturcture and how module is used inside in other bundle, so we can't just sync, it's like an extra `script` tag when you load it, there is only one ability is using API, i.e. as I show above, it allows to undestand that module already loaded, also module can be executed twice inside bundle using special configurations or just use any query string. Also if we change this logic, we can break other people's apps because they rely on this behavior. 

Shorty - only `remoteEntry.js` knows which were loaded, inside standalone application own logic and standalone application knows nothing abote remote, if we will sync and other bunde load module faster than standalone, it potentially break logic standalone application because some modules can do side effects when loading.

Also we have `shared`, so technically you can create an extra application with Redux stores and share it between bundles, I would say that it is even more flexible, but of course it depends on the architecture.

So I am closing due expected behaviour, Anyway feel free to feedback

**Closed by alexander-akait** 2023-05-23 14:36 UTC

**Comment by alex-vukov** [comment] 2023-05-24 03:31
Thank you for the detailed explanation!

**Comment by alex-vukov** [comment] 2023-05-24 05:39
However, there is an inconsistency! When I switch to static federation (i.e. all the remotes are listed in the webpack configs of the two apps) if in app2 I use `import foo from app1/test` the module is indeed executed only once. However if I use `const foo = import('app1/test')` it is again executed twice. The inconsistency is that if I do the same test for a local module in the same two cases the local module gets executed only once. Shouldn't remote modules behave the same way?

**Comment by alexander-akait** [comment] 2023-05-24 13:54
> However if I use const foo = import('app1/test') it is again executed twice

It means you have racing, it is not good for an application

> Shouldn't remote modules behave the same way as local modules?

local modules !== remote modules, they don't have sync, because `remote` application has own state, `local` application has own state and as I said above there are side effects, anyway you can implement sync on the application side by hands
