### ISSUE TITLE
splitChunks make the global array `chunkLoadingGlobal` contain same chunk more times

### ISSUE THREAD

**Issue by zphhhhh** [webpack/webpack#12128] opened 2020-12-05 10:13 UTC
# Bug report

**What is the current behavior?**
On webpack 5, The global array `self["webpackChunkxxx"]` may contain same chunk more times when using splitChunks. When using webpack 4, it runs ok.

**If the current behavior is a bug, please provide the steps to reproduce.**
> or see https://github.com/zphhhhh/webpack-bug only well~

we use a global array like `self["webpackChunkxxx"]` to cache existing chunks, but it contains same chunk more times because `parentChunkLoadingFunction(data);`, see the output code:

```js
var webpackJsonpCallback = (data) => {
  // ...
  if (runtime) runtime(__webpack_require__);
  parentChunkLoadingFunction(data);
  while (resolves.length) {
    resolves.shift()();
  }

  // add entry modules from loaded chunk to deferred list
  if (executeModules) deferredModules.push.apply(deferredModules, executeModules);

  // run deferred modules when all chunks ready
  return checkDeferredModules();
}

var chunkLoadingGlobal = self["webpackChunkwebpack_bug"] = self["webpackChunkwebpack_bug"] || [];
var parentChunkLoadingFunction = chunkLoadingGlobal.push.bind(chunkLoadingGlobal);
chunkLoadingGlobal.push = webpackJsonpCallback;
```

**What is the expected behavior?**
> 

The global array `self["webpackChunkxxx"]` should contain same chunk just one time,
and **when using webpack 4, it runs ok**

You could change deps to webpack 4 in the Repo https://github.com/zphhhhh/webpack-bug , then it runs ok.

**Other relevant information:**
webpack version:  latest, 5.10.0
Node.js version: v12.18.2
Operating System: macOS 10.15.6
Additional tools:

**Comment by alexander-akait** [comment] 2020-12-05 13:23
Fixed in `webpack-dev-server@4.0.0-beta.0`, stable release will be in this month

**Comment by zphhhhh** [comment] 2020-12-05 13:52
> Fixed in `webpack-dev-server@4.0.0-beta.0`, stable release will be in this month

Thank u @alexander-akait , but I don't think it's a bug from `webpack-dev-server`.
Maybe the README from repo [webpack-bug](https://github.com/zphhhhh/webpack-bug) make you misunderstand:
```
Avoid webpack-dev-server, we could use `http-server`
```
and I've deleted it.

**Comment by alexander-akait** [comment] 2020-12-05 13:54
in webpack-dev-server@4-beta.0 there is not duplicate

**Comment by zphhhhh** [comment] 2020-12-05 14:11
but I test on  webpack-dev-server@4-beta.0 just now, there are duplicate chunks remaining. look the snapshot:

![image](https://user-images.githubusercontent.com/17380627/101245290-be9b0180-3746-11eb-9c83-441da0fa4619.png)

**Comment by vankop** [comment] 2020-12-05 15:21
this is by design, one module could be placed in several chunks, but it executes once.

**Comment by zphhhhh** [comment] 2020-12-05 16:40
@vankop in my demo repo, `src/math.js` is just placed in common chunk, but the global array `chunkLoadingGlobal`(or `self["webpackChunkwebpack_bug"]`) contains the same `src/math.js` more than one. 
and it may cause performance issue, 
![image](https://user-images.githubusercontent.com/17380627/101252538-265a4800-3759-11eb-8fa7-0075dd04cee9.png)

**Comment by zphhhhh** [comment] 2020-12-05 16:59
> this is by design, one module could be placed in several chunks, but it executes once.

BTW, in webpack 4 it runs well, but in webpack 5 it wrong.

**Comment by zphhhhh** [comment] 2020-12-05 17:15
i changed the demo , make bug more obvious. https://github.com/zphhhhh/webpack-bug

**Comment by zphhhhh** [comment] 2020-12-06 12:59
hi there, I has fixed this issue, review my PR and contact me if any question.

**Comment by sokra** [comment] 2020-12-06 19:02
This sounds like a bug to me. Each chunk should only be added once to the array. Looks like you are already working on a fix. Send a PR when ready. Thanks 👍

**Comment by zphhhhh** [comment] 2020-12-07 00:24
@sokra my PR is ready now~ https://github.com/webpack/webpack/pull/12131

**Closed** 2020-12-07 09:49 UTC
Labels: Send a PR, question, webpack-5
