### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined     at ModuleFederationPlugin.apply (***/node_modules/webpack/lib/container/ModuleFederationPlugin.js:45:49)

### ISSUE THREAD

**Issue by javajeans** [webpack/webpack#12165] opened 2020-12-10 09:37 UTC
# Bug report

**What is the current behavior?**

```
> vue-element-admin@4.4.0 dev /Users/apple/Code/01-Demo/01-End-to-End/vue-element-admin
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
    at ModuleFederationPlugin.apply (/Users/apple/Code/01-Demo/01-End-to-End/vue-element-admin/node_modules/webpack/lib/container/ModuleFederationPlugin.js:45:49)
    at webpack (/Users/apple/Code/01-Demo/01-End-to-End/vue-element-admin/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/apple/Code/01-Demo/01-End-to-End/vue-element-admin/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-element-admin@4.4.0 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-element-admin@4.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-12-10T09_23_58_524Z-debug.log
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

git clone https://github.com/javajeans/vue-element-admin.git

Execute in terminal：
```
npm i
npm run dev
```

ModuleFederationPlugin is configured in **vue.config.js**

**Other relevant information:**
webpack version:  5.10.0
Node.js version: v10.16.3
Operating System: Mac OS MoJave 10.14.3
Additional tools:

**Comment by sokra** [comment] 2020-12-10 09:55
Sounds like mixing webpack 4 and 5. Could you add a lockfile (`package-lock.json`) to your repro. btw. lockfiles should be committed, remove them from .gitignore

**Comment by alexander-akait** [comment] 2021-01-12 13:33
Answer above, feel free to feedback

**Closed by alexander-akait** 2021-01-12 13:33 UTC
Labels: question, webpack-5

**Comment by hugoebarboza** [comment] 2021-03-12 14:08
I have the same issue Cannot read property 'includes' of undefined".

**Comment by SUH11** [comment] 2021-03-19 10:00
> I have the same issue Cannot read property 'includes' of undefined".

Me too. So how to solve this problem?

**Comment by alexander-akait** [comment] 2021-03-19 11:43
Looks you forget to include runtime chink in your HTML files, if you provide example I will help

**Comment by simmi08** [comment] 2021-03-19 12:25
> Looks you forget to include runtime chink in your HTML files, if you provide example I will help

Hi ! This is the template project, for which I am getting the error -  https://github.com/simmi08/Microfrontends

**Comment by hugoebarboza** [comment] 2021-03-19 15:50
> > Looks you forget to include runtime chink in your HTML files, if you provide example I will help
> 
> Hi ! This is the template project, for which I am getting the error - https://github.com/simmi08/Microfrontends

Hi, if you are using Angular, try to follow this tutorial and use only yarn....https://github.com/angular-architects/module-federation-plugin/blob/main/packages/mf/tutorial/tutorial.md

**Comment by simmi08** [comment] 2021-03-19 16:01
> > > Looks you forget to include runtime chink in your HTML files, if you provide example I will help
> > 
> > 
> > Hi ! This is the template project, for which I am getting the error - https://github.com/simmi08/Microfrontends
> 
> Hi, if you are using Angular, try to follow this tutorial and use only yarn....https://github.com/angular-architects/module-federation-plugin/blob/main/packages/mf/tutorial/tutorial.md

I am following the same and had tried with yarn as well. But same error shows up with yarn also. The problem is  @angular-devkit/build-angular@0.1102.3 dependency on webpack 4.44.2, while for Module Federation plugin it requires webpack 5 or above.

**Comment by hugoebarboza** [comment] 2021-03-19 16:14
Hi @simmi08, I solved the issue following the tutorial I had sent you....doing it from scratch using only yarn / NOT NPM.....4 minutes ago my app worked well.

Package
{
  "name": "mf-demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "npm run start:shell",
    "start:shell": "ng serve shell  -o --port 5000",
    "start:mfe1": "ng serve mfe1 -o --port 3000",
    "start:all": "concurrently \"npm run start:shell\" \"npm run start:mfe1\" ",
    "build:shell": "ng build shell --prod",
    "build:mfe1": "ng build mfe1 --prod",
    "serve:dist": "concurrently \"serve dist/shell -l 5000 -s\" \"serve dist/mfe1 -l 3000 -s\" ",
    "build": "npm run build:shell && npm run build:mfe1",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "resolutions": {
    "webpack": "^5.0.0"
  },
  "dependencies": {
    "@angular-architects/module-federation": "1.2.3",
    "@angular/animations": "11.2.6",
    "@angular/common": "11.2.6",
    "@angular/compiler": "11.2.6",
    "@angular/core": "11.2.6",
    "@angular/forms": "11.2.6",
    "@angular/platform-browser": "11.2.6",
    "@angular/platform-browser-dynamic": "11.2.6",
    "@angular/router": "11.2.6",
    "@nrwl/workspace": "^11.5.1",
    "concurrently": "^6.0.0",
    "rxjs": "~6.6.6",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.5",
    "@angular/cli": "11.2.5",
    "@angular/compiler-cli": "11.2.6",
    "@types/jasmine": "~3.6.7",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.14.35",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "ngx-build-plus": "^11.0.0",
    "protractor": "~7.0.0",
    "serve": "^11.3.2",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "4.0.2"
  }
}

**Comment by simmi08** [comment] 2021-03-20 02:59
> Hi @simmi08, I solved the issue following the tutorial I had sent you....doing it from scratch using only yarn / NOT NPM.....4 minutes ago my app worked well.
> 
> Package
> {
> "name": "mf-demo",
> "version": "0.0.0",
> "scripts": {
> "ng": "ng",
> "start": "npm run start:shell",
> "start:shell": "ng serve shell -o --port 5000",
> "start:mfe1": "ng serve mfe1 -o --port 3000",
> "start:all": "concurrently "npm run start:shell" "npm run start:mfe1" ",
> "build:shell": "ng build shell --prod",
> "build:mfe1": "ng build mfe1 --prod",
> "serve:dist": "concurrently "serve dist/shell -l 5000 -s" "serve dist/mfe1 -l 3000 -s" ",
> "build": "npm run build:shell && npm run build:mfe1",
> "test": "ng test",
> "lint": "ng lint",
> "e2e": "ng e2e"
> },
> "private": true,
> "resolutions": {
> "webpack": "^5.0.0"
> },
> "dependencies": {
> "@angular-architects/module-federation": "1.2.3",
> "@angular/animations": "11.2.6",
> "@angular/common": "11.2.6",
> "@angular/compiler": "11.2.6",
> "@angular/core": "11.2.6",
> "@angular/forms": "11.2.6",
> "@angular/platform-browser": "11.2.6",
> "@angular/platform-browser-dynamic": "11.2.6",
> "@angular/router": "11.2.6",
> "@nrwl/workspace": "^11.5.1",
> "concurrently": "^6.0.0",
> "rxjs": "~6.6.6",
> "tslib": "^2.1.0",
> "zone.js": "~0.11.4"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "0.1102.5",
> "@angular/cli": "11.2.5",
> "@angular/compiler-cli": "11.2.6",
> "@types/jasmine": "~3.6.7",
> "@types/jasminewd2": "~2.0.8",
> "@types/node": "^14.14.35",
> "codelyzer": "^6.0.1",
> "jasmine-core": "~3.7.1",
> "jasmine-spec-reporter": "~6.0.0",
> "karma": "~6.2.0",
> "karma-chrome-launcher": "~3.1.0",
> "karma-coverage": "~2.0.3",
> "karma-jasmine": "~4.0.1",
> "karma-jasmine-html-reporter": "^1.5.4",
> "ngx-build-plus": "^11.0.0",
> "protractor": "~7.0.0",
> "serve": "^11.3.2",
> "ts-node": "~9.1.1",
> "tslint": "~6.1.0",
> "typescript": "4.0.2"
> }
> }

Hi ! Thanks, I copy-pasted this, it's working. But, still this warning is shown on doing yarn-
warning "@angular-devkit/build-angular > @ngtools/webpack@11.2.5" has incorrect peer dependency "webpack@^4.0.0".
warning "@angular-devkit/build-angular > @angular-devkit/build-webpack@0.1102.5" has incorrect peer dependency "webpack@^4.6.0".
warning "@angular-devkit/build-angular > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".

**Comment by lhf2** [comment] 2022-01-13 03:16
I also encountered the same problem. Has it been solved？vue-cli 4.x
