### ISSUE TITLE
webpack v3 mangling exports name will break `Array.from` of core-js

### ISSUE THREAD

**Issue by blade254353074** [webpack/webpack#5135] opened 2017-06-22 08:10 UTC
### **Do you want to request a *feature* or report a *bug*?**

Bug

### **What is the current behavior?**

> (I wanna cry: )The optimization of Scope Hoisting could break core-js `Array.from`.

**After updated to webpack v3. My code will throw the error:**

```log
Uncaught TypeError: Cannot assign to read only property 'length' of function 'function from() { [native code] }'
```

### **If the current behavior is a bug, please provide the steps to reproduce.**

The error due to wrong context:

* webpack use `__webpack_require__.n` & `__webpack_require__.d` to mangle exports name;
* Array.from transformed to `__WEBPACK_IMPORTED_MODULE_4_babel_runtime_core_js_array_from___default.a`;
* While calling `arrayfrom.a(arraylike)`, the context will be `function getDefault`;
* [es6.array.from.js#L15](https://github.com/zloirock/core-js/blob/8cf8d1e0cba3601fc533f8b27a3966d0d6100daf/modules/es6.array.from.js#L15), `C` will be `getDefault`;
* [#L25](https://github.com/zloirock/core-js/blob/8cf8d1e0cba3601fc533f8b27a3966d0d6100daf/modules/es6.array.from.js#L25) `new C()` will return `function from(arrayLike /* , mapfn = undefined, thisArg = undefined */) {...}`;
* `createProperty` will make the returned function property `length` read only;
* finally when it call `result.length = index`, the error `Uncaught TypeError` will be threw.

### **What is the expected behavior?**

![image](https://user-images.githubusercontent.com/9346008/27423701-0af63cb8-5765-11e7-8db4-6473deb40a38.png)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack v3

**Comment by blade254353074** [comment] 2017-06-22 09:45
Although can set `module.strictThisContextOnImports = true` to prevent the problem.

**Comment by STRML** [comment] 2017-06-22 13:25
See also https://github.com/webpack/webpack/issues/5111#issuecomment-309900873

**Comment by blade254353074** [comment] 2017-06-22 13:44
By the way, after built with `ModuleConcatenationPlugin,  my code was only reduced 8kb.

**Comment by alex-shamshurin** [comment] 2017-06-25 11:17
The same issue with 3.0.0

**Comment by ZhuGongpu** [comment] 2017-06-26 13:49
Same issue with webpack@3.0.0, any plan on it?

**Comment by STRML** [comment] 2017-06-26 13:57
This ticket is about `3.0.0`, no need to corroborate that you have this bug with the same version of webpack in the original issue.

**Comment by asmundg** [comment] 2017-06-27 08:05
@blade254353074 why did you close this? It's not fixed AFAIK. :)

**Comment by blade254353074** [comment] 2017-06-27 10:50
@asmundg Honestly, I'm not sure what's @STARML mean...

> This ticket is about 3.0.0, no need to corroborate that you have this bug with the same version of webpack in the original issue.

I thought he was saying that this issue is duplicated.....

**Comment by STRML** [comment] 2017-06-27 10:54
No, this is the canonical issue and should be reopened. I was chastising
the other commenter for saying they had this issue with 3.0.0, because
that's the same version the ticket is about anyway - saying you also have
this issue with 3.0.0 is not new information.

**Comment by blade254353074** [comment] 2017-06-27 10:56
Hahaha sorry, I misunderstood. 😂

**Comment by htulipe** [comment] 2017-06-28 13:52
My 2 cents. I experienced this issue when trying to set up ModuleConcatenationPlugin. For this plugin to work I add to tell babel to not parse modules:

    {
      "presets": [["es2015", { "modules": false }], "stage-0", "react"],
      ...
    }

It's exactly that setting that start throwing errors, whether I use ModuleConcatenationPlugin or not.

**Comment by Andarist** [comment] 2017-06-30 09:58
Aint sure where this should be fixed, but I've proposed a quick fix in the `core-js`. Maybe @zloirock will have some insight what should be done to fix it properly.

**Comment by STRML** [comment] 2017-06-30 12:25
It's definitely not a core-js bug.

**Comment by Kovensky** [comment] 2017-07-06 01:55
The problem is a size optimization that webpack does by default by not correctly setting the `this` when calling an import directly as a function.

Enable `strictThisContextOnImports` to fix this, as mentioned in https://github.com/webpack/webpack/issues/5135#issuecomment-310331312. It will change your invocation from `arrayfrom.a(arraylike)` to `__webpack__require__.i(arrayfrom.a)(arraylike)`, so that it will correctly have no context.

babel does the same without using a helper function, though (the babel equivalent would be `(0, arrayfrom.a)(arraylike)`); maybe webpack could do that too.

**Comment by Andarist** [comment] 2017-07-07 08:45
@Kovensky 
this whole thing also affects simple case of
```js
// setImmediate.js
export default setTimeout

// otherfile.js
import setImmediate from './setImmediate'
setImmediate(() => console.log('smth'), 0) // Uncaught TypeError: Illegal invocation
```
It's because its invoked now with some object as a context and from what I can see your proposed fix doesnt solve this:
```js
var obj = { timeout: setTimeout }
(0,obj.timeout)(() => console.log('smth'), 1000) // Uncaught TypeError: (intermediate value) is not a function
```

Would it be maybe possible for webpack to analyze what's getting imported and wrap a whitelisted items (`Array.from`, `setTimeout`, `setImmediate` for starters) appropriately?

**Comment by TheLarkInn** [comment] 2017-07-07 16:24
@Kovensky Does this behavior need to be specifically documented? I'm feeling like its an obvious confusion here after reading the thread.

**Comment by Andarist** [comment] 2017-07-07 18:05
@TheLarkInn Personally I feel this is not a matter that can be solved with a documentation. From what I understand this option `strictThisContextOnImports` was introduced as opt-out from the default tree-shaking optimizations for cases where a module could use `this` as a module itself (preventing effectively any tree shaking). 

As this being seen as poorly/weirdly designed code its completely fine to have such a default, so its not needed to bail out of the tree-shaking in many cases.

However we deal here with completely different situation - those exported functions (`setTimeout`, `setImmediate`, `Array.from` and possibly more) can be assigned easily to a variable and used, but such exports got broken in webpack3 due to how it wraps modules.

Maybe the wrapping method can be changed? Or maybe a code can analyze statically whats getting imported and wrap differently for those few built-ins?

Otherwise we have basically only 2 possible solutions for this:
- change every package which export those, like [here](https://github.com/facebook/fbjs/pull/247/files#diff-3c1821b759afbba664174414c690c185R17) - far from ideal
- recommend using `strictThisContextOnImports: true` which kinda kills the whole point of having the `false` as default and I think the optimization it brings its a good one - this is even worse than former

**Closed** 2017-07-11 18:36 UTC
Labels: P3: Important, X1: Inspection required, X3: discussion required
