### ISSUE TITLE
@types/eslint-scope@3.7.2 dependency doesn't exist but is present in yarn.lock

### ISSUE THREAD

**Issue by GregoireLgt** [webpack/webpack#15059] opened 2021-12-27 15:41 UTC
# Bug report

**What is the current behavior?**
Webpack has a direct dependency to a nonexistent package (@types/eslint-scope@3.7.2)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Webpack should not have a direct dependency to a nonexistent package (@types/eslint-scope@3.7.2)

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 14.16.1
Operating System: Windows 10
Additional tools: Angular 12 / Angular 13

**Comment by denyseflo** [comment] 2021-12-27 15:57
I agree, this problem is present in almost all Webpack v5.x.x versions.
@types/eslint-scope@3.7.2 has been flagged has malicious and removed from npm : https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

**Comment by alexander-akait** [comment] 2021-12-27 16:00
We use https://github.com/webpack/webpack/blob/main/package.json#L8, if somebody unpublished it will unavailable if you updated lock file before, nothing to fix on webpack side, sorry

**Comment by alexander-akait** [comment] 2021-12-27 16:02
Anyway it should not be a problem for other packages

**Comment by alexander-akait** [comment] 2021-12-29 12:21
I think we can close it because `3.7.2` in npm register (https://www.npmjs.com/package/@types/eslint-scope), also our lock file has no effect on your project, maybe something was wrong with the register, I can't reproduce it locally, feel free to feedback, also we have https://github.com/webpack/webpack/blob/main/package.json#L8, i.e. `3.7.0`

**Closed by alexander-akait** 2021-12-29 12:21 UTC
Labels: webpack-5, dependencies

**Comment by GregoireLgt** [comment] 2021-12-30 10:38
@alexander-akait 

**For anyone who is having problems with eslint-scope@3.7.2 :** 

The final solution was to force eslint-scope to another version in our own package.json (in our project) so the 3.7.2 malicious one is not retrieved.

**Comment by tatethurston** [comment] 2022-01-05 20:54
To expand on what @laurentiustroia mentions above, a recent package update for the type definitions for `eslint-scope` https://www.npmjs.com/package/@types/eslint-scope was published. That published version is `3.7.2` which matches the unpublished version of eslint-scope [which was compromised](https://github.com/npm/npm/issues/21202). If you're using an npm mirror, it's security settings may be preventing you from downloading @types/eslint-scope because of the suffix matching.
