### ISSUE TITLE
Optional chaining operator is removed incorrectly

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#15134] opened 2022-01-10 08:32 UTC
# Bug report

**What is the current behavior?**
Optional chaining operators being removed which causes a runtime errors. 

**If the current behavior is a bug, please provide the steps to reproduce.**

env.js
```js
export const env = {}
```

index.js
```js
import { env } from './env';
console.log(env.foo?.bar)
```

config
```js
const { resolve } = require("path");

module.exports = {
  devtool: false,
  mode: "development",
  entry: "./index.js",
  target: ["web", "es2020"],
  node: false,
};
```

Output
```js
/*!******************!*\
  !*** ./index.js ***!
  \******************/
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _env__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./env */ "./env.js");

console.log(_env__WEBPACK_IMPORTED_MODULE_0__.env.foo.bar)
})();
```

**What is the expected behavior?**
Operator is retained.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 14.18.1
Operating System: darwin x64
Additional tools:

**Comment by vankop** [comment] 2022-01-10 09:00
duplicate of https://github.com/webpack/webpack/issues/12960

**Closed by vankop** 2022-01-10 09:00 UTC
