### ISSUE TITLE
UglifyJsPlugin incorrectly adding `\t` to the end of line for multiline string.

### ISSUE THREAD

**Issue by ye11ow** [webpack/webpack#2898] opened 2016-08-21 11:26 UTC
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.6
Node 5.1.0

**Current behavior:**
The multiline string are joined by `\t`

**Expected/desired behavior:**
The multiline string should be joined by a single space.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

Considering a source file `app.js`:
```JavaScript
var test = "first line\
second line\
";
```
It is compressed to the following by using `webpack.optimize.UglifyJsPlugin`
```JavaScript
var e="first line\tsecond line\t";
```

The `webpack.config.js` is very simple
```JavaScript
var webpack = require('webpack');

module.exports = {
     entry: './app.js',
     output: {
         path: './',
         filename: 'app.bundle.js'
     },
     plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ]
 };
```

* **What is the expected behavior?**

Should be compressed to 
```JavaScript
var test="first linesecond line"
```
This is how r.js compress it.

* **What is the motivation / use case for changing the behavior?**

Added `\t` to the original string is dangerous.
 
* **Browser:** [all] 
 
* **Language:** [ES6/7 | ES5]

**Comment by ye11ow** [comment] 2016-08-21 13:46
BTW, I notice that Webpack uses uglify-js to compress the code. However, I tried to compress the source code by using uglify-js directly, it just works good (no `\t`). So most likely this issue is related to Webpack itself.

**Comment by TheLarkInn** [comment] 2016-08-21 19:39
Would you mind updating to webpack2 and seeing if this issue is still prevalent? I was not able to reproduce it myself on webpack@2.1.0-beta.21.

**Comment by ye11ow** [comment] 2016-08-22 01:18
Hi @TheLarkInn, I tried webpack@2.1.0-beta.21. It works good. The original source is compiled to
```JavaScript
```

**Comment by sokra** [comment] 2016-08-22 07:48
This was fixed in webpack 2. You can fix it in webpack 1 with `output.sourcePrefix = ""`

**Closed by sokra** 2016-08-22 07:48 UTC
Labels: bug, need more information, waiting on response

**Comment by ye11ow** [comment] 2016-08-22 08:06
@sokra Thanks!
