### ISSUE TITLE
require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by olalonde** [webpack/webpack#2675] opened 2016-06-20 21:27 UTC
I added `console.log(require.ensure)` to my code and it resulted in thousands of error lines from webpack. Had to increase my tmux scrollback to 40K lines to see what happened.

```javascript
[...]
WARNING in ./src/routes.js
Critical dependencies:
158:18-25 require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/routes.js 158:18-25

WARNING in ./src/containers/Admin/TODO.md
Module parse failed: /Users/olalonde/code/project/src/containers/Admin/TODO.md Unexpected token (1:13)
You may need an appropriate loader to handle this file type.

[...]
```

Not sure if it's really a bug but would have been nice if that message had been isolated from all the subsequent thousands of error lines that are really irrelevant.

**Comment by sokra** [comment] 2016-06-22 08:03
This is fixed in webpack@2

**Closed by sokra** 2016-06-22 08:03 UTC
Labels: enhancement

**Comment by minnaq** [comment] 2016-09-04 07:55
with webpack@2, it's reproduced again.
```` jsx
function getAsyncComponent(path, chunkname) {
  return function(nextState, cb) {
    require.ensure([], function(require) {
      cb(null, require(path).default)
    }, chunkname)
  }
}

const Routes = (
  <Router history={browserHistory}>
    <Route path='/' getComponent ={ getAsyncComponent('./App.jsx','asyncApp') }>
      <IndexRoute component ={ Home} />
      <Route path='/hello' component = {Hello} />
      <Route path='author' component = {AuthorList}>
        <Route path= ':id' component = {Author} />
      </Route>
    </Route>
  </Router>

)

export default Routes;

````

**Comment by Kovensky** [comment] 2016-09-05 04:26
@minnaq it indeed is being used in a way in which dependencies cannot be statically extracted.

`require.ensure([]` is asking for webpack to load 0 modules (???), but more importantly, the `require(path)` is a require of a free variable with no context. Webpack doesn't go as far as doing program flow analysis to find out that your `getAsyncComponent` is only called with `'./App.jsx'` with chunkname `asyncApp`.

**Comment by mnpenner** [comment] 2016-09-27 21:35
@Kovensky 

> `require.ensure([]` is asking for webpack to load 0 modules (???)

That part seems to be supported. Search [this page](https://webpack.github.io/docs/code-splitting.html) for `[]`. Although I can't find any information on how that works.

**Comment by drewwells** [comment] 2016-12-07 15:50
Is it possible to get webpack to ignore these errors? Then allow the amd-plugin that builds for the runtime to find bundles that you package via separate webpack configs ie. i18n 

A more complete example of https://github.com/webpack/i18n-webpack-plugin would be helpful here

**Comment by mrdulin** [comment] 2016-12-19 07:14
same issue. How to solve this? Thanks.

**Comment by lili21** [comment] 2016-12-26 08:43
How this one be closed ?

**Comment by drewwells** [comment] 2016-12-26 17:56
The short answer is that webpack statically analyzes your require statements explained here: https://webpack.github.io/docs/context.html

Fixing this is different for every case. If you post some code somebody should be able to point you in the right direction. https://gitter.im/webpack/webpack

**Comment by olalonde** [comment] 2016-12-28 02:43
@drewwells the real issue was that thousands of lines were printed making it hard to find out what the issue was

**Comment by drewwells** [comment] 2016-12-28 03:02
I understand there was a specific start to this thread, but the title indicates a more general issue that people find via Google searches. This being the use of variables in require() calls. It may help to change the title or open a new issue about console.log() if its desired to fix that. I don't think that particular bug will be addressed, since require.ensure is documented already: https://webpack.github.io/docs/code-splitting.html#commonjs-require-ensure

**Comment by stevenvachon** [comment] 2017-02-20 17:32
I'm getting this error with this line:
```js
const broquire = require("broquire")(require);
```

**Comment by lovepluskaka** [comment] 2017-04-08 07:53
### My code is:   
     if (configs.renderingConfig && configs.renderingConfig.codeSyntaxHighlighting) {
             require.ensure([], () => {
                    const theme = configs.renderingConfig.highlightingTheme || 'default';
                    window.hljs = require('highlight.js');
                    require(`highlight.js/styles/${theme}.css`);
             }, 'highlight');
      }
There is the same warning in terminal  

> require function is used in a way in which dependencies cannot be statically extracted

And there is also two error in browser  

> Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete 

> vendor.js?v=20170309:92 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete

**Comment by Rookian** [comment] 2017-04-10 12:54
I get the same error for typedjson-npm. 

WARNING in ./~/typedjson-npm/js/typed-json.js
25:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted.

**Comment by prateekjahead** [comment] 2017-05-03 11:01
My problem was solved by making following change - 

**FROM**
```
const moduleName = 'moduleName';

function getComponent(location, cb) {
  require.ensure([], require => {
    cb(null, require('./components'));
  }, moduleName);
}
```

**TO**
```
function getComponent(location, cb) {
  require.ensure([], require => {
    cb(null, require('./components'));
  }, 'moduleName');
}
```
i.e, avoiding the use of a `const` variable for the string 'moduleName'. 

Don't know the reason though. :|

**Comment by arcanis** [comment] 2017-05-06 23:52
Using `typeof require.context` generates warnings as well.

**Comment by TaroWong** [comment] 2018-01-05 21:12
My problem is this 

` <img src={require`${this.state.currentIco}`} `

Are there any ways to fix this?

**Comment by atav32** [comment] 2018-01-17 02:21
My problem was a line in a library similar to

```javascript
var library = {};
library.require = require;  // whyyyyy
```

**Comment by d0ruk** [comment] 2018-02-27 18:57
Same here. [@storybooks/storybook](https://github.com/storybooks/storybook) config goes like this;

```
const req = require.context("../stories", true, /.stories.js$/);
function loadStories() {
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

Replacing line 1 with;

```
const PATH = resolve("..", "stories");
const req = require.context(PATH, true, /.stories.js$/);
```
errors (warns?) with

> Critical dependency: require function is used in a way in which dependencies cannot be statically
 extracted

Using webpack@3.11.0

**Comment by Kovensky** [comment] 2018-02-28 00:32
That is because the code was changed from calling require.context in a way that was analyzable into a way that isn't. Webpack doesn't know what your arbitrary "resolve" function returns, or that PATH is immutable (if you compile your code to ES5)

**Comment by d0ruk** [comment] 2018-02-28 01:20
@Kovensky 

From what I understand, this warning means the dependencies are not statically analyzable, and thus cannot be tree-shaken. Is this correct?

Is there anything else I should be aware of?

If I weren't compiling down to ES5, would webpack figure out that PATH is immutable?

**Comment by Kovensky** [comment] 2018-02-28 01:43
The bigger problem here is that webpack doesn't know what the result of `resolve` is. It's just a random user function that can do anything at runtime.

This is also not about tree-shaking, this is about knowing what to bundle in the first place. If webpack can't see that you're trying to look into the `../stories` directory via simple string parsing, it doesn't know that it needs to put the files in `../stories` in a context module.

**Comment by jony89** [comment] 2018-03-11 10:25
@sokra this is reproduced with webpack@3.11.0 as well.

**Comment by hxuanhung** [comment] 2018-03-15 10:30
@jony89 what is your `webpack-dev-server`'s version?  try to upgrade to `2.9.7`

**Comment by senyaak** [comment] 2018-03-27 09:45
Im using https://github.com/biesbjerg/ngx-translate-extract and get this error when using marker function to extract strings :( 
webpack 3.11.0

**Comment by montogeek** [comment] 2018-03-27 10:00
@senyaak Submit an issue to that repo

**Comment by senyaak** [comment] 2018-03-27 10:49
@montogeek this is a webpack issue...

**Comment by aj-r** [comment] 2018-04-27 19:38
In case anyone else comes across this - I got this error because I was using `"module": "umd"` in my `tsconfig.json`. The solution was to use `"module": "commonjs"` instead - you can still get umd output by using `libraryTarget: "umd"` in `webpack.config.js`.

**Comment by yeyuguo** [comment] 2018-06-27 08:02
@aj-r  it's work

**Comment by simeyla** [comment] 2018-07-17 19:15
You can get this error if you accidentally import something from `/@angular/compiler` instead of `/@angular/core`. With auto-import this can happen easily.

For example this just happened to me when I used `ChangeDetectionStrategy` and VSCode suggested the compiler package - and I accepted it without realizing.

**Comment by sumantaparida** [comment] 2019-01-29 19:20
WARNING in ./node_modules/html-webpack-plugin/index.js 242:85-92
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/dynamic-cdn-webpack-plugin/lib/index.js
 @ ./node_modules/dynamic-cdn-webpack-plugin/index.js
 @ dll reactBoilerplateDeps
