### ISSUE TITLE
why webpack 4 is solwer than webpack3 both in development

### ISSUE THREAD

**Issue by xiaoxiaosaohuo** [webpack/webpack#7087] opened 2018-04-20 09:23 UTC
node v8.10.0
npm 5.6.0
os mac
webpack 4.6.0

**Comment by evilebottnawi** [comment] 2018-04-20 10:05
@jinxin479 Please use issue template, also please provide your configuration and/or minimum reproducible test repo. Thanks!

**Comment by glen-84** [comment] 2018-04-20 13:17
Could be a duplicate of #6767?

**Closed as completed** 2018-04-20 13:21 UTC
