### ISSUE TITLE
Using webpackChunkName with dynamic import changes chunk logic

### ISSUE THREAD

**Issue by hoschi** [webpack/webpack#4807] opened 2017-05-02 14:59 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using a `import()` that uses a variable (dynamic import) each file gets into its own chunk. When adding a name to the import, all files get bundled into one chunk instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create import:
```js
export let config = {
    resolve: (props) => import(`templates/${props.templateId}`),
};
```
run build and you get one chunk *per file* in "templates/"

Use naming feature:
```js
export let config = {
    resolve: (props) => import( /* webpackChunkName: "templates" */ `templates/${props.templateId}`),
};
```
run build and you get one chunk which contains *all files* in "templates/"

**What is the expected behavior?**

Always create one chunk per file in "templates/". When I cant one chunk for all files I can use `require.ensure` instead.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
webpack@2.4.1 

frontend > npm --version
3.10.3
frontend > node --version
v6.3.1
```
OS is Arch Linux

**Comment by obituz** [comment] 2017-05-04 11:24
A chunkname with dynamic parts would be nice to solve this problem.

**Old version (works)**
```
require('bundle?name=[name]!i18n/' + namespace + '-i18n-bundle-' +language +'.json')(i18nBundle => {...}))
```

**New version (doesn't work)**
```
import(/* webpackChunkName: `i18n/${namespace}-i18n-${language}` */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

**Comment by ematipico** [comment] 2017-05-09 09:52
I would say that is a feature :)

**Comment by niieani** [comment] 2017-05-10 08:22
Does this fix the issue? https://github.com/webpack/webpack/pull/4818

**Comment by ematipico** [comment] 2017-05-10 08:51
Quoting from the summary of #4818 
> Fix a bug which caused context chunks to be merged when using chunk name

I guess it does

**Comment by niieani** [comment] 2017-05-10 09:09
@ematipico it's not been released. Also you need to specify the `webpackChunkMode`, see that sources of that PR.

**Comment by hoschi** [comment] 2017-05-10 09:21
I'll check it when it is released, thanks for the update @niieani

**Comment by sokra** [comment] 2017-05-10 10:39
``` js
import(/* webpackChunkName: "i18n/[request]" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

This works after the PR. Will generate chunk names like `i18n/namespace-i18n-bundle-en_json`.

``` js
import(/* webpackChunkName: "i18n" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

This will generate names like: `i18n-0`, `i18n-1`, `i18n-2` (for each json file).

There is a new `webpackMode` option which allows to specify the behavior:

``` js
import(/* webpackMode: "lazy" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

The default behavior. Lazy generates a chunk per request. So everything is lazy loaded.

``` js
import(/* webpackMode: "eager" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

Eager generates no chunk. All files are included in the current chunk. No network request is required to load the files. It still returns a promise but it's already resolved. Similar to:

``` js
Promise.resolve(require(`i18n/${namespace}-i18n-bundle-${language}.json`)).then(...)
```

``` js
import(/* webpackMode: "lazy-once" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

Only available for imports with expression. Generates a single chunk for all possible requests. So the first request causes a network request for all modules, all following requests are already fulfilled.

``` js
import(/* webpackMode: "lazy-once", webpackChunkName: "all-i18n-data" */ `i18n/${namespace}-i18n-bundle-${language}.json`).then(...)
```

You can combine both options. It's parsed a json5 object without curly brackets.

**Comment by obituz** [comment] 2017-05-11 07:11
Thanks @sokra. It has already been released with 2.5.1, hasn't it?

I've tried several options (with webpackMode and without) but none worked.

```javascript
import(/* webpackChunkName: "i18n/[request]" */ `i18n/${namespace}-i18n-bundle-${language}.json`)
```
produces a single chunk ```i18n/[request].38d4a189.chunk.js```.

Maybe a problem with the json suffix?

**Comment by kanzelm3** [comment] 2017-05-11 14:59
@sokra any ETA on next release date that will include the fix?

**Comment by roastlechon** [comment] 2017-05-16 06:29
I am also interested!

**Comment by gaearon** [comment] 2017-05-27 11:47
Seems like it's released in 2.6.1?

**Comment by kanzelm3** [comment] 2017-05-27 12:41
Looks like it is.

**Comment by VoronFX** [comment] 2017-09-01 13:43
I can't get working [request] nor [index] nowhere. 
I've created the simplest config and copy pasted examples. Nothing works, every time [request], [id] and [index] are copied as is, although [query] seems resolves to empty string.
Tried webpack versions 3.5.5, 2.6.1, 2.6.0, 2.7.0.
Does anyone have this working? If so, how?

**Comment by chbdetta** [comment] 2017-12-27 09:23
@VoronFX 
It seems `[request]` wont work if constant string literal is used to import module.
e.g.
```js
import(
  /* webpackChunkName: "[request]" */
  "./animals/Cat"
);
```
In the above code, `[request]` won't be parsed.

But when I change it to something like below:
```js
const cat = "Cat";
import(
  /* webpackChunkName: "[request]" */
  `./animals/${cat}`
);
```
now `[request]` will be replaced with `Cat`.

I think maybe `[request]` refer to the variable parts in the import url ? But what if there are more than one variable?

I expected the [request] is replaced with the actual file path `import` resolves to.

**Comment by rosenfeld** [comment] 2017-12-27 11:35
I was able to get `[request]` working in a second attempt. However it would be interesting if I could use something like `[configId]` and be able to set the config id when using multiple configurations. For the time being, I'm using the "map" option with the ManifestPlugin to be able to get separate names for each configuration:

```javascript
  const manifestPlugin = new ManifestPlugin({
    filter: function(m) { return !/\.map$/.test(m.path) },
    map: function(m) {
      if (m.path.indexOf('.legacy.') !== -1 && m.name.indexOf('-legacy') === -1)
        m.name = `legacy/${m.name}`;
      return m;
    },
    publicPath: publicPath, seed: {}
  });
```

**Comment by Mouvedia** [comment] 2018-01-26 17:42
@sokra when you something like
```
  import(/* webpackMode:      "lazy-once",
            webpackChunkName: "custom-name" */
         `../../components/foo/bar/${pathname}`);
```

Will it work for `pathname === 'baz/qux.vue'` as well?
Does it drill in the sub-directories?

**Comment by miaulightouch** [comment] 2018-03-12 05:00
can I use `import()` to list mapped keys like `require.context`?

I write these code before:
```javascript
  const availableLangs = []
  forEach(require.context('./translations', false, /\.json$/).keys(), file =>
    availableLangs.push(file.replace(/\.\/|\.json/g, '')))
```
but all locale content would built into main chunk, I have to manually maintenance this `availableLangs` list.

how can I get all possible keys from webpack without building all locale into main chunk?

**Comment by kof1290** [comment] 2019-04-15 06:05
can i pass vriable into `webpackChunkName `like this
```js
/* webpackChunkName: ${my-name} */
```

**Comment by fancyboynet** [comment] 2019-06-03 02:29
@sokra can you explain what does the `${namespace}` mean?thx.

**Comment by cxx1993** [comment] 2019-06-05 03:07
> @sokra can you explain what does the `${namespace}` mean?thx.

import(/* webpackChunkName: "${namespace}" */ `views/${namespace}/${file}.vue`)

**Comment by Haraldson** [comment] 2019-11-17 11:00
This can’t be used alongside `webpackMode: "lazy-once"`, it seems?

**Comment by yvele** [comment] 2020-03-02 10:05
Why is Webpack by itself not able to generate a developer friendly name for dynamic imports when using `chunkFilename : "[name].js"`?

For example with this configuration:

```js
{
  output : {
    chunkFilename : "[name].[chunkhash].js"
  }
}
```

When I'm doing:

```js
import("./animals/Cat");
```

Webpack should be able to generate the chunk name like that:

```
animals~Cat.60feccc3f820a06037c9.js
```

🤔

**Comment by ematipico** [comment] 2020-03-02 13:44
@yvele you can, just use the magic comments: https://webpack.js.org/api/module-methods/#magic-comments

**Comment by yvele** [comment] 2020-03-02 14:32
> @yvele you can, just use the magic comments: [webpack.js.org/api/module-methods/#magic-comments](https://webpack.js.org/api/module-methods/#magic-comments)

Sure but I don't see the added value of using individual magic comments for all dynamic imports when a generic developer friendly name is OK for me.

Why a this single `chunkFilename : "[name].js"` configuration doesn't do the trick? Webpack already knows how to generate a `name` for "static" chunks. Why are dynamic chunks specials regarding naming? 🤔

**Comment by evilebottnawi** [comment] 2020-03-02 14:50
@yvele What about if you write 
```js
await import(`./dir/${file}`);
```

What is name we should used?

**Comment by yvele** [comment] 2020-03-02 17:33
> @yvele What about if you write
> 
> ```js
> await import(`./dir/${file}`);
> ```
> 
> What is name we should used?


Webpack generates all **chunk files** and knows exactly where comes the source chunks in each **chunk file**.

Why do not use a name based on the **source file name** by default?

If the resolved source file name is `src/foo/bar/baz.js` Webpack may use `foo~bar~baz.js` for the chunk file name?

**Comment by knynkwl** [comment] 2020-06-18 19:40
I am looking to dynamically change `webpackMode` based on in `development` or `production` to save time on bundling.

I there a way to dynamically change this?

I know below wont work, but is there another way?
```javascript
let dynamicMode = process.env.NODE_ENV === 'development' ? 'lazy-once' : 'lazy';
import(/* webpackMode: ${dynamicMode} */ `../components/${moduleName}`).then(func)
```

I am trying to avoid having to fo this for every import:
```js
if(process.env.NODE_ENV === 'development) {
  import(/* webpackMode: 'lazy-once' */ `../components/${moduleName}`).then(func)
} else {
  import(`../components/${moduleName}`).then(func)
}
```

**Comment by lalo-mx** [comment] 2020-07-07 17:05
> This can’t be used alongside `webpackMode: "lazy-once"`, it seems?
> 
> Also: Chunks seem to be generated for all nested, normal import statements?

Any alternatives for the lazy-ony mode? For example when wanting to combine locale files. https://stackoverflow.com/questions/61035621/how-do-i-dynamically-import-locales-in-angular-9

**Comment by dmantsevich** [comment] 2021-02-12 16:30
Maybe webpack supports param, which can "override" [request] in chunkName option?

I mean:
By default: 
`import(/* webpackChunkName: `[request]` */ @components/${componentID});`

generates very long names: "**app-layer-component-add-event-component-add-event-add-event-component-asset-index-component-asset.hashhash.js**"


Is it possible to define custom function for chunk name generator?

**Comment by cristianmdev** [comment] 2021-05-19 03:20
Se van a volver locos pero podrían intentar un enfoque similar a este
`
            // Widget
            const Widget = React.lazy( () => 
                  import( 
                    eval(
                        `
                          /* webpackMode:"lazy-once" */
                          /* webpackChunkName:"${widgetName}" */
                          "../../Widgets/${widgetName}/${widgetName}.js"
                          ` 
                        )
                  ) 
            );
`

**Comment by vankop** [comment] 2021-09-15 19:29
Should work with `webpack@5`. Feel free to report new issue with reproducible repo.

**Closed by vankop** 2021-09-15 19:29 UTC

**Comment by joe94113** [comment] 2023-02-20 03:47
@chbdetta Thank you so much

I use dynamic import in`laravel x Vue x inertiajs`, the following is my `app.js`
```js
const app = createInertiaApp({
    title: //,
    // add output name of the page
    resolve: (name) => import(/* webpackChunkName: "[request]" */`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        //
    },
});
```
