### ISSUE TITLE
RealContentHashPlugin mangles valid javascript assuming an integer is a module hash

### ISSUE THREAD

**Issue by issacgerges** [webpack/webpack#18390] opened 2024-05-07 23:31 UTC
# Bug report

**What is the current behavior?**
With `realContentHash` enabled, `webpack` does a pass of module content replacing identifiers it knows have updated. [This code](https://github.com/webpack/webpack/blob/main/lib/optimize/RealContentHashPlugin.js#L199-L202) generates a regex thats used to detect and replace matches. Although rare, these module identifiers can match valid integers in code, mangling the output

In our case, this was the generated regex

```
/7151687|16ad854|b1e006d|9c15c6e|5bd0714|ad2663b|3b5d601|076b0ae|a7f4bb9|de5c80c|6ffc7e7|45c2905|41e45fb|5412984|010b7ba|d3b2014|c88432f|458f47c|660cb06|ce5b5f0|670de9f|d5fc0eb|cfbb1dd|4c1323f|392c36b|456f6d7|314f794|f19f7cb|fa2385b|cd9da9f|e04f39b|82939fe|9200442/g
```

This included this value `5412984`, which was matched [here](https://github.com/material-foundation/material-color-utilities/blob/main/typescript/hct/hct_solver.ts#L115) in `@material` (a vendor module). This code was then mangled into the following string

```
19.290534eb4b6df56
```

Since this is an invalid integer, it produces a syntax error when the modules is parsed

**If the current behavior is a bug, please provide the steps to reproduce.**

Unfortunately a minimal example is different to produce as I can't consistently force / guess these identifiers

**What is the expected behavior?**

The RealContentHash replacement should not mangle code

**Other relevant information:**
webpack version:  `5.90.3`
Node.js version: `v20.11.1`
Operating System: `MacOS`
Additional tools: `none`

**Comment by issacgerges** [comment] 2024-05-08 00:00
it me. increasing the length of `[contenthash]` makes strings that are much less likely to collide.

**Comment by issacgerges** [comment] 2024-05-08 00:01
Can open a new request, but should webpack warn or enforce a minimum length of `cotnenthash` when `realContentHash` is enabled?

**Comment by alexander-akait** [comment] 2024-05-08 12:26
Duplicate of https://github.com/webpack/webpack/issues/14058 (https://github.com/webpack/webpack/issues/14058#issuecomment-951837186)

> it me. increasing the length of [contenthash] makes strings that are much less likely to collide.

Please use it if you have such problem, also you can disable realContentHash

> Can open a new request, but should webpack warn or enforce a minimum length of cotnenthash when realContentHash is enabled?

It is not an ideal solution, because numbers can be longer too

Anyway if you have ideas how we can improve it without increasing length, PR welcome

Feel free to feedback

**Closed by alexander-akait** 2024-05-08 12:26 UTC

**Comment by issacgerges** [comment] 2024-05-08 12:39
@alexander-akait when `realContentHash` is enabled can `webpack` instead use a non-truncated `contenthash` during its first pass (making collision near impossible) and then only truncate (if requested) during the replacement phase?

**Comment by alexander-akait** [comment] 2024-05-08 12:45
> Or maybe you could also include a needle like _WEBPACK_CONTENTHASH_{value}_ pre-replacement?

Yes, it is our idea to solve this problem in webpack 6, but it requires change logic in many plugins (and in vendor plugins), that is why we can't use this solution right now, but we still thinking how we can solve it more better. 

> in vendor plugins

Maybe plugins can generate somthing like `my-chunk.[hash].js` (for example in HTML file), so we need to search `[hash]`, I have idea how we can use both solution and make smoothy migration, but it requires better design and discussions
