### ISSUE TITLE
[node 0.11.x] TypeError: Expected a SourceNode, string, or an array ...

### ISSUE THREAD

**Issue by remoe** [webpack/webpack#549] opened 2014-10-23 10:19 UTC
Hi

I have this error:

```error
node_modules\webpack\node_modules\webpack-core\node_modules\source-map\lib\source-map\source-node.js:177
      throw new TypeError(
            ^
TypeError: Expected a SourceNode, string, or an array of SourceNodes and strings. Got /******/ (function(modules) { // webpackBootstrap

    at SourceNode_add [as add] (node_modules\webpack\node_modules\webpack-core\node_modules\source-map\lib\source-map\source-node.js:178:13)
    at Source.ConcatSource.add (node_modules\webpack\node_modules\webpack-core\lib\ConcatSource.js:22:14)
    at Source.<anonymous> (node_modules\webpack\node_modules\webpack-core\lib\ConcatSource.js:12:8)
    at Array.forEach (native)
    at Source.ConcatSource (node_modules\webpack\node_modules\webpack-core\lib\ConcatSource.js:11:40)
    at SetVarMainTemplatePlugin.<anonymous> (node_modules\webpack\lib\SetVarMainTemplatePlugin.js:23:11)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (node_modules\webpack\node_modules\tapable\lib\Tapable.js:37:47)
    at Tapable.MainTemplate.render (node_modules\webpack\lib\MainTemplate.js:112:20)
    at Tapable.createChunkAssets (node_modules\webpack\lib\Compilation.js:745:32)
    at Tapable.<anonymous> (node_modules\webpack\lib\Compilation.js:509:8)
```

I think i don't have installed multiple versions of source-map:

> npm ls source-map

```shell
├─┬ autoprefixer-loader@1.0.0
│ └─┬ autoprefixer-core@3.1.2
│   └─┬ postcss@2.2.5
│     └── source-map@0.1.40
├─┬ css-loader@0.9.0
│ └── source-map@0.1.40
├─┬ extract-text-webpack-plugin@0.3.3
│ └── source-map@0.1.40
├─┬ html-loader@0.2.3
│ └── source-map@0.1.40
├─┬ jade@1.7.0 extraneous
│ └─┬ transformers@2.1.0
│   └─┬ uglify-js@2.2.5
│     └── source-map@0.1.40
├─┬ rework-import@1.2.1
│ └─┬ css@2.1.0
│   └── source-map@0.1.40
├─┬ rework-loader@0.1.1
│ └─┬ rework@1.0.1
│   └─┬ css@2.1.0
│     └── source-map@0.1.40
└─┬ webpack@1.4.8 extraneous
  └─┬ webpack-core@0.4.8
    └── source-map@0.1.40
```

**Comment by shama** [comment] 2015-07-19 21:45
@remoe Is this still an issue with Node v0.12?

**Comment by remoe** [comment] 2015-07-19 21:56
I can't test it, because I no longer have this setup, sorry.

**Comment by shama** [comment] 2015-07-19 22:02
Thanks @remoe! Closing as I can't reproduce. If it happens again, please reopen.

**Closed by shama** 2015-07-19 22:02 UTC
