### ISSUE TITLE
Unexpected code after tree-shake

### ISSUE THREAD

**Issue by Birowsky** [webpack/webpack#6264] opened 2018-01-08 16:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Either a bug or unclear docs.

**What is the current behavior?**
Given `entry` is the entry module:
<img width="750" alt="screen shot 2018-01-08 at 17 19 34" src="https://user-images.githubusercontent.com/3199950/34681428-28df7576-f49c-11e7-942d-12caa6e905b8.png">

It just uses `function1` from `external1` module.

I expected that `external1.function2` and the whole `external2` module would be eliminated. 

However, my output includes `external2.function1`. Just.. why?

[Here's a repo](https://github.com/Birowsky/testing-typescript-treeshaking) of the whole thing.

**Comment by EugeneHlushko** [comment] 2018-01-14 15:35
While this might not be what you want, but i suggest trying webpack 4 which does not include that external2 thing.

**Comment by Birowsky** [comment] 2018-01-16 09:42
@EugeneHlushko tried compiling with:

```
    "webpack": "4.0.0-alpha.4",
    "webpack-cli": "2.0.4"
```

Got:

<img width="687" alt="screen shot 2018-01-16 at 10 41 43" src="https://user-images.githubusercontent.com/3199950/34982150-e132016c-faa9-11e7-8428-a3767f1bb505.png">

**Comment by sokra** [comment] 2018-01-16 13:01
This doesn't work yet. We don't do this kind of scope analysis yet, but this is prepared in some places and could be added.

**Comment by chengluyu** [comment] 2018-03-23 11:11
By using `ModuleConcatenationPlugin`, webpack does eliminate `external2` stuff correctly.

Here's output from webpack 4 with `ModuleConcatenationPlugin` and `UglifyJSPlugin`: [gist link](https://gist.github.com/chengluyu/ebded4db2ca38b3d570eb2c6d37b77dc).

**Comment by chengluyu** [comment] 2018-03-23 11:18
@Birowsky You really should try out webpack 4 and `ModuleConcatenationPlugin`

And don't forget to upgrade `ts-loader` to 4.x to avoid the error `Cannot read property 'ts' of undefined`.

**Comment by chengluyu** [comment] 2018-03-23 11:26
@sokra I think although there's no deep scope analysis strategy in webpack, by using `ModuleConcaatenationPlugin` and minifiers that supports dead code removal (e.g. `UglifyJSPlugin`), the same result can be achieved.

**Comment by Birowsky** [comment] 2018-03-24 08:31
@chengluyu hey mate, thanx for figuring it out. However, I don't see you using the `ModuleConcatenationPlugin` in [your fork](https://github.com/chengluyu/webpack-issue-6264/commit/b6029a52295179f3d2b68bb9106b5986e78371d5).

**Comment by chengluyu** [comment] 2018-03-24 08:40
@Birowsky I forgot to push the commit. Updated [here](https://github.com/chengluyu/webpack-issue-6264/blob/e46bf9271830b6ad2776f0cf9aeb2d01964c6a0d/webpack.config.js#L34).

**Comment by chengluyu** [comment] 2018-04-03 05:13
@Birowsky The `ModuleConcatenationPlugin` should make imported modules inline. But it didn't, that's a known limitation.

**Comment by tomkel** [comment] 2018-04-03 15:54
Well, this was on the roadmap for 4.x. But now that it's closed..

**Comment by Birowsky** [comment] 2018-04-03 15:57
@tomkel I can reopen it. Is there a reason tho?

**Comment by tomkel** [comment] 2018-04-03 16:57
I think this bug report captured the scope analysis you were looking for, for not including code that will not be used. Yes, it can be removed via dead code elimination, but we can get even smaller bundles ala rollup by implementing strict live code inclusion.

**Comment by vincentdchan** [comment] 2018-05-17 14:39
Hi, everyone. I am implementing this feature. Here's my repo:

[https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin](https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin)

And demo, you can experience the analysis:

[https://vincentdchan.github.io/webpack-deep-scope-demo/](https://vincentdchan.github.io/webpack-deep-scope-demo/)

If things go well, we can use it very soon. It will come faster if anyone can add more tests or edge cases to my repo. Thank you!

**Comment by Birowsky** [comment] 2018-05-21 18:00
Sorry, I won't be able to have a look into this for the next couple of weeks.

**Comment by dmwyatt** [comment] 2019-03-10 23:37
Did anything ever come of this?  Any plans to integrate @vincentdchan 's work?

**Comment by vincentdchan** [comment] 2019-03-11 03:53
@dmwyatt Thanks for following. My plugin has been released for a while, and I rarely receive bugs report. I don't know if it's really tested by the community even though I have a lot of unit tests. Because shaking wrong modules would make production code crash. I am worried.

@sokra Maybe I could submit a PR for integrating the plugin as an optional parameter, people can choose to use it.

**Comment by Birowsky** [comment] 2019-12-03 22:05
Don't you dare.

**Comment by jschmuecking** [comment] 2019-12-20 12:27
I'm not sure how relevant this is but when using your example repo the `production` mode achieves the elimination of external2 based on the optimizations. So for development this is reproducable with enabling the corresponding optimizations:
`optimization: {
    providedExports: true,
    usedExports: true,
    concatenateModules: true
  }`
Which actually results in the usage of beforementioned `ModuleConcatenationPlugin`.

Did I misunterstand something in your requirements, @Birowsky , or does this mean the problem is fixed in webpack 4?

**Comment by Birowsky** [comment] 2019-12-30 13:53
@jschmuecking, thanx for that. I can confirm that just by switching `mode` to `'production'` in the demo repo, the unused functions are being shaken off the emitted code, and that solves my original issue. 

However, extra quality work was being done by @vincentdchan, so I'd like you to chip in.

@tomkel, you too had some meaningful input. Please confirm that this is closable.

**Comment by fregante** [comment] 2020-04-12 15:41
A "Very Important" issue should not be marked "inactive"

**Comment by fregante** [comment] 2020-04-12 15:42
Good boy

**Comment by vankop** [comment] 2020-04-12 16:13
Work done in `webpack@5`. Provided example works with latest beta (`webpack@5.0.0-beta.14`).

I think this issue could be closed @evilebottnawi

**Closed** 2020-04-13 10:52 UTC
Labels: P2: Very Important, enhancement, webpack-4
