### ISSUE TITLE
TypeError: Cannot read property 'jsonData' of undefined

### ISSUE THREAD

**Issue by jkthinksmart** [webpack/webpack#13709] opened 2021-07-05 10:23 UTC
During app rebuild this error happens:

let data = module.buildInfo.jsonData;
TypeError: Cannot read property 'jsonData' of undefined

Webpack 5.42.0

**Comment by dnsnx** [comment] 2021-07-05 11:09
This bug is already mentioned here:

https://github.com/webpack/webpack/issues/13691

**Comment by dnsnx** [comment] 2021-07-05 11:11
Duplicate of #https://github.com/webpack/webpack/issues/13691

**Closed** 2021-07-05 11:36 UTC
