### ISSUE TITLE
WebPack - locks a file (read-only) during build time

### ISSUE THREAD

**Issue by andrey12432132** [webpack/webpack#10175] opened 2019-12-25 08:19 UTC
Hello!

I press ctrl + s the studio saves the file, and WebPack starts the assembly ...
I press ctrl + s a second time and the **studio does not allow to save the file**
since he is involved in the assembly.
instead the save as window appears ...
- this is the problem

**QUESTION:**
How in WebPack to disable file lock during build
so that you can always rewrite it.

(I have visual studio + task runner - but it doesn’t matter, it's in webpack)

```
"use strict";
var VueLoaderPlugin = require('vue-loader/lib/plugin');
module.exports = {
    mode: 'development',
    entry: './Scripts/entry.js',
    output: {
        path: `${__dirname}/Scripts`,
        publicPath: '/',
        filename: 'coms.js'
    },
    module: {
        rules: [
            {
                test: /\.(js|tsx?)$/,
                use: 'babel-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader',
            },
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { url: false } },
                    'postcss-loader',
                ],
            },
        ],
    },

};
```

**Comment by evilebottnawi** [comment] 2019-12-25 09:35
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions. Also we don't look files, we just read them

**Comment by evilebottnawi** [comment] 2020-03-25 12:19
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2020-03-25 12:19 UTC
