### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by igordata** [webpack/webpack#7212] opened 2018-05-06 14:41 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Uncatched error pops up if some resource is not found in array.

`try` block have no `catch` block, only finally. That leads to interruption of execution of webpack client-side script.

**If the current behavior is a bug, please provide the steps to reproduce.**
Honestly, I don't know how to reproduce it. I suppose it should not happen if build were correct. But I had this problem when build happened with no error, but some resources were missing in generated scripts.

I posted a simple example of same situation without webpack here https://github.com/webpack/webpack/issues/7212#issuecomment-387354884
Please check it out.

**What is the expected behavior?**
Execution of script continues after finally block.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 3.10 and as I see - should 4.7 have this problem too
node  v9.3.0
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Detailed description**

webpack/lib/MainTemplate.js have an issue leading to that error:
```
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (main-b872855452d328d9c1c2.js:formatted:110)
    at SomePage (Some.js:345)
    at beginWork (main-b872855452d328d9c1c2.js:formatted:7973)
    ...etc
```

It looks like some chunks are unavailable, but the problem is in `try` block. It doesn't work as expected:
```js
/******/ 		// Execute the module function
/******/ 		var threw = true;
/******/ 		try {
/******/ 			modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/ 			threw = false;
/******/ 		} finally {
/******/ 			if(threw) delete installedModules[moduleId];
/******/ 		}
```
It have no catch block, so it can't catch an error. That's why an error pops up and application crashes.

It looks like someone forgot to add catch block after try. Maybe because it would do nothing - an empty catch block looks useless. But it does important work - it catches an error.

**Solution**

To fix it one just need to edit webpack/lib/MainTemplate.js starting with line 189:
```diff
								"// Execute the module function",
								"var threw = true;",
								"try {",
								Template.indent([
									`modules[moduleId].call(module.exports, module, module.exports, ${this.renderRequireFunctionForModule(
										hash,
										chunk,
										"moduleId"
									)});`,
									"threw = false;"
								]),
+								"} catch (e) {",
								"} finally {",
								Template.indent([
									"if(threw) delete installedModules[moduleId];"
								]),
								"}"
```

or in v3.10 starting from line 69:
```diff
					"// Execute the module function",
					"var threw = true;",
					"try {",
					this.indent([
						`modules[moduleId].call(module.exports, module, module.exports, ${this.renderRequireFunctionForModule(hash, chunk, "moduleId")});`,
						"threw = false;"
					]),
+					"} catch (e) {",
					"} finally {",
					this.indent([
						"if(threw) delete installedModules[moduleId];"
					]),
					"}"
```

**Comment by igordata** [comment] 2018-05-06 16:42
Updated description. Problem persists in 4.7 https://github.com/webpack/webpack/blob/v4.7.0/lib/MainTemplate.js#L200

**Comment by ooflorent** [comment] 2018-05-08 06:54
The lack of `catch` block is intentional. If you need to catch the error you must wrap your `require` call by `try/catch`.

**Comment by igordata** [comment] 2018-05-08 10:14
Without `catch` block an error breaks through

**Examples**

withCatch.js
```js
let a = [];

console.log('Start');
try {
    a.call();
} catch (e) {
} finally {
    console.log ('Finally executed');
}
console.log('Successful end');
```
output
```
$ node withCatch.js
Start
Finally executed
Successful end
```

withoutCatch.js
```js
let a = [];

console.log('Start');
try {
    a.call();
} finally {
    console.log ('Finally executed');
}
console.log('Successful end');
````

output

```
$ node withoutCatch.js
Start
Finally executed
C:\Users\igors\Desktop\дока\withoutCatch.js:5
  a.call();
    ^

TypeError: a.call is not a function
    at Object.<anonymous> (C:\Users\igors\Desktop\дока\withoutCatch.js:5:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

The second example ends up with an error and no "Successful end" in output.

**Comment by igordata** [comment] 2018-05-08 13:42
Finally I updated description according template. :D

**Comment by Dinfyru** [comment] 2018-05-08 14:50
+1

**Comment by ooflorent** [comment] 2018-05-08 17:45
@igordata What I am saying is that it is intended that the error is not catch:

- **we want** the exception to be thrown
- **we don't want** the exception to be catch by webpack

If you need to catch it, use a `try/catch` block:

```js
try {
  dep = require("something-missing")
} catch (e) {
  // 
}
```

**Comment by igordata** [comment] 2018-05-08 17:48
Why then do you have this `try` and `finally` blocks and variable `threw` and check of that variable? o_O

**Comment by ooflorent** [comment] 2018-05-08 18:10
Because `finally` is required to de-reference the module if the `require` call failed.
Considering the following file:

```js
// silly.js
// NOTE: I admit, this is silly
let luckToken = Math.random()
if (luckToken < .5) throw new Error()
module.exports = luckToken
```

And this one:

```js
let token
let attempt = 0
while (!token) {
  try {
    attempt++
    token = require("./silly")
  } catch (e) {
    // not this time
    console.log(`${attempt}: failed to get the luck token`)
  }
}
```

Thanks to the `finally` statement, webpack forgets about `silly.js` and will try to evaluate this module until it succeeds.

The above example is really naive but we could imagine something more real:

- my app uses a custom profiler that is heavy to load so it needs to be lazy-loaded when needed
- the profiler must be decorated before used

```js
try {
  // Try to decorate the profiler if it is already loaded
  require("./enhance-profiler")
} catch (e) {
  // Looks like it was not…
  require("custom-profiler")(/* some options */)
  require("./enhance-profiler")
}
```

**Comment by igordata** [comment] 2018-05-08 19:49
OK, got it.

The problem is I have no optional dependencies and I don't know what makes this error to appear.
And if I add this `catch` block - everything works fine and I don't see any missing resources. =(

Maybe that's an issue of next.js, or just chunks are assembled in a wrong way...

**Comment by ooflorent** [comment] 2018-05-09 06:42
I'm closing this issue for now. Please open a new one with an example to reproduce the error if the problem is still there.

**Closed by ooflorent** 2018-05-09 06:42 UTC

**Comment by JohanBeumer** [comment] 2019-06-12 04:19
Can you please take a look at my question on [StackOverflow]( https://stackoverflow.com/questions/56540461/how-to-configure-terserplugin-to-not-mangle-classnames)? The error I get is the same as described above, but I can't tell if it's related. The issue can be reproduces using this [repo](https://bitbucket.org/JohanBeumer/angular-ivy-aot/src/master/).

**Comment by Jaynam07** [comment] 2020-03-04 10:23
Uncaught TypeError: Cannot read property 'call' of undefined
    at d (runtime.js:1)
    at Module.<anonymous> (app.js:1)
    at Module.<anonymous> (app.js:1)
    at d (runtime.js:1)
    at Object.<anonymous> (app.js:1)
    at d (runtime.js:1)
    at r (runtime.js:1)
    at Array.n [as push] (runtime.js:1)
    at app.js:1

Browser - Chrome
Nuxt version - nuxt@2.11.0
Webpack version - webpack@4.41.6
