### ISSUE TITLE
Webpack compilation ignores source change

### ISSUE THREAD

**Issue by burnall** [webpack/webpack#3137] opened 2016-10-14 11:56 UTC
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
I use Webpack + Gulp with build-watch style explained [here](https://webpack.github.io/docs/usage-with-gulp.html) (mode 2). Occasionally, Webpack ignores the change of JS source and bundle contains a code version before the change. Gulp script is very simple and there is only one js file to bundle.

``` javascript
gulp.task("webpack:build-dev", function(callback) {
   // run webpack
   devCompiler.run(function(err, stats) {
       // Handle error
       callback();
   });
});
```

After changing of app/mmm/index.js, the bundle should reflect the change. It does not happen first time then it is working fine. I started from real-life project, and here the pattern was different: 1st, 3rd, 5th etc change was ignored. 

**Expected/desired behavior:**
Bundles should be updated after every change.

Complete example is on [Github](https://github.com/burnall/webpack-with-common-libs). 
See [gulpfile.js](https://github.com/burnall/webpack-with-common-libs/blob/master/gulpfile.js)

**Comment by burnall** [comment] 2016-10-24 14:33
Hey,
@bebraw Is there a way how can I speed up the investigation?
Please let me know, I'll gladly provide more details or tests cases if needed.

**Comment by bebraw** [comment] 2016-10-24 14:39
@burnall Can you try upgrading to webpack 2 and see if the issue is there too? That's where the current focus of development is right now.

**Comment by burnall** [comment] 2016-10-24 14:53
@bebraw The distilled example above is working fine with 2.1.0-beta.25.  
I can't check whether it is fixing all other similar issues I had in the big project, since first the configuration needs to be converted to the new format. 
Do you know dates for Webpack 2.0 release?

**Comment by bebraw** [comment] 2016-10-24 15:26
@burnall Based on #1545 I would say sometime this year. The final release will be announced week before.

I understand it's big change. I don't think we'll be back-porting fixes to webpack 1, though, given how far apart the two versions are.

**Comment by burnall** [comment] 2016-11-01 09:20
After upgrade to Webpack 2 beta, I can confirm that all similar issues are gone.

**Comment by bebraw** [comment] 2016-11-01 09:41
Ok, cool. Closing.

**Closed by bebraw** 2016-11-01 09:41 UTC
Labels: bug, P3: Important, S4: Broken, X3: discussion required
