### ISSUE TITLE
4.29.3 breaks import()

### ISSUE THREAD

**Issue by 1attice** [webpack/webpack#8755] opened 2019-02-07 22:48 UTC
# Bug report

**What is the current behavior?**

When I upgrade Webpack from 4.29.2 to 4.29.3, import() breaks.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using a relatively straightforward, up-to-date package.json, code that formerly worked using import() stops building after upgrading from 4.29.2 to 4.29.3. The error message is, e.g:

```
ERROR in ./js/registry.js 22:44
Module parse failed: Unexpected token (22:44)
You may need an appropriate loader to handle this file type.
```

Downgrading to the previous version eliminates this error. 

In other words, the bug has been easy for me to reproduce/ toggle on/off since I isolated the package version bump which introduced it. (I can induce the bug by `rm -rf node_modules/*; npm install` after upgrading my `package.json` and just as easily quell it again by the same operation after downgrading the webpack requirement in `package.json` back down to 4.29.2.)

Apologies, I have not yet had time to come up with a minimal example, but here are my config files. 

package.json: https://gist.github.com/1attice/dde6cd694fcb5202ebb78497772417b5
webpack.config.js: https://gist.github.com/1attice/1eef81fbd36ab67b9bd26600bf320e5b
.babelrc: https://gist.github.com/1attice/906515f7386b5c36d03dcb420872cb04

And here is the code that occasions the error:
registry.js: https://gist.github.com/1attice/bb922e8e3d155db53ad1942de7ccd31c

**What is the expected behavior?**

Compilation should proceed normally, as under 4.29.2.

webpack version: 4.29.3  
Node.js version: 10.14.1
Operating System: MacOS 10.14.2
Additional tools: see package.json

**Comment by 1attice** [comment] 2019-02-08 00:49
I tried to replicate the bug in a minimal version (screw you, KPIs!) Fascinatingly, I could not. 

Meanwhile, back in my main repo, I can still induce/eliminate the bug by bumping up and down from 4.29.3 and 4.29.2 respectively. 

Here's the repo that **does not** replicate the bug: https://github.com/1attice/webpack-import-bug.git

A couple of theories, to assess & eliminate after I've done my actual job for today:

- The problem may only show up in dev server mode. 
- There may be an interaction between babel plugins that induces this state.
- The bug may only affect .jsx files for some reason? (I'm reaching, here.)

If anyone else wants to help out, I'd be most appreciative <3 This bug took a while to track down (I had to play pare-the-possibilities after running `npm-check-updates -a`) so I'm committed to its elimination.

**Comment by sokra** [comment] 2019-02-08 07:57
Duplicate of #8656

**Comment by sokra** [comment] 2019-02-08 08:00
Maybe it's mot the same...

**Comment by sokra** [comment] 2019-02-08 08:02
Could you run with `--display-error-details` to get a stack trace

**Comment by 7Pass** [comment] 2019-02-12 13:35
I think this is the same as #8656. I had the same issue and use the workaround suggested by @devCrossNet fixes it:
https://github.com/webpack/webpack/issues/8656#issuecomment-456153381
> downgrade to `"webpack": "4.28.4"` in your projects package.json also works for now. Just did that a couple of hours ago.

**Comment by JoshRobertson** [comment] 2019-02-19 17:17
If you don't control the Webpack version (for projects like Webpacker), you can potentially solve this with yarn resolutions in your `package.json`. This will prevent yarn from upgrading to 4.29.3 (which indeed breaks as stated in the OP).

Specifically for a Webpacker 4.0 related instance, this solve's the issue:
```
  "resolutions": {
    "@rails/webpacker/webpack": "4.29.2",
    "webpack/acorn": "6.0.5"
  },
```

**Comment by idangozlan** [comment] 2019-04-12 00:26
anything new?

**Comment by evilebottnawi** [comment] 2019-04-12 00:29
Acorn problem, just add `acorn: <latest>` in you package.json

**Comment by evilebottnawi** [comment] 2019-04-12 00:29
Close in favor https://github.com/webpack/webpack/issues/8656

npm still not fix problem, it is shame

**Closed by evilebottnawi** 2019-04-12 00:29 UTC
