### ISSUE TITLE
Broken subsequent builds when watching with DedupePlugin

### ISSUE THREAD

**Issue by matthewwithanm** [webpack/webpack#583] opened 2014-11-13 21:52 UTC
When we use the DedupePlugin in combination with `watch()`, the initial build will be fine. However, any subsequent builds are broken, throwing the following error on [this line](https://github.com/webpack/webpack/blob/d94706ed028b3b1a3b1231771c809e313e16a779/lib/optimize/DedupePlugin.js#L201):

`Uncaught TypeError: Cannot read property 'apply' of undefined`

To be clear, this is an error thrown by the inserted code in the built file at run time—not by webpack at build time.

**Comment by shama** [comment] 2015-07-19 21:50
@matthewwithanm Are you still experiencing this issue?

**Comment by adjavaherian** [comment] 2015-10-06 01:19
I just started seeing this today.  Hmm.  What should I try?

**Comment by shama** [comment] 2015-10-06 02:29
@adjavaherian Are you able to post a stack trace? Or even better an example that reproduces the error?

**Comment by adjavaherian** [comment] 2015-10-06 07:08
Thanks, @shama  here's a stack. 

```javascript
Uncaught TypeError: Cannot read property 'apply' of undefined(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:149__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ index.js?cf14:1(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:2251__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ PathUtils.js?952e:5(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:807__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ Route.js?d94e:10(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:417__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ PropTypes.js?4c46:5(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:321__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ DefaultRoute.js?68d8:7(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:1191__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ index.js?e07d:3(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:303__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ app.js?86a9:2(anonymous function) @ app.js?86a9:14(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:165__webpack_require__ @ app.bundle.f0b311f75a8b0a8034f3.js:69(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:112(anonymous function) @ app.bundle.f0b311f75a8b0a8034f3.js:115
```

app builds fine, watches and I think loses module cache after rebuild.  my example is pretty complex, not sure what changed today that caused this, but here's my config, anyway. 

```javascript
//webpack.config.js
//main webpack config
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');
var CachePlugin = require('webpack/lib/CachePlugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var NyanProgressPlugin = require('nyan-progress-webpack-plugin');
var ProgressPlugin = require('./webpack-utils/progress-plugin');
var RewirePlugin = require('rewire-webpack');
var StatsPlugin = require('stats-webpack-plugin');
var DeepMerge = require('deep-merge');
var myCache = {};

var deepmerge = DeepMerge(function(target, source, key) {
    if(target instanceof Array) {
        return [].concat(target, source);
    }
    return source;
});

function config(overrides) {
    return deepmerge(defaults, overrides || {});
}

//require common.js for node_modules (better for server)
var node_modules = fs.readdirSync('node_modules').filter(function(x) { return x !== '.bin' });
function node_externals(context, request, cb) {
    if(node_modules.indexOf(request) !== -1) {
        cb(null, 'commonjs ' + request);
        return;
    }
    cb();
}

//require common.js for configs, manifests that might change
var dist_dir  = fs.readdirSync(path.join(__dirname, 'public', 'dist')).filter(function(x) {
    if (x.indexOf('.json') > -1) {
        return x
    }
});

var config_modules  = ['states-json.json'].concat(dist_dir);

function config_externals(context, request, cb) {
    var clean_request = request.split('/').splice(-1)[0];
    if (config_modules.indexOf(clean_request) !== -1) {
        cb(null, 'commonjs ' + request);
        return;
    }
    cb();
}

var client = {
    name: 'client side webpack',
    target: 'web',
    entry: {
        analytics: path.join(__dirname, 'app/analytics'),
        //vendor: ['react-tools', 'react-helmet', 'promise', 'numeral', 'lodash', 'google-maps'],
        rehydrate: path.join(__dirname, 'app/rehydrate'),
        app: path.join(__dirname, 'app/app')
    },
    output: {
        path: path.join(__dirname, 'public/dist'),
        publicPath: '/dist/',
        filename: '[name].bundle.[hash].js',
        chunkFilename: '[id].chunk.[chunkhash].js'
    },
    resolveLoader: {
        alias: {
            'lift-sass': 'passthru-loader'
        }
    },
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css!sass')
            }
            , {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'manifest-loader'
                ]
            }
        ]
    },
    plugins: [
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.OccurenceOrderPlugin(true),
        new ExtractTextPlugin('style.[name].[chunkhash].css', {
            disable: false,
            allChunks: true // extract all css from async chunks as well
        }),
        new webpack.DefinePlugin({
            __CLIENT__: true,
            __SERVER__: false
        }),
        new StatsPlugin(path.join(__dirname, 'public', 'dist', 'webpack-assets.json'), {
            assetsByChunkName: true,
            source: false,
            reasons: false,
            modules: false,
            chunks: false
        })
    ]
};

var server = {
    name: 'server side webpack',
    target: 'node',
    devtool: 'source-map',
    entry: {
        index: path.join(__dirname, 'index.js')
    },
    output: {
        libraryTarget: 'commonjs2',
        path: path.join(__dirname, 'server', 'dist'),
        filename: '[name].js'
    },
    resolveLoader: {
        alias: {
            'react-router-proxy$': path.join(__dirname, 'webpack-utils', 'passthru-loader'),
            'lift-sass':  'sass-lifter-loader' + lifterParams
        }
    },
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: 'noop-loader'
            }
            , {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'manifest-loader'
                ]
            }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            __CLIENT__: false,
            __SERVER__: true
        }),
        new webpack.BannerPlugin('require("source-map-support").install();',
            { raw: true, entryOnly: false })
    ],
    externals: [{ 'react/addons' : true, 'newrelic' : true }, node_externals, config_externals]
};


var defaults = {
    context: __dirname,
    node: {
        __dirname: true,
        __filename: true,
        fs: 'empty',
        tls: 'empty',
        net: 'empty',
        console: true
    },
    devtool: '#eval-source-map',
    externals: [/^config[a-z\-0-9]+$/],
    resolve: {
        root: path.join(__dirname),
        fallback: path.join(__dirname, 'node_modules'),
        modulesDirectories: ['app', 'images', 'node_modules'],
        extensions: ['', '.json', '.js', '.jsx', '.scss', '.png', '.jpg', '.jpeg', '.gif']
    },
    plugins: [
        new ProgressPlugin(),
        new CachePlugin(myCache),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.NormalModuleReplacementPlugin(/fastclick$/i, 'node-noop')
    ],
    resolveLoader: {
        root: __dirname,
        fallback: __dirname + '/node_modules',
        alias: {
            'noop-loader': path.join(__dirname,  'webpack-utils', 'noop-loader'),
            'manifest-loader': path.join(__dirname, 'webpack-utils', 'manifest-loader') + manifestParams,
            'passthru-loader': path.join(__dirname, 'webpack-utils', 'passthru-loader')
        }
    },
    module: {
        // Disable handling of unknown requires and requires with a single expression
        unknownContextRegExp: /$^/,
        exprContextRegExp: /$^/,
        unknownContextCritical: false,
        exprContextCritical: false,
        loaders: [
            {
                test: /\.json$/,
                loaders: ['json-loader']
            }
            , {
                test: /\.jsx$/,
                loader: 'babel',
                query: {
                    optional: ['es7.classProperties']
                }
            }
        ]
    },
    bail: true,
    cache: true,
    debug: true
};

module.exports = [config(client), config(server)];
```

Thanks.

**Comment by adjavaherian** [comment] 2015-10-06 16:48
FWIW, It looks like it might be an index out of bounds error.  The function at `modules[_m[0]]` doesn't seem to be valid, but only for the last module in my bundle.  Which appears to be part of "request"

`~/request/~/form-data/~/combined-stream/lib/combined_stream.js?c0d9"],"names":`

```javascript
function(modules) {
	// Check all modules for deduplicated modules
	for(var i in modules) {
		if(Object.prototype.hasOwnProperty.call(modules, i)) {
			switch(typeof modules[i]) {
			case "function": break;
			case "object":
				// Module can be created from a template
				modules[i] = (function(_m) {
					var args = _m.slice(1), fn = modules[_m[0]];
					return function (a,b,c) {
						fn.apply(this, [a,b,c].concat(args));
					};
				}(modules[i]));
				break;
			default:
				// Module is a copy of another module
				modules[i] = modules[modules[i]];
				break;
			}
		}
	}
	return modules;
}
```

**Comment by syko** [comment] 2015-10-18 07:20
Same here. Works with no dedupe plugin.

**Comment by moekhalil** [comment] 2015-10-30 18:37
+1

**Comment by moekhalil** [comment] 2015-10-30 18:38
:+1:

**Comment by cchamberlain** [comment] 2015-12-02 02:30
Same.

**Comment by dharness** [comment] 2016-01-04 01:28
I am having this issue, but I haven't explicitly included DedupePlugin. Is there a way to confirm this is the issue and/or remove DedupePlugin?


``
var webpack = require('webpack'),
    path = require('path');

var APP = __dirname + '/app';

module.exports = {
    context: APP,
    entry: ['./core/bootstrap.js'],
    output: {
        path: APP,
        filename: 'beamer.bundle.js',
    },
    devtool: 'sourcemap',
    module: {
        loaders: [{
            test: /\.scss$/,
            loader: 'style!css!sass'
        }, {
            test: /\.(png|jpg)$/,
            loader: 'url?limit=25000'
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "url-loader?limit=10000&minetype=application/font-woff"
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "file-loader"
        }]
    }
};

``

**Comment by cameron** [comment] 2016-02-08 22:45
Same issue w/ `CommonsChunkPlugin`, resolved by removing it.

**Comment by srahulprdxn** [comment] 2016-05-03 06:21
I am having the same issue with dedupe plugin.

vendors.js:1Uncaught TypeError: Cannot read property 'apply' of undefined

I am getting the above show error.

var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var path = require('path');
var VendorChunkPlugin = require('webpack-vendor-chunk-plugin');

module.exports = {
  'devtool': 'eval-source-map',

  'entry': {
    'vendor': [
      'react',
      'react-dom',
      'react-router',
      'react-redux',
      'redux-thunk',
      'react-bootstrap',
      'redux',
      'redux-form',
      'axios'
    ],
    'app':  __dirname + '/src/main.js'
  },
  'output': {
    'path': __dirname + '/build',
    'publicPath': '/',
    'chunkFilename': '[id].[name].chunk.js',
    'filename': '[name].[hash].js'
  },

  'module': {
    'loaders': [
      // JSX and JS transpilation using babel
      {
        'test': [/\.js$/, /\.jsx$/],
        'exclude': /(node_modules|bower_components)/,
        'loader': 'babel'
      },
      // SASS modularization using style, css and postcss sass loader
      {
        'test': [/\.css$/, /\.scss$/],
        'loader': 'style!css!sass'
      },
      // Font path loader
      {
        'test': /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        'loader': 'file-loader?name=fonts/[name].[ext]'
      },
      // Image path loader
      {
        'test': /\.(jpe?g|png|gif|svg)$/i,
        'loaders': [
          'url-loader?limit=15000&name=images/[name].[ext]',
          'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
        ]
      }
    ],
  },

  'sassLoader': {
    'includePaths': [
      path.resolve(__dirname, 'src/components/'),
      path.resolve(__dirname, 'src/components/common/assets/')
    ]
  },

  'resolve': {
    'root': [
      path.resolve(__dirname, 'src'),
      path.resolve(__dirname, 'src/components/common/assets/'),
      path.resolve(__dirname, 'src/components/common/'),
      path.resolve(__dirname, 'node_modules')
    ],
    'extensions': ['', '.js', '.jsx', '.scss'],
  },

  'plugins': [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.BannerPlugin("App has been developed by PRDXN."),
    new HtmlWebpackPlugin({
      'template': __dirname + '/src/index.tmpl.html'
    }),
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendors.js', Infinity),
    new VendorChunkPlugin('vendor'),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      'minimize': true,
      'screw-ie8': true,
      'mangle': false,
      'compress': {
        'warnings': false
      },
      'output': {
        'comments': false,
        'semicolons': true,
      }
    }),
    new webpack.optimize.DedupePlugin()
  ],

  'devServer': {
    'contentBase': './build',
    'host': '0.0.0.0',
    'https': true,
    'colors': true,
    'compress': true,
    'hot': true,
    'historyApiFallback': true,
    'inline': true,
    // Display only errors to reduce the amount of output.
    'stats': 'errors-only',
  }
};

**Comment by insin** [comment] 2016-08-04 02:53
I just got this, and it was solved by dropping `DedupePlugin`.

Switching to using the `NamedModulesPlugin`  helped understand what was going on.

This is what's produced without `DedupePlugin`:

```
/***/ "./src/App.css":
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },

//...

/***/ "./src/index.css":
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },
```

And with DedupePlugin:

```
/***/ "./src/App.css":
"./src/index.css",

// ...

/***/ "./src/index.css":
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin

/***/ },
```

The resulting error happens inside `__webpack_require__`, which is trying to do this:

```
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

Should __webpack_require__ check if the given moduleId resolves to a string instead ofa function and require the other module it points to instead?

**Comment by bebraw** [comment] 2016-12-24 07:28
There's no `DedupePlugin` issue in webpack 2 anymore. Time to close.

**Closed by bebraw** 2016-12-24 07:28 UTC
Labels: bug
