### ISSUE TITLE
BUG(CLI): Incorrect simpleType for watch-options-poll

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack#11129] opened 2020-07-07 10:30 UTC
# Bug report
`watch-options-poll` can accept only `number` or `boolean` values. But it's `simpleType` is defined as `string`.

**What is the current behavior?**
https://github.com/webpack/webpack/blob/e3efb7b46cc45d97622cbb6a3b8fda3f21143829/test/__snapshots__/Cli.test.js.snap#L4365-L4383

![Screenshot at 2020-07-07 11-27-03](https://user-images.githubusercontent.com/46647141/86768152-b42aed80-c06a-11ea-92a3-1fdb47beb458.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

`webpack --watch-options-poll`

**What is the expected behavior?**

it's simpleType should be number. `simpleType: 'number'`.

**Other relevant information:**
webpack version:  webpack@next
Node.js version: 
Operating System: Any
Additional tools:

**Comment by evilebottnawi** [comment] 2020-07-07 10:58
Feel free to send a fix :+1:

**Comment by snitin315** [comment] 2020-07-07 11:11
Looking into it.

**Comment by sokra** [comment] 2020-07-07 14:41
The merged type of `number` and `boolean` is `string`. Numbers can be 1, 2, 3, etc. Booleans can be `true` `false`. You need a string to hold any of them.

**Comment by sokra** [comment] 2020-07-07 14:44
I think the problem is here:

https://github.com/webpack/webpack/blob/20ba3c07803a3fd580755937016f0d5c85c1ccd3/lib/cli.js#L534-L537

It should be 

``` diff
-if (!isNaN(n)) return value;
+if (!isNaN(n)) return n;
```

**Comment by snitin315** [comment] 2020-07-07 14:47
I will check if that works.

**Comment by snitin315** [comment] 2020-07-07 15:11
Actually on cli side we are defining types for flags based on `simpleType` , to parse them with commander.js
```js
        if (meta.simpleType === 'string') {
              meta.type = String;
              meta.usage = `--${flag} <value>`;
          } else if (meta.simpleType === 'number') {
              meta.type = Number;
              meta.usage = `--${flag} <value>`;
          } else {
              meta.type = Boolean;
              meta.negative = true;
              meta.usage = `--${flag}`;
         }
    }
```

**Comment by snitin315** [comment] 2020-07-07 15:21
> I will check if that works.

Working now. I will send a PR.

**Closed** 2020-07-09 07:14 UTC
