### ISSUE TITLE
Build for productions with module federation cause white blank without error

### ISSUE THREAD

**Issue by schirrel** [webpack/webpack#14130] opened 2021-09-03 12:14 UTC
# Bug report

I am trying to make a shared file, such as context/redux/vuex (i am using vue) but after build i got only a white page, no errors. I thought it was some sort of vuex problem, so i decide to try it as a simple file exporting a object with a function, just it. I've used bi-directional and shared-routing as example to follow, the second because of the video you've done.

The strange is that when running at dev, yarn serve works as it should, when running build and start, it presents a sample white page, no error, no clue, nothing, all files right requestes but nothing is rendered.

**What is the current behavior?**

A white blank page with no error or warning, even in the build i got no errors, everything works as it should, only when opening the page that nothing is rendered.
Using dev server works perfectly 

**If the current behavior is a bug, please provide the steps to reproduce.**

- Clone [project](https://github.com/schirrel/module-federation-examples/tree/vue-shared-strang-behavior/vue-cli) and install dependencies
- run project with (npm run || yarn) serve
- see that the project works well
- run project with (npm run || yarn) start (runs build and start project with http-server)
- see that the project becames a white blank page without any error on build neither on page access

**What is the expected behavior?**
After build the page render as the same as when using dev server

**Other relevant information:**
webpack version:  5.35.1
Node.js version:  14.16.0 
Operating System:     OS: macOS 11.5

Environment Info:
  System:
    OS: macOS 11.5
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Not Found
    Firefox: 91.0.2
    Safari: 14.1.2

Issue at module federation : https://github.com/module-federation/module-federation-examples/issues/950
issue at vue-cli: https://github.com/vuejs/vue-cli/issues/6670

**Comment by alexander-akait** [comment] 2021-09-03 12:24
What is dev server version?

**Comment by schirrel** [comment] 2021-09-03 12:29
@alexander-akait is the built in
my deps are only 
```
  "dependencies": {
    "core-js": "^3.6.5",
    "http-server": "^0.12.3",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "5.0.0-beta.2",
    "@vue/cli-plugin-eslint": "4.5.13",
    "@vue/cli-service": "5.0.0-beta.2",
    "babel-eslint": "10.1.0",
    "eslint": "7.30.0",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "2.6.14",
    "webpack": "^5.35.1"
  },
```

And at my webpack.config i only have
```
 devServer: {
    port: 9000,
  },
```

**Comment by alexander-akait** [comment] 2021-09-03 12:32
Please run `npm ls webpack-dev-server`, you need webpack-dev-server v4

**Comment by schirrel** [comment] 2021-09-03 12:34
@alexander-akait before do that, i just want to clarify that at **dev server** it works, only cause the strange behavior after build.

**Comment by alexander-akait** [comment] 2021-09-03 12:44
webpack-dev-server v3 has bug with library, please check webpack-dev-server v4

**Comment by schirrel** [comment] 2021-09-03 13:00
thanks @alexander-akait, i recieve the following from the command:
> ➜  vue-cli git:(vue-shared-strang-behavior) ✗ npm ls webpack-dev-server
/Users/alanschio/Projects/module-federation/module-federation-examples/vue-cli
└── (empty)

**Comment by alexander-akait** [comment] 2021-09-03 13:04
I think you need to open an issue in `vue-cli`, I can't reproduce the problem with pure setup

**Comment by schirrel** [comment] 2021-09-03 13:06
@alexander-akait i've done, thanks. I had open on both because i know the vue-cli uses webpack under de hood, as @ScriptedAlchemy mentioned at [the issue at mf examples](https://github.com/module-federation/module-federation-examples/issues/950)

**Comment by schirrel** [comment] 2021-09-03 13:28
Thank @alexander-akait 🙏 🚀 ❤️

**Comment by vankop** [comment] 2021-11-24 15:35
@alexander-akait should we close this?

**Comment by alexander-akait** [comment] 2021-11-24 15:37
Yep, we can't solve it here

**Closed by alexander-akait** 2021-11-24 15:37 UTC
Labels: question, webpack-5, module-federation
