### ISSUE TITLE
Webpack issues in splitchunk with setup of micro front end (using ESI)

### ISSUE THREAD

**Issue by pgangwani** [webpack/webpack#11355] opened 2020-08-20 15:48 UTC
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment] 2020-08-20 16:01
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Closed by evilebottnawi** 2020-08-20 16:01 UTC

**Comment by pgangwani** [comment] 2020-08-20 16:30
@sokra @ScriptedAlchemy : Please help till we migrate to module federation (webpack 5)

**Comment by evilebottnawi** [comment] 2020-08-20 16:33
@pgangwani please open an issue in https://github.com/webpack/webpack/issues/10352 for helping

**Comment by pgangwani** [comment] 2020-08-20 16:35
> @pgangwani please write an issue in #10352 for helping

@evilebottnawi : This issue is not related module federation. Its for webpack4 using external & splitchunks

**Comment by pgangwani** [comment] 2020-08-20 16:39
> > @pgangwani please write an issue in #10352 for helping
> 
> @evilebottnawi : This issue is not related module federation. Its for webpack4 using external & splitchunks

give me 5, I think updates didnt happen on issue due to n/w glitch

**Comment by pgangwani** [comment] 2020-08-20 16:51
> > > @pgangwani please write an issue in #10352 for helping
> > 
> > 
> > @evilebottnawi : This issue is not related module federation. Its for webpack4 using external & splitchunks
> 
> give me 5, I think updates didnt happen on issue due to n/w glitch

Updated long description (which was lost due to n/w glitch ) again. PLease review

**Comment by evilebottnawi** [comment] 2020-08-20 16:55
It is application error:

> vendors.b76597ee.chunk.js:formatted:1476 Uncaught TypeError: c.call is not a function at Function.<anonymous> (vendors.b76597ee.chunk.js:formatted:1476)

Maybe something wrong with your code, will be great if you will create reproducible test repo

**Comment by pgangwani** [comment] 2020-08-20 17:35
> It is application error:
> 
> > vendors.b76597ee.chunk.js:formatted:1476 Uncaught TypeError: c.call is not a function at Function. (vendors.b76597ee.chunk.js:formatted:1476)
> 
> Maybe something wrong with your code, will be great if you will create reproducible test repo

Do you need both webpack configs ?

**Comment by ScriptedAlchemy** [comment] 2020-08-21 06:58
I know what this is likely caused by. Bump this thread if I don't respond tomorrow

**Comment by pgangwani** [comment] 2020-08-21 07:10
> I know what this is likely caused by. Bump this thread if I don't respond tomorrow

Sure @ScriptedAlchemy. I know webpack 5 module federation is way to go in future but currently, I am blocked to use common chunks (using split chunks) & loadable when the esi build is umd with external deps of vendors (react, react-dom etc). If you have any esi setup for micro front ends test, we can utilize as and when required.

**Comment by pgangwani** [comment] 2020-08-21 07:24
@evilebottnawi : Would you meanwhile change the status of the issue to "Open"?

**Comment by pgangwani** [comment] 2020-08-24 16:43
@ScriptedAlchemy : Current setup is in production till I tried below 2 things:
1. I used splitchunk common vendor for header & footer entry (non externalized common chunks)
2. I wrapped loadable component for few component, 

then boom broke ..

I tried putting optimization.runtimeChunk as 
```
runtimeChunk: {
 name: 'globalShared'
},
``` 
it accidentally fixed 1st (trying to understand how) but still getting below error for 2nd  and experience is like header fragment disappears (breaks rendering)
```
TypeError: Cannot read property 'call' of undefined
    at u (VM2848 globalShared.ef3d5849.js:formatted:38)
a.<computed> @ VM2778:1
el @ VM2793 react.0c138dfa.chunk.js:2
n.payload @ VM2793 react.0c138dfa.chunk.js:2
fi @ VM2793 react.0c138dfa.chunk.js:2
Da @ VM2793 react.0c138dfa.chunk.js:2
yl @ VM2793 react.0c138dfa.chunk.js:2
cu @ VM2793 react.0c138dfa.chunk.js:2
lu @ VM2793 react.0c138dfa.chunk.js:2
Jl @ VM2793 react.0c138dfa.chunk.js:2
(anonymous) @ VM2793 react.0c138dfa.chunk.js:2
e.unstable_runWithPriority @ VM2797 vendors.a288997f.chunk.js:2
Vo @ VM2793 react.0c138dfa.chunk.js:2
Ko @ VM2793 react.0c138dfa.chunk.js:2
Wo @ VM2793 react.0c138dfa.chunk.js:2
Ql @ VM2793 react.0c138dfa.chunk.js:2
enqueueSetState @ VM2793 react.0c138dfa.chunk.js:2
T.setState @ VM2793 react.0c138dfa.chunk.js:2
v.safeSetState @ VM2849 global_vendors.98dda868.chunk.js:2
(anonymous) @ VM2849 global_vendors.98dda868.chunk.js:2
Promise.catch (async)
v.loadAsync @ VM2849 global_vendors.98dda868.chunk.js:2
v.componentDidMount @ VM2849 global_vendors.98dda868.chunk.js:2
il @ VM2793 react.0c138dfa.chunk.js:2
pu @ VM2793 react.0c138dfa.chunk.js:2
e.unstable_runWithPriority @ VM2797 vendors.a288997f.chunk.js:2
Vo @ VM2793 react.0c138dfa.chunk.js:2
du @ VM2793 react.0c138dfa.chunk.js:2
Jl @ VM2793 react.0c138dfa.chunk.js:2
Ql @ VM2793 react.0c138dfa.chunk.js:2
ju @ VM2793 react.0c138dfa.chunk.js:2
(anonymous) @ VM2793 react.0c138dfa.chunk.js:2
tu @ VM2793 react.0c138dfa.chunk.js:2
Bu @ VM2793 react.0c138dfa.chunk.js:2
t.hydrate @ VM2793 react.0c138dfa.chunk.js:2
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
w @ VM2849 global_vendors.98dda868.chunk.js:2
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
u @ VM2848 globalShared.ef3d5849.js:formatted:38
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
u @ VM2848 globalShared.ef3d5849.js:formatted:38
t @ VM2848 globalShared.ef3d5849.js:formatted:21
r @ VM2848 globalShared.ef3d5849.js:formatted:12
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
(anonymous) @ header.cdd70f34.chunk.js:formatted:2
VM2778:1 ReferenceError: none is not defined
    at s.value (header.cdd70f34.chunk.js:formatted:2)
    at za (VM2793 react.0c138dfa.chunk.js:2)
    at Da (VM2793 react.0c138dfa.chunk.js:2)
    at yl (VM2793 react.0c138dfa.chunk.js:2)
    at cu (VM2793 react.0c138dfa.chunk.js:2)
    at lu (VM2793 react.0c138dfa.chunk.js:2)
    at Jl (VM2793 react.0c138dfa.chunk.js:2)
    at VM2793 react.0c138dfa.chunk.js:2
    at e.unstable_runWithPriority (VM2797 vendors.a288997f.chunk.js:2)
    at Vo (VM2793 react.0c138dfa.chunk.js:2)
    at Ko (VM2793 react.0c138dfa.chunk.js:2)
    at Wo (VM2793 react.0c138dfa.chunk.js:2)
    at Ql (VM2793 react.0c138dfa.chunk.js:2)
    at Object.enqueueSetState (VM2793 react.0c138dfa.chunk.js:2)
    at d.T.setState (VM2793 react.0c138dfa.chunk.js:2)
    at d.v.safeSetState (VM2849 global_vendors.98dda868.chunk.js:2)
    at VM2849 global_vendors.98dda868.chunk.js:2

...
VM27252:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _u (react.0c138dfa.chunk.js:2)
    at react.0c138dfa.chunk.js:2
    at Ra (react.0c138dfa.chunk.js:2)
    at za (react.0c138dfa.chunk.js:2)
    at Da (react.0c138dfa.chunk.js:2)
    at yl (react.0c138dfa.chunk.js:2)
    at cu (react.0c138dfa.chunk.js:2)
    at lu (react.0c138dfa.chunk.js:2)
    at Jl (react.0c138dfa.chunk.js:2)
    at Ql (react.0c138dfa.chunk.js:2)
    at ju (react.0c138dfa.chunk.js:2)
    at react.0c138dfa.chunk.js:2
    at tu (react.0c138dfa.chunk.js:2)
    at Bu (react.0c138dfa.chunk.js:2)
    at Object.t.hydrate (react.0c138dfa.chunk.js:2)
    at header.6337eb4f.chunk.js:1
    at w (global_vendors.6f9ca896.chunk.js:1)
    at Module.<anonymous> (header.6337eb4f.chunk.js:1)
    at u (VM27333 globalShared.f41ecd4e.js:1)
    at Object.<anonymous> (header.6337eb4f.chunk.js:1)
    at u (VM27333 globalShared.f41ecd4e.js:1)
    at t (VM27333 globalShared.f41ecd4e.js:1)
    at Array.r [as push] (VM27333 globalShared.f41ecd4e.js:1)
    at header.6337eb4f.chunk.js:1
    at header.6337eb4f.chunk.js:1
    at header.6337eb4f.chunk.js:1
```

Now, I tried to switch to development mode for NODE_ENV, you know what : Everything works as expected (common verndor & lazy chunks)even I reverted runtimeChunk config above, continued to be working. 

I am not able to understand what is causing this.

**Comment by evilebottnawi** [comment] 2020-08-24 16:47
@pgangwani update webpack to latest version to avoid `Minified React error #130`

**Comment by pgangwani** [comment] 2020-08-25 15:11
> @pgangwani update webpack to latest version to avoid `Minified React error #130`

I tried 4.44.1, same results
