### ISSUE TITLE
`config.module.rule[].resolve` didn't merge with `config.resolve`

### ISSUE THREAD

**Issue by Airkro** [webpack/webpack#8968] opened 2019-03-26 08:57 UTC
# Bug report

**What is the current behavior?**

### config.module.rule[].resolve not merge with config.resolve

I'm using the `resolve` option in `config.module.rule[]` , because it can be work with  `include` option.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
// webpack.config.js
module.exports = {
  resolve: {
    alias: {
      abc: 'efg'
    }
  },
  module: {
    rules: [
      {
        // use `resolve` in config.module.rule[], then it works.
        include: '/path/to/src',
        resolve: {
          alias: {
            '@': '/path/to/src'
          }
        }
      }
    ]
  }
}
```

**What is the expected behavior?**

alias `@` work perfectly. but alias `abc` not work in `./src/xxxx.js`.

Because `config.module.rule[].resolve` didn't merge with `config.resolve`.

Unless: 
```js
module.exports = {
  resolve: {
    alias: {
      abc: 'efg'
    }
  },
  module: {
    rules: [
      {
        include: '/path/to/src',
        resolve: {
          alias: {
            '@': '/path/to/src',
			abc: 'efg'
          }
        }
      }
    ]
  }
}
```

**Other relevant information:**
webpack version:  4.29.6
Node.js version:  10.15.0
Operating System:  Windows 10
Additional tools:  yarn

**Comment by evilebottnawi** [comment] 2019-03-26 09:00
Not all loader support resolving, please create minimum reproducible test repo, thanks

**Comment by Airkro** [comment] 2019-03-26 09:56
@evilebottnawi 

test repo: https://github.com/Airkro/webpack-resolve-problem

Not work even without any loader. thanks.

**Comment by evilebottnawi** [comment] 2019-03-26 11:11
@Airkro What you expected? Why you add loader?

**Comment by Airkro** [comment] 2019-03-27 02:17
After the release of webpack 4.0, I found this feature in the [changelog](https://github.com/webpack/webpack/releases/tag/v4.0.0) (although it was not found in the documentation).

![image](https://user-images.githubusercontent.com/12206891/55045389-95246a00-5078-11e9-9a84-fb5633460147.png)

I decided to use it because it can be used in conjunction with the `include` option to act on a limited range of code. (Guessing is helpful for speed and security).

For example, many projects use `alias: @ -> path/to/src` . But obviously it doesn't have to work on the code inside `node_modules`.

**Comment by Airkro** [comment] 2019-03-27 02:33
In actual use, I didn't use `loader` in the same `module.rule[]`, but added it after the other `module.rule[]`. 

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: "babel-loader",
            ...
          }
        ]
      },
      {
        include: "/path/to/src",
        resolve: {
          alias: {
            "@": "/path/to/src"
          }
        }
      }
    ]
  }
};
```

Otherwise, I have to copy my `loader` option:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: "/path/to/src",
        use: [
          {
            loader: "babel-loader",
            ...
          }
        ]
      },
      {
        test: /\.js$/,
        include: "/path/to/src",
        resolve: ...,
        use: [
          {
            loader: "babel-loader",
            ...
          }
        ]
      }
    ]
  }
};
```

**Comment by evilebottnawi** [comment] 2019-03-27 09:11
@Airkro I can't understand you, if you use `loader` and want change `resolve` use `resolve` option for `modules.rules`, if you want change global resolving change this in upper `resolver` option (not in loader), i strongly recommend don't use `@` - it is can be part of import like `import '@myorg/package'`

**Comment by evilebottnawi** [comment] 2019-03-27 09:11
@Airkro please provide full reporducible test repo and describe what you have and what you expected

**Comment by Airkro** [comment] 2019-03-27 09:33
Many people use `alias:@`, and they don't want to change that. You can see it in `vue-cli@2.x`.
<https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L40>

Even if I don't use it, it may be other words, it's just an example.

**Comment by evilebottnawi** [comment] 2019-03-27 09:36
@Airkro 

> please provide full reproducible test repo and describe what you have and what you expected

I can't understand what you expected

**Comment by Airkro** [comment] 2019-03-27 10:48
test repo has been updated: https://github.com/Airkro/webpack-resolve-problem

### Q&A

Q: Why do I use the `resolve.alias` option in `modules.rules[]` ?

A: I learned that it is available. So use it with the `include` option to limit its scope.

### Current behaviour

`config.modules.rules[].resolve.alias` is working but `config.resolve.alias` not work any more.

### What I expected

- `config.resolve.alias`
- `config.modules.rules[].resolve.alias`

`webpack` should auto merge them, make them work together?

**Comment by evilebottnawi** [comment] 2019-03-27 10:55
@Airkro without `loader` using `config.modules.rules[].resolve` doesn't has sense and will not merged. What do you want to do? It is really weird.

**Comment by Airkro** [comment] 2019-04-01 08:14
Since you said so, I won't use it without loader anymore.

Even if `loader` is added, it is still not as expected.

example: [[Branch: with-loader]](https://github.com/Airkro/webpack-resolve-problem/tree/with-loader)

**Comment by evilebottnawi** [comment] 2019-04-03 12:32
Yep, looks like a bug, feel free to send a PR

**Comment by sokra** [comment] 2019-04-08 19:08
Yep, many this behavior is a bit weird. Changing this makes sense, but as it's a breaking change we can only do it for the next major.

As workaround copy the alias configuration to the rule, or merge it in config.

**Comment by sokra** [comment] 2019-06-09 12:15
fixed in webpack 5

**Closed by sokra** 2019-06-09 12:15 UTC
Labels: Send a PR, bug
